format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/um7-git.2026.02.000_access-esm1.6-brsjmzl5ftf2cdwiugm4fij5ubaommtp/bin/um_hg3.exe
  hashes:
    binhash: 00c96ac0b28d036e37117ef4c1e54731
    md5: baf41869f02cfc09af01ac438209863d
work/ice/cice_access_360x300_30x300.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/cice5-2026.01.000-3y5cnforztuq3pyqmy45nr5yevao3crj/bin/cice_access_360x300_30x300.exe
  hashes:
    binhash: 3bc247d74219207cdabffca3dcd15c2c
    md5: 440f71b311114a05354d06e5b9b56211
work/ocean/mom5_access_cm:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/mom5-git.2025.05.000_access-esm1.6-4rel6l23pxcht6azxdp5umkedkt36pgg/bin/mom5_access_cm
  hashes:
    binhash: 731e4304e4f06caee26c3139ad381dd1
    md5: e14f6e45df028b73b6793dbc076a8337
