format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/um7-git.2025.12.000_access-esm1.6-yhsp33y3tbwbw3lhoeorzb6szlovz5ko/bin/um_hg3.exe
  hashes:
    binhash: 999c686b2277687f15b32d590eba5f06
    md5: 001141b30d1cf0f0eafe82c708245eea
work/ice/cice_access-esm1.6_360x300_12x1_12p.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/cice5-git.access-esm1.6-2025.11.001_access-esm1.6-wfnrfmludyqwfoxdqabpjgstsnuberty/bin/cice_access-esm1.6_360x300_12x1_12p.exe
  hashes:
    binhash: f3913e61791e9aa135fd08cfdcda8cd6
    md5: 3cc816a6e617150d49435e1afd4657fe
work/ocean/mom5_access_cm:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/mom5-git.2025.05.000_access-esm1.6-e3fa5mlbqica4z44sirp6ps2teieqgms/bin/mom5_access_cm
  hashes:
    binhash: 55d4eb9f8a5e734c1833134b4ecf1095
    md5: b2169db9341f32e4828d1d4b671657d2
