format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/um7-git.2025.12.000_access-esm1.6-d54mlw4de5uvfl6cq5ghdoqznzwmx3wf/bin/um_hg3.exe
  hashes:
    binhash: 9a3a0f201563183e969460aab99f816e
    md5: ec44033b2cf17a21a6cb09de09206318
