format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/um7-git.2025.11.000_access-esm1.6-nwpmrxgu3rst7i3mpucbsyzsbr6nbeqq/bin/um_hg3.exe
  hashes:
    binhash: 4f43750a722b4be2d3c4a9ca650e1f7d
    md5: 38bbaca9e1b13b55d59f0aed5263ffff
work/ice/cice_access-esm1.6_360x300_12x1_12p.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/cice5-git.access-esm1.6-2025.11.001_access-esm1.6-6umbsy5dlepupzm7lxm2ubyb4rsxwetj/bin/cice_access-esm1.6_360x300_12x1_12p.exe
  hashes:
    binhash: 7c99150ca50ce68b1e59d11ca869660e
    md5: 1b2bdff3029668fa3249f69207e2d690
work/ocean/mom5_access_cm:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/mom5-git.2025.05.000_access-esm1.6-tzlv4hwxcbh4u2alvbiwnpnxjg67crnu/bin/mom5_access_cm
  hashes:
    binhash: c54fa44a8d0c20975b42bdd915ff7bef
    md5: 8e404189b0972fb1beb916ed0dcba88c
