format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/um7-git.2025.12.000_access-esm1.6-n4khgi6wnko6nn2wzqqk4575wetqbyjx/bin/um_hg3.exe
  hashes:
    binhash: 4d919699451f3a66650390b1d7f8c321
    md5: 77e66471e73ae272e6b548f2bc5f2794
work/ice/cice_access-esm1.6_360x300_12x1_12p.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/cice5-git.access-esm1.6-2025.11.001_access-esm1.6-6umbsy5dlepupzm7lxm2ubyb4rsxwetj/bin/cice_access-esm1.6_360x300_12x1_12p.exe
  hashes:
    binhash: 7c99150ca50ce68b1e59d11ca869660e
    md5: 1b2bdff3029668fa3249f69207e2d690
work/ocean/mom5_access_cm:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/mom5-git.2025.05.000_access-esm1.6-tzlv4hwxcbh4u2alvbiwnpnxjg67crnu/bin/mom5_access_cm
  hashes:
    binhash: c54fa44a8d0c20975b42bdd915ff7bef
    md5: 8e404189b0972fb1beb916ed0dcba88c
