format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/um7-git.access-esm1.6-2025.09.000_access-esm1.6-s7ckahfudhpeh547lksszvuqt44usnq3/bin/um_hg3.exe
  hashes:
    binhash: 6f8b323ac3b87cc25dce32cf14b90188
    md5: 5580604dab9ed80b2f869fde88bb3603
work/ice/cice_access-esm1.6_360x300_12x1_12p.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/cice5-git.access-esm1.6-2025.11.001_access-esm1.6-6umbsy5dlepupzm7lxm2ubyb4rsxwetj/bin/cice_access-esm1.6_360x300_12x1_12p.exe
  hashes:
    binhash: 7c99150ca50ce68b1e59d11ca869660e
    md5: 1b2bdff3029668fa3249f69207e2d690
work/ocean/mom5_access_cm:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/mom5-git.2025.05.000_access-esm1.6-q7acqikepkutcdxofim77qzjbul2lkc7/bin/mom5_access_cm
  hashes:
    binhash: bbe76179c6b55a7f83c8aeef8a44927b
    md5: 70f590d05f1a582dff3dd458a3f9c296
