format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/um7-git.2025.11.000_access-esm1.6-nwpmrxgu3rst7i3mpucbsyzsbr6nbeqq/bin/um_hg3.exe
  hashes:
    binhash: 4f43750a722b4be2d3c4a9ca650e1f7d
    md5: 38bbaca9e1b13b55d59f0aed5263ffff