format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/um7-git.2026.02.000_access-esm1.6-brsjmzl5ftf2cdwiugm4fij5ubaommtp/bin/um_hg3.exe
  hashes:
    binhash: 00c96ac0b28d036e37117ef4c1e54731
    md5: baf41869f02cfc09af01ac438209863d
