format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /g/data/vk83/apps/spack/0.22/restricted/ukmo/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/um7-git.2025.12.000_access-esm1.6-n4khgi6wnko6nn2wzqqk4575wetqbyjx/bin/um_hg3.exe
  hashes:
    binhash: 4d919699451f3a66650390b1d7f8c321
    md5: 77e66471e73ae272e6b548f2bc5f2794