format: yamanifest
version: 1.0
---
work/atmosphere/INPUT/ACCESS_vegfrac_LUH3_states_withAusPFTs_1850-2023_v7-transposed.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/amip/atmosphere/land/vegetation/global.N96/2025.11.25/ACCESS_vegfrac_LUH3_states_withAusPFTs_1850-2023_v7-transposed.nc
  hashes:
    binhash: a22f8247bfe47d9f8cea67f73a1d7657
    md5: 91e2f9f2ac9e7e6ed308cd414ee78ef2
work/atmosphere/INPUT/BC_hi_1849_2015_ESM1.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/atmosphere/aerosol/global.N96/2021.06.22/BC_hi_1849_2015_ESM1.anc
  hashes:
    binhash: 77ecb24ca0aada9ea3871fa17eb9ffc9
    md5: f16cdb65e5d35103b1d7b7f45abcfffa
work/atmosphere/INPUT/Bio_1849_2015_ESM1.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/atmosphere/aerosol/global.N96/2021.06.22/Bio_1849_2015_ESM1.anc
  hashes:
    binhash: 3d1bbeea23f49ee75e7cc9c0f41c9db5
    md5: fb650ff10a39596b92f67b1393c15289
work/atmosphere/INPUT/DMS_conc.N96:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/DMS_conc.N96
  hashes:
    binhash: da1baa25e78ec281c82ea4588e30a340
    md5: 7e8ec8de832c0b9b8c1d9f0eda4d54e5
work/atmosphere/INPUT/Ndep_1849_2015.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/atmosphere/land/biogeochemistry/global.N96/2021.06.22/Ndep_1849_2015.anc
  hashes:
    binhash: 70379cea8570223286b661347b720b39
    md5: ff75533e9f52d92c42ac3556b4ec1fed
work/atmosphere/INPUT/OCFF_1849_2015_ESM1.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/atmosphere/aerosol/global.N96/2021.06.22/OCFF_1849_2015_ESM1.anc
  hashes:
    binhash: c80d56183157d220322253672fc9198b
    md5: 1e38cac3a03101fb5aa5d88c713e809c
work/atmosphere/INPUT/STASHmaster/README:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/STASHmaster/README
  hashes:
    binhash: 01e4a19f6616aaa0aeb3a41965a6be9d
    md5: 4b9b721b80b3a2e1d292cdab756f14a5
work/atmosphere/INPUT/STASHmaster/STASHmaster_A:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/STASHmaster/STASHmaster_A
  hashes:
    binhash: c4f0b8856159cca024b69f03443d1176
    md5: d257ddb7a98b882c3ac492f408df7793
work/atmosphere/INPUT/STASHmaster/STASHmaster_O:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/STASHmaster/STASHmaster_O
  hashes:
    binhash: 1a82f824556c2da2f712ec1271fde2cf
    md5: 5a65d77c62d55e3b62e35ad9662d32a9
work/atmosphere/INPUT/STASHmaster/STASHmaster_S:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/STASHmaster/STASHmaster_S
  hashes:
    binhash: dd55b55f5cce7bd9442bb6d194a85c93
    md5: 85ff5d563968cf24d1be595b05b4e52d
work/atmosphere/INPUT/STASHmaster/STASHmaster_W:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/STASHmaster/STASHmaster_W
  hashes:
    binhash: 7be6a163341f49473d8179f183609a4e
    md5: 1e4391ea1f6234b33c33168bd7089d06
work/atmosphere/INPUT/STASHmaster/STASHsections_A:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/STASHmaster/STASHsections_A
  hashes:
    binhash: afb52507011158a9ae30fb368d06f2c2
    md5: 8525fd107dbea6184db74089f1d55fd9
work/atmosphere/INPUT/TSI_CMIP7_ESM:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/atmosphere/forcing/resolution_independent/2025.11.25/TSI_CMIP7_ESM
  hashes:
    binhash: 61204ba958920f80aefa03c4689834e3
    md5: 635295693e07ae1079753d0835a6ad07
work/atmosphere/INPUT/amip_seaice_n96_greg.pp:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p5/modern/amip/atmosphere/boundary_conditions/global.N96/2021.07.08/amip_seaice_n96_greg.pp
  hashes:
    binhash: 81345cbc844a887e5eea04687dcc1e1c
    md5: dee51bc6417e99297d70e557ac52632a
work/atmosphere/INPUT/amip_sst_n96_greg.pp:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p5/modern/amip/atmosphere/boundary_conditions/global.N96/2021.07.08/amip_sst_n96_greg.pp
  hashes:
    binhash: c0268c388a150ceea10adbaa74c82fdc
    md5: 47368fc3565d554200b0f1fe78e79416
work/atmosphere/INPUT/biogenic_351sm.N96L38:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/biogenic_351sm.N96L38
  hashes:
    binhash: 35f8585c3290dfc25ed19e7d93f6a1bb
    md5: 55eb75f602a4639fb3c8ff40e36eb661
work/atmosphere/INPUT/cable_vegfunc_N96.anc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/land/vegetation/global.N96/2025.08.29/cable_vegfunc_N96.anc
  hashes:
    binhash: 6463172e2ec728967ec86f0cb4ba50a3
    md5: d36f7104db31c372fbbf1cdc90a4e4f4
work/atmosphere/INPUT/modis_phenology_csiro_13evergreen.txt:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/land/biogeochemistry/resolution_independent/2025.08.29/modis_phenology_csiro_13evergreen.txt
  hashes:
    binhash: 9062c9c2e90980bce48ea7c7046d512d
    md5: c8f344d7371949fb6aac7f71e1e003d6
work/atmosphere/INPUT/ozone_1849_2015_ESM1.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/atmosphere/forcing/global.N96/2021.06.22/ozone_1849_2015_ESM1.anc
  hashes:
    binhash: d0f4f5fa148594a325854548f84b82eb
    md5: b85f5374d1b89cf23cff05b6c35c4d0f
work/atmosphere/INPUT/pftlookup_cable3_OctB_update.csv:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/land/biogeochemistry/resolution_independent/2025.11.18/pftlookup_cable3_OctB_update.csv
  hashes:
    binhash: 9c4c143d53559b2ac70ea8eb37af48c2
    md5: bf80c75ce38f147dd46323323d3039e2
work/atmosphere/INPUT/scycl_1849_2015_ESM1_v4.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/atmosphere/aerosol/global.N96/2021.06.22/scycl_1849_2015_ESM1_v4.anc
  hashes:
    binhash: aa9156fbc9be897ba7e9f32ad0b267e3
    md5: 66ef33e0d38eb1a9f550766c1952a252
work/atmosphere/INPUT/spec3a_lw_hadgem1_6on:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/spectral/resolution_independent/2020.05.19/spec3a_lw_hadgem1_6on
  hashes:
    binhash: 278569974348c9583fe0a2a9e1828ffd
    md5: 9ff85916dbb36ba6679b954d16387aee
work/atmosphere/INPUT/spec3a_sw_hadgem1_6on:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/spectral/resolution_independent/2020.05.19/spec3a_sw_hadgem1_6on
  hashes:
    binhash: 149899ecc54ed754ab8c6f05cb99f140
    md5: 0e74c13cf3333132f38d8c5c52e1c7eb
work/atmosphere/INPUT/stasets/X01001218:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01001218
  hashes:
    binhash: 4a2fcf832b7f8a1af9be58a81cae5ce3
    md5: 7293caa27798d235bd5520eede9700fb
work/atmosphere/INPUT/stasets/X01002207:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01002207
  hashes:
    binhash: 33a0eba5237db140fa882a18a40c7857
    md5: 448daeebba685950d0c347d0493b5fc4
work/atmosphere/INPUT/stasets/X01003236:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003236
  hashes:
    binhash: aafd86926894f4594c6062a495c0fa0e
    md5: 71a2288ee0a7d0fc89dafe95653c128a
work/atmosphere/INPUT/stasets/X01003237:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003237
  hashes:
    binhash: 1bb68e38a6084c8a2767bd6893603d3e
    md5: 4efd39ac9a917525bbc35146d6770e3b
work/atmosphere/INPUT/stasets/X01003254:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003254
  hashes:
    binhash: 207f67096815d4664ac7982648b8d8f1
    md5: 1b5f7755f752c2ee2086ac6eba886ca3
work/atmosphere/INPUT/stasets/X01003255:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003255
  hashes:
    binhash: 3cea8088b0d54e4597c0741441787cfb
    md5: f23a78b048f0cb52ed0e2beb57f00fa8
work/atmosphere/INPUT/stasets/X01003274:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003274
  hashes:
    binhash: f856ed8d2d0ff403ffa9e94dfe0c8fb2
    md5: 032190f23c926eb47199da6e1f054bf1
work/atmosphere/INPUT/stasets/X01003275:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003275
  hashes:
    binhash: 29ac8a8f7e754036d1abbfc9029b4a32
    md5: 120694f3d078b9ade033b56217e9ed85
work/atmosphere/INPUT/stasets/X01003276:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003276
  hashes:
    binhash: 43c3ac834df0358c81f6221396068c95
    md5: 61afb6eb4e76efb2171c56d02742e9ad
work/atmosphere/INPUT/stasets/X01003277:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003277
  hashes:
    binhash: 6238e630892522b0f46acd3e1d44fda0
    md5: d8cced93214dd8e84c0c9d06259412ab
work/atmosphere/INPUT/stasets/X01003278:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003278
  hashes:
    binhash: e935ca61d8b752d7d093c64acca24e97
    md5: 032190f23c926eb47199da6e1f054bf1
work/atmosphere/INPUT/stasets/X01003279:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003279
  hashes:
    binhash: 6af3413a4e20a6c7886c9da83b29a406
    md5: 120694f3d078b9ade033b56217e9ed85
work/atmosphere/INPUT/stasets/X01003280:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003280
  hashes:
    binhash: 99f55e386151a5dd2a088896fc4a6ca0
    md5: 61afb6eb4e76efb2171c56d02742e9ad
work/atmosphere/INPUT/stasets/X01003281:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003281
  hashes:
    binhash: c79daa736f08def365936f862885cde0
    md5: d8cced93214dd8e84c0c9d06259412ab
work/atmosphere/INPUT/stasets/X01003286:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01003286
  hashes:
    binhash: f9521fa75f35a1560427898f8af88337
    md5: 062ab130605e4771a89b2a300a6154bf
work/atmosphere/INPUT/stasets/X01005207:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01005207
  hashes:
    binhash: 6b6a12743ac6963e668640cb9e98f0e5
    md5: 3d1ccb47257c379b909e8d6098ab95a0
work/atmosphere/INPUT/stasets/X01005208:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01005208
  hashes:
    binhash: defb4bb479a4d78f81652f3413ad03ee
    md5: 8685052394200b839f115a667e7890ff
work/atmosphere/INPUT/stasets/X01005222:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01005222
  hashes:
    binhash: ad2c3364e969423021abe903e5d82aae
    md5: 3edd8e46166dbed4102c329991a7a497
work/atmosphere/INPUT/stasets/X01005223:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01005223
  hashes:
    binhash: e4785752007a33ac800835988d38a2e6
    md5: 4633fea316272fd71cd823881d100c14
work/atmosphere/INPUT/stasets/X01010206:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2025.12.19/stasets/X01010206
  hashes:
    binhash: 2a115dffeeb330f2809743d264fd2455
    md5: 7d5e82e70a2f3936743eb957462d41aa
work/atmosphere/INPUT/sulpc_oxidants_N96_L38:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/sulpc_oxidants_N96_L38
  hashes:
    binhash: e8b31e6ca1af7da756d87243e622e3c8
    md5: 7c42d1faf74b2b9f6819f2349a8d0d25
work/atmosphere/INPUT/volcts_cmip6.dat:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/atmosphere/forcing/resolution_independent/2021.06.22/volcts_cmip6.dat
  hashes:
    binhash: a041386af6706dc7cb9e96816bf8f234
    md5: 9fa4ef9fbc7c86cebd22980e73347f67
