format: yamanifest
version: 1.0
---
work/atmosphere/INPUT/ACCESS_vegfrac_LUH3_states_withAusPFTs_1850-2023_v7-transposed.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/amip/atmosphere/land/vegetation/global.N96/2025.11.25/ACCESS_vegfrac_LUH3_states_withAusPFTs_1850-2023_v7-transposed.nc
  hashes:
    binhash: a22f8247bfe47d9f8cea67f73a1d7657
    md5: 91e2f9f2ac9e7e6ed308cd414ee78ef2
work/atmosphere/INPUT/BC_1849_2023_cmip7.anc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/atmosphere/aerosol/global.N96/2025.12.19/BC_1849_2023_cmip7.anc
  hashes:
    binhash: 913c40b516de049a3223f30f52171851
    md5: e9aad4c541ec37f5403bd75ba207ccd7
work/atmosphere/INPUT/Bio_1849_2015_ESM1.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/atmosphere/aerosol/global.N96/2021.06.22/Bio_1849_2015_ESM1.anc
  hashes:
    binhash: 3d1bbeea23f49ee75e7cc9c0f41c9db5
    md5: fb650ff10a39596b92f67b1393c15289
work/atmosphere/INPUT/Bio_1849_2023_cmip7.anc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/atmosphere/aerosol/global.N96/2025.12.19/Bio_1849_2023_cmip7.anc
  hashes:
    binhash: 4e9b55ca691d84a0f2a194c10c02789c
    md5: 7d593fe0f4f90999fba705ad022a1df0
work/atmosphere/INPUT/DMS_conc.N96:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/DMS_conc.N96
  hashes:
    binhash: da1baa25e78ec281c82ea4588e30a340
    md5: 7e8ec8de832c0b9b8c1d9f0eda4d54e5
work/atmosphere/INPUT/Ndep_1849_2023_cmip7.anc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/atmosphere/land/biogeochemistry/global.N96/2025.12.19/Ndep_1849_2023_cmip7.anc
  hashes:
    binhash: d08c04b2029058c9368c49fc58ede86e
    md5: 634b2d78d0ae02b5a425b29a20f67f2c
work/atmosphere/INPUT/OCFF_1849_2023_cmip7.anc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/atmosphere/aerosol/global.N96/2025.12.19/OCFF_1849_2023_cmip7.anc
  hashes:
    binhash: 87e11cdf24eccfb2166e849a818ca909
    md5: 0be90f4ac9c50ad3c5b70388cd4f9fd6
work/atmosphere/INPUT/STASHmaster/README:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/STASHmaster/README
  hashes:
    binhash: dd48aaec06d8a65d764c0595b6748f03
    md5: 68d47be694979b827a9f68088d8d5800
work/atmosphere/INPUT/STASHmaster/STASHmaster_A:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/STASHmaster/STASHmaster_A
  hashes:
    binhash: 69257dc3199aee9b47c48ad2a532cd9e
    md5: 808dac1f259bf3e3fb468462ccbbee81
work/atmosphere/INPUT/STASHmaster/STASHmaster_O:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/STASHmaster/STASHmaster_O
  hashes:
    binhash: 76c188f1b29929a1a4cfc66a2a1bde93
    md5: 5a65d77c62d55e3b62e35ad9662d32a9
work/atmosphere/INPUT/STASHmaster/STASHmaster_S:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/STASHmaster/STASHmaster_S
  hashes:
    binhash: e10f471a240cbb6ab47d9941850ae31a
    md5: 85ff5d563968cf24d1be595b05b4e52d
work/atmosphere/INPUT/STASHmaster/STASHmaster_W:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/STASHmaster/STASHmaster_W
  hashes:
    binhash: c131e6e7d9b00472b083b4290644341e
    md5: 1e4391ea1f6234b33c33168bd7089d06
work/atmosphere/INPUT/STASHmaster/STASHsections_A:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/STASHmaster/STASHsections_A
  hashes:
    binhash: 2af3017149d587a0ba600d22024f7c0f
    md5: 8525fd107dbea6184db74089f1d55fd9
work/atmosphere/INPUT/TSI_CMIP7_ESM:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/atmosphere/forcing/resolution_independent/2025.11.25/TSI_CMIP7_ESM
  hashes:
    binhash: 61204ba958920f80aefa03c4689834e3
    md5: 635295693e07ae1079753d0835a6ad07
work/atmosphere/INPUT/amip_seaice_n96_greg.pp:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p5/modern/amip/atmosphere/boundary_conditions/global.N96/2021.07.08/amip_seaice_n96_greg.pp
  hashes:
    binhash: 81345cbc844a887e5eea04687dcc1e1c
    md5: dee51bc6417e99297d70e557ac52632a
work/atmosphere/INPUT/amip_sst_n96_greg.pp:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p5/modern/amip/atmosphere/boundary_conditions/global.N96/2021.07.08/amip_sst_n96_greg.pp
  hashes:
    binhash: c0268c388a150ceea10adbaa74c82fdc
    md5: 47368fc3565d554200b0f1fe78e79416
work/atmosphere/INPUT/biogenic_351sm.N96L38:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/biogenic_351sm.N96L38
  hashes:
    binhash: 35f8585c3290dfc25ed19e7d93f6a1bb
    md5: 55eb75f602a4639fb3c8ff40e36eb661
work/atmosphere/INPUT/cable_vegfunc_N96.anc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/land/vegetation/global.N96/2025.08.29/cable_vegfunc_N96.anc
  hashes:
    binhash: 6463172e2ec728967ec86f0cb4ba50a3
    md5: d36f7104db31c372fbbf1cdc90a4e4f4
work/atmosphere/INPUT/modis_phenology_csiro_13evergreen.txt:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/land/biogeochemistry/resolution_independent/2025.08.29/modis_phenology_csiro_13evergreen.txt
  hashes:
    binhash: 9062c9c2e90980bce48ea7c7046d512d
    md5: c8f344d7371949fb6aac7f71e1e003d6
work/atmosphere/INPUT/ozone_1849_2015_ESM1.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/atmosphere/forcing/global.N96/2021.06.22/ozone_1849_2015_ESM1.anc
  hashes:
    binhash: d0f4f5fa148594a325854548f84b82eb
    md5: b85f5374d1b89cf23cff05b6c35c4d0f
work/atmosphere/INPUT/pftlookup_cable3_Pfix.csv:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/land/biogeochemistry/resolution_independent/2026.02.10/pftlookup_cable3_Pfix.csv
  hashes:
    binhash: a8d18513f014fe1fb4d57f36f9a53321
    md5: d9a4d71ee8038029739c23a1b829ab6a
work/atmosphere/INPUT/scycl_1849_2023_cmip7.anc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/atmosphere/aerosol/global.N96/2025.12.19/scycl_1849_2023_cmip7.anc
  hashes:
    binhash: 8883058894d3b9f00fa5320345371743
    md5: 297ba35db320ff7ca8041cb2f014f88f
work/atmosphere/INPUT/spec3a_lw_hadgem1_6on:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/spectral/resolution_independent/2020.05.19/spec3a_lw_hadgem1_6on
  hashes:
    binhash: 278569974348c9583fe0a2a9e1828ffd
    md5: 9ff85916dbb36ba6679b954d16387aee
work/atmosphere/INPUT/spec3a_sw_hadgem1_6on:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/spectral/resolution_independent/2020.05.19/spec3a_sw_hadgem1_6on
  hashes:
    binhash: 149899ecc54ed754ab8c6f05cb99f140
    md5: 0e74c13cf3333132f38d8c5c52e1c7eb
work/atmosphere/INPUT/stasets/X01001218:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01001218
  hashes:
    binhash: e5c100e78082bd07ea0d5d299a973356
    md5: 7293caa27798d235bd5520eede9700fb
work/atmosphere/INPUT/stasets/X01002207:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01002207
  hashes:
    binhash: 50a73eef1f79b1449325dbf7e40cb579
    md5: 448daeebba685950d0c347d0493b5fc4
work/atmosphere/INPUT/stasets/X01003236:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003236
  hashes:
    binhash: 5630ac65d4e2a72e68fd693559d60f72
    md5: 71a2288ee0a7d0fc89dafe95653c128a
work/atmosphere/INPUT/stasets/X01003237:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003237
  hashes:
    binhash: 61c20338fd23e02926d12cb21b1ad17d
    md5: 4efd39ac9a917525bbc35146d6770e3b
work/atmosphere/INPUT/stasets/X01003254:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003254
  hashes:
    binhash: 8a1daadc09eae1018a72273320e7b576
    md5: 1b5f7755f752c2ee2086ac6eba886ca3
work/atmosphere/INPUT/stasets/X01003255:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003255
  hashes:
    binhash: 05f279a0fede7a9d5f9cab5b34678567
    md5: f23a78b048f0cb52ed0e2beb57f00fa8
work/atmosphere/INPUT/stasets/X01003274:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003274
  hashes:
    binhash: e21b1e2f8504cdfc2a366becdf0c143d
    md5: 032190f23c926eb47199da6e1f054bf1
work/atmosphere/INPUT/stasets/X01003275:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003275
  hashes:
    binhash: 6f0991ba269c7fd2eef285c844a5eae6
    md5: 120694f3d078b9ade033b56217e9ed85
work/atmosphere/INPUT/stasets/X01003276:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003276
  hashes:
    binhash: ed36f30479fd39213deb3e5c32fae431
    md5: 61afb6eb4e76efb2171c56d02742e9ad
work/atmosphere/INPUT/stasets/X01003277:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003277
  hashes:
    binhash: 447fd0016956c4ab1920d68426acd77a
    md5: d8cced93214dd8e84c0c9d06259412ab
work/atmosphere/INPUT/stasets/X01003278:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003278
  hashes:
    binhash: 46d73862b86b80866a94e3d6bbcabc83
    md5: 032190f23c926eb47199da6e1f054bf1
work/atmosphere/INPUT/stasets/X01003279:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003279
  hashes:
    binhash: f5f44da1995cbb07755dbc3012f066e2
    md5: 120694f3d078b9ade033b56217e9ed85
work/atmosphere/INPUT/stasets/X01003280:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003280
  hashes:
    binhash: b9f346dae64f793b24844f4ff5f90a12
    md5: 61afb6eb4e76efb2171c56d02742e9ad
work/atmosphere/INPUT/stasets/X01003281:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003281
  hashes:
    binhash: 2216fb97ea72cb8056b985732853d3e4
    md5: d8cced93214dd8e84c0c9d06259412ab
work/atmosphere/INPUT/stasets/X01003286:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01003286
  hashes:
    binhash: 58e976a5d2780b10f92d0d925363da0b
    md5: 062ab130605e4771a89b2a300a6154bf
work/atmosphere/INPUT/stasets/X01005207:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01005207
  hashes:
    binhash: 936fa5a2a4185914412b4d3377805854
    md5: 3d1ccb47257c379b909e8d6098ab95a0
work/atmosphere/INPUT/stasets/X01005208:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01005208
  hashes:
    binhash: 894598be8f19e566e523022875949962
    md5: 8685052394200b839f115a667e7890ff
work/atmosphere/INPUT/stasets/X01005222:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01005222
  hashes:
    binhash: 87367a6d692826d2343926c4a4e688c5
    md5: 3edd8e46166dbed4102c329991a7a497
work/atmosphere/INPUT/stasets/X01005223:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01005223
  hashes:
    binhash: 2a6d7ff04dcf89c2241ae1df46129db4
    md5: 4633fea316272fd71cd823881d100c14
work/atmosphere/INPUT/stasets/X01010206:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/stash/2026.01.21/stasets/X01010206
  hashes:
    binhash: 96a108bea8d960fa65987115a58621eb
    md5: 7d5e82e70a2f3936743eb957462d41aa
work/atmosphere/INPUT/sulpc_oxidants_N96_L38:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/sulpc_oxidants_N96_L38
  hashes:
    binhash: e8b31e6ca1af7da756d87243e622e3c8
    md5: 7c42d1faf74b2b9f6819f2349a8d0d25
work/atmosphere/INPUT/volcts_cmip7.dat:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/atmosphere/forcing/resolution_independent/2025.12.01/volcts_cmip7.dat
  hashes:
    binhash: 7af83bb201b6b22a4d7735c41061f509
    md5: 89a3d931712da3805369894e068280b3
