format: yamanifest
version: 1.0
---
work/atmosphere/INPUT/BC_1850_cmip7.anc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/atmosphere/aerosol/global.N96/2025.06.04/BC_1850_cmip7.anc
  hashes:
    binhash: 1b813f612ec0c46bddb8d1c41dc4cc46
    md5: 72eac6922e418ad1da3756cd118c80b2
work/atmosphere/INPUT/Bio_1850_cmip7.anc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/atmosphere/aerosol/global.N96/2025.06.04/Bio_1850_cmip7.anc
  hashes:
    binhash: 89287284b946f3165d2d0d0517572e50
    md5: 9c7af32c6d35a0ecbaa99026bd57943f
work/atmosphere/INPUT/DMS_conc.N96:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/DMS_conc.N96
  hashes:
    binhash: da1baa25e78ec281c82ea4588e30a340
    md5: 7e8ec8de832c0b9b8c1d9f0eda4d54e5
work/atmosphere/INPUT/Ndep_1850_ESM1.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/atmosphere/land/biogeochemistry/global.N96/2020.05.19/Ndep_1850_ESM1.anc
  hashes:
    binhash: 47374849ef42f83e3c02629827a482ee
    md5: 48462cfa1aeed200c3b8d0bf1b49654a
work/atmosphere/INPUT/OCFF_1850_cmip7.anc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/atmosphere/aerosol/global.N96/2025.06.04/OCFF_1850_cmip7.anc
  hashes:
    binhash: 7ac76d91223e2e1cab68c331ad7b6547
    md5: 6bceddebc7b0c2ebeea3be8b4c0f13e8
work/atmosphere/INPUT/STASHmaster/STASHmaster_A:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/STASHmaster/STASHmaster_A
  hashes:
    binhash: 4f75001536d84c87362b607aa42c4f61
    md5: 74cbbb76edfbd9f7c4b928609c00cd64
work/atmosphere/INPUT/STASHmaster/STASHmaster_A.original:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/STASHmaster/STASHmaster_A.original
  hashes:
    binhash: c7d3efdc2ca645724064afc4f7e655f6
    md5: ed1004d9aca8d29baba143ea12defbb7
work/atmosphere/INPUT/STASHmaster/STASHmaster_O:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/STASHmaster/STASHmaster_O
  hashes:
    binhash: 763bf187687a18a505264b4b79d40153
    md5: 5a65d77c62d55e3b62e35ad9662d32a9
work/atmosphere/INPUT/STASHmaster/STASHmaster_S:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/STASHmaster/STASHmaster_S
  hashes:
    binhash: 6d6eb7e1e0f21e635e532202f7b8d462
    md5: 85ff5d563968cf24d1be595b05b4e52d
work/atmosphere/INPUT/STASHmaster/STASHmaster_W:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/STASHmaster/STASHmaster_W
  hashes:
    binhash: 919a2c8987bd593c78153ff323efeb51
    md5: 1e4391ea1f6234b33c33168bd7089d06
work/atmosphere/INPUT/STASHmaster/STASHsections_A:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/STASHmaster/STASHsections_A
  hashes:
    binhash: 9401083e4199439b77254fc490b6597d
    md5: 8525fd107dbea6184db74089f1d55fd9
work/atmosphere/INPUT/biogenic_351sm.N96L38:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/biogenic_351sm.N96L38
  hashes:
    binhash: 35f8585c3290dfc25ed19e7d93f6a1bb
    md5: 55eb75f602a4639fb3c8ff40e36eb661
work/atmosphere/INPUT/cable_vegfunc_N96.anc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/land/vegetation/global.N96/2025.08.29/cable_vegfunc_N96.anc
  hashes:
    binhash: 6463172e2ec728967ec86f0cb4ba50a3
    md5: d36f7104db31c372fbbf1cdc90a4e4f4
work/atmosphere/INPUT/modis_phenology_csiro_13evergreen.txt:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/land/biogeochemistry/resolution_independent/2025.08.29/modis_phenology_csiro_13evergreen.txt
  hashes:
    binhash: 9062c9c2e90980bce48ea7c7046d512d
    md5: c8f344d7371949fb6aac7f71e1e003d6
work/atmosphere/INPUT/ozone_1850_ESM1.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/atmosphere/forcing/global.N96/2020.05.19/ozone_1850_ESM1.anc
  hashes:
    binhash: 7e82d4a83bf18e59277f026cbbee4c74
    md5: a64a01e3b092085fca308524a75a1cee
work/atmosphere/INPUT/pftlookup_cable3_1213_exp6_c4crop.csv:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/share/atmosphere/land/biogeochemistry/resolution_independent/2025.08.29/pftlookup_cable3_1213_exp6_c4crop.csv
  hashes:
    binhash: 28cb640d1f82c866fb2da732ee61a018
    md5: c67bdd681339f6d9c72223f9f8aaf1b7
work/atmosphere/INPUT/qrparm.mask:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/grids/global.N96/2020.05.19/qrparm.mask
  hashes:
    binhash: 6d189a763e3418d2cf61581eded5522e
    md5: f497c7827bd22ef0b98f1d1af776866d
work/atmosphere/INPUT/qrparm.soil_igbp_vg:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/land/soiltype/global.N96/2020.05.19/qrparm.soil_igbp_vg
  hashes:
    binhash: 51560dde970f7123a7250cc6bdc8f3ef
    md5: 26ce57f462dd574fe49f290ab7877112
work/atmosphere/INPUT/scycl_1850_cmip7.anc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/atmosphere/aerosol/global.N96/2025.06.04/scycl_1850_cmip7.anc
  hashes:
    binhash: a338723ccb4fd879c443516e844c7198
    md5: 46c41f2683230a383bd7fb1face49203
work/atmosphere/INPUT/spec3a_lw_hadgem1_6on:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/spectral/resolution_independent/2020.05.19/spec3a_lw_hadgem1_6on
  hashes:
    binhash: 278569974348c9583fe0a2a9e1828ffd
    md5: 9ff85916dbb36ba6679b954d16387aee
work/atmosphere/INPUT/spec3a_sw_hadgem1_6on:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/spectral/resolution_independent/2020.05.19/spec3a_sw_hadgem1_6on
  hashes:
    binhash: 149899ecc54ed754ab8c6f05cb99f140
    md5: 0e74c13cf3333132f38d8c5c52e1c7eb
work/atmosphere/INPUT/stasets/X01001218:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01001218
  hashes:
    binhash: cef321aa4d4eeae2d156db854ce276c4
    md5: 7293caa27798d235bd5520eede9700fb
work/atmosphere/INPUT/stasets/X01002207:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01002207
  hashes:
    binhash: 4e7a1dc7a52a0aab1da67b9328510fb5
    md5: 448daeebba685950d0c347d0493b5fc4
work/atmosphere/INPUT/stasets/X01003236:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003236
  hashes:
    binhash: 5cdf6aea7e61410df48d3cac8469454d
    md5: 71a2288ee0a7d0fc89dafe95653c128a
work/atmosphere/INPUT/stasets/X01003237:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003237
  hashes:
    binhash: 883c4ddd6d137ac441bf6c045c8a1c39
    md5: 4efd39ac9a917525bbc35146d6770e3b
work/atmosphere/INPUT/stasets/X01003254:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003254
  hashes:
    binhash: e6db920da74cdf06c3c32053d778e9f3
    md5: 1b5f7755f752c2ee2086ac6eba886ca3
work/atmosphere/INPUT/stasets/X01003255:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003255
  hashes:
    binhash: 9b804470b184c2e3a143a64314b4baf3
    md5: f23a78b048f0cb52ed0e2beb57f00fa8
work/atmosphere/INPUT/stasets/X01003274:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003274
  hashes:
    binhash: a999c69b36a2f7d183e8b9fce0b17dba
    md5: 032190f23c926eb47199da6e1f054bf1
work/atmosphere/INPUT/stasets/X01003275:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003275
  hashes:
    binhash: 24c47dd90d0a17b6fa81e48133f310e3
    md5: 120694f3d078b9ade033b56217e9ed85
work/atmosphere/INPUT/stasets/X01003276:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003276
  hashes:
    binhash: 9c8d8aa71ac65ee098ac3a50f00007c3
    md5: 61afb6eb4e76efb2171c56d02742e9ad
work/atmosphere/INPUT/stasets/X01003277:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003277
  hashes:
    binhash: da58ccbd06fe6cf6987f8eef37590c70
    md5: d8cced93214dd8e84c0c9d06259412ab
work/atmosphere/INPUT/stasets/X01003278:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003278
  hashes:
    binhash: 5a899ad334e42cc3cdd1ab14429299ed
    md5: 032190f23c926eb47199da6e1f054bf1
work/atmosphere/INPUT/stasets/X01003279:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003279
  hashes:
    binhash: a43fcc064f100a634326d53110ab8fe2
    md5: 120694f3d078b9ade033b56217e9ed85
work/atmosphere/INPUT/stasets/X01003280:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003280
  hashes:
    binhash: 05b3ac5c90fdf71e906e3b6e0dcf3329
    md5: 61afb6eb4e76efb2171c56d02742e9ad
work/atmosphere/INPUT/stasets/X01003281:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003281
  hashes:
    binhash: 990649b208fa059df477aef96d2242a0
    md5: d8cced93214dd8e84c0c9d06259412ab
work/atmosphere/INPUT/stasets/X01003286:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01003286
  hashes:
    binhash: 731b64153656addbd7bd29b98e60906a
    md5: 062ab130605e4771a89b2a300a6154bf
work/atmosphere/INPUT/stasets/X01005207:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01005207
  hashes:
    binhash: 52ae55398cdcdf5582bd6253755c5185
    md5: 3d1ccb47257c379b909e8d6098ab95a0
work/atmosphere/INPUT/stasets/X01005208:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01005208
  hashes:
    binhash: 4d114e56511e247ca65b4bd79cd66437
    md5: 8685052394200b839f115a667e7890ff
work/atmosphere/INPUT/stasets/X01005222:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01005222
  hashes:
    binhash: 115879288e4fe41cf3aa936793597f0a
    md5: 3edd8e46166dbed4102c329991a7a497
work/atmosphere/INPUT/stasets/X01005223:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01005223
  hashes:
    binhash: b0707253914846f3a526030c52a818fe
    md5: 4633fea316272fd71cd823881d100c14
work/atmosphere/INPUT/stasets/X01010206:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/stash/2020.05.19/stasets/X01010206
  hashes:
    binhash: a7c6cf46b049f520547eab48654687ad
    md5: 7d5e82e70a2f3936743eb957462d41aa
work/atmosphere/INPUT/sulpc_oxidants_N96_L38:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/atmosphere/aerosol/global.N96/2020.05.19/sulpc_oxidants_N96_L38
  hashes:
    binhash: e8b31e6ca1af7da756d87243e622e3c8
    md5: 7c42d1faf74b2b9f6819f2349a8d0d25
work/atmosphere/INPUT/vertlevs_G3:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/share/atmosphere/grids/resolution_independent/2020.05.19/vertlevs_G3
  hashes:
    binhash: 67eeeb98a7de5eee305f026a20482cc7
    md5: 58ca02de69b16bd59771c81e06c4c21a
work/atmosphere/INPUT/volcts_18502000ave.dat:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/atmosphere/forcing/resolution_independent/2020.05.19/volcts_18502000ave.dat
  hashes:
    binhash: 34b64995370a775e276c7a270aa659a7
    md5: 47bd369c750be55d706ab60c78bc7aee
work/coupler/areas.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/grids/global.oi_1deg.a_N96/2025.07.29/areas.nc
  hashes:
    binhash: 38b36da3d0026acf1232d414c58a05d4
    md5: baac51890712116fed22bea5db130ee1
work/coupler/grids.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/grids/global.oi_1deg.a_N96/2025.07.29/grids.nc
  hashes:
    binhash: f8c1d444a726ee0cd7d7b91ee9b86f3b
    md5: 9145052d524bd19faa88287c8c020976
work/coupler/masks.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/coupler/grids/global.oi_1deg.a_N96/2020.05.19/masks.nc
  hashes:
    binhash: 9372991dd00c8f0d9a2aeb97fb36d1f1
    md5: 0a12503901fd3d595bc25b5d3008f9d3
work/coupler/rmp_cice_to_um1t_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_cice_to_um1t_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 25469d1a591bac4a823fab31c4a525a3
    md5: f15237ecf7a9d3c2184bdc6766e21c19
work/coupler/rmp_cice_to_um1u_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_cice_to_um1u_CONSERV_FRACNNEI.nc
  hashes:
    binhash: bb85edae540c9a2df03c97471c1a70d1
    md5: 1af0789dbe4e5bf428b6c80be05a1481
work/coupler/rmp_cice_to_um1v_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_cice_to_um1v_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 05cff6bfbe5db1be1ccfaa664bfd702f
    md5: f30788fa9f38e8df6cd6fb36d76d5274
work/coupler/rmp_um1t_to_cice_CONSERV_DESTAREA.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_um1t_to_cice_CONSERV_DESTAREA.nc
  hashes:
    binhash: 8fb49cd703a5d4322ae376c156d81c17
    md5: b21b2648851b6669f8fec71288953647
work/coupler/rmp_um1t_to_cice_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_um1t_to_cice_CONSERV_FRACNNEI.nc
  hashes:
    binhash: f57e2b1bb8365c3b66f4e9dff7c519e1
    md5: 29ad892acb5516ffd501d0ef1c7f0716
work/coupler/rmp_um1u_to_cice_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_um1u_to_cice_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 76dd8a2632f9f24c9c008ed56a9120f6
    md5: ddaa893e0485c65f8e72f60cb4ccb105
work/coupler/rmp_um1v_to_cice_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_um1v_to_cice_CONSERV_FRACNNEI.nc
  hashes:
    binhash: df320c62a9f91bc48c09172eb56c03d8
    md5: 2a5817b8136e8820fbdd4ed28cfb4098
work/ice/INPUT/grid.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/ice/grids/global.1deg/2025.07.29/grid.nc
  hashes:
    binhash: fe44237f8bbe8cbcbe8fadef8957f35c
    md5: ff163d91fb6f3e1f5536c8a109d5c04c
work/ice/INPUT/kmt.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/ice/grids/global.1deg/2025.07.29/kmt.nc
  hashes:
    binhash: c733037d8edd737e43df4335edecb6e8
    md5: f9d11b6fd3c66d6e16a4afde99eec937
work/ice/INPUT/lice_discharge_iceberg.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/share/ice/iceberg/global.1deg/2025.09.16/lice_discharge_iceberg.nc
  hashes:
    binhash: 02e5fe73a134ce5674b3aa6712443e66
    md5: 6257b68d0a6704e99c16ded8d65f9096
work/ocean/INPUT/SFe_Hamiltonetal2020_monthly_clim.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/ocean/biogeochemistry/global.1deg/2025.09.22/SFe_Hamiltonetal2020_monthly_clim.nc
  hashes:
    binhash: 77097b886b17f0942923ef591fca924f
    md5: 28da8ae49dd0d484783b684e3406b338
work/ocean/INPUT/grid_spec.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/ocean/grids/mosaic/global.1deg/2025.07.29/grid_spec.nc
  hashes:
    binhash: 78c18496a68d4abc5a0982ee10110fcb
    md5: 159843131d3e9a169486fe7402047970
work/ocean/INPUT/ocean_hgrid.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/ocean/grids/mosaic/global.1deg/2025.07.29/ocean_hgrid.nc
  hashes:
    binhash: 54eae673fd3c78c4962166a2065c097e
    md5: add61fd8a7e0576871a20dfee003f42b
work/ocean/INPUT/ocean_mosaic.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/ocean/grids/mosaic/global.1deg/2025.07.29/ocean_mosaic.nc
  hashes:
    binhash: a15d1478279c9df0ce672b13f367b2c9
    md5: 938e1cf183a7db8d1eeb17db45fbac3e
work/ocean/INPUT/ocean_vgrid.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/ocean/grids/vertical/global.1deg/2025.07.29/ocean_vgrid.nc
  hashes:
    binhash: 000e7fe06ca6e9d2c69ad6d8b924a932
    md5: b304f3311d9e2f2622277c3636e7347c
work/ocean/INPUT/ocmip2_press_monthly_om1p5_bc.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/ocean/biogeochemistry/global.1deg/2020.05.19/ocmip2_press_monthly_om1p5_bc.nc
  hashes:
    binhash: d4b3605e8765d477b02a55d6ae21feac
    md5: 2e71cbb78c052e06e3df20f862928da2
work/ocean/INPUT/roughness_amp.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/ocean/tides/global.1deg/2020.05.19/roughness_amp.nc
  hashes:
    binhash: 9283cb9b6093d7d9570797f360062d10
    md5: 185dadeb53da2de75b47c53fd7085f89
work/ocean/INPUT/ssw_atten_depth.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/ocean/shortwave_penetration/global.1deg/2025.06.23/ssw_atten_depth.nc
  hashes:
    binhash: f932355b4f6c0197c095a4ea3f94f0ab
    md5: d195ac0cd1e3bdc5bf42476bf300169e
work/ocean/INPUT/tideamp.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/share/ocean/tides/global.1deg/2020.05.19/tideamp.nc
  hashes:
    binhash: f20fffd2f2b42e73b177b439b006751d
    md5: b2840af757d9b7b40207f33f1fc84c5c
work/ocean/INPUT/topog.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/ocean/grids/bathymetry/global.1deg/2025.07.29/topog.nc
  hashes:
    binhash: 420f402d07ad59887eed0f1ef812e041
    md5: a6eaa6fb5097093d3ef05b075cdb810a
