format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/atmosphere/restart_dump.astart
  hashes:
    binhash: 002b33fc74149695b085c6ff864fb5be
    md5: 60fe4d464281f4367a9b0a2853f99153
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/atmosphere/um.res.yaml
  hashes:
    binhash: cb9708df1af89d5fa404b2f3593fea8c
    md5: ac41377c6d4da938558b1b0be72bd134
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/coupler/a2i.nc
  hashes:
    binhash: ff9cacf9893d3845ddfc686626b61db3
    md5: 125338dee5925131eb7819e10c8a1098
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/coupler/i2a.nc
  hashes:
    binhash: d89a0b001afb72dcda15b79981b2d176
    md5: 38416e3b2a89cedec29848390c657f5c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/coupler/o2i.nc
  hashes:
    binhash: 0c1d7bbf2a960b1d53473ba9bfc5fe3e
    md5: 66960a3998370b9ea958e0819ee78166
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ice/cice_in.nml
  hashes:
    binhash: 5d577c54056c6633d0d9e2e3aad4b99a
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ice/ice.restart_file
  hashes:
    binhash: b136df95c29af27207a08ea8ab942d22
    md5: efdaa2923c20f04f5bafdbe8ccf72198
work/ice/RESTART/iced.2798-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ice/iced.2798-01-01-00000.nc
  hashes:
    binhash: 7c41bc5332454414ed2475b48e255ce3
    md5: f86bf431ef1bfbbb560c1cd637f8a1be
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ice/mice.nc
  hashes:
    binhash: 95e8a1ea5660172466cc919e1ae3d2cb
    md5: 6fdbe669b584580da9afb5c998fc9a3c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_age.res.nc
  hashes:
    binhash: 7fa0c3ba4a272379cf30c3f9e91af7dd
    md5: 7e9d55c6e1dfbd7b333d2eb443e89416
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8c2dcf1106186fee75670406a53ebc5f
    md5: f9d6b1fbad7fe0a90b4c02ce29ad7630
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: eb147eb75104df0749fe7a739c9f4ad2
    md5: 3b1fa70302e8d845840e478cdee0ce65
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_density.res.nc
  hashes:
    binhash: f3f8703ff56c7b14224d6a9d2e23163c
    md5: 213a41bdfc0ebb8ddc19f954b79b95bc
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_frazil.res.nc
  hashes:
    binhash: bd596ac2bf7167ae5c89dc30222db45c
    md5: f66f5d0ec71f2894a6d6613216c57331
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 32b729c0267ae446a02f4fce2dfc7320
    md5: b01726a52b1fff90c334c97055112416
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_neutral.res.nc
  hashes:
    binhash: dc02ac9cf8be644837f421ba4fb03dde
    md5: 643c89c9bde75e8fbccefb4ae26c488c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e0b7c832bb43061cb31b01b0d35aa2a7
    md5: e008c28b8a9cf8bd16cc4ebcb045bf83
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 20016d0dd1502312b61548282f4c9baf
    md5: 5085ef6c65cf6ecffc7be831e04ef0a6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f2c5eb69e71b92cc3e912b86153ba7a4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_solo.res
  hashes:
    binhash: 961abd5bf8acfde6402e0cccae424fa5
    md5: 0e5c972384ba5eb5a3570d67e680e7f3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c421e392b443d96c3851d6cbbabc41cb
    md5: 3670dbb934f4bcbf2fb421d91d39c524
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 29715ee54456d72b437ce9c1775d95ea
    md5: da1b061cf85f25da591dda766679bb37
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_tracer.res
  hashes:
    binhash: 64fbf005278dd7d690ad45bd13b1cefb
    md5: 3043d485eac46b22bf62171f96eb5f5d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 17af3de0fe599a81c45bf97ca64737a7
    md5: 84cc816565cf36efeff136ea240f55bc
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7fdb9f09f75e251cdc653e07ca502add
    md5: 5a68a27d4849daa593200389bd2fe5ac
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e06833db370a89052aa4e8ae4711750a
    md5: a8cd636261c859b366b777a84484ea1f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart121/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 370a71ea123be5b69b2eb064afad1aa4
    md5: ba146da21ecd78309ac3dab64a649f78
