format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/atmosphere/restart_dump.astart
  hashes:
    binhash: 300e3b60a49d6b7fcff75a9ff08d57af
    md5: 0dedbef7d4dba93099733be3802a1443
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/atmosphere/um.res.yaml
  hashes:
    binhash: 84dffa9ce8be1a8d529da0bec581aa4c
    md5: ac077e93ba96f88e6b7e9b8d550c8621
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/coupler/a2i.nc
  hashes:
    binhash: bf6450aa3952973fb21b548aeb66029c
    md5: d3e03c5f2ffd08205ce0827166c6fc00
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/coupler/i2a.nc
  hashes:
    binhash: a84655b5c7ee42e65d168971370c1287
    md5: 7d8cd074c63415fb9ceb6ab4a4e91478
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/coupler/o2i.nc
  hashes:
    binhash: b20f09dee98d6d484d79f29156fae6c1
    md5: f5cfd998fa139037d09f0b6aac3f12b1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ice/cice_in.nml
  hashes:
    binhash: 18f474287813e9b0045762cbbef3124b
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ice/ice.restart_file
  hashes:
    binhash: 06ca0d2b0d977e77e2c35edd14f57dfd
    md5: adc94dd197287da8bf02781a7df3eb64
work/ice/RESTART/iced.2721-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ice/iced.2721-01-01-00000.nc
  hashes:
    binhash: e5cf4fcd3b831725fe4f1d858ead2030
    md5: 4dbac949e32c56cc98bf95d88f8fc99b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ice/mice.nc
  hashes:
    binhash: 1d0cb6bc5809f11eb0d96e29046efa1d
    md5: 7d916c22a8910e73f1d324850b3457a6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_age.res.nc
  hashes:
    binhash: 31aef176311bd7c9268a5aeb0424229c
    md5: 05db39d58874c6c4f718ffef6f8044ea
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: dbbcac327dc9012e4b0257043ca6de0a
    md5: 641dec230ca2c9441a4dd59f11e0711c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6bd493e142db371574ba862383c542bd
    md5: 02b319ae05a02ccf34cc78b748495be3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_density.res.nc
  hashes:
    binhash: e63232c8cdfe7efd0a224a5fa8edbd01
    md5: 8bcaa7537b20f2f6b70e4b488df0b2be
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9b3af97bf57cd42cab0978d082e25124
    md5: 5925bf838d4d181128279dbd0e00af71
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 403a13cdcd520d8303aa722543ec9d24
    md5: 1c60fe6cb59afc3a29e8880ded87be08
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a375605e31e511de951d13b1c1c826c5
    md5: 9129ff6de551b419ffdd62d69aa2bb9c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ff933df37c58993a1db42b8b6fba4e19
    md5: 6c958bc3cfd1e3358c4fd87d0f698091
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 98e4434b84bb426d246fa38bf7fb0584
    md5: ffcd86d80928311ed260d1f207c6ec53
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ebb54da42013310579490a205e4a9272
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_solo.res
  hashes:
    binhash: de191c16b17ed55f45d6e6d5764a9c38
    md5: 69a8a3c7b8d45079b574a0ea54d6ab33
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ed2621c79355cfffcaf8b9199051db7a
    md5: 3ee9208d8bce96a0a7709715653f98cb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c937486182e1aff5deee51aa3b75c9c5
    md5: 0e38792d370d095b65ec6c7c94433dff
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_tracer.res
  hashes:
    binhash: 8e271329fe0f7109e9e3943eebfff9d0
    md5: c3ec68c289cd5c15f3ba8791a865f2bb
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 05de445df0f9f9a8580b41d65f73bdea
    md5: c84017aae4f9fcb411cdcdf39f0eefc4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: db498708708a8f246f465b3c429ca38f
    md5: e741c4fd3a9aab692e5c2d3df73c6e56
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e6269521ef884c1e7ef8f8852d2c040b
    md5: 1d44cd6dceeeb36e752ac72f3e439a2c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart044/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d813f5cff1d1c5b61a2b3daa1126d540
    md5: 833360f50838fa3e4eeee58233642d37
