format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/atmosphere/restart_dump.astart
  hashes:
    binhash: c4a6975bbbd677dcef0e1938e5709320
    md5: c9610558d9836246b5c5976b9c622bb6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/atmosphere/um.res.yaml
  hashes:
    binhash: e84ab281c59337d2ff1b4e4033e0f031
    md5: f3a2a06b4a0e9e61b8f285cc3c603bc9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/coupler/a2i.nc
  hashes:
    binhash: 36f7d59dd59fb0d5006134b73104c32d
    md5: 1bcf9dd6f3bddef14df1aa0c9fb18ff6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/coupler/i2a.nc
  hashes:
    binhash: e6d540f1552702f00d1edc4c11efa342
    md5: b804738ae38bd4a9a741503f858ff110
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/coupler/o2i.nc
  hashes:
    binhash: 5feed47faa0c79bb014ec148b5ccea5e
    md5: 6fa9b8ec3b0019ee15b9b21828327428
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ice/cice_in.nml
  hashes:
    binhash: 6a20de69d7bbdfa5bdb9c54c0668ba71
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ice/ice.restart_file
  hashes:
    binhash: 8684a528f316a99ae53bc7a648493395
    md5: 83320d7537043658fcfc382e9896906a
work/ice/RESTART/iced.2818-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ice/iced.2818-01-01-00000.nc
  hashes:
    binhash: ce659055361e3d1af0b01c907c85798f
    md5: b846aa503bef364883ce009afe70d9a8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ice/mice.nc
  hashes:
    binhash: 5f61ebfee927d481bdd4f8a0a0e68be9
    md5: c6aef8b6a3b05c312475148aa8fdaff8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_age.res.nc
  hashes:
    binhash: 27234d689708a2f1c96aaf1f7d1bce4b
    md5: bf40ee0fdb9a16b7bf4a6c6253c37fbb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fa1ea64156b01c0fd75d5fcd23af2732
    md5: eaf00a40c7bea4cc7e005aca134a2521
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9f2d92fe4a487a760726824ae67b0ec1
    md5: 821c6089dd8f60dda7d5910bfa0cf141
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_density.res.nc
  hashes:
    binhash: e457e6aadd01dfc599e20a5ef8c0bb80
    md5: 672b20a0bf223d1c694c792f98cd7ce6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4f5d3202a3a24d47bdba18ad083de7cc
    md5: d2e783af9f271f2eb56143d0517379ec
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7c937351e41adaec513a57e73fbfa372
    md5: 1d4ae500fb5f31cb78f1a9902918e42d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5bfa36b4fef7c3c2a534dba7279012a0
    md5: 0e651e3d4612902732f9a7e9729d5e54
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 72b19d5d0ffe951d0fe97c96969da8d2
    md5: 06120e8d6d512203ccab7056553b8e6c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 42ebf08dee566d45abaa717b08130647
    md5: a771821e281554052224d80d058ef1f5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 97e63f51f93f7eb3ca9ccb472b7a3ce5
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_solo.res
  hashes:
    binhash: 485893fe4e0c632bdc4057d211a52e3c
    md5: 320aa00b81b405d05e452f034e89e42c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f4c75421db53aeb0844704cd20385665
    md5: 56262f5884ecf809ad9410f5ffea0bae
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c1c95c22c4678bc31b0b614025152d9b
    md5: 9d792aa2195e78429dac02fbac4627cd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_tracer.res
  hashes:
    binhash: e57ba3ebb9818e71957cc2843b656c44
    md5: c485d176894eb93cda0441c7011138cb
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0451dba654a16b9b41bfe0b76f65f770
    md5: 14c99f717f496a8c1a7c77efca48cfd6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 20ace3174f9999587c56768f125cb819
    md5: bd575a0be2f3a1931181e8e3e5c8118d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: abd7109757af1cdaac78ee4f1c2d5d0b
    md5: 89d7536987eef9975413a62f2ddd2588
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart141/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 21e079c23ddad06859da43a0158e9a57
    md5: 9f3fe94594269c1778367a3a36058363
