format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/atmosphere/restart_dump.astart
  hashes:
    binhash: cffbb06cfa2c34686ee520fa8c993692
    md5: 9d3dd983b50a3bf24678298bbf637d55
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/atmosphere/um.res.yaml
  hashes:
    binhash: 784f224d330ba4304e9c8b1f933295c5
    md5: 7f43242285a4c4dcee95f33c6056980d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/coupler/a2i.nc
  hashes:
    binhash: 15a5d5d7d3ba73261ec32ac6b2c1b24e
    md5: 9dcd7b5cc623e180c706b3a57ab07041
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/coupler/i2a.nc
  hashes:
    binhash: 9abda69285a999a09e40375acf72fd0a
    md5: 64aa87a83fa28f370f82185b0502cc82
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/coupler/o2i.nc
  hashes:
    binhash: a9030ebcab87514a482ac13c9b5183bf
    md5: 047641d72eed903bce63a1851bb9d8ed
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ice/cice_in.nml
  hashes:
    binhash: 29be7acc46fe8996ef5a6d5e4d83ad42
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ice/ice.restart_file
  hashes:
    binhash: d1a4767ce0d3e153c43f7fb7e58eccf7
    md5: 6eef2308f3694c833ab115d2cb86196f
work/ice/RESTART/iced.2945-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ice/iced.2945-01-01-00000.nc
  hashes:
    binhash: 9ab664645f8528299f38c8878cdfb388
    md5: be7436a379f03d759251b9cb6341ef24
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ice/mice.nc
  hashes:
    binhash: a8071b4c23ff887e8709ce050863c1c5
    md5: fe061cee624baf6c5648dd21a900732f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_age.res.nc
  hashes:
    binhash: f5c23da46adb1b8ec256b1e493e95a5e
    md5: 64faa200f2f043db0324bbdecaeb6a39
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 68bff79cb2d96d47b05a33a0c249cfd8
    md5: dfba8eb69b1c73c2c30075c7eaf44ed4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: afe653b512c1c9b3a6eaa986e96f6cb3
    md5: 1bafa07d411c27f9073fad411f019b33
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_density.res.nc
  hashes:
    binhash: 3227d3c9d56faff7f71871f6a32e1d29
    md5: 6e919942bbc1131f4dc655a4bfacff23
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1df946043479403735020ef209f4a05f
    md5: bdeab6816fd1c1d1be96b0b3fea7bad0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 41787f6abfcc1e34e164636789993fe5
    md5: c5e73fc81c8c20b4091c47076b529f69
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e518395a7b61b164e35b88b11dc7d79b
    md5: e6f2889a49b3822db7698fd59f34a2ac
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6215aeb462ea7b73f1c85860932a5f07
    md5: dbb5934e719a94a5a9dbb4101bb095e9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 811e6678a8ce1e14eb8c4167819969a7
    md5: df2bab575ee843116f30b8127e141346
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 26aa1a71a49ddb502e1922c7b334af7c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_solo.res
  hashes:
    binhash: 738c3f99b1c098977d8f977d458e478a
    md5: a56f5b4e93f92d4e8214e94e297295c0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 93bd63981db5b5e1877423f72b2a0e0f
    md5: 0c36be3e1490f947a28fd585eb9ef923
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 02d52376daf07c7f3eb63e40c7690f7b
    md5: b0c71c24e22753e458b64296c1d242b9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_tracer.res
  hashes:
    binhash: e06eecac9cfceb4a4fe44da45e18f896
    md5: 8bdc93180b35afe698226ca3235046bb
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a315d3ae0d49a62b0a443dadf6732a6c
    md5: 09e415f180b1f0cd71153f526306c094
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8e2203a3755f46ad8245e388736fbf7a
    md5: 7de7d76784493bf031f1668cd7c31615
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a2eb50d0c548bbde041821e12e4fdf1a
    md5: 01bb3bd328513706ec0eeea1912e7db4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart268/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c965575eb587483fc10e0a03d0a07d1d
    md5: 7021331919f86c724283039b5e65c659
