format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/atmosphere/restart_dump.astart
  hashes:
    binhash: ddccdc4e0121c2a0b323df3ccff2fb03
    md5: d1cc6df4b78ccfc38a77716d94d74c1e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/atmosphere/um.res.yaml
  hashes:
    binhash: da07f9f723dfb54a1fb04394fbf27e17
    md5: c4eaf60c871dca36ea9fb836779a4fea
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/coupler/a2i.nc
  hashes:
    binhash: 86f3f6ddb36e70f432205bc58621a033
    md5: db36a467fdd412658d8b4bdcabf03164
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/coupler/i2a.nc
  hashes:
    binhash: 211929b9bff1ea6322d738d84b007463
    md5: c043e3a0d8a6f0a0203a5dabd1542834
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/coupler/o2i.nc
  hashes:
    binhash: b94affe1c92ec02e86b77dca5913ec48
    md5: c4088ebf40cc151e0e41613804f06e7c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ice/cice_in.nml
  hashes:
    binhash: 2c02e38a52bac5aa8a86511f57a45705
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ice/ice.restart_file
  hashes:
    binhash: 40c860233743ab2f448c0ac68806b1d0
    md5: 3541ed1e73f4feed1654ddf53672d8e9
work/ice/RESTART/iced.2950-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ice/iced.2950-01-01-00000.nc
  hashes:
    binhash: 6b3278b1be7aebf6eae044476b773044
    md5: 385112290da630104f6096d4be79721d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ice/mice.nc
  hashes:
    binhash: e61b9afca73507219b1924271fadbdb4
    md5: 1e644721639c8ec80b1969c9de23190f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_age.res.nc
  hashes:
    binhash: c5ff14bc746e7c55ce258b558ba9a13d
    md5: 14e18977465c1d1738de0826c97f1328
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 902c4f8267ba8e85fd491e36c1d67bde
    md5: dd7e4bba0a7b3da2d839689261f7a211
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 96ab04042ae1c4a3bfb3ff94f6c888ee
    md5: e442bb6c8d91bdf1aa68771249c9be50
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_density.res.nc
  hashes:
    binhash: 9bac929ae530e8f4d23f8a1b8cef4422
    md5: c227dba609a15ee43d2931cd4d348d77
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5292871fd0ed5df37649d8d276d3cffe
    md5: 24d41962e76696c9f31f23e91fb55834
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5cc2e35329412cec2223cd28d6b68826
    md5: 2df0a9d5ba496c604c8f808decf15103
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a0fd9878798c0273fd9d5f38930d911e
    md5: 0f2994e63dd77a1844c38db255447349
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b58d8e2c8d6aec36a7bd9dbffe69ecf9
    md5: cda2759a6457fe96e29f1340d9272e51
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f62f757f346d5bbebe42fb492b9dbb03
    md5: 9f182bd5f64031671e66097590e07b55
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7add2dd17c4e385f6af3004e02b3ed5c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_solo.res
  hashes:
    binhash: bf38f5f0ee9bcc7f274f62e56afed6f1
    md5: 64fa414ecd402df51acfe0d9fdb6992f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 737b10b7e277e0cafe76fd1784dc728f
    md5: 11d5cf7c29d870b524d06a745b098775
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_thickness.res.nc
  hashes:
    binhash: fd450a9a916eae48948c7b0189f85583
    md5: 5678ab1f950ca7fe43539fbc3c6a3127
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_tracer.res
  hashes:
    binhash: da56b4fd63b2b7d2534396f0ea752b2a
    md5: 53c95a97bcded012f1b2c7bc8b4a25e4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_velocity.res.nc
  hashes:
    binhash: df2289cf7ff7d7e6300dfd7b92a76b49
    md5: 6f7441139033403b5e9946ce3f7dd404
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d69da75f84af1425cf64f15047260073
    md5: 2c24fbdddd7a6660875ab313831aa8b0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4b0f2f4ac6f3fd3ba7fad02c4e6f0fd9
    md5: f25f2edaef44f8b41be789f1181b9923
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart273/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 53a60012fc4682857acde3a827ead7e3
    md5: 0848672f4192e1de4c945a5048b0fc62
