format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/atmosphere/restart_dump.astart
  hashes:
    binhash: 139e5ef4a36cff774332ae5c4777b3ee
    md5: 140155d11c3a0fcb561a49fea67fb561
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/atmosphere/um.res.yaml
  hashes:
    binhash: db3d4a122b63007af163c1725308471a
    md5: 35719e7e7853015b67084c8b788831b6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/coupler/a2i.nc
  hashes:
    binhash: d16d4914766d0065508bb1517a0d1e8c
    md5: dae2a2ee1ea842b328e0d18e81243499
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/coupler/i2a.nc
  hashes:
    binhash: e077525671ba9efc20aefd8069a41599
    md5: c987510470c955b94c0a084983026d70
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/coupler/o2i.nc
  hashes:
    binhash: 76dfd5db59ff7fefb778d90e26561ad9
    md5: 90f61d5becdffc1dd3d70b2db8f8e659
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ice/cice_in.nml
  hashes:
    binhash: ca77734ee2913895d12395fb741b9432
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ice/ice.restart_file
  hashes:
    binhash: 7ec5b2087be44b5525a67d2f77fd74b1
    md5: 32abaa52f28eb7d9fa235c4314c10de8
work/ice/RESTART/iced.2829-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ice/iced.2829-01-01-00000.nc
  hashes:
    binhash: c68fd357337afbd0c7d672f24cd5fa9a
    md5: 1a74bec854737220e2e310ebb3e92e2c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ice/mice.nc
  hashes:
    binhash: 55372c41afdc4a1e66e7046718a9fdb7
    md5: ed5fb2bfec1419ee11659781efb58763
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_age.res.nc
  hashes:
    binhash: 4be6e9af84ed481e9b44b78403759a9f
    md5: 4ccbbecf0ef623a34d52c2db98d4c186
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f7ac9a3d83e010ec027a7bc487e4c5cd
    md5: 742caf9f5e4dc343b9821beb8801f489
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: feb45ed467d418068787f8dd891e5044
    md5: 20d2fb55ab55ee0143b3b1ab3f4058b9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_density.res.nc
  hashes:
    binhash: 133eb1e9d53657f3e55338c0253f7639
    md5: 46840b19535a75607bf0465ef9a7b709
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 21fca14ccc8e90c3351891752c0d9197
    md5: fda97e116cf334dfa0df47874f06a85b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9fac6ef9b5cee1a91055652faee661ce
    md5: 78e909902070ca95b1d02c7b4f5ecf51
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_neutral.res.nc
  hashes:
    binhash: af0e724414b806307f6345615c3bdaf1
    md5: ae37e1cf0cd889f6c2f703b2fbd38b83
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7483903b8a84195e61133c6381b12ae5
    md5: c9633d8490058de1cf0343576ad45f77
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c276c7e8964591a91039a388f08ce2f2
    md5: 059176cbc78922dc2d31a28f431cbfbc
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fb85e50970f200b2c0af241fdebd867f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_solo.res
  hashes:
    binhash: 04f2222b1b5a1290a1bb547abd735864
    md5: e2aa33e4b900b6999b29ae1afe304fdb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 129e4e3cd04dac4d5e0f1e37fbd0b4f7
    md5: 7877144d86e66446fa485f973317f3dd
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 092ee42d7f192d5471c9757c9fa089f1
    md5: 9ac6ed0efafe87ee15c4b6bc3640dd8a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_tracer.res
  hashes:
    binhash: c37d287f0cd423eec417a4e35e7430a6
    md5: 9b4b903338a5c9184f03a46d47abfb73
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a3914a6ed11416ca6f7fc4158e14d3aa
    md5: dd651a3969c47ddd977d48714f18708d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5a13ac8468055e6962bacb951e19732d
    md5: 5c31ed3106a7022d38f91309ed829d13
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9d26856c59c4d7a61c22b864264f1626
    md5: b5858ebd0514a784c2be2560090a3a7e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart152/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3873668e801eea08a920e5e1486109b1
    md5: 945216d3b666095235a91a2f1edda127
