format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/atmosphere/restart_dump.astart
  hashes:
    binhash: 899d802d1610da670b3c9adb39ab596f
    md5: 02ea5b982e161642763058c6ce300393
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/atmosphere/um.res.yaml
  hashes:
    binhash: 120504ba5b633b55a20017e95b1a9df7
    md5: 110eb31c0f8863d145e2b0f34c4e640e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/coupler/a2i.nc
  hashes:
    binhash: 3f5af364737c67e0b0c2f6013b95711a
    md5: a73c9270a6b08b0491de1ba28705f785
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/coupler/i2a.nc
  hashes:
    binhash: 803743039b6243b9b730f6e6e382e664
    md5: 5746457b5040eefd5682e2b0ec7af78e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/coupler/o2i.nc
  hashes:
    binhash: 2c6c78011aacae3a00b3eaee7d4e9a85
    md5: 26e98fd884d50b526d3a25ecb696f7e4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ice/cice_in.nml
  hashes:
    binhash: 73aed16b89123be05fe4e3d035fd039d
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ice/ice.restart_file
  hashes:
    binhash: ad7c93c1bdf7276d7f2f6bfc7e430e61
    md5: f034a9d5e453526b0a50fe5440d9f8ef
work/ice/RESTART/iced.2900-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ice/iced.2900-01-01-00000.nc
  hashes:
    binhash: 19c7206b65673a2ad422ab36ede38109
    md5: 8fc7ef0703c24af73aa2da4fe063299d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ice/mice.nc
  hashes:
    binhash: bb09b0465bd5f26ba0e8c18f6082e080
    md5: 7efef28d0666bedd70059097f9f8daaa
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_age.res.nc
  hashes:
    binhash: 854bf3725ff768ada5eed05703c8515e
    md5: 1cf3776c56c3d6436af6f081f7833eb0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 778074dece121228d34efa5efaf10699
    md5: e665e4d8d162e94b873cb24d2bfccae2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: aca74d4f06bea738ca48c08c93ad0c16
    md5: 250ff7731b6826b71de7a7bc78d99670
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_density.res.nc
  hashes:
    binhash: 7fc86a3242ea71e9a658e1eda6121bdb
    md5: 785f07bf225aca5d8c8fc9c89990dee8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_frazil.res.nc
  hashes:
    binhash: eb83a3ba8716d192a404d162ef0e365f
    md5: 711f8a207edcf418b11f5b37df62bc64
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 40a9e7b9004e0998dfa04d2941efd6d7
    md5: 46fc0dfe280a3b023006bde994de64ac
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_neutral.res.nc
  hashes:
    binhash: caa5a2620f97e7dcb43632895dfc34b9
    md5: f575e2f5334e9e4780ae3989c68f1f44
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ff3b064e337765b27a129b6bd2887dc1
    md5: 9cb9cbec79a28fadf664a541c1d3490d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 63a3b8742fb177615e18c404c0d1d467
    md5: 1c24c8e901f9aa87facb40f0a1c9cfe9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f43c4b0885331fa1dc96de2c5b46ec4f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_solo.res
  hashes:
    binhash: ab8d8acc878978c257dd1fd853a34065
    md5: c58dec7b13fe33666d1ea6115c5fddb3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8177d09813a0813172b5582c2f279af0
    md5: 3316d2d4644329c3ed8d06c8345f6f5d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5fe09c2901a8b88549d8edf2711e2423
    md5: 9e2c78d7ca7e1f9a9f8ce05516d3b88a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_tracer.res
  hashes:
    binhash: 447ccdb61dd0d734cc4928098906e6ff
    md5: 55d3070ffea0f535cda1aafa7e24f10b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6f6838cbcae48fdda3320aa42dc9b609
    md5: 220cf89c26bd4a89fad7dce76f5719d2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4da000e7982e8b996624dd2c2c93157c
    md5: 28cdb8f2a496bf227f1ded1563e9a416
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e7f455e8a423a370d41a55ef9e199b5d
    md5: f4ca460a5f90a577a4e8b55ed616955a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart223/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 90da5627c6822c2c38243d9f174dea5e
    md5: b2e7ced45ca4f8c7ef14b62c77cde557
