format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/atmosphere/restart_dump.astart
  hashes:
    binhash: 3c46e4d2f2347f77857edfe8590e3486
    md5: 693da2ecff388057e27a90143533937d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/atmosphere/um.res.yaml
  hashes:
    binhash: 714a28a75791f5db94c36712262494c3
    md5: 5c8009365219270c3ffef52d042ef440
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/coupler/a2i.nc
  hashes:
    binhash: a289b82efb07309e3db4d6f9192e0d71
    md5: c8e0cbda467a2462cfb513e9960585c0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/coupler/i2a.nc
  hashes:
    binhash: 074260510dd8ce0fc0cf38f2dcb91d42
    md5: d5eca5a5754c490fb507f0a7db2cf4a6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/coupler/o2i.nc
  hashes:
    binhash: abf5c37f55aeee1903c8d8a848f412d3
    md5: 40224bcbbfed2e2b61674cb8806b1ec5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ice/cice_in.nml
  hashes:
    binhash: f550d8daec7c0c96489dbc699051b60c
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ice/ice.restart_file
  hashes:
    binhash: 37df8da2d7af616a1809f0abb33c9be1
    md5: 479093303406aed4c3f428e78deffc23
work/ice/RESTART/iced.2788-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ice/iced.2788-01-01-00000.nc
  hashes:
    binhash: a3fc246d5447c459ece28e54f22776b3
    md5: b8f14c6fdb1505e7c2b6fa359c3a64e3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ice/mice.nc
  hashes:
    binhash: 25ec59f49ebd9d2eb4bdd1afa16e6808
    md5: c01a503114cd2958c8569369c2e06129
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_age.res.nc
  hashes:
    binhash: dd929c78eb6a0d450b093a9ea563166d
    md5: 05d218c6c5153bb6ed38353a78242668
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 51a364f39b015e821faf21165042727e
    md5: d5d180265130ff06fd1af9592648f149
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 472531ff919e29b7da230ea4a6d69530
    md5: 6c00b76ba5e1011ac1757ccc4bd18305
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_density.res.nc
  hashes:
    binhash: 18eedd66e5d320c14edc4300d5faa980
    md5: ee46d051b1424bf2519fa3e6e02d11d2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c2720a106128a6b3dccdb9c969151755
    md5: 1ab99ba305eea18b7be6f838013646af
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 31c73cf9306f1c4ec5173b651c9752eb
    md5: 9dd2bbe4e617177b63451629e3eb86f8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7defa8ab24356ef0570a7b3728699793
    md5: 47090135e4f3fb63263b06dbdf22183e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: de67abc98bf55e6c6a3341838bfe17b8
    md5: 8f42886c018fc1e902e22cd1e68e8a3e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 209d14832c606151dff9fa71560273bb
    md5: 12bd56d2024a4fb9c2de3341336498e3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1b86c39d92073bb6014b7c55e174419e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_solo.res
  hashes:
    binhash: 89e666320237bcf1f10d33820d2b559c
    md5: 746dcf268df125fdbb8764d1ccc3773c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 65cb0133238283d58cc2579678adddce
    md5: 9f5d28b665d2d66e70190192abf19a93
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 988b5cbac253f0938d5095feb3d6225c
    md5: cef612d20fa7fa6ef86b8182d16e523b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_tracer.res
  hashes:
    binhash: 5dfade49b2056913462d1374f8a9ad6e
    md5: 36e4ef1f5fde841e026a50228ab278b5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 680a1ddca0ec76b301fe2c2c57a53d1e
    md5: 57cc6db5c2d6c9887cc53f78fdac4967
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e317765fffbc9863bb28096b277f54ae
    md5: d650b87c1e5ae597dbfafb46c1d4312b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8ee7f85aed34050b3553a3d4cbc3b42b
    md5: c6e7d5922a6237203491fdfbc34a15d2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart111/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a75a5f8f3486adedfd4aca20dfaecb42
    md5: dc1be205a464ba35fbd9fcc0952b665f
