format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/atmosphere/restart_dump.astart
  hashes:
    binhash: 1f7f28386c38896dceaebfd98d049fda
    md5: b7d71bf5c6ce7bfc77d85c24332eeda8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/atmosphere/um.res.yaml
  hashes:
    binhash: c09a99aae14bbaac13006fa072a23360
    md5: 9699b59b0c65eec6225a527b1b29bc02
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/coupler/a2i.nc
  hashes:
    binhash: f2e1eab6d3bc3e1521e46e0e5f6638fe
    md5: 8db098e9fe0d01c12c63804d5847ed7f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/coupler/i2a.nc
  hashes:
    binhash: 7469d25862bf12c119f1a207fa8b2f4c
    md5: 6b714fd5d4147ba3d379ed5cc5f611ba
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/coupler/o2i.nc
  hashes:
    binhash: 6fa57ad3d48677bc4ea9c8413e4789a8
    md5: 7d67635c75700b70c8ec03f96752383d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ice/cice_in.nml
  hashes:
    binhash: 4abfd1664fe0aeff19825bb11a8004a1
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ice/ice.restart_file
  hashes:
    binhash: 1af7e3e4b7ac59b0fc9fac90cc1de004
    md5: aab5288f063f3a0e286d0c4ab5ba29a4
work/ice/RESTART/iced.2677-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ice/iced.2677-01-01-00000.nc
  hashes:
    binhash: df7fb681c489641888df9a946fcc2ea9
    md5: 4abc3e8a5d6af791540fc559ec3e0a96
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ice/mice.nc
  hashes:
    binhash: 43dc45f9318e88e41a56c648e3e70efd
    md5: 967c4f13a514963bf9ecffc48876ed4a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_age.res.nc
  hashes:
    binhash: 3014aff55c632cdbf243a834979c48d9
    md5: d199bdba3c49146e108d0af45e3517b8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 23d9200f51818d215f282e560c2e3a82
    md5: c6474dff6f8c1657206c171f76984caf
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 90ae0f2a1b4762a594492d709cd27c07
    md5: b95d11baadc6d69b056929ca3212966e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_density.res.nc
  hashes:
    binhash: 983e5114cc075a4f3b0f3c8bfc8cf038
    md5: 67433e5ef01bcf617e20132b7525c0aa
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 257e1f105d1b2e05b4e4d2c12e5450d1
    md5: 372f20e34176298013198dbbf56ef7e6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e647934a96835b033517d641acb61363
    md5: aa484b8b24abc67a98622239d049ccf6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7ecc065234822d2af605f1ab0444d8fd
    md5: 971b1b04922549c102233e46da0071a4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d9327a4871312aa4fb9cd5edea0b75f3
    md5: 5f9182e92f7c3c0d4a3d7190b9f36c55
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 95efb8260c6b0261b94f2f431fba6f1a
    md5: 7d30116edade6152357ee1bc008f8c8e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b8ce5979fe594687e0bbf404ee6ccfff
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_solo.res
  hashes:
    binhash: 29b4fb11caa35c49ccf2fc0c71c199e8
    md5: 472032570f9804fd24fcc388e9d56418
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f421cdf0bd5ca7016c1bf35fe6c5a360
    md5: b78e5a2cdd45da6cb43f06d0156c746e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 094272d9d2ffea03ec1165bb02544e61
    md5: bfb457ce02e4aae1c5e960677b3df548
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_tracer.res
  hashes:
    binhash: 48623fae96c31142a7ff4b7830f58344
    md5: 9e3f4823d5867352d631d89edf64e9bd
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d3e6cf077f9612ca54581ba653fd2c85
    md5: 2564a5921c349678c008cd93f85274e1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a7fd192ee1c07b54bdaf7f5fa0cfdaa8
    md5: ca5047bb2bb1895fb6230ff5845d6a5d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ad5105b3922af3f3062bcd457ce4d6ff
    md5: 7dc1f0635408653444b2bc1b251a059d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart000/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0e61071ec909e73a7efd792b474029ab
    md5: b3d21e28623b2f004e8f79076ce9cf37
