format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/atmosphere/restart_dump.astart
  hashes:
    binhash: 308ac22e50e7cd65ff6a1c513761810b
    md5: 23e224716942cf0291130f2f5a3a0401
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/atmosphere/um.res.yaml
  hashes:
    binhash: ac4e02ae727988d5329af698e87cd439
    md5: c94f89681c9e62916ab3d49696877427
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/coupler/a2i.nc
  hashes:
    binhash: b9c5bcec7ba6c52e55473346fb53fded
    md5: 92373e7358afe6820b911d1fac162af2
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/coupler/i2a.nc
  hashes:
    binhash: faa074487a598edd9afd23c218b1bb38
    md5: d241b45a77b2dc31d1bafa0edf492bd4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/coupler/o2i.nc
  hashes:
    binhash: 7d4c82275d743555880455bf99fcddfe
    md5: f96712e77897876319e48b21d0ca924d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ice/cice_in.nml
  hashes:
    binhash: d8a73729087ee412bb047c8b09301d71
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ice/ice.restart_file
  hashes:
    binhash: 5f8898c1805dd70410633ff0f682e4f2
    md5: 0add9250f917e07baa6e3cd9530c01fc
work/ice/RESTART/iced.2939-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ice/iced.2939-01-01-00000.nc
  hashes:
    binhash: ff1bd3f940667e76914b12e9d67106f7
    md5: a8784271d9c760186cf7ee16607352f9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ice/mice.nc
  hashes:
    binhash: 8878f83465d4640e0e32418d8cf5e72f
    md5: 8a09885995b3b2eb697f03020cbd7e62
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_age.res.nc
  hashes:
    binhash: 6b4ff5bd821dc409c6c6a1504b69f9dd
    md5: 92500123aff51323404d706d3e05c78c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 16a7baca1551aa9cfd763b3efbb17a5c
    md5: 69d627770bbeee365bb6722ba6e9fc44
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2a418c47857d458fcd790ca32d0052bc
    md5: 55a6d19bb980d382c288e4fbe08cdc51
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_density.res.nc
  hashes:
    binhash: 1df3b9e4e6eff11f0ad88698bcb7f820
    md5: 2d1d703bbb76c4f4ec3b4ae77eac8396
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 845457265a556401d481b3899be7dd6d
    md5: 18e5021a461ed63e2b5f5c33d7fa117f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0108e01e5cadf70131238200e4618244
    md5: 932cd2ecbbe83356383b309d0e42e694
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 54444c05b04b5f4d775576023ef48203
    md5: 6bc9dd82205c8c5856b0bbe64e582939
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a51bbc3d9412c5325a20c4eb4d5eca92
    md5: bf444c59cf479f907963709f3d6d9581
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a18e7abc799776150aa1bcd649411cea
    md5: 0e3ec696e29afe0335711f721142a36a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d82c289e8e447f1d21910ae9dd7542e8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_solo.res
  hashes:
    binhash: ccd40eb99b0f23c0d20c9b6524f3dbcf
    md5: 797496614bd6f4d35a58174da22591fa
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1dd66816c564d3e928411b703ead99a2
    md5: 2425b9ee82422a64ce625510496b6186
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d4b4c1447c9345258584332825a1399a
    md5: 3c0349ce4065113cf4ab2310c252a95e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_tracer.res
  hashes:
    binhash: be05d6d3e05fd885da88ae0237aa4264
    md5: 74fd73cdc777fc5aa71bad4150c37976
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_velocity.res.nc
  hashes:
    binhash: cb40c93395d508576d2e56752b2b07a0
    md5: 681dfa460666f434f0084e42577bc8b9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: da7c2e60db1cf2b6849777183ffe9c5a
    md5: bcc11d922e94ff82942d5ce03976ad94
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b3c27058daf86bac40c3072fab8d32b7
    md5: 9bb0165a682e187320c7db3933c26b8b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart262/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 70e705c5b820a8d174d427c724a82189
    md5: ca140841b757e81df7a628a7d5cd4949
