format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/atmosphere/restart_dump.astart
  hashes:
    binhash: a3b9fe6ad1ab9652eb9ba96c4b0b4c15
    md5: 885b40c9527b24973ec77ded73b4111c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/atmosphere/um.res.yaml
  hashes:
    binhash: 58a4cf4c3682326b5c81cb34de01c8bd
    md5: ee8533974ca9c258da8598726c433fc3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/coupler/a2i.nc
  hashes:
    binhash: 4cd9e80adf6fab99ff294dd2333b509b
    md5: e3a711f45e041d72f53eee0caa8a0fd8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/coupler/i2a.nc
  hashes:
    binhash: 3d4bf429bb8a6751ff63413710f4310e
    md5: fe1756f4973c7d20991214945fdb8674
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/coupler/o2i.nc
  hashes:
    binhash: fed5989d3995580a54448387399303de
    md5: 408aeb84ff32ff2588c73aea957a38a5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ice/cice_in.nml
  hashes:
    binhash: fa855cc103e056da7224882688e1956f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ice/ice.restart_file
  hashes:
    binhash: ea0cc274b15787ebcdb65702d4166993
    md5: fd9f2d214ab3028e81347c1d5c50b269
work/ice/RESTART/iced.2861-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ice/iced.2861-01-01-00000.nc
  hashes:
    binhash: 90f5aafb0442825abda559d49ea44c41
    md5: cca2006b86be708a88f7788755f0440c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ice/mice.nc
  hashes:
    binhash: 15d52d53033fcc5bae1199854927584e
    md5: 295c0caa5a2881c25e485753ee373bf0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_age.res.nc
  hashes:
    binhash: fae578b5b9ebdea2a905ab77a3ccd26a
    md5: 8584f64dca2c0de2bcad1782ed99cc55
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c20a4f7d936c9cc65418ad19bcc5c940
    md5: 103e17774a234760826f0065571712fb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8a436d6afba3582073a5466e9639c51f
    md5: 0d09fc9cf199ae90d3729f739bb93d68
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_density.res.nc
  hashes:
    binhash: e1aaa9d842e6c88dd4c8582699d7d2b2
    md5: e8ee790bf6a5fe72ad8c1563cb8b55ca
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c49746fbe838677b628843cffef55e6b
    md5: ca2379c0b67f57a96eb85e3902f34cdf
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ac25b656d03c6454eb6bcd598b8f1798
    md5: d6116501c766e94bc156503568ade4d2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5122c60e5eeee18f76bed046fac42330
    md5: f3238f4c978aff3704cc64c00fb7c6eb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2469999a344208c43e09bdf9b648029f
    md5: 21724b865993c31d57c6c39d84b32aa7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8740b9554284e780301d8d7a9163ceac
    md5: 2b436fb8f220794e22a62a9e8a429df9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b47594fb9ac34e9d200027f9f45d14a4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_solo.res
  hashes:
    binhash: c935a8406870c22aff805173f2bcaa9c
    md5: 12bdcbfba0368517a3776488e398e030
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 88d58e520bcdde934082aab91e03850f
    md5: 9a72000485e1dd9f84630c82f0f1152b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 46a82fd4b81210b348c80637ba7ad692
    md5: 9ae4306a7861afbbd23f03838adff9bc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_tracer.res
  hashes:
    binhash: 738df185713e7b4bc3edf0bc34795160
    md5: 79a0810fe3ca1f88d51eeb90fbfac93a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_velocity.res.nc
  hashes:
    binhash: fdcef590bedd4fef000d43d39076b115
    md5: d67abab6659f6d79d9f5010db1c53511
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a8945c7d8325dd8b424c618b0c271f06
    md5: 2efdbb0308f1c0020f43ef68546ae50b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9258a6d97661dcbf1495844ced559982
    md5: b447df6eab59c8fc6e9bf2039266f26b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart184/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4edd50fea82f3b37fc14b66e753492ce
    md5: e3da9d24085eb25e3e0c85d055e9d49e
