format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/atmosphere/restart_dump.astart
  hashes:
    binhash: 37b9f4dc667d60efcbef3e4adfd05672
    md5: 2f34d93d5da9974b9f0c9e4016f963fc
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/atmosphere/um.res.yaml
  hashes:
    binhash: 14788850a9054875f604e9ac9afbb08c
    md5: 49be99cef5ce2f7ebabe641000d8edce
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/coupler/a2i.nc
  hashes:
    binhash: 2ca4e05e6e124ceea3fd38b9bf8904ed
    md5: 28494ebf1428385bfe34d91462002d93
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/coupler/i2a.nc
  hashes:
    binhash: 3894706bbcabf4bbb3ad37eaa5683cb2
    md5: fda3aca7fbfe1e5555b4ccbeb774dd9c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/coupler/o2i.nc
  hashes:
    binhash: 826a7e303f25be362003b99521908b99
    md5: 7fd0f56648a14b8f86b094be973a2ce0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ice/cice_in.nml
  hashes:
    binhash: f73440772ff81f5322125caf07b006d3
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ice/ice.restart_file
  hashes:
    binhash: 0b339411a08fd2e47192f8a41e2893eb
    md5: b521296927f8b45a07a9dc9de276288b
work/ice/RESTART/iced.2906-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ice/iced.2906-01-01-00000.nc
  hashes:
    binhash: 1203288f480e8766de36f0a8a2d49d4a
    md5: 5d8ef47a22719cac94f9a934ec44e70d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ice/mice.nc
  hashes:
    binhash: e856df65808e3e4e9e96ddcfb8e3a232
    md5: 7b3fc56bb9d63001539d3efeb929ded3
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_age.res.nc
  hashes:
    binhash: 5f29e5ff6ac90fae30ac5be0921709fa
    md5: ecbab18377a88f3c468c0b100b03cc55
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e5adffc7951ee825ebfb63addcb93119
    md5: 4fa21cdd0450f2aad492bd310d160b9e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: d946d34b7b80a28637ce86a083e6f490
    md5: 79607053303b6a04a22e366d969b5f65
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_density.res.nc
  hashes:
    binhash: 6ca5eee2f366ba2fc9578a1d07b27136
    md5: f55343810a761e04b720e679a07d207b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8584dabe3103a28e28e23a39f74d94bf
    md5: 752be75a3915db57dd50068639467a67
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f80b77fc862b608b4e3438944786d18d
    md5: d516268a92ac098857840746443fdd3d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bc355aedf128e6918a1f43566a08fb1c
    md5: 404f2aa8dfcedccd226bab2765654aee
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 368157f62d78bbb6a860520ff6129b5e
    md5: c6f32b35b381c2d543c0684df2441519
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_sbc.res.nc
  hashes:
    binhash: be5f7916f4c10deae3e8e4bd08c3a3ef
    md5: 225fc649eb0c2e8e9231c608d5f50cf5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ab5733a5b24b98fdd60e7b510d8e4d4f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_solo.res
  hashes:
    binhash: 75de927f5c2675970581c88ebc0db4e7
    md5: 7c2e35393ff9e509545cda9bbdc7156d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bd669f30acae07f65834bf1a484a605f
    md5: a9f4ff9f15b1a688e2af90b94e7ff151
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3d769886180c69b62ca19f65fdeb4a58
    md5: d0c6dc79e9cec8c5d9a31d70b6c88bcb
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_tracer.res
  hashes:
    binhash: 61bd52fcd807972d08c42c6a71b87d57
    md5: 7bf62d4bbadda4a2f21e8507434c3411
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 527728b28750e18305d8c886cf9e5599
    md5: 49479d261a0940d246856174244b9f8b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c7d03e69a81953d695e291f6a5827e9c
    md5: d02d29009c6d2db06938699b756fbd38
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4b47c603553271a3c0d049bb05039084
    md5: 0a3401685d055755630cea289936475e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart229/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b63d9d30ac9bdc8d5eecc511bcbd873d
    md5: 95269e7d034816a9740f0926be3fe1c2
