format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/atmosphere/restart_dump.astart
  hashes:
    binhash: 2d6ff5cff173ad1e351af32c5de4202d
    md5: c24aaf91147e9f8a6138d177ec236ace
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/atmosphere/um.res.yaml
  hashes:
    binhash: 7b5195a9b61dc5c8bf605b7a449a2f1c
    md5: 616417b0344470f6d5b6ace1d5fa67c9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/coupler/a2i.nc
  hashes:
    binhash: 16d9b6c6071755b2775ccf2e463e2621
    md5: 142e786ea2c224b6138962ed9a500d3d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/coupler/i2a.nc
  hashes:
    binhash: c2ca1263bb967841d01d106c4051d0a3
    md5: f3d85990ee74aedafde9707c3da57821
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/coupler/o2i.nc
  hashes:
    binhash: a2f528c46437352ac52b287418771929
    md5: e97ff87033fa2b07cfbb3d2fd5ff3c94
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ice/cice_in.nml
  hashes:
    binhash: b0aebd70c8af22145687e93d85355d7e
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ice/ice.restart_file
  hashes:
    binhash: 590942bab12c55015463174f864db22b
    md5: 666c725ecc3e88b33d5204778407d2f5
work/ice/RESTART/iced.2764-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ice/iced.2764-01-01-00000.nc
  hashes:
    binhash: 60d62e58bb9a31069c95e1b483a78eff
    md5: 9ee19c008f4bb8b04f58a69d4caf1f3f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ice/mice.nc
  hashes:
    binhash: afbaf4e9fad69e6aac4e44504c1d7d25
    md5: eea934c2a707a5292f6d4323dd85cdca
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_age.res.nc
  hashes:
    binhash: 1d8cc30609ec2a7fd2cbea56c47d0371
    md5: aff3a4e5c7b47ccd3c54e8a64cc16eba
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7737301c4818a2980215b062a473597c
    md5: 303bfbd00a7a267ab86b480f6c6754e3
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 96c69ca122aa472ae998f17e19a9da36
    md5: b2582aa2e38024d555a53529a39199a5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_density.res.nc
  hashes:
    binhash: f2afbd8252d2f415c6259bd782789056
    md5: 9c40d3ce6a4f56cf611bf8150fb8d8f8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 772a7ea852f81ed3966d9404c728b852
    md5: 61e2344c0ea66a1284843e92e5dfd115
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: fed7cc33d95668b2576deb1e42252115
    md5: 3d6b2da0a25441e62918fbc703f30bce
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9e0be35cf1606ba84f47ab6fa54f9873
    md5: c4b2f66024d69e84df6df572eb755927
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 63431172fa6815c6eb5529267aa6b127
    md5: c6824e351d0b07ca0a676001032449b1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ef5d2379813554d44a30f2181e007a14
    md5: 953fa9cbb62f90aed7771789facf28c5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 92ebc4114791c30bb2af2b0c3f275ba2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_solo.res
  hashes:
    binhash: df754069939dd14af1b709ca73035c33
    md5: 572a12e0f2ed974f8c51fb39f4194a80
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3a15e109e42294357bdc3cf6c7c4900b
    md5: 5cb843294ab19322c2318edd466949c3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 61b9aa926b4445858e54a60205f1552c
    md5: 5ad3f51f3990359fe1e46a71f778f436
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_tracer.res
  hashes:
    binhash: ba208cd995186b9387fd965e7f216d9c
    md5: cccf931c32cc790770327010e9bf3f36
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f9201661e2a3b7b4917e3779da6b7cee
    md5: 4656ddc696bb5162ba270f5982d25f16
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2e1f1e48b462d5a7e171a1cd2edd9519
    md5: 757b09a7cb02c8fbbacf4d4303f704ed
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: dba8a4ecf8c7bf5e4c6b7c514f725bd6
    md5: 8184795f15b0de12c63920271f00b953
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart087/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 923871221b694cdaad6d8555cc52c7e4
    md5: e4fb7d2086ccf2372c4db96ac43ab8b8
