format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/atmosphere/restart_dump.astart
  hashes:
    binhash: 07858047c91d35f9450ffc8d2694d243
    md5: 152bfb8886cf5ca4fdafbc3eb861036c
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/atmosphere/um.res.yaml
  hashes:
    binhash: e8f08266ba80534777b83ca4af19404c
    md5: f5307351dfeb7863d90209bb30500be7
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/coupler/a2i.nc
  hashes:
    binhash: ba4f9d1bbdf42c44dd0412374a00dc33
    md5: a0705dfbc3435320d5b0c65119430e80
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/coupler/i2a.nc
  hashes:
    binhash: 93b1b711327d7b5ca3451732616f6a34
    md5: f2a8449927119b6d7676590f5ef3cec4
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/coupler/o2i.nc
  hashes:
    binhash: 014adcd1d5dd60ab46eb6d225a39ac5c
    md5: 424e12481d4827ebdcf12738ea68d8fe
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ice/cice_in.nml
  hashes:
    binhash: 46ed8858288c858354df9bc8c50f33fb
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ice/ice.restart_file
  hashes:
    binhash: 7392ca0270be17dd79d7356b78ed682d
    md5: 6ffb313c0a715bd962769f972fe8aebf
work/ice/RESTART/iced.2676-01-01-00000.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ice/iced.2676-01-01-00000.nc
  hashes:
    binhash: c2f71a567d05fa6b392e588d6bd90064
    md5: 53ce8cebad1d2fba41d58a07d055d2f6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ice/mice.nc
  hashes:
    binhash: dc4f2517b6a8d8bbaab126baad17f40b
    md5: c71f480eb83945a5138db052b91aef6a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_age.res.nc
  hashes:
    binhash: 6893ae34c9b99a8126ed5091b3777b53
    md5: 7eceeaadc40f68654ac01c13929acff3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4d0a5efc2a81e7713279e46a5f2d1418
    md5: fb21f6c407252ebb063daa14eabf7c42
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 03cbd2c97f7dcb5bf836d33104d53d9f
    md5: 17eb6887873fab1a7893a9af97791dd2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_density.res.nc
  hashes:
    binhash: a326556591b090b11dddd5a5a04f1b6f
    md5: c76c29f0c2f9ed805d687e6f69d18e4b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a2eb97cf4356e0196d25d136e8bbda91
    md5: 8bfc7a175a5cd83253ad25eb163551be
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ec417de19e7d5b30e0e454ed6b85b17c
    md5: 7fa1f8541b4fb08e267ec7a1b53a817a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b083d34bfd2f459925584f4e4a1f026a
    md5: 609965c633d18eb742fa810d9cbe4395
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7e7b974da0a63af60bc817c066c1fc9f
    md5: 4fbd75b94fead7103fdadb4f1665e751
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b2b02b50a512dcc2b1248c863fb2cb30
    md5: 95e1bd4e65a8fba7883757f4ae9d20a6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 82adf2a79ca9c9c08d6d52c2dbbc52ff
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_solo.res
  hashes:
    binhash: d38c8f1742dfc91f7d1a84d35c664e3a
    md5: 241cc3f69d951a2e25860d212a23ff79
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5c2b8b662fcb80d397b9c2e58782d372
    md5: 5fa6b9508886f9f8574265672f1e8310
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ac9af51e5f0753e29c3edf4eb08e486e
    md5: f7e5deb8d6ce99a24e1d94072d6ddf09
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_tracer.res
  hashes:
    binhash: 4dcd7261470db49ba6224ea66f72cb88
    md5: 573b342d4729db00dcf8ab58166cb707
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2b0592245cede173fce07a440e040559
    md5: d78bdff14e081dfc6064e92f75c56c59
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: aa8262e162e54336f55dfd4fc210bf0c
    md5: 7d5936788f925b717f8f48008e07c345
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: accd08fbdc771cfda4890a7db903056a
    md5: cc1b35030bf63b2f47c264055546cd88
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.12.22/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 049d4ff6c0c87455ed2df068acbbc6c4
    md5: ab126b4a4b67ed259bc9ad42d3b598f2
