format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/atmosphere/restart_dump.astart
  hashes:
    binhash: 4142694cbdf5c609e7309efff56b9885
    md5: e90ead6f8efd7610c183b3e488136612
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/atmosphere/um.res.yaml
  hashes:
    binhash: 57cfc6a953f63f8ee4c4254c80a1f5cc
    md5: 30f111fe76f963672a81f590f113fa0e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/coupler/a2i.nc
  hashes:
    binhash: 6cefd44ad7bf2d99933f768f3fe423d9
    md5: a787efbc024357803f4f5ee8f3aa27d0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/coupler/i2a.nc
  hashes:
    binhash: f91b590c08140c5105101ddac0e37add
    md5: 90e023155a06168a6562b4e09e3f35c6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/coupler/o2i.nc
  hashes:
    binhash: d37f611223f2924e014ddf7113dada95
    md5: 8fd4d264a79fae05ed69698b212988b0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ice/cice_in.nml
  hashes:
    binhash: 72ddba4b50544cb2ae672a18b3a91777
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ice/ice.restart_file
  hashes:
    binhash: 9922a7a7e28b21235a39ac248e99b164
    md5: 754867e920280cee41bef1be6931e8dd
work/ice/RESTART/iced.2923-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ice/iced.2923-01-01-00000.nc
  hashes:
    binhash: d6a4600a936ba1c90b9d1c7ac1691fe9
    md5: 38d6d0c1e7d2f6f5c1acb1504ba107bf
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ice/mice.nc
  hashes:
    binhash: 67e817a5bd596fe5b2e7041e115afe03
    md5: 63a480f25af27cd1ac66d1df44656fac
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_age.res.nc
  hashes:
    binhash: 9ab90884691747062ef0907882c41108
    md5: 244212a399d1da068dea932c5cd71940
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ea937297b232407d802999a4ece3be24
    md5: 4ba7eb182bb77d49e5b10071ec23e070
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e0dd376a94b9e2cc0b84ad9237b6aad8
    md5: cd6892c021fd8bf384fa647532cc17e9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_density.res.nc
  hashes:
    binhash: b926e89a5f739be8c7f15fd314430a75
    md5: c955932317228bf8f9b5c186b59f7732
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1001b10437fd39c577bbae8217ac7cea
    md5: 3d6c9979b70647b6ff5a9a3e2841a8d2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7a7bd5ac763cff11dc7183184cb756b7
    md5: 3e38dec8ca8e43eb167746a57e2b3f91
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ee090b27ae030723b32eafa7c8300079
    md5: f6372fc5278b8f4efa4d8c2f4297e468
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bea36e2cd129e5da2dbd45f77f4b71ea
    md5: a2a28426eecd24adcb2b31984f14bd79
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8030f31480be5033a9e893d9468c00a5
    md5: 67c52ae289564b13d6afa1209ff47d6f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0dd13dd5b16692c8db2b45610fc8b9c2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_solo.res
  hashes:
    binhash: 6821fca4bb33ea78143cbd831c838c23
    md5: 3cca484a7859983a2c718c01ec643f6e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 03dfa7cc8b2dbb708a1b141b8f6b847d
    md5: 5f46cdfcf4568fef4b00f21f613bd53d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_thickness.res.nc
  hashes:
    binhash: fc8d63b51781413a5b0ade8ced0895f3
    md5: b6623900c50c0779c445ba8e2107f0d0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_tracer.res
  hashes:
    binhash: 15923427d0790190881b1f52b62f0df3
    md5: fa7a6f563268c47cd58b533b4c984b79
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f641a69f28a9e80ee23d2a7b7ac9c8fc
    md5: 5d2355513f79bf8f5aaab3f600e47d40
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 166e66313a508c72b7959c2c52549307
    md5: f836c0fdf48644fb015425b49fffc526
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: be03b8a32a1951711cb546b845b56db9
    md5: 71eb7846064857d9f25afff3d2a22905
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart246/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 835b614174cb48dae2d5eea0d16800de
    md5: e63035d4e357dd192c569e54453c256f
