format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/atmosphere/restart_dump.astart
  hashes:
    binhash: d9a81d0389658289b3199cfbedc3f2c8
    md5: b7dd37b2dd26b7e6c02599848b4cb7b5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/atmosphere/um.res.yaml
  hashes:
    binhash: 977145ea5dbfd4f57c8b111467d48186
    md5: 7cbfc8391341b9facd06385378fadf8f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/coupler/a2i.nc
  hashes:
    binhash: 9ab26a09973f9f680416a98b958802ca
    md5: 5e63fa3353bc39962847920df30b7338
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/coupler/i2a.nc
  hashes:
    binhash: 20a8a605cff049b6affbea917fe0ba5f
    md5: 439194556bbd33732572df9d323a0087
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/coupler/o2i.nc
  hashes:
    binhash: 3c23d8b8691bac21a907358c865ac3a2
    md5: bda74017f2c4110acdbe0233e4fb1e56
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ice/cice_in.nml
  hashes:
    binhash: 963cd34338d614638f7a66a16f687750
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ice/ice.restart_file
  hashes:
    binhash: 54cd8353a84ba070c6384e6a9ba99f3f
    md5: b622c8e34922397c8a2115b7a2597129
work/ice/RESTART/iced.2839-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ice/iced.2839-01-01-00000.nc
  hashes:
    binhash: 9d8e5e8c9061a57e546a24b4b761ae8b
    md5: 60345646e90ea8c1ee5e61ec8733230d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ice/mice.nc
  hashes:
    binhash: 9f0b2e6a0e7509134a4e77e50e3c2810
    md5: 2de44dad984a99f2dbf01d31840a043e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_age.res.nc
  hashes:
    binhash: 9986361dd43e3811ffb4b848777dfc32
    md5: 5c76fbedb0ffd9a64a602b9ca048c59a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 44eefb960b60e0c00007ba84fb98395c
    md5: 99ae716998c571484fdd4fd361784faf
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: aa15bf6836b8b3a4386e5f68f955ef56
    md5: d2f116f67ae9e1d0c782f16feae326cd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_density.res.nc
  hashes:
    binhash: 89163d87464b5cf4f3695d9d11cb28bc
    md5: 1771a21c0f169ff09b1e3d4d2a0b5335
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_frazil.res.nc
  hashes:
    binhash: dbf15cf6ed37d2209d7886740d5b3e5f
    md5: dba5cfda6a5cd9b786e8f47b25607ac7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7cd01836770bbaba4eb6c8904e93b2bc
    md5: a25354de997f78778a7a3ff720c1e558
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 11b0a17b53f61fe527f99a80e6648c74
    md5: 65ccc497b8bf2e2e829a8927f19d71db
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: af29233b4f90cb64edb4180404cbb26d
    md5: c2551c23ed440b0a73e79af9285b61d6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 674e03a4d38641ed5afb20e021d0cbdf
    md5: 183e159799b42ef89f8823c0afd16b66
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 277894b483bf4a72a1e8b8cfc876788f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_solo.res
  hashes:
    binhash: 67cf0c4368a4e92b578a43ee12da01e1
    md5: 67acb6208a7f1e6bafdb1b110267efd1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6159367825b0de10ba4fabedb5a848d8
    md5: f017f7706961dbe20b3e6e7eb98d677a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c4efc890365627b5911e98e54eca4405
    md5: ac3a3ca8c9749a535608bd92c084f530
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_tracer.res
  hashes:
    binhash: 73b685be6b0561dbeff3c852c2eb804a
    md5: 89069e952536a6cf69ac4baf2d7bf1bb
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 173e3dc0f625b15e6d4ad9661b872351
    md5: b1a952c6aa614f4cc413cc8ea93d13e1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 76e929069d55feb4b53df7c74d5a6abf
    md5: a19a1c4ad98ea2e6971d5aa366d90a91
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2ae2d2c29f9d72fbfbdebee82b5624ec
    md5: e19b3f3c49c3cec5bbfc9d93da4abc6d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart162/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 60801863fb50c6d11817e3c3e899b70f
    md5: 3c0bc4dad80cd653bc786bf3e8c1251c
