format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/atmosphere/restart_dump.astart
  hashes:
    binhash: d883c5011519affb8430a7880c53d3b8
    md5: 1e946316e1a36adc150d98fb520d7da8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/atmosphere/um.res.yaml
  hashes:
    binhash: 5bbe3886b43c4b8c46b516623f5ceb70
    md5: 1ac1a20c13b5dbb5c4d0d3250f9eec4d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/coupler/a2i.nc
  hashes:
    binhash: acc0d1fc9a463e57480ea8f95d1d823a
    md5: 30a8a008dfd88c4a3724a909e58f823e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/coupler/i2a.nc
  hashes:
    binhash: 7a97cb8eee34f584191954685754d99e
    md5: 380516fd2f644dc2a1b547d355c0cfec
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/coupler/o2i.nc
  hashes:
    binhash: 8b699880ff857810b32e49fcd51e9359
    md5: 33268f67e6f86d66d1bfdbaeaad54a74
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ice/cice_in.nml
  hashes:
    binhash: dc8edd27737d90b560298cc9160d0b9d
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ice/ice.restart_file
  hashes:
    binhash: 9ea787752d688661c45370f707540ac7
    md5: aaf72cedabacba5eb982f6ac1893c5ad
work/ice/RESTART/iced.2921-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ice/iced.2921-01-01-00000.nc
  hashes:
    binhash: 341f38b2199f984640d104a83a7a0c23
    md5: a94a4e6184ed7505f43204c9c55f8767
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ice/mice.nc
  hashes:
    binhash: 2b4f248d99adcb245a20ef67f0067db6
    md5: 89e4fd90c45040cf051984e7295f0ea3
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_age.res.nc
  hashes:
    binhash: 506499ecd1464486efe7fc082adadb57
    md5: e4daa2d9ef625a541dc6be77bacea618
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a018c9cf0fdabdb64c952c7fc1e00558
    md5: db0bb2b37137822e6cd8981206ee44b0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 92a724f5146f2dd58837ae3b50ddfb30
    md5: 6d41af2e2ab03602c2b6bcc569ea072a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_density.res.nc
  hashes:
    binhash: bfacaa62f69dc387f92da3ce0aafa0c6
    md5: b1ab218a9cdb77d4b8720e0e61e398d6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 612a310145d147a75d91ac00e1e1dab4
    md5: 2114e85896e0e1d2c1507094befa0fba
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 030befcb1093a139302b31f080dc637b
    md5: a20296c546f3595bc5af01e2f34157e9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9ba52352f3c89cccfa082bd03a685335
    md5: 13f42a4e34fdc6d5b59cb94d975ef165
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f22b6bad0087e4097b0d2dd8e4dbf66e
    md5: f53c7a5da6c09e7ca1bd169175bfea94
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3f4db7d5e51146553ec911b70eac99b7
    md5: 6a7beaaea1b53ce74f2af87cfe1c1607
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1bd0fbf25b97344575171158b254a844
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_solo.res
  hashes:
    binhash: 88139fb03abebfb906c3e24ae5918165
    md5: be208ed51589c1e0c1a72a59a4b31208
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 43d8b54211036f3e6f393a82acc739e4
    md5: 6c14588ba33fd5c236a35c6e8ce4078b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 11e680e87c0000ed026947c117c26479
    md5: 266300fadd959d66b16aa717fd74a463
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_tracer.res
  hashes:
    binhash: d60a922ad5c1e513f2d012ffd047530d
    md5: 63e8d9caade81a0dfc5fc703d2f76ce5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_velocity.res.nc
  hashes:
    binhash: aa1cba25e72b77e5a7e1a3dfacd61e52
    md5: 4c3af289750d0731098e59db03a0bddc
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5eead900fe405c13bd4fa6a9ece43a35
    md5: 89a7b9a80df31a875ee41f5fe0a43e74
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b1f66fc416221895470cecb8dd58c778
    md5: 6ee1bc3dec2aa01859c0f9df3b22f8ad
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart244/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 88d479d5b13dd775e337f7b6003e82ab
    md5: 292057f889b91fd2cd171c62d5a03801
