format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/atmosphere/restart_dump.astart
  hashes:
    binhash: e4ae115c325bde7a405780debed9c8ca
    md5: c42516078a281f18f56c9edc9b29e623
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/atmosphere/um.res.yaml
  hashes:
    binhash: 6ff445c934d487dc45d7fc348bb3b4e3
    md5: d1d32fc850bcbad5c0880b4665161514
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/coupler/a2i.nc
  hashes:
    binhash: c503045615f34a791f4c3784ed2acebd
    md5: b6e1093afe0f5e253b56ab38b5594df4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/coupler/i2a.nc
  hashes:
    binhash: c99b5d92b3e0be9056aa5a13390735f5
    md5: 2c4c2730f8dfa3ff94538775ba014a59
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/coupler/o2i.nc
  hashes:
    binhash: dc6166a7f2f4707bb6af178cfa6c41d5
    md5: 804378b8b31e24b759aba529e9b87b19
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ice/cice_in.nml
  hashes:
    binhash: bbd0ae9a5243d553d2822a472924d0ec
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ice/ice.restart_file
  hashes:
    binhash: 379d2ee7648d857d5ad78b7280cff6ff
    md5: 8a7f49a7dc707c518664a8de63ee0db2
work/ice/RESTART/iced.2838-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ice/iced.2838-01-01-00000.nc
  hashes:
    binhash: feb88ed801f7bc0edb8ee38d7477e7d0
    md5: a48d21e773a5a3f0351cc9f7b211d93b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ice/mice.nc
  hashes:
    binhash: 61a99b2bd60277c0daf5a7c6e82aea92
    md5: 0a2be35762c6007170c786d365733048
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_age.res.nc
  hashes:
    binhash: 1ef1ec0b2b74ef6294799aa8273d868f
    md5: 2a71021399966d12c7e261691e2109f4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ff6cfa74febf2d5c0a8a1e9576d39bdb
    md5: 2c669d75d4942de60f6ff5100cac72c2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a90b46878ca7883c704dc1f9c0da50c8
    md5: 50c4788ecb63ce365df8018bb1b0a0a2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_density.res.nc
  hashes:
    binhash: 83be59b8792e868615393fe74f161015
    md5: 4f4034c475b5455202336565b8fcd867
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 80d94dc0df5aef57bd4999d8579afc62
    md5: 2d9db3c8d7a961a07c02102a6bda3419
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 03e93cc73c646d6ffd9c8e276cf3f758
    md5: ac686aff0d7b609caddffc2b8c86d6cd
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_neutral.res.nc
  hashes:
    binhash: dfa1728c92691369f8473615b2634fe0
    md5: 5ca609ba4533e0a4c86ebe9f14327935
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2a1411352e82cfbb6dd94f2e26b1ebba
    md5: 3cb37ddc126b806f73a5b19a43960f76
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 73d8ace38a9e61e26bca041deba21227
    md5: c9871ad846f9b1e9af4e1463f9524069
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2d63d8bdcec50d98e26a8bd58c9e2524
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_solo.res
  hashes:
    binhash: cdc0a2e9b3d38ee2dcbe83097a5e5d14
    md5: caf76dd96e4e9698a5885cf1b60bb032
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: acf22606435c33b4b52276ce1f47c2ea
    md5: 5d18c48d28083f5bc603dbbb1d069ad1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 98d816cb6002e731d5d7d4502561e38d
    md5: 9924f4653f62080cab43aa66307fd5c9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_tracer.res
  hashes:
    binhash: 261bf878135bac1b18789ae4c221c9a5
    md5: 133f9d846d096f7f59cb0c4e8623aab3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3c3c1dcecedbd74e5c961100f5a574c5
    md5: 61606050178d24163dea466a89d5014e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bd5f5d6e3bb730bc869134419f99561f
    md5: c26b344b14075b21876785fe5f443352
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: fc3e0875ee516d0b9e1dec5ffe57d523
    md5: ad44fe7a23175ba51dc4d426eb0b57e2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart161/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6729e1f99c960c15a5ab6c06d953abe1
    md5: eb956e928ba10ac85fa7fc34c095d138
