format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/atmosphere/restart_dump.astart
  hashes:
    binhash: ad431bdd2f0d7f7faa7dff9392d351c8
    md5: 42b10cb414c5bcee6451f5800a7bea69
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/atmosphere/um.res.yaml
  hashes:
    binhash: 6dd305342a84cd969533589da90bc83d
    md5: 0f3cbc8789353d6a3a01cc6ee987f59d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/coupler/a2i.nc
  hashes:
    binhash: 06e1113d34abb804d7c7dc36840b24e5
    md5: 67915842429b002f762f693d5d9a14eb
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/coupler/i2a.nc
  hashes:
    binhash: b02ee3f2ebdfb9a6cb26883228ec26c4
    md5: 558e72a86b5aeefa734529821b81629e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/coupler/o2i.nc
  hashes:
    binhash: 3f9b445fab5922320e7339c0d01bfa03
    md5: 3e43e1f3316e7de4bafe0283dccfc8d6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ice/cice_in.nml
  hashes:
    binhash: 675d69bed00415e2356e01e668ada808
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ice/ice.restart_file
  hashes:
    binhash: ddc26996b133e19cf014e1b4a200f398
    md5: 819372fd32e599d78e43918073e8c651
work/ice/RESTART/iced.2783-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ice/iced.2783-01-01-00000.nc
  hashes:
    binhash: cd86342f3b64ef587041450fbca9248e
    md5: d9bcfb4de405de61fcd078a099284d99
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ice/mice.nc
  hashes:
    binhash: cfd420016480dddf084e19cf84795089
    md5: 30bcbc1e3fabafc554f20a906dc969eb
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_age.res.nc
  hashes:
    binhash: 8b6c26ce4eacefe6b06400c1512b6e06
    md5: 51fcc786b1cea86eacf53e74562907e5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6628341225330b6dff78b6e3c04caac3
    md5: 730db4e80498ebd8e83f57ae95008ebc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: eee1f3f0a627a44cde1597fa6d47c77e
    md5: 4837a2ecd89c54d59a7be8b4c00d0de8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_density.res.nc
  hashes:
    binhash: 35b2d3383f38e35550e31a5e2f382360
    md5: d7188390ad4df74db13e86e7c262c535
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 325bdc7b9ae3c92a2ee6ca2d9b963922
    md5: 27a6f2a5d3058d28d69a450f6f35448e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: be6654e058c7a99420534c64c83af75c
    md5: 0fc33bb856145c4c4647bedc0ee8723b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f6edd027c305372953a59086d913589a
    md5: 43909af6c1ba131cf998fcb6a69f8a97
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f916d8e8995d86df7c9e367be13bea46
    md5: 60c11d80369e8bd7916921caff5da440
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 03ace9f1faf7f05ef47838287906fd68
    md5: 9db725fae25a74f5b92c37a5d6e29dd5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8f38a017a09ed0af0c8d39c25535d0db
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_solo.res
  hashes:
    binhash: 4fa8cd011b98d1e9562cdc1c321bea14
    md5: a12c65f61d46a63ea278f93470f62d90
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7400189e94ba5380ceb4936baf7b5a66
    md5: b5dd971f33a1d14a21bde58ff414f17f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b812052b1bb53146c8ffde842f994ec3
    md5: d1f6210638106fc10c30f72edae0f5ec
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_tracer.res
  hashes:
    binhash: f353b64a9336c33988fe7b406977fcf6
    md5: ed04f8ce6e9c4a96482af0cecea5aebc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 815261ed95042ef40a1b08cad701cf93
    md5: b495b7c4ee73e3cf230cfe6c913601d3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0437b8bd4a823ce7d1de32c1a0cab584
    md5: 2417f9f029e75d4a76c03edd66831686
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cab184959c12c80297375dba668eb9f0
    md5: 907f8cc56396af99eb5e9ee225d1b657
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart106/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 14c7e2a3bc1e8f00c954ceaaf32c5e9a
    md5: 2453f300cb37f21c3b340decf4ce8533
