format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/atmosphere/restart_dump.astart
  hashes:
    binhash: e62e3214351f47e0f51dd1c9bb65fbe6
    md5: ce26a7603364def5518179f80ce89e44
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/atmosphere/um.res.yaml
  hashes:
    binhash: 6bb11645b6ed13c5b4189c34e2c1eb73
    md5: a255b05773140da7e176b98bf405a450
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/coupler/a2i.nc
  hashes:
    binhash: ac8d229ce0354970db749dadffa71458
    md5: bc4b255d798b2bd4c5c55f7faeefd589
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/coupler/i2a.nc
  hashes:
    binhash: 12ebb87afebb2fa6f238740e74fd9640
    md5: b3aa8056fc6ae86cf70a56751829c191
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/coupler/o2i.nc
  hashes:
    binhash: a94c3afbf99634399d01b67cfe4aecbd
    md5: d70d498fa57fb3fc6c1362dbf6f176ef
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ice/cice_in.nml
  hashes:
    binhash: 1432a539c0abd8d89e38de2b67bb9fe2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ice/ice.restart_file
  hashes:
    binhash: 8a3927a8b8dad97ceec1725218241a38
    md5: 07e7dbe9f6231ae1874d416c8bd03bd1
work/ice/RESTART/iced.2696-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ice/iced.2696-01-01-00000.nc
  hashes:
    binhash: fe84298f0d12276e84fbcea57e72365e
    md5: 2d32905cfd865f48ee4b7258a0739855
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ice/mice.nc
  hashes:
    binhash: 15b928c400146d26874024d7e626db99
    md5: 9e7462bba7ca256318a9bc6912c4bb88
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_age.res.nc
  hashes:
    binhash: b38a6b0f63eb94e1ae97c16ec5f0d9ea
    md5: a972e89624d6df4ac9d93aab22f51868
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6cd48ce3a0ab2ab1ba91f7ded05fc4d7
    md5: 74c3f6f719081ec28f2e83ff73eba306
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ded7fdf9c01b57eea94f4a44da966221
    md5: 0bac3a672bf4407bd5f71eb8fb471de1
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_density.res.nc
  hashes:
    binhash: e2e0753108649c2ed3425818e2b2fa83
    md5: 2f70a92226a71bb8a87fdd6cd882f6ec
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 054dd75b2172419d0eb212ecd890a488
    md5: 0e0fe0fb75821fc5c37423c259d1ab4f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8e92cfbda332a5bcbde9cbf9446e842f
    md5: b53f00bd9ad553144a828f1b22138359
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f9f576f17897c2e6a776b61c1cd61a7b
    md5: ca03beea03a58d48d03694eca6b360c1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 07297e78df1137bbaf4159cf18aa82d6
    md5: 894914c2a2c40e5be82fcceeca0e1633
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4a9df8468a3c86ff59f6eb2a23ed0c88
    md5: 2643a9a6ecbfcb2216173c34b050ee7a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 66e9dab57bfa5db8e154591f5d0bfd54
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_solo.res
  hashes:
    binhash: 5df6bad38220e4c68ce306dcceaa603b
    md5: e134c514732ea06f2f92e77fb55d0bc9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 44bed03674f1f00b07e58c67622d0634
    md5: 7c5e826547abe8e212c40986c6911ca3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6310b02742277f9851144a9750657e7e
    md5: 4dee9e5ef642df1a4860acc1b8e071e2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_tracer.res
  hashes:
    binhash: 5889eb5a777ae9e35801c44e7c71447b
    md5: cc10985c7dcfae8422ee7233b93387ae
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_velocity.res.nc
  hashes:
    binhash: afd1e2ae418a1141f76ec21490999cf1
    md5: 425af35be23e837f13dcd1ebe457b695
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 677389ff540e523ba94a7e833eb60cef
    md5: 8e0965f934d262a633423d9b47e1f91a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5c7286050c0b3ad8a7c3d26322c85c8d
    md5: 9ba494c87a0ce26706c47df7d556ea3c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart019/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a90bddbbfb1f63173ae1772adce6d69d
    md5: 9e3ab1896de41338705afe4480d314bf
