format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/atmosphere/restart_dump.astart
  hashes:
    binhash: efc0afb945422922865691c4ce89aae5
    md5: c333dc6e7b26837147f78f07898972f2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/atmosphere/um.res.yaml
  hashes:
    binhash: 736eab5d4295ce6ceb8d8f1cae26204d
    md5: a1fa166b6f56ac2b3c52a6df3392ceb4
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/coupler/a2i.nc
  hashes:
    binhash: d1eb9d741f35178be7ba182409ab5a63
    md5: 634c1a712e2b265bc0c2d851612abecb
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/coupler/i2a.nc
  hashes:
    binhash: 69daee2db9a6278d1c003fd0f3adec31
    md5: ef8f5f7f4e40de1693b6abcfa49ebb26
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/coupler/o2i.nc
  hashes:
    binhash: c8a2d7cf050b061cab2348d414299ff5
    md5: 22f4dad34f7d21d50dffa6b198e8a9ef
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ice/cice_in.nml
  hashes:
    binhash: a3b0c9a7979ac222184908b91cfeea12
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ice/ice.restart_file
  hashes:
    binhash: 4f2e1cf6659f51492e86fba74a768e62
    md5: 2de09631212bc42b65c0043f2ea35d2d
work/ice/RESTART/iced.2706-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ice/iced.2706-01-01-00000.nc
  hashes:
    binhash: 22bf5ad87f01430f6c5306189b1167ed
    md5: 982c1da9e41e875592eb123e951390e0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ice/mice.nc
  hashes:
    binhash: 8848005c6c98e5a3b763657f6302b2ce
    md5: 9977db338dc0dc573d1d7c0b8e8422de
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_age.res.nc
  hashes:
    binhash: c12048e51290a3e3a7e7a7784b992ac6
    md5: b15e3632a56c928ce4687d9433983c12
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 746453a0ce47192105c702764f371d93
    md5: 564f55ae4e519a37d4437fbf698a4fe1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cf3b7ab8b3cdf37db70fc2736ac492eb
    md5: 01b1e0b725c344e33d395a7b374c294b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_density.res.nc
  hashes:
    binhash: d6fb6808881aa0e03742cbebcb859103
    md5: 25a268faf51a2a2f35bc3a181bac4b67
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 48289aa16920d0a1aeec9903ea1c8421
    md5: a9749a6379bac7dd85bb52743101da3a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9e6920ed086e009d435709168c1138a2
    md5: 4227ea706d261e817564f8875784eb4b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 278a265566d6409d970ff8bf1c60bbf2
    md5: 1ebc876ecb4d4da18d84e22d8b8e72c4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9d9942eb2dc655d57733cd33fd92ab7d
    md5: f55842c50ceb5838a45ad78e1e90226d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f7b8764d1d2aeed8e43ca083204694c9
    md5: 78381937068d6f19c4c3abe840df3656
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3122980f93e36095a1fd30184a799659
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_solo.res
  hashes:
    binhash: 2d668e1c8668f43e9d1de7c5206347a5
    md5: c01db37488ffb9337f6cf93221ab51d4
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8500f712b77509612f953e9e80c2be70
    md5: b3899302b09007bc074c8db2c5dbaf73
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 501d366feeecde5b8c7593ea2203a295
    md5: 07eed2997940ec8e659e52daa42a754e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_tracer.res
  hashes:
    binhash: c3eab9f8e7bb4c0ed2c6ec4519da4dae
    md5: d00e05eedece4c1d45f841e650cd380b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 892b1ac0a49dae458934456c9dd689d5
    md5: 9045e3d2fdf596a69fd9f3149d004147
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e6f23d10a717ecdae5781d31280c88f1
    md5: 4a42b4e32052a9cf8587ba04841f09ce
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 39aa323a7250be6b5b6dd27b9fdd51e1
    md5: 9af89e64b0caa71f6c5cc349d894edb1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart029/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 94403a6dd558d4c8f79264f74ef7d031
    md5: 0c63e7ebe8c84e3873ef3e8124fe68f3
