format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/atmosphere/restart_dump.astart
  hashes:
    binhash: bb0cfddc1426496721b197d111cd6bda
    md5: bbd5938276d2595bd6a700f34c81f649
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/atmosphere/um.res.yaml
  hashes:
    binhash: 7893d419ed28994201eab33aad3816b2
    md5: 7798b54d910e69e22f8019a0fa612eb6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/coupler/a2i.nc
  hashes:
    binhash: d4cb97636b13ed46d9984b542d5ce6c8
    md5: 1b7fe8b9d067dbee28e19a8b421914ec
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/coupler/i2a.nc
  hashes:
    binhash: e54b89d78976fa6e0d8d808079730057
    md5: 237f4a9d6bf3e9102ed481aa67adefa6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/coupler/o2i.nc
  hashes:
    binhash: ba2e9ed326c42e82ea117a043cd5dceb
    md5: ef71b6850ec61ef09128a79df5fd4a38
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ice/cice_in.nml
  hashes:
    binhash: 13e325f8893845c64cbf59b8f3b5bbaf
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ice/ice.restart_file
  hashes:
    binhash: 7b9e622cb1471e7f76127b49419bbabb
    md5: b5e306b7d1f54be3ec9a9e2ac826098f
work/ice/RESTART/iced.2840-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ice/iced.2840-01-01-00000.nc
  hashes:
    binhash: 2548fb80e3eb23d7a41575b7a3e7e507
    md5: d84bc82101761c29e9c7fb8e89286359
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ice/mice.nc
  hashes:
    binhash: a575379a05a0e1a2845f2e122076793b
    md5: 70557a38173a20092865f57f7e2c0e21
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_age.res.nc
  hashes:
    binhash: 308d9adca70477b1b2c54ab90d11ed02
    md5: 59b00528287ae1f1201dae667e710f13
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 59378d82935237f77180c6bf8a4ba8be
    md5: 6b276061ca7fb2905c7b382c3727c402
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 657e6a8e529ad7709b30d1058271f4b1
    md5: b6359a249b20e566cf72998b0e32aba4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_density.res.nc
  hashes:
    binhash: 2f020826de191d157bf58203b622e5d7
    md5: 638615341e51552d64b53f0990d00122
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 15997b475b52853fc0ac1b97075c9058
    md5: 50003acf0ee4a8a4b97b7a3294f24689
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 947a1cdfc7980e703d004a4f125088ea
    md5: f3a2126c45d1dea313ce638b28fac66f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 62311352b5cee0fa42722f27710a1ce0
    md5: 05a04270b0ed7b90cd829b94db1dceeb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d93195448a24d396ed2e58aff690eeb2
    md5: 7c03508d663874e668097e30736cb853
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 549bb7ba20012542a4a08bc722bd2e43
    md5: 0abbc76a608fa9879902a5eaf2447e4a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1dffc86a74d0fd5e4818b89bc6cb8622
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_solo.res
  hashes:
    binhash: 31324f046437ed8578025e40cb6c86e3
    md5: 719fcf170c36a4b6c870c70392200db6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4643715694a1c9f441f254e30192950f
    md5: 8e1ffcba8c95f76187bfdbdbef55292d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c8d548407f563a52a63add4142d0ef13
    md5: 697c10b2857c9dc56bff0c34aa52b230
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_tracer.res
  hashes:
    binhash: 072973e6a0b1596f3d6021cd54322159
    md5: 85c2c368be9c8e272a24e6761d96df18
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9c4d99984bce48ae067af382505cfc1f
    md5: 7558dca0a3a6ae9fdcd4fd440e957e9a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ed83b1b2ee4fff150e911091d40064b1
    md5: 6f07275b6c8731bce439eb8dbc994be6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7cd3a889c1f73c12c601375108481bfb
    md5: 4397e66210e2de4c74de2337c124a6d3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart163/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 646b237baab93f6a921f23e34d0f6aef
    md5: b530cbdc947678e3c7b32f0da7e4053e
