format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/atmosphere/restart_dump.astart
  hashes:
    binhash: 41377bf80b799d73dba2deaf1c7813fa
    md5: 0f1781eb272f8b79f7b732047721a7ee
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/atmosphere/um.res.yaml
  hashes:
    binhash: e7586b099ad4dcdba07bc129dc892a23
    md5: a4ad17b4c7246631c6c023bb435b71fd
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/coupler/a2i.nc
  hashes:
    binhash: bc1d0f2d7c909cb4f2093df332155fa5
    md5: cb42589944010d697d9f01e16f4ed71c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/coupler/i2a.nc
  hashes:
    binhash: 37fdf644b945bc48335efaa79c371cc8
    md5: 333be848c99a8c7a8f84081cfdbbeb2b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/coupler/o2i.nc
  hashes:
    binhash: b688d27b32a7ea407e378cf1a9a92b47
    md5: 19b5b264bc41b6234c28eda73de12ad9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ice/cice_in.nml
  hashes:
    binhash: a332051785a9841f42f7e8c51585cfdb
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ice/ice.restart_file
  hashes:
    binhash: f2232afc85f75f21f5ff66ecedcb2d91
    md5: 31a78e3eaa9109a2bebd2d4f5b92be67
work/ice/RESTART/iced.2797-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ice/iced.2797-01-01-00000.nc
  hashes:
    binhash: 70f9402b4f52c16bfe33581b6c3e15da
    md5: 9632c7a62c822d4bfdea7a9616527c16
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ice/mice.nc
  hashes:
    binhash: 822f3a802651db28dc6393228598b6a5
    md5: f02ad1e50814409fcd3e0bf3a1f20fbf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_age.res.nc
  hashes:
    binhash: 839b096c8ef03c5d5e5391e89ee82c0a
    md5: 837b0929e12f00afc3b787f32d5fd1a1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4a87db1813e3a239a0ccd427f484b6eb
    md5: 88280eeebcfd32b7c1d55c06a669e11d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ce4c0b6bb0906a61e0faf7181bc1bc41
    md5: 6d4053d05a5e6640ca020b5d20407ec7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_density.res.nc
  hashes:
    binhash: b589d735ed44bc8192bfb21fac82f346
    md5: 28c7a383c2a1154ff1673c6f35204be8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fd080fb9cac3566cba8ca2d61c8acec5
    md5: 2b4a9b53982abf10daaea18975555591
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9accb00cdb636339827afab8bb7cfa5e
    md5: 910e30a178745ceeb09a6c9491f9dd41
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 105158727e7a2ead0b43d345d19d2db7
    md5: 0e52c111fdb869cdbf6c0861b10709e8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8edff80ff9759989d6e5925ad5215e15
    md5: 70d738ff17e6936716b1622cbc8ec47f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 49ac9c0c075cc2754b50bfd3059c01e8
    md5: 66b61e587939f27c6020659934ef001a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 014799d0dd14e0f56ad2491036c92ae4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_solo.res
  hashes:
    binhash: 1730341675e18b49fb6002ee1d969f05
    md5: 29a5256ba20966aa31e268fd0f77c132
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fcf1d876fa4e747f0ac99a2f05ba18d1
    md5: 2dfe592362a9a33c4ac03b0b699bc64c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5062e1130d7de53055d18a256c9adf42
    md5: d48a1770cf8cc7b15adef3b6cedbebac
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_tracer.res
  hashes:
    binhash: fe6040f052bfd5138caef0ad78c17025
    md5: 4688fa20a92d80be0febcc9d23f657b4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ad37c35d73b87259b2b57b5a41f1285d
    md5: 92f8f9bd9001500eeba98ab7d896ac4e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: adf87961e78774ab9e2be264d29f7037
    md5: 1b2d1e58c2358274df83690f741c55c5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 42e665e75a50edc3faeda92083dcaaaa
    md5: 0357c72d34119f6b0da946db87165183
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart120/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e481fb7983897b8802677c0f82bcc47c
    md5: ba08ad945f8e93f83ea715190fbb069d
