format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/atmosphere/restart_dump.astart
  hashes:
    binhash: 2cce52981089f82200dd8b6e213fea85
    md5: 0d0098058d8e85e305c05f9fe234ba16
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/atmosphere/um.res.yaml
  hashes:
    binhash: dddaf080744df2280798f9168ff594c3
    md5: 6dae1f786f251ddc905c053cccc5855f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/coupler/a2i.nc
  hashes:
    binhash: 53d2f16eb87eecddd623f6ddb716bd37
    md5: b699f450f82afd0952ef4c2cc887610d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/coupler/i2a.nc
  hashes:
    binhash: dd3165857d95020007fc8aaf21cc4ed1
    md5: bf827083a4bdcd7cd8c2e2b1e043d2ad
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/coupler/o2i.nc
  hashes:
    binhash: 75607ed2c14a039b536ae2420451369d
    md5: 084d46cb74b5a498c1321c9c60442353
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ice/cice_in.nml
  hashes:
    binhash: d6d223397b5c3b2502df04e4321bde7d
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ice/ice.restart_file
  hashes:
    binhash: 5f5fabc05bdffbef54ef247d86e98550
    md5: f5ee9e51d0264fe61e1eb846055f523b
work/ice/RESTART/iced.2958-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ice/iced.2958-01-01-00000.nc
  hashes:
    binhash: 220dcacf7cf2120a7232ca7d003d10a8
    md5: 69e75d5094cf86f44dfa871a1f1b1feb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ice/mice.nc
  hashes:
    binhash: 8b94602878526bd0faaaa07f8f92cb20
    md5: 28c8c4b7546c7ccbd0cc1a0b2f573ab1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_age.res.nc
  hashes:
    binhash: 0275ff9e1f8309be2463daa81cddfe92
    md5: 1608fad805ba686c1f4742d3034976aa
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 405b65aa8a10fae46efe381c65e035da
    md5: f8383c821ba74e42f8e8ea0f3851332c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fcaf9ba211118d8f3764f24b261f69c4
    md5: 7496a969ff2f65a77f476a0d19d24cb7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_density.res.nc
  hashes:
    binhash: 254d171a14895142c53e932a97ec05ab
    md5: 85a9b0c72c3cade921abbe032cb7cd42
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d6825dcd0016d8ef0ec86f2b35037898
    md5: 9735f8a867d49a4335dcab4f986ca06d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e9c29d232d75b7ccf5089d96f9a86f6a
    md5: de11eddea23a701edcfd2f674d09c26b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3ad2d888b25f772fcbf3b20a758b3121
    md5: f2df8310a3ec86764e6f81107832c4a2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6ff80965e68e8933554f715c9b1d5892
    md5: 0b7d944df6c47b9e840a63677737507f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e9485d7fce5408e0fd9360a9f283b55a
    md5: db4a24109c60ae79e8218fb80a57e92c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 59e0f95fbefe85d13e4b4b909a9e9bb0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_solo.res
  hashes:
    binhash: 63444e78c82c48cca3d13abfb674044b
    md5: 07bcb1e7c1510ea5cdffde47bc6e5ee0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a47cc0981e9817883b7109e3453c342a
    md5: 3c8ed72a52164631214ffbdc35829a08
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0fd86aacda6a0f0adcb2d2e2a8a5a82a
    md5: e8e611482fe0fb1f6681eb0857bf4d6c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_tracer.res
  hashes:
    binhash: 0e105815277cbf474283a81701b8843a
    md5: 7b354cae4db6614bd9ddd0c5f9bd71e0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1ea53d70fac91ff12d7509a7eb908851
    md5: 1fdd3e15d0b8b41f5c6155f663d60c26
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d54cbc865e16833884c26550b36c4e65
    md5: f25d724adfb19b6c292341c0d78d8eba
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6a958126926712f3062efcde92c0d671
    md5: 341f89412cc9eecc35c52a5b1d8672d2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart281/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: eaa596f56df8d350d2a6a482ca9812dd
    md5: ee3ef0050cff3273477053aae6f4301d
