format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/atmosphere/restart_dump.astart
  hashes:
    binhash: 978eb436d4fe030af41a35f39591ff5c
    md5: b98cd00aac5d1a3b40af91dd439372d6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/atmosphere/um.res.yaml
  hashes:
    binhash: 87a887db0bf75d19afe09ff14d77df97
    md5: 1e534aeb56d13997ef6758c13efe0ad2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/coupler/a2i.nc
  hashes:
    binhash: 428abde051871b2b66442378942ced57
    md5: c4cf5b24b146afb05d31183a55ccbfa4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/coupler/i2a.nc
  hashes:
    binhash: 6bbf0d7501859f3399c5d9ee8f6dc28b
    md5: 41919d4d94b16945a03f3e7e7ec9bf52
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/coupler/o2i.nc
  hashes:
    binhash: 3092e496d44f7849c371b44b884d0afe
    md5: ddc288dd42fc2cd96a0cd5942ea43d1a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ice/cice_in.nml
  hashes:
    binhash: 3235f382968921e5292f767f8677f565
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ice/ice.restart_file
  hashes:
    binhash: 59fd2bb1ff3ca86a80399c3288658d80
    md5: c1b71c2fe37594ce98198d498036c3f8
work/ice/RESTART/iced.2729-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ice/iced.2729-01-01-00000.nc
  hashes:
    binhash: 2f3f44b07ea7baae64eaab968010f511
    md5: 83935878ad1c979b5b161e3ecde97be5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ice/mice.nc
  hashes:
    binhash: fc540f850018706dcd637b2964f1570f
    md5: f69492bfd22a454db101435560287e28
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_age.res.nc
  hashes:
    binhash: 746d2f23b205d3cc10acd2a0fc445e95
    md5: 0cf60374bc13f3c8c73a4a1095b4fb87
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5b56339d199945aa0db244bab87af338
    md5: 54cfeea825474355ef9981db440961ae
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7474e8c2cf6e01185e957a941e4ba44f
    md5: 28433a522214580f5db8a3212bd078fc
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_density.res.nc
  hashes:
    binhash: 188bc58554256521a8ab2a9f45ace421
    md5: 7ea46a04a74947bc144af9f56d3401aa
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d89ee24b216119c1d600806fd5dbdf6b
    md5: 9835c2297125876c14765e930ad24a03
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 281917f504cfe179b51294c81cbfc8f8
    md5: 77349c44d23919b37ff55a4e49d111d6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3e85cf3d5d91535a44886a6eca5bf1f6
    md5: 173dcaa05c1e97bcecdde39d723f9ad7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0e9761743c98a553d6951cc6287c35b3
    md5: e8cf863a7885260a5b6b0490591fdeb6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ef842cb229fdb78b71c6a0c44fc78617
    md5: 2555be38fa4250790d2207ac71bc2ff6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 542cb6c447f95672c24bad9c4dbfae5d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_solo.res
  hashes:
    binhash: a8ff0d9052555929d6db7e4f38e88a17
    md5: fd8b3fb85a1ca4ec72563a181164e526
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1e34cf92da4344b88e7b89e39858fa15
    md5: 42cd49be36142d5d4208f02fd51a5354
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 14a616894971d3adf9ecc3b54255f0a9
    md5: 81ae072f62ec2453fa820b94351b14da
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_tracer.res
  hashes:
    binhash: 819decd9d535c5a7132073ccadbbdbbf
    md5: 2a8b788cfb29bdadd56caea50a16491e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5ed4618ecebab4d0c6fbc13d958e390c
    md5: 4308db01c0e827700e4780b2bcfb21cb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 061fd00a52942ec76aa0663fa94c19d9
    md5: 87d619b842fb1aefe3926a535d9c6f92
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: bd860b47214b6f169bc28e2287fb55d0
    md5: 4d3e82b776e1fea0fbc89f6c2750c0cd
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart052/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c1908af2bab927889b7d03effc168646
    md5: 543b002f3c4f50655c1f622811aa6f58
