format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/atmosphere/restart_dump.astart
  hashes:
    binhash: 0e9a6a4c711d74e28b8dbd0e5c01d7a5
    md5: b7484916de4e3ac5eff2c58070229554
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/atmosphere/um.res.yaml
  hashes:
    binhash: f8fffafc5bdabbe76118604ed08747fc
    md5: 55ddbe74b4a486605215626d3af44528
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/coupler/a2i.nc
  hashes:
    binhash: bb8714838f27a84b05061cb43a17722d
    md5: 44752bacdd21980eda89b6186f00ca80
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/coupler/i2a.nc
  hashes:
    binhash: d4d53541a6f1c9b29ee752b5a74f2a60
    md5: a03048476d520c330ed9de0729b0c3c8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/coupler/o2i.nc
  hashes:
    binhash: edb7f3b9d81266dcd3fb80d5facc2384
    md5: 56565b8284f29ab6f51a91df9f82ce63
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ice/cice_in.nml
  hashes:
    binhash: 2327da26b0804a53442c039e59717006
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ice/ice.restart_file
  hashes:
    binhash: d8d8fe9d21ed304143486e2708f10175
    md5: 31418680a94fcb9ef793750b8d84beaf
work/ice/RESTART/iced.2815-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ice/iced.2815-01-01-00000.nc
  hashes:
    binhash: 08a0864ab2140e9612dc1b5b15bf2333
    md5: f88dd7f236140784156061742ee3280a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ice/mice.nc
  hashes:
    binhash: 739093313ab65aa21345c5ca2b32f2c1
    md5: 8168b22393f74c32515b6ce733a021da
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_age.res.nc
  hashes:
    binhash: 549cf656fab802484b9cb2af66dc3cf5
    md5: 3c6dc25dabeaf196afa79ac53fc4d77a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5e182e29ef763680e83393296e2c8163
    md5: a21497ec3f118cb9317793c0914f7438
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 960bd572f235c586a708885deb30a1c0
    md5: 0eef756e96b60aeb25c16137f6d789e6
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_density.res.nc
  hashes:
    binhash: 409e48d8b8fcf5d0efe9208755639c25
    md5: 7b6b1865e9ad1cc7fd6e3da65d6151ed
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f85a28aeb89af5dae0f8a637c775f9ad
    md5: 8a342831b94d3e20e81b69e77563c892
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: fdc1ddc2fbc0cf5ba4da2fe284ebedf5
    md5: 0b8f9a65d6b64ab6a63f2e77fe4faee2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 16cfec592217760eb4ddb79654de724a
    md5: c0139a3086768f9767c3d824666ace2b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 33fff32d04928d1f79f8fdfc2ddff22b
    md5: f0f7d326d00666237927a4b96f384832
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5b11febea4f3073540cb6ce8a3e02ae9
    md5: 4df68bc514fe21478b61f31d0e989c05
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f813af19034931c40d8815df7255eb2e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_solo.res
  hashes:
    binhash: acd02a47270d3ab48fe826fcd7639c29
    md5: b4a97b9284c173e0c42e4ff8f44f678c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 853fa50dcfb698f870790454d0149d34
    md5: 4a6791519379655d81103cb47a8b0c51
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d7291c62f3c2fcf0671242431e86519c
    md5: 9c176a9676fbca4e219d1acfe6171582
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_tracer.res
  hashes:
    binhash: a05257e065f6ea358efe42689e6802d9
    md5: 0f0457ee277f85d6c32f9e8f43918fe4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2ef4a501c2bddaf09eec101339a70041
    md5: f3f04c39845da41b6fb39f548aed9718
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5415c18284aecda24342ce31a7d7f230
    md5: 5c340c2bb347c981a12bed252aed3110
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: dfa9d01bfe37df5499bab950a58a97b7
    md5: ab87e15c23b54c1bddc58d6468081af6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart138/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d10c37be069c3644d4f16dea13166d9b
    md5: abf2587f10e81723e0413e3f103de8fc
