format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/atmosphere/restart_dump.astart
  hashes:
    binhash: b3c9f87bef305b4be0b6a79f19cf2938
    md5: 8bfae703b1935f38a592a89a5e3d48cf
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/atmosphere/um.res.yaml
  hashes:
    binhash: 70a1c8c298e250da2287bad027616113
    md5: 61e17ddbbad89e0d2bba0fb6d10d5525
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/coupler/a2i.nc
  hashes:
    binhash: f5fca1f3eecee9a5c57333c74f0199f8
    md5: 6e91a57ac0062b2a744ef3ada46c5eb7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/coupler/i2a.nc
  hashes:
    binhash: 8de9a1f6278a4fedf861d65f14951ab7
    md5: 1f85b0f132ed89dfc056f1872b9ab06c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/coupler/o2i.nc
  hashes:
    binhash: 57053a685dd28427923ce5e4f5a70447
    md5: 5013ba504f797c6304da79e64a2ad2d1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ice/cice_in.nml
  hashes:
    binhash: 169d632a428b87798b6837c91f50bc25
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ice/ice.restart_file
  hashes:
    binhash: b449918a4d036d4f843b7fc4e2fa8950
    md5: 0930d16d7ec95ce99b0fd491156654ef
work/ice/RESTART/iced.2760-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ice/iced.2760-01-01-00000.nc
  hashes:
    binhash: 2fcb75820ac053f25d8e64b05957eb47
    md5: 50204c0e30149e56dc7eb92673b76525
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ice/mice.nc
  hashes:
    binhash: c391203ac8e4630d68c892b3f46619b3
    md5: 6bb88c5d8adad5db0e5dd1d119f732ae
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_age.res.nc
  hashes:
    binhash: aa76a4aa51b035f1395c61624b57a272
    md5: 248c66dba6d35f96dd1194dc7bac8c7d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2a7656d2e8ae4fe1a3bc0605f7b41321
    md5: fb7e525c05ee49980908862181a5d7ba
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7c7545f86890ec8b9de8ba7e588427a4
    md5: c4985d38700b1378942f7ab8f33513fa
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_density.res.nc
  hashes:
    binhash: 211a4d54ea7159e735eae0de261ccf8c
    md5: e9391645652906b39235208b46d9bfcd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1d839315309b38c96c5c4f1eb6849bc4
    md5: baeee5fca99bcb1900a0c4311d563b17
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a1f7857b3d9c1325d874efa42321fd7c
    md5: 9468a4aa12887c057526c8953d273184
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ba1cfce465772042be1e9cf1b96a0063
    md5: 1254327c7ab674a638d16620d14009e8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8e498a01939b404872c1fd3a4b81b58d
    md5: 22a3cf04f9da20e16a63c8e8bba21fe9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9f9192002b127b9dd9d683ddebede172
    md5: d50fe2ea0d8fc4993f82e4ff336fe4d5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5003eac1d9904ee84d048a2efaac474f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_solo.res
  hashes:
    binhash: ddcd8a8ff18b481f8d5cfcc5d258d59c
    md5: e93d32cbada57bf3d25feef8c58da9e7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 91989e8189b12e2576969bf6e1814fb3
    md5: 7811fc2d254081c11db64836a54f7353
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4248b78736d841a8c2a85674cac6b5f5
    md5: 997ef033eda1b5b563ce0db49fc88519
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_tracer.res
  hashes:
    binhash: f4492757885c2ff9525175fab78ad85a
    md5: f2c769053a7b1ae261aabcd0d20de6d7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 01122f722d8c7a94b0e0448e3ebe7126
    md5: 69e7f90e83c0a3e7de32b542b7dfcf24
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6991a8444ba185f97d5d6977dba8e7ca
    md5: c884cfa7915fda9a421c6a10567d6031
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 05e6e6e4b2a3f9d21743695cff3d1514
    md5: 2457a4ab7e0f3d4ffb28d471c9286f62
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart083/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 210c2a81f54fdfb05ce567565469e1e9
    md5: 3b6dae842e7e279c16e61a808fe6f173
