format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/atmosphere/restart_dump.astart
  hashes:
    binhash: da1b0f58ea3eed0c1735f1b10e9e0759
    md5: db05a0aa0b286d3cf4b53a4eed0dcdaa
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/atmosphere/um.res.yaml
  hashes:
    binhash: e551c6ef837e51a1913d63d2cc648337
    md5: 0645a3e2f7e7d799264d864837a58156
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/coupler/a2i.nc
  hashes:
    binhash: 4160fd8d8b9a3e5f1ea6fce3cd5c366e
    md5: 4360723d6f74c0807589b97a19e7c794
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/coupler/i2a.nc
  hashes:
    binhash: 29df5a96eb7bd6bc99ff168984afb71b
    md5: 7e940da5f186cc10f0b0a777b856b744
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/coupler/o2i.nc
  hashes:
    binhash: f62954e2ff5d72c79f0dc6bae0bacbd2
    md5: adc13cc2d4a92085200f57a13979a831
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ice/cice_in.nml
  hashes:
    binhash: 21118fc35b7447882614a09cad35132d
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ice/ice.restart_file
  hashes:
    binhash: 828accc129e5bd3eb449be7807540cc5
    md5: f3a6610c3abbf6987af6b1a48363aa72
work/ice/RESTART/iced.2902-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ice/iced.2902-01-01-00000.nc
  hashes:
    binhash: 4ce862827d8c9cbb44021252c1338c32
    md5: 8172258e6dc4359098fb1c6bebf4a204
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ice/mice.nc
  hashes:
    binhash: 1fd27672f22b86e5147a5c9fe84021fb
    md5: 7f442766f529895e74b67b1e73f601be
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_age.res.nc
  hashes:
    binhash: 874cac2b13434ee0d15c7432ab3ba855
    md5: 81b4624b3bfb9ee28b9d7c1aa6044bb2
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 34be4d0dfcd2f5fb107a033d03c1232b
    md5: 2243a67eba2292102c896778ad9d88eb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a5b291762ff64571efebcbaa5c9bc7a7
    md5: e3596caf2e4e81b6eabb390395ed49ed
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_density.res.nc
  hashes:
    binhash: dccf0700c70d0ba31fa79eeed4221a16
    md5: 3843111789cd8f81325e34da895fa512
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7a7820298f011a6fc4d6c5fd85e0ca80
    md5: 4fc0000b32af5f5dee4a6b37f8b82f65
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 55f41ec0a58278aeda8681c390bb1f9f
    md5: 171271cde1a25bd3877c495ecb1a3e99
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9b4f17faacdfeb8f3cafa2c26d9da4aa
    md5: e52165c2370eef22a3c14b4cad87c47e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 283aacefac97bd050b3d63073efcd00c
    md5: 64dacd76246e1c4d22cae3607f0fea8a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 90e43b9d21151b667f623a5bc1759981
    md5: 3ebfd8848ffcbf4f471d6b01a85aef75
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8373f760d0355afee2289160dbff8656
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_solo.res
  hashes:
    binhash: 4c0fd2367fdee7badd2e090d490a6a62
    md5: f2856cc132935ade80521dcd0aea4064
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4760e7cbc8bd757d7c7148bd89d03224
    md5: 6bc680fdc6b146711d3d594b848ac42a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 148dc189925fb7fb5fba06322867fc70
    md5: 02150af575f597cd31bdb9e921a61bc5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_tracer.res
  hashes:
    binhash: f3df79ec93e5bae6a8baf3a567c31043
    md5: cfa22992a0527de65295bc030b256bf3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d249f83e912581ef58efce2d227fb3a4
    md5: 95541525f8c84771fe2dec0ded53d7d5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: da28dcc294805b48f4bd4d56394f9944
    md5: a3cccfd074fe586859b840913624b653
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2eb6d86727d24121ded090d2d941ed79
    md5: 35b9aa80fb64164d811fc3e9600a98e8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart225/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 08c67717b5d1f6b417088f7fe7b6c532
    md5: fc491e0fa47f7133a96541677b597f3e
