format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/atmosphere/restart_dump.astart
  hashes:
    binhash: 8ba77db44b72a9c67201fd1fb7def9cb
    md5: c00aa6df60976335bc4aba0c17403997
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/atmosphere/um.res.yaml
  hashes:
    binhash: 84d07aaacfa9d0a21b67d43b0298fa24
    md5: 792945b1a1a2b3f70062edf1bd197126
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/coupler/a2i.nc
  hashes:
    binhash: b69a33e23815f760793c47f74ce01faa
    md5: 8023c92004866624b9089e565e724384
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/coupler/i2a.nc
  hashes:
    binhash: 1ebb30d82371006723869568f51724d7
    md5: 5d7a069e04df730d87dabbd511f54cbe
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/coupler/o2i.nc
  hashes:
    binhash: 7f761895a4f158a826a602cf8d7451c4
    md5: 946d56e4f917d7a272e9ec000bb45971
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ice/cice_in.nml
  hashes:
    binhash: 36b94b5d2bff8e931cf6b0bc6866b01f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ice/ice.restart_file
  hashes:
    binhash: 56b99b539da824bc25cd5466bc98cc81
    md5: fd203fd22946d6a21344a6f0e05cd2db
work/ice/RESTART/iced.2954-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ice/iced.2954-01-01-00000.nc
  hashes:
    binhash: 5de81da893bbfce6f552e21094b5f8a3
    md5: d0a850c5398ed4c933d744bb867fca4b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ice/mice.nc
  hashes:
    binhash: ab501109910fbb7ef90bde8274cc1f61
    md5: e6334b89c613611701e1d52e8bf0a942
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_age.res.nc
  hashes:
    binhash: 314c6d76cdeb0f73b3064053ad56d404
    md5: 258e980af06dc30b52011f0e9f9d306c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 75afce1806daff433cb33ed5678b815d
    md5: 4a56feb727cd01ce804fac0c9167ef96
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4580cab1bfcc2f871d131492e9d4c76d
    md5: c1096c09e2032ad6cb038faaaeb9d0a6
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_density.res.nc
  hashes:
    binhash: b452d169e558d0e1676872e3a38883f9
    md5: 519183636b7e44e9694a132cbb2f4d3c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 78430a32b76b86b4757cb26444338d5a
    md5: f242a88b6eea1876c111ef18145a0dac
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 30ead50e2315101540626d29de6b0491
    md5: 8f3c68599936441199b09ad0e4e5d602
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7f483df6551f364c02e869129fc7d165
    md5: fead94607c5b965363ade6cc65342c82
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c5d4c92906c413d3be72952c9a40b01b
    md5: 69d7488eb6abdf90149b8a47130e4b4c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 47720fd82407b2f40b0b94e1987bbf40
    md5: 960449d684093050f2e22026bf5403f7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3b622dfbfc380323fc89ce21df5fe6d8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_solo.res
  hashes:
    binhash: 1dbda9e8c510aad4b8532030f5eacba5
    md5: 6f5e8bd2beb1b1c6b7de525f042f9417
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 36c22c3d2a869ff03bacc0ed78e710c5
    md5: 7d32678b98f6d3aa83fc4a9c6c38f8a0
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a94b1d5833ad92294dba6e815fbfcb3d
    md5: 0e793a38a072eaa795ee42638058b3bf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_tracer.res
  hashes:
    binhash: c6e5ac7fa300568791add9dea89939a1
    md5: aedc67d10e11efc5b8cfbc52696c1c19
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ced6550be2848aead355b4cea62aa87f
    md5: e97875f68839ec1f2d6e1394ec7c9fc6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b36ea19227ba5549f9c7a8c5c87ad62e
    md5: 18e1b1571a1e5c68d9d2b5c4c6eb5083
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f0294f31698ff44d13a2f78f66dc86ad
    md5: fe1a8639ecc2c0c4a5eb67a40c4cb885
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart277/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 13d2290ea13d38792994c5d5d7015153
    md5: 71ef0e029174d0d3f81bdbb1f13630bc
