format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/atmosphere/restart_dump.astart
  hashes:
    binhash: 9e4e5d4cabe71ab1d6347da0b7fd8902
    md5: 64c10a75a5486af13cacc8fd79437f42
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/atmosphere/um.res.yaml
  hashes:
    binhash: 44cb1934527e029d5d727774ce707673
    md5: c85d02fe12b26d14f85ab235f539033b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/coupler/a2i.nc
  hashes:
    binhash: faf34b27bd6ce7abf1786402b188a1a1
    md5: 60bdcdba839d21e7be4a1c9cecd8bb4f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/coupler/i2a.nc
  hashes:
    binhash: 419d804959532837c77931a657333233
    md5: 4e75285914276ce07dbc8ad7adfc4a6d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/coupler/o2i.nc
  hashes:
    binhash: cee7dc2385b4cebc002837b09b5fd031
    md5: e68bd07ba625f0c0ee21066516c60ab8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ice/cice_in.nml
  hashes:
    binhash: 3bf3b466b2768f9e91bd3120ecd12a56
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ice/ice.restart_file
  hashes:
    binhash: 13bd3707c2cb27d9719f81d89fde6078
    md5: 3bcaf33288d9e85b574f2b37abae4ac5
work/ice/RESTART/iced.2753-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ice/iced.2753-01-01-00000.nc
  hashes:
    binhash: 2f8243af62dac32fb6e26075ad6175b2
    md5: 93b33ef894a15cf4cecb457c4e36729f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ice/mice.nc
  hashes:
    binhash: ae75a8ef536dc47ce8dac8ea8e254edf
    md5: 69ae722e434f36e57169d9b2df56007b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_age.res.nc
  hashes:
    binhash: 255f537306d8c79d546f198efdeb7f67
    md5: d93ab6089ed02aa160ceabba4082171e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ada6ffef465f43e719f1c3102230b1a2
    md5: 703134ba021c8a1fe0b63b4f6024cdd4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 92cfc158d8785e311e6b65e29bbee511
    md5: 8d4a5ccc0b81f81c0486f99f6875d271
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_density.res.nc
  hashes:
    binhash: 11189c6359e0e6159ba1d701626336aa
    md5: c98351a54f0017ffc9e654db922d3af1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ed6972edc0f8bc371ab1fd41bed64486
    md5: cedd86ed070206b87a04153fb6620270
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 09469d77cd797375608a3616fb29f8ae
    md5: 02b8b9e18eed6bf4baf81dcd1a0bffa6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 17f72c8b68f3e0fc040eb4d0efd3d1ad
    md5: a3ad3c3b0d7afa72886a9e5dac6a35c9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d209806943b29ce9b381fe74afd6b344
    md5: ee9fa8862e7cf9453b5ebc1181d93b4d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ed42029b075acdf3ed00dcb1bc3f5853
    md5: d4cce65b1b35a71a4f58dcc09793c038
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fadeebf062ef2d1e7178f1e4f8c1618f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_solo.res
  hashes:
    binhash: 12873440a8068ac2f42e9daacaa10516
    md5: e0d15f0164036b5695761c8a629a4622
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 26e4f55d86d5288f189a78b292a5a662
    md5: c92e7f64d5d5a76ce25d9d4fb6a5b5cb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 38a5543e4813088072316877f3f076ca
    md5: 3c54a901ecac628629a2a4f54748fd11
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_tracer.res
  hashes:
    binhash: 6fc615a4632a1ec072bbbd9b659483c0
    md5: 1a3b327a4f281f1ced6c9152fc30f603
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 81c4fbfd05b98d14d2437a38918c2cb5
    md5: 91c3e5e77331c973858627d7fa44e69f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: daaaec87328274c736f087b066f86de7
    md5: dfaef742a97ba6382c11c150ab9f568b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 017921955b28758b90dbdd74fdb6e968
    md5: 81b5c05473b4b5043f953c708c90fe9e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart076/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0b97ad16fa4f2576413dd4db6436d94b
    md5: 30a73095536db6ec89288e44bb5d0f6c
