format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/atmosphere/restart_dump.astart
  hashes:
    binhash: 243b3081f2a372e38351b962c11b9f09
    md5: 2a22aaea6c88dc4ca86cf688bc41bcff
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/atmosphere/um.res.yaml
  hashes:
    binhash: 2a0672e30c47c5ecf26d5b3a7c0a46c9
    md5: 170799c2ddf48d06259dd3d2695e2b63
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/coupler/a2i.nc
  hashes:
    binhash: c12ab696973e18ec6e444b83f93ad1b7
    md5: a2a7f90a5b4244fcbd0814c963994930
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/coupler/i2a.nc
  hashes:
    binhash: 7ef96830d16e38b4aec944590b47092d
    md5: a022d8334c2a6fa3b1485687f2beb444
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/coupler/o2i.nc
  hashes:
    binhash: ef47a82ffc1552280b7d0fcf35ea0279
    md5: b91b0e895689a145bf29350fcda4cdd3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ice/cice_in.nml
  hashes:
    binhash: 64cdee4b6fe364f762398a555c07e39f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ice/ice.restart_file
  hashes:
    binhash: 85ae46570c89e18c008ba48ad23f3875
    md5: 55caaf5f538cef29365e84c7dcad6808
work/ice/RESTART/iced.2899-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ice/iced.2899-01-01-00000.nc
  hashes:
    binhash: 9ebb7e035170766a6161c9fd457c0489
    md5: bfd9ba6a19ca079c4adce405398c7a5f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ice/mice.nc
  hashes:
    binhash: 77362d894af579d0da84dcef0f378086
    md5: 0ff0c7731011ab7515005fe8e4582737
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_age.res.nc
  hashes:
    binhash: c3760b1b4640b2a60bf9a95f4f0c99bf
    md5: 2c0827affd9c1d3b7f56825b2e27b7e8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 303572aa61530a15d281941a136cfbb9
    md5: 7fdf42a73adb240b5b37742a5ba27b5b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 678a0402a673881e3029f3ffea98903e
    md5: e7b4cdde27e15cc10043c454a512f18d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_density.res.nc
  hashes:
    binhash: c526afe071c964c544dece0e5c4dcb88
    md5: 6c444eb11ee471cc7231ea3dbe9f9189
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2d5965d6bf8d8d230a3bd3396a23ed0b
    md5: 823a052d5b3e1b9c93026fab879d064a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c562ecd6c35cf8397314362acaeda39a
    md5: 9a49bbd7e90e5b6c07233c34cab9c876
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3cf7b1f7a3b94fc774d3bd141b7c210e
    md5: 411a92d1896ed50ece95ed341ad77133
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4b9fa595d5f4cec616f9032c62d289e3
    md5: d876e15fbfa2d62b51b11ff1d3abb34b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9cba45240c173566fa62f3858c3f1087
    md5: 5ac172f192f36a1fb8542a58d4cdc06a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 33200099715a1b3e3198fa60c046b452
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_solo.res
  hashes:
    binhash: 529bb318eff0844be74d775827a57635
    md5: be2c49db2c089c05e30decffd2f66d62
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0314eb4206550d9f7a84e0ffd60eabb3
    md5: ee19f838d077fa1a4958fe1ad212f213
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 43ae8f02d45fdd322d063d842cb68c4a
    md5: 561e14fe2478f83b6d2307c508195dce
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_tracer.res
  hashes:
    binhash: 7be0c8660aec6906a64ae28c57565ec2
    md5: 92e77584f9dd3443335c2e13e04f07a1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 45b70280df684ae7e50badda051ab014
    md5: c64e0a5cf46e5261ed89197c5efae5c3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bd79b49abaf34d8aebd16bfdbfb1c47a
    md5: 875f512149865f06dba91b075a4a9b92
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 439c812c96a7fec9ce9eba52615d8b7b
    md5: d6ffaec76688dcf728476d093e68bb7e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart222/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0e3b1b76b379a2a0e504db78197d65b5
    md5: 154e98b7135e185dd1ff57deefa3038b
