format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/atmosphere/restart_dump.astart
  hashes:
    binhash: 1577def7f95ec09d00d5443f40c9dc88
    md5: d88a193e06c7744562f4e0e8207c448b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/atmosphere/um.res.yaml
  hashes:
    binhash: 95f9642d5267f6d3ecbb48215c5cc570
    md5: 6463d72669e45d979590ca435917f25e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/coupler/a2i.nc
  hashes:
    binhash: e4a7f85ace07f4969dc95d9884507fac
    md5: c0866c01e55fa483cb5c607b8e72784e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/coupler/i2a.nc
  hashes:
    binhash: 318c3fd5ce2c63caafdad3fc025879d8
    md5: 47a10a47bbe762ef47207b3ccfcdddaa
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/coupler/o2i.nc
  hashes:
    binhash: 71d41dfae1eafca4ea6c871f4773c61d
    md5: ae8f4c25d6369d16dc03be45a15b995d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ice/cice_in.nml
  hashes:
    binhash: 577c2e4a33d0f18d962d7246ac10220d
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ice/ice.restart_file
  hashes:
    binhash: 74c8938a7637b4aa627deb56f3dd7f8e
    md5: bb34f61466e4fc7170d5636b006bfe31
work/ice/RESTART/iced.2868-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ice/iced.2868-01-01-00000.nc
  hashes:
    binhash: c6e3ff40d303778b9a17dad20c53c48f
    md5: cd3053689c171e813bc96877fffffe81
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ice/mice.nc
  hashes:
    binhash: 14d620f41b42d3d0011b3072a57ecac0
    md5: 91e51f41bceb1a40b87d3f38f8880a4a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_age.res.nc
  hashes:
    binhash: 213c2f991581a5923cbdc193644e6275
    md5: 3795127d3d8a7a666f509c4ebd265dba
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e592f15935cdd4cdc13a37387085092c
    md5: ec5d0b62777dd1840e08c6f027eebd81
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 609be3e82d006835f0ed5598862932b4
    md5: 8ae6b0a5d3fab0c5304fbd8b8473e440
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_density.res.nc
  hashes:
    binhash: 2076b5de9270c13d9d9d9535c983a042
    md5: 9518afc4ea39dded06b0271ec1c78d20
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 53af9758a3932c2488ceb5d2b4b8c287
    md5: 02f54ee6db792e9a33b1b742882cf9b2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6554c299e150ef71828bb3dbcab6a667
    md5: c757c0a941e56ea4a13d4c5e95ab900c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b92ab7d9ea275daad46d3b717b564008
    md5: 39d05c782fc8f724495e9b58f861b547
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f6d03d126508a1fdb7cd8be79b1b8913
    md5: fb8f8a619e60679cf94cbc1fddf8c416
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 626cee71a49a86cbe76fcc7f2d0f4e6e
    md5: 23e972bfd3f5f5a62f682d3c3f06751a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 06eedd250d87bf4649be19d5907b3ecf
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_solo.res
  hashes:
    binhash: 6a6b0f58d0ec5c820f258d90278d1867
    md5: 84ec1d93c592b69c4f6b3dae15285194
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b3e81fd596014e99d9385870beba231a
    md5: 91045d6b7919073b98997867cfa8f7e3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a224de5da3c04fe6629267318a0bd74f
    md5: 844956fa295807ac93ef83a7fd9f80ae
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_tracer.res
  hashes:
    binhash: 7b3756fde2095747a2a391d30cb1c539
    md5: df3355cbee06aed958ce8314f2a52939
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2bf54c0b051c7e87ae7f19804c6b6108
    md5: 741ed457cd64983a2d60e675ece6aeec
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 78df24a1b2e6c27e9603fafeaa84e0a4
    md5: 157650c37f15d4ac0fb537bb8fd46acd
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: eb6d3977cbf177e844a9d2bb29e49983
    md5: b2a9013503322ed1c8c27b7f08415ec4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart191/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: bd8665b1ecbc30cabc20fcc58f1a5a5c
    md5: c979f1791fbb48a41365911b4c047998
