format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/atmosphere/restart_dump.astart
  hashes:
    binhash: dc859ad2a99680afd83c2a57ab7dd856
    md5: ebf72ad94283bcdc50ff90e16ffed218
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/atmosphere/um.res.yaml
  hashes:
    binhash: f7a6a1fc4e061e3c598ac510c65eee2a
    md5: f150ba5a1d4107d20899200b8415b6d8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/coupler/a2i.nc
  hashes:
    binhash: 50b55209fff0a4f53cc590704d47775d
    md5: 1509869f744957f29a26e309f60cf483
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/coupler/i2a.nc
  hashes:
    binhash: 526d1ad39648ddd16247bd95495e642a
    md5: 145469bc2b222327bb0931e774329a0c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/coupler/o2i.nc
  hashes:
    binhash: 5df98b4dbcf2f586559efe7099855ed3
    md5: b7366076ce5bc5d1f2abc0d13956945e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ice/cice_in.nml
  hashes:
    binhash: 7fb1348d1dbed9c0c24676f6708947b8
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ice/ice.restart_file
  hashes:
    binhash: e21fbe0c9fe4e0eddb9d1e0cf7c1fe79
    md5: 6972725c663c23d711aca8420adedd0d
work/ice/RESTART/iced.2710-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ice/iced.2710-01-01-00000.nc
  hashes:
    binhash: 23c70b8bb8bbde7275050135e3ce444f
    md5: 5808720e552968d3defe228b8275799f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ice/mice.nc
  hashes:
    binhash: 6e5919c2856820e06bf47948798f9b32
    md5: 7280159de98a338c7d762092ca2f8474
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_age.res.nc
  hashes:
    binhash: 814fc13c0d113274c45aa5cf59288da0
    md5: b1624e38d29362288b8c02a28bdb1c20
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2665ebda86b7919395c6c81deafa2c38
    md5: 2c92657e12f59c2bf3e72f8ff52dc87e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b5b01ebcdf549e1a74fc983ea2ab0aaa
    md5: a5c3888f1edd7c2e5f7afd3afec87aea
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_density.res.nc
  hashes:
    binhash: 9685aa0d93e0f199de9df8b8a858c237
    md5: b2b59366379d33a0eae87e632758fdcb
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 238bba45a600fbd114fa9f5c0642f803
    md5: 82932737553098e3afb0c12e2c15de27
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5329383f102898ba1dcfc264fa9753c7
    md5: 0ca0fa6bcffc973eeec9a199effeab2c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 18d128358186dccbba7207f94c03b7e2
    md5: aa46b8589d6400d9fdfc99e34515dcc5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: eaff611619a442a91db71aa3563438fe
    md5: efcaf46e6f0e8226766f0c7d2db36caa
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 827714a6c924a32f5efea5cb00ca14b3
    md5: 9feeba12785c1f662bb49729ab729eac
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7abd0a317db64d50504b02e7fdce63c1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_solo.res
  hashes:
    binhash: 615d482c9f2a8a26c1e26f9decd6645c
    md5: ee2854f809ed49cce638fc4aa9e8d156
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fe575c01abe788a9b0e853a335aa5b73
    md5: a8f72286d276e98546437aaa0b541a96
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 12a1e93ab0e9e51d4f6ef5db476d7892
    md5: b78f4cb48b5978d8988a9c7deeed3f1e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_tracer.res
  hashes:
    binhash: b3d53ee434317d3922200c7f720375db
    md5: 933310b5679630b4f3d054644361729f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0bed6f31e060355fae0e49ead317474b
    md5: 97a05f8a8fe89ff0535a4000b747842b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 56f70bbaea2ccbd6769da5afc2fa7bb8
    md5: daa495ffb9d7b0a45eb3695ef84c7669
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 35e75bb9ed19dbad4f394db8d7613359
    md5: 6696784aa4d8092143c725014bdde628
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart033/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6471f4b60e3f03b05c5d0a1208496d59
    md5: 6be5f1f26e5f25515e91363a7cd2ec4e
