format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/atmosphere/restart_dump.astart
  hashes:
    binhash: cce5049cc93476bde7fcd202639ec6f5
    md5: ced8a8b0c121e66be5fb5054f22663ce
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/atmosphere/um.res.yaml
  hashes:
    binhash: a3babc5813abd006ae1383f5ab3ae6e5
    md5: fa76ab10012dab6f32eb7a2713924162
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/coupler/a2i.nc
  hashes:
    binhash: c5ef320050e6310c4e0771db0ce39d10
    md5: cce457411b1060040ef3b65080f65ca3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/coupler/i2a.nc
  hashes:
    binhash: a7cec8a66e48c00570ea16fd112da6b9
    md5: 760b2931d6b5792b0bfcfe89754dc262
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/coupler/o2i.nc
  hashes:
    binhash: 1d1958477067b7b395569e2876e7e3e8
    md5: ceb6552716c950114fc2347baced8d5d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ice/cice_in.nml
  hashes:
    binhash: c091f2b3cd7e4e4825e5206600993bde
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ice/ice.restart_file
  hashes:
    binhash: 5cb4272f0d672b505a73a86575324337
    md5: be322c94f0736a74151ea743eb45c58b
work/ice/RESTART/iced.2725-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ice/iced.2725-01-01-00000.nc
  hashes:
    binhash: ac3a5af5dd879dc6838dfcbfedb55cfd
    md5: af9ce76242da7bb1d34155295466250a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ice/mice.nc
  hashes:
    binhash: 342b133438401541dd2d49170f07563f
    md5: 392ed8551807e88fb3ce1050e390668d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_age.res.nc
  hashes:
    binhash: 391a3cafc774e01192e11e645da490e5
    md5: b9378bd5ea0d1b54bc34de4b1017d810
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6b3ef4915ed086d1637e2dc28a019af4
    md5: ac2d733e7d8fc605999421704d8e7205
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 52976a3a288d8b6afdd4a26a0e6a5cb1
    md5: 979fa3ef5e2ba48e92d018dc372644c7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_density.res.nc
  hashes:
    binhash: 9eef722e5a0963975782b617ea367b7f
    md5: 9990a644383b5ba1691eda87d96a16ef
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e083131f72b48553216312f08254b118
    md5: c2eb0f0f112668757ed80813b65a0c99
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c05861fc2ed0bad1a483cf4397c2f558
    md5: b68f2866c85fcc8c36ed697444f6e341
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6c27d4c9c5e1c8403c49cdaf8a134723
    md5: 7ea18905f2c802ba7356b74e1252c3fd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e97ed5b98e34b4b29c42e35367c3212c
    md5: 322436bc1e50afd5d8fb4f17dd3c1ed1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7dbbed39c4795527eb81eea08b588922
    md5: 3d5306731eb979df628b154a90643029
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 22c66084b5c162b17a5fa05cb1fd6aad
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_solo.res
  hashes:
    binhash: 8f4646010c849aec8fd3c32a0c573a1e
    md5: f31732c9fabf277c737b514d230ee911
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1c208bf1fc8b4060cc46921380e9ebd2
    md5: 1285e95dcea9a731683b3248712e6da9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d0812dcfba5cbd05084f81e8c79771c7
    md5: 5fc9048bba80686af7e47c928b5e9ac6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_tracer.res
  hashes:
    binhash: 1028f175796267f36ad51baeaf3cd94b
    md5: 4e9976d702c701322dcc2f71c897025f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 86fd5b9e6e01d3709db2333e517544a4
    md5: 15262f73e40f20fcbd4b3aa108a77f53
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 71c2d7589e785948d81dea3ddfbaac91
    md5: 4ed3b4a48e096493f6113a5ee178ae71
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cf0a227fc23b557d9e8bfc464c07b614
    md5: f31e41b0fd26f4884c3bee764e27daf7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart048/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b21d147d67daba469eb2400659945f9e
    md5: 30ce45956408028a77587872e0535778
