format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/atmosphere/restart_dump.astart
  hashes:
    binhash: c12bd733d8ca69a705ea88f9d69f042e
    md5: dbf6583521ade22af0cd50bfc1aedc5d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/atmosphere/um.res.yaml
  hashes:
    binhash: bbf15cdb4e5761083a2405f7f63064a4
    md5: 11926d0aba4521133dba7a39c8f946a2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/coupler/a2i.nc
  hashes:
    binhash: c612e640d335973a70555df6924156b3
    md5: a1e3532e3296e6d654994f71eb8beb15
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/coupler/i2a.nc
  hashes:
    binhash: 959aca9041cc3ea14f8c9f13a76645f0
    md5: 3e12565fa1375aded629ce586e418381
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/coupler/o2i.nc
  hashes:
    binhash: a8a02feb4f827c46480b21f5bfbe6840
    md5: a7dcaa106b0c5f3e296bbdd79e1e30f5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ice/cice_in.nml
  hashes:
    binhash: f4f56ac94c32cd153a48c4f96ce1b079
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ice/ice.restart_file
  hashes:
    binhash: 27bbd33b1b21e900c4dac9f481182544
    md5: 0f67aaaec87bd098fcea2b9baf7ee0cb
work/ice/RESTART/iced.2733-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ice/iced.2733-01-01-00000.nc
  hashes:
    binhash: 7a9f9a3ac1c90f8f8936b37907d6e8ee
    md5: e1e148decb8d83051f84cca5cfdf391a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ice/mice.nc
  hashes:
    binhash: 50cf10fcf5fdc11986bca6fdd50b8414
    md5: 1028f8643678c0cd11ea8c589f11d5e1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_age.res.nc
  hashes:
    binhash: 898b6bb232a8a88b021fba79baea1067
    md5: 55c9c434bc91d555f0ab3a20a1be424a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 63c48c333bf752ac4f722e61c83ca262
    md5: 6d208a31a63d92b76c5f51e328f0ee08
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4ca6e4ccd70f273ac083334ffc6ae217
    md5: a2fd30b401b37250bfd1b79a618478f5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_density.res.nc
  hashes:
    binhash: c8348ec734f57f4a650a9faf653dcae8
    md5: 9feeb51b24d89353cbdd20cdbbfcdae6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cae4e4a0976d7763eba6b31457e063a8
    md5: 9722d3f107fa06f808deee079ee8d82c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3e9a368142ae52154013ec0e27b56d1e
    md5: 0c65970285725fc7070c430940a774fa
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2a3533f5fcf813d5015128f1a2bfa07c
    md5: 6fa07d5aa6fc0b8f73fb5b4bc6c7be0e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2e3c5d8ed3f6d83ea3113692f7182e43
    md5: 73b83afe8e285f5fc9ccce16edb76c5d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1e9a46f073a2d8848c7e840e9bf86793
    md5: fba2761deb5bbb391adcc4240cd740b4
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 02b622810306c6e4df877eb008466884
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_solo.res
  hashes:
    binhash: b9aac999c93fdf71aabcba5d3bd28de6
    md5: 0e6c9d9be2231236048dfdae24d0a837
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6668191839f903d805982f9a7ed70b5f
    md5: e6905f5ff428835d173bf421241b7f58
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8408a0b4171ea41f27cae98425b9ed2b
    md5: a580d8b8f548f3b4710487efb216375d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_tracer.res
  hashes:
    binhash: 34377f4e1e7e2ecca026508e99bba3f6
    md5: ddf8bf87c5b16fb9f312923376e03f0c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_velocity.res.nc
  hashes:
    binhash: efa79f9a15b77cdb314b30eff705c1d9
    md5: 54dde034d5894034215f645a418d8879
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: dca86414825e4c7e5604e13341cc46b4
    md5: b239f6d03c9cdf4f1e34a6d2e4aa2512
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3441ea3b35c8607af3b7e081be47dfeb
    md5: a08fa64daf61f25748a9e9cc2066715d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart056/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9c92f9dc606e9c4bae3fbc1a5e0bec25
    md5: 58c6b9e8118e23ee9c86cb8fdc8f375d
