format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/atmosphere/restart_dump.astart
  hashes:
    binhash: b043045dacc8425ddda7a0e6f26a9106
    md5: 6d9d295a4f29318c9950747296a1dc83
work/atmosphere/um.res.yaml:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/atmosphere/um.res.yaml
  hashes:
    binhash: cdb89f632469ba484ac3d069096cf110
    md5: 257d9ff1e60fc4efac3e4ab3f05a768a
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/coupler/a2i.nc
  hashes:
    binhash: 87c4125b792ed1268f7e8ba85fee87ea
    md5: a25eb5a98dea07abd840ae73bb830339
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/coupler/i2a.nc
  hashes:
    binhash: d1efabd8d3adef5ae2f4fd531459d27d
    md5: d3fe02e8328c5899c4593de32a09f93d
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/coupler/o2i.nc
  hashes:
    binhash: 6a4568edaa10797d1dc6c48dc3c147c6
    md5: 27687d19032fb7fdf3b17b6a37f1bf5c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ice/cice_in.nml
  hashes:
    binhash: 92ca911f37986e9a920e9f43c403f79f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ice/ice.restart_file
  hashes:
    binhash: e1a976fbf446f5ec8f95208cae64c449
    md5: b493e91fc33d32dcbaf5d57e12b97f93
work/ice/RESTART/iced.0883-01-01-00000.nc:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ice/iced.0883-01-01-00000.nc
  hashes:
    binhash: 029583abe01083af6ec112488e35f3de
    md5: bb7c602e6d3abbc39086c84a06e6ef7a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ice/mice.nc
  hashes:
    binhash: 947c8e79a7f0a06d2d0b78924c2288d0
    md5: fa6463dd2464f35c9e804357b1876f72
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_age.res.nc
  hashes:
    binhash: 39ec6fb3de66c2d9e98a0a6a25aa461c
    md5: 1e6d304a4ae39c21e92fcd7648f5e193
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 69f939c9d820a6141bb065fab19779a0
    md5: cdaa1779471b598b139ae3391bd7bf40
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8902e8c443987967f6e2e679560b4cc1
    md5: ed1685ae3374126a92891aef9ba3cf18
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_density.res.nc
  hashes:
    binhash: 7e38b5644d65eef0d8ffc6df6a157f65
    md5: eae2c205ec80263af75d49b6ef120047
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 294c71e27e1ded8d4df5e569d0b012c8
    md5: 7aebe4d068a55814764f7acf3b1ec5ed
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 89525efb67096dd25ac764bb4e6f76bd
    md5: 4bd3cb6a1aed956ac604fe11a6efa952
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3d3cde74b9ef28f6e73bf67e0097eee1
    md5: 8d9088f8154c75d053d9e4511f266b58
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 47488a84ee1a22ae761aa5fc7a1b14de
    md5: d876a227e41538fd28bfd9b877918bd8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1cc6ff518ae05599e5457bb6840e79ab
    md5: 1c2cd4a1416fe4d6485035ea8d6728cc
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4e2d62bbce004a90b7c6f7e6dbea7342
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_solo.res
  hashes:
    binhash: ab961879f313c0c9d85c3fd35ae49d89
    md5: e92908dd86f4cbb9f69a8b89c24abcd8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4f190a828053913a854a99f93343b44c
    md5: 44441815c6fba43f7432ef9110040ab5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 22bc950321c969b97f11e11c34869fbe
    md5: 636ab393ed9157de1206e0f3c2d2a6aa
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_tracer.res
  hashes:
    binhash: bac90c575dfc6df6c5d514ce8578f622
    md5: fca94f3fcba7e871862cd473d35092ad
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ef5a8caf17ee64399bae6ebf26e747c7
    md5: d0a85cbc4676e026e43c7ac2f66d3b39
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 956a77f77ff662cd68f2b3587ff8f89b
    md5: e9b1e9359c27ae9585c9877eb238ed7b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3bb63ff124fdde35498b0e6beba0b068
    md5: b0cc90a8ea47907b32d2000f7db4ae52
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-A/restart280/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c2516ecaa2085862fadabceaccd18e03
    md5: d02c62c35220b4d18c560c9a3a96483c
