format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/atmosphere/restart_dump.astart
  hashes:
    binhash: 296d4d841f7e54690d5b0388def31a46
    md5: e795a0a41d9d1001cc7c34ce910a29e1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/atmosphere/um.res.yaml
  hashes:
    binhash: 23fc061297bd1cc4452d3fd9d9539562
    md5: 1d164c788c1efc6991f09f65171b7709
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/coupler/a2i.nc
  hashes:
    binhash: 338ffe522ad28ad3c5484467d31a9797
    md5: 1bf769e3eb12296adffa59f86a4563b3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/coupler/i2a.nc
  hashes:
    binhash: f5cbfa461773cbadbb00b1f30c54b1a1
    md5: cb0a8bb875f4c4d04a72f8778141a30b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/coupler/o2i.nc
  hashes:
    binhash: de6f15f74967262cb6abaa2382743ac5
    md5: b87334a10348e62a70a83ffaf34c2263
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ice/cice_in.nml
  hashes:
    binhash: d4e76d4dec4320871c890c70471d6e97
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ice/ice.restart_file
  hashes:
    binhash: 8a2cdd2b49aa4489b4acc316871bc960
    md5: 2e75eab359c363919b8d971bb7383e5b
work/ice/RESTART/iced.2761-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ice/iced.2761-01-01-00000.nc
  hashes:
    binhash: bdaba5347b9eba848d9f22385a6696a8
    md5: 9b44ba8330bb9132e8130d2faac4e73f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ice/mice.nc
  hashes:
    binhash: c82bf2e4f8280fbbc2d6a6800f4a98a9
    md5: a26aaec0b77f0f11a48eea4550097226
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_age.res.nc
  hashes:
    binhash: a5b72ed63b062d7785bbdd44ba35bd40
    md5: e211e562f0f1521e3e0b702be45b4b8d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b8455f6add3de5259fe3d957a78801b3
    md5: fb4a7fee992b16000886c45d776c231a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 27d7d76a59e061a7121b862a85b511cc
    md5: cf9affb9438241094c22f3446b9e3f7e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_density.res.nc
  hashes:
    binhash: 9aa8f3966e62ac1051aebfd07d07bf5a
    md5: 81d2bcb8e1111f3e0057c2ce6f8a417c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8f2d8dde16de68d89414370a21732ec5
    md5: 6e2c92c289acf0654341bbe3ecad9b21
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d1c4323a48e3899b76975c4c315c894b
    md5: fe738fa11711198d2efd2f23878e05d5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 912631f73cb388517c8137b43cd975c3
    md5: fb494d82c8fa2b2bc6f7016eb8134b09
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5d69c3249d3380164483507abe1daceb
    md5: 9bdceb8bc32af5c843527aa9a791384c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 249c9de24701d79b104a97f7defacdda
    md5: a93f67f76d678f94f40d32781562474d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2d18f6fdb554db5301f1b1be19f0c086
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_solo.res
  hashes:
    binhash: 4e79ec9fbf8729191401981801579249
    md5: b7dac22c04fbb382247f30e1f7e0538c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 436aba1bd62c548b0baeb7994af5ccb2
    md5: 7e0a9366c5bb109a40faffe571b6d852
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4c37009553256f8d4dda09cd283ece95
    md5: cb3e823af6a0126e434610dbf12e1397
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_tracer.res
  hashes:
    binhash: b22b563d422452d2a8a272937b8d2e78
    md5: e34abd4d476d3336c5266002d25a1770
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d45badafd68c1ed15d6d74ec1bb21bab
    md5: 337023d779a27590844079c0423207f1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fabaa6dc03aa5d8dd7558cc6a0546e39
    md5: aff132fd4fd4778f081eac2a0db5be98
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 506beb614cf0e258ac9d1e8e2c3b23c2
    md5: a1a914669b992e7ce140853f2c1503e3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart084/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: adab214a2ed80c9e4fcd8fb58088736b
    md5: af93f8874c7300df5fb242c153f47c56
