format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/atmosphere/restart_dump.astart
  hashes:
    binhash: 5396214bd08bbf5c55f5741e636608bb
    md5: 5cbe9aba3a0698f2f61240950d4c7208
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/atmosphere/um.res.yaml
  hashes:
    binhash: 5a2b9f2c7dce3a95e94843e741383a6a
    md5: a6c4b57d296ab8362424879ce85a996c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/coupler/a2i.nc
  hashes:
    binhash: 429ce0bd76854cfd477e0dc3a7720671
    md5: e141ec10c856c958ad4b856f0a12f43f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/coupler/i2a.nc
  hashes:
    binhash: 7a457dab79772fd9a41ff623387bd902
    md5: 087e578bfd2a43818e8fbfe964b4e624
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/coupler/o2i.nc
  hashes:
    binhash: 47708b39ff302a17c5f18de3e8dbeadc
    md5: 9b48e8ce79f6cdb096895e1eaf7d29cc
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ice/cice_in.nml
  hashes:
    binhash: 1264b9112b1a271f0b1ea25cbfc857eb
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ice/ice.restart_file
  hashes:
    binhash: cdb7b2ce995ecb9a7e31651efb3ecf78
    md5: b82311975b5b851c7b1e15f977203d31
work/ice/RESTART/iced.2928-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ice/iced.2928-01-01-00000.nc
  hashes:
    binhash: 35e224d1c925100e8a5e7b89d398670f
    md5: 3904877d8ea8d2672a93ebeee67fef58
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ice/mice.nc
  hashes:
    binhash: 532813e9c0d8039483f31691758313da
    md5: fbef62888ebe8bd22ac064655c5ebbe4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_age.res.nc
  hashes:
    binhash: ff5bfed024d7d638cbcbb7fb0cd71102
    md5: f625ec4440cf3a0855c81d6137a90e8c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 76b9e306d3de3380984796b97fcfb5b6
    md5: c5f14eaafc0b1049020709fee8551b23
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8acc5a235e83c00c115fa9993bf71dae
    md5: ccbf95e44193c915163d9bd4c28f67a3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_density.res.nc
  hashes:
    binhash: 7e6018671714bac1bc488fdc6ccfdf6d
    md5: 54d2f131b3f1fc9b748a035e34854319
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 16bbf29aa7b025b900d3c025b166dcb0
    md5: 778fece9a94dc2c6a7a7ffe9eeda5c18
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8daf434eb6f51921df8b588406961481
    md5: f6711d2a776b889f25a4fd82fc8060a3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bb3cd9eaffdd165f8e0ce82f144e02db
    md5: e8db4bc94e3b7ac6c6e90ccfaa1fbf58
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5b36efc7226709936eaa54f7dc31f568
    md5: 8ec99aadc612de8c2ab8636ae0b96f42
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 818d04e8e996da50f4858a32911efb9f
    md5: 9779523a42af66aa663473aa0f796f27
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fcf70b79b9a91885cab87d3229848ea5
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_solo.res
  hashes:
    binhash: b053c654330c7fded5b167e2bc96f54b
    md5: 6b567dcbb3321377b2e533d56b075247
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7fe30b65ab1f40ea15016ddf4977fc37
    md5: 49791ec238d9f2e4b0d4ccb018ab56fd
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 09b6700746efcf7c6c75207f99e1d515
    md5: c2e3b8f09c291375117e602955c50f46
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_tracer.res
  hashes:
    binhash: 7825745267691348b9206971a6d74d29
    md5: 307b092de086f15e7c43d3459de53d39
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8092e8cb48da85fdbd56add8d4036d33
    md5: 765ba65dcddb441b9db5814ac59e820c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e0def3d5b96cf836e3b40f4fb78612e0
    md5: 814d4487c237953c517ec7936508b478
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 310073b2bbf0b068c94a15ab04901fe7
    md5: f27521fa91ca101da1d5c747668d7a11
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart251/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b4a01d543970379ff312922e786beafe
    md5: 740b350641930ce2766efe7cafa6bc6a
