format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/atmosphere/restart_dump.astart
  hashes:
    binhash: ee9d76a77e151ad7e8815360bbf5e962
    md5: f48f17090ce33afb486b4a1cc0eb64eb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/atmosphere/um.res.yaml
  hashes:
    binhash: bf2788ba883f7c8d4e245d2fa96bcf0b
    md5: 4e77bd0b7e6975b6cb7bc1f842b06acc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/coupler/a2i.nc
  hashes:
    binhash: b345e12d2ab71c522a5410949a3ad306
    md5: 0bb06337ab4db343138f2c14d7e024f3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/coupler/i2a.nc
  hashes:
    binhash: b26b64601117ce784097201e135b8bb0
    md5: 792b1b1b9d3ce100b11631558b5064c1
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/coupler/o2i.nc
  hashes:
    binhash: 15d5843a3f12da84d43597031dd4bf93
    md5: 4f876211a114db0a369fbe058cc1c336
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ice/cice_in.nml
  hashes:
    binhash: 8f33bddb1f6afb5d531d86d35036fe49
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ice/ice.restart_file
  hashes:
    binhash: 6ee479b1d99834dc45ff680c6c00b8f9
    md5: ee839568072310e55fbbb542503128af
work/ice/RESTART/iced.2679-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ice/iced.2679-01-01-00000.nc
  hashes:
    binhash: 807cdfef9bed07b40a4e40104e0b5b39
    md5: 4279fbcc8262c250ece7811251357882
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ice/mice.nc
  hashes:
    binhash: e720bf2dd08abd59347147595c47d6f5
    md5: ab9eb4fe635c3ca0356a9b0a3fdf86dc
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_age.res.nc
  hashes:
    binhash: c638c3565056caa363a40e6d9882f183
    md5: fb36bfc15cdfe41a6ad57ea6cdb6e709
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: db08f64d539bab2f02e463d969f48be7
    md5: c102a90b9103e2c5ff533efd6f509a1c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 66805c5674df447b7e503d3c22715b56
    md5: 571869c9002606b00a23fb72fbfb06c3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_density.res.nc
  hashes:
    binhash: b918719362ea4e5991f51c9f1b76edc5
    md5: 8e03b5bbee527211cf5749a4b7b9e0e0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f28d14289a8ec122c72b2ff6a641b163
    md5: da50aeecedbeb1cae2725a4293d3d283
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 65836a78547de01b0f9932e98f37cd35
    md5: a1115013067df9d95a2ebf3a68e2905e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fb1da65a20dcd2d6adcdf1292f92c073
    md5: 63ef79c25e2512603938a32aaf09187a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5ebf5a45d18c9723beba89f86d199d0e
    md5: 7d0728b6061bb28a460aea39ef1b8a4b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 907a5b67dcabde585b348f61615f580c
    md5: 4b4571e5ed3b4d10cf87d04310bfb193
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1c6d80c16284685344a5e5be660eb838
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_solo.res
  hashes:
    binhash: 9e99c7897e7c45bfb5291620e9f25604
    md5: d9f213b91c44e0f7c7b8000e0487e569
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 420f6cecb5798f747d7b52fa02660989
    md5: 0060b388d6a230c1fa04ddce55b79609
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_thickness.res.nc
  hashes:
    binhash: bf2463635e53866b9b8ff45c2c80cc84
    md5: 9b0de418ee727a4efab07a2b37165b5f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_tracer.res
  hashes:
    binhash: b48cf69d73008327a7beb252968aa405
    md5: 741f8ffe758c4aeee5331b1058f11378
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9f1c3a3618faf17df43193ced8603c23
    md5: 9fd46c5e64d2a13c6bfc0748da6c5315
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 222cc233017c708ffa33f03767bd4df3
    md5: 82b3e2cd2f3487f08776c483211aabd3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d39623f3c753fdefafe103204fe4a614
    md5: 6f514e1204cdf94f9894ea573b9cb8af
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart002/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ee45926eed2eb1fd0ab761e4552dc650
    md5: 33f40724353798a76c0953d6bccf583a
