format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/atmosphere/restart_dump.astart
  hashes:
    binhash: 998e0387aa2c7f78e9fa1e70f74ae4ca
    md5: 24b7bf3570c9157daffbd2292979727c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/atmosphere/um.res.yaml
  hashes:
    binhash: ee5e92d4d5d9f3be465b834e6d6a0145
    md5: 5978e15fc974ab210d5e5b81327cb1ae
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/coupler/a2i.nc
  hashes:
    binhash: 881f00fc487275cc187ba59c3bf33cb9
    md5: 31aaea68951e4ea71b62ec17692ccc6a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/coupler/i2a.nc
  hashes:
    binhash: e13f69c34f2d62ca718e2e9268aad58a
    md5: 2cfd778bfcc92130da90b9f4d867de1a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/coupler/o2i.nc
  hashes:
    binhash: 6827c58c9bb4fdc83d50dc1d49675a3b
    md5: 6142f3fd0de1ad9f6200c56d212fdc77
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ice/cice_in.nml
  hashes:
    binhash: 743be6f07dd9bf4edf458675a06e71ce
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ice/ice.restart_file
  hashes:
    binhash: 5277a65da34ac50889a32c0affb457f2
    md5: 98af09d2b1d97f97873060b633135e53
work/ice/RESTART/iced.2758-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ice/iced.2758-01-01-00000.nc
  hashes:
    binhash: a52c25857672f5260fd6e101904d4937
    md5: 4a547916fb23d58fbad26548a07dc2f8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ice/mice.nc
  hashes:
    binhash: 1b229a76e4d470bdc40cf3b367cec8cb
    md5: 7aec7bb0f4a4b44008b9e54676b819ca
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_age.res.nc
  hashes:
    binhash: 24f0daf7b38151f259851625e14ecca5
    md5: e9680a716e16a7c042af2859d21c9ed6
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: faf6361f2f4d5c26a6b323c18beeab0d
    md5: 17c5d2762bcc4de030e048d0e9579c46
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 50a711e9a1b2322ce2758a48777547a2
    md5: 1b6f5167eeb92d150f2252fcf33f5607
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_density.res.nc
  hashes:
    binhash: c3fdc8dc1376b69134dc035b2eb26b4c
    md5: f8449ccea235e9f052e543dede3d3eec
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 721931cb965d9c5279e5b9fa7f2ed19d
    md5: 60dc1a33c85e4243123ba009c4b99ef1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 493da2ca97633f131e1388109f0f0c10
    md5: e219f9c02daeefca08c9c94101dd0d7d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ed4464e9cd3b7176ccb7924e648224e9
    md5: 1338261a31f5482011db140acc2bbc9d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bf8af0cc0e36f3458c727e3a642d6c25
    md5: 450ee75e2d03608b2e659708bd9b1da2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 543fdbbc3d93099ad2e955e921eb5419
    md5: 7fdf6ccd99b751c7bd3541654701a306
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ea8dabaf321be20cb6383adf547e9b2b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_solo.res
  hashes:
    binhash: 7e9e4619d5293f5b20555f69f37732c2
    md5: d7460a21c8fad301cdcb46142453ed3c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4d0f00f22b78cc062f472efbd74e35ef
    md5: 9aca9d890f419dd4ccf68d339d05638e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5163485ff2f2acfc9e40b376a0ea3008
    md5: a5c42ffb48abc06b2e945a0781fda5fe
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_tracer.res
  hashes:
    binhash: c22093cbc36b1e3f6d96a6c1bd6e16fa
    md5: ffb14a26fb614d897d493a8201621c6b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0e2a1187f1d8cb9dec84d557a0487838
    md5: 202aa9c8802edee5172917254c468716
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a338994a5473ccc7fbbcebb3573601b5
    md5: c9703c4a6465befcf7d6aa9e39883b47
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c9322696260ac8c571479c9331fa913f
    md5: 1ea1d10ac122c8281587842b400fddaa
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart081/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 71808602e74e764a662e5aff9562600b
    md5: 14c60c4101c66efab30c9fc2127bd95c
