format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/atmosphere/restart_dump.astart
  hashes:
    binhash: b14346194b11ec61222e9c242bc5011f
    md5: d2fc2e9a3a9109c3cba7c330ed9446df
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/atmosphere/um.res.yaml
  hashes:
    binhash: b91d57c9447b512d8aed6b591fbaca83
    md5: 7d5bdd5e0a15b0ea595596a2116a94f9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/coupler/a2i.nc
  hashes:
    binhash: 9dc35e8efc292d226f1f1e5015b8f570
    md5: 97afa8fe0eea8d76dafa10ac10fc29f3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/coupler/i2a.nc
  hashes:
    binhash: 3dffc57052c504a73e4ae42697d35dc6
    md5: dd552e35310e6ef0992af9e1d17343d8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/coupler/o2i.nc
  hashes:
    binhash: 2b30e312303ffc2ff8c1e5e94f3ccb5b
    md5: 83fde9d128a2b27940928e5b3da6a6fd
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ice/cice_in.nml
  hashes:
    binhash: 732099210e3dcfb940039228194092c2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ice/ice.restart_file
  hashes:
    binhash: 54742ea1cbbc1fe11388b4666a097444
    md5: 883ffef1a7201ec6684a904d27b04420
work/ice/RESTART/iced.2724-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ice/iced.2724-01-01-00000.nc
  hashes:
    binhash: c9531bca8d86093e23779049c0a793ad
    md5: daedebf39d4ac68132b8bdc925f9b5ea
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ice/mice.nc
  hashes:
    binhash: 9c341c55219387fff18dbf004789f0e8
    md5: 6e51ea949da2b3f8378f54f71f414e4e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_age.res.nc
  hashes:
    binhash: 0c4aad10d0a73f1048f94940e5b381ea
    md5: 8b8153cb5ff49f2067a6f01c6ae64066
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0404a2e3bbcf0831417f1ab12d9a172e
    md5: 7019523a784711a1529311a163fcbdbd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 50bb2e26c8dd1a516cf3feb1950d4989
    md5: 6b7bf2ba3233d73826c9974e14791d5a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_density.res.nc
  hashes:
    binhash: 4ec156c0f2911a61ba3f07f8be383d2e
    md5: 20e21d331994658d5e989022e80fdbc6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6c628956aa2de621cbfb50e701a8dee3
    md5: dafe7c9c4c31ef8393a0dc8460c027f0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 80b4a38305ef9137be2074665e58e5bd
    md5: 862a0aa350498f3aea88a37bca876a36
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 23eeef27c241a6620208328e8f36d6b6
    md5: 6620fdf515f845dfa499610cc73b82a3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7a79b75a32e6d9ceceae3f5a0a7573aa
    md5: 9daa6fa9bb77ade7fccdb2ed3b1e90bd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_sbc.res.nc
  hashes:
    binhash: be8e62992385a6cd2626644e0f9fb8a8
    md5: 92f68c32dce18894e2d2410d3bb8ea9c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 53f26264f2b30be3ddafb04632dace1a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_solo.res
  hashes:
    binhash: fd93d66b83e49345733e04c464858e73
    md5: da993fade8dc04ccab83c8b72f4d1c6c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 45e0a41bb53dafb838eea47a1ab9c3d7
    md5: cdf55100b5a99e38ca44e9aba7ef019f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f94944c4a4b0f0cc58756a1ef16ae173
    md5: 19a214c643a2c4b9b968a2d99d57cb33
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_tracer.res
  hashes:
    binhash: 18e8bc64bba9aae275f022bdefb8b95f
    md5: 1eb134790af349da4eeb598ee1c82c67
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 70da44081824b325a64a8d91631fa05a
    md5: dd66c3b7c21e2a0ddf67bf170818d323
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5ba5f72ae63821c5b6ff910e1f3729af
    md5: fe300c05b103c5bdc680d58db309d0d6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d807afc3a1de42df4b2f525cf86e6a03
    md5: 1e4d15ae92ba3a5a35a093faf7e045e0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart047/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 95732599d2a90bd9e7dd8d510b9c95f9
    md5: 8c8f22040ec6ad76a3c0958df3b746cd
