format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/atmosphere/restart_dump.astart
  hashes:
    binhash: 486fe3d57936b7cfe7066fc820bb77dd
    md5: be95587bcb3bdcc804fde6017da3e198
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/atmosphere/um.res.yaml
  hashes:
    binhash: 4c438625b4918b3df6a997a29e4e1253
    md5: 2b7e4f2fa4cbef3b39974c7aab310527
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/coupler/a2i.nc
  hashes:
    binhash: 975c9b4652b6a29c837eadbfe11301cb
    md5: 04833723c011c1767ffbec51700a1933
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/coupler/i2a.nc
  hashes:
    binhash: 1409d6483a28cead4e0678a37b3cc345
    md5: cb5cf8816ea50fdfc2380c9ce6f91f6a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/coupler/o2i.nc
  hashes:
    binhash: 7e1f78317fb15b26cd6f102d839dbc6c
    md5: 721e2946a20d834ab1387993e9f746a2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ice/cice_in.nml
  hashes:
    binhash: 1254642825b4aa3b3d5bb1f1cc57c0b6
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ice/ice.restart_file
  hashes:
    binhash: bc73f9ada07a8b38aeea5c10bab26b7e
    md5: d23e3c6d1843617d4f83bb745c3319fe
work/ice/RESTART/iced.2914-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ice/iced.2914-01-01-00000.nc
  hashes:
    binhash: 542a12cc42a3a7c9f0a5fc1ceeff74ea
    md5: 91e78da5810baa7721610e8164fd178f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ice/mice.nc
  hashes:
    binhash: 48364e80740aca2643353b8cda479e75
    md5: 02f57fd9fe25163ca9d2de349266fee5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_age.res.nc
  hashes:
    binhash: 0f77e44fe2182862a30f7fe94283ce82
    md5: 53f8706403488726546a0fe7d6607fdc
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8f77622bfe1704e1d02dbb6873600c90
    md5: 7c84d384437a7949dfa0813fe322fde1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: d614c1588f75c16f09f0f6c3954a9ee6
    md5: c941c5141954a74f74e10228a0871fbf
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_density.res.nc
  hashes:
    binhash: 5f2b199722b7689f0bc8b66b8a532c80
    md5: 2f1ae6916eaa758bc0f50597bcfb058b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 546e965c74a3071565e45445bf3ec5f5
    md5: 04adf6c53aa533da885f11d2acb65824
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8c97983668ebdfce58232be52e53a94a
    md5: 206bb135976f6fc98a9e44fa96bc3c6e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6f352912a628672e22c3cabdd01d309b
    md5: 8a167fc92b0cdc6a30ad0372eb6ea8d3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e53aac27932c1944b75a239cea7c6bc4
    md5: db5af746ccbf7193efec4e6e0773bffe
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 702e8483e76eedcaf19c327cf3793dc0
    md5: b34fc9963ed879c872bb855f4f5ad653
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b2f73fdd7d606a28ad1d76b93c9c7db6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_solo.res
  hashes:
    binhash: 5bf032c3876c676c0220b9707aa88d78
    md5: 1c14b393bd97e9f56aec14ea326ac6f8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d321c0c8ee3d734856395198d632c082
    md5: ec96cdc38b213b8cc192a9be3937d894
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9e760e59bebe00844d66c3d6fd44acff
    md5: cfd4b42c20176480f140d490194d3c77
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_tracer.res
  hashes:
    binhash: f4f7f02ed314c419d10e3f89e5ac7fbb
    md5: 134f0af42c87c6bd1af57bb1f5123f35
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d41a71a8f1def43559a5174b07239e86
    md5: 6d2b60ea743b56081753ecfb2f21fe8c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c7d3048f9f91c588f87327afd00df50c
    md5: ec4b8b7cc73808ad8a5187fc01c37a9c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5199dc1e2e264bd3aa562e7a2abaad8d
    md5: fbfc8a33dea27497201fbb78f3800cea
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart237/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: bbceb7de987d9418282e040457ef425f
    md5: b55a2ad0155a817eec7e455bb6a8cc95
