format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/atmosphere/restart_dump.astart
  hashes:
    binhash: b936b0ced9179780391d476d4ee5c78d
    md5: da512ad2346cbf91850e29adbd1d5475
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/atmosphere/um.res.yaml
  hashes:
    binhash: 403d0150a765beb45e10ab1e7e88d03f
    md5: 7023fa136b5e35c22af5f20cdee0a828
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/coupler/a2i.nc
  hashes:
    binhash: 7fa2e1d4a9c69c27f2d4ae5180b19b3f
    md5: 215d36900da65df57aa6f11641d4ae16
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/coupler/i2a.nc
  hashes:
    binhash: 3c6d70656bbb208822492b3e351d0015
    md5: 7d97174466ac6fddfbdcac7b3953367c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/coupler/o2i.nc
  hashes:
    binhash: 3739d59a3ea66142577bb13b28c86d6e
    md5: c51bb2e9ce7bd8ab557027a939d7bdd2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ice/cice_in.nml
  hashes:
    binhash: 652e7d7275018de1beded9fc403904df
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ice/ice.restart_file
  hashes:
    binhash: bc096aed3a63787c6110d91eaf53512b
    md5: 3076d91a9230276b51bc429681fb0b5b
work/ice/RESTART/iced.2848-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ice/iced.2848-01-01-00000.nc
  hashes:
    binhash: d5028632b8a588852a9c86b4400e9aaf
    md5: 73ea99ca87c8b319aba5c77e026616d1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ice/mice.nc
  hashes:
    binhash: 6b3cb9f00da59a0a64cd0616f9a81614
    md5: 31562f40f4bea9c22bc59aa240429d89
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_age.res.nc
  hashes:
    binhash: ef06b7c6236a94e009d2f80708090d61
    md5: 8a620bf144649aa2dce10ab0d4d28ce0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3d63a5aca87330b4ffb54fd0afecd981
    md5: 6c9feaac4d24e47fea33c586bf2b6bb4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ed9ea8bc26090514caba726849c5899b
    md5: dc6f620a123e9fe7936a6fe749f21fc9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_density.res.nc
  hashes:
    binhash: dd8e35409906e6c4f6e583c16456f4dc
    md5: 04f52428da5617257255cc856a4c6bf5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 26d57f30dc10472b6cfcfbf88f0bf204
    md5: e50a03a9e5e404f70e559ff32883f395
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2a6d3142f79e8e95931c12a9a188675d
    md5: 41d1e762cded2ed31c5f2b1fa7a2712f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d0fbb1b47852fd29ba9a1c5fde44a440
    md5: 387c662bf9f041743cfdf4cfee9ad294
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8c482433f9357f71bcc315bbf1ee1809
    md5: 7e6206431082b55da7da197435ba3764
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c785abdabb51e6fa11a73ec7841ffd31
    md5: 09816fa775ed6fa62c814a2893bd1c44
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cf0666bf1caad9a19cdc3902c49d8920
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_solo.res
  hashes:
    binhash: 08349a6090397c1d8658b86e03fd49f6
    md5: b59c9e3ea780300286c66107d7d6e150
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c316a3302f94acdd3edae5f36c3abef6
    md5: 010bb70ea125a2da585fd2fe8bf6ce19
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b226b8d93a8eaabfe3c29eebd69bcc79
    md5: 831a410a1c24ecf14f0fbcf407d6295d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_tracer.res
  hashes:
    binhash: 9237d7e2f2bbfa3939dcb4e4dc5c7654
    md5: fc77597ef334ad205931e55d465136d3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bfe39f6e77cc967be7a9b97291bc22af
    md5: c81882eb2a72de7f2465304b7d8fd096
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e706c59f36ed54b282c0b77bea512102
    md5: 50f86cd3345ded60725fc9904a6b12fe
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 271f9e3be8f5ae7be5771df6ed16a76c
    md5: 9af8b69ee183b6875ce1d8f4aa3f6f7d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart171/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8cf7d58d3d0124bd6719e265a043b807
    md5: 28e34befbb58bfd32e5859a2d9600a19
