format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/atmosphere/restart_dump.astart
  hashes:
    binhash: 5fb92b121fa4161c86a5544d38d3eae9
    md5: 330dba69dd039864d02e2ccabbe31fef
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/atmosphere/um.res.yaml
  hashes:
    binhash: a4aea45f1be306001d707bf8e816979e
    md5: 5f02e5394be55920a92294f1811bec88
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/coupler/a2i.nc
  hashes:
    binhash: 414ab4188c8f3082f2c2774b9ac9df77
    md5: 75c3937656df38666ebde8b4c38d416e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/coupler/i2a.nc
  hashes:
    binhash: d4aae7d81fe20b3af2af798d88f5cce3
    md5: 8b6f8066e348de2fa1d9cdf1f002a1f4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/coupler/o2i.nc
  hashes:
    binhash: d247f057b37c9dd11f0f11ecf3c450b9
    md5: 9d97de6abd46d2de8f55e34991847436
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ice/cice_in.nml
  hashes:
    binhash: c8d51abbbe69f96245ecc8f59a8410cc
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ice/ice.restart_file
  hashes:
    binhash: 1033212ca278bbd670292d0320f15039
    md5: fe068a73fbeacdef2ad9c2fcb6a67a5c
work/ice/RESTART/iced.2835-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ice/iced.2835-01-01-00000.nc
  hashes:
    binhash: 67a2dc3cad5e5a4ad48f4c8ea28eb97a
    md5: 81f78a52c5ee85f8638b5e91fd094120
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ice/mice.nc
  hashes:
    binhash: c0230228258e53e9a2a91b7423ec6e9e
    md5: efc8deeec3ef24e66d6bf4ec131ad31c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_age.res.nc
  hashes:
    binhash: 0a490cd6e6807910f4949a861d0fb702
    md5: 12122346fc83ec47ed9c451ab7928c45
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c7da73600c1ed8f26d1abc78d1dc30b3
    md5: eb3edb0b5d53a07575d8cd20f05b2133
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7c32876c3dd2855d9dbb13ca259d617a
    md5: 89ac08f79b019991810f5ab9144f1734
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_density.res.nc
  hashes:
    binhash: 1685923148b6468f535f6ff387972df3
    md5: da1be7588f586c83264a0d64e88c877d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_frazil.res.nc
  hashes:
    binhash: de318b2db2fa28c9f027d4967e85cf2f
    md5: 34345c7ef6eeeefc708144b6ca696901
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8623dc115bbacae901660f3c0facccce
    md5: f40e02148f554fdd9625be1f86a0672f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d91c30782781542a95fd07aa71a179aa
    md5: d1a84548f5da79c60a8400dd0dc790d5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 518c8ba910cfe66037eeaff6a74cd479
    md5: 898a16fbc326270fe4dcda23fd294286
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ee5716e1097fb6b366d0dbc55354df70
    md5: c496a3d12382e186eda2f7252e8654c7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f414995b114069fba742d7f923bec3ad
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_solo.res
  hashes:
    binhash: be16c5f1a4588e7338b0dbe6768db705
    md5: 266d9499208fb2dfc557a531cb25135f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 703bd0c653f476765885d6bed0f773f3
    md5: d113a7750e61695af7cbc3a141f917ee
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 96d6fea473f94d0752645bf1ad0c4393
    md5: 85c894ee5ebda323078404ae58bf573f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_tracer.res
  hashes:
    binhash: d150db40db49489659598ab7d1083c72
    md5: 052d1cacbb0ad284140fdb879c6dd43d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 56ac0f1a91df291638ec73bd7aa5d3a4
    md5: 969cee92d805dc9d6d7dea90925d1f68
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 59d0320002546ae21f92f0df8dd266c6
    md5: 702a453e1c4eddcc0a27ec52a5651d8f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 73efbc5b2f72408d86f942fb4e65db61
    md5: 603c8b5542e30f858a7539529f3aa2a4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart158/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 27aad81ecf936bbae41450f7052213ba
    md5: 04403bf08af6caafdfb5b275a7e95112
