format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/atmosphere/restart_dump.astart
  hashes:
    binhash: 1020ad167771d59e7c26c2c9d6def966
    md5: 9bf7e382c2a0758bea4c48d1ca92552e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/atmosphere/um.res.yaml
  hashes:
    binhash: 479407aab95a30f409ef878a52aeae91
    md5: fa251a04d30d21eebb973e289172cec6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/coupler/a2i.nc
  hashes:
    binhash: 8a0cdeffb91bb82aacdc16d369d23e68
    md5: 4d7486039bf9ee1b9d25bd3fb6f1f4ee
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/coupler/i2a.nc
  hashes:
    binhash: 19e5f6ea47630646c2fc0afa372f9d90
    md5: 06abae7b7eff3f42e80c355218d9ae81
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/coupler/o2i.nc
  hashes:
    binhash: 137c6d6fd316df5a6636b2b01db927a4
    md5: bee796f1b8b0bada68448f5f66dabd86
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ice/cice_in.nml
  hashes:
    binhash: f184c0753eb3cc4ad7f3f2990cceb4cb
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ice/ice.restart_file
  hashes:
    binhash: 4e1ba15701186f15dfd2312ecbed60b5
    md5: b7fa35dc395661066c181c669bae6079
work/ice/RESTART/iced.2691-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ice/iced.2691-01-01-00000.nc
  hashes:
    binhash: 5cb67cf6b5944e8092b587aa70599adc
    md5: f227be7f6036f3e5ec73cfe9e98f9a44
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ice/mice.nc
  hashes:
    binhash: 02146e7fdaff9b51a5348d08bda23e96
    md5: 6da7d5eb779fab85038431cba02e42cf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_age.res.nc
  hashes:
    binhash: f64cacbd6e5c34f986c6dd8fdfdaf87d
    md5: 4eefe4ecfcb0ed121b705e8b2084bdc2
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 16ed585ae30866ee27c9b6e144d71173
    md5: 23e496bbda46de3cfba8a66613642917
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8ba62562cf6b34073cfc6d7b6e831bf4
    md5: aa125f4971a8df6ac90fb84a71e4d959
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_density.res.nc
  hashes:
    binhash: 68fb3b9070a7d9fc5eb6e48d62cbf3a1
    md5: 9975348c72722d1ecedd9362b4aae673
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1b30653822a5d63b03ed35d33aa199ba
    md5: a0930463f7cd1eb0c34d5b9b5d57091d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9d44b8d4cd208e0136879f6b04dffd41
    md5: f467d505d2427f4a57b33356caff124e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 507e09d65af1a1dfebc8dd2ad25ef299
    md5: b79aee88fa3ea67805909b8b22a343bb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6c493515d1ca3f81ccae7574cb83add7
    md5: b8161e10115963e9dff76d90f30c8089
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 35f264f11d3e5739e2d5c48706e962fb
    md5: 93c1d56b08b193647723a44c0bad43c2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5561feef2a3bfe9a69c2bd69108fc341
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_solo.res
  hashes:
    binhash: 770b577a402f7c260fbcb6b276512676
    md5: deacb9569b0b91e018ab23b3e0b5e693
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1dcaa61bb3f6f05f15f3b681ff5273eb
    md5: b866d93d777ea6f87516cca7cb0265db
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 207df32acb69b28afb1a77d801ff7f9c
    md5: f50f11c473b075f740d3393bbea1dfd2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_tracer.res
  hashes:
    binhash: d08c5e1a384e6b27682898298e4c3185
    md5: b32ffac06563c82c47f0bae0cc08c86a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6a45690d92d425943933141b56fafd6c
    md5: 677346707c3d0e9e73c1be5515884d48
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ba06be96b65a13a3d42c3992bdfbe064
    md5: 95de51522e0bcc3fd78ce0813b1e5a8b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3f2439ede7cce825b585c2677e760502
    md5: c2c599228437c8a332f91a9a8165dfdf
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart014/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c6bfb8ed096f47995001f146351b96b3
    md5: b57e1a3942f40a4db4e3e9cfc6189d69
