format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/atmosphere/restart_dump.astart
  hashes:
    binhash: 6340b6a3d316e47218f025dfef1aed38
    md5: 0731ca5ad95f59ef902aaac3a7c0c667
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/atmosphere/um.res.yaml
  hashes:
    binhash: d5275c8e9c0bea09a80c285d50690c44
    md5: 537dca57af29455f81714f91e0ac2166
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/coupler/a2i.nc
  hashes:
    binhash: c182cea78372731458a4b4df042ce375
    md5: 6606bc3de8f4f674990ac1ea83f2adc0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/coupler/i2a.nc
  hashes:
    binhash: 0348463a416b5504dace103cd1fec0a2
    md5: c0b066a355180c3de9669a9ccd943afe
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/coupler/o2i.nc
  hashes:
    binhash: dc171337d859a68c6751b99ab32168d7
    md5: 935224da5a667bdf0db0eae0c350e81b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ice/cice_in.nml
  hashes:
    binhash: bf8768854cb82c5192d0f25982e1adb2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ice/ice.restart_file
  hashes:
    binhash: 3feba0dab4b93723827d120a184b6f45
    md5: ce495e12d44d77e95e7fcb3313d2e215
work/ice/RESTART/iced.2763-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ice/iced.2763-01-01-00000.nc
  hashes:
    binhash: 6c784efd38fb32d15e12a3b0ca9bb550
    md5: 33d76115711aeb74776f29169395bc13
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ice/mice.nc
  hashes:
    binhash: 2a78b28f6b502632bb813d131a782a1f
    md5: ee389cf9617fa6fec6269182fc0182c4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_age.res.nc
  hashes:
    binhash: 1a643731e73f82f9091e79185324b361
    md5: bbe47717230676c5603e2bf231db5933
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 479142598fd2149e8dda6bf973b49998
    md5: c808fbe4f454afd61fc92cae207986b7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ca667daaca4129b594ff369242518331
    md5: 88ca8def79f6c8e89cdd7d0e9ed35ca7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_density.res.nc
  hashes:
    binhash: 124bb84f046de8852f65cf1365b82248
    md5: dcf1843b8315f7cd59eb25fe8eaf5443
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 11b22d2d129a40314be6ed3705d4380b
    md5: 313658a2c301e4131e80b37585e14f48
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f89eaf217e18c2b31c29b3730697705b
    md5: 25b82316f4496bd4017d0e94561f6758
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4ba1bd5739bda8e9af827689abdb6e66
    md5: d904db55f62190eb425f074d2f92fb5e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 146db9b7bb84e14c31908b1d7176475b
    md5: 74ce1bf2b73ee2dbc2ceae3cb8a598c8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0384b5e52d42e793f89de05ebfff6f9d
    md5: 3350c4baded002aa9456ca3f0e42db5e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8e79fb3079955b90df2a3d937a59a905
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_solo.res
  hashes:
    binhash: bb2e71258d3bce0f8f12826f8a2a1115
    md5: 3ba08dfd1f53781e462507be65ae5048
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 38bef5a383865eba13079e3aafb05948
    md5: ada1f24ee42df7cad1d4364c348e4c8f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ca06b1ae01d8019a5f273e2633eb0440
    md5: 629f6eff17194ed320813c1084b98fea
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_tracer.res
  hashes:
    binhash: 83ee0e6317cac027fd57b9fcedc39673
    md5: 9c66fa0e062d6c3f3b8b24cdd073b185
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1aedb8b466ee059c5624b4190d88c254
    md5: 12844d3db6f456e928de7d0a0c4f770e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 637c49c14ca8feff342fcd1b2642471f
    md5: a9fc1265d7b3960ef6c87efb8486dfe8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2d8ba20ccff0555e547f7ea5cbd6bb11
    md5: 740ce7d243158075c273720e428ed0de
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart086/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f1e2550f1db40d6701eefdb87174b10a
    md5: 5f10d4c44c666a1441227905d92151c4
