format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/atmosphere/restart_dump.astart
  hashes:
    binhash: f67cc597a6e1fc785b942c38a975dd09
    md5: 5bc51c1a7b7bc7c037b36292a31f2ec3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/atmosphere/um.res.yaml
  hashes:
    binhash: 0055764664c55efb354eff9f07e65df8
    md5: 14d4d1381aa25bc932adc77965903422
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/coupler/a2i.nc
  hashes:
    binhash: 33c2b1c5b935df3383431c9ea244caf4
    md5: 532f16489bbb6e0361cf37e426568af9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/coupler/i2a.nc
  hashes:
    binhash: e4d4c0035c2d54d008cfe05e52569bdd
    md5: 055bb78e09f681e84f06418e4f5eaae5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/coupler/o2i.nc
  hashes:
    binhash: b94f6671dc93d893c1051b95c5dd66c8
    md5: 7f42cf4eab365c526a09ec501adefb05
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ice/cice_in.nml
  hashes:
    binhash: f1ff1d17c9236869306392bc48768309
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ice/ice.restart_file
  hashes:
    binhash: 2e7abb3927b7f9c352bc8615015f8542
    md5: 417015656fd9cf8ccd921a626a6c8d7b
work/ice/RESTART/iced.2723-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ice/iced.2723-01-01-00000.nc
  hashes:
    binhash: 3639e1d5ee4c6379d28143f1667c1456
    md5: 57c9f3af13787091c0a8ba261e78330a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ice/mice.nc
  hashes:
    binhash: bd7bcb44c20396d7546cbdde9f0bf617
    md5: 2c786c793f60ead8ba7ed72c8d939dbb
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_age.res.nc
  hashes:
    binhash: a61856ff73a9e1fd43b729df9211b5a4
    md5: f90650a66a845f812aaf26dbde5c4c70
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 84ba7ca9288538a99cde2ff675bb2382
    md5: 510ec4102fc60855880a9e1bc72e55fb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 20af4ca579ecd7d541d67c2c37930cf8
    md5: 62bc8bf8f1c035682b43c6dc6b6e818b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_density.res.nc
  hashes:
    binhash: d2fa04f1f3146fbf3df422f9ef07b7ea
    md5: 7f231feada82f8746faec900b6f7521d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_frazil.res.nc
  hashes:
    binhash: da5e24181065955edbf106ed328a73dd
    md5: 8ceaf3443879b5008ddf9aa925729623
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3c6531ce2b5e42e64cd0da9f15c9cbff
    md5: d1c81af54690cf7a4e84d010e0cae8e5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0162a81d4d8e416304b119cb6e5a018f
    md5: d5d02ddc0d146693ea307520f9787e73
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0f4f780bb0b579bcc5f27bfa1dfe7033
    md5: 66c17fe7706ea7c5bbf7029cb3284c92
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7e450e05df4c6c8eb99361777d6c7c84
    md5: cb1a673dd69ab3c5e3cedfebf2202498
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1d10f9bca8a79aa2ab578b1503ac144b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_solo.res
  hashes:
    binhash: cf27b37a5f95abf87575283bd3e140f5
    md5: fe6b9faa364c5dd8a1f799d997e1fb92
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 11a212a699c6f4960bb5ebb7eb18e5de
    md5: ba8c757cfa7797a0a5d412aa62545373
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_thickness.res.nc
  hashes:
    binhash: af49d094e2d252eaee2edf91c1822c9c
    md5: fe228d4fefb9edd9cf3a6461dd427e00
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_tracer.res
  hashes:
    binhash: 8730f6ad5a64b948fac36bd6b40f711a
    md5: 561e8a5c8ffe249f3c851bf232a9e8de
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0773cfcea5a6458218b10ecdc4b790d8
    md5: 40ec2ed67b3389fdfa2405f50c402986
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5dd1f97ad66d1f91e23f395b920bc9c1
    md5: e893610c938c8225a966446af0c8f60b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 794c2c49cf92ec1bb0b001aa7aa1f85b
    md5: e3b6a107e9d013fd923f3bddd46ae637
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart046/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3f746c0cd96cb9869e4a65a2bf3e25b8
    md5: 4e432a4257fbfe025e29b5fc1b83f426
