format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/atmosphere/restart_dump.astart
  hashes:
    binhash: 21583e5cd9d3a0fd786460cc55b64ba6
    md5: 95d1818e87e128f3985b2de4505a96eb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/atmosphere/um.res.yaml
  hashes:
    binhash: e0a004c603ad88838a08c35f2062cb3e
    md5: fcb97a7d927612e5b46fbcd4eb8e2346
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/coupler/a2i.nc
  hashes:
    binhash: 9fb3f5e31cf958f4d5d5c42da9bff781
    md5: 2bdc28eb57229c65fb93b0935debba36
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/coupler/i2a.nc
  hashes:
    binhash: e3e1eb8d0cd6aead521929e003d26971
    md5: d528b98c79e2eed2845863e97f8cdf94
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/coupler/o2i.nc
  hashes:
    binhash: ba2e3229a062d3fa6cd63928b1af5060
    md5: 08148aed808e565a38b5f3a40af9bf1e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ice/cice_in.nml
  hashes:
    binhash: 406a423279d71f2f5f98e43ad4ef24a5
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ice/ice.restart_file
  hashes:
    binhash: c6942b6116f507e1d79f7f18a8f4fc76
    md5: 4dfb0ae040c8b7f573d971e27e1e22ed
work/ice/RESTART/iced.2701-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ice/iced.2701-01-01-00000.nc
  hashes:
    binhash: f13467f4f9e756f8ae25b4ce650ae683
    md5: 2f8b3d4c8c0c236e09ac53858cc3e188
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ice/mice.nc
  hashes:
    binhash: da57719ad81650710e6d86c95d534877
    md5: b8274934080f0dc09e9699e1020bf1df
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_age.res.nc
  hashes:
    binhash: df6e9577b4bfacb576f7978364a9ba27
    md5: daeb52718edfdd446bb253d65411965e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 063c793fdfb54cce2dfea63878301bb9
    md5: aa5c174a4ab6c5ecfbe4aa3b6ca0b28c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 61ac0cc31daadf70f2ccf2965f98ba51
    md5: 9a5d82f6fcccfe3f31bfc147a4f9c630
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_density.res.nc
  hashes:
    binhash: 8f1bf824de4f5f66af6df6432a434553
    md5: 605461852d6d0575a6d7c369a424c100
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 71ddc67c72da4b3822141086d2397fbd
    md5: 82287a39553e99a2189c61c7ca5f50bd
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 850a16806e2c979b69a7bddcb12c160c
    md5: 289319bcf5b585537d4826b2be08e16e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 391ab9a830415f6b909c163b6f32efa1
    md5: c669f1508fd87af51176b6382ae36397
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9aab98a50cb93ba8294f0cd8b78f94e0
    md5: 9f2d9d1b070a4613ff8964a960bbaa66
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a5554ef7c13b87038541c06d61618721
    md5: c1170a11d813ac99d8c15b356997383d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2f5ff95f182cdcf18ce14de9ad11ec98
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_solo.res
  hashes:
    binhash: 49f315f881ace09f47cc24aa9312689f
    md5: ae3b0af77d63d2546c921df3deea9dac
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4b316db1c6e34382774cdfec616b0d92
    md5: fdbf8d4536da8c83889608280f1f2644
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 576037d1643838881ef8823cb411c8a5
    md5: ec1838459a108e600b40980b9f966c2c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_tracer.res
  hashes:
    binhash: 0293ccff25b34f4072d4a07d1f601b17
    md5: e8d060e943934bc5c48bb2d10b72d58d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 011694f1bcfd16ebef40bd6689c549f0
    md5: fb34536d14e93247995135a8bc87b7ad
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8ab24220f2937eef9b0d9d85f37314d0
    md5: 1fe0aa6a27ec6d37b5e2e5648810b50e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9b5799e7adf1400914b6846a38ebf844
    md5: c91420cfed14e83368789889c15b82a4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart024/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 181a3f0aa804dc63899993fd5fb4517f
    md5: 2246568d062c38a36eb34a2c5fcd0d96
