format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/atmosphere/restart_dump.astart
  hashes:
    binhash: c8b667e035bddc13e59c0576ba366a9d
    md5: c5b29c7c58cf7a8b6d9e8f88abce9e4a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/atmosphere/um.res.yaml
  hashes:
    binhash: b32df509b00ee3885d8221cecbae6ae8
    md5: 9da949fe5fcf1e85205cace6e68fe842
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/coupler/a2i.nc
  hashes:
    binhash: 095f6923bc62e8262adcee30a50190f0
    md5: ff1d58e8ff466455a04638e1433374d7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/coupler/i2a.nc
  hashes:
    binhash: 1ceb93591d81a8f62f3e9261046c9f27
    md5: ab421a610943ea9c2b71facc9065a6aa
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/coupler/o2i.nc
  hashes:
    binhash: c5189bf0e494a4f2b7a8e21bcf5e8ac2
    md5: 2c04de1c932fd8057258aaa74e91d882
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ice/cice_in.nml
  hashes:
    binhash: 7e27adea0a16d142c76d56710e662099
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ice/ice.restart_file
  hashes:
    binhash: 3d8f7ee47d369d886cbe9292df0af072
    md5: 213303156421c07723eab61e0dbc7214
work/ice/RESTART/iced.2692-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ice/iced.2692-01-01-00000.nc
  hashes:
    binhash: 53f5d45bb8f605a011c4f2439bfc98e3
    md5: 98f508b8b2cb6b5173e4e94936d8e4ce
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ice/mice.nc
  hashes:
    binhash: e42e31db00d34506e3334bfc522544af
    md5: 27e421e505142780c252127e80e457cc
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_age.res.nc
  hashes:
    binhash: 68841a7f0101645560b4a9c57a18988f
    md5: 16a29a84e11e2f77a01e1256056035f4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: dc7713ed961c9d71f211d3f405b4eca8
    md5: 67249dd8faf7e0dcb47a60b0268aaad3
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 37de7d951fbae0e875759b42e69d87d4
    md5: ca873f164c654d76d2b4476ebb99ad94
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_density.res.nc
  hashes:
    binhash: 90bdc5e17a1b51eea877bf07eabdb815
    md5: e8cbd86414f61a3ce04aca632cb154f5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_frazil.res.nc
  hashes:
    binhash: aec36667056bf201950127d3ab33c972
    md5: d25ff4e14d9bdc2e24ac7b62fd69ba80
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c97aa7ce53c49dfe0c42afac5d5641fb
    md5: 3112585fec6674ddb8a699d028beca27
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c3b808b2932d3cee2876cf7879a24d67
    md5: 6fff2e21e9503c03243fa4fdbc269c9d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 14e58f8b635375256d03d5a56b70c134
    md5: 05fdeaa54c4932625a0144273d662700
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 27297c8cf4a01cbfc8e8a413a3e1d388
    md5: e65da80c8ffda5ddf2e930c123c130db
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4d5c72f5a66ec6c93016db7602157d69
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_solo.res
  hashes:
    binhash: f8334efbb183a03ac9fa6be4c7f34691
    md5: 17881c197602e1192d23373d770a130c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f9cff139a78e0eb2abbe8b1600319935
    md5: a22a3a42085976d88b87747f568bd818
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 84f029b10ce720ce72f9fd64f0a9ec2d
    md5: 00d0c60353fb7e8b320f0c19f0df995a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_tracer.res
  hashes:
    binhash: 5a1753df1920ca03da96bc169182c9e0
    md5: fca4d082bb9076d03c2b7304325367a5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f309c959b61460f0b8868fcb94cb450f
    md5: ce977fb262af1ff3136ec97b390f4279
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: eef8afad248580ad50eb6ec004425126
    md5: 222b37a9c09602f0140ac516f3da1063
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d7fd4e7898732ce63f654acf36aee19c
    md5: 55229b60227f0c6faa1f6a1c922d7bc2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart015/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7f6d76cacb5b862085f0962e24bc0343
    md5: 2236de2f9ca30b8441d8f34d784a344f
