format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/atmosphere/restart_dump.astart
  hashes:
    binhash: a9353774faa20b41fa506574457ae0e6
    md5: f6859f4e3770b5e260233098e005bb9b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/atmosphere/um.res.yaml
  hashes:
    binhash: 51782058db9c59256854701d6746f2ab
    md5: 7a8acafd92910d96fca4af4079fcfb22
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/coupler/a2i.nc
  hashes:
    binhash: 743d71404090b883ccb7e81a37836379
    md5: fcd223780e248adaf1c3d6fa560903a1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/coupler/i2a.nc
  hashes:
    binhash: dfa7daa6b4e00cfaf2e80c2482a19a73
    md5: 2fa935f8ad9529f7e8b208b9b6412d7a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/coupler/o2i.nc
  hashes:
    binhash: 7e1dc4536d89a9268b8eb6da7b555707
    md5: 182dc110f3683e307fd4118c63be4a39
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ice/cice_in.nml
  hashes:
    binhash: 6faa5a72b9f853f265165ffb1469cb7c
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ice/ice.restart_file
  hashes:
    binhash: b173cb2ffa37cbfdd0cfa9d51e12e516
    md5: 4102bbab942adfcde6e0e70e617ade97
work/ice/RESTART/iced.2744-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ice/iced.2744-01-01-00000.nc
  hashes:
    binhash: f5020bb644cf3add7a87eddd5da141d9
    md5: e5f91ae2942dec9d897fd24ee69f1d4d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ice/mice.nc
  hashes:
    binhash: 98f9d043106770dd1d2b3ab4c6efb4b7
    md5: 6a6cb75cb0496518428ea4e74fb968cb
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_age.res.nc
  hashes:
    binhash: a1af674d0a311135ce472dbe69fa71a1
    md5: afe3448e984f4486a9e13c70eb23e860
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fb15ded341d1fe915882936248dd45fc
    md5: f616f3a865c77724e706253399963d99
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2187d256602fe12ebdeaeefddc324cab
    md5: e7088a2901af12f06031297ed8aa184a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_density.res.nc
  hashes:
    binhash: d482716b8bb71041db5a82b5b642978d
    md5: be1ed3522b9297fd4007eb9e5c530014
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9356e0173162e1951a04c1b7b4ed54f0
    md5: 783ebf567ea72c03c45ed87a9dc5545a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4792ab0554c56e6c14ca5b45989e1706
    md5: f8df0ca89f7fb3123f6ea047fd4c1ef1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3f80b426175ab1b45a1b691514637799
    md5: 08f3636548a04cd7201a688f2478bdc0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 42b234d27c1e6e6986bd41736849e890
    md5: d62d0d8a60f202eed8ccec5f4c902ecd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c94e855d59777af0251d9e1bba37d8df
    md5: a26c63dd8a5354b30740c9638ad09699
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f8b4504a7570a5abb7bf6fdce4be9c30
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_solo.res
  hashes:
    binhash: ca6b49d3ccafce2ff2ae4be01941f796
    md5: c276d5b8249a6e4ace7a93fbf932e613
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 95593c1a17742fa4f2f57917b97aee09
    md5: 742b719dc0687c84c35f4c5b0ca01c75
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d362ddc5852acae7d27aa96401344d2b
    md5: ee66751f7409596ed42805d7088ee8e1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_tracer.res
  hashes:
    binhash: 2f92e63934ce606e00f04bb1eae43579
    md5: 6b6b33e2b2fab7bcabdf639bbf51a117
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 78692bf868256ebef2806187d859a0b2
    md5: 53171900ebb97b59b8bf38d7b4c28ec4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 79adcef3f0dbb933b17bc6cda864975f
    md5: e0db8ac0739421c478e973a5a146bbcf
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4effc4fb5b754ba9700c7750b05c1a23
    md5: 86b7eb8ec63a21757ac3fc221ce780e4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart067/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 08313bf6181fbf95213ba566eefbb823
    md5: 26515d24eb18c9c9436ecc164c869e8a
