format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/atmosphere/restart_dump.astart
  hashes:
    binhash: b15507c0a5e8a0f7d2b0e76ee50ec752
    md5: cb2492ea5f305e2923a291d159eaf511
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/atmosphere/um.res.yaml
  hashes:
    binhash: 14e45b65e7a1a9ac7261cc187f6927e4
    md5: 86aac6f6fcc9b3bc474fdc5b6174d0bc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/coupler/a2i.nc
  hashes:
    binhash: 9a163e7df428cc2e9e1c7372b71bfb3f
    md5: 4aeb28115bba8e3fb5e3abf5424052ba
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/coupler/i2a.nc
  hashes:
    binhash: 4657d711ab9d2516cef5eae18fa1f472
    md5: 9519254de97eb6bf0e5ba30bdd5f1f24
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/coupler/o2i.nc
  hashes:
    binhash: 22a64473b0df9f287adb36bd0c78aaf9
    md5: 86a6b86c5e80757fb5c00be2364f3dc7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ice/cice_in.nml
  hashes:
    binhash: faf28149343e15f2cc5a6be34ff99dfe
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ice/ice.restart_file
  hashes:
    binhash: b4fcc48381d7bd52170d0a8bacd97cdb
    md5: 7ec7e6535a0ce95bb6a42183382ead6c
work/ice/RESTART/iced.2785-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ice/iced.2785-01-01-00000.nc
  hashes:
    binhash: 9b147aa84baf33a2a6c9ec57dd309ac6
    md5: 4c1f60658d0207c0be603670a775669f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ice/mice.nc
  hashes:
    binhash: 8c6c98cea68da78f68d873092ce88c1b
    md5: c7a2d93b3a62764055cd1bcb87a64a4f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_age.res.nc
  hashes:
    binhash: 94b772516c3efa48076731b7751a7b32
    md5: ed4127b6a1fab3222de111d954626fd5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2b5c884c56e405fdd1a0f503ab0c5d5c
    md5: 22b098779fe15feec46f17aeeb741c78
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3287dc5fe224395ff05aedcdc267e498
    md5: ef36dee30465032cca9bd5b2ec479baa
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_density.res.nc
  hashes:
    binhash: b2ab925b663f1c8db2bbe9182c72c16c
    md5: 1752910fc5415160a399b2755b35bab7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 13ffd0a6ba1eaf8c1cd86d56470f5255
    md5: 43716dddde483923ae3c7a369e384f1f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4849732bc58a89a503ce6df376791b77
    md5: 90ee0d7041ecc660dd582759a70e14a7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a3bffcda6eeb464a603e94a3234a36bd
    md5: 0abc32d970231f0e5b8d58cd6fec4ec8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1f7614e31e82f8a74a69a47afbc89672
    md5: 01e316d7087ccfc68454766f35e1e91c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e4f43af91d83adfc2a1b3d4f41861d37
    md5: 68932d32de4a8cccf8328bf07a8c67b0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6e79655ca31bcb4372e5ef04ad5fb241
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_solo.res
  hashes:
    binhash: 71f6dad3bcc32e4437df901153ff9cd7
    md5: 51647deeecd715871cad36252a5bf1c0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5019dde8094e5bfc5d2d07d8569c8e9e
    md5: cd516154563dd66bd23445cdce0547fe
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 848fd9d53ca1f32c0de5c130847eca45
    md5: 564ae1bc5d283c56c350a169c2a9cc5f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_tracer.res
  hashes:
    binhash: 4bce8eba3de02abb22b6691e71201206
    md5: 3d247c3790561ea5cafd1724aac99173
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 58ee0cc164155a30d334de72e92d8e94
    md5: 91bce5c42455d294b5c15960cd80597d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a4a0e0b361e405f20d785332c6850318
    md5: 5607522098900a978fdcd3cd265a104d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2b0c3f9341d9c088737a5f9070d2c56e
    md5: 006a3f85e7daa817c25b796b14876c87
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart108/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f38c2f637e74ba269863abee0a739a51
    md5: 3e8d80b32e7d2a3cf19d60e9fb7e75fd
