format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/atmosphere/restart_dump.astart
  hashes:
    binhash: 1b62a0aa4bff3cd73a95522fac09a6f9
    md5: 1f530dfba32f9c4efee3136f150a5bb1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/atmosphere/um.res.yaml
  hashes:
    binhash: 4e36a8eb2078f1a880887636b6afc43f
    md5: f26f6c33da09c88ebe7074d4ae1e4c5b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/coupler/a2i.nc
  hashes:
    binhash: f08f841487ccdaeb1e09e39b7e9d7bb8
    md5: 133acb0a3c8641c121c3b3df59be3759
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/coupler/i2a.nc
  hashes:
    binhash: 683f472db0e84e7555e74c060ad2da47
    md5: cd152bf1a6adbaca608e59d4c652ac1a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/coupler/o2i.nc
  hashes:
    binhash: ed8276767ec6ff806c6ad6beb3ab5c2b
    md5: 14db4931b0f4fd66a4b263b9d7856b3c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ice/cice_in.nml
  hashes:
    binhash: 86ad30ad0ea1e0c4620efa3ce2f10d82
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ice/ice.restart_file
  hashes:
    binhash: 91c313c54a09aceec95cc50bb71e61be
    md5: cd80505155972328abcd99688972a177
work/ice/RESTART/iced.2879-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ice/iced.2879-01-01-00000.nc
  hashes:
    binhash: 31878ebf148fe08eb47cea9dde5269f9
    md5: e4495625773077fc731ff2b1075b9b22
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ice/mice.nc
  hashes:
    binhash: 1e4efccfcc53fe4e06b073f07ceb6f4a
    md5: c22f076071f2a6baf9def4b258d2d0fb
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_age.res.nc
  hashes:
    binhash: 1748e6d9b835f16d7a65a1ddf22d6949
    md5: b23ed36005d1268ad75e97109a5445e0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 597298f7e08b38156fa73f5b74da45bb
    md5: b6d8b51904760cb61e335dae9817ac9a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5260d30c9bd9a37e4782afd13a461c8e
    md5: db76e91135a14d504b2899a0ef0bb2ea
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_density.res.nc
  hashes:
    binhash: 09bb5a3d626add092d704283eb74db1f
    md5: ad38d29116a13bb1f5ab7d2b83183fc1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 382bc7b57d417c38534e85175334fa8e
    md5: 55973fa91406fe2336966bc2ecf6ebbd
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: fa6e1b2e114086078b1b1f2caefc8365
    md5: b95eeaae678f2fb934ba768c9e083b47
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c2fca17b614f7cda24515979bec49457
    md5: eccd61f4688159dc47d530f0799ea6bd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 68a90837e04a0d8a8b89d427bcea96bf
    md5: b2936d971ae312d93aec241c94756708
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6c564004064d0927b02af88bb90c3c17
    md5: ee3de662cbb0adbc7568b7aa545f4cdb
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 37c6bbbfdc9fa2a2b1716fe10f81d180
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_solo.res
  hashes:
    binhash: 9cd8e3f794573544a19c7f00871aa6ba
    md5: f414ad640438e46f8711f73a4b2fbd22
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 183d546bb298992393fc0754c2c9f43b
    md5: e315f061d46078e5bdd3c9d2cd869c46
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7785fd385ad3c4a30e9b984d76b5c368
    md5: 1c940a0949e06681bbcfe2621bbdc74f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_tracer.res
  hashes:
    binhash: feebdbab25118ca209f345eb22d32dc9
    md5: a695dec46eb512fa2be0b97d18f93ed9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d4669fe044e92c90d3f8b5aa9cad411d
    md5: f9b91a6ab77738b67988c05223265b81
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 86e660dc3bd5236aacb2bd1a2139594d
    md5: 28d13d2763139c62c02a9ee68a886f1a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6c2e9354ad7f62246543053646dfe8bc
    md5: fe60bbbdcb737b266a3e076291887448
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart202/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 52c813910f128bea39b8b275a287f8d4
    md5: ac1e40f5e73806375e52fed6822e4083
