format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/atmosphere/restart_dump.astart
  hashes:
    binhash: b0318574bb8a205eccaf66385071db61
    md5: 66450ac12165c11dfed6e5f03328409f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/atmosphere/um.res.yaml
  hashes:
    binhash: 33f9bf52cb3bebfb31e7e7218817e678
    md5: 9d85e04683e36668c04819752d7bc9ad
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/coupler/a2i.nc
  hashes:
    binhash: 93a815b72680791ba0f0e21d19a42ff6
    md5: a0bc366380e7bf5a923f0e47096acbfc
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/coupler/i2a.nc
  hashes:
    binhash: 28456e09f7c8c75217882420b776e5f4
    md5: 63367a8511a516df4ff02e4a728dccfc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/coupler/o2i.nc
  hashes:
    binhash: 20d70de2949d8bb193b1a68b4bef1fe1
    md5: 56a93e4c8aa314037c47b9a61bcda4dc
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ice/cice_in.nml
  hashes:
    binhash: 3ed7d78d8db5b2edf105a94f042c6ba0
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ice/ice.restart_file
  hashes:
    binhash: 7bf5e0a6f5819ec93988543f333e0f95
    md5: da2500fb109d38b06d168340b30000c0
work/ice/RESTART/iced.2685-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ice/iced.2685-01-01-00000.nc
  hashes:
    binhash: 4e7172818cc63532e07d46ce83d80d9e
    md5: 3abb0a3c4d71533e80ee955f975da0ba
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ice/mice.nc
  hashes:
    binhash: 21b6f8cd9058c0dd08682a84f456dcc0
    md5: a43b7a1e4525d7acdcc12c98387e8802
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_age.res.nc
  hashes:
    binhash: 81f0e5aae1f1f5a826b72609af934dc3
    md5: 7adbd0106758c539b52b756f6ffb1063
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b1310662d7113365adf872ba0589e6dd
    md5: 6c5216ea9c273453569c51cf29bf60f1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8a85a1427c289b33b9e98797544640ea
    md5: c81bb22d0b06b1874d2d163d13e6fa8c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_density.res.nc
  hashes:
    binhash: e77fe39d538e8a7eb444f105c1fffe36
    md5: 0635712ceada3c86eaf327fa3a507fab
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8852d37c6f7759b1079a293d245f8f0d
    md5: 135479311ad8f58a70494f04a91e517e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c5738b12e478fd843651e851e707614d
    md5: 56e37a8ee7c7bcea2b43046d0550036f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_neutral.res.nc
  hashes:
    binhash: cf9baa81285081b9b5fe25f828bf227e
    md5: 0db3dece05cc9f009aa79f03887ff8a1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2b69479d149b17235252ae56424c012f
    md5: 3b481adfcaddc4f97a2c2ca2890e0d3a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1806d6e93055b51b20ab2eef90f5c97d
    md5: 9c625fbe57a1a73fd9a1fcc0311c9838
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4225db406f2036e2ad442f2f51557750
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_solo.res
  hashes:
    binhash: 8d2898d7e0534760f2cacf122aa07f8d
    md5: 0c2a2048f0404ffaa9b5183bdb3ed116
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1bc0383ce94e82a6443e0581e41b1d55
    md5: df3308c79197281811093ecb9f93762c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f1d6feb408a846fba96370e35d36f9f9
    md5: 113fdf9c555d31683d8155723331009f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_tracer.res
  hashes:
    binhash: 5c6826e74c09046ab6adb3ab596a8b75
    md5: 56fd0953f7b9210d160fdbdee33ce7ce
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 00fe2866c28a7c213683a00cb30f345a
    md5: d4f471c4d55630ba21d4c810a01bf70c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2c0b72fedf81b33d109bfb6127606b45
    md5: cfa8a8f1b130633d5359d7b6f0662a6a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: dcd5072c151a2f357668523ccd1d6581
    md5: 03e81839eea9b1c22af3a8d6a9e11a4e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart008/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8e70f96cc6ab6c42732c4e3912de6179
    md5: 752c7d2896967676b09bec5d30cbe342
