format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/atmosphere/restart_dump.astart
  hashes:
    binhash: 7387200990ad868db3866a5896d04f7b
    md5: d6fa0e99072e7c0471400be45f7915f8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/atmosphere/um.res.yaml
  hashes:
    binhash: 673fdc96575b913fe77ac484b232ffe3
    md5: ddfe76f4b9396afdac7448d256707fc5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/coupler/a2i.nc
  hashes:
    binhash: 1d27391e6e28d681303212b68c95ff97
    md5: 9d80ac6ff9e7feaad2b0871da3e34a0e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/coupler/i2a.nc
  hashes:
    binhash: 07ae0e27fdbf9e37d43b0313d7b9caf9
    md5: 51466ef0f80254d94bfac9014268597c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/coupler/o2i.nc
  hashes:
    binhash: 5b268fa78f2578197ab7894b368336a0
    md5: 4d35aa1288843418f4bef1b1c8c55083
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ice/cice_in.nml
  hashes:
    binhash: 7dcf7966e7b78d1bf948e308c09da0b9
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ice/ice.restart_file
  hashes:
    binhash: e6748edb8902d8679fa5cc735b0530d4
    md5: eff48144ec815c9d21d212641955894a
work/ice/RESTART/iced.2877-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ice/iced.2877-01-01-00000.nc
  hashes:
    binhash: 4b2b55da47ddef0d28d1a0b02df9937c
    md5: 6c97575c203b70a1c4a57cbd60b56462
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ice/mice.nc
  hashes:
    binhash: 6e4cb8adb689ebfff28b6f8acbd8c33a
    md5: d3550d0c5bb46764c681c93db657095b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_age.res.nc
  hashes:
    binhash: 6f8368c5de102b191a96c217c28981e1
    md5: b53213d0dd69f91974b743321dc77949
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5d425e562d8c7d4ebd205fb7bb178b77
    md5: d2628d137129ef19a8da5c5d36191eec
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 503f7e4456b5f742b6cad4302014b67f
    md5: 99066c40ec813be7ae1799faa26bf7de
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_density.res.nc
  hashes:
    binhash: f639965aef48ef9b15183d5a562d720a
    md5: 974c3364ab341583d9a71d7cae2c4701
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_frazil.res.nc
  hashes:
    binhash: dd5f17c51ad7f24e4cec63ef6ef86765
    md5: a77adcd54b28e9e86d36e3df17bbbe59
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7f4b64a99ba569eb5db8e1d664f586b8
    md5: 28dba7b111f28fb3adba32cbd9d4a443
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4a0d3fad76ca0a2e08d86e243704e0cc
    md5: 6d03b94dfcc7ca3eeb642722dc8592ea
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 637efffcb580fd4cb0b1a6d15b7e4a8f
    md5: 563e4dc6485d927b4d6abfafc3ea5019
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6c8371dca80d64a84a3f5f54a8cb822f
    md5: d79e2ac354c966b57337357ffeb62882
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9bd9f3cad3de38c2585d8e448950c8ad
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_solo.res
  hashes:
    binhash: c88a707b31eb682919e597c2fe7449ca
    md5: 4884ce63910af84fb61525a82aea28e4
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 94171508d0af8373221e7c8f6939eafe
    md5: 485a0f927d5fba21d91744270d946fe7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b48ffa34dc6d9a193c026946eb6e4cd6
    md5: 5e56e76b937fecdebb3b919197c22d02
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_tracer.res
  hashes:
    binhash: dc04faeb578ea60cabb63d9ab2956668
    md5: c3f70ff8886423f999aa9cf4813dfd6a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 00584e8e322031541135065b20e93562
    md5: 26bbadf1e46c1905595acf5d62e3e3dd
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: adb12d42cbcd5fbef05fb1a86f70a4d3
    md5: 1952ac6166e0f5f30a9b4dca93db4723
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a6b458dc5b37a1f49b90d7779dd5d7a9
    md5: c97d7aa07be52985e8847158dd01d754
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart200/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: abb3e0c3d2108795301f664deef85c54
    md5: b307225599ce79f8d4a717d02075ea63
