format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/atmosphere/restart_dump.astart
  hashes:
    binhash: 4c6854bd5f2b72447b9b1ea8c69a242e
    md5: 77a12713fb30b36da226577b6ba906c2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/atmosphere/um.res.yaml
  hashes:
    binhash: 17eb9cd75ca3cd593a7d09550c3ae05d
    md5: 5fce5a1d462f50e89c2f0ada953144d2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/coupler/a2i.nc
  hashes:
    binhash: 8168a3f9ee7945d64a73dd1b88991324
    md5: 6aef5574991258fc77092582adecdbb5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/coupler/i2a.nc
  hashes:
    binhash: 4bd0b6cc79b9f118cd917d3ceefa8c73
    md5: 3e4ea76bf9f168c3bcc4a597049bd2de
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/coupler/o2i.nc
  hashes:
    binhash: bfc0e82b7ddd267457dca0b0935ba562
    md5: d6a9bc7dd37c172ce3e891b343712456
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ice/cice_in.nml
  hashes:
    binhash: 3110e4ae6a7f0814bdbb3fefe6937f25
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ice/ice.restart_file
  hashes:
    binhash: 543f9afa0f7179079fb3962d96b6d4c3
    md5: 209581d1c4e6b98f255047a36a7e43e0
work/ice/RESTART/iced.2876-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ice/iced.2876-01-01-00000.nc
  hashes:
    binhash: cbc903bba9839f40a516e1cb0b79a201
    md5: 43d7477d8520c4ec2e2a54bc44119b20
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ice/mice.nc
  hashes:
    binhash: bbd954d0cb215337b706d52694395a73
    md5: 9fa8992398b1b947602a5a4fbb502ac4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_age.res.nc
  hashes:
    binhash: adf8e1e04c4451088b1733548634c487
    md5: b122566a0745e84477b8e3d1f898fa4e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4c6c2a63978453e52651ea53f2206bc0
    md5: 04940484f30b0e0e89e3bca0a8e6462d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9c416773592f4566fade150685c36fde
    md5: 18ada8ea34cda00f1685f9524fc37371
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_density.res.nc
  hashes:
    binhash: 2886ad11e86559957a37d16b9287e4ff
    md5: 39c8ddbea75e0c682d55abd3bb8bd843
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_frazil.res.nc
  hashes:
    binhash: dcd0623e6340348b552ea2257139c654
    md5: e5f406f435c7994e2b89e2f7ee0f503e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d15cfb828105bb90fb0b8c02662bc0e4
    md5: 0681f86d27699d562d32a6a4245747c2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8fb7343558d39b2e0c664abea2deef17
    md5: dc4ea79f34e9d1dd635f4fd7bb559a06
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7f6d8dc8d64bb8b36ad9709d989a816b
    md5: 97c77eae7f206189c113b8541dd47920
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8f54f005580a4aadab62fe6bc110e5b7
    md5: 286d6e71e479d8514f421dafae6e608b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8677ecd73bd58c88e97399e0d80991e8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_solo.res
  hashes:
    binhash: 615f07175ef2ae10696d9ca9904d2349
    md5: d83480577036cd01bed828939b5ca305
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: dad1bd3ac0a57ff564efcde5b97d5dd4
    md5: 58924d237c561a6f1b2e4d31d25fdd1c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ce9d49eefe3eb83c3788588e15768121
    md5: 6ccb7d4a624b83bc34127fe404e8a933
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_tracer.res
  hashes:
    binhash: 2ed1cfce0975c55e1ecbdf7d2a768d47
    md5: 4e48591d6352f54c039d4d0f8569c040
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b68b92ef36f3fc8b3659e4a7cee3bb79
    md5: 3f8b7a2273669444856822a348fa0a77
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7774d5f4555e075504f5af9dbb55915a
    md5: 94e8e6e36b187aeeb6702b57107d61e3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5f6cd4af23de9cdc7403f2fe3602257c
    md5: aaa5436f7268b26e2d73148ea76cb9cf
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart199/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 65c6d2bd8b1c53362cd6fdf33c37a344
    md5: 3239fb3d2d3877df3b24b43a8d70acad
