format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/atmosphere/restart_dump.astart
  hashes:
    binhash: 425bc3c739169dc55e0d67b5bd554803
    md5: 6b6974a4e7c2c95b95c34717e10aa056
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/atmosphere/um.res.yaml
  hashes:
    binhash: 8df90ca9a282d84368555f2e9abfd593
    md5: 6497a1e07ddf4ee5120e1db29097eddd
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/coupler/a2i.nc
  hashes:
    binhash: 10f055dd711d443dd4580cac318de18b
    md5: 422dc348b7acc0b72200ee521d4c8047
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/coupler/i2a.nc
  hashes:
    binhash: bff5bda9eef97dfd12c1ae8a7b818ca7
    md5: 05a3342be1cc014d125c72f4ced334de
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/coupler/o2i.nc
  hashes:
    binhash: 6c638de43eae689f41bb3107261479fc
    md5: d536f653fc72fa5601bb42312e369606
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ice/cice_in.nml
  hashes:
    binhash: 1a58da9ad4ff8d628768bf7be7280ce6
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ice/ice.restart_file
  hashes:
    binhash: 524c3e5adbeb4002adf9cbf68e53e596
    md5: 41c069605e0e0f51168c681c0ce87323
work/ice/RESTART/iced.2690-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ice/iced.2690-01-01-00000.nc
  hashes:
    binhash: 6f332c1939d30b24f2aceb76fb887cfd
    md5: 0755b2e976ba65971f40c61f19574b44
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ice/mice.nc
  hashes:
    binhash: a3397171ed9f34d9e8cfa2c27e7a56ea
    md5: 0ade050acfaada8366f242b5d16045dd
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_age.res.nc
  hashes:
    binhash: 5eecccc34f447b92f4fdabe8d7c8a0bc
    md5: 495de772b2d85b4ce602623da44fb464
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 16772023d8df3448044dfc445b00e6e9
    md5: 03b54e7adb5f4ab40971603f9c4c4c12
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f8517a0804e4c060c19e3761cf190be5
    md5: a00b7d540fc1c6c86d73ba41e18c9978
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_density.res.nc
  hashes:
    binhash: 618e1285629c0abf45f797be8e11c378
    md5: 74270d5fbdf3f011024639587e987f98
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_frazil.res.nc
  hashes:
    binhash: dab4b82c409cb28a9024543e82f43b44
    md5: 6c2b2e7e0d9aafefc817743d9139514d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 894423a532833dc92baeeae0c119d1b1
    md5: a920036c1f84e2ffb00a645874fc86f5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d59981670519a54e4008f7cefd5b2188
    md5: 352bfa92dc2883d49a5e844b88f75ad3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 286e5502a20fd26470e2c21e53cfabb3
    md5: 649cc7f3fdca044768d79b0019ebf9d3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 64ea62a99a5ac8c90f040387b7d1f4a4
    md5: df25922ffed4c1dd56627142879c2167
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c91948b6215fe1ec92cb083887bf5cc4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_solo.res
  hashes:
    binhash: 28ed6a697971ce1b08e83fff7d110e46
    md5: 367c9c7943d4e6b795b9fba08db76a3b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 17dd09c9d9b4412c4e474c208f0c1a0c
    md5: e2ffb6603d91271d153349162f475433
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c23cf73e79559ea00152c588e94c2cae
    md5: 2522f816b402f514f41bef22c998744c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_tracer.res
  hashes:
    binhash: 48fbea81644e6252abefe161d41fdc9e
    md5: 09a366314d5f1c0bfce2bee8ae066c5e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dddb29b781ee82c27a1f41ca88a37963
    md5: 8ec039812729dc0cfe12885e1e8b744f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 28bdf5173c6816f94bea4b1fbfe45607
    md5: fd73606174c9331f2b6b8f147e6992da
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 636ba005f04357631e5312ae597dd3cc
    md5: 4991b3e5a4df9f2ad069919e993bf719
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart013/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2293f19474a6248bd048d5843680c383
    md5: b317a39cb85c30a43405bf8570d15eec
