format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/atmosphere/restart_dump.astart
  hashes:
    binhash: 610d1d3d17a53f26665aafeb24120778
    md5: 947b5eabaeddcdd3fdcf107ca2f6c277
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/atmosphere/um.res.yaml
  hashes:
    binhash: abaac8adfdfec87de922f347dd835998
    md5: 7553cd9dcd0779cbc00f6170adceb791
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/coupler/a2i.nc
  hashes:
    binhash: fa9522dde67ca16e0ea42af41da8731c
    md5: 8b33620c7d9a3d91ebe8ca73b8483bd6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/coupler/i2a.nc
  hashes:
    binhash: 3618b8d518b24c5a7692a107786b7d03
    md5: d2ed42ef76db8de762ba0c7b71499f1c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/coupler/o2i.nc
  hashes:
    binhash: 1dbee8d1c813cb3472852b8c792c69a7
    md5: cd89bde951a7e8130b16003e1691dd50
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ice/cice_in.nml
  hashes:
    binhash: 90ac0f4593ea556c5f69855552c92276
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ice/ice.restart_file
  hashes:
    binhash: 5f0152fc115369fe14d28e348cdde387
    md5: 0c8f4166599801643c454b1cc4daa8c2
work/ice/RESTART/iced.2752-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ice/iced.2752-01-01-00000.nc
  hashes:
    binhash: eb5e587f342cbded4526961ad1770011
    md5: 311b5607ecd60036ea2325175288b0bc
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ice/mice.nc
  hashes:
    binhash: 43d576232daf0b5e575ddc0c54047a87
    md5: 4943902211e6f7149050d22988b7c909
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_age.res.nc
  hashes:
    binhash: b6466c59224ee516ccb53cbda0a550b1
    md5: 356f4fad8c92da6313bda509ab3e1b07
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 51e0e005b3bd44deeb5fa759dc174f5f
    md5: b47b3e5fa1594aaa53756dcc13beddee
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b01257b9cead7a4920ab0b9ca036783a
    md5: 4a0155cbf5fad2bc88134b0b75d84e20
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_density.res.nc
  hashes:
    binhash: cded0f7ba0ffa0fd3d4d397af77da545
    md5: 4a4a973ec2561a08ce37cd01e94cf7ac
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 99c1e2b3e9e0fd271ed6874578ca1784
    md5: c5be4a97b39b437ce8c87246735a1229
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9c212c5389e13e20b116960aac2daf7f
    md5: 97efa299716216f91a4457faf9156a6b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bd861361944d81493c1e678bb4966c67
    md5: fae351a3024fab075093e899e37405d9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bffa0f737d31905c194f7d1e7e7eab68
    md5: 43e1b41dc4f547fe79e877d2fd7c9e8d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 67b85e4ecb4fea0213891a5347e36294
    md5: 536c2636e1117cfec053281f58b86c9e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1ad569fa1aed5274cd455deb2ffd3336
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_solo.res
  hashes:
    binhash: 15583217b8e5be2c8cbab19820492348
    md5: 913b248794f1692cd492060c4f80d345
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4ea4dad659c2351d452c146135da849b
    md5: 65055a905f0919d08a930bb3697f4258
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1124594d508feeeeb4af9046a15cda98
    md5: 43eedd848b4d5b61112c0cd66a3fa3e1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_tracer.res
  hashes:
    binhash: 85502ec787a40139ace726c9fc4f262e
    md5: a5a697a20513e9a398bdf6f0b07069b6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 668c630c4c53c28f33f2ff59f592902a
    md5: 0de0d66c06b5b17012eedc0837cea0d7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 247be26025ead1011c444c80890cde2e
    md5: ccede993be60609001c10f3c9c6fd5c8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7ccaa743f91d6abf0aba004d2d60f9c5
    md5: f5ae7163c9a16738f63aff02b0e705c4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart075/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d19db61101fc0eaba6fdcad5e8a90a1c
    md5: c1372641a184377f8ce3bfbc8e39974e
