format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/atmosphere/restart_dump.astart
  hashes:
    binhash: 79486eae486a2570de3324924ec855ce
    md5: f7be6aef03c77d2bbcd16bdfe78860ad
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/atmosphere/um.res.yaml
  hashes:
    binhash: 6a309fd8318faf7448082f7fc18b6917
    md5: 22d6d5deddb6fdec204a72e219fa38bf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/coupler/a2i.nc
  hashes:
    binhash: 15e8d51333aabbabe747ddc880c5fb26
    md5: 6cc37ab7bacf59cbe7b798b621da487b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/coupler/i2a.nc
  hashes:
    binhash: 0414beffd35573fbb7b1493fcb24784b
    md5: 58c58096650ec2860806a8f8e8adcdc2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/coupler/o2i.nc
  hashes:
    binhash: 4c8f018f8f65f412c49dfd6f0dc3cfee
    md5: ad8489ceaff8821f7d5a1d8799668c5a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ice/cice_in.nml
  hashes:
    binhash: 4a89fa962e1ead367c061fb3f6d6f2ec
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ice/ice.restart_file
  hashes:
    binhash: e249d3c710b3379104339d27389a53d8
    md5: 41c36780d72ebd94f782e263cc759013
work/ice/RESTART/iced.2704-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ice/iced.2704-01-01-00000.nc
  hashes:
    binhash: 13c5d5a50c8e334f9b179150759bcf8f
    md5: 520712f93bf90be70d3b4df7cd68c312
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ice/mice.nc
  hashes:
    binhash: 51ab2847feb48edb4693a17246b8d088
    md5: bc428837d582990d15fcc9bdcc6c616b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_age.res.nc
  hashes:
    binhash: 7f117c64f65a2baae8638cf96fe44d4e
    md5: 9bf4166de6f4df8437a9dbba5aaab7fd
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1ec90b0bc4492563fec94a2e5cde5897
    md5: 40c920e755c050fe38d6a8fff5c4d9ea
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 53978b940bea113bb78a0709a10b220d
    md5: 68e98ffda5a26167c349d1074299c1c1
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_density.res.nc
  hashes:
    binhash: a04610ff6f021860110e06e7969f9728
    md5: 604ab3ef7ef6c9fa88c77d91ddf7c144
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1cf1648290d691642e45a08160e5919a
    md5: 6a78754bec2c4bab2554662069cf6a7c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d21d69e5d490c4c8d577c9255ba24633
    md5: 93a3122f96de3c84c8c9a1ff6734b06d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ac9f0e190cb18723a9c1e92ea03ad30c
    md5: b323ceca0a6e6b883b7f4a3b078c53a5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b2ab44adbe3e14d4c9af2a0b797c003f
    md5: cac738dd709f38e09c28f00928a59e44
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 866bedcfbd9275722a718eeaa504c675
    md5: c7eff8345ef915946acfd9a714972c0d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e92f776b617b143153aa7fa0104f2c5a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_solo.res
  hashes:
    binhash: 48ba5a6ffe37a0aeb91d66680df84542
    md5: 2bcb85779a9c822a3ae6b7cad206542f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1fc3d6df43d059b6196a59abd45c3267
    md5: 07cba33e3006c7ce600d956fca58005e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6a42b09aa6ebebc99592dfa9dd6eb4dc
    md5: 5593163c49048edf2fbdca80c54eab8e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_tracer.res
  hashes:
    binhash: cfcc9451974fd9c2b775756a083bd2db
    md5: 3629f276d683dc57a9e8f1ed406ce538
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 36a8515581a6e23fac6e68c172deca56
    md5: f50b9b5363c13c97bd272e719e6c8d6a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 16260010d36e106562f36a606a2438ee
    md5: 6357dc950f8e6d1eda30bd85128ce3c3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ea90431deddd922fd370be7751099ef9
    md5: af9e7229cc34471a112f5f55950ca58d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart027/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 73d739a0f4b806b59794f9648092a317
    md5: 58d3dbe526e14d7d3b5d07ae0420c5f3
