format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/atmosphere/restart_dump.astart
  hashes:
    binhash: 77c1e63e7ee055f17f944ae67e84852b
    md5: 641709846f1982cf39f00dd67a032077
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/atmosphere/um.res.yaml
  hashes:
    binhash: 903ad78848943ecb2b894ba134125448
    md5: 3d3a1a1e03d6e123d56ded26d1017d55
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/coupler/a2i.nc
  hashes:
    binhash: 0d6f54fe3cf9ec889e90785889091051
    md5: 008742d32378c5fde661565ee06e0bd5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/coupler/i2a.nc
  hashes:
    binhash: 1a22547f7881416527d9654dafc68c2d
    md5: 6f8ff26e6d5a2f90f8fa6309a7142d41
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/coupler/o2i.nc
  hashes:
    binhash: bdb3502ef71b4379229aee1d1d7bf994
    md5: 213d4d52bbbff51718bb302a1b2a3e89
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ice/cice_in.nml
  hashes:
    binhash: ac77366a1859b370520ed8e62e7bf88e
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ice/ice.restart_file
  hashes:
    binhash: f7bd887cb074e1fd6735a4271d9d7948
    md5: ec2af905bfe1a7d2d2253267530abbcc
work/ice/RESTART/iced.2748-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ice/iced.2748-01-01-00000.nc
  hashes:
    binhash: c8fe8412b6f09524eb28b41d3b507690
    md5: 6852802e5e49dbaaa76d51e3a59a5aeb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ice/mice.nc
  hashes:
    binhash: 1ede854f52c04be12385be56a7f81177
    md5: ecf0ba9771501921d313ec0313e8e19c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_age.res.nc
  hashes:
    binhash: e4556c5dece030d6811333c240058fa6
    md5: bb40e2d4570fd18e4eadf6b7237bd715
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 71db374ada45018f418a5be4c81d7af0
    md5: d8a48e4b25a6b5ea1c0fce711c0fea55
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e94aef2f2d808e3c8ada78f593e7ac9a
    md5: 901632e64a719b574fbdfe29643666cd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_density.res.nc
  hashes:
    binhash: ae09353340c7bdc06a14bad2046eec51
    md5: 574128a38195b06f2f1bf5184ba61443
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b22ed497d4c44eb0c79dc7cae776cef1
    md5: 052e26fddad03cc54829aad07c0f30ed
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d0a1d140016d180691a7e911e142ff86
    md5: f1aeb44d3afe1b6f4273b577069b863a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 665e0d62d1c824ae1a57a47ef951c612
    md5: a0cf52607a7eff6c0ebd5973af25e809
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0bf9c57704a4d474a5f8f63f6f21eb53
    md5: 5c6df919a3fbbc2ab7371b1a8ff562ef
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 22d57ef4ad85b33a666f3bb3150d72f8
    md5: 631ea48d30700663d47285201628efe4
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: bc22c51c681f42c57ce50cc91d12e411
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_solo.res
  hashes:
    binhash: 64f104bbcc501e1c99b28c00aaf18218
    md5: 58c8f5739efa94f1ec4442ba47db5370
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6fed16be9fb6313248e0c52e4865b258
    md5: 3eca6d24c0eab3d3c643fa863d5379cf
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f52581fe5aed975b7d861df4802ce905
    md5: cf6ae3867ebefe858040050f8d75ff62
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_tracer.res
  hashes:
    binhash: 308e30ed547adb4ac6157116b9c8fbca
    md5: da2fac6ee5fa3ea75c8a73a56b1d9d10
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 353a5826cd7c0cd56240f90f4bc5b6ba
    md5: 91a9fc1789938b3dcdb848c9d1961f10
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9d8f9496d5852f847b77eee5e53786bc
    md5: 1bad9559b813a03fa4cfb89b14a84c35
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4b5fe8b2b735ddf768be5235c44af029
    md5: b466d4b78ab38e98ba93ee7f45f63ce6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart071/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d2697b1e05c249ba51be280686814a06
    md5: 80b0c17ce821fef8dc2a532c7b0174ea
