format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/atmosphere/restart_dump.astart
  hashes:
    binhash: 5304332c642d6793a6ad336fba6c9f57
    md5: bbd4ade28099b879326d0123ff374eb0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/atmosphere/um.res.yaml
  hashes:
    binhash: 7aa47b5983e0f6f77bdbc920bcee0a63
    md5: f2e1f0766857496f3ffce98ed0075b99
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/coupler/a2i.nc
  hashes:
    binhash: 77fc0504e97d496c787d8c93f0c1582c
    md5: f7ad14fa472c6d1a2613a17b5bc2b3a2
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/coupler/i2a.nc
  hashes:
    binhash: 6dabff827b2ab7179005c215e2147370
    md5: 333863700ede84ce525feaaaa1bac7c8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/coupler/o2i.nc
  hashes:
    binhash: de0fcc3c59bc3f5a4d2a880ef3ff402e
    md5: 0305c355ee1ebec10e45680c4ac9f29d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ice/cice_in.nml
  hashes:
    binhash: 965bc19ff02345bded8d1f7b0def1670
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ice/ice.restart_file
  hashes:
    binhash: 35e65d886499e3fd58bee206b87d5d2a
    md5: b4871269ad562ac22a54a551590ce4d8
work/ice/RESTART/iced.2741-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ice/iced.2741-01-01-00000.nc
  hashes:
    binhash: c14e23da9a40060d5cc6a53e94c9f2e9
    md5: 25601063ce7b791353d215bdf47bbd35
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ice/mice.nc
  hashes:
    binhash: 9bb298f927cb823df14d75a7e2e23241
    md5: 144b30a2160251ba1ac07bb22c8ced7a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_age.res.nc
  hashes:
    binhash: ece192160b34445f58f0bedbbf50f6aa
    md5: a61d2440d0c60f29ff22e0e8149b2e16
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 07714d2506e8fcbffb6b9d85ac3b9da8
    md5: 8a7417749b07f5de513d8e507aeb8151
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7d38183cc8a348b83e2f8a36878040e0
    md5: 27088ba976647be76e29a9c35cb4f714
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_density.res.nc
  hashes:
    binhash: 80049873fd308f5ee50c1cbb07631c3a
    md5: 03a12c73e71b5343dc0d8e0a92a68930
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ffaeec185a471ccfb6d33f7064261ed3
    md5: cf169a1adb65947665f1e55be3153af9
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0de932dd7d6b0a46fce828bd14f23dc9
    md5: ea7870706dd8b8fa90e937723dc1cc30
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 180b3fbe335aba8917cf7d9f2eb3647e
    md5: 8efc7774f65c91222ba89c1db2b5e56e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c7b0c9a8e2e471b7c3c30cf85ce8f5c0
    md5: 95ce2111e5ed942eaeba58b9107ce16c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9c822b92b67da092cd40ec28eb84f0a4
    md5: f5afac968f306993bad79d2022dbf5ed
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2ec810d905ef64e95f25c4691854fb88
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_solo.res
  hashes:
    binhash: 5bfa6a14305a59bb98d4576cab0dc4ac
    md5: 0d02152dc0c4ea2a208134c7e4f946f5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c32f6ccdb2db2713d408d2d6f550eb42
    md5: 488db978418944b8da32d2d34537d28f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f28217bca7f7d018e38cf4be9c037c15
    md5: 2616862deba8386c8ef91944f663c818
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_tracer.res
  hashes:
    binhash: 0d53d88612dce2f7cebb1d1aee8f5063
    md5: 0fd5ffb705ea0dc827b4fea5ffdb0f35
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 876854af614dae1774c2f944fcbfc2f6
    md5: 1e3b11d806768bca9d334243d0a67f89
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 62afa78dba769a3c404af8c3ac1fb640
    md5: e521368f2e4d716909de941e4fae1e69
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8880344c17507bf120c9d549fa643661
    md5: 57cc6ac4f69636284162440c65d3be64
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart064/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 27e88e41f28953ae522af4766a785028
    md5: 5a45ff0b82b80bd061cb95b359a7a232
