format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/atmosphere/restart_dump.astart
  hashes:
    binhash: db71e181022396510acb9283df4472fb
    md5: 0fa80442e628063e3863d838ec87ccf5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/atmosphere/um.res.yaml
  hashes:
    binhash: 57ff7f16b7990ebe8675069d02397bf4
    md5: 70e7ff4b472d7d6cd9bc6f54108a05e5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/coupler/a2i.nc
  hashes:
    binhash: b57e4f2f31ad3bbf63e97a1d86310b79
    md5: 8cf181c54ff1762fd6e76ba41e577cca
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/coupler/i2a.nc
  hashes:
    binhash: 5b2c8c80fb1610322c6e97e8a3dc2384
    md5: bede51ff76ed398be1675dd1b3adef22
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/coupler/o2i.nc
  hashes:
    binhash: b5add58fe3cf920f62746d80b7967b97
    md5: 0923f277570f73604b0b314f27e19c16
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ice/cice_in.nml
  hashes:
    binhash: 4eb5fc5101107fc258b9b202b6a1a5af
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ice/ice.restart_file
  hashes:
    binhash: 6a4b92539ddb888a2ce9ad0e84d77167
    md5: 6824884ea10d9fbc92005b937019a71f
work/ice/RESTART/iced.2919-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ice/iced.2919-01-01-00000.nc
  hashes:
    binhash: 6ec733f79c8cc7ccdc678ddaa2d1e681
    md5: 8b88126480b3ed6abfec828388f9e84b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ice/mice.nc
  hashes:
    binhash: 38e2afe1861425d3a934dd9b756c6717
    md5: 113c585a39e31ae3af8113b36fb6a78b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_age.res.nc
  hashes:
    binhash: bdf2fbf7c7e7ee917103c756d32d772a
    md5: 10a4f27cba312f0e07e65e1670f95cc9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 028545eaf5691ea60199fda024d2b0da
    md5: c41d77682d519fc13d39278586200876
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 586da13dba2b678d0b9615c798ed9d1a
    md5: f394a9c9974322115d3168e0b71edb3f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_density.res.nc
  hashes:
    binhash: c17a3fbcc4c02f04911a665b85bdd765
    md5: 170dee2547a404906c5a9336e3cd47a7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1e3682b59d45a754aa2de43845b27ef2
    md5: 77ce34cbfbbd17d3c584216bafb98197
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3476e8e6f26ed70d5dfec0b9d948c8ef
    md5: 78489a2812743223cd23654b032df503
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 18d58fdf92bddcf6a6119a92e577777e
    md5: 2ec75ea26d7f4658c57d8b7ea841f825
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 82d07dedc71a110f1618a3207c99acd7
    md5: 352f4e0b0be4619e462fb9e5a09d3a7f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 543640ba4806367c5326f0e0b0316f5e
    md5: 3422b7c787a047bd31b1e4220724af06
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f8ecbe721072adfb766da784ee9a9ce9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_solo.res
  hashes:
    binhash: c486f1570a362e427f610c3e88753231
    md5: 939c5232ee353e403c3cdc82aca2028e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: feb13486ef3bf01010756820497a5f7f
    md5: bdc048c21b3eba15f187932d03062a41
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 462f54dae495c6c43ccc7a9f82eaa08a
    md5: 7f8eb1b503d9964c9f5a457712384804
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_tracer.res
  hashes:
    binhash: 743047d0d41d13eded4863e998c98df0
    md5: cc442d9d8c1ece61d370ee94b38ed16c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 287a1081c829a656c841affb7d8e81f9
    md5: 888af2d00349b308bea283925bf7ddc9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b2470656cf56b25869162607207f5a64
    md5: 166a05bd42f6691fd6593f2060a9badf
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c16990642851df81975131179eb0a7c2
    md5: 652514daa4eae4d899c05884f697abd3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart242/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 59ff122073a9a363383d8e088ec5753f
    md5: 19f7c610bada796263efb4dcb3aa58bc
