format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/atmosphere/restart_dump.astart
  hashes:
    binhash: df8ceb9c4536e9fdebb1c0e299210560
    md5: e304436d6da7bc361c130063960e93ae
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/atmosphere/um.res.yaml
  hashes:
    binhash: cb14e221461432675f774ab4ec49b066
    md5: 7fccc4f508a9cd045a7b043a188ff15c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/coupler/a2i.nc
  hashes:
    binhash: 34626ba15a77d04354f1954b35928862
    md5: fa95db70c4d75241ff9261c95db14dd6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/coupler/i2a.nc
  hashes:
    binhash: 6bad52ec3b7ca5c21dfa75a8f17c3c82
    md5: 57fc881379a551a208f4710dc61b5c90
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/coupler/o2i.nc
  hashes:
    binhash: e9febf5534127b89f47cadb54653b7cf
    md5: 13ab5bfcfdbbc16c23798b336591254b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ice/cice_in.nml
  hashes:
    binhash: 4d327e59b891ad99b92a19a35a266430
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ice/ice.restart_file
  hashes:
    binhash: f393cfe2a2ccd4b89bd35d7c5dfe576e
    md5: 95a0fba23f3a0779e9a2dce4e54cc4e3
work/ice/RESTART/iced.2934-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ice/iced.2934-01-01-00000.nc
  hashes:
    binhash: 562042118b952c4ec7ec4282a7702f80
    md5: 3771029f5e462b286dbf998f2063e11f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ice/mice.nc
  hashes:
    binhash: 9ef194a5222636feaedef78575b05cdf
    md5: 67c4c54b17f9850cfd8425589ff3899a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_age.res.nc
  hashes:
    binhash: ed3a8af30d9c6e35839ebc58640de604
    md5: 37e616b2b4ffda1460b44e059b7109dd
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 828f8ed5385a60a2ea6ff3a30c354d6d
    md5: 7ec5698db6870bb6820c0fbabf8a7131
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1a4493f16fd8284d4e9bb4b2279af70a
    md5: be1d97cf8199b38bea47078934df59db
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_density.res.nc
  hashes:
    binhash: 4e773fd2c43ab0f7774bc7a30dfc5689
    md5: 4e7359542fc1f6ffbf08711ccb7d2e75
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d5c215fc2cee9c7a482e4f4f59411c05
    md5: 4f305141f1485bec47291222c1283480
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 230f0d20301430fcbeebc5a7ef622a8b
    md5: 4bcd9cff9d4967910a91ab1f0e66cb6e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b05b70d62b97f3ec7f34410a7d2351b1
    md5: 25a874bfe0986defa553cfbe30fcd287
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3d85dcb70749fc36ef1c7392c72be236
    md5: 3a1bb44ce6daf5af989e2e9b2ef12ccc
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0da1bf2e02eb2083ab955cb3153a88ee
    md5: 4ded91365a9d79516a28e0d23d07b8d0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 35ffd5d99f258ff4a301186f6ebbcb43
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_solo.res
  hashes:
    binhash: 6b637e52dc7f110a373866e766cefdff
    md5: 74ffe136c317d8ca62a2924f4ccb9dca
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 46f40e2f69d4c3b638d2ab06833e467f
    md5: 8fca02da9a6768e922a117db801c5538
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2a73f45712f5e3b0548e22931483ee17
    md5: cdc0c8598c65a982b1a8689233cdc913
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_tracer.res
  hashes:
    binhash: eb1908a8218548d93b635cde95b9d8cb
    md5: 956700f3dec8f1463e9938272ef6fd60
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a2f271a1be1a8edcca11b13e51d1ebbf
    md5: 19d3bd60b41259a8aedd8ce9ff5a478b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 181dba3f74518f0d081c670b88fd6666
    md5: ca1cdd9b066b69b1b8ff3d5f21e93ba6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 45756af939dad435ad859ed88de26816
    md5: 8e45515e76a31aafa01d5ee92c80b03d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart257/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5e906c8e6901ed9a8448939c740c7e4c
    md5: 2324274e49a07f5ca052cc9303c66861
