format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/atmosphere/restart_dump.astart
  hashes:
    binhash: 61557e50729f2efa3f9614d342bad4c5
    md5: 52ba862d8ab1a8ece8c28b8dd6a261cb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/atmosphere/um.res.yaml
  hashes:
    binhash: 9e6f28a1ca8ef56c37f224cf55233aae
    md5: a849165ee0e542669b4105374e6c59cb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/coupler/a2i.nc
  hashes:
    binhash: 54d4dbdef6a2c75115f8943598b55b06
    md5: df27d0e881dbb75aaadd356ad612805e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/coupler/i2a.nc
  hashes:
    binhash: a409bbed095b854f6d6c28b84bbb11ab
    md5: 6948a67b1278018ffb57f6e70fc9e636
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/coupler/o2i.nc
  hashes:
    binhash: 5ece4b609eb1013ddb9e1bd78fbeb820
    md5: b301d80b7ae0557a2b91c50eddcf7ae5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ice/cice_in.nml
  hashes:
    binhash: 9860120a70318cfcadc4e34ea1ed81fd
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ice/ice.restart_file
  hashes:
    binhash: 8490fa384be3e076d4ce0a7719256439
    md5: f2ac5a3482a824313f37ae4a90523891
work/ice/RESTART/iced.2896-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ice/iced.2896-01-01-00000.nc
  hashes:
    binhash: 8b64d5aa5fca8c0ac29f6c6665f5f43c
    md5: e465b31d1e2ef2ee79f34d681fb2fcea
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ice/mice.nc
  hashes:
    binhash: 7af01fa349bae287301854434d26710a
    md5: 1527470280509f8f27bdc88fd32a4fce
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_age.res.nc
  hashes:
    binhash: fc106ebf5745331f100a5851549829b2
    md5: 43e3d38657806995dad29f2b6c021e90
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b065fb8bf4dd5f756813c1e69ac7ca0d
    md5: 21f823a4d7261fb3028240a472fe732d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 40b2f6f0c4de74a0f00240591002fa17
    md5: b5bb95670002d7eafd33557658376c2a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_density.res.nc
  hashes:
    binhash: e5e25285857b26e984446b9cb5cb226f
    md5: 7705c9eb338808ae95f9ecd000c97378
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9f7f24b99d2ba652c23b68ed2f80d7d7
    md5: 39fcb96cab75fe934071ba7f49ce8dbd
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6f162074fcee6060a4628fbf70101352
    md5: 8609b3d9e2dbf39e00e778a86623f0a5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 387cfab13efce76e010a9b8ec38a0b30
    md5: eaa704b97f2608d99907be6963d3ffbe
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 04e9698d530a74365a33b3ab7f5f9554
    md5: 541ebb6ba3230c6323efe96eca60ed87
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 784f5feb94449ec450a9e0e6a2a3770c
    md5: bf6094bfa5cfe60976184d1b90559789
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c405c1ee9d9aed52ce2575d2c2b5f9a7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_solo.res
  hashes:
    binhash: 2b290b75c4cc1c7af20fd254877b008c
    md5: 1ce49e537e0caa03049b1e923f89b253
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 002785b776fa722280435b0dd5cf885f
    md5: 95d38d34e60287eb0cf1d2214e9da056
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_thickness.res.nc
  hashes:
    binhash: febd95bc5141a072d6b57a8048130bca
    md5: 43cd39407f4b418a692f2aba7c07e319
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_tracer.res
  hashes:
    binhash: 83f5601f4b9c2f9b2cacc49e5b16330a
    md5: 0c47e33bce40eae92c5223a6c8e7bbc9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bb628634cf4dc48e17224028020471df
    md5: dd695e0db7869f1b045344e8a4b15322
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 37ee425264542190c45029818bdb4d5f
    md5: af7a59548bcad84ce978341ae805ece1
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 568d5638222eb61d2bb85c1ee772ff90
    md5: 7f5412c0f61e1a92059d6b5c7a56352b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart219/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f039bc210c2ff05345b74038ab5dbbb3
    md5: 7fc25f9f749981b882c35b5b210673ec
