format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/atmosphere/restart_dump.astart
  hashes:
    binhash: 44ace7e1d6e97ee8e7ceb8871db9b19e
    md5: 651c579fc45da7fea696f8973ce9760e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/atmosphere/um.res.yaml
  hashes:
    binhash: f84dc75aff1034056ce71b9a40fe1e66
    md5: 9ca578d170c3b46b594661b940306409
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/coupler/a2i.nc
  hashes:
    binhash: 45b3d250eaf06d00e25c32f9939bc026
    md5: dd2af3bbfed4b341263a5f63d66ef63d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/coupler/i2a.nc
  hashes:
    binhash: 834a7ec351d9aaead4d71263eeb89217
    md5: ccc5d444814cce910812ec58be9a9ec7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/coupler/o2i.nc
  hashes:
    binhash: a5253aeb2a4341c38dac892b0fe390c6
    md5: 5c3a8e580ed5eac60c7f9537a94c89f3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ice/cice_in.nml
  hashes:
    binhash: c60156a2eda32cc6fc97942f55179b26
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ice/ice.restart_file
  hashes:
    binhash: ec25649dd909d806579141e5942fe341
    md5: 9efca7b98608274db8838d8b1e612791
work/ice/RESTART/iced.2888-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ice/iced.2888-01-01-00000.nc
  hashes:
    binhash: d9f2c1649b66b8971cd29460efe9de48
    md5: adfba2dbc8ce8bf99d3d31ff79473f8e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ice/mice.nc
  hashes:
    binhash: 2e3ada16581d0e1ae6933909f2464869
    md5: dc5ba05b228dd74e7dbc7814ee3970a4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_age.res.nc
  hashes:
    binhash: e155f297ac8eac853bf50759140941fd
    md5: 38f9b3bae134d3c72466367c35c3272f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5f8495cb375c01596854b47e8662c494
    md5: b6455b12110c4f1c89ebe4af3084e562
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a2101793092538ec6ca51ffea4f7f2ba
    md5: 870f9e4f6431c46a6e5c211d5e0c74b7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_density.res.nc
  hashes:
    binhash: 86af908c26c6fa9748cba37f62a659ae
    md5: 7207d0fa5f828fec0b17d16e5c0c8393
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e8031c261b9c24cc2a5eff0297270b03
    md5: 5c098adb8f4fd1a0ffe634675660a9c5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2c3ba29be6918dc1676cb8bf63bdbe4d
    md5: d4e0743e4c5e1f94ee5504a96febc099
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6c3d9afda445e55db477e56f452e1294
    md5: 28d8a9f31370b4d21489d5efb469dbff
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 425288ddce1b9c1d159112ac770a1a6f
    md5: 5423b341cb68a38c189a7cb6c3ae2172
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f1f2da75dad734ce2ac6130e246d828c
    md5: b428476adbcba961676241f6fd5fbfbe
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9a0a587ef101072daf5c1c3864aedf9b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_solo.res
  hashes:
    binhash: 7fca9159d3b244d4e5804c761ed45959
    md5: efdfa02f78cab45f35e821180661f2bd
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: dd5df38041ffeb66fd0053abde1a9f69
    md5: 2b5e6d914d1c8d156fb452904946ec8d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_thickness.res.nc
  hashes:
    binhash: fe5acf7bdd2a6d7a1ecefa41e69365f2
    md5: 8546a79e03d5f3d11ffa006049b59f4c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_tracer.res
  hashes:
    binhash: 5b13eb375176bfa064dabbb611a7fee7
    md5: f62ea3420143395bf53a9a3bd191050c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e6cbcd40d8092089f4570d675514b016
    md5: 7473fac7da09d5059fd4ca8915fba5c3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cc4cb7baf2c8148802888c61f4adba56
    md5: e38e0451ec646425c8ca62b3ea5af97f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2e4aca9e03dd77d47f3aebbb2e095e48
    md5: 5321fcf7e87519670d352343cee673c6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart211/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f4a8755a102721ecc7ef61330a42d14c
    md5: c50b1f1f7c5710c20b765655becd254c
