format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/atmosphere/restart_dump.astart
  hashes:
    binhash: 7656289dd2c81ec5f52c8227ea60ee98
    md5: 3cd7523d33ea7ca446a3d702bf0c36a7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/atmosphere/um.res.yaml
  hashes:
    binhash: d22997826f05d10ca17c3659f9aed91e
    md5: bd6ab48ad8f7d4fe77c551253bd20e37
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/coupler/a2i.nc
  hashes:
    binhash: 96be73b0f4ad80ad6d98440dad64544f
    md5: 097092dab295334d6250af739621d4b8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/coupler/i2a.nc
  hashes:
    binhash: 012367bf80d499f25a6d8f4bff3c2301
    md5: 5dea46dd094d8eddb8611f6a8424197b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/coupler/o2i.nc
  hashes:
    binhash: 7e2015712211b67e852a8bd2d107c3ec
    md5: 4ee5c76f6cbbbe65e961181d82647cd5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ice/cice_in.nml
  hashes:
    binhash: 0def20fc7166517d4434b435820d5912
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ice/ice.restart_file
  hashes:
    binhash: 51bbba954c722d13d9d62c644f2dc977
    md5: c41f2799bcf7511ffb58708c2b6c42d6
work/ice/RESTART/iced.2907-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ice/iced.2907-01-01-00000.nc
  hashes:
    binhash: 0622f9039b9799db1e4acd3f5b7c9ae0
    md5: d01def46d204b3c96dcffe37648de93c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ice/mice.nc
  hashes:
    binhash: e6617d66316e0cb5b86c61807e90bad3
    md5: ffa5aeb683e8d2453ca4737efd17f141
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_age.res.nc
  hashes:
    binhash: 31e040156e80faca276690f3cd803dc1
    md5: ab8f26b11817e542fc6d3e4b543149ff
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 43e6b7d71523a869d61f8eba2feb6d24
    md5: ea972687c161de0d33745b6ee7782c79
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e5448e128bd31732a9cc03974c2b6c58
    md5: 192cf7e19725500ee19148cd0f32b932
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_density.res.nc
  hashes:
    binhash: 04a5f668c3aa1cd36745588adb2bbd53
    md5: e11a5eaaa8c8695da585e78c9cc6f183
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4089e6137b56c742483273439305a0ae
    md5: e91e86adbc7b11837a9da5e1a6a0984e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f55209727c732e7fe6a679e17d075771
    md5: 780b64ef5976a45601ddadcbc78fdc64
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fca08d8a1b8327047491c9c74ec8489a
    md5: 933868d9e19c5ad3a7ecd24924f4e4e8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9d3ea69f45acb3fa78d47a71e62efc14
    md5: 52e4f6119201b2cc1fcc62af84cc117c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0b03b11e08150b69647a4a6d4a1de424
    md5: 3213525852b327b4e713b7156f244b18
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d98011879fb9941b403a1778785e4073
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_solo.res
  hashes:
    binhash: 58cc3cebeba3104a691a5a1d03eaff0f
    md5: 94d27f25aaee1c6f4ec4b0340f5e7bde
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9c4720a9507d45e92dd44d53882bc045
    md5: 5c5710de594b14f1b8269b4c86625721
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_thickness.res.nc
  hashes:
    binhash: aaecb2b3c50cdbfc844879341548e3d7
    md5: db5cd2c3f943f11544353e5d361829b6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_tracer.res
  hashes:
    binhash: 621eb99a68135a661b988a147405d547
    md5: b683d10b159bdc7331444ead5cc845c4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dabdcab8b8bdff05c7045407475aaf46
    md5: d97eac704972926e4f3634577299ae0b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7aa232c538a4f654e1fa1a41644fd6b5
    md5: 43de4170405b6bb1188532f1d437fd9a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1285ffb360c0982e2dbe89819ef9eeb9
    md5: 1aa08698034f0692818f1483dee991ca
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart230/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ed254b291a267aaf2f7132b923973cb3
    md5: 4f5a479aacf866e58a7457fa249ca8a1
