format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/atmosphere/restart_dump.astart
  hashes:
    binhash: 69e2d6e9b91d39524adc3da76b82425b
    md5: 1ad6aa7342de0c93c5c930377e1af7a9
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/atmosphere/um.res.yaml
  hashes:
    binhash: f609008be491fb55a545e32d212bc363
    md5: da5441d5dc08f24bf374296bf46c28b7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/coupler/a2i.nc
  hashes:
    binhash: fedb0623e053e42af9601bb6674792fb
    md5: 10bd8cc627b609dc48b7c7f5f062f68e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/coupler/i2a.nc
  hashes:
    binhash: 70fd17ef9fb02bc0f0506cd7fc5a1b96
    md5: 5405bdeb3f01bb9e121e6b67304f4ca2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/coupler/o2i.nc
  hashes:
    binhash: 9969965f6ed6989b82a94bca43e5c145
    md5: a5be49d72fc4edc67015ad7c2b2b74d6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ice/cice_in.nml
  hashes:
    binhash: 927383361d2ed1588be1930c9a025698
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ice/ice.restart_file
  hashes:
    binhash: a7d9ef67865b044c2b970648d140ee99
    md5: 901ad3e68b367b1b6bf339dccfdcbd0c
work/ice/RESTART/iced.2948-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ice/iced.2948-01-01-00000.nc
  hashes:
    binhash: b2de70de18785630da3f86e0e8adffe3
    md5: 8035bb7cbd662706ae02795301f3b6a9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ice/mice.nc
  hashes:
    binhash: b362d526e0dd89b546e4037d8781a5f3
    md5: 2efe585bc32797e2013f9f8481249c50
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_age.res.nc
  hashes:
    binhash: fe8ae40d8702bd0b590caa1e373c2bb0
    md5: 86eceb449973f200ac0a466b50b340cb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ebe3bbd6e969083f380447938fb073a2
    md5: 8092caf7a6c89788a830b90813265bdd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 56b649bbb97cac8dc1b7996276bd1cd1
    md5: 3ad4ab18129d490e090aeb2c5965d187
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_density.res.nc
  hashes:
    binhash: 1247e66c18967b22ccf4722f3d98c60d
    md5: abbf4a56f36954712fc3298456dfd856
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0c57803ca915ad0553d036436836e753
    md5: bda4ad4946b7ca544f27102627113113
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7d85ef4d9fa12c690a8f34cea3d91ad5
    md5: e799d66e4870e38b9ac9899648e91b61
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c8e4844156ea363c45ae35a6e9e03140
    md5: da47c44e94e356051351741033b8ffb6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 16a8af32bb305f0002e617ea114a26f2
    md5: 34170c00b1bcd69bd3315180582eae92
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 43a7067f3ee43fe752f554e1104da4a0
    md5: 3a9b1038e4dad202de215a5a1bef3851
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e400387dcf25231871fd62ced030325e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_solo.res
  hashes:
    binhash: c80df1240ef617cb8c5bbd25aac1f862
    md5: 5b50aeaa83f3d24e77235fba76e23f06
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a95b7753bce28f8afc637467acb900f8
    md5: 4dc824720f44dedde5e9247af5ac1124
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_thickness.res.nc
  hashes:
    binhash: dd5fcfefc77c3571a26e57522e6cbd17
    md5: bfac63ce374374b852b5c8d3c0eb9e53
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_tracer.res
  hashes:
    binhash: 864c28ae850572f351d048320d37f737
    md5: b86bae61f9fe31d2a53643419666eff7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2022df5d49f7b717131cfa2b60fbf535
    md5: e6d77106462d62486bffafbddb074647
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4027ab10cce7cb3e2ab030cb4175b666
    md5: 23eedb5ebf7897c116cb910f441178f8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b57ee50ae448a624885d4ecf51d3864a
    md5: 3cd7d5e4704b887688f3b78e3836cecf
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart271/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 815614b304cdd51bd841cf1eb6f02492
    md5: 2d3178bc8263587e21d95a0bc26ff0ff
