format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/atmosphere/restart_dump.astart
  hashes:
    binhash: ea114b63f46cf16a8491b581c195d521
    md5: bf9ad5a2667712773e0ae8b0cbdc4ffa
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/atmosphere/um.res.yaml
  hashes:
    binhash: fc17d29a2cbe7530167db00d48ae97f5
    md5: d50271b857c90968912a07776a66bb81
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/coupler/a2i.nc
  hashes:
    binhash: b6239e8e688e8aa1c50ffb31bb8004ac
    md5: c2ea4e3ea983e86d4309e347f1021287
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/coupler/i2a.nc
  hashes:
    binhash: 6b2ab5689227d6b7a34335594db887cf
    md5: 91d0838150205e517fc7fdec3924717e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/coupler/o2i.nc
  hashes:
    binhash: 6f019836c87f4010c63138c05031391c
    md5: e53d245e3ea645785fb8bfae822ef3ee
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ice/cice_in.nml
  hashes:
    binhash: a16d499e22b028169bb030d2c1458492
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ice/ice.restart_file
  hashes:
    binhash: 91effb4a5e53bec91fae8e03f08fa1a2
    md5: 57a6ab741caa05e39075e2823e0168b6
work/ice/RESTART/iced.2709-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ice/iced.2709-01-01-00000.nc
  hashes:
    binhash: 7acb4187d760825a841f21d349106f98
    md5: 87856b9b0daa067ee9b40e3218908a0a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ice/mice.nc
  hashes:
    binhash: ab5a7cc051fcbdff485c7956d001da24
    md5: 3d94bac2bb7afe0c263ddd6a059ea462
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_age.res.nc
  hashes:
    binhash: a17dca67b93624877cdf7e728fc39f17
    md5: c0bfdf0a062582e90bdaf88414309082
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c5995a6bc1b617bc4cf3ceacdaed2b10
    md5: 44e1a9efe3cb43de9f2d4a6a35bceed5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4a6f68d5345b4dfd6d9a1e45d98e3eee
    md5: 3b8295bbb74feeb3f106b0e7000e18c3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_density.res.nc
  hashes:
    binhash: 01a2280b89719baf87b77d60eb3f1b12
    md5: 2e732263190bc13252dadb47ea61acb6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 29539dea182fab047b1498e0a34098fa
    md5: 2910ceac9dafe8c459147208f36bc4e5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c7acd6bca01a45690397a61ee0c69e34
    md5: 738d78547edfaefc322241d3f0f603ba
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6cdc5047109ccd7122a060a86f15692c
    md5: 8224b9ae6f62f890099a8f37d94f638f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2bad37a9bd9c5abbfb9db865b4e5d810
    md5: 4b070cb71b365c04cbb6957d6afd776b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c3f308f6e2d86d8ff7e6beaccb592977
    md5: 5d00ced6f1250532f38a0ef634064efb
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c78eb8bfd20e911e1ae185a7bdd123ec
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_solo.res
  hashes:
    binhash: d1a0c7f33d36b4ab9edfa3a2684f2047
    md5: 4106d1d2461f80f9fc1923c6ff672535
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6e9964e8dc4eec338eae8fbb8a50e93d
    md5: 100a403b529e7752aedac568f9bffeb0
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 63a1eaa6fb6142c8bbeb5fe0e372641f
    md5: 12129c911f7313ed86b97e4f842102c3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_tracer.res
  hashes:
    binhash: 9f97b620b8adc9e00299afab3f41bd7f
    md5: a8b9122d26fb579c78cf36282f8d6330
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2f3c337dbd9c36d1bfaaba9993dcab8d
    md5: 594028bb7ab88b425d98a9c67bfb66ac
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 39d139f07b3957c5662e56f4957ec027
    md5: cf89248cb12519e45ba99625086bae8b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f90954b514ee0e08cbab996a983eb597
    md5: b2014b235a53b14284b3a398d622932a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart032/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6546b3c2e4fe6fe5c0c87333cc39f988
    md5: f4c63b2fdc1c8741a4e0aa550f69741b
