format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/atmosphere/restart_dump.astart
  hashes:
    binhash: 94f9b01ed51f1cd897734e6612c77ab6
    md5: b099a1b1a59806f745f244bda09562ea
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/atmosphere/um.res.yaml
  hashes:
    binhash: be72de84e9ccc798d70b3d73c402a418
    md5: 1a71d3b50644e035231ad28a1261bf52
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/coupler/a2i.nc
  hashes:
    binhash: 9c1953e542ddf645162648b415b913c7
    md5: ee1be809b96c96425268e5741aa2efe7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/coupler/i2a.nc
  hashes:
    binhash: dfcdc9db57261dd5058e88b9a94c7f4d
    md5: 88c7721e9482c61676e41f2fa31ddd9c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/coupler/o2i.nc
  hashes:
    binhash: 089cc40f74979b9f1f84162a0daf3a61
    md5: e7f8f5ead4903342841ba96f8e2de9b5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ice/cice_in.nml
  hashes:
    binhash: 921bed9647837b351c7b8cb8fcd545b8
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ice/ice.restart_file
  hashes:
    binhash: 1d0052f80c60c25e80fd513f0881c34a
    md5: 18745d56f228dcac3b52824592ced056
work/ice/RESTART/iced.2908-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ice/iced.2908-01-01-00000.nc
  hashes:
    binhash: c330c987b737e3a671cf45b41a504d06
    md5: 44592fe05bf7a4296731d398c4c27937
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ice/mice.nc
  hashes:
    binhash: 2ec282784241f26fe5769467b2497e61
    md5: bddc1a2605cf8f977c07d4bd95d92d10
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_age.res.nc
  hashes:
    binhash: a767eb421ca99f888ea1f342edcfab04
    md5: 63f7a00456d3a6a2cfecb985550e562d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0da0eba23e315cd45f7a3e194c98c645
    md5: add851e2199e49af2c0ccc8451281cb5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 301b7f2e0b7beed450b6f9f70ff6f6e5
    md5: 92c825104d0bf096fc85cb76afb9db72
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_density.res.nc
  hashes:
    binhash: 28efc71591dcc530fa21689a3c045341
    md5: 8933172fa5b553f494497894f2f1be1c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b6b89dcf0de551c7c4c6a34e0863669d
    md5: 7cad801da66a68fff671740f5c3f0834
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 68407fa1122e284e9196e8db7ca074ac
    md5: 113e82bef536c96b3a515d7d6b714f38
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 92be623d5998ba4819c0c07d15bf9c96
    md5: c5eec21cd5959507417a147717738c2f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: da0b6d49afcb08a7fe362eedae1ca880
    md5: df51ce4be8621ef4be3d3dad8265235a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5778b960cfdcc8cb3c312aae9b20a17e
    md5: 6d3e6eb2bc806aa077e097aac066e9df
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3d4eef076fce538e8e98b7e654905645
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_solo.res
  hashes:
    binhash: 6d5f021531d53836edc06cf8ecd0ce8e
    md5: 04d993a45814ad55406fdd58b49a26d0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: dcc3530eb205b06a8e619a4e8ad69bac
    md5: 7b1bf363addbbdb0e8a1929f8e05ec31
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c86a11e8227ae276a75978f8717184a8
    md5: 2463dc69438611068ff3dfc271cdd156
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_tracer.res
  hashes:
    binhash: 1efaf1b458d39f5110d905d34c985805
    md5: 2b5aa666131cb6f49c63e5b00d761ef1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bf399ac86a282c2d087a748558521072
    md5: 441d7dbf44ee8124d3be9c1058cc9b2b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2b38b15256a94d9713fa41663277dca3
    md5: 340d719f7a7d8a7d1679d8766cd54e57
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 328a380e82ab743fc37d4e5756cd0206
    md5: 5e3112929cf79952491682d4d306274f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart231/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 79ed4a0a36397a76b219e9dbff6bc126
    md5: 4edc88e18c7f0ee04e381bf670b7c300
