format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/atmosphere/restart_dump.astart
  hashes:
    binhash: fa96a3cee0f4a72b551c2a8028b48bc6
    md5: 3fe81881d426c8ea3491a1e85112e397
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/atmosphere/um.res.yaml
  hashes:
    binhash: 9a1ab780bb9cf422ca90b9a628b5f27f
    md5: 8015cf48376ab4336e646bd501219b9b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/coupler/a2i.nc
  hashes:
    binhash: e5d5791bfffaac0b9fe7a24dd7e929e0
    md5: 4e0fef0566e92aed2c18c04c82e01386
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/coupler/i2a.nc
  hashes:
    binhash: c8319c6d025923b7dccce25f4090b815
    md5: 370dfe3a4a679cbec0101055d929faec
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/coupler/o2i.nc
  hashes:
    binhash: c58c29e1b8fa4ac1f0302197366441a2
    md5: e64c9aa9435d1fce661637d2671774e1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ice/cice_in.nml
  hashes:
    binhash: e3035e835120a5d943a889db1ae3a323
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ice/ice.restart_file
  hashes:
    binhash: 26cd24c8920fcd12d934a2d71f72edaa
    md5: 7cd9fcc9dd10c5d877b4e1b1a1ab75db
work/ice/RESTART/iced.2913-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ice/iced.2913-01-01-00000.nc
  hashes:
    binhash: 1909710eb29fc6115dc592ef5002e52b
    md5: e520ca0bdfd0b987ec86a6b9b7931a8b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ice/mice.nc
  hashes:
    binhash: b0b9f28833eba775b430c12fe9f0ce59
    md5: 55faef14ffbf1aa8a18579379cb93666
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_age.res.nc
  hashes:
    binhash: 950271e0af8b4a31ad28ed5963b1dda0
    md5: f78fdc4a32b26dc762e8c8fd2f37757f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 380f00b63ae1ee2cae93a3f9b301e500
    md5: cd6e42bd779d9751d0f3c30f87d3cc55
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f401a583b489272e4e90cc4babdf39d9
    md5: 0c49a8cb1df69b99a4c19cc692e91bf5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_density.res.nc
  hashes:
    binhash: 5904fe674887be3665dd5ece80dda1b1
    md5: 5be0a7d3c531930a78c9c19e5f1f64a4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e57c58afda95acd34e8bc95b28ddfed2
    md5: 95d2d53c4f976df1337c8c7f35a903c1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 269e3c8163689a815b25553ef0f8515c
    md5: 30ffc98ba892b70ba431fdb5aef21da3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 533ab900e4f53a1b13585c75a112fef4
    md5: 52690fe890230143188f72b56764b61e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 111e54c19d32da8d868eb42bae4da546
    md5: ee2589be53f30056e2bd20afa2d98629
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e0bfbeaea340b7723c92c5fa93ffdea0
    md5: beb27a191c7c55b09fd3c74dbe1a549e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b98bc2b12dfcf38ea9d4419855956b5a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_solo.res
  hashes:
    binhash: 772715500fb2941bdfc0fec28d4ce5ee
    md5: f67afa593d21efb26519505dcc100d22
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a95aea6c4bcbd04714f06fba7818bbea
    md5: 573407a267f3eb8aa3309ad0141350c6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9da4b158181613b964700641e4c4e42f
    md5: fc1a59a5a87bdfbcb38164e78878a9f0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_tracer.res
  hashes:
    binhash: 1a17c1110b599a918c6a20b601c30a3c
    md5: 68995ef0810358af4cf82c59c53feb6a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_velocity.res.nc
  hashes:
    binhash: fcdb56800b48f145b00a01ab9cf85ea4
    md5: d4447b55fddaad36fafe430e49d86ecc
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f80b3d47df06fdb12456209fd0e99c5f
    md5: f695da305688ce8493bc75b6b393a1f9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 86c6fc74f4271f958b4efefda0777b99
    md5: 95000774f0abf55218266ba2891fe58a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart236/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6368bf0071b5a2ff2040465342e15800
    md5: 1b90cf4b8867616d9dd031eb48881d7c
