format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/atmosphere/restart_dump.astart
  hashes:
    binhash: 1fba3bef5849ff8d636628375817ccff
    md5: 8f26441e3f45c3e793dbfd755b2e0f37
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/atmosphere/um.res.yaml
  hashes:
    binhash: f3d519e2a1074d7e48f5a5b0a621ad40
    md5: 6acc3c4cfb5a3580672b73e1be83ec2d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/coupler/a2i.nc
  hashes:
    binhash: fd84e737705a10460435d1f055c06249
    md5: 98305e6dad344487b88f23a1775ba7b8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/coupler/i2a.nc
  hashes:
    binhash: 7134a1943193e3262ece3f2a3bb02863
    md5: 3fc32f39283109dda9c351529f327ec4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/coupler/o2i.nc
  hashes:
    binhash: 4d10dfe3eb2ef8be85afdabe614bd58b
    md5: aee1ff9316f95177af96c29b357263c0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ice/cice_in.nml
  hashes:
    binhash: 1c6be04616b003e7053f3ac86609a2c1
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ice/ice.restart_file
  hashes:
    binhash: 85a9b9d5144320cf7a3758266789741a
    md5: da978cfeaba9666628f4e55cea52188a
work/ice/RESTART/iced.2703-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ice/iced.2703-01-01-00000.nc
  hashes:
    binhash: 520ae06a8092069cf1207aa0925d5d67
    md5: 6675cc7a93822e9e3b7b1ff1a4b2418a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ice/mice.nc
  hashes:
    binhash: 146e3b837239151e1dfa843cda4c5c7f
    md5: bdc5aca333afb82ffdc235ff78fd3843
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_age.res.nc
  hashes:
    binhash: eadabeb740685ab0658e13f095aeafc1
    md5: c08be2c005acbdd6d9c504f7cfd13da7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 434c1bd97a821e43bf706dcd9226839e
    md5: 54fc28f7ca9f7e30211e1ac0b17a0aa9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9252ff6472db9f9d4a2c13210d9fa267
    md5: 61c86b32dbb8b7aa473dc77e9ef627ca
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_density.res.nc
  hashes:
    binhash: 6e6fcedf49d0d630ecaedada2c5b6596
    md5: 9bbfa2450016b8d0eb13041bb414b78a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4da1b0b86a91373fd500dec816457ed1
    md5: 4a45dce023cac697766c6483c2041290
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4ba4fe70854daab2334f1ee678b86fe0
    md5: 7c6b688c1809b94b716dc135ea3cb071
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c39a5fa956e485dcb0ffa9ec474342fb
    md5: e5765b2cc3b0d76f6e487770997ddee9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d9b66f72a9cf643c0e94cab3388e55af
    md5: afefb26ef8cee255bd9244dfa1bd867a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 77e115acbc86ea098a6c15d74ef99560
    md5: 8ab3a3284787988d34a1ebc181512ad8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3f4b2d62ee40620e664c8c06ce8fac96
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_solo.res
  hashes:
    binhash: 6d1df53e130ad56ec5b42e1439910ce8
    md5: 9d04cd64197f4d4f8748d267610524f1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 628af9824a7470ecce9ff4c9ef0c5be8
    md5: 588559751b1a8d3d984c4762b38e9a57
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 533b9abda174ef4d377058854dd9534d
    md5: a952bfe57df7741b1ca61b2b53ae34a1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_tracer.res
  hashes:
    binhash: 012834edeba97477da48127983ddcf6d
    md5: ee73b78a40d95fdcf46c226d050e9fdb
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dd40dcc043885b8ef1ff221c23759673
    md5: 8fdf7a7a462a6baee27b02494baaf174
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d68280412b82382aa26a6ec25e8eac5c
    md5: 2bd03e391ed528292b687689c7253a1c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 64c179896e5d2ddacc2efbcee829a9fb
    md5: a10700859273c12899cf17b60063122a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart026/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1e5aeff90c81f831075c6f2069b49abc
    md5: 3338ec0c7ce2addc3c472c0c2443e09c
