format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/atmosphere/restart_dump.astart
  hashes:
    binhash: 75d97883041ebb594b0fbaf943178806
    md5: 9e03b307129fc9d02c0a029aa411ee12
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/atmosphere/um.res.yaml
  hashes:
    binhash: 7d0478f349bfbb44cad9e66a97906eb8
    md5: 72b0f8978ceabdeb25eef09dc329d6bf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/coupler/a2i.nc
  hashes:
    binhash: ae5a56faa96f04039d6de830ae5c46aa
    md5: 09aa6c5a45d867c9ce7aee7388d7d0ff
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/coupler/i2a.nc
  hashes:
    binhash: e2349b0d596c286146e0cd9f1e745d46
    md5: 4457878ee2fd6d9ab06199cd8822ef72
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/coupler/o2i.nc
  hashes:
    binhash: 196c81ad2e3aa6ec96154894be416bec
    md5: 8a72ea7a68f6a3a74fcd38a1f2771a75
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ice/cice_in.nml
  hashes:
    binhash: 091d5b0f209963d7a6bf32841e3a5858
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ice/ice.restart_file
  hashes:
    binhash: 0924106a49f6df97d3466e0bfd926231
    md5: 005f2c2bf7e4519f6fe39942d08967cc
work/ice/RESTART/iced.2870-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ice/iced.2870-01-01-00000.nc
  hashes:
    binhash: 473ecf9978f6798adda09d626519bfbb
    md5: da3d758aaa21f5dda8956b4270a3de3a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ice/mice.nc
  hashes:
    binhash: f7949e283e23be33d26061d12a88c2fb
    md5: f596504f03a3bd38a1d71747a567fe14
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_age.res.nc
  hashes:
    binhash: 54fa9790fb89b565cac799e6956b786d
    md5: 2a5ee25912a838ac8bec5cd9fae50614
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d3344356054f1d88d0b22a78cb71a5d3
    md5: 6363c8f1f169f3b48ffd8a5d35287e0b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: baae34c3203f3b9ca256ffb916027b98
    md5: 9d98227ac971115ca3668d53b0e8a55f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_density.res.nc
  hashes:
    binhash: 704f95f3b58b9df0cb47d230c910fd17
    md5: 9b6488ea74cb1487c486071389f17f25
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8e5ae079ed6f131030f7e226159f6d09
    md5: 44543b5cb6f58e6ec218c45cb0bd54b5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ec3e7fe513c4e2a6f9709c29bc5c487d
    md5: b8048082dd74dfc7ccb1d71934539b9d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1274c445360167507d1f896c82414e29
    md5: 47b8ef5f88b230267f01babdee5b57aa
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e0ae1e98bf06fe178ab560360c25697a
    md5: eedededa582722473ceb1c6ba6cfa81e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f9874f2895332b242705296437dc04fe
    md5: f2721688b1c53429f8a2f507b1c0cda8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8b4ecaa8697759e3cd1cd6e96df65892
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_solo.res
  hashes:
    binhash: 3225d741f8b4b08888c0b4544bfd2fe7
    md5: a605dbb5a3b72f732a14c4af33a99c10
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cbe90df27edccfffff59a1c27dfca599
    md5: e01fee11a7745e368df08ae0fbca78ee
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a673085d01d55aa13a7fba01d2527155
    md5: dd50bcfdeb90c7db49498408848950b3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_tracer.res
  hashes:
    binhash: 1e05758f90169d30e18a8badab0c77cb
    md5: 77f1a896bbcf928045e06a05140db080
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d1a705c5d083186f35430e91e50a3228
    md5: 1f4dc1a2ba1fbe7b45e10c57f87daa03
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c3e6428d887647a97ec891702b33995c
    md5: 2c8010ae7913818b08fe7c5f4c105494
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6bf3dbf44dda1277d05882eb2d2cda68
    md5: 9f0c3779322765c4c2efa2e8ba1c4ded
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart193/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 271fd153ff0ad1c563708e6f7822e5df
    md5: 4ea4175b0527188c58332e54b9c744d4
