format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/atmosphere/restart_dump.astart
  hashes:
    binhash: a26c3a0f308745a783055ad1b1f5fd1d
    md5: 3af98723e73c22dc3ae1a285852db6d5
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/atmosphere/um.res.yaml
  hashes:
    binhash: 7a476ff8ce4c8f5903cd5d2c2f40e0aa
    md5: 3799476c44ad810f06ee248dd8d58889
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/coupler/a2i.nc
  hashes:
    binhash: d66e112255bc4efafcf041d54a00983f
    md5: b3839596b889724e0f74249bfcbb2bbb
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/coupler/i2a.nc
  hashes:
    binhash: cd111b10f6906f0cc39ac1d0b4696767
    md5: 3ef44fab3b084a45e9b3e5d6c3ea864d
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/coupler/o2i.nc
  hashes:
    binhash: 728bf711cfbeca2a7d9f91bfb2204df8
    md5: 9cc309c53725980fb8ceea8c3beb578f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ice/cice_in.nml
  hashes:
    binhash: 8da0b6a883e32576b46d97e9c7e7c71d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ice/ice.restart_file
  hashes:
    binhash: 3f51b2b1ac4dd1e3bcb5228f39d6ec56
    md5: 422d27f3e0e57a911d0460ca51a34307
work/ice/RESTART/iced.2145-01-01-00000.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ice/iced.2145-01-01-00000.nc
  hashes:
    binhash: d024b148b2ea6466b69079765999e3a0
    md5: 9b38a443da662dfef1ce950042dd98ed
work/ice/RESTART/iced.2145-01-01-00000.nc.back:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ice/iced.2145-01-01-00000.nc.back
  hashes:
    binhash: 74dfa7b96c189abb86190bbd0369bb49
    md5: b9b59b71f031ac1538ab5a763c5c7589
work/ice/RESTART/iced.2145-01-01-00000.nc.back2:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ice/iced.2145-01-01-00000.nc.back2
  hashes:
    binhash: 5c5a1df367601e71ec9387ee6129a061
    md5: 30aa4c9195a2354304eff8409933902a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ice/mice.nc
  hashes:
    binhash: be4c0f03e0e1234c6035a991ae3f8ea0
    md5: b0f77b9c94aadc78ad29846129c068cf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_age.res.nc
  hashes:
    binhash: a8482e425fb46c9f822b2fc1f6491c7e
    md5: 8ea6938953bde98add4f0396b3aa4d7f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0abf5a9dda403d28cd8ccae67c43a456
    md5: 1bbc9c7b26a763824600d343721284ca
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ddbd57633db3cc8357593acf582441a5
    md5: d3319b42b15770e6e496bf876c56c3a9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_density.res.nc
  hashes:
    binhash: f8199c803278ef7d13b9322c86cadae0
    md5: b9721a24f0ea54e6148149b6fd8c49ca
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7548e0d0f49fcdd4ca1012ba814d4bd4
    md5: 9c74f9b91e446eae36647e1532b5c1e1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8b069fed44cd519461823a2a37454e9a
    md5: dedf6f50c59997f3d1a4dfa91e09141e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a4388d9e7199a1639e8645132cf93f2a
    md5: 5b83d74deb91b28687ab17591ab8ec7a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a3f7ca18433eeca7e773f928f6b2ae51
    md5: 778294e24b94dd3de9c3c4c7ddc4ae1c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 547fa6a86f8749bb622c380745f260a3
    md5: 3cee186611b12bd55fd6df5d8705bbaf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9429f4921d9fdec4f5092e5c0e8503cb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_solo.res
  hashes:
    binhash: dddbcacd472598d9726b541bc6005aea
    md5: fc8621b51090a6b219066eae79806042
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c4141373f67396a4e4486355765eadbc
    md5: f94e61d860b97c1110da9ab9465b86dc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1da62224f1f42f493da6c6ecf932f118
    md5: 27cc724aaaa0746715b60f8287bb7be3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_tracer.res
  hashes:
    binhash: f53ef7197b22ca2e5db243c4197e0ddc
    md5: 89366655c8e44c73707bb79d7f6bcf6b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_velocity.res.nc
  hashes:
    binhash: cb6b222d7fafa33eb5f5dd569e6934bd
    md5: 84daa2d28d4f4d0bb23323e873e20d48
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fb05dd725e5ac42ce4cc9278d11aa37a
    md5: 701abc0960bb26c8d7df8d9ca6bb73d8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 909c48569e33562ca7dac04c52c17e11
    md5: 292c7d2fe3f7dbd632d4b88c13094c1c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.19/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 17d8979cbd4df38d68f6aa7da0f0a1e3
    md5: 2ef19c2a89987d615a629b6ade6179e2
