format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/atmosphere/restart_dump.astart
  hashes:
    binhash: 8e0424b2833da1635daaf450d04c646c
    md5: ed377dd5991b17ab0cad9e53ff969e26
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/atmosphere/um.res.yaml
  hashes:
    binhash: 89de1efb934d7cdc11252f9428a7844c
    md5: 3a56e91b4a54044a4e1a04c71237ebf5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/coupler/a2i.nc
  hashes:
    binhash: fde9aa1dbb162fbba6d03aae2ca443b6
    md5: 5ec0d1be94c3fa08a8772603bc641343
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/coupler/i2a.nc
  hashes:
    binhash: 4af78c6352b1f97900881f2b895c1238
    md5: af74773bd00b9d507e415de6136505e0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/coupler/o2i.nc
  hashes:
    binhash: 94fd1aebdaa005c1426cfb84c5b0b40b
    md5: 2a3a89e33e13699ac6cde69ee2a2f6ca
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ice/cice_in.nml
  hashes:
    binhash: 9553993de6224cc31768421cf5c940eb
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ice/ice.restart_file
  hashes:
    binhash: a3ac448e397f63ac5cfbf5e83c41f5dc
    md5: ab637e23b34ab152a011710d8375c1d0
work/ice/RESTART/iced.2791-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ice/iced.2791-01-01-00000.nc
  hashes:
    binhash: aca531ce3d7808682a5477603d4a01da
    md5: 9f661487b80b1b9e1f2a6a7d8532032a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ice/mice.nc
  hashes:
    binhash: 87bff01ecf9633c44fb57e3ae3ca2d1c
    md5: 9023c83280fdfaf58da094f4d8db891d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_age.res.nc
  hashes:
    binhash: dc2e525845816012673046ed81467481
    md5: 8b2c0cfcbbcd6f7a72cf70e894066e95
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 96b7ff5f8731646c846aedcff38bf921
    md5: 926b4c1fc41ce4167a82ed23cf99726d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 60197e4a798908ca157b1edcdd529fb1
    md5: 4957e31f5e40d212635162dc872b3778
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_density.res.nc
  hashes:
    binhash: c87ff6f32a3177e5f4280544fa373165
    md5: 7d52952ee734444b4f28004f4f9811f1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ed0153761802ee9e7ee32a8dc7e6eacc
    md5: 5fcdf703b22df6fdf48f4fc1d4b6f202
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d1e4e3aaaef6a5e136c9c2c1b6e6ce55
    md5: 4741ae93723ea51a4abd5e9e75f64ebe
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 30a3291185cea12b74211d2a03f80e0a
    md5: 54ac582dfb2dfb85b95b986d8db32d41
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a2a894e747d2faa1ca498d06dd0426a8
    md5: 62a4f17d12c899c642f30692702b8496
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3b88fd36dffdbc1a4e5897a8c64a64b7
    md5: 21ec1f0f672a1e62dfabe0eb7c4d1fa5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 67950ec76e5c4c8667ee5c8302d42eba
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_solo.res
  hashes:
    binhash: 249dc49a3175d1f46322c425c093e4ff
    md5: 4d1906d45572faa6dbfc24857e2e6c39
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2bfda2b360e4690de90eb76f4c9464c2
    md5: ab8b4ddc1a72276198ce7efa34bee37c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_thickness.res.nc
  hashes:
    binhash: afd47f5bd8736667e94fc75e353f9d58
    md5: da786eaf38c1ebf84f126901a2913013
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_tracer.res
  hashes:
    binhash: 23b79736a33bf43bc046e962eece839f
    md5: 7adcd196f93076a5e741650e6cd124d4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e232f82a5b0665d6099ccf9b028c7987
    md5: 6b66e76e2aa2afee0f1b9262bdb4d05b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2fd5efd0a408e83f5c5cea3a458d40cb
    md5: 1cf423141ef356176f83cb9c43b88d52
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d603fa261cba4f1959ce7f7719389ca0
    md5: eaad1d913bcbcfa7fc1e6af526113856
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart114/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 22ce11d0dfaed64a8ebaf2824b735c09
    md5: 21889e4bc3cec47001523932b4c05003
