format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/atmosphere/restart_dump.astart
  hashes:
    binhash: eafb1387d9529a86e887c6e59b30722d
    md5: 15f46ab9fdf84cb2fa4fa7d1ccc1ca8e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/atmosphere/um.res.yaml
  hashes:
    binhash: 2c503ddae199393509676a95bedddc2c
    md5: 5e472fba1d6566af239d4229cefbb9b3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/coupler/a2i.nc
  hashes:
    binhash: 547bc49bb56cd311329ea86de2438b8c
    md5: e24c00c545b5d990306e374b35072953
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/coupler/i2a.nc
  hashes:
    binhash: 4420a864eeddd6ef87bee20b04ae5428
    md5: 09cbf864494e8db848195dada25b19cd
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/coupler/o2i.nc
  hashes:
    binhash: 9b465f979d0bdecf5c2b5fa9e5ae2517
    md5: 399ef2f58d5a0bb0df18672c083364c2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ice/cice_in.nml
  hashes:
    binhash: deb09313b297213b5450c60e487a70ab
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ice/ice.restart_file
  hashes:
    binhash: ca0c1dcae0ab69e5e6de767dc7601837
    md5: 1d3e1b22142a3802f4c21022f5bd2d11
work/ice/RESTART/iced.2778-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ice/iced.2778-01-01-00000.nc
  hashes:
    binhash: 399bf0ca2195c3279b80d17286358548
    md5: 5dd5a63409e55296117b18db06582dd2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ice/mice.nc
  hashes:
    binhash: 785dc83f2a71adbf026adacd60dc03ef
    md5: 855bebae31f72af2869551c62c20ed45
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_age.res.nc
  hashes:
    binhash: 6fd1a84f249fbcb86cadb66b265c10a7
    md5: f42e88a3375ac5aba211e34bc757b262
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 843f4a7539ae0d76b38f1591f9fa7930
    md5: 78124c26e29b4759836dde62c2b62a2a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fe5fad5a680bdae8d68661e836371ff4
    md5: edd9e3c53287bac4d879bfcc48e6114e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_density.res.nc
  hashes:
    binhash: 590829442a38f9b07febab117664c234
    md5: cb21c9e1b50a372a56b087ab4baaadb3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fd94da3f78b361df6a53eaed471a47f5
    md5: d94bc65bf0201fa70d6b2df03eeedd35
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 975c92c1ec9d9819cc1715472459cb04
    md5: 43b1e34a5d71f9ef51dcab5b59e77b62
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 61f72b7d90d9d34be22badace7054fc3
    md5: 21c58e57db2ec3a68284799fe7b2453a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 312c67a15a6d9735f04a52b351237b00
    md5: d0f01faede5dedb7a68eacf3f5e3e98e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4416b96878a9a56e13b15bdb5fa720cf
    md5: 24794b2d41cc29d848a78fc31e51d816
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3f4ac5ffe6d5275afe92768db22c5c31
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_solo.res
  hashes:
    binhash: dab4aeb8f5b52a9080428cc560e9413c
    md5: 8f3666f025434e1db67210fe2a4f9bed
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8d0566551b19b9fb91a7e4a84e44a571
    md5: 4a05e5e3c6fbc7a037f5f4f33dc3586e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 930c7fcdb207690d73a1997d894ea0cc
    md5: d5dc619f00b998bf76492a5851e93054
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_tracer.res
  hashes:
    binhash: a94e5955441aa18d87d916025241c908
    md5: a07d18208d95d1d0ae657e1a0c1babfa
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 20ef643f61b95831703b8f817297db91
    md5: d3a95fb7f082136ba39e31173212c2ad
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d0e77d46ffc0f77dcd588cc2128def8e
    md5: 93d364be0c925b088536855a25eaab6e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f7d926a8e81797d6c35ffbb625c9b762
    md5: 977b3d995bd32ebb37d4e95b6182c819
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart101/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e02271a93f6e0753bc43e8802596407b
    md5: c7291cc9818e03d205cabf786af9d194
