format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/atmosphere/restart_dump.astart
  hashes:
    binhash: bda3e0cad5fca13cb6ffd6b203cfd2fd
    md5: 1211b49b65fe4931a94282cef587649b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/atmosphere/um.res.yaml
  hashes:
    binhash: cfbe6eebb9c6686c837fe2898c0a4d7c
    md5: 83269855ae54a5d07349ec8c93ae5615
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/coupler/a2i.nc
  hashes:
    binhash: 92bb76f313caee59507e1b2dbd6a49d8
    md5: 9492598d5b2a4e8502cde392f92de4d1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/coupler/i2a.nc
  hashes:
    binhash: c77a4532d60567713da8f5c789125d0f
    md5: bd7166abe2879061b32efa354403121e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/coupler/o2i.nc
  hashes:
    binhash: c1a7c85f68da0133a69df523231fc4de
    md5: e62b99ddd0192c326d92c45d7b0887c1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ice/cice_in.nml
  hashes:
    binhash: 3634e227f71fd3b7f8ecfcf7b99dc3e6
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ice/ice.restart_file
  hashes:
    binhash: f9d6663e32dbf484111c4d22ce789528
    md5: a0456440efa1d6740df03de00d1fa3d0
work/ice/RESTART/iced.2780-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ice/iced.2780-01-01-00000.nc
  hashes:
    binhash: 4f57384b4b84893f1b56013ce634c07c
    md5: 121c7e195b4a73ec7fa7df597e54027e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ice/mice.nc
  hashes:
    binhash: e0de440075f050ecf140b33c7d8ab73f
    md5: 893f0ac54e83196d0e405bcb2805dcc9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_age.res.nc
  hashes:
    binhash: cb15e5a009205ef815f91cf4398923f8
    md5: 938c26c6fa945098b7360153f98e1af0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5085e300916d90705250ed0a12133f45
    md5: 125fee6a4da5b9cb80aea5206c3f21a6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 75d5747c5e7e5f33e8a9c02ea300fc36
    md5: 6636563e05743f27d6097307b8a4c036
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_density.res.nc
  hashes:
    binhash: 95ce08ef01cd135ef2f3d76f75728e97
    md5: 32a790ebe483f482b96803c98337d3d7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9ed72ac017edbd2b3a2c2b9ee40c15a0
    md5: 3f8745d67f543a37cad95e5951fd65fd
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: fd0c642fbfc999341617f50bd1bc2c84
    md5: 34fb4af83d61d15c21178d8a6ccbc50d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 254cfab9dedc70db375506d3f2bb0773
    md5: c7c190c85be67c1496ff575ae921a349
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ee2eb59dad093edee2c47a32a0a8dc5a
    md5: cc2129b620a54c5f19a8760ac5d057ce
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bf6141b345c0b9e5edb1cfe1da67fce4
    md5: a16d11ebad1eb7df35ee71cda0fd8603
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6c89c1c8da0c744c9c486f6b761d746f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_solo.res
  hashes:
    binhash: 169bd7d02c7f05f4ffd9f795a2ca416b
    md5: c9736961f3653138ae7550198caa556f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 23b5d51d2b4425475a35feab5081284e
    md5: 5e5fb46b098b1e2f904b71bb0ad3faab
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0fc88e3547186db7d57e5593d0381330
    md5: 44e39a949a50ab8e9d5846504293c6ae
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_tracer.res
  hashes:
    binhash: 567a79352d4bc64c1f0ae9aaf8fdee84
    md5: 9decaccb5804c7a43a4f7418f2235216
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4cde929b411b7f2be7814d89c8d036f8
    md5: 799ee3c4cd40fc07511f915af7e18e5a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6aa8e233d3da5de407cb3775241bdfd8
    md5: faad3a65242939fe302fe543053b2406
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 31325543ff83916b9e01803403f05c66
    md5: 6be8422b50278b7bb7f60da927a410d5
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart103/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 93438de1aa01c8db1fd12238f8e2d35a
    md5: 729559ed2af0eb36b0523f7f0f6e686c
