format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/atmosphere/restart_dump.astart
  hashes:
    binhash: e760dc2c80ea837a17ef27c30581bffc
    md5: 9d94f3ed45ec0f47bad75d463035fffe
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/atmosphere/um.res.yaml
  hashes:
    binhash: d8822dc80372ce7e34042a394d92dfd1
    md5: 5aebdf911c1535ac5098fd23505f6b36
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/coupler/a2i.nc
  hashes:
    binhash: 4f37085ef9593e1cdd60f08fc26dbac6
    md5: 3951526361ba0fdcb5be408cd1208b50
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/coupler/i2a.nc
  hashes:
    binhash: 9e5e8d3aeeef8897ea2c48abd69cdc7c
    md5: 279372eaf9e4948e2523fe4275691d5b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/coupler/o2i.nc
  hashes:
    binhash: cc9cb3083978d3754c8590d586eb4596
    md5: 29f49cc1a16d29d5f3a871d009fe3a5b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ice/cice_in.nml
  hashes:
    binhash: fd4d47b659936174b80ae6f874c4a2b0
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ice/ice.restart_file
  hashes:
    binhash: dc483711917033b836bb61272e15b9b5
    md5: aa7b98c49fe9ed9a3ea1be391ef55d0b
work/ice/RESTART/iced.2789-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ice/iced.2789-01-01-00000.nc
  hashes:
    binhash: cd4cc5f66683467c196e1b5f1a746051
    md5: dec9679d75fa766adf011882305ab745
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ice/mice.nc
  hashes:
    binhash: 7ba189dad60508a60866b8fb777a3b43
    md5: 258eac8fd894242a39dc79f2f0330b63
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_age.res.nc
  hashes:
    binhash: 01629ea5332b6674384593bd121c111e
    md5: b352f943ce4a8e112b10325e656e352a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0aece17489d834f5100e286f2f84cdcd
    md5: 8965e7db8b4605204fd30c0c9e57f7a1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ba099fb60cc37c54b68270a3227ee675
    md5: ed76e3cc52c2dd1896487963cf88c894
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_density.res.nc
  hashes:
    binhash: 9b265494d55cc5c303cf0351db8c4e56
    md5: 5562b7acdfd007f7280fc9c8b1284dd2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 73a8ed1e261bf0f7e34b50c696ec737f
    md5: ddd15224a7b2fccbab66c5d0310b2f37
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4a7c6891b2eeca4369c6541eeca2441a
    md5: 7012fd0bb1b8be4f9bcd64b8b76236a1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 230fdc4302480eb286b262cb2ad73ec4
    md5: dd8368e2108227d51091a86677c5e385
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d23b920db723b6b711e3e65c387de268
    md5: bad9935cd5dda928b4afcfc6db42c75a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f254a8609c318d236a60ad177f8d2bfc
    md5: 8a1715daeda4c92b3b5623149e92dc45
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: dd161a462c68c6f2ae2cd50d4e3c5037
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_solo.res
  hashes:
    binhash: 7565366b0e83b97eb798546a98572ff6
    md5: c5c59a545d3ce86a234b6b21d1b047a6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6f3db8b3a832d2553ce0682ab3760fa3
    md5: 6d69305deb08440c95dcb3bc9c6db834
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d1da0e0337fbae6e5b82abb28c02f9b4
    md5: 17830ac8a2026706f3899c1b7710d288
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_tracer.res
  hashes:
    binhash: 6ef3cd4b9f436b1d379a5deba82e919f
    md5: d58b535b9e9495536288de02d3042fd6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 40e91c65f467096f0a1f94fc339da559
    md5: 269c6cc53f6323d063388fc3d106b5f4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6b70868d4b32c9d5dd904d621f5270be
    md5: 3bb7b73b3de2da7a7a8517b924261d9d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 49a7dc896e0117e5db5cc76d8cb1e428
    md5: d8ed38cccbaec473db3d341b0467495a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart112/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c87296810ad80f406e9a737e15db2b1d
    md5: f42fba7796c873b646f4de7f8be93bdc
