format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/atmosphere/restart_dump.astart
  hashes:
    binhash: 3e9223d31bc7c1461cc2bc5a35a6b44e
    md5: d9216c98346bff859d1103586da3d1ea
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/atmosphere/um.res.yaml
  hashes:
    binhash: 950e5a82434dc36ede9911e1447723fb
    md5: 684d148b07d448060e284de20c1d88e5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/coupler/a2i.nc
  hashes:
    binhash: fccfcd5fbcf2be2facb3bb02a05b58bb
    md5: 3df2200f8d6140149a882167e5099d83
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/coupler/i2a.nc
  hashes:
    binhash: 796987d1490b94b7279b884aa00b8c12
    md5: d2caa82465dfa0315eea488090af4184
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/coupler/o2i.nc
  hashes:
    binhash: 5b7dac826bde37bb3df2ee3eef584eb2
    md5: d19b64928308dc922a81fae7b59913ea
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ice/cice_in.nml
  hashes:
    binhash: b7373326a74ffbab593bf9c79df5710e
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ice/ice.restart_file
  hashes:
    binhash: 670d36ce62df87a6bf22b3ae690039ee
    md5: 0802bf0f4161a30bd0277e2b4adc4262
work/ice/RESTART/iced.2700-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ice/iced.2700-01-01-00000.nc
  hashes:
    binhash: 83abe50ff5ffc0e900652b758ab4f552
    md5: dd10019334721d72550c8d75806e945b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ice/mice.nc
  hashes:
    binhash: 2d7329cd607c0c561342d51b4f361dd5
    md5: 331e0381538c4f4fcccd53c8b2f518b1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_age.res.nc
  hashes:
    binhash: db46790bd810ba3bf3f4a237b1b6eb2e
    md5: bdaec770f74c2ad4435f5382de8af74a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 84cd6981623aeb232b84215e1c78b09d
    md5: a4b112350f8d47a93a2a48b79e2dbfd5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5148c975904414fe0c42adc70d65edc0
    md5: e033b4b04bbdf0d9c4fd796fe30fd120
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_density.res.nc
  hashes:
    binhash: a557764abc17022dfe3ec087be5cce04
    md5: 9d034a54db8fd6d7771d99ee4000ce25
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e783767b95b871f3409e89b5fe8383f5
    md5: cd8220d6d2e2b3cfa1dee53122383e3b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: afd520a246310746f10e77082bc81ef3
    md5: c78fb9b2214bb1ef1398f149fda01996
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 50901ca3ba99b756c89f055dc19c9f00
    md5: ef85c0971b5fd5e0ed31b5f8dde0405e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 01bb200fa24b5583cab8c9d134083f34
    md5: 6a3abf2a5e2c2e91820173abb70a6c57
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4cca7cb6b03825cbc92be8205a19062e
    md5: c31e713a176e96fa30f7b3d11e26002e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7492f34f3ceabfd360b2b7cd202ea1fa
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_solo.res
  hashes:
    binhash: d33a8ec310ec50b9edd7d44a3bf63b09
    md5: 0a4563a3f76fcd45e75f06879a717b2c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 109dddc8974ea65d7547d06c81a6e44e
    md5: e0b80c1ab9e65fd57066f28f9b62b63a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 65a225760bc563cc53b51078a3eb52f3
    md5: 19529508f64e85655696a16a4fa6d832
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_tracer.res
  hashes:
    binhash: 4771646562dad98bfb6a220f3f29b399
    md5: 5a3f224199e3ae1260dc2b44277ad88e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c13cd3953e9cdefd988b6efda4dde9ea
    md5: bf690ff586f39336152fcbacf631e97c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 93980235bf658788a376101fea7299ea
    md5: 4a0a7b36d49f5d65a36cc17f6ffb8a9b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0c26392d79f15ddb95f228db2a4c306f
    md5: afee7bc81abb4d73f41b255a93d053ff
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart023/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8fb290e8a790bfd7276ac3f0078193f9
    md5: 70db4155997c01c038fe9db5a4df66c8
