format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/atmosphere/restart_dump.astart
  hashes:
    binhash: 1439aa2456c10f391c50e0b54fc3ee18
    md5: d0abeeb5d62ec049b06b27560628615d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/atmosphere/um.res.yaml
  hashes:
    binhash: f62b4dc22ec1add1eb75c7fc0ab3eafe
    md5: dfe8bb2672458587d3ad5d1b6c091ee1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/coupler/a2i.nc
  hashes:
    binhash: 4ac5223ca6db7440dca2c7b61176a114
    md5: 7926ab6af18914e36c3303a12f1ddba4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/coupler/i2a.nc
  hashes:
    binhash: 9cc9d102d60940ab9ded49f52ed91e85
    md5: ebec3d8835863a3556ddd37a8bde43ca
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/coupler/o2i.nc
  hashes:
    binhash: f76e49debfa9464d76669bc43d883233
    md5: 67ce19bebe00c237eff7514027f582a4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ice/cice_in.nml
  hashes:
    binhash: 13c8de2dc20c09ef2fbe1493b005a40b
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ice/ice.restart_file
  hashes:
    binhash: 0201d6780c693b6c76b81540744cc6e8
    md5: cc4d935da876b01b0d350bb374f73a25
work/ice/RESTART/iced.2713-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ice/iced.2713-01-01-00000.nc
  hashes:
    binhash: 2b088c883a57e9d16803eebb99d1501d
    md5: 7b0d4d055801d8b4b7497b9fd6676f3b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ice/mice.nc
  hashes:
    binhash: e820640cf127a6e8d28b9cd5050e562f
    md5: 0ac80f36dc2710a9cfcf7fc34bed0500
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_age.res.nc
  hashes:
    binhash: db8147d4fcc77b1126eaeb14534073ba
    md5: 7778fe1aa005b1b068cb75ceca3ea42d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 074fcc24381fe59269576cdfcae6d8e7
    md5: 268fd0a108cbd1db22aa1f8464d1d0fd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f4fa4af37625f4b29f7e0301645f91f4
    md5: b8e6675e634b0bf0c9d0ba9e3a90132a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_density.res.nc
  hashes:
    binhash: 8ec3a6e356a8a7ed0bafc86eee81c82c
    md5: bf50178b9ca4d9ed2d765c12f3691ee3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e647d3d72d890e93989fc952b0d9b26f
    md5: c17918248ec84b59666c9d09dbce770a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 01b98818aa1468b1a1f5eadd9322487a
    md5: c31f95c79af5bba089e1d29a1c0defdf
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f0cc8f253a0443fbc4e24d5f86366c79
    md5: 14d78bd4b9de3163a8f83b9d8a83ed75
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 71968cec6f173592e5dbce56937e5298
    md5: b7fc5ce08be3a4bb7d5090d0e119d77b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 44dc65ee822aa3e52e7d72e88abcd6fa
    md5: 22315457e25df32005656521ece0177a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e4b7630fd523f27cb13424a699bbaf2a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_solo.res
  hashes:
    binhash: b1f9cd2e9da99f17f60a5f4569144585
    md5: 2b4ed5689da79d5a97affb2535b79214
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 407b10e13cd85e1fbbfeee456464294f
    md5: a8477b0b5db1f7918f8d2135f2171112
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f4d2bf93140f9c4a401fcfb6eeea238c
    md5: 5676803dd31a0804fe1170dd57fbfcc5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_tracer.res
  hashes:
    binhash: 2cba884304c300ab588853a3b808db31
    md5: b322404927e38dff5af3137ac33e5653
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9ad26800a553b1e6cf2d5592a09e9540
    md5: aaa75d97c1b6ba601ea39ead6621f0fe
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3a7bb547d6633cffc4709b1c9e81d145
    md5: 2b9d2682f372a35daf9ef97f76e3c054
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 060b5eb5f6a7b230cc9bdb169efc6bb1
    md5: 0cec8b188da506473507f3b35013d8fa
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart036/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ee6dccdb747748568801f40fb72546d0
    md5: 3c4968ce65e029422314360c99f5e57c
