format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/atmosphere/restart_dump.astart
  hashes:
    binhash: 72fea233891264792ac933ca23f78072
    md5: 82ab171d89d9b214d1a645a9f077851a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/atmosphere/um.res.yaml
  hashes:
    binhash: 359d359fbab4a28f61361df0635a3d1c
    md5: a1971b442192ce4357e76eda3d184c98
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/coupler/a2i.nc
  hashes:
    binhash: 2feed5e53959e36a495f3414146386f8
    md5: 95b07dafa3fa6aae96fe75baab4c1ef5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/coupler/i2a.nc
  hashes:
    binhash: e6e2f7db82223ca498eed0a7cd94a7ff
    md5: d89074ff09b9879d2b38476e112f4ce4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/coupler/o2i.nc
  hashes:
    binhash: cf7f2d5de5ec067add93b143b92ada94
    md5: a973537ad730455b543ad82bd64fbdfd
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ice/cice_in.nml
  hashes:
    binhash: f567c8dfd4922d898e6632cf5f719dbb
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ice/ice.restart_file
  hashes:
    binhash: 7a3f0ed8f6a7156a10bf945db798c6a6
    md5: 5f56e2d87fdf05e11ab1df449e923f10
work/ice/RESTART/iced.2933-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ice/iced.2933-01-01-00000.nc
  hashes:
    binhash: 8a4b6497f256a78b886c160dbdaf8f9f
    md5: 28827ac7bbeed15dad2c6cbb6e7aec95
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ice/mice.nc
  hashes:
    binhash: 3f2437c0a8216bada102098a48b7fbf2
    md5: 69193a5c87ceff1e133f70a76826af0e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_age.res.nc
  hashes:
    binhash: 16fb6998f52add8c366d5bc035281b2d
    md5: aecbdac8baf6f26b19fd6350cc5f649f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 71eae75b96e8d38416fcbad1a429c7ef
    md5: 499c92d3265be40e463be3eecd2a8e8f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7dcbf935259a716d47131cb36368fd1a
    md5: 08f3557362253628465c16e838f9a206
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_density.res.nc
  hashes:
    binhash: 23449af2080b1e4175eb004f19ec753a
    md5: dd2a7341509566a8fe76c4a3db4b922c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c960cf45fd5d5832b18a9e057f1250d9
    md5: 54241a050b142af8ce1d51af10d72709
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 997f24909279ae1f7183093a9a7ec0b1
    md5: 8110ccf35676dc13b0c8ea849b2c00b0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 01c718fb8ea08fe011846f0c4563a961
    md5: e73bfb9bafc7ae7abde9c906a215ebee
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 872e510f26b90caabc0a18bad4cdcfb3
    md5: 7899e40ea9ccc36925c68b5ee5f9e5c9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1fc3d14ff61f22e6a7023b23e18ff541
    md5: 0f2a3f23e8ec74987f7de23977bc0dbd
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 56a4ad29878c0012fadce376459fa38e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_solo.res
  hashes:
    binhash: 63e543fb9ba1c1579afbaf532bd52c4f
    md5: f38b6ec4400d63a5f16f5688a0856ae4
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f8996bbe8b72cb21c999d77c0a7c0acd
    md5: 7129cae8538a7f29a206967f982acccb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9e6a5558fc990ac42647ac51723b141f
    md5: 22d3a8f302fb25669eb0c901f7de9ef8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_tracer.res
  hashes:
    binhash: 49a6ac2fe5c5af92e261c059fa24e628
    md5: d2acb9cccdce70f5b2701b770a2ee6d6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 97556d901bcef578ab88863fbbff431c
    md5: b75402dc8e9fab24a24611fc929ddf29
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 74597461f865a0e43d8481dffe34ce5c
    md5: 4f9148a98d500cb1d271ecb0d91da0ea
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8b48f306dc571828fcb4d09783db004e
    md5: 7ce42ee41ddc1ba64968554f74f9d383
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart256/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2515dc5ae26a4b04696e71d16b45e1ba
    md5: 40f317833e425a0c08d93033f6d20941
