format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/atmosphere/restart_dump.astart
  hashes:
    binhash: 984370e3d76a49b8f288ea242e9773b6
    md5: 715c8dcb3a3eb80ddcc880771c28f0cd
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/atmosphere/um.res.yaml
  hashes:
    binhash: cb06aa16fa335a8ac68ac8c96d1d7fd2
    md5: b421afe36dda532d6bc3fd456e1291fe
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/coupler/a2i.nc
  hashes:
    binhash: e9ce5f99869f7d5931200cfbb450ce63
    md5: a6bd16d52e522efd835f5f48a04b0003
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/coupler/i2a.nc
  hashes:
    binhash: 1b89fe6ba5034227312a3a6316bc2082
    md5: 419fdd2f150939269bbdf934e74a2846
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/coupler/o2i.nc
  hashes:
    binhash: 6a0df26793f43c6814b53691f1baaac8
    md5: 357410ba5842aaa154c3d77566d7d490
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ice/cice_in.nml
  hashes:
    binhash: eef22feb943562c19b88e8451081cd2e
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ice/ice.restart_file
  hashes:
    binhash: 532af2981ff98acf55add063e522b422
    md5: cd13297ed42211b422a955a417c5445e
work/ice/RESTART/iced.2759-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ice/iced.2759-01-01-00000.nc
  hashes:
    binhash: ec761f61cc8e2b6be4ce6899eca91821
    md5: 338547f485f8628f8dca2a0439f1b818
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ice/mice.nc
  hashes:
    binhash: 782236a86c506e77aa715d5cdfcc23bb
    md5: 0c50c170e4535966ffbd75c044c86f44
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_age.res.nc
  hashes:
    binhash: 1b041f4798d624f06fb5632195b802c4
    md5: 13f1323babaf843476bb4ca268527db0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 37712faf65437c5f3e7f304495c351b3
    md5: 9e74a9fa5745c8580a847bae9709f211
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 33772597a17212f8516e82ed8d4cb399
    md5: e59d1b678f0125036f33c329936ed86d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_density.res.nc
  hashes:
    binhash: 1f20e70057c19e96e34500c0b24a2d96
    md5: ccee420cb92541eddcdb00dac9f18659
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b17b1f7c5189378f814b40afc56c62af
    md5: a05bdb839a78bb5ce1e87dc4c9bb9fad
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f3a14260f458e69f2f9eefabe0de23d8
    md5: facd38b15d51466ef1ae78991edde11d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_neutral.res.nc
  hashes:
    binhash: cd38b52995d17dad710e06ea983f385c
    md5: 7ee381bcbaf8633066ed03e63a1a1998
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 555e62bb0f7480f141626a2b8307ab3b
    md5: 2aeb907c29297cafe66bd961731f2f5f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d5533ae85f3f488b03bbf117d9733cd2
    md5: e0630b48a8fa40da673997b543851784
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d90118538a856824bd8f2e40eae707ee
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_solo.res
  hashes:
    binhash: a53d33ea009a3113ca6ab4a7c7c3d20e
    md5: 2e0449c132cf6bc54a0723a37673a8bd
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: eee4a11f3fdbc6ba6326011ea36c7165
    md5: eacea92d9754d4f74dcf312f031725ab
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4b46fb97c2388c12ae1ce838ad241ed9
    md5: a6233363921b7c6343016060ecb8b9e0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_tracer.res
  hashes:
    binhash: 3563b20577b0b7aadc08fdecf45c4dd2
    md5: 28a237201b1900cb3d4483f05fade77a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_velocity.res.nc
  hashes:
    binhash: af553638575a3ae8b2e649a0632686e5
    md5: 666b5dd7f50d7138b5a2ec45f3d2cd7a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ac9942054a2c021575d38da7653c4379
    md5: b8291e48b37507fcc8bc7f204a693b72
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: de26fe78b806a1f90b452375de843020
    md5: e0e0cf62b04505b77e87a9e5f50c42c6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart082/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f79a5083929920c1f0d66be9faf6c80a
    md5: 937517e0da98fc9da0467cfc627b4d6e
