format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/atmosphere/restart_dump.astart
  hashes:
    binhash: 3347a8164a4a0d2696291b4893a9d62d
    md5: 334857d98da1e2aaa0e5f7c9c4371c86
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/atmosphere/um.res.yaml
  hashes:
    binhash: 8bf39c8e797e26d345ccd8b063ec622d
    md5: fc54aebc9c5e79db749db308d858775f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/coupler/a2i.nc
  hashes:
    binhash: 29303e433cd524b4df64894332a1127d
    md5: 81e3115d5253010213150145a4db82cf
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/coupler/i2a.nc
  hashes:
    binhash: a87d0203645f3fe08037a4f1e5c355b5
    md5: c69eea4784378b19357e155b9ea958e4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/coupler/o2i.nc
  hashes:
    binhash: 66bee3341b7a1d60274a15d79c9a428e
    md5: 91277b9c5a80b83d356acd7c567da672
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ice/cice_in.nml
  hashes:
    binhash: 2621b84b673f00900d1455ffd35975a2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ice/ice.restart_file
  hashes:
    binhash: 622465f2acfec9f3fa59f895551b5c7c
    md5: e530a0496e406c3336da99812afbda3c
work/ice/RESTART/iced.2947-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ice/iced.2947-01-01-00000.nc
  hashes:
    binhash: 24c3e05ed1e71d2d04812658723c4042
    md5: a2fb2847849ff0c610c849058825e556
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ice/mice.nc
  hashes:
    binhash: 16257f5bc9a010850d191cf0059ea3f5
    md5: ab35903aa9e50b9221c6fefea61ff712
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_age.res.nc
  hashes:
    binhash: 3a528182ab4278b5ce392434e45adf86
    md5: da248b89347d68c358f47f50d3a40970
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4f210fb6633769b223b600313b294726
    md5: 5b78f72364b01364c24dee51f19eaa6a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c6b8b9cdb86e0d04a0278477385a1e4c
    md5: ffaad0608ac5a117fb5ca2b92ac3dec1
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_density.res.nc
  hashes:
    binhash: 179264b32752afe53fb9cbfd498603bf
    md5: ae6fcdafa6f61fbf7b374b15673e87db
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4c645c1708c15e6d1557f733fbf391df
    md5: 2f544728614b1abb3a0539216c87f94f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5cd76960d64eff4a32a30bb445d338cd
    md5: c5811143f7f8e59b184b3b370483b6a3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a57092066db350d643bae6963d15ce93
    md5: 27307fa0071ca2e558c7dc54bd4c93e7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 20861ddf75a70d0f31c7c71c73d8f271
    md5: 25a801f0809881ee37518f70e0ac8e97
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a661a4a671a74772db69c14be84a51e8
    md5: 49804f40de3f2266f6d41ef6aaab5f62
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a0cc3d9aaa6c5a8a43c5d650e2e0f699
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_solo.res
  hashes:
    binhash: d26389f1f287bd035b5bb3bbf98fa4e1
    md5: 77f7fc1519b3bc479f5a00750efd2a18
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6294898f3c712bf40d1adfca6a4de7a9
    md5: fd9a0fc1e80754f2fd1a2204ce789460
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 31a1018651cc6be338d8063376ec0db3
    md5: beb3cc4bf0d9b7054ee03bc070ed1178
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_tracer.res
  hashes:
    binhash: 14e2466a84bbe8fdca08e723aeb2a3d2
    md5: 3a91bd8f1e355385d8bc787828b59dc3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ad54463f97be6ce7dc7665d2222f2822
    md5: 059003f31ec6a80d01d95aeae88cc238
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2a7284d3dd508637c0e6271767f710e5
    md5: 46a7159db9a4f98fa2486f4a18c3a040
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d9ea2c90a634cf4db75cdf63877923a6
    md5: b3a0b8f20b1b36002ed5d2fb7c91b32d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart270/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d168c5c509965713cdedb2a7c18b7e9a
    md5: ed0187dbbce58b1faa6d7b765bef7305
