format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/atmosphere/restart_dump.astart
  hashes:
    binhash: 72da9cecb3c5e70a1613332d9b814a03
    md5: 254f4db6afa996ba87580038f13ec800
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/atmosphere/um.res.yaml
  hashes:
    binhash: d751dc7ee39d88a31dcc326abdaafcc4
    md5: 12eb37a8821706e5410e2c713843eb1b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/coupler/a2i.nc
  hashes:
    binhash: add7d547dbc9988f3d4d4d9e159b6e94
    md5: 5defb0d63912f8a959c7397bdeaf5b1a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/coupler/i2a.nc
  hashes:
    binhash: 54decafd42f3aeb4f4a11e9f2348678f
    md5: b2f4b0f99ebff1cb53baa7e74b94a62e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/coupler/o2i.nc
  hashes:
    binhash: 5566c35b51aae7147dc27c1942ae422b
    md5: 4ce01716d43b83d8c5e8f7ca4ec1e072
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ice/cice_in.nml
  hashes:
    binhash: 1af598db1c954f024973b6eadfaf3fc2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ice/ice.restart_file
  hashes:
    binhash: 7325ab05f6fa0a443a5c4a1937f4371a
    md5: e7378e878bebf3ab3b7f79a494fbc64c
work/ice/RESTART/iced.2860-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ice/iced.2860-01-01-00000.nc
  hashes:
    binhash: 00f29748f19b0304ba6b192456ca346b
    md5: e212f714758707f50d22edcf0f737c57
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ice/mice.nc
  hashes:
    binhash: 1915f64a6d5541be4e98dadf2a14f08f
    md5: b947f625f9bc3b6ad2f0712e4adac9ad
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_age.res.nc
  hashes:
    binhash: 1fc0cd0ee206ea13223d0e4071ec5e32
    md5: 7f2862d4a4cbab079ab035b62078bf65
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7788e59f9740c4500d9f9db60781a228
    md5: 1153a553007ba88288fbf8f33e2ccc03
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4146cabc9adbb0e5781d36d90c3379d8
    md5: 805cbd413df6a1a6911281c58d0b1ab8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_density.res.nc
  hashes:
    binhash: 91a61cfc9327a121cd65ff148bcd2212
    md5: 048a8932d28d4a0ef4bd7fb09f6d12b1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4ff64dae407acc7b1dd20be1916c5021
    md5: 5e5d8903c4ace5c2adc1cbf2907a5e52
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 62a3fe7171a29cfd568e509d02c2b8fe
    md5: 1b8b221e2632a52e4885f71e141afecf
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c7522fc8c8c342260300ee3a843d02d1
    md5: c505634c4fbd10dcf07ae3511e1ef30c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7278e60cbfc18ba98f37699664009a2f
    md5: c7e843ec4ab38bdaefe256d5d3844621
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0b47074b24d8831b536da91729f51c42
    md5: c2a68c5e2fe8aa7c98bca743dd2914a4
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 92990042bd4c0e4c01300babdc421bd0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_solo.res
  hashes:
    binhash: 7ac63c45d2c02edce4f4a266b7a58f00
    md5: 695bf893bf150492e5f1e2ffe14da96e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0f5298055a02500502d5c5540a4f348e
    md5: 397dc18c7e86ca533c7245b72933c271
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5db91fabda981c34367ef05b8d780183
    md5: da175288e3f2bc99c7b199ea10487911
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_tracer.res
  hashes:
    binhash: 05a87fb5a8109267da8ded3b84f3c018
    md5: a7331dc7f219191194136b1f890e207f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a88d871305e1139ae9a551a6536142b3
    md5: 2a2e820d008108b87815f741be4e2479
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fcf3247ffe69d4b33043cf57878b6e8f
    md5: 42018d6e9b1178bcec74d6d517207c12
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 370ff09603b9e6513038334b4c090df6
    md5: ea34d05a718ff5e0a69e1eab3381bca9
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart183/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9c3c72cf19b2c3e5113d14eac7505a5c
    md5: 9e1ded84fb9c0fa6b33645814a1668fe
