format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/atmosphere/restart_dump.astart
  hashes:
    binhash: 770af258bcf2bed783a0b2cd9e66fcc1
    md5: c8e21afaa847076371bf32c2bbf5d0f8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/atmosphere/um.res.yaml
  hashes:
    binhash: 0dbe8567a53a2a3a02752dc058f42676
    md5: 24f6c9dbe8ac4115acf4c24e33ad8011
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/coupler/a2i.nc
  hashes:
    binhash: a04e968dbec94abe0b9a256272b01b29
    md5: 17c8dbe58bcba8bde40662a94a282be4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/coupler/i2a.nc
  hashes:
    binhash: 6637d05e63a5eef77f212be34339fb0b
    md5: ceebf109d5b55b781ed863c77be26f39
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/coupler/o2i.nc
  hashes:
    binhash: c142d3d89b16c4dbe80fd056702404ec
    md5: 3ba992846657b9aeb1c9623b1ee29df2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ice/cice_in.nml
  hashes:
    binhash: 71de3045cac8e15af888d410374419d4
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ice/ice.restart_file
  hashes:
    binhash: 0d7517711819163b4f561f6aec4a239b
    md5: 5ce1e56cbd89b73e685f7b6d11ad3054
work/ice/RESTART/iced.2717-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ice/iced.2717-01-01-00000.nc
  hashes:
    binhash: a9ce7ad0d4e4e2b44d1ce74d3bb716e0
    md5: 0bbf3c78d9523edfaceadeec40bef8eb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ice/mice.nc
  hashes:
    binhash: eb9e54312814758b835e8220c2917cce
    md5: f2810b36e5fc5794933c12ebad5fb4a6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_age.res.nc
  hashes:
    binhash: d7ecee6fa86735c64ef7b2d38d4e8cda
    md5: e7e2d577340d257e68ebe13cf24e7641
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 15146d029ff83df557e79cf4ff31fcd7
    md5: 43365f8c1d8e42a017cf644791f76585
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cef0356be5562b7ef9236c9fb27a2aba
    md5: 5779481ad4e282cc13eab9619c7576f2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_density.res.nc
  hashes:
    binhash: dd34da9ebe7e3a6fc923a64ca267bdf4
    md5: 4183a42b7e025953ff8575f15a45856b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d52dfead9e1eb68262c4da4ae7e1c786
    md5: bc1105570a106bcc4458c9f77ff8d870
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c3509e6f96d87dcabd145aef0cb079d8
    md5: 9cc572945058e17eb119609b6cd677ef
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 79f3e41c5508699d1a050d2fe879995f
    md5: 06293617f84a263932452c725cbf693b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 23d2202e8a121acbd3a220010ceb919b
    md5: fba8501619774186edc7e2ec0e781a19
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a3c6d490fdd086c35e1979b2c186d8a9
    md5: d846fb85646f27b5ccbda215f5a7e9ba
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e0f94d40d841ba5d40aea39cda56fc0d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_solo.res
  hashes:
    binhash: 2e13c70b0521f663473ab597e038220c
    md5: 7957bd4e5d245a241ff5b2157cb17a0f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 494e4ea5bac8c2968dbd9993da4f72f9
    md5: 2a1fce042d8422c05074da10b19ff2cb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 640635a3576d28f245fff795d88686c8
    md5: 931b0e1f3f2e6fdb45ebc963a7d02e87
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_tracer.res
  hashes:
    binhash: 22fb83e8edca6959ab1916a611fb04d8
    md5: dc41844fd3df77625f6af73b92273cd0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d646d56d80657921934d3d7a5e3c6cca
    md5: 43db236f18308a2ca76d42efa6a98919
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0a4bdeee8435a3dc8408b7fc9f8b78da
    md5: 43d9ddceb3aa8006f40a506fcb7b86eb
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c1415fe66f52c14ab596b76f34162636
    md5: 98b6e8ae82d3e7bc7b0ffa31380c85cc
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart040/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1e141f5f9660621d67b09bb1de1554d6
    md5: ee29fdcb18faa3a22e1ae8ac09706d7a
