format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/atmosphere/restart_dump.astart
  hashes:
    binhash: 2dd0c1b8a47c9dd1f93ac3280dbee0bc
    md5: b1124a5beefb2c6407df33325000f515
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/atmosphere/um.res.yaml
  hashes:
    binhash: 19404e73ff1cd653bdbd962a05c5dbae
    md5: 85ae748d4d812262f63cce56be7c1d52
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/coupler/a2i.nc
  hashes:
    binhash: e8ec73a9ca40755c1110f4ae2b58dc4b
    md5: e23340ee94f41df5db8d4e8c72e7d98e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/coupler/i2a.nc
  hashes:
    binhash: 9a5529c453bd651d633aacf309ae7435
    md5: 1c1afc2ff22e83691830835850698710
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/coupler/o2i.nc
  hashes:
    binhash: 7484c64af76504007fe1021d529cf616
    md5: 0e3c413ae33f38ec5ec2bbf113c613b3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ice/cice_in.nml
  hashes:
    binhash: 9fa988ddffd39a853c3cfba11794e8e0
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ice/ice.restart_file
  hashes:
    binhash: 78c07ae64dfef27f807127277562142d
    md5: 471cf11bc064e0530f5a6c81bc585ee2
work/ice/RESTART/iced.2924-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ice/iced.2924-01-01-00000.nc
  hashes:
    binhash: ab38810f86a7dad7da7d082ed07923aa
    md5: 05fbe1903763b3fe0698c7c3f404ad26
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ice/mice.nc
  hashes:
    binhash: b3f2d0ff95c5c26e891f7f6f03db9faf
    md5: 1b495f0f6ccdd97a2e0d120e85948830
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_age.res.nc
  hashes:
    binhash: cfb9201d18592f2a5adbf0180db79c82
    md5: b25d8cbb2bb94c79bdc188a1a712a663
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7ea9328e487a6b9317a0205524e9a2e1
    md5: 42992152c37ff0a76cb0fb3272648c72
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2531ac3fbfcb844bac7677d759749412
    md5: 845939c3abb630763018ff74b4427dfe
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_density.res.nc
  hashes:
    binhash: 3807e8dcf30ba2a5dc3be0cc59e163a9
    md5: 1746929f6c2915b94ea230de30010e6a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c34602b28eac0882d43ca1461bc2835e
    md5: ed2b67870600cb053f0e943aca0b3a9d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1204f21fbb98b314351de902c25a7a2d
    md5: fdeb1e1377a74c8de7c8ac14212ed145
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5f1bddc1c039ddc624c65f4ff1d84812
    md5: 02d394b47efc05ff81f5e2a13f151279
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 95eed6535995ae692660fdc1989f6a66
    md5: ba8d4fd9b1e033d5ba5a062d37fbf6ed
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3992142899ce68f2747ecf2edf6d08c9
    md5: 8d9a9a2276ecf2325f4358053ccb890d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 40c583882d52166065ad57d3b3ca9238
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_solo.res
  hashes:
    binhash: deb25b969dfd759bc6a4f9527caddd2d
    md5: de6920baab175952f57438b702632d24
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f155d3cf353b13a706d05fafb8427ff3
    md5: cd9485128615abce09a88b8cb2b675e1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b717d5bdd2f3e132887376ef2dc89cad
    md5: 8fc701d1ef0747cc36dcd91166dcc421
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_tracer.res
  hashes:
    binhash: 1133c38745727ace7b69471dea9297c8
    md5: 62f09101dff377b592182c4919d5e6ff
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 24939e37855ab9c926a812db526c7240
    md5: 4f5a435f9cc8fa94c4274c376ea957ac
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 446fe8df5516f1e1a3115c094a586711
    md5: 1b2d3f93d76c2a1b919fdcedd48d15ea
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4610c98b769570eb6a46be655d4449a0
    md5: 8b3a4ee7333c4516415d1a6acbb4c1b0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart247/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9827597d44890f97b06d3f0630d01547
    md5: 63985954d92e7eb08bd8035578fb2c17
