format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/atmosphere/restart_dump.astart
  hashes:
    binhash: c907a6b1b830bac1d4e0a48b7f1b8ba8
    md5: c48a36a6bed69efc7e48390b11159d8b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/atmosphere/um.res.yaml
  hashes:
    binhash: 6822df2dfee7ffaae25133f8e708e510
    md5: 56c80695d6978c06206a51fd7dda55f3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/coupler/a2i.nc
  hashes:
    binhash: 72ea6f121a0f7e0da9cac5b71fbeeb15
    md5: e3dad14842325d77658c0e439dcb38b7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/coupler/i2a.nc
  hashes:
    binhash: e0579f0a164960301096033b4032e8e6
    md5: bc0857c4869b66119594b0b94e7e2013
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/coupler/o2i.nc
  hashes:
    binhash: be6eeb67418ec75f3cf193e876afc2b2
    md5: de3c45bc323aeb9dd82aaa51a1478c53
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ice/cice_in.nml
  hashes:
    binhash: 288dfe60cbcb944b573a16bc8c6682ba
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ice/ice.restart_file
  hashes:
    binhash: aa199b86d17ee8b5a9a329df664573d9
    md5: a828a1cafd8683896ce017bfc69fbf25
work/ice/RESTART/iced.2859-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ice/iced.2859-01-01-00000.nc
  hashes:
    binhash: 6a7e1745ec8ab272c1842bf7939d5bbe
    md5: d8c2eb03f8d90bb0629c3319bfbd0acf
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ice/mice.nc
  hashes:
    binhash: fb1815e0a2f7a1f49dee248c66e447e9
    md5: 5cd482af0f0e5fb820cdf2c6b40cb8be
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_age.res.nc
  hashes:
    binhash: 469cf5b66b2d89261e2db7a72a51db26
    md5: 769016926a4d2cabc1624f4d39c60400
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4e92721d17077206efebeef7d22ca16f
    md5: 8de2d5a8a15ed5fb1e992b110bda5dfc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: acc179e467c9c0e41720db82162b42c0
    md5: 2cad0e4c422ce0a022ce86daf381be22
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_density.res.nc
  hashes:
    binhash: 3f4469b11944740955ca55542ebe9afe
    md5: 8ab4f4f6c248a94404ea47a703bd4d7f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8e0a17577e30467f628f3556f21ae30f
    md5: 7c71a7e4f5941c6628a49e3665cec197
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1f2e3c8eefa9eb652d5d2fe6c679178f
    md5: df866c5faf32b1be6b464fe70a92cd12
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bae7d769aee9b5f15afaa6d3af36f129
    md5: ed8c7dc121f04fc7dc118100d8943434
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 419bd05ec1df13c3d4eca90cc2a7c9d6
    md5: 524a1270b4c062b86db4629ff96108f3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8e65afa2aa0d68159ac05d7c3a3fea93
    md5: c07b4fcb0ef189f4f68b301cc0ee53f9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: bdbb087cedaa773c5005bdd7041b5b12
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_solo.res
  hashes:
    binhash: d7095416354f4909fef2655b176d1ce9
    md5: b405cb2384965888a37e0784863ec6f1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d86156447a64b37be43528e6bc96334e
    md5: d19a62af8e38e5145b622339514446c7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_thickness.res.nc
  hashes:
    binhash: be9d907b06c252ec95cc5fb24891cdd1
    md5: d0e23bfba0d23d7599b69a71cc645b36
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_tracer.res
  hashes:
    binhash: e1c1e5abb6b007ae0e27eb19e5175b94
    md5: 190986e3e2a4ae7ad403f7effc7e0eb2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 70284a4db6e4fc06ca1d20f8e40f8269
    md5: 671861d0d06a5624acd2f04edea32c2b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1958a6c3065462d32120ea7ce38c1dc6
    md5: 30b43bdb3642adfc470d8c826a9cc787
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: da11f90dd0cd36e14fec3789ae5446a3
    md5: 0c350579eea61508aa26373744b405a0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart182/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9ac2efd54e83145d6f512d786d624c1c
    md5: 729d3f6dfa33154d529be15a028cd3fe
