format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/atmosphere/restart_dump.astart
  hashes:
    binhash: 0d9d55275dfcd36a00de0fce48ad6932
    md5: 8b95a47f5ee346c7dccdb027132f9f71
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/atmosphere/um.res.yaml
  hashes:
    binhash: 28810adce6170a743d6607a2aad0b738
    md5: 413415893e8c8efd72084270110a9480
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/coupler/a2i.nc
  hashes:
    binhash: b6856386e00e43c317ab5537f437a782
    md5: bfdcf58f1436c84638bcd0e4dd2ab8dc
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/coupler/i2a.nc
  hashes:
    binhash: 0c5f34f7c041981be4c2ecc0cedd50ab
    md5: b721855819f42055fb07e2d9a53053e9
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/coupler/o2i.nc
  hashes:
    binhash: 483078d8ff1c0aa10afb45d043750204
    md5: 7e70bb32ee2ff6213f7519382d48c67f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ice/cice_in.nml
  hashes:
    binhash: f55881f2c28e13c4ce6a8d63dc78d52c
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ice/ice.restart_file
  hashes:
    binhash: 5de0b8d399b83607d9b93ee885034dd1
    md5: 75956ffb3da4a4cf51a6e05024199394
work/ice/RESTART/iced.2728-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ice/iced.2728-01-01-00000.nc
  hashes:
    binhash: fb68f31eb3e7ab238f5edcc726faa40d
    md5: bf69b050c4927dc38842345fcba99eb4
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ice/mice.nc
  hashes:
    binhash: 1bcaa0766cfe54bdcefb1cea34d4aca1
    md5: 97e87821f9daa6c4267e2d118e3f4db1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_age.res.nc
  hashes:
    binhash: e04c5bd3f3ed4d8bf457a430d366f4ba
    md5: 15db958b93e6f30ab54f585aad2b5658
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8c564d0079c7a057d11f06c8926c93ef
    md5: 9ea62769483e1ca9384421515755a9ec
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c29e33e144254c8201c136843c12bb9c
    md5: 3d3b33d5c5e8d14ed939b92755902eac
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_density.res.nc
  hashes:
    binhash: 8b561ce9c03f3eaa780c9ebef554080c
    md5: f022c3c59cdd9117d5866c8f130574b8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c9cb458767481fd4f0f4cd5a7a8ed14b
    md5: acbbfff440ba75b8b6c8a368e3285d82
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 91f310011c580f0852d770a7866f4d9e
    md5: 8e4b39685e4463a89b19598d10cffc10
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c8126cb10e935fa9678a14f4fc717955
    md5: 1b76a807fcf6bbcaed2d0523bd834612
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: edf3efab577d541beb849ae6c19c4ece
    md5: c01f6818377ebbfe414b9331df933784
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d528bf8d2ea07d3cf26506d0a7716b7f
    md5: 73fdfa567d5167681a116d434cd151f9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 161a1c8d1cfeb663077581e0c6034013
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_solo.res
  hashes:
    binhash: 12bf7af9e9751ff1cb7386e99daf9c25
    md5: 2fd6e7a8c48868195189e3a6b389b90c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c46a77688c47e8ed9c82e82c0547cb0c
    md5: 936581c32a5b0c61a2098cb3a788c1dc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_thickness.res.nc
  hashes:
    binhash: be66debb17331409ed27a1a2aab37be9
    md5: 7e80ceaeb03732b03d0dac6b1a2950a9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_tracer.res
  hashes:
    binhash: 2997370b0785038704c51efa7d110156
    md5: 9d792dbc40ecae8d1a0d98e057094245
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 27a8bcfb5c068b68d54bb6cd71d0bbe9
    md5: e5a1fe93b29aeb30b6e2a99168fedc88
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c9460cc4414638efc3a2f0e50081bf18
    md5: 00cbd1f879b5b042fa623dc1804c540b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3c01bfc2812e25ebf1fd6914e84487f6
    md5: fc208eb446a27f15780ec1887c4d71a6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart051/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9dc144457c14181ec98bea71383bf9cd
    md5: 23266fe8155640f5bba85a6d46e57a49
