format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/atmosphere/restart_dump.astart
  hashes:
    binhash: f0c94c8272d205fa5531ee3734112627
    md5: 655436d297029814cc95a84191cd56ed
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/atmosphere/um.res.yaml
  hashes:
    binhash: f4438643319cf4e5cbe566df64f5d799
    md5: 7c43a1ce870065031814b036b1fa00ac
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/coupler/a2i.nc
  hashes:
    binhash: 06fe46195b037072d9a1bb9104b64202
    md5: bf1d6dd20a98cfef518bae26c93b1b8b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/coupler/i2a.nc
  hashes:
    binhash: 0a768711c1e09db70c8549f5b9bb787a
    md5: 8defd2f0d831b671797e706018b543d4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/coupler/o2i.nc
  hashes:
    binhash: 70560c99fd231f97be765d92b0a5668a
    md5: 7344df0990bd474a0067df23f9c10e7b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ice/cice_in.nml
  hashes:
    binhash: f65e06d2af4cdfd75ad1ed3a57d64ec4
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ice/ice.restart_file
  hashes:
    binhash: 3dc6f70df71cc2afa6e25a0120b6e30e
    md5: 9e556971e664892fe3fa3fa4885261fe
work/ice/RESTART/iced.2813-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ice/iced.2813-01-01-00000.nc
  hashes:
    binhash: d99fe8cac08c7a092cb0e07f4b8c5500
    md5: 67874ba83b8ad434c57234cc14710f4a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ice/mice.nc
  hashes:
    binhash: 30eb94b20f7b86cb2c2e2fc98fc48049
    md5: 8f3be5de34dbeea6ffc2612eb700e765
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_age.res.nc
  hashes:
    binhash: aaee0bf3cbc34b4ccbb3a847a8ac8fd6
    md5: 6b4ce1be5f3d2dda84845b2c7f8b1911
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: eced7d526a19ddbed60dc9471bb897c9
    md5: fff03a733be52ee121784073edf1759a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a8ab72a76c22b23a873baf76702ec669
    md5: 22dc9abcc3a2895cbf64b34543d37279
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_density.res.nc
  hashes:
    binhash: c3d83665a56448770f22827b829f452f
    md5: fb0762abb8059d8b8e91ee73152bb1fb
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1f2f2604d589e4996ea714dced5b7143
    md5: 7ad977ca58c118f7fbcbb6201850d13c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 32988418909a850689d425468526246f
    md5: 2831e05a4b89b6fa9632d811ceb05ecc
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e201155655494359eb0d1a5ee1dfa7f8
    md5: a8c7c1ea5117f2777319288fb4474258
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ebda325266f50b6e877f32280d5e1d7c
    md5: ff4e793092b93e4ceca157ede0d72a7f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7a11498141a57679d35ec873a7359011
    md5: 38d1daa3d9d34751a9b6803154911d34
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c907037d87ce9e66e715bd020c704b0d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_solo.res
  hashes:
    binhash: b02a882ede2b12ae945334d6ab88311d
    md5: 65ed76e6dd64f0883096b7eccc74147f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b1d6f838b24974c323921f55fd796e02
    md5: 588892250eb0599eb422ebda716829f3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 69010dada188fe40edc66c6fafb58d32
    md5: 5da11ffa65f6ea801d8d6cfa5d40a1fc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_tracer.res
  hashes:
    binhash: 7c92e64d259d6d1d4033ba6be1a9e14b
    md5: 7edac81687788b41e3f190b3ddfd127b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bcf4a8dcf9b8bc1be8c714a986b4aa96
    md5: 4ae528b91b73a101205ad94153ecc3a3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a6900a37143f5ab12a03f201e6ea737c
    md5: 6060f9c46783d119c91d401dc1a53820
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c88e4a5b2dcba7df8ddc58e227acf40c
    md5: ca17eda95f99a856e955bbc883ba6184
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart136/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4d57b23bec3e37414ab1e8aa4287b588
    md5: 83d6b15d95544a79a0983404d0684704
