format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/atmosphere/restart_dump.astart
  hashes:
    binhash: c5d7156c98ec7181713be6e6cdb8f530
    md5: 92bbb4f622b43ddd312021282c821d98
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/atmosphere/um.res.yaml
  hashes:
    binhash: 9c4884eb414db45df5637b6cb69445f7
    md5: 85ddbf7ae07e413c972eaed9e305c4df
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/coupler/a2i.nc
  hashes:
    binhash: 9f6425fce2d95a2a8061b3bfdd9aaecd
    md5: cb91a58d2e02e85b042068ec87aada79
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/coupler/i2a.nc
  hashes:
    binhash: e1e28fee69055d75df99e1aa10819145
    md5: 544feacfb0cf0c60a60e6e017d5b5e9c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/coupler/o2i.nc
  hashes:
    binhash: b151c3dbbc1fd858aaa91b5acc5b1e2d
    md5: e559983eadfb8d19c67c5de22067c81c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ice/cice_in.nml
  hashes:
    binhash: 9177593ccb71118e4e00dc1e857cebb0
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ice/ice.restart_file
  hashes:
    binhash: 84e2ca74a5c897e5d2d246ac8e427ec6
    md5: 39e5b94618616cd197e63aa9c09b2b8f
work/ice/RESTART/iced.2898-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ice/iced.2898-01-01-00000.nc
  hashes:
    binhash: 80b203f9e51e4c20afec5e0a73ecf548
    md5: 34850c3ff98e72fee5d92f1a18f60bb3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ice/mice.nc
  hashes:
    binhash: 3919498192e666927dce0459600172cd
    md5: 752c99301332dfa416f03d9830ee16b0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_age.res.nc
  hashes:
    binhash: 24a0c3302f8f3b805fa8e62fd7833f9e
    md5: 5074f14861079e3be74bc2ffda9e1db9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 080a721455f6e287a3f5bd96a918f0c4
    md5: 94902da045233651307c8b8232928dac
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fa507a23601eff55b41c36c3ad031931
    md5: e26846252c4cbfdc532f8062ab12c77c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_density.res.nc
  hashes:
    binhash: 79f14c6ffaf9b7bf943793ddccaf508e
    md5: 7d6ab6da1ce454e6e433e2938c039b51
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 20e33d190d7a5ab7bf0609a4deaa287c
    md5: bb686b2e9a1d5b70050d33fca10df06a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a82ce93425fbe72006d51c29458bf56f
    md5: b769ccdc4afd837767f64703f12dd9d7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 00e9e2392136e4dc91c5ca1912e5c871
    md5: bbeeb9b35292132706d86c736d7f9257
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 529d9d2d5985db0e530cb9fc859a3195
    md5: 0a6f14e94350e3ede5ba9a28aa45d619
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2b43564eccd6c2baa28efcabb4df37f9
    md5: 2b7c1d63456a6c2afdfb74f6879fc9da
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c4c88560897eaf83b7ed055e915621d6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_solo.res
  hashes:
    binhash: 102a493102fbabf2715fac2762d2167e
    md5: a7c96cf20edc83aa6fd2e7d4b8f9b1b1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ebcfca60c4e66e3cd6d742102e5730b0
    md5: d99c574f713d7eeb2851378d6babfa9d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b952ae55744b4931374fbc1afcac2dd3
    md5: 1f49be828e3c68a2f12bd4ae5bc4ddd2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_tracer.res
  hashes:
    binhash: 7a303be9375659ef193d1c097b316cd1
    md5: 349ab66af20f7becbfaedcf8f0a3e044
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 360fcbf12434485f48d689ef85629aef
    md5: 9b5b9487b6dc0d79e9cefbc4fb7f37f6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f7a4b3a933cf5f6551f199bc16b8d55d
    md5: 482bac5cfe9fb5372ad83330e9dc4cab
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b4ec7985f30eb29a206b5c0a2290ff7b
    md5: cc9f322e0937b33e43b1fc5306bb1bc6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart221/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 18eac9919d20f9d295ee778782eb9e01
    md5: 03bc3f0d409406990443d4efac76848c
