format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/atmosphere/restart_dump.astart
  hashes:
    binhash: 689cc7c9b87aa5f1b6795ef1e18837ba
    md5: db6f2d0bf37c920553fa74b28813f97d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/atmosphere/um.res.yaml
  hashes:
    binhash: 466aef2539b71872d7555795bbcaff48
    md5: de5efd45b1a2ed44c16ecaa57dfeda96
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/coupler/a2i.nc
  hashes:
    binhash: e610c0500751c9dd31504d203861615e
    md5: f9cd18f0690cecd1b212ee177b15bf43
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/coupler/i2a.nc
  hashes:
    binhash: a3e75bb8b4ae9d91989ccb4c48187465
    md5: 369edde71cfe3a5f3ebb10240e35d55f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/coupler/o2i.nc
  hashes:
    binhash: 7e5a72bfd6c6a0c1e4830e1a20a59113
    md5: ea80d7462a3bd3bdce13f3edd0673d14
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ice/cice_in.nml
  hashes:
    binhash: 479630faab0b534fea2caadc0e9fe653
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ice/ice.restart_file
  hashes:
    binhash: 61ff61cef8a52a8b82edd104e7e66e1a
    md5: cc7ae9ddd677389a0842f8a9bb0c3aa5
work/ice/RESTART/iced.2715-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ice/iced.2715-01-01-00000.nc
  hashes:
    binhash: 856128bb373dd7ffce884a598a3d0e58
    md5: e69a5c3b54bb6e87857aca32fac35238
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ice/mice.nc
  hashes:
    binhash: 97c92fb03e17d361d6e58dac2cba816b
    md5: 08b81202c149a446808168f2107e2f60
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_age.res.nc
  hashes:
    binhash: 1463b22b916154df67e0bca7730f175e
    md5: d840cbf712392ed86207c81182997b62
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d154e218df4e5a8a5b9e56c0d07e5a66
    md5: 1d8fd7a31c9878de53ad78103579ca7c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b23c5b3c6d1ed5d4d1e8057790a4ab67
    md5: 7f4d0ae596d1e2897242dbb04a31fd7d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_density.res.nc
  hashes:
    binhash: 5cec80f3eff5133d39affd2a7d45bb4b
    md5: 9621bf775a2fbcd4108baef7b5206898
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4a9a302f397ef3d2f40e529f8913bc41
    md5: 86f4c272fd93cecf967ef1e76fb4561b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 77ef7ef900c6635e8db35a43e7466203
    md5: abf1df76c184d97c37929fb40f40ef12
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c1ea60e0c91fe683352965a0c1fe3b06
    md5: 7d6675d2eb55ac253d3ba710f6db4299
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3fce26e5f912bdfe2991d0a91916383c
    md5: 3cdcaa798eb7f1fcad7b1cb32752bba8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c9eef7f6351c0ed57b064cd772cf5e6c
    md5: 3db809f6e4242d86edb44e5f563e78bf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 88e22f77547dde30ead68be9501a6f64
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_solo.res
  hashes:
    binhash: 2da52fdf45b416d245a19f6712deb589
    md5: 1d53e9085fc7743d978b5a00f7358f48
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ba5c5d8dd896ba2ba37332efbf3ba7d6
    md5: c77fe1bb9cffc61b6d0e646d0af1c0f1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 479a9b6a4dcb66553d0f43d38a6b12c1
    md5: 045984efb6e2ca2841adc78a2fbc5c7f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_tracer.res
  hashes:
    binhash: 1845cfaa9964b0cef4fc04f5c7bea746
    md5: d5f8918270eae2a75d678cd894976822
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2bca86fad9d737035c0ffb14fa960750
    md5: 3b09ba75b9230ec807b6fc44987110b5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ab0d9274707446b1ce12b35d18c37175
    md5: d1f81d65a6fd0769e1bf8f32fdeb57e8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 11b0a465395a85bcaf908c55606b7430
    md5: afd9576ce4c69373f66b49b728d6d521
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart038/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 534b92a3a4de93c3671a3ae20f01f99b
    md5: 22f9b87acbf20af4ddb73051ea59d167
