format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/atmosphere/restart_dump.astart
  hashes:
    binhash: e9ee32bfd673bf476671d5566b83f58c
    md5: ba4f65c443c6d2a93385cf38ceb123e3
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/atmosphere/um.res.yaml
  hashes:
    binhash: d2242b4526427b8a6d09065108d7e896
    md5: 3799476c44ad810f06ee248dd8d58889
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/coupler/a2i.nc
  hashes:
    binhash: 424e0ca7c9a3a10faeb7177860ff5cd1
    md5: b3839596b889724e0f74249bfcbb2bbb
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/coupler/i2a.nc
  hashes:
    binhash: 67c39bcdb415c173e648db83f321d9be
    md5: 3ef44fab3b084a45e9b3e5d6c3ea864d
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/coupler/o2i.nc
  hashes:
    binhash: 12d67c7aadd7ea7c134fa6fb0fb1e973
    md5: 9cc309c53725980fb8ceea8c3beb578f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ice/cice_in.nml
  hashes:
    binhash: 641f50276cc00238fb7e6173d5a388a2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ice/ice.restart_file
  hashes:
    binhash: 8dcc25bc39dc2657b229f57ae4556560
    md5: 422d27f3e0e57a911d0460ca51a34307
work/ice/RESTART/iced.2145-01-01-00000.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ice/iced.2145-01-01-00000.nc
  hashes:
    binhash: b3f84ceb3af051add8909697387c2d7a
    md5: 9b38a443da662dfef1ce950042dd98ed
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ice/mice.nc
  hashes:
    binhash: bd161731e15386fe1e64900daebd93f4
    md5: b0f77b9c94aadc78ad29846129c068cf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_age.res.nc
  hashes:
    binhash: 2d5ad3b0ef9df816587bae89156b4ed9
    md5: 8ea6938953bde98add4f0396b3aa4d7f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3c0a7250ca1936fe6d3c14bc89dc4149
    md5: 1bbc9c7b26a763824600d343721284ca
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8ce666196733f53a7ba8c7f2f0672f8b
    md5: d3319b42b15770e6e496bf876c56c3a9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_density.res.nc
  hashes:
    binhash: 861ecb050ad76ca502e1c178849f26df
    md5: b9721a24f0ea54e6148149b6fd8c49ca
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d3c421f288b676ae709f44aaf0dbd4ad
    md5: 9c74f9b91e446eae36647e1532b5c1e1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 460f0b9d162e10e0f54c190495f67c2a
    md5: dedf6f50c59997f3d1a4dfa91e09141e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b3ea37272b5a2ad2055738a9780af49d
    md5: 5b83d74deb91b28687ab17591ab8ec7a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0ed9eb7fee308642bc87d9b0e38c54fd
    md5: 778294e24b94dd3de9c3c4c7ddc4ae1c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 578b08a0e0597abddb8ab4d43f7687ee
    md5: 3cee186611b12bd55fd6df5d8705bbaf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c1bc80d78f4969bb71f61aa74021036d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_solo.res
  hashes:
    binhash: 23bfbdd9e7891e0219c7227ac80659aa
    md5: fc8621b51090a6b219066eae79806042
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bcc6f9581294712d7dd1f34fbc655279
    md5: f94e61d860b97c1110da9ab9465b86dc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e8e87f3ea1a845ec0cbff1d44293e362
    md5: 27cc724aaaa0746715b60f8287bb7be3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_tracer.res
  hashes:
    binhash: d7ad00f9464008d4d1a06c6aab208320
    md5: 89366655c8e44c73707bb79d7f6bcf6b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4b86feb6a1f122de5975396325a8420a
    md5: 84daa2d28d4f4d0bb23323e873e20d48
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4186aa79b2d1bb2833940078bdf03e89
    md5: 701abc0960bb26c8d7df8d9ca6bb73d8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8265b158131ead0317e04c503faf7b27
    md5: 292c7d2fe3f7dbd632d4b88c13094c1c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.11.28/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0c42b3f0b8848275fb0b8687aab209ef
    md5: 2ef19c2a89987d615a629b6ade6179e2
