format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/atmosphere/restart_dump.astart
  hashes:
    binhash: 6add24532b8ad0d303efd7e433b2ce7d
    md5: e854f2b42c72bd32f16e11627e59d8c5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/atmosphere/um.res.yaml
  hashes:
    binhash: c3fef512e673f171d97991b265d6dca7
    md5: a07c905c0d122e3942b2f1dcbeac12af
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/coupler/a2i.nc
  hashes:
    binhash: d97d6aa97c3df2aa7993656496671df8
    md5: f78f8ee2b1de9ad6354acf1b3b082229
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/coupler/i2a.nc
  hashes:
    binhash: 76db97aa1b26430b010bd824df39ba08
    md5: 2318de66a06af199b1d392b05cf8c6fa
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/coupler/o2i.nc
  hashes:
    binhash: 9c125d6e93103a1c107a29e0ace44375
    md5: e17f4227994052c5f7e49428f31c51df
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ice/cice_in.nml
  hashes:
    binhash: f6525704727d2c77cdddf57e5174defc
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ice/ice.restart_file
  hashes:
    binhash: 4e14c7c6aefaba45dd768ba2b0b72622
    md5: a0d2cf5d4c3099772e6dc90f6ad7673b
work/ice/RESTART/iced.2892-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ice/iced.2892-01-01-00000.nc
  hashes:
    binhash: 8fa88f3a50910d5d1989bc6bae134776
    md5: f9430bac9aec21dc59c449e774af4ed3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ice/mice.nc
  hashes:
    binhash: af4cc3e99ac21f19175c3d44021f0022
    md5: 417c625ffd977b351be06416a18ce0b0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_age.res.nc
  hashes:
    binhash: 5470c4599b629d253514092afd018a18
    md5: 7dc60c9b543e4e2e6c185e8209f77821
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fda6ea5dd8d47a67a955cb0f01b05a32
    md5: d7fd0342180fb8124c85723b95225c7f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8984e599c5c2a6a97ba7ab5ceb1ab0e6
    md5: 7d908f4b85ac4c5b659361fabe657d9b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_density.res.nc
  hashes:
    binhash: 10255c5a2da468c727f7cdc39aa71342
    md5: 7e3c81cb28925ebf9bf3c62759562f95
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3292fec3e583b37552d8acded489105b
    md5: de225e06e0a27ca4d3309a49daacac7d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3e138766f701bd82f5ae8e6150b3d5c6
    md5: e9469af02c7b41e5f45621b3bdea507b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9a47844d75d66f65f794346a012d55e5
    md5: 00b9cb2b849c095a3a015997e0d05156
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d02198979875c94d281675b88ef34be9
    md5: 8d140bf515f0b8f92257219e1c7b9169
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b426d13fe2110eedcc0b5aebb0a30fdf
    md5: 6596540d61019dd9bdd112db040b0767
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 64bcf7065e78d52891fbc2bc07084941
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_solo.res
  hashes:
    binhash: 341e6e35562a4eeb50de34a2aafa3b17
    md5: 7cb40c432f2d7c121c34155fc092f802
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ebaecc875849c8b088ceb80e80e5bff6
    md5: 965721f0685699439a8cc20f79926eb9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c4a8add0003c999b87ebaf64c1d83d0f
    md5: e40323b9982fe21a81e1b35516501229
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_tracer.res
  hashes:
    binhash: 040efba6ddac51035e93c1789cb39ff9
    md5: 400f923180d5ebecfbd057bb74afa4aa
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5ad93f8bcd304cb2ba0ff72394da0672
    md5: 9fa71288883e08db42a17dc22e2800b1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cd1f04d8b90efa9559789c5418e6d7df
    md5: 7066e7b31b17cd78d51977c3de403a6c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 10264949a94bf660dfc59f6dc6442188
    md5: ac0084900f8b871aea6e12f9d2c3c02d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart215/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d4d141d0e6ff682aa8e00c76b8b9234c
    md5: fadda04de6f6b75ab2ea994b07e91aa7
