format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/atmosphere/restart_dump.astart
  hashes:
    binhash: 7182306e641722079af0ae80af4aab46
    md5: 903370e1f19bb2caf1b5aaea8447ee11
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/atmosphere/um.res.yaml
  hashes:
    binhash: b04c9103b426963724c01bb85e284fe7
    md5: 9e2764888d7b9f9e2d86a9e52f5993f7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/coupler/a2i.nc
  hashes:
    binhash: a253ab317cb7083ba9b9b160eb098480
    md5: d52c6647718718c3c01af82faea6c4eb
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/coupler/i2a.nc
  hashes:
    binhash: 26a602485ba2218256583cd5fce676b7
    md5: c3b7fac389063608382f0a3250d3b51b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/coupler/o2i.nc
  hashes:
    binhash: b01bf89fc6fece90506e10fc7dac93b2
    md5: 228a0d37437a505ddbb081158ed43813
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ice/cice_in.nml
  hashes:
    binhash: 39474e55261b38585591181a178df48f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ice/ice.restart_file
  hashes:
    binhash: c326af099734fb1d2fceaaf461fd5136
    md5: 43d0c4638b195ddef695d71958625097
work/ice/RESTART/iced.2770-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ice/iced.2770-01-01-00000.nc
  hashes:
    binhash: fe274c0ef0e736e2d6d2ba220fddd526
    md5: 915686f04fc6ba606969d593238677c7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ice/mice.nc
  hashes:
    binhash: 795b157d32e75317cede7c3f7b207760
    md5: 236752f034e8707d0c40915b3463bc5c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_age.res.nc
  hashes:
    binhash: d606df0f54a2d792d07207996c3e3247
    md5: 16604aa5edde64c6c812a1f55701bf1f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 15cdad7dabb69a34cd2ca36d526cf863
    md5: fa64e46b231b6e079a538d71cc11de81
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 147812386e012765f37f8d4b96504b43
    md5: 39e2088211ae1514401e0fcbc446d80a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_density.res.nc
  hashes:
    binhash: 62e42e775e17a796312ced57ec6fd22d
    md5: e55c1f7f290546a65fd2ff00dda78206
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6ed4dbdf18986a07265f992ef558251b
    md5: ad145902c68cb900bed8652d734d5cd4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9c0d14713ec7a4268e156c2d4020099a
    md5: 44c3a0de10d45d2a02e05c3296e1d4b7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fdb7c91dbdda8d3e83aa38551c1d7e59
    md5: 18b55c27de683d45e60ece5eaf2897c3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: eecbf93ed9f56fef74511a8562d6bcb2
    md5: f52e95d5cd422c9adcf2dda34bdb19f5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e6368fac76042a02e5a39846d41746c1
    md5: 72644f9ee5e94e5e914270b03fbd2145
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ee3aacdb4a7dac9931c8f1e26ba7ea4a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_solo.res
  hashes:
    binhash: 3ae5e9ff0f49c4c04f43ae78dc89916d
    md5: 24598496a5ccc8fe357ab3e060a6ecf9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7fda97a71e678104438742ae78755da3
    md5: f964927acca52090a50fb38d9656c2ec
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 17986572e68c27822ac3201fbe16aef2
    md5: ad2ed93eb68bca7c6daa745fd19ac466
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_tracer.res
  hashes:
    binhash: 8323303125ded3b1bdc2b37e9b842a6f
    md5: 587675a5be2722ec18f0d67a05e579f0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 478ed4ae87cd280676feee7c0d9c2715
    md5: 0bfef2d5fba2095ee21c6b1b5c508360
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b203bd1b5cdb178b531bb61fd13e20fa
    md5: 1aba199c9aabae536869cc2bfe59ded9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 51f09387813e9508f92d900b1677abf7
    md5: f077c9361445d192789e18f348b3c688
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart093/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2d704fba5c8dcd38e8c2efdfb6d182a3
    md5: 1e4df1fcc3fa86d1f95fab3c90d65f73
