format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/atmosphere/restart_dump.astart
  hashes:
    binhash: 7510e83f006248ce35de55f8f6883ef9
    md5: 4bf518c8649494813951d0bfd72679a2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/atmosphere/um.res.yaml
  hashes:
    binhash: 5741837c2285167b883876a514b3b7e1
    md5: d5c3424207491ab6206137189ae93c8f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/coupler/a2i.nc
  hashes:
    binhash: 3be30bc4d7a27323dd58bbb886821fa6
    md5: 4496e97cdd5768aedd4c4ab186b85faf
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/coupler/i2a.nc
  hashes:
    binhash: 79c6c27a35928c2a6fc0468be3e7f1dc
    md5: 0d41201462cfce3c10cadc1abbce9d5b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/coupler/o2i.nc
  hashes:
    binhash: 8b9cf6963edddd7a39f73fb39680c49c
    md5: c362a53f697770656f8a47915a7c8d7c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ice/cice_in.nml
  hashes:
    binhash: e863eb2c53399bf2dcc01bdc90548bf6
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ice/ice.restart_file
  hashes:
    binhash: 6314f5e0c63499ab88cab6a3ad710609
    md5: f340490bf8ba9e7aae8ae54a0220bc12
work/ice/RESTART/iced.2927-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ice/iced.2927-01-01-00000.nc
  hashes:
    binhash: 1e4599af369dc807dc83db6a9d54fcbe
    md5: 6afc709237cdec8c704f9097d4d15ce5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ice/mice.nc
  hashes:
    binhash: 812e0902e5370872457069d1e5fbff65
    md5: 0c572723015a17740865f646f1485fad
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_age.res.nc
  hashes:
    binhash: f0e069a94c96ef4521001ad0d5f17fcf
    md5: a4c3d15da586d4ad4ae4d05400313275
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 816286215e4b8227c1e0d7915c07c91f
    md5: 536bafa3b804db8df3831e81da1f3c63
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3d51c3f0e9fa05d357e832f7a66213b3
    md5: adbd164692384db3032d6d165809aa20
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_density.res.nc
  hashes:
    binhash: ba4569fa188d23068b2e4d52c340f67d
    md5: 6c9996526004a7954ecab5b6c4236cd5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d3d2001ebb07926296f5b487e363fe43
    md5: 6c84bd16c1b403527205e4822d6465ba
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b8ab9b8c32843bc0b07a053369a83bda
    md5: bc92ffcf0ebab96fa54478abab4a2ff5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2aac97dd396be5ff5d7da3b4c4569d32
    md5: 01d1948524c9320ed53a0769508105a8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0a1c1b24a3d98803593069723ed7c91c
    md5: 16fbee7de016c896742a28de49183b24
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 41cfc45093ca747dbca659795598be58
    md5: d5f5e0f3896f9e3c97900cfe995e8298
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5640c88c9b61a2bf8fccf03aec013a0a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_solo.res
  hashes:
    binhash: 1e4c3ce597617514decf2988b4db58e2
    md5: 89a0ff82349957a91ee165a4c2a90060
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d1c5ef9233a1cc898c7a5afe5318ed81
    md5: 9feeba67f45822232b87a1c6d691bad3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9ae5d3d4c714705f90082caaf625cd94
    md5: 6145948215e6432932d3782b07a0b95b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_tracer.res
  hashes:
    binhash: d1c6b58abd1cceb1316d0a26e755fe63
    md5: 8c78d22a4b9042de9d62cb54ea958bef
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3dcc70e932f894fce014c39d0f290211
    md5: eee97a50eebd3f8a794c44dde7978652
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 445f3a38cc4a57ae7241637f7d4584ab
    md5: 38d2511233dfefa285f1c7a865577f90
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d76fed4479f92044f035e75a1a687f7e
    md5: 204fbce5d3e96a797bc4d1e288419895
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart250/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5bee0377b9574e85072b9c5e1d62aa0d
    md5: 41a1b0bb5da11e01fe6c5545634992c2
