format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/atmosphere/restart_dump.astart
  hashes:
    binhash: cb1f9c3fc77c6654cfc1b5ba7f44a5e7
    md5: 22c07c646b9c61b1ca964dfd0fa4a6cf
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/atmosphere/um.res.yaml
  hashes:
    binhash: a42fca5d9c199dbfe317ee843fb165d4
    md5: 7fe2992968835a6c06e199998fcbe758
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/coupler/a2i.nc
  hashes:
    binhash: c330cbe964da76563ebd62444342b0d9
    md5: 77c4125a6971f8fb751624eaed8b5a6a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/coupler/i2a.nc
  hashes:
    binhash: 888e1c9ec361536ab963b0fa5aebeda2
    md5: c2c957e523b51ab186e240e260fb301e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/coupler/o2i.nc
  hashes:
    binhash: ad79e65e3beb183412ac16d8e30e4421
    md5: c6bcd0dcfab19b69241940c135acc815
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ice/cice_in.nml
  hashes:
    binhash: 77cf6462ed9f66a246059dddb21ce4c2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ice/ice.restart_file
  hashes:
    binhash: d2c2da9eda0be4714ed7a85c488f055d
    md5: 8919975f82cefff6f17c9b6799f6ad51
work/ice/RESTART/iced.2808-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ice/iced.2808-01-01-00000.nc
  hashes:
    binhash: 3c22bcb2fe5a067f015bf97ec7ce8ff6
    md5: 808b9dcc90b6d00decfb2652d81f5700
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ice/mice.nc
  hashes:
    binhash: 6f831246c19583c86dc47234a44b197b
    md5: f8ba2aab6500929db9585726cd1a1a40
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_age.res.nc
  hashes:
    binhash: daff1be6afe0e818111cb630eee90768
    md5: 7569ecc6b7410c4b40ea48fcc2f2486e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 684cfae9227678cf959af0f59a38953a
    md5: fe90608ca0e79900564006ee84b690c5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 242ca412d54f0bc829a6192765ed26eb
    md5: ab1eacb7a9222166f2a9f951aa6ce91d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_density.res.nc
  hashes:
    binhash: 083af9354d56c40a3e06a8a87b4ac3a2
    md5: 8c8831204b68084546f8916cbb9d6275
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 814c6fc7e4117fd5ff8d2be4c258e13d
    md5: 86bc7bfd199043f0aeaeaab39fa67c75
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bea8b46a9f3b9459afec590845b562c7
    md5: 2119cc43abac988b2f3a7f30cda514b7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0b99a7f85c57fdbe484a96b86529710e
    md5: 45343d58334ac253596660c31f12f3fe
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6a9af567b075fbabd6999045172d5f61
    md5: 4e4326264c57038dc4c5e8a9a52377ca
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c8f75aae44ec9e4bb2f5959ea9233a5a
    md5: 662a396d023603a75df73e151efb1db8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ca8036c1eb55600b62b98d9246bf474a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_solo.res
  hashes:
    binhash: 0e3a9a6d1ff0e3e22f931de1129da637
    md5: b047bdc83f999e21888e4a336516537d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4c3230b4287e5dd4281ad533def84995
    md5: 4163b07d3e4d3e3cfa0b378ae4fa037c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 46acec2ab245b6c5adade9139c79f81d
    md5: ea6be16cb5a721821ecae1378d2d68fa
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_tracer.res
  hashes:
    binhash: 6d0fe33f7f07d4c558b2d13b51bde7ad
    md5: 88506fe727e87927338b98d1c9df7aee
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5cb24e8bfb021332a0fe171001c3762f
    md5: 838d54c7c3a44eb1ca284fcf3f417395
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d9baa2a08dc0b679e63d201a4bfef989
    md5: 2280fa5967e88d03e714451a7a5d19da
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4fd832bb0d82808bccfaf8494e013ead
    md5: 797f2f2d65476b12398367f1ce18ce35
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart131/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c5b00acd0f9b7c1bfd0b8bdc0069c242
    md5: 342de1e39f809a92f8d2491302ba43c5
