format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/atmosphere/restart_dump.astart
  hashes:
    binhash: b0f1a54f6b2103aa148d6b06f664bf46
    md5: 11a51fd9f518121887c60dadc254d57f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/atmosphere/um.res.yaml
  hashes:
    binhash: 12f8dd645d62fedee4876939aa734a67
    md5: 86fa49572ca11a455432684b0271ccd0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/coupler/a2i.nc
  hashes:
    binhash: cc9c993c2932cf7e3e6f2473f4e35604
    md5: 8aef6fd309f2ac45a3aeef5e70f925d1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/coupler/i2a.nc
  hashes:
    binhash: ea42e99d17e7375f8edcc19b05f6a014
    md5: bfe5b723749ed7f2c8913ca174e44f42
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/coupler/o2i.nc
  hashes:
    binhash: d4840005bc948558e4a5c8f5ef2b3b1e
    md5: 334161af5e647f6ee2b5a7bff9261a84
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ice/cice_in.nml
  hashes:
    binhash: f9120724a10d102bf840a95165907d53
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ice/ice.restart_file
  hashes:
    binhash: 722ea1c067459021157c2561a2898f86
    md5: 58ad4fc27b551e37ba837ae023d5e4a2
work/ice/RESTART/iced.2943-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ice/iced.2943-01-01-00000.nc
  hashes:
    binhash: c24e3a0deedcb9c9e9b111ad3032572e
    md5: 9e7fe82a071f31e205e035d16e4018ba
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ice/mice.nc
  hashes:
    binhash: ff050c5200925c07cd9818749bdb7ddd
    md5: 73991e4d505f1f35eb4f22c0276ae2a0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_age.res.nc
  hashes:
    binhash: 628af06b15c921f87c1f3d578c62579f
    md5: 8fa6f3fc85b96f062217e8f19f271b66
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 65c65fd1e75f80b0bd1c56468ae039b6
    md5: 185665a7b26d8231199b0e8f116ba528
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 840cc50f9f77a2428d0806102971873b
    md5: 220a9909d30117ec96d37613aff4f5c4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_density.res.nc
  hashes:
    binhash: 4e88dae4eacbab7e3875125af704ccac
    md5: 16f371f0f00c843005f349c9e4525d9b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_frazil.res.nc
  hashes:
    binhash: bf1b2b9c152bb74f937a2c61b48f7e69
    md5: 9bca109e7025d9741023aba962123229
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 89053ed2cb96a938dcfa297c9da4b52f
    md5: b7b071cce8f4fb88677952ad4124b0c2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c6a57c6e01970c2531fad3e65cfba378
    md5: 7180a8aebbb1110651409754a568c173
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7f6c1d58cbf69c64603ee47883902499
    md5: ff3695d4716f9e06ae67a212748db284
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9d4a26eba8b1cf89b51d4dcf2b4f24c0
    md5: 13295916514e0b612c91748c43f6a335
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 947af214433701941cc39e870c5b5a8b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_solo.res
  hashes:
    binhash: 2bb775f31853f43be027ea57ed118dea
    md5: c0ddd57d89db3312a7ef276bfb22aa72
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a08f3d2bc8ea7facd225ec4520bace07
    md5: e7b261a4d4a62a7da57ea2329d12f719
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8417de3a8fde814fc80c0db28dd8a8e5
    md5: 8d785fc14194aa50d904943403f879db
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_tracer.res
  hashes:
    binhash: d5e9499a9b9507bd351afb1b5f153f39
    md5: 6c57788f31b2a545302d854673631de2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7088dbf51f3cef9923e8874cb25f4038
    md5: d27d8bc18f828380c2cc741b0e497bc5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ba7e117db3838487f23a645736b8e5a7
    md5: 5dad5498ab53031f8ff2819dff473e25
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5b0af3b7f3a8d65695b6e3216c950d6c
    md5: 6d27cf95a75183caab30dcb03ff5182a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart266/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3705b8c984f2ff1ef65e0be68f55d189
    md5: b6674fdf2275c78f607b1a188041ded7
