format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/atmosphere/restart_dump.astart
  hashes:
    binhash: 86129aef7f76fc0cefb387878196e5e4
    md5: bb8c4b973251265e945afd9b0e48e77c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/atmosphere/um.res.yaml
  hashes:
    binhash: 1cda626236f67dfa01611d47480ef977
    md5: 82c2e1033c9f05721b35053643e2bdd7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/coupler/a2i.nc
  hashes:
    binhash: 642b655de6c4898e1f47f0cf7f4889c1
    md5: b444f38d914c569d86d82b0c792e464d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/coupler/i2a.nc
  hashes:
    binhash: c4110dce9333f0fbabd47a8ad2ab49d2
    md5: 907d7da6d75811b3e0730bd119415549
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/coupler/o2i.nc
  hashes:
    binhash: 933648146cd10aa9a7eed67bf313d8c3
    md5: ef5f1471aa51caad99cea35ff9611b8d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ice/cice_in.nml
  hashes:
    binhash: 094987e5b3ee11a88a71799b70fc943a
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ice/ice.restart_file
  hashes:
    binhash: 65bc2e26e5922f052d90b4d26245241c
    md5: 7b1d0d2367167c764c94066be69273e2
work/ice/RESTART/iced.2830-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ice/iced.2830-01-01-00000.nc
  hashes:
    binhash: aac4018e0193b042f6402ab35b8eb665
    md5: 4eb9fb572889046be37c82e3a42cdeec
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ice/mice.nc
  hashes:
    binhash: d9b4fb34eea1067fd6c7990bf982fb38
    md5: ba8911f886e7629b507ead7f8defc64b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_age.res.nc
  hashes:
    binhash: a471abe40642f78d4017ff6edbcda5d3
    md5: 7db8b6bfef7c648e40739a6f97271186
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1ca77bca7529e07a5d24edb2214de2b6
    md5: 63bcb09aa7c54339cdc3616f02212a65
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ab6c2c7a8c578e531c9ecb03d2caa7ec
    md5: f8e73322fe05742a598631d906e417cf
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_density.res.nc
  hashes:
    binhash: ee8cbb10ec79837425b56947acd65b0f
    md5: cca8eb372479c3c265c4f4eb0cad8798
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2929f5a9b30b11a7141a8244616463de
    md5: 67d9c77c808c0a244ecaeff3762bb44e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6f93fc1988a6ba35e7837125126d0154
    md5: e7d76ee3ad0f339e0d58bbbfbe912568
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_neutral.res.nc
  hashes:
    binhash: aeed46e66c5fe59b299fa763065d6fe5
    md5: e55ca15112a0399c20a24b66570497d0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c1540cb31e5e050c481294d15b632df5
    md5: e1e69e4bf136f3d91e0d641bc120c7a9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 39a33ed16518982b8bea3e6d273dc59d
    md5: 12823674e80f90849453a3ee94a1cdf0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d57611f208a2a16c27c51f66329d05a2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_solo.res
  hashes:
    binhash: 84a3c1af5e454442792183885f353018
    md5: becacea7e8415506a9e6ee0f12ffc716
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9dc1b1379fd6d1eb6ee77fbf09d6ebba
    md5: 4ddd909f9e9c7c64fff5ccb607b18d26
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 01c240009dccfc550af6261e7c8da764
    md5: 5a645559159e0757437b409024056e22
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_tracer.res
  hashes:
    binhash: 2b84a8260beb301f7b8e542d60ae5de7
    md5: 453a4ed32fe23e253ad15d3dede6c65c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 29a876037c95eed885bc891f75cd6335
    md5: cf1dab67a9d84d91624dfe8e9ac82186
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fd34a8e5c0530305cbb6920978c3b1fe
    md5: c6d509fb36ff1a7777d41e62308ef873
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 14e7a14690f1c25bb614c0c1f964b777
    md5: 2a72ced5345d03fc745c24a130453bc1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart153/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5ab9358e0ffae3061e2d8f6d43b25de3
    md5: 4f267730ff63ffb92fb7eee00e84610a
