format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/atmosphere/restart_dump.astart
  hashes:
    binhash: 44d7be91a3e1a2be89a6a813f2117503
    md5: 898d11274c487c06e8b9936cc4d662bc
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/atmosphere/um.res.yaml
  hashes:
    binhash: 84270f0275b2582e984e8ecc638bc2af
    md5: 4bb0edc03cd8316b9e5097928f40fc01
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/coupler/a2i.nc
  hashes:
    binhash: 79ddaa7357097dd109978ef2e814c88c
    md5: 0e22a7d56993cd666e8be1fc9f9a3f18
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/coupler/i2a.nc
  hashes:
    binhash: 7f1596b82a736d5c00919415b9897fba
    md5: 373a34b44d58de7e05426fc7df790286
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/coupler/o2i.nc
  hashes:
    binhash: f5fcc97b7b4ec43ba88754a434d93b22
    md5: 9f719e215c9e4f5f1d5781f99e3ba42b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ice/cice_in.nml
  hashes:
    binhash: c16de649014b3ef0be96fb1fdade474a
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ice/ice.restart_file
  hashes:
    binhash: 53a6515285c8b4909afe82edd898eb52
    md5: c972e23ab519dc9b1637a5d4f29d3238
work/ice/RESTART/iced.2814-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ice/iced.2814-01-01-00000.nc
  hashes:
    binhash: f744f39d39ea3de99e6f17100cd8a066
    md5: 31a06639ab177c54b960a0e1be6c3659
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ice/mice.nc
  hashes:
    binhash: 9a6bd32c05b6338316299c73c32a7cf0
    md5: 18bf8ed4906126e7eb2cf00668b832ab
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_age.res.nc
  hashes:
    binhash: 0833c67f21d9542f1ee54640ffaf76c3
    md5: 419831742efcb0d7563c3553f53f6be4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1f552068bea51a5c25cc1f4e50a8d0ad
    md5: a5f30340a8e966b494a84600a6759a89
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fd12caf0a7230e0aec789af2ab9ea728
    md5: 7f8981c0927a73f7f1601b94c4b1c4b2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_density.res.nc
  hashes:
    binhash: 6dd8da0f5388fe27d4eae38e0f4462d1
    md5: 5836f53663526113e61eaf1c4114e9d0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ac5bb35a3dd4dbf165a91d9088338e3e
    md5: 4aa506ba4676585f6943d6b38cf33eb8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c565f624fa85bd55af42772b061bc243
    md5: 5f9715d8eb971806e334b5afba4af8b2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 00f9d94f475307966e01792c1d00b209
    md5: cb4b1de95f16e676028f5b27111d7214
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 096059f4c5975053b779da58eb44a0a1
    md5: 0f00ceb3942e7eefb1049874cb5cc0e4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c1ce7a384ee57d80746e6bd606d8ca71
    md5: 91b8b05c042f5435cacbc28198958a39
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0236417ca91769a0372b2a721801e1f1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_solo.res
  hashes:
    binhash: 08df14d92a26fcc99b16b9fd62882f91
    md5: 0e5e41ac8d152ca574db404b37509aee
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 24963619c544387a655a5d0c45225676
    md5: 9c26b81a345d6d3601544ba46bc12188
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 650b012790af46ad24bc89218fef91a9
    md5: f24754e8ce218f899f29e727249b7461
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_tracer.res
  hashes:
    binhash: 3cb1fc693b0dae2d5778979442e6c6a2
    md5: 465ad48f8041cd06fecca1a494d770c2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6652d6b5d8d14ecde58899608d390410
    md5: 6619f15c4f103baf0739a2a098218e4d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 107db662085da58398fc62cc49ff5a45
    md5: d1e94cb526920c2e433eecb34f05dd3c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 471cee2fdc58b09a985576366529c6d0
    md5: 3671702af57297b50174c7b3519b0a5b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart137/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ad56d9085b9b0344ab312e0bc6e54534
    md5: f2e4804e59c74e7f606ab719006544ea
