format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/atmosphere/restart_dump.astart
  hashes:
    binhash: 20ee6860309bbf633bc315ef3c2f18fb
    md5: 4f7bc1425a6e035868d3bac867fe0022
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/atmosphere/um.res.yaml
  hashes:
    binhash: 7ff67e627f5e584fb77a3c5ddd079499
    md5: c0017be82d604dcb4fd6fd754c568c5f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/coupler/a2i.nc
  hashes:
    binhash: e60f8d6d8b6003c0a640e1f8dbb5b721
    md5: 2fc811316c1af11aa822adb21a258a3a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/coupler/i2a.nc
  hashes:
    binhash: a12baf518a4ff538d9881f6adecbe654
    md5: f851ec1ae8269ed651f53a769346710b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/coupler/o2i.nc
  hashes:
    binhash: 03e330265948318cd138db88d492fe2f
    md5: 0e0fce0249fc14c3d9ae058fc3e67bb7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ice/cice_in.nml
  hashes:
    binhash: f172d3014df5663875b22558cb2ecb40
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ice/ice.restart_file
  hashes:
    binhash: ee481ce5f7367d6403c794e315303239
    md5: 8df73cecd42e979d435ee8c81b80bccf
work/ice/RESTART/iced.2873-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ice/iced.2873-01-01-00000.nc
  hashes:
    binhash: 38c184e06b7b41b10fe25f6139371192
    md5: 1469e761b3920d405bf9f28b66ba418c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ice/mice.nc
  hashes:
    binhash: 67aced5feeefb8f7d13a5c0cda0130d3
    md5: b1960dc72c8786847a7c17f5acf43b9e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_age.res.nc
  hashes:
    binhash: 7a1bf3ff8c9f5b2a4c98542747e36411
    md5: 7585337149532d6d9ddac3ac5c6cab4a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d0f0d9f54d05027bbde0c025854adcdc
    md5: f6bc7f88712400e151f1d51aba62f5c2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 56c1e86fe07dcdfbf8e6e6e84aba9957
    md5: 645e7b3df4d6d75c8038f4a84a02290e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_density.res.nc
  hashes:
    binhash: e589812c7466d0980726986211a1afb2
    md5: 88e5319f6bfeb0edfff7ac3db5a7c9ec
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_frazil.res.nc
  hashes:
    binhash: acb4f1c9a1f9139910d7135a22b4e80c
    md5: 94b8d6f1af5f5962217dae5ea85d3d69
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f476b7e6e06207629911cfa533c25fd6
    md5: 385a61c16f28b1bbe977d10857a6f45a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_neutral.res.nc
  hashes:
    binhash: cbfb690bee7156576646815d34da1183
    md5: ce435c2fd7fc060a40caade18220b5c5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e775f1d21dc14c16ec2e7731a9644280
    md5: 770d4c57679bf754a62281e508bb5249
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8bd35c0b643449459f3150b2a7b3b072
    md5: 8a2ae61c4f7be5b4bf841ad0f8ccc15b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: adb35e395cba1628b758b4b3c2c85148
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_solo.res
  hashes:
    binhash: 2ba0ee385066de47798d68ff6d25ad1b
    md5: a3bd48a704a79e5c2929c0273a9d8fbe
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 38e134aa7dcd1e74aef32eadf7bfc234
    md5: f9420bb823d07254bfcc867fa7a7eef6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 81e5ff60543a9694b750391103209c0e
    md5: 11e67637b051ef9e2a93237e4e4234ae
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_tracer.res
  hashes:
    binhash: 358651406a6bdf970e6bd7c2dfa18d8d
    md5: b4ff13436392574efbef6e82d2756b78
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dc46551fb3369ac783160000646905d2
    md5: bac8b62ca976ac4a673e7d3fa462f47e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 740186bda033106902507f857a288f63
    md5: 0d71ed96c8c929eaab38aad5707b1dfe
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 56909994bf83bb653c036afeddf78121
    md5: 5dd3189ebac08fbdca191f94607f8ceb
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart196/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 74f978576a028cbf3162c885d3b841b6
    md5: e27d4922bb8263fcd8975db54eaf3eaa
