format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/atmosphere/restart_dump.astart
  hashes:
    binhash: e637e9c98f8c405ebacab1ee3770765f
    md5: d2432b87064cae5d5a3069cf1d864f38
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/atmosphere/um.res.yaml
  hashes:
    binhash: 374367fa7315c92f655377aad523304e
    md5: 7e2a86a989a0cd7eceefd0474b658f7e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/coupler/a2i.nc
  hashes:
    binhash: dfb2b9726e8f9c8e057d8971ff413c5e
    md5: efce461d917848cdbaf6cc9e85f7453b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/coupler/i2a.nc
  hashes:
    binhash: 35b98ecfb5a6aa2fb5ec681dffe94d05
    md5: 7b0b7ba67c43c26c01af0a5acbb18e6e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/coupler/o2i.nc
  hashes:
    binhash: b1dee9d373dc692f2478c2960afe8073
    md5: 077c1fa0a5c4c55ef1d76a9b306b9605
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ice/cice_in.nml
  hashes:
    binhash: 42386b7e0adebabfb1d0a56e58123d3f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ice/ice.restart_file
  hashes:
    binhash: 4c22be16f848307a6799376ee34ed06a
    md5: bd069fdf2a10e0f04f91895bd3ef79fb
work/ice/RESTART/iced.2944-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ice/iced.2944-01-01-00000.nc
  hashes:
    binhash: 8fbd2014297040d412d2c8ea369163d4
    md5: 85a24981a218431f3eb7e6669d3a6876
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ice/mice.nc
  hashes:
    binhash: 04dcf63b33e4dc833debde58976249d7
    md5: ded7a819f32ec7616abd4506b4d50181
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_age.res.nc
  hashes:
    binhash: cf4b1f1321dbc5f857f70ebe77dfb4d7
    md5: c188bc8b7519d25aaedfc1f5e6821698
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bfb975e8313b678875346750c19974d2
    md5: 93677aeb5f49b6472e2d436a44f3cdcb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2fac56563957da8e478c75cafdf3a125
    md5: 5415fb87f960f5c0b6dce7c35eb5062a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_density.res.nc
  hashes:
    binhash: 97a665f01f9f2ec5000a8690e1cbc752
    md5: c919f89da436d77aa0ef998df27bf062
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2d57098b5fc2b3d5f914c7c3308d072d
    md5: d933c3a50bf93ccff5b2f44aa8d3d21e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a2f55619eff16f5dfdb44a9c051741b4
    md5: 644202ffabeff5d01fe0a8b41fc18a3e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8a8de604c7891b44a1b7bf210dfed13f
    md5: 03cd45bb84894af53dd740ede84e3903
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ac2229fc7803e5b80631cd2a57b7fa82
    md5: b2512a92096d2b3f9b7d08200fe8cbc0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 010fa473f8bc0f06d846bf75059e5130
    md5: 1b79d59c59f4a3b74111e2227d566cfe
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8b6a906ef1f75a03f9d174b4dfc9fd38
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_solo.res
  hashes:
    binhash: ccd972c99112a1881a7aeaf553b6d9e1
    md5: 2fc07ec62f30f2c4c5a3f7d2bd72d141
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 223ec983167ea580c03c1b94d739ee44
    md5: 28f344c974f7bcf46b1908dd92b191c1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ac47440c6711f00ffe5410ad585717f3
    md5: bdb31a0bfc08c5a403849a70f7df4a45
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_tracer.res
  hashes:
    binhash: 5029e3195da2b7f9d62b0a459d0eeef2
    md5: 0951bd2d598cc07f9de54b6b9802922e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7921da89a0638b7a89cb7d7ba54838b1
    md5: 7b55c7a752581b65c4310e017fadd21d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4c401226beff6bc291b7d90f1cd3a94c
    md5: d0e5ddb47603462ada428cfa5b09d3d1
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 88a06cd2380cadf2865eb126c0a00e90
    md5: b3d66902f562942ec983cd289311a181
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart267/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 919a95c70b1a4aa27eb38910152c13e2
    md5: 168b75b800fae3ebf8131a4165f7cea2
