format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/atmosphere/restart_dump.astart
  hashes:
    binhash: 38a49d0f841ca5450382f1a37e812865
    md5: 02d86c77fdf848e53dddfce108af7d8f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/atmosphere/um.res.yaml
  hashes:
    binhash: 9801b989e6a0e8d637dec3ee633a4505
    md5: 7cbf3aa21b1ca2a4d69f01690fecac61
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/coupler/a2i.nc
  hashes:
    binhash: 9f0b1a8e1b7145a180532e3730368e1c
    md5: 68fa1ff04b515aa741e94222993931a6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/coupler/i2a.nc
  hashes:
    binhash: e4fb593aee647535eeb89f4079d729c3
    md5: 77879c45dfd3ac19e72edfa5913c6781
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/coupler/o2i.nc
  hashes:
    binhash: 93b1a0e37e01711fcc1e9633611e82fa
    md5: 0e82a9166caf546c27fca584439af675
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ice/cice_in.nml
  hashes:
    binhash: 5548bf1ec7126735342795c460fe63d7
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ice/ice.restart_file
  hashes:
    binhash: 4555f51b304c4282963414e657be94e2
    md5: ad76711b1395a0c513820eb5acd46d60
work/ice/RESTART/iced.2843-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ice/iced.2843-01-01-00000.nc
  hashes:
    binhash: d145ee5a4141799a21ae9b4c0f8f787e
    md5: e8529cbfd14cfc6dd5a4a0dfc40a804e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ice/mice.nc
  hashes:
    binhash: 7355d26f3c8c3c4c9d1c53d6b3131b26
    md5: 986f5e80c8abd4c5a60cfa1ca8faa513
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_age.res.nc
  hashes:
    binhash: 3a45e44b9588efaec548b36808fd401e
    md5: 3ab375072a6417f0b8e9390df72aaf3d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0ed9bb70b9c3c133b0fb0579ed4f1326
    md5: 315745f6b172028e34fa01c71b5e09fc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 965b39f4def5d3f73feab33aa79915db
    md5: ca4c2aed2eaa6b960928d71d0f313e45
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_density.res.nc
  hashes:
    binhash: c6ac4769d66c998051fa0cb903d9ed5d
    md5: 1c0b1e44e3ef9dd919dd2612dfb1afc8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 912ec219c9c05aa362833ccaaf6221a7
    md5: ef8b71bec0f02e7604a2e7750c32f209
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2d66c5effdc02da826b7a403879428f7
    md5: 5c199af2d012fe149241a7a1168106f1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3c78bdee63b203395fe57436e60c5758
    md5: 0739cf0324d75c7d13dc072018eea39c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a886f67e7f55031e1e5f6cb1137054f7
    md5: e6b90d0857b8c265387c882495432381
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1202f2d20da0371d696b8ec7b8d7c3aa
    md5: 3d6a86c5df8e54dd219d8892d0ee4c0d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 26ef53cf52f0d7e4142703ba965cc922
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_solo.res
  hashes:
    binhash: 1137c4e3da26772ee806880d14c86d11
    md5: ac8b4c46f79833be3bd82512c9f14ea9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 645c5f47785314d9644ab94296964a2c
    md5: 4583c630081665d62f2a13f2f98edebc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 79709d1a3476a1b1e70c4f38fd16b114
    md5: 7d364cfdedbcc9c769e3fb9de29e9851
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_tracer.res
  hashes:
    binhash: a72fb3759da41ac8aa95cace3964da1f
    md5: 8c12e13bad00ea28c5e033a4b1dcc381
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 695d66709f64b1fbf605358b21a036e0
    md5: 30cbd04704df301ad854018ecc01be8a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6ac6ae05c4da5c856b2e4c2b7fc99c4f
    md5: eb4e2cbf82ae6633fe367f3b4220e726
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 00d8d480c3f934c617e8218004702157
    md5: 59ffc56494c6f4b96df0b541ad7f7afb
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart166/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2fe95f61c4e792d84b21083a9fec7097
    md5: 7926bee02ad7d11565838c93ebdd5c16
