format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/atmosphere/restart_dump.astart
  hashes:
    binhash: 08b97aabe4f6e6af1551fee1e506f547
    md5: a21004be7b6a5964ea8cb9f26833f63f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/atmosphere/um.res.yaml
  hashes:
    binhash: 289891599b2c086b4808c66aade97e1d
    md5: ecff379b1556d5f332b6b376a7b9430f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/coupler/a2i.nc
  hashes:
    binhash: f3084d741dcd4e61ff76b2d715615ea1
    md5: 6fec84f8579cdc2cf6634ec7810ccfac
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/coupler/i2a.nc
  hashes:
    binhash: 20aac7bbe002e54455a23a7402d13723
    md5: 5aba1970a564b355cd240f595f32a133
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/coupler/o2i.nc
  hashes:
    binhash: d5db74cb211fb41495c6f83b045ccc59
    md5: 46ca940fb6bf8c1fcff31bd6f31c5cf4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ice/cice_in.nml
  hashes:
    binhash: e9fe915a125e5207c6bb2065f177356e
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ice/ice.restart_file
  hashes:
    binhash: c096620702ee336027f335a3a305c127
    md5: 05c279e43c3902c30ac84a07d9803915
work/ice/RESTART/iced.2726-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ice/iced.2726-01-01-00000.nc
  hashes:
    binhash: 428b19480d184ee3a07e585c3ae7e8a2
    md5: deb6898a2b17d7d968fddf3e2c665aa2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ice/mice.nc
  hashes:
    binhash: 10805e1d5a305b7486c7a36387be188f
    md5: 6c8b1e6392eaad2153992c69d90b97cd
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_age.res.nc
  hashes:
    binhash: e2357407cedbf43cff60b731900c8552
    md5: 6c032aaf75b485273cc32917ac216eb9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 17db4a87d1877ddce14c3e3cf48438f5
    md5: 535235721b1ceeb2f773a25b41e4058e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c36f974165f1ca1424272fb29dc7ce0a
    md5: 6e4ab5f9c58ac7b6046e15cfcd777d06
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_density.res.nc
  hashes:
    binhash: ca5246956e3e12f2ea4b3bd4cd3bca43
    md5: a5a62f31dceeb88dc5948c9e8656021b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9dbf948c6a460aa48aeaa1440b89e084
    md5: bc593534e2cdd775011b3f73d3571f56
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 083bd4609b690bf2a5bea66da48dd80a
    md5: 0f0e523e8895900293cacc1e48d15b91
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a90a92d5fff431d1ba881f1ff2a6dcf0
    md5: a9e2a7f0fd7fbcde1fed76652e474911
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7fc2c821c24d6ff1a88d8f7dc85f2832
    md5: 70065f7b62d08d297f0ea66b5f90af6c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4962814d6959d2fde694405ec72a116e
    md5: 44f6c008b7ebbc15ebf4ee49e7398607
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0d67a857f0adaa38e98320b925f1c561
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_solo.res
  hashes:
    binhash: acd40f2a00236ab028468f6021e97256
    md5: 785bbfc07a629bc9d20f4788fbbbb68d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 548fbf47a15d3bd7e69cf6c313a22ee6
    md5: 8ddebf61c0ba0b3f98227dcf5efcfe1f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 437da3e0941c5b0e9eabad57e56c4cd2
    md5: 81aba6738615c6b95dadc890d4e16a63
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_tracer.res
  hashes:
    binhash: 6f0e4ab811b2a24b9bcd2679dc8061cb
    md5: 7d7301f1603124f65f1b45bb7c2eccc6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9b6fdc9cbd8d2ceb0dfda6c28cbf58a9
    md5: 452f094cb840df78bd77e09d12d2ab4d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: dfebbb4adb0a8bdd91a47dc0f90cc456
    md5: 0e786da75b6391452b665a90d3257ab2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 894da0dfb4e9b7931a25365555ac7eb4
    md5: 1210d804c50f339834a8f33c826d9997
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart049/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 03f5b7bc11a760b4fc97374cea5ae0d8
    md5: 3c6d1332f14685dc519dc6b6e5ce0424
