format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/atmosphere/restart_dump.astart
  hashes:
    binhash: 33cedce5817317760c40039ffe344b06
    md5: 4e5a323bac10dd81d0c7b123d22bfe4e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/atmosphere/um.res.yaml
  hashes:
    binhash: 28ad01ad8a1c8e5e6f52b763833cad3e
    md5: ca272a20fb42180d31c00eb21fdcc777
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/coupler/a2i.nc
  hashes:
    binhash: f85ad81200553c82d5f4dd022fe4e4c3
    md5: dad9cf71b8bf45f4e02fa02a8476b840
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/coupler/i2a.nc
  hashes:
    binhash: 1f8ffe9c6a144353fc1e3965e2a4ba59
    md5: 1ccca8a5254574ab6bc4e8313ea80ab9
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/coupler/o2i.nc
  hashes:
    binhash: 57c187dba44c0c1b36213cd9467888c5
    md5: bca5fb29aa3a88fb0249889973f3ff17
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ice/cice_in.nml
  hashes:
    binhash: b097365e112de3a542e0d8100d3539dc
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ice/ice.restart_file
  hashes:
    binhash: 9b4ee76bef13093e0d279ed8fd5a4e98
    md5: 86d2e7c3d4a0636565368e14c90a3ca3
work/ice/RESTART/iced.2787-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ice/iced.2787-01-01-00000.nc
  hashes:
    binhash: f0404ea1a79432230a4633d083b611d5
    md5: 757ac53066e9140f3b5acf2d98bd5b66
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ice/mice.nc
  hashes:
    binhash: 9d957e01f5c1fc8f124146028c902003
    md5: 0a699488542af8756b9ecad8ea9e9742
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_age.res.nc
  hashes:
    binhash: f052d1622a341314722e2ba10604438d
    md5: 15dc6df34d209bc3d23d98c8f4df702a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4d06bd2d48b5e867f46f329c959ae4da
    md5: a1b2bccc8ffc900b2ca22504ddb231d3
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f303035a5df8ca1786ae1eeb2f0e0537
    md5: c13e962d6074cf6f6ef5a04cebc85471
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_density.res.nc
  hashes:
    binhash: 844b75b9124503117ffe450b269379f8
    md5: 42120180e2968d44a589708d2f17feb2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c831f2304b209a187469c6f713786596
    md5: 8d09caee7bf210361df0ec54eee72bf2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 306d3ed04a34d79dc0cb8cc80485c8e1
    md5: 5aaf1f0edca02c4e5d0b98aa03d7f68f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a8be1ee52fa09759a648db9c4ad9e94f
    md5: 233a2f31f7971f3e7f789e22395955f6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0ad5741dc4bd9d37770329c10c9ce74a
    md5: ecca8a013d49fad3ed180b249d5fc1b5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f57ee143c38fa58099e876b975fd92d5
    md5: f6583da8aa050edbfd6acc7b9d568c4e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d5b0020d900109fda62fb965d278bcdc
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_solo.res
  hashes:
    binhash: 2c78926681ca504bbd68e0e4951f8d8c
    md5: df30bf4c41e07fe9eada1c5e863d0ccf
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e6f465814ce3e2ef2498c0c59481a45a
    md5: 2b50c7665a5e3aacc8cc89d7b8561332
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cff862d93e7c2ca093276c0989612905
    md5: 00601405c4f835e2e8606815c1807860
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_tracer.res
  hashes:
    binhash: 248261caf6a8bfda8e05b5701b952151
    md5: f8a5b5bb242bcfe73eff0d68312f6e35
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 570f9ae7783d4067d5345c38d814c196
    md5: 165b6785009fcbea660e761bf7c912ca
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cbe20e83ca85686a8c978568e4524641
    md5: e6c4e7d12a9e691cd770a10f12dab2bf
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 34d2e08a0d58451a3cd812636aca9c01
    md5: 809cea7d5b2c78417125b185a01d3c99
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart110/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e58bf7bf8f8a102b2694ee0d3b2390fb
    md5: 8ee3621bd3de9c1968115152205be89c
