format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/atmosphere/restart_dump.astart
  hashes:
    binhash: 3c984ea60afa01226a214a92f6d242ba
    md5: 2e9d1fcf857fd0976c0fb781b89f41c2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/atmosphere/um.res.yaml
  hashes:
    binhash: 22f5206908d455fe94b92635f6a43f3d
    md5: 74e9af7e4c45f4d4db85fe4b9c8fe574
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/coupler/a2i.nc
  hashes:
    binhash: 0773037475d99fa23b9f6a9e5b68b5c0
    md5: bb0f8a02de422f2ae29e0c7ea35929b6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/coupler/i2a.nc
  hashes:
    binhash: e2d4ec73f48aa10da8fda9820bcad1e2
    md5: d89affa941a633b74a694856ace04723
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/coupler/o2i.nc
  hashes:
    binhash: 622b1a2ec078da87fd1ea80f51fab2f4
    md5: 34469e1635bc607cfeedd485a48ad5d0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ice/cice_in.nml
  hashes:
    binhash: 751c3f000d35778ee53dd845e46578e6
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ice/ice.restart_file
  hashes:
    binhash: 559967f552c8869636c5f9f6528f672a
    md5: 9145c5c0c4fbafe8a86212f1c579994f
work/ice/RESTART/iced.2883-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ice/iced.2883-01-01-00000.nc
  hashes:
    binhash: e742c26c5e2f52cd338d68f43469a372
    md5: a9accc515a7665471a5bd0e64531126f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ice/mice.nc
  hashes:
    binhash: a27209fda594a11ae79896b76219fae3
    md5: f9207d8fb7247dd18d3d614d5bbd102f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_age.res.nc
  hashes:
    binhash: e3ba9d802a8515c6c2870873bb246202
    md5: d406b02314261a8e18b950ba31c317bd
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 51eaac5e185ca3a18f98b6766013fd12
    md5: 47183c90342ad7af7f1c4e1a659e7ad9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: da3b3ced3d994f96173de9eae92148bb
    md5: 7ad59652b5fe1d288daec71244672e68
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_density.res.nc
  hashes:
    binhash: fb99de04640a5b55a502c0779520c659
    md5: 0e91dcfdee40636883dc56da400e3b5c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7777887b19b041527c5f2ac9054686bb
    md5: 0cb2947f3571836b50b45a8cfdb924c6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e0afd84aa33fbce369281a5f744bd664
    md5: 45a1807d891348aa19961430ee237adc
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1df915f8c5e37d745cbee9048d56eda1
    md5: 2f14bfd6c67c537d47f5bb06ac55ef08
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ea16355697a4fa8af2225c5e0df40c4b
    md5: 3eedb7a2eb93c8a2e1c831f76fa12e83
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_sbc.res.nc
  hashes:
    binhash: da31ed408b425df6e63c09d8bce46971
    md5: d6dd245d785663071f55e5599f4c1752
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2337893dc06071ee643ffbe665692737
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_solo.res
  hashes:
    binhash: 73bf6cc8a4639971791c23962f3af32c
    md5: 96a7a0a8ee6e316f582b999a0fc5e888
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3ec91ac7c64a6d247fa5f5c78ad69d66
    md5: 7a72492ddd49de7790c1702a95d81699
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 23eb8565aa83071dd781b826fff0c901
    md5: 159d7838c384b0904b7957ca6c35a4ae
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_tracer.res
  hashes:
    binhash: 4aff78904bd5b3f0032a21383dcb85b7
    md5: ef17b4eecbcb87021063549baff7f721
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9df2228abcb282ea06f129ae078d7445
    md5: 253fc0038a25226d9d036e94b62a9ca7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 700392ca70540f9ff2223d3a44fd2962
    md5: f3d611b28174acbd41d574be08675cf7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 046747ba08e80126772221ddfbb0e913
    md5: ec02c82121c228cfaa336b996076a96a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart206/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 65663fa51985a4bca725b90e3a20e700
    md5: 3537cfca45d64da69e7259fa7638a9e8
