format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/atmosphere/restart_dump.astart
  hashes:
    binhash: 619bcdc89e0c66e9f3ec3de027c7e847
    md5: 2c9efa44ed9f15dd13e26a695e6cc9fc
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/atmosphere/um.res.yaml
  hashes:
    binhash: 0d3bb927bbc6398d7c66dc9cb32e8074
    md5: f4dc7839ec8e3527e04a05915cb75b9c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/coupler/a2i.nc
  hashes:
    binhash: 545da34cf71dd7c2f4afd9622a6b551a
    md5: aec66b58e1837388b4ee390fa8da34fc
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/coupler/i2a.nc
  hashes:
    binhash: ea440185b06e9ed059d3a0a2df23802f
    md5: e231d6e2cd94e15b84c8d8b444def322
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/coupler/o2i.nc
  hashes:
    binhash: 5577852f8543b4863835c8d853589dfd
    md5: 08cc4b291d87c7e427eb0049abd06d9e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ice/cice_in.nml
  hashes:
    binhash: c42bd4b3bf30768004d516d795b244a0
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ice/ice.restart_file
  hashes:
    binhash: 4644920bd1f033d0debc46d01c5ab37b
    md5: b1b550670f730fbfe17fe94e1ca16e45
work/ice/RESTART/iced.2890-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ice/iced.2890-01-01-00000.nc
  hashes:
    binhash: f4c368c72f770fdda49302c97b44236c
    md5: df8f7f3c2535e280370075c109951028
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ice/mice.nc
  hashes:
    binhash: 5f01389bf84ad5cafb06ef8832dbcd28
    md5: 5dc2be8c5126dc014f9e9b7fde95b302
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_age.res.nc
  hashes:
    binhash: 89adb26c3b73d6cefd828af3d467f8b3
    md5: 79330a2a765ca8c845f0afd9017b0cf9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 323ddf7784784f3cb0fc4d4d50da3a25
    md5: ab67c6bd591f396dad65ade1cbe4dc9b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4a3df88792e0a55fc59e07e232df0b71
    md5: 81928e6b63f2ecbcd1e69fefa72f6b04
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_density.res.nc
  hashes:
    binhash: 795e126834907b6cb19882544a50d224
    md5: c94324ea7fe77ec41e1c62d72b48101e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fbada9bf2491d1e8c6d096e84820719a
    md5: 21a309812816c6a729490b98a34f6222
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: cc998820791a83df6bdc63742fa0bde8
    md5: fe341667f2b5f53afff06251555eacb0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 08e4ee215d80c58c4b92cdbb616a7ba1
    md5: d509bfa32700dbede6da42b870861edb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2d7d8d970e4a1efb3a0221765b86b220
    md5: 8dd769b665089838035bc6b99d9c4668
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7db6f3542bb1f01904a13c0c2190f39e
    md5: 531eadb39eafd14f219feb01d5cc811a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 621e29b5e3b3d3e4c2b9bb445c718d03
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_solo.res
  hashes:
    binhash: 65d1327ecb9a90fd4caa3d53da57c28b
    md5: b8adc29a68fe9f5527dd522612cba3fe
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: addb498bd8a8629a3a02e6e6a6d9fbc3
    md5: 1983006d25dd9f5e754ab010dc51d0b4
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 33854f7be60979c4eb8020ee2183b0d8
    md5: c56c7e18e638e2ad0b780c43935213ce
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_tracer.res
  hashes:
    binhash: 35868b486797a0eb1ecf2da98ae2719c
    md5: 09e2bc40b67048f7da0ee79f5ee4a02f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 97cc5f3aa3084b48511bf246af77f753
    md5: 918af9ac59f90d81930ba9ffc7720995
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2db5a6c67862f9a08b92565972022c6e
    md5: ef180a2d5cd295a4cd6d30dde4e86b9e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7490ffa1755c7d01270f8084a0eed78c
    md5: 22d1430435d5619752b83f244df2e48f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart213/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: eb2ae09462e54e5a74031fab9f2875d2
    md5: b2f5dc2ed6551c85586923ef8c44c85b
