format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/atmosphere/restart_dump.astart
  hashes:
    binhash: 2b447dd24db68e68615e1fb19407d03d
    md5: cc7c10e462248643806c04a8672b9ba0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/atmosphere/um.res.yaml
  hashes:
    binhash: 25f5b4b81cd5c7e279e29cf6fa53f668
    md5: 1f5ce68d00e2dfaeebddea443b4c43c6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/coupler/a2i.nc
  hashes:
    binhash: 0443a68a602ab7c2a0f7972a601fffdf
    md5: 490126221b44c308a8f889cc81ac9a90
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/coupler/i2a.nc
  hashes:
    binhash: 33461e56402390f51c47a5c6ba6f94ce
    md5: e5c24db4fe421a790ffaa11819d61796
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/coupler/o2i.nc
  hashes:
    binhash: dc828452a938688b0032b5b6d029a7da
    md5: 52b9129cec9334290978510f732ff6cf
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ice/cice_in.nml
  hashes:
    binhash: 7678a9ad7bbfe192a2309386a18580bf
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ice/ice.restart_file
  hashes:
    binhash: a5749dc6f71c34e995ffdc59d19c2eac
    md5: 6dbfd95e1abb4b20f5a2a8d92049e6bc
work/ice/RESTART/iced.2897-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ice/iced.2897-01-01-00000.nc
  hashes:
    binhash: ec4e91a7eef2daf186d52ea696d20b41
    md5: 7257547a1ab2c468b050ae15cc6d17fa
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ice/mice.nc
  hashes:
    binhash: f17bc03516ad3a6dddf3972bc0d1c94b
    md5: 92ea489fc7296d18eb2afab74caec92f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_age.res.nc
  hashes:
    binhash: afb8ff1e0beabc01a6a0d6f4361b9b73
    md5: e7c4f33ea80d6b65e28fbd7082dde801
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 71ab79e07148c7fba623334ab7a08d04
    md5: 10097dfaeb3e1c36afd943251b583ea6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a3a9f105f744ddb0c5f893db4d72c18a
    md5: a6bda6f622e6e0228d80c9c3cb2b1929
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_density.res.nc
  hashes:
    binhash: d63cb340ecb90d6ac960c549e2b58c76
    md5: 288101fe8fc7d3cd608c406ab9600db0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e021ae06a9b577cb98c4e63121721d4e
    md5: 739eb49fa26fdfda947dff4b76bcb373
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bb1692209fa5fc3f5448a30ca8d85849
    md5: 29db5271af37598c95038abb8c724d70
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f48d20afab4659666c6cf1360deab727
    md5: c4a124bc97090b5c40d93b713faccafb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 87410ae751200d8519becf9d821d80f0
    md5: 126aeecd3032579361368692d85a59c3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 070e7b5537aa0e8f53d649a2491fdbd8
    md5: c49b955a8618c050625f446e3e48632a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1e4234a6975fcaad8ed0308b1cbe1eb5
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_solo.res
  hashes:
    binhash: 72012f83dc00e452fc1144e25d74ce26
    md5: 5b4068ad740a6a5c94b7eee8b37aeeb6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2e047a6b701c2e197d748a5351a4c4cd
    md5: 6227d78a31f1b1d38e9838cb719b83e1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1b7c04463334cdd71019737d473972d6
    md5: 8266436e8240cb7181df429b10d86c98
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_tracer.res
  hashes:
    binhash: 28e77f438288df8bedac0a755f907d1f
    md5: 3154c184455e05e20ed4dba450e8dd72
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4c5f7157e16ee81a54bf39babf7308fc
    md5: be186ed377fbb73c3eb729a2074a2bfa
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 826b14dc75baf23470deb1a34c61c688
    md5: 08ceb216ebb91967e8ded287c78fa7b8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 492f8ee2b2d069bfa63cab842b2b2081
    md5: 02390730cf3a14fbac609d75dc56d382
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart220/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 84cdd6f3fdb42658e443b42a3564cb6d
    md5: 815d40fe624b5e2e767c7d4b29272745
