format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/atmosphere/restart_dump.astart
  hashes:
    binhash: 3cfa17bca598825e48b67ea7840eeb63
    md5: 1cb371b037b53487ebc45d0c86ef7e6a
work/atmosphere/um.res.yaml:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/atmosphere/um.res.yaml
  hashes:
    binhash: 36730387d7b2806781d861f1198ba556
    md5: 8eabaa1923304b04e47de3b65614b6c8
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/coupler/a2i.nc
  hashes:
    binhash: fe95ddd9cb2f9bd79fabb8e2703911b8
    md5: 68756c87766cf2c33f88c2278466d529
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/coupler/i2a.nc
  hashes:
    binhash: 1c35782fa3caf0e03c1dc3af2cef6592
    md5: 992100c10f095e3849688717ad6a8d4b
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/coupler/o2i.nc
  hashes:
    binhash: 2cd33344e8ae0827b33ac2086471ec59
    md5: b833167d77b9ce6a624e78ec609b6901
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ice/cice_in.nml
  hashes:
    binhash: 1df0ccca2be31e00b91cf3f27e272267
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ice/ice.restart_file
  hashes:
    binhash: 874466fcad94b3a1803ec7afb7b370d8
    md5: a2bde2f3cc43964ecc86823a5d7750f6
work/ice/RESTART/iced.0553-01-01-00000.nc:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ice/iced.0553-01-01-00000.nc
  hashes:
    binhash: a7a027916c03fdd4af81679ff9921399
    md5: 4aad2a8d551df53393a549724591fc18
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ice/mice.nc
  hashes:
    binhash: 7356a7d8fb4725d4d9c02028125f73d5
    md5: 1f65d5432284d8b47a194a398bfef556
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_age.res.nc
  hashes:
    binhash: 8a92c0a605faca5ad1fb3be3c8f2fc19
    md5: 04c81b5d5ccef94f7c4600ea9908ce66
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 64521698ba0df913958cc1f43504e5b8
    md5: 20ab36268adcd8c45fb9a427dc86b9ab
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 53d0f591a02ebc3565e9e253238cdbe3
    md5: 20832711eb1bdfa013e1ce15a5e4e182
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_density.res.nc
  hashes:
    binhash: 37cdc157b48d75507006590bf8a16b54
    md5: 379befe1f796862a7f564e2e9c3941ae
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f2e8c4d890cdf50c06d1d50ceba42e7c
    md5: 9076243f8eb68f0192ea68c3d66c9ab2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: be37404f752385fe5146f9a61fadfe1e
    md5: 62d82bc9fee9c76e564821c272271bab
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 98cc4427e16b12e7e518008407d396ae
    md5: 7fe0ddb59104eebc706f4ccf8591e86b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f898b16d26b665de897448374de1765c
    md5: cf05b67322d877d807164882905b0e2b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 110749938e99a91d553c426209b6d8fb
    md5: 17cec787b848ccb6d80adc82a44c72e6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 720ebb40187dbe3c14a69f7f22446bc4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_solo.res
  hashes:
    binhash: 2e6b2084aea7ac490165b872cb9b6bc8
    md5: c24135a0a21a77788beb9bc0cc991fc5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bc51c2f6d0b2605ed894fdfd98f588da
    md5: cf2305d0beeed93a9eb4f614d01a843c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f916458169bf1c6e3a20d67d8d7fd00b
    md5: 1b0358f95d63cd1ec09a1ee80bca2dbd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_tracer.res
  hashes:
    binhash: 98c583b01da3524b81d1cef676ee7ef1
    md5: 667b40b14402e5d924c17ca432e4050f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1ee8dc057085338475a71e55dfec2791
    md5: a215a5a4f3f8cc27563e5b1c3bd81851
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f4ba9529baeb119d7e4213bbda762b79
    md5: 6163a09da3e678915bdbfe2849f95384
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 865835ab708c403a7f9a2f8995677946
    md5: a7c400b9c250ab5a1a626a3b74fb87e1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/p73/archive/CMIP7/ACCESS-ESM1-6/spinup/Sept-C/restart150/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 66e48198ef980321ad557a0bc3af40d9
    md5: 0ab1ea5cc5be0efc71a9fd97c03f4392
