format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/atmosphere/restart_dump.astart
  hashes:
    binhash: 623c665ea7cbef15e5a39865cd586d95
    md5: cc6a9f140e90f7bccafc1b5133101130
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/atmosphere/um.res.yaml
  hashes:
    binhash: 7d9a4fdd85b2a0166a70315fa1734535
    md5: bf5d0b1bca607d1f476353148b937f7a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/coupler/a2i.nc
  hashes:
    binhash: a1c5d6134494a730902b3c435e5aa336
    md5: e375ad17e0537e814244de178e85acd3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/coupler/i2a.nc
  hashes:
    binhash: c2d52c22a6a908e4a4d012e30c250ae8
    md5: bc6f4a02999eb678a1379962e17c71a3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/coupler/o2i.nc
  hashes:
    binhash: 3e6737a6848e5ac9132d85d8065f6329
    md5: 47463dd92a0e457086df05d6662233d4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ice/cice_in.nml
  hashes:
    binhash: e99816fa107f80136f11625855878bcc
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ice/ice.restart_file
  hashes:
    binhash: c3dff5d56ca87cae56695a3da7bead83
    md5: 7bc376c30becf36c5653a2045135f348
work/ice/RESTART/iced.2852-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ice/iced.2852-01-01-00000.nc
  hashes:
    binhash: d7bbd8074f0402d46e162a8aff0ee423
    md5: 8267f2b8f19024195825698950abcfbe
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ice/mice.nc
  hashes:
    binhash: fb9c5c2e0d2e620672fe71298b44448b
    md5: 2e069e8cc4bc8e5b6ea48a08c7f5f332
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_age.res.nc
  hashes:
    binhash: 8121ee4386717e3b757d2fe6d4a1e358
    md5: 64b2bd46fa83139c2c115dbc8dbd5810
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cbdbf51b264a01879d657db3d5ed6c36
    md5: b22206197153c05cbff102c03ba587d8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a13baf0e8f5404ee69d6b71ed3da412c
    md5: d2c9d2af762a5ee5ea1542eb54c35864
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_density.res.nc
  hashes:
    binhash: 689791bb8f5a6bc158b63ea6fd975f89
    md5: ee2d608b8891095f7381df0b5bb26048
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4e8f3f537a9324c7aba9d122a55e911c
    md5: 1fbcffd571b98c35c75d97fb2acfc8b1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f4699a141721b1d82dc11b5ba0f6dd12
    md5: e2592627873c9ed762f3f5d787caa95b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f32267e2060775c06139b32df5443877
    md5: ea21f1f58618e835867e84ad8c0ce956
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d7b69cc5e7f35bb03ee64b5fd5951ce0
    md5: 9e246f8021637ad84c5551199db0293e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 25a0d094355b56f872e90b5e0cb1be17
    md5: 95a28a5491a4af03a96b0d4697b37a59
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e9e756bf033a3a32e0fbfa6b9aa25a5f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_solo.res
  hashes:
    binhash: 8739c802b00b33b2c58ab462d5aacf2c
    md5: 5108d89f07cf38ba50fc3623b3367688
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ec53f8ac683c53144788ea6624fec1b0
    md5: f2652086d0f310a2284e7f8113eea1be
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3fd469b7e5487e8cda9a4f9a0b322bf9
    md5: 8ad6ad7b9cbf93eda85d868442149a8d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_tracer.res
  hashes:
    binhash: 5ea5209987a9bc6ae36e8a2f1a45b715
    md5: 5e0e345d2affc99f9852db4100533114
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3aaeb55f188617b532252ac55172e2fa
    md5: 626a23cf66df9599461be666250b5fd7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9893707b8247a1dd98209efd0fb71dae
    md5: 22e7980a72fce5187ff0886844ef70db
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 557c451b852f816cf669d7d43a4b7820
    md5: 7cc441578685408e5edacba59d71d604
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart175/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: da0c713db126bda4c60010afbe78bb81
    md5: 95243aabb73a48f58ec31ed19fc15d3f
