format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/atmosphere/restart_dump.astart
  hashes:
    binhash: 737aaaaa8d78db2b782a0b81d323b992
    md5: 6dd56ba66c6e8e07091f80fb1660ba31
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/atmosphere/um.res.yaml
  hashes:
    binhash: 10f7388d979b9567ac40b959d3b8b13f
    md5: 19a972a68af80f04d97227e82a4c69be
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/coupler/a2i.nc
  hashes:
    binhash: 021f29a3d08b16fd308c144fa83985a9
    md5: ede29cac0b478bd900f6deaeb03d859b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/coupler/i2a.nc
  hashes:
    binhash: 9a71e0cf9464b9e2e8221d65b829ddd2
    md5: bdd4efec493cc346d627012da5ccb3f0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/coupler/o2i.nc
  hashes:
    binhash: 8eedd36744fbec7acdb24e79c4ecd211
    md5: 71b3352e97b04a3907dde245f5289fda
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ice/cice_in.nml
  hashes:
    binhash: 91154771ca148c4fea6eaa6d8376c55f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ice/ice.restart_file
  hashes:
    binhash: 7ae76b34539dab4fe178b8feb91f4f3a
    md5: 7a310ca245f82242986d40fcf52b6636
work/ice/RESTART/iced.2853-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ice/iced.2853-01-01-00000.nc
  hashes:
    binhash: f3791fda812822630420782a1c2c4268
    md5: 3e9092c20e19c037d65617fa9e5cd5ae
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ice/mice.nc
  hashes:
    binhash: 3c2491c517b3aa2b5a6926bd30ec8a96
    md5: 887d1f1320c7b9a305e0e64bc9317867
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_age.res.nc
  hashes:
    binhash: f3d6616a4b3f33d1b0a15250f0fa13a4
    md5: a004284f8e188b8704fa44c2ce9b93cb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 012274200221fc306b8b5a87b09422c9
    md5: ce87c60c4142e3467eb80f9c02b34d07
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 88e21de0fe37d72e6c2a00e075f30b3c
    md5: dcdcba1acb34fe10003ddd63a8584261
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_density.res.nc
  hashes:
    binhash: 3fa265f3da7e9b5391a7c1f909be4eb0
    md5: 0a1e2b5eb84058f6f0d9faaab5b737ac
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ba4eb522a484d67d2fa72f989e47f32e
    md5: b615399917a1099cf2b05490e50f4651
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ce6502b6881386f8d317d0a2fbc88693
    md5: 96fc9bed94060263c92b84e6f4a787a1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d4cbb1495e46a5934273147749baa24f
    md5: 44bdb5582f06a152c07f593a8e9b5386
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1f7105f0103b1f24235488d838603c7e
    md5: 8463a931f04ae486aff4d6f4804ef116
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 581c2c847f1229a3ac1b7c7ed0ab4bf3
    md5: 48fbd57797fbd268ecadc8a6ff731911
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 07b242f8651881f69d6b824930e12af0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_solo.res
  hashes:
    binhash: 47e7c3ecc22a8d066ec1dd320326abd7
    md5: 5ff09e3f796ea08ecd94f8822474ac07
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f298ef76218465a8d999b0c1fb1c5939
    md5: 9f87ccda7f0ec06ee4cd1c0b7547c1c4
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7abb58401a66e68eace4159f19aa9201
    md5: 589c84e15bb2cbeea5d05c1e786cc6b7
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_tracer.res
  hashes:
    binhash: 6e16fd46774b35b827b20cd20ba61c65
    md5: 841edd26cf28d465a30f5387f7e63e02
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 913d1ee4edd5d4537d984481198893fb
    md5: 51bbcc6c85e015df45af942e24b554b8
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 254ea4ce6812666a131d6b95aa486cc9
    md5: 604333f8fc2d8cc9cc86cddc5c136d58
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e88115665bf60fbe11e1b38f11700ec6
    md5: a4914142ca09d517a03411e0e75ad5ac
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart176/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9b7bcf88b4ea951b3d6bdd6c64f8ad73
    md5: 5e966645c8e14e2e788e839c2e7709d0
