format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/atmosphere/restart_dump.astart
  hashes:
    binhash: 00ba2bddb4660f133b56b6c732a83de2
    md5: 048e7e7a712faabba5d4b6c1c79e5ac6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/atmosphere/um.res.yaml
  hashes:
    binhash: c8c7160af33314d5a405910dcc938b19
    md5: 72e09fc4455acc92af1a64e31aab225d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/coupler/a2i.nc
  hashes:
    binhash: 29b79841fbbf9ac20bad14b919e89328
    md5: fc9c8323e8eec6c2a61a94bef5ab0e68
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/coupler/i2a.nc
  hashes:
    binhash: 4e1a1572d7d9d1132739086cb1e25901
    md5: 711be3696c1e64aa5393367966215e01
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/coupler/o2i.nc
  hashes:
    binhash: 1fa703227907faa9b4ff862471110a43
    md5: 2bedcce3b467a37e47a834e9537f4250
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ice/cice_in.nml
  hashes:
    binhash: feb518b7743c288ca1db1beaa4e18b42
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ice/ice.restart_file
  hashes:
    binhash: 080c8002ab1df633b42ff21f42be480b
    md5: 9cd5796e1f1b74dc7518da06560b76c5
work/ice/RESTART/iced.2929-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ice/iced.2929-01-01-00000.nc
  hashes:
    binhash: 8d1eae9ff8c1170e9bf3689bd6afe39a
    md5: e346e8863590729738749ad2eb3f4a82
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ice/mice.nc
  hashes:
    binhash: 7ebc10394899c621e5c2084b412430df
    md5: e6ffc484770273f71795b46f6b52a28b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_age.res.nc
  hashes:
    binhash: b6917f88d6e53626a6f896b4c7a7361d
    md5: d518ee07cf41a2d393f6e51ef228b8fb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7b71d03ee46ad7280c8750eaa6a8beff
    md5: 64d928e88f80d92abfe66aa140d01cf7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5119bc0807bda0406ef0437d413a4d05
    md5: c68961d1e8c59ce85bb8fa599eddbecc
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_density.res.nc
  hashes:
    binhash: 6a484a5e8c30b0f02330de858a522d56
    md5: 55b09b95b570826a77397a9ea1966a8e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 46659914ee5d568c9fddddae54d95291
    md5: 3a075c69d0ee97fb02ce017d4877d954
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5302fbe8d59f8abccc8c8ba4fe06e0de
    md5: d3da8a468ccee34b806c8d02b964294c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 879746f3754eab635c473496c30e7e0e
    md5: a2f42ff127d3b867bc1b59abf1fccb6e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 952bedcb72f6f802026daad1b6bc8888
    md5: 20293e07e2ddc1ed5d025e72cc5fbda1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d063b3d619352717ec256f5507ed4bcd
    md5: 50fa8902474a5f535ec7feb377feec09
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d4e14339734db598d027f23a1e41288e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_solo.res
  hashes:
    binhash: 88b2456ced6fe206a7b173b50fb35e5a
    md5: 1078a6a5eb03f220204291f327cf0e31
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c77500c0c86df5300b62049a6764a79a
    md5: 84f01f5a58ef3b2892ac524fe3928bb7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 157733904b293c143bd2f3b937ae3575
    md5: ac35620d9aac80181992aca5b2f0c481
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_tracer.res
  hashes:
    binhash: 601c030954c2249627851cfe3f435f02
    md5: bec222bb6faee85344536420b83ada62
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d2c3ad8f604bea1ab3bc58060e67b6be
    md5: ee9976725fe021cb2a893d2c84c2ed33
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d0c5f5d927c65b2862c9f58526c461f9
    md5: 4897674595c11ee601fe66afb4be37d4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: bf8473c058e6b51943ad739d8e8c72bc
    md5: ac80bb9fc9155465df5a86063d1d244f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart252/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 022eacfc56f7c4efccbefba2755431bf
    md5: 9ece64916d7ccc6cd0b50798cf2cad6d
