format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/atmosphere/restart_dump.astart
  hashes:
    binhash: 308515efae02e03c384a4021e0b0a91f
    md5: 2d0386b0a129a456062982982b75a555
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/atmosphere/um.res.yaml
  hashes:
    binhash: afc4d7bf2cfe8d03481eb450282fc54d
    md5: 5e3e8d09c106f2d2920d4980e636c72a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/coupler/a2i.nc
  hashes:
    binhash: 6629bf06adac1a816cc8c8ce715fbf64
    md5: c2ded327a78d4379e6bec6826ac38b1e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/coupler/i2a.nc
  hashes:
    binhash: 5049aad1ce6a1b6eea52b1fa0983fcc8
    md5: 63c4479aa7c82b25c1290ce810a46fe1
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/coupler/o2i.nc
  hashes:
    binhash: 1de82efa09a757d1437e4ff530042d52
    md5: 7e933d7efaed8e8fd780a2963c90c8ce
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ice/cice_in.nml
  hashes:
    binhash: 365fab42b01b6368f14d1e33e6f44e41
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ice/ice.restart_file
  hashes:
    binhash: 3a2ebccb99b07c3fd5ffeb94b75e22b7
    md5: 128cecf34a10796d1a0634e6e63d85ce
work/ice/RESTART/iced.2771-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ice/iced.2771-01-01-00000.nc
  hashes:
    binhash: 2f5aa07d0be76b8f552ece2457e96708
    md5: 94ff70eca34ffe5388ad71969c4e8be1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ice/mice.nc
  hashes:
    binhash: 0c8495e76919311635e0c4c8b90f7e68
    md5: ac4ffbcadbb0e6fa4aff4c9ea208f45a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_age.res.nc
  hashes:
    binhash: 868bac3a95d4cbb1c407f645e0c096ea
    md5: cbf399cb62fcf501167b3e0bd7517307
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a1ee7b6bb8cc58dfd17225583612dbd7
    md5: f0f26764bd9235269e7cbd5450af18b9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 375438b7b8b884b26ec51fb61cbbecc3
    md5: 658be38c7ca5acab848b480373a8a72f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_density.res.nc
  hashes:
    binhash: 82cd473a7e4bcca9da676a3e5e1aee30
    md5: ca880d9ce6d99495c495e56d8ec9fb87
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 470f073d0c52e3bbc70793421322e496
    md5: a919eeadf85b23bee8fd7c3a828a29d2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1dc30765f791a6cca76c76d010c67502
    md5: b0b3c21afb121d3eef4255c14bc42409
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d085607c54f62f1e01e783307338f668
    md5: 2a5797f7c8735297a2ce88f764cb38ce
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2bd81e9424f93e87e281a55650653825
    md5: a5a3e317eec35498a492d48a31093c5f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 69e5501b1f15b5ff0cc3387ac135dbd5
    md5: 2a4d349b1cf10940bcb0da7898560cb8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ea26e60be21dc2ca48d9633a71b4cf6d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_solo.res
  hashes:
    binhash: ad57a0fa56c17a1146c4d95282c64e95
    md5: c99279efe31df282935cba3730a51dee
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cf416598ccf1edc1d4810665e591a8f1
    md5: 1d0436aefb32fd8fc22d18aa1c4cb664
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 77f47f8f810f19f1b290fc55e44ec003
    md5: 00f301ee2e4a83437864b28923659040
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_tracer.res
  hashes:
    binhash: 407880bbac06d6c73ab207e746a4e322
    md5: 246d079b556072e8bdf44ba6f913defc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ee737f5346ee30cbf4f481eace4a98d0
    md5: 5c6971bc2da6defbba38ae4cf63ba7f9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 744616438c4dbfe3c7ebabe4f81c8451
    md5: a6e44f8f2a9e24e9a7dd2610e3e71eb2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 12f994b04bb94f4f25b92cffaf1111f2
    md5: e01844ab91e655bb7d1a0c03b5e9e078
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart094/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e5aed65309d617dd43a91f6d87858300
    md5: 7b203e31ee1a58c7e914d02a782479d9
