format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/atmosphere/restart_dump.astart
  hashes:
    binhash: bab9d1d62865b9b9de15e58122cd8183
    md5: dba8b84d688676c855db72f4247558ee
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/atmosphere/um.res.yaml
  hashes:
    binhash: 1b26532e7dab264eda656ceaa5901413
    md5: ea73ae9247fabb7240c9ba779de87a34
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/coupler/a2i.nc
  hashes:
    binhash: 527c4e358d74b5b6d8a6680e77eeeabf
    md5: 544eb3d357af9aae073d232ac47e432f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/coupler/i2a.nc
  hashes:
    binhash: a055996075002cdd390af09983f79e16
    md5: 72c4051771493b17cc1b917bb374da9c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/coupler/o2i.nc
  hashes:
    binhash: 7c51166d8e3f82cfe852c52a38a8f6c0
    md5: 96e1d96b4bc6f514e55d6e1f583cdcdc
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ice/cice_in.nml
  hashes:
    binhash: d11c652bb04562e711537d67def8cad8
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ice/ice.restart_file
  hashes:
    binhash: 53cfbce1c31774e8ac132b1e60167063
    md5: d3f17dcf97f7424ac11301cb52e5ee8d
work/ice/RESTART/iced.2720-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ice/iced.2720-01-01-00000.nc
  hashes:
    binhash: 4aa35ee192a1df8beb1f53849b98b975
    md5: 686fef2dc565a4dfe40701631095440d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ice/mice.nc
  hashes:
    binhash: 475f408c5419738cfd9d99731a188a72
    md5: ae605c9bc084267be82fe07ae1aa6f73
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_age.res.nc
  hashes:
    binhash: 17b410a7814c215d56a5ffcc82debc45
    md5: 3aa77a211286aca561f081e3efc7c42a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9fb6d8f9cefa2c07e4cddb2b9c10ee54
    md5: ecab191c25c4104fb60621b850d2f1f7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0629fe795fb0d488465657d15fb7bbce
    md5: dcecdc6d3afd033cd27494a796ea62af
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_density.res.nc
  hashes:
    binhash: d4d653ecee2d9b0cb7c5dcb2c910978e
    md5: 726aa88e49c902fcda40496a90d8b6cc
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 89a8564d714105522611ca1db4e8505b
    md5: 5702a7cd1310500b6ca74d21a3d62c76
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6d7d1d7eab169dd5fa9b1f2eb3abce07
    md5: 2cdf8af2ea5cf56ecb68c9ea8ca035c9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a6e28615e40b9b74954e193ae14f2c0a
    md5: 62f76b50ed4a32e3cf6676bbce80c5f4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5b5c66a66728d8f5a6164fa0413fa623
    md5: aace005d9aeb48f2bcc9d05c5620a211
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7cca7d6e473c12e46de5e08e3c6eb271
    md5: 169cba1bba3398198e074a81878f73db
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 419b247089a2a96caa253d1dda73b227
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_solo.res
  hashes:
    binhash: 0c931da652d244f4f2118809fa1ae385
    md5: 8d920524c29f34b270a321e4b58252f2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6c1aed5878c5e2f6b48fa4753d8f81eb
    md5: 1d2bb1ef5f8908d555b4e63645a05836
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a3478ff6f87fc1093cc86d8229eb3203
    md5: f8a1d1ca9faa1c2db7fc43c0f3d5d505
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_tracer.res
  hashes:
    binhash: 9af028994b9ded682bc37078c2693af4
    md5: 1fb14763311f2e9a544d5e8ac5d93736
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7688cac8a977ec245fd31f3bde09bd4b
    md5: 9e50c7090f9422d6adfb5a9a3e8df678
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 983c75dfaa2ab7408c6a171bd2f7f4b8
    md5: 7a4063cd6959fa3184d3e4c6050e3a6c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d356d4d8e70fd5342d5567f532e5d4eb
    md5: d97ab520285a80b94781cea13f82950a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart043/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fca8cb618f09f9a81bb869d9890f11c8
    md5: 69f206b4c0a3ca4fad37b3abaa066a1c
