format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/atmosphere/restart_dump.astart
  hashes:
    binhash: 1fa6685721dd509ba89cc16943cb89b3
    md5: cbe0cc5172c3f8a6ed46a5af3a404519
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/atmosphere/um.res.yaml
  hashes:
    binhash: 00d4bf51b051e1218b29af027e656d66
    md5: 17783f075160c57567ad4ba9bc6eeca8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/coupler/a2i.nc
  hashes:
    binhash: 1d3e5b151bb7e8eb9e98d591e79714b4
    md5: 697e4d42af7e3c308600093c860e35eb
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/coupler/i2a.nc
  hashes:
    binhash: f4e8f38f7355d5f086db6f66491eda1d
    md5: 5d436c0fc288ba39e62eca93d7dc9477
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/coupler/o2i.nc
  hashes:
    binhash: 20e6dee461e65e79ca0413a7ea25f4dc
    md5: f89997f2a4b698303492d259312fb371
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ice/cice_in.nml
  hashes:
    binhash: 476d25645d081b3e2941460a34ecf25c
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ice/ice.restart_file
  hashes:
    binhash: 423a6ba58d099bb96f969d4997d2e30a
    md5: eb15f26472ec812668997eaea7b2f775
work/ice/RESTART/iced.2916-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ice/iced.2916-01-01-00000.nc
  hashes:
    binhash: 87c88150023e5c9e186b0922c1bef422
    md5: 50cc0d166653a873108e86bc3e474603
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ice/mice.nc
  hashes:
    binhash: 709efcc003f302c24c815bd3e76d4642
    md5: d7aa21a0b84d4fa61140bc51d64a762e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_age.res.nc
  hashes:
    binhash: e2031f1a7141b7fd8b32da832285abdc
    md5: 177bc443da36583d0ff8d6f6e27b0b12
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b59828565e535efa5cc1b60b1365a541
    md5: 066d7e1b6182e72564c51636db3084bd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 697e3840bc90716778f1c2d45d296649
    md5: 9d95be54fe162c387cff7315a4bedfde
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_density.res.nc
  hashes:
    binhash: 5b4238158b6cb5e2882a2532d5587e1a
    md5: ba57c13d406fa2131a1151f79de5ae7f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9d228f42d13845e00a8d27dbb6665561
    md5: 816a8084d1e75a7bb58dc8d97ede0ef8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3b98f75437eecf6e58fab439b9e3a2ff
    md5: 4acb14f6ef042c101ac79ead651a7350
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ab7df3bb23920f5da6d9162ffd0be935
    md5: bcc89af05f1818557b1d1c9a13e1f341
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b865167f2116219abff008309046d039
    md5: fc924282b8cf91f8d2c820f73d4aab8a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_sbc.res.nc
  hashes:
    binhash: fd47a422cd2c29510cea5ea17eacfd80
    md5: 1b5c9b27b24f407511ed96e376a61fb6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f0bd70f9ce93568b7808cc2488cd25d1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_solo.res
  hashes:
    binhash: ca02d61315f05203752ca1dd2f767913
    md5: b6ab07ea0ba5f9189ca90632b8619427
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: dc7ac40dfa9993b8922ddb1bcc12e6f9
    md5: 1682fd9d1d88bfbd6ff3c7401c5981cd
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 91b73d00e5eed65145cf23cfa7cb0b7f
    md5: 1828299865aba76c92fca55e243a4e14
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_tracer.res
  hashes:
    binhash: d99ca15932205c6fc1dfcf85ec840a68
    md5: 4d39a137166678edc242b6c0a98a9e1f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1ff9abdd00db3c481f5380334da70b9a
    md5: a9e662decf49dc4d4f20ebf5eb39025e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 066df1697d52dbf427512014dca664ed
    md5: bbfc06a87a289e2eae1f938abbc2f230
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a16a6a05b5886167827a47fd46445b94
    md5: 6cf25c77b4dff4e4d83bc895130b2669
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart239/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ee070ddfc18fd53a6f81a9dc2e027868
    md5: cf73e256123eb337e890665e5a6d55cf
