format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/atmosphere/restart_dump.astart
  hashes:
    binhash: 06bb5becb55640d4a0c58eb072731db9
    md5: 6eb687fed074eb25d16bb286eca2c929
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/atmosphere/um.res.yaml
  hashes:
    binhash: 288cded1e7be8ecbed9a3cd64a802765
    md5: 559ef1527328cdc216084f5499c1ebe2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/coupler/a2i.nc
  hashes:
    binhash: 21dcb582d81e5fdeb1c5c49111408cf1
    md5: 4df2f8391af02acf8615eb360db3e3eb
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/coupler/i2a.nc
  hashes:
    binhash: 1da52529c7424b4a0677b3c868412cc9
    md5: 788e0397d86718e601a9513b47c88b2c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/coupler/o2i.nc
  hashes:
    binhash: ae27f08a9600429e848546c4eb5c572c
    md5: 88a18da3a3ee047d57b153ee30b82a8c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ice/cice_in.nml
  hashes:
    binhash: 28536f44f28f38cccecf87df12a6e193
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ice/ice.restart_file
  hashes:
    binhash: 7a54f189ec8685169a459a7454152bf5
    md5: 4f81a1d5063f9302b7ce01fc8df0f3b3
work/ice/RESTART/iced.2698-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ice/iced.2698-01-01-00000.nc
  hashes:
    binhash: bc5ca31106986bb708cb83aaad0b24e3
    md5: db37a816e11c38b3ff2b589be3530ed6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ice/mice.nc
  hashes:
    binhash: b31d6d91063d5ad067a438f410357997
    md5: c4c0e93106315594b34ae2d07512f695
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_age.res.nc
  hashes:
    binhash: cf571bf9998d47cd1cef34b0a0c13e44
    md5: 323844c5a02ac4353ba6a5bcbd6f4aeb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d71571ef13ca58d6428c0cf3d1922d58
    md5: 175f0568bd004389461aabd0fbf7572b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ea25c7a0d37232f62a9f00d6c1209380
    md5: dd84015d92748b4e6cbf0d3d82bee19e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_density.res.nc
  hashes:
    binhash: e4d13ef81e1e0413783b2605062f911b
    md5: 691dffbaea09c348cb288c10df6b7f98
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9f5bf089c2c79a6ee0ac06382219ea87
    md5: 1615d47de2fc7dfe9c87e9f3cfc474df
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: aa56a634327e3c2437278602fcb82d9b
    md5: 3b09a3aa913d60e24b91775e914b3b1d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 57cafb3efc6d456ecc854bb7f5d88298
    md5: 2291acd62fb6497b50402aed9d391ca5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9f60b3480aa5bc3934397c08f8b13da2
    md5: 5ebd22fc74f1651f39535731913fb92e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 447f58111c6a1b1fb8b5c78c5a15b444
    md5: d0072e3c3dc15bf8409c469944237954
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 59929c45258eb27bc5d0e623e02b2cd0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_solo.res
  hashes:
    binhash: 06ef60e739a23d1d1d4912aa7d4dcd8d
    md5: df271a2fe8dabb0c127933630edbaf58
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ca6bb1eed2d8fddd1c923cf0b5686556
    md5: a47dabf7aa3cb950acab8db77ad61bf4
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0b3bccec83bd0b471dac4dfbdb92b7e4
    md5: 3606144633d35ebb4fe02e852d45cf52
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_tracer.res
  hashes:
    binhash: 807f4db30ec554cf7d03109cd4410b1b
    md5: 99e689275938fd271b715c7b3989eb53
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a581c801be2d3da2d3aa02cd178721ca
    md5: 802acfdb6411cfe4e1f7dbaf699c03be
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 07a157d45d97a510173a78ca76ea2798
    md5: 8de8c9ed6ffc3ea206d4fc56b2a1b259
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3d7c6afb8580ed4640b52babca98d77d
    md5: effaa4748da13dcfedf6113d001339a6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart021/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6e9a9f64b932e450b688d664fe2dda0f
    md5: 1b7ec87cc6ffb1680a374e471b5072e7
