format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/atmosphere/restart_dump.astart
  hashes:
    binhash: acd513fe15f455b6c917969ba673c92e
    md5: 7539ab02a674556ed7b0944e8c7d0d9f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/atmosphere/um.res.yaml
  hashes:
    binhash: 56eef9558d5d5bb2c50208e3cf46a340
    md5: 04562658b02367e60ad8b6b643cee791
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/coupler/a2i.nc
  hashes:
    binhash: a5f8076e968a97d91a30225c4d06c96c
    md5: 76338bf81508b0fd0d4e20fd868424da
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/coupler/i2a.nc
  hashes:
    binhash: 65b034419199dc91dd22ffe44aa5b77e
    md5: 8079f392d6f589bcf479d9b8f2194fd5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/coupler/o2i.nc
  hashes:
    binhash: 9a115871093dc73bfd1958c27e1f7035
    md5: 6967dde286a861c401a02b89b1d3d9ca
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ice/cice_in.nml
  hashes:
    binhash: 1faf27f8ad9607008d51db3bad817a93
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ice/ice.restart_file
  hashes:
    binhash: 13b413689056ef586aabd9f05a4687a4
    md5: 7c2bca8a62509a24c1b00e1112d2f65b
work/ice/RESTART/iced.2796-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ice/iced.2796-01-01-00000.nc
  hashes:
    binhash: 794f1ad21f352e4742b3693b7cd26a4d
    md5: d4b6e733555f38b69bdccb2dd2c93e83
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ice/mice.nc
  hashes:
    binhash: 28ba7843a8f06c35a72b33abe7151352
    md5: 9fd818009a67bbc775ec2af274a682a4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_age.res.nc
  hashes:
    binhash: 4846f8bf10e3e1dbc08f32f4a3903f6a
    md5: b88daf74b63f0f272f459a8384d0a58b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bd210a95fd7087d55be7663e263b9533
    md5: aae0922354073199d71bee5db2d89818
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3405049e152aa1dc76651808e09ed824
    md5: a1b57bb0e4a03a35a133bc8fb24cef7f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_density.res.nc
  hashes:
    binhash: 00a01f02f013f09b04080a9d1ec8201b
    md5: 8ca54c85a637e7396b6ca34ca9d6b25b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 984aa7a40182abb521a20f4a61017224
    md5: 49827d131b3c1c3b40434ad7bfac849d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2c0d6e6fff05ac92b65e393c29631150
    md5: c99538099f0787b043332a0093819685
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_neutral.res.nc
  hashes:
    binhash: dd0607beba97a9c1e10bacd5576410ee
    md5: 7a2604187596bb277bb87ce2faba3530
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b235bfc3cbb9af3f57ae9c9654825a67
    md5: 10f132c2dcba04b0cade16685fb82bf0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 28c3485a0c7772a24af75162ee5e4b7e
    md5: dfc0cb91354c96d16ddf542d25c9e513
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 24161b793d4d322602017c785e33a2fd
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_solo.res
  hashes:
    binhash: 1e49c5a04276dc9f2adb482101282006
    md5: 2266baed65ac0da7c5651744beb5009f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a15d2f6bcbcb64de604bf402c5ba05e9
    md5: bd51e3b7dafbef0c0e0ceb3a14d08a82
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 12d41a2ad12282df0bb047cdeec2c5fe
    md5: eafc5272795c001a4d3f99cf8c1d1fb5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_tracer.res
  hashes:
    binhash: fcf9cbd7e8334e1232c1caf630527702
    md5: 998c5a3f408e02c01d40117d57fe508c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e3e6cb24bbc275e5d62607798cfe2f06
    md5: dd7fe081b7cf7832e34ab79b68e1d66f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9050bfe36a040a6ad4c9338eeeb49695
    md5: a6ca6fcbe3ab57ad07743af43f425c76
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 099d7973efe5e9c9b9cd06521a991f56
    md5: a214dc61889144c58f25fcbd1767816b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart119/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 50c6604740c1bcb733bf38c92614cf51
    md5: 9d41167fb49e959d62245e2706f40469
