format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/atmosphere/restart_dump.astart
  hashes:
    binhash: 5451df7736d596dc915a1676f7e9f29c
    md5: ed3df89d8d59f30e9f825f07f054669e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/atmosphere/um.res.yaml
  hashes:
    binhash: b0f5bac4acb234e84c025257a61a800e
    md5: c689ffc03b6ee2ec969270f35ae6029d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/coupler/a2i.nc
  hashes:
    binhash: 01c97b117d2a5e90a8cd25f003bebfb4
    md5: ddab8cf5899e12d23e1d1d033f1b17c1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/coupler/i2a.nc
  hashes:
    binhash: 8934cf98865938924952ddbdbc2f0501
    md5: 0b710f5f93deb05fa6aabb166c8739df
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/coupler/o2i.nc
  hashes:
    binhash: 7c55eb321a1fd68edb6228896224ce42
    md5: aaa4ccf51dd911ba6a2a86ebd9312c42
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ice/cice_in.nml
  hashes:
    binhash: 3a9661c1321c2a38d4dd9ae081713f11
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ice/ice.restart_file
  hashes:
    binhash: 87c54583861d4ff89c20d663804b2b44
    md5: 9d523f0b6e5aee9d8d52c1ee7dec1a83
work/ice/RESTART/iced.2880-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ice/iced.2880-01-01-00000.nc
  hashes:
    binhash: f2d7252fa2638e900e66bba6917b8f5e
    md5: e5bac9e593b2950548c38da0371ebc5c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ice/mice.nc
  hashes:
    binhash: e1268cf50f42367722d19f2098742af5
    md5: 8608cfdeb7a2200a8a41b0f1568d46e0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_age.res.nc
  hashes:
    binhash: ba6835da42b0aec4f5c4a3b9ed58da31
    md5: 2912bf9a1e2eeae86fc21d44ddb49f95
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 60ddf8eaff9a215f68e9b27d5bf249b6
    md5: 040571071da1b86c2db8434a7e38f6c6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: db0b6817b6d30ab71820e2b21677860a
    md5: d36851af51d7521d7351714befce3beb
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_density.res.nc
  hashes:
    binhash: ea95e63f369999f2f7657f715f38c574
    md5: 87fc29c10f4c50110ba4ec42b0c3ebba
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_frazil.res.nc
  hashes:
    binhash: abb1c1843cad46c913aa4acfb80d9124
    md5: 99598f5f857d77df2d739c53c950dade
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a9e161d4da6e7b07f274a8eccf93935d
    md5: ac52231b93fc4fa3d7c81ae5c03e3603
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 53a87b0ec67f19c247cfc152b8795b08
    md5: 4e655947ef49e68801352db200c4dbbb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5b5d9e944bcc6405f89a4ca3a5667af9
    md5: 1cd88676866bc80285c84b2f84dfa089
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f16f17c366957db6d63e6306b6650c8d
    md5: 8e8a623feb2b56f55254e1bcb2a32fdc
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 87d37d36e2b89d0edc205cc911fbdde2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_solo.res
  hashes:
    binhash: 1a41e5cfd56a68397466e0d61431b0fb
    md5: 54132602581ac341a81ca043fdee687c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 24dc9e77489c41bbb8b5c8a246ae4348
    md5: 9c702c446ddaa4eed6d3f236757fdb91
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6fff24df0da0e302f49808ae8bcf3094
    md5: 207d521d89b036d18c75662d1d31bdc3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_tracer.res
  hashes:
    binhash: 3cae61fbb2947369af41b90c36fde731
    md5: a51fe837279aa4b78fce48508dbc6c09
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_velocity.res.nc
  hashes:
    binhash: aa907dc5b224798de5c1bfb31165bb62
    md5: e1fa4ab902aa7dff20fbd14afed1e175
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 649e48ba6530aba12488a01503fc4f55
    md5: cce15fc4e247d1d2b906e6e117a212fe
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0abea62e8ff7cfc603f54ba1b99c873e
    md5: a2499918ad204df39fae1da268652ef8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart203/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5d941b3c52bfec8a162752f60866a4c5
    md5: eeb01382ce746faf0a3bd70d18632d3e
