format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/atmosphere/restart_dump.astart
  hashes:
    binhash: b8e82c08072b9dcaad7d5decc8c3dc54
    md5: 4954ef3ee4e092488babfc6b92632d50
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/atmosphere/um.res.yaml
  hashes:
    binhash: b818ad19b02a20508b5af9093df1f9c7
    md5: 2c34899e23c6cbf55db19045b42afcad
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/coupler/a2i.nc
  hashes:
    binhash: 2f7f27c113ecb308f2b496b4987bdb49
    md5: 2e9a6982e438bcf75ff8152599d01583
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/coupler/i2a.nc
  hashes:
    binhash: 1d19ca22fcb92be2c6dd72eabcdb5afe
    md5: 226ca83b14de05cc477a7cbf187812c0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/coupler/o2i.nc
  hashes:
    binhash: c062df8ead53c12bd2aa8faaba929a3a
    md5: 56dac64ff49b4e623c483b1fd6f3db41
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ice/cice_in.nml
  hashes:
    binhash: ec6a8dad82d760a4a91e7f6d7476b587
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ice/ice.restart_file
  hashes:
    binhash: 1aa5697183a259e5e0fd25e0b747bdc1
    md5: 8f6d7409d7b85361698bca48c5346a6d
work/ice/RESTART/iced.2936-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ice/iced.2936-01-01-00000.nc
  hashes:
    binhash: 8178d2b72e7f8c6a20a295b55a2d5093
    md5: 3793872008811e0b97afc9b559060909
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ice/mice.nc
  hashes:
    binhash: 3de9536a9a0ca4a68460ff12decef055
    md5: 332601ab3d5c3adcc3c8bf1d6264409f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_age.res.nc
  hashes:
    binhash: dfc43afb0f0bc89aa5b58f1e7f435212
    md5: 6da4f7592c7560fab9824e40280fa0d7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1c77d3935e3075c14b31f7386c03346b
    md5: 047638a5ba59ff6f38c012d71dfd7fc5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2f291ddd2760a6b60a3c17459fc78898
    md5: 8fd93078a2a411c3fe9798828962b8e9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_density.res.nc
  hashes:
    binhash: 62e6cea495a9a980b7103ece6055d221
    md5: c82158c065284d991ed77fd020c1f0c2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 97048ab61883d82a65e7ea9fddd9a7c5
    md5: 290840b5903c6950af8776695cc6b4aa
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 632e20ac37a1b319da98e1b500f9677f
    md5: e66aa2dfe94be0232ed9c2d3d59f275c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7888ddb1bb0b4264091b5e6991dc27d3
    md5: 53c7a4de83c48ce7afa9dafa5721fb9c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c6cbec3930fe5b3985b939c37c5f5355
    md5: 3e665caf1eaaf084001c167f3e41fd03
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bb6ed7e8ce091876696e3ca48c9acb14
    md5: a29f809279c690ea6f8800c181bea1f2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7f5fbf9f05938fea6104d79cc954c432
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_solo.res
  hashes:
    binhash: fb8c6915cd9e68ab5adc40115f98341e
    md5: 4b406f1bfa88c4ac08d3a3b0912e8333
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a884b01a34936942a12edb59762361ca
    md5: af6bdc2e282a96e4cb98faad04a7f785
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_thickness.res.nc
  hashes:
    binhash: dabe8ba7b201014a5509f1f1fc349a9f
    md5: ca31b0c12cc90ba41cf2af9e5b42d23d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_tracer.res
  hashes:
    binhash: ed342a3a3a7cfdf1356eb591d3306c92
    md5: e434ffa0db11f04a283a84461f923de7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1b97c61767368c4f29f0a424e793ebaa
    md5: 0943141b651aa4c9419501fd6541453e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a33678f651c2b1e20cba912ce8a0318a
    md5: c59dd8584f29f486abe37b1052f9fb92
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 93c782306f243d05f0fc29d87931f1d0
    md5: 3f8c9c920c2ab60c745b8b8ab5423707
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart259/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5d88317745354d07cd49486c97e8ecab
    md5: e9bd171b4d73760fa189ad094bc1887b
