format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/atmosphere/restart_dump.astart
  hashes:
    binhash: 05f2a519dd897e266d099aec7293e672
    md5: d3945db9ff42bb5922762b0671be6d0a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/atmosphere/um.res.yaml
  hashes:
    binhash: 76145cb38e1e92d2c583bbafd0fc0edd
    md5: 566fdef83ef967924d06251d9bdbc1f4
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/coupler/a2i.nc
  hashes:
    binhash: c3dffe3526e6915c0a43b8c96d67bada
    md5: 1d482e96c2b5e03b2cd7dd1603bbef34
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/coupler/i2a.nc
  hashes:
    binhash: c7f5513981aa153db92bca8576abfc02
    md5: 038fda823a261a350f2a1f6ddb038615
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/coupler/o2i.nc
  hashes:
    binhash: 29adcebb53d452922e323773d23e0e06
    md5: a55e8227a2721433924fd789c1ba06c7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ice/cice_in.nml
  hashes:
    binhash: edc331d63ac43af361d6af31d55f6c92
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ice/ice.restart_file
  hashes:
    binhash: 538ca3e8af129126860036da4ddc24ec
    md5: b308a075926bb2c61771659a03d27ffc
work/ice/RESTART/iced.2682-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ice/iced.2682-01-01-00000.nc
  hashes:
    binhash: ac1fe86468e0b80563e3f313e3bf5a51
    md5: 245db82363095b44da39f53fe00b3f0b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ice/mice.nc
  hashes:
    binhash: c09a7add0f540b82dd191b6d156ca8b9
    md5: 7efb52296b4552b11a5a0f61719d542f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_age.res.nc
  hashes:
    binhash: 73a32331416877e331cd2da53309816b
    md5: bb5cbd9a63b7f142c15de65a8cd184d1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3ce751b1265b2a8afaa080df8b056e20
    md5: d384f6593f4303221ab95714ae28f735
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e258f5cd64e062fc1b2b8614aedbd2f1
    md5: 7bee0aaceb7c38272425fb9db225204e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_density.res.nc
  hashes:
    binhash: a602375ff0da4dff9aa7db7295cf4e03
    md5: b9bf5480d6463b6467bfc19a4ef90ee4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_frazil.res.nc
  hashes:
    binhash: df3ad6ef8e8109dd53f3fd94777c3529
    md5: 257a1022b6c9f43aa4352e1d60e23d21
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2108cf84b400ec373b7e7830ddbf399f
    md5: 1927aed760b51c5acd2e74b7ec350e89
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 373f16aab16b70a62c9faf707a8f0e66
    md5: 3118d5730bd6d91f7ab8de00ec890391
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: da75642b208a6591c0d7d4c090e93bae
    md5: b805e2bbda9afa6c64c4e8562659b032
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e3bb07864bcde581a8ddf7dfd7c621fb
    md5: 3a7a998e3ae6dc3921bb1cd9519066cd
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5d2aad2187ace8249c2081b4045e1c6b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_solo.res
  hashes:
    binhash: 91c74ccf4793d4edf1fbb674d21eaf32
    md5: c8b71e6c263ff3f3ebc2e0d086e0717b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bf239293de35d7edd870d6da11fad491
    md5: 66894cdf48c0ec75d863562f2fa9f416
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9723a1ff320a1979a4e9ac6d643c651e
    md5: 7cf256bd78fbb456817be5b16c9b0aa5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_tracer.res
  hashes:
    binhash: b896b1338eeb5f0b97125453b41c1a81
    md5: f89e103ccd8bcfede10561c37a3ad91d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f698aa41e5bad026ca14245a43d23334
    md5: 6b2550ff24ddca974df8afea1e6c0cdd
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cde91f20ca63d81165a462675ba769a9
    md5: a0dd4a66c385fd171e2b7688ef52318a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ca0ae75169070455187ef16e21299c17
    md5: 891dc5ccd68d0a64060ddefd3f4bbfe0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart005/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8a53ad55d6b0e3ff5bd6c63763cc6965
    md5: b11e5c302a95a42e156a264e302cd1a5
