format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/atmosphere/restart_dump.astart
  hashes:
    binhash: c2d4cfd37c50820ddd5e1b3f8e063639
    md5: cf74d37c32d9fef0504c7f6592eb9da4
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/atmosphere/um.res.yaml
  hashes:
    binhash: 7a2445fb9148e1769edaf755f170f95f
    md5: 355af351f014f0affcdb920cc69126f8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/coupler/a2i.nc
  hashes:
    binhash: c2738ddd83927546c71f7ddbbd6590eb
    md5: b45ee655787ce82a295068444958d574
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/coupler/i2a.nc
  hashes:
    binhash: 7496fa44a3dd8b632ebf95d547322c4f
    md5: 352ddad7207df281bc90afb28a8681e8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/coupler/o2i.nc
  hashes:
    binhash: fbae2305f5069c55bf744556971605d6
    md5: b8bdceaf84c9c9b491e3e55d39456280
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ice/cice_in.nml
  hashes:
    binhash: facfcf3c4eb5c1f1f4334fc7b1f80416
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ice/ice.restart_file
  hashes:
    binhash: 000373f196725ba90b9a16878e55c8b8
    md5: 81b7844ef63e2bcf9c3730aa307ccf27
work/ice/RESTART/iced.2858-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ice/iced.2858-01-01-00000.nc
  hashes:
    binhash: d1efca8e6b3f1e6f82ac7f7ede562486
    md5: 76003bdcc9f1f767e5f343153e0e67f6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ice/mice.nc
  hashes:
    binhash: 035417b1dfd57a872b1c5addd303bfe3
    md5: 73c32925f9f26b0dfdc4fc23889045c2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_age.res.nc
  hashes:
    binhash: c3d966467f85e2dfdc9a56563de5381a
    md5: 30f3b9912f301e4a34dd702b08c0f25c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1f766dbc6c445ad993d5261ecaaaaaef
    md5: 3c612d41a4a994d7ab6cd85be56ad06f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c53ac52e92e47e3adcfa9a32b039429f
    md5: eab5a04c5a2adaa6836e379632a4c9e5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_density.res.nc
  hashes:
    binhash: b645122b76fceb5f056afab5dcf9331a
    md5: c3d3d1c93734316f2d1c0a11ecd1cf3b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 790285cc66708d8730f1b5e991703b39
    md5: 10d54fc24affef50c962fd856584b3b5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 57604064fb0411f863ac5ca280263799
    md5: 40ef4ee878f3596cb0788a6cef988a1f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7d30d7e0bef6c4d13842d4104fa3f1fe
    md5: 846c6a14436b8e00acf8c56bbc978054
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 501d89b6742a61b2fdb4467e16298de5
    md5: 0ad609554b453f272229028a96cda4ae
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 81f0d954195ab4d39d550d285b40078a
    md5: 1c920f6e136da8d04e950ee7bf1774a3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cb428f3423a7e3b2b87412ede942b5b2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_solo.res
  hashes:
    binhash: bb1ef317c5505593873881fc1d552f72
    md5: 7b70fb02680331a2f0845447a3123440
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d1b2a5d26b89e0d8215887b2e5c46903
    md5: 6f738138fe99a1f981fe18def9406fb1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 647f56ef6e608467656940be7e8afb50
    md5: ae79222fcb042c913a59946f13ab91e1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_tracer.res
  hashes:
    binhash: cb3da70f79bd40c59c9deb8e87b12c15
    md5: 5f7b2c363ef9aae3f6cbcf73d78b3c63
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7c269cbc1b632d9912d5c86c2ec60e3d
    md5: 01fefd18fc2392d685f59c44da79e332
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3625fe41fe077f765b82350f88b4b5e4
    md5: 8cdbe4862dbcfe25b8f73b0e0bab6fbe
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4382a53007c8d9814ecd38c378dc9fc2
    md5: f7caf89ce368d80b73c834bf80b01907
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart181/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9d110263faa10ac7ccfacd28d3f9914a
    md5: 10d5758a7e95b4fbc39c239afed0c3ed
