format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/atmosphere/restart_dump.astart
  hashes:
    binhash: 49b38895e31add7ed35de9e4a67470e1
    md5: 41855957e86183709c6e40f3570e0091
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/atmosphere/um.res.yaml
  hashes:
    binhash: 1ff6fdbdf12f7de690a4bc8c562ec743
    md5: 93eb1bd785b9a8e8a299fe526a5ea994
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/coupler/a2i.nc
  hashes:
    binhash: 63a207a14251331b6bb3a9f3e8baa2df
    md5: 14b1d6fcb170980361bbcbbc61197677
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/coupler/i2a.nc
  hashes:
    binhash: ace7545239fc81ae2c9c5e7c158e8629
    md5: d67f9d5e29aa57e7ae99f0d0f604a75f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/coupler/o2i.nc
  hashes:
    binhash: 3409f09fa53be275437699a86ccb41b8
    md5: 66843d2a11a7fda249c3f9acdbc5790f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ice/cice_in.nml
  hashes:
    binhash: 40abab38264ef931080d19e932b1273a
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ice/ice.restart_file
  hashes:
    binhash: 2fc5bd64430d3a6d0333e618a7970cc0
    md5: 17f742805908f3ed3dd7dfc8890784d1
work/ice/RESTART/iced.2740-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ice/iced.2740-01-01-00000.nc
  hashes:
    binhash: 5100872096274eecc3bdaabbcea42771
    md5: 9ea6dd39bc1259c0fe22366b9b5579b8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ice/mice.nc
  hashes:
    binhash: 02ad03b0f4abe4997ceb30ff70391948
    md5: eba8943c255e0ee9a651400dc6856b44
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_age.res.nc
  hashes:
    binhash: 050b60337955f41951352e4136573a2a
    md5: b2707b64018f05a790078a2467da6f8e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 97f1952c693fce3c56a0043acdbf0a75
    md5: 40f1dbb3e1bcff801bc29ff6b1822523
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 82c2f8323e457426a2c607be38d862bd
    md5: 1d76994be9bab5b4492cba66be626bb0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_density.res.nc
  hashes:
    binhash: d9d877cf4e5b6cab1329b091c2d40bef
    md5: 0cea158afbc4da3d73050fb4930242d0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 01b2708bf4163a5b0dbd9e29d6d23e96
    md5: 1ad95b8d218cbf0da6aca5573f925bdb
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 67d8be85717acf4008657bfd600cbcb2
    md5: 135a4fed55326fe2d3b7499ad98a2d64
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ff286c454a280ac3dff3946aaa2ab622
    md5: ed9591dc5c4f6fcb04a5e0deef373443
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: daddbfe501e2258dafc3df2dc8ceb4e6
    md5: 037781909aa323d57cbdefc2ee5bbb69
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 607a49afa48fdd464518e4d626c722e3
    md5: f5f56e4ba34ee352f90324d380bb4269
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e93d07df3a29fe8f737893e0e350746e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_solo.res
  hashes:
    binhash: d8cdbe0d82cc11faf0b38b3d2d84ab12
    md5: c42f424e50d1417ab31769f29a6ef745
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 62eaae8c434bdf6d1921bf8fb19c9ff9
    md5: 4c82495e1852a9a29caf4f8f596f8a73
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 930a9ab6ae6991cb2f09173cdeb359eb
    md5: f991751f34306b254d49960917fe2d36
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_tracer.res
  hashes:
    binhash: c1efb87619bae15ed2a19512ffdc37ec
    md5: 428b5f7b8cda683f2b1a61eea3107ccc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_velocity.res.nc
  hashes:
    binhash: acebbeddb649e027f9ac97aef06b31c1
    md5: 9b33cf09b9d0dd53327fcb6e833b06ab
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c4a6ade3ef53e5cd4030d23d5c5839fb
    md5: 22be59063f1e3db6730f70f0cc002ede
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1548697fad4d0f8f203b0ba410e3b178
    md5: aa92be9e3bdbbc6b229e45447dff2be2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart063/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 075c7ec6a805f9a0a4e8146ff386cb00
    md5: 1adcc0310ab2182ef133aebbd978b327
