format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/atmosphere/restart_dump.astart
  hashes:
    binhash: 050fd28e5f3e30a7fe08f90e9c8e8934
    md5: b68792cbb2ac3a23219ce3a93d155574
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/atmosphere/um.res.yaml
  hashes:
    binhash: 257105a87d747416097ecbd06314a45f
    md5: be400c12f821c35ac6c23461cf5569cf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/coupler/a2i.nc
  hashes:
    binhash: 46e39788faa4483d8be6acda6af95c64
    md5: 677ff45b319df5cda5416cefc131a51f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/coupler/i2a.nc
  hashes:
    binhash: 470a2aba5ada98ba5c73f690f9e40be0
    md5: bc314101d59236ea8a082a32ce4f7b25
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/coupler/o2i.nc
  hashes:
    binhash: 8da6805f51198e55d72210b3e1fcc7d1
    md5: 41f6cc59e94e3a1b333039a88d7f1102
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ice/cice_in.nml
  hashes:
    binhash: d844bf911e1bb0045cae41cbe8c234f6
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ice/ice.restart_file
  hashes:
    binhash: 991c3bdf0d75d0b857a97be9edf4c2a6
    md5: cfeac091b3f6a57aa05ba19bb6097c99
work/ice/RESTART/iced.2756-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ice/iced.2756-01-01-00000.nc
  hashes:
    binhash: 07c07ea4c2df426d74036a489df7000a
    md5: 35935fd75c08e5544c68de143275e21b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ice/mice.nc
  hashes:
    binhash: d025905d5a77411c2ed51f8012b01fc5
    md5: 2d1fe8f15f989fa448c6dbf2f9e4f2e5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_age.res.nc
  hashes:
    binhash: ca073581ffa8fc0e8194e638a9d87805
    md5: 2ed97165a54cce13126976bfd1307512
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7f779fbbde3e11846e764a26b052a8a0
    md5: aafb0ada89687a1408c105c19057c4ea
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: df19b9e7deec679386130af09b5de640
    md5: 639ce4d21c7ab8bdec3321fa99ccf605
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_density.res.nc
  hashes:
    binhash: 01ce29d9019575c918a9fc8958e19fa1
    md5: 88bc878c7ea064124d433eeb412c9b38
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 09e56bb96d150331bf405e693a96e9c5
    md5: 6149c15a0acb8040e9d32f27c99d2c47
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b55cad0e1f7fa7550354700e6a763c9d
    md5: 3672d0fedd213e772c91a452ce88521c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1e35ce74e1f868fb54fe5da45f70cb67
    md5: 2e11358f184f348fd189b59706ba0d8b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 65cceef1f70ea705b477f7146a18df66
    md5: 2e200e682cae68595a363f0e67b4fbed
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4dc90c244f2489b176bcc6d8fc67f6a4
    md5: 2177f3882f644ef2f8963db29de0fdb5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3de8a414d9d1b1147e84cd7f4cf385e9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_solo.res
  hashes:
    binhash: 052e834c59f95b341445a5c02d60e1d2
    md5: 1a488672486aedbd520017a23ca86403
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: efae77b2c8620fbb697b926acef2fb32
    md5: 15d4927d6e88b20075f904665cc62f16
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 546701484e080df354347b747b11a550
    md5: 9bb00baea607b1422bd37c1208c806c4
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_tracer.res
  hashes:
    binhash: b89c758a6723013bb2713a6fde98c5f9
    md5: 6b5a60878886181b3605383426d98a54
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3952151dc480f3f92cae780577d83ae2
    md5: 593b24399bbb6a800586a724fb8d9d1b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 68fe45bb73e048cee7e02b7e914510f4
    md5: d6d85cf2c3f1c48c316109f855cc0ab5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ff9a0f7629d7d7f3e5a655db1c217bec
    md5: 3a6df34b544c02bc04e6034011eb7e3b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart079/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 44375c819c905d456ddf9ae804e7e305
    md5: ab2ed8ae86568bd193b64f8925166f1f
