format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/atmosphere/restart_dump.astart
  hashes:
    binhash: 153b929a2b91caeee2597773c1404a54
    md5: 28cdfe0a6a3c357a23aa50cc6c0cb554
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/atmosphere/um.res.yaml
  hashes:
    binhash: 99322363e4361124d4a6e678aba09280
    md5: dbf172493614d000647f131009409caf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/coupler/a2i.nc
  hashes:
    binhash: eb9de125b2942e9dfdf846da691a1d0c
    md5: efd7da1524b189cb5db3154b997dad96
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/coupler/i2a.nc
  hashes:
    binhash: 0a4227198aa10df32ad1f3da4e4dd1fb
    md5: ac82fbc7198da045effad2e7ca5ff3ec
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/coupler/o2i.nc
  hashes:
    binhash: 889d8ea88309bf1f57beeba952edbd18
    md5: 45d1e8dd696e62f9f441d6f2a8b698ac
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ice/cice_in.nml
  hashes:
    binhash: 61ac2b0ebc2562c9257843f6ff6fca87
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ice/ice.restart_file
  hashes:
    binhash: f99f94931b10796557fb86efea6b5f94
    md5: 4724f152b818fcd1212a41781bcbdf18
work/ice/RESTART/iced.2718-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ice/iced.2718-01-01-00000.nc
  hashes:
    binhash: b46f54438d49a800df5cbe6b8a7b2798
    md5: 6a46a8265b46e8a66efbd968a7c05a35
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ice/mice.nc
  hashes:
    binhash: 4573944b801803328070033f5b3bce6f
    md5: fbff3762a9bfbe6dce88adec5955b2ea
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_age.res.nc
  hashes:
    binhash: 7e0d0d2438ccb771c29f0ed44d061179
    md5: 99cc8d0b231c1be5343e405215139834
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: abe7e007e4bb437b2ae279d74102f352
    md5: 44f07601ca7d7cb32efbc6bd0748fefc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: d1319b9fe01d184a8c1153890a29a63c
    md5: 016f84725e95fedee84aa42bde4cdd12
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_density.res.nc
  hashes:
    binhash: 95455e495e972e10d367a45dbdc60660
    md5: 9d66c1bab3c0e1c2441b14703240ab14
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_frazil.res.nc
  hashes:
    binhash: dc255c7ef06a1b7ab02743ab19a98f75
    md5: 6052d76e625ffac91cce7d757b2d9459
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e9ca5d7d568c1778d29b00b05d384e6a
    md5: bcb448ccf51c4984e7e4e8264c9d6b31
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c63993f0e2f15a7ecfa398adb05663ab
    md5: 47f0a185911d5b9b5bad798c9e86cde4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 73745954e55ab78289379be83c196b76
    md5: 5da07eb4f69fa0c58bc8aa92029e38da
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6138798f6b1ea05275d41ff1d498ed08
    md5: 5d890a6680aca8fa6e9a1712aa126482
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d70a8167e975a9f87ce2ea1c1ef9b704
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_solo.res
  hashes:
    binhash: 6c86672473bd4a2a179dcad32f8d413d
    md5: bbd888bcf8888924c1ce47537104fe62
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6295286d340c358476bcf18d8c7609ca
    md5: 53457753e5b4e951662a56f567817fba
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6a8a429a35ce05e817f13ecea52a5d8d
    md5: c24b1f9880b8682351dae2aa20fb01f3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_tracer.res
  hashes:
    binhash: a88361c3477e6dccc073f6f66a040787
    md5: 9d2adee16288060b10784caff617a476
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b58aad28fc5740f200cdf9f2e58ef5f6
    md5: cba2bdd4c93a2b5cc8f5485556ca86fd
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6050a12eb1c765dc06f65595c5d4d8b6
    md5: b1bb35ab4a707d1eed9cc670763236f9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 29db458de18b776aad696f60a6bb4bd6
    md5: 80ac28d87a15801473b4e08d953bd030
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart041/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3adc50b9bedafe8fdea5d4386d1d0b40
    md5: 487ac4c98f65b0211568a0ace95bab47
