format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/atmosphere/restart_dump.astart
  hashes:
    binhash: 4facfce5ae18d86205c960d15597b490
    md5: 6364e0457c7e369d59b9d5de45b729b1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/atmosphere/um.res.yaml
  hashes:
    binhash: 8cd560ed986e448a4d6feb82db16835a
    md5: 13cdddb2532046087e55dd7162a81e25
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/coupler/a2i.nc
  hashes:
    binhash: b1682d7c418581f43de3d6424c4ce744
    md5: e011abe1c03b12b4d9c18d1ec159e512
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/coupler/i2a.nc
  hashes:
    binhash: 1772b5728654012a7cd1a44e3b66fc33
    md5: d41ad3342022116198a85bf96170aef6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/coupler/o2i.nc
  hashes:
    binhash: 5baff0780bf43bc36d40152c2ca5f37d
    md5: 9bd564f280c69150637736092bab5e34
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ice/cice_in.nml
  hashes:
    binhash: 6895bfbbdde3242c09de563a2926eb57
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ice/ice.restart_file
  hashes:
    binhash: 6816c84cc49904a74636b451e49d6ae0
    md5: 84ea2e26904b3cc696ba09e75c7e4e5f
work/ice/RESTART/iced.2912-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ice/iced.2912-01-01-00000.nc
  hashes:
    binhash: eded1dcf91c1168224895b2f37effe22
    md5: 706c8e833a433dcf2693c7501771866d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ice/mice.nc
  hashes:
    binhash: ec9a8e6bf0f5ecafd24f84359f39c9a6
    md5: e20b074a0bd2b711fdb5517dbb651015
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_age.res.nc
  hashes:
    binhash: ddb22e04f0b7475c11f778d560e54302
    md5: 613f987ce01291def3dcd546292d88eb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 79ba15d18b82089ea955eec902911902
    md5: 5335acfe934962bfaefb63b886c98f69
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 361103c7f0326e0d19e9231b8d98f4a2
    md5: 1e1940f040d49538adbefc8042392124
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_density.res.nc
  hashes:
    binhash: 8dfc075ef6ae3f41a3a804e80412073d
    md5: 08e916d942d3e5297bcd37fd96b90a6f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f155d17b5ab9fff3f8ad46f5db71efcc
    md5: 354cbb7ed42f71560d53003e509a630e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e0ebd7a465c4e0b9fac51274e7701e8d
    md5: fdfcfa4967a4ce2c3569d183a66a541b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0eb2f182f5bab36145ae2b836d250be2
    md5: 2b2ced5c482fc411af83e7ddb6a1a613
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8507f17fd1e479c215f417ba916ed2f5
    md5: 304a868cc86066ed6970f310f863bef0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f07abf633e464f3c9b23fdf1df204030
    md5: 63b1a5429c63a08e64ef8ca8c9559c01
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3d3086d93cbac4a3a2228f4d5fa9997d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_solo.res
  hashes:
    binhash: 2f4996deb409f6efb9d99525abf66e03
    md5: 6066597d5f4cc4a19d2d1f044baf0a7c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6345043fd02bfdf75c9b4a92b550a2a0
    md5: 696dab2cdbec0939ecafeefea70871dd
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c408e43565229d91e839ecd67fe5a581
    md5: 5e6c8f64994472f0961db3aab2e03294
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_tracer.res
  hashes:
    binhash: 76871ca3033632fc8bf3420a8286cdbd
    md5: 46c620990ef83107455c2d1398051101
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c6393c33e7c3ce61ac72246ebfdd81de
    md5: 08841bbe5823fa3f7978d0ed3b20f044
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f6eed3a5671556a38e298e1a7d985dd3
    md5: 1d8b84440edd69d63c072488ed3058e9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b5bcca35812a6dcdd338d0c404cd5bbb
    md5: b887222803ffecf6c731cc8292017866
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart235/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 078aefe552a5fa0aa143c847441a0b51
    md5: 23fead6cabfdd7f8e1a9f05562033ee9
