format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/atmosphere/restart_dump.astart
  hashes:
    binhash: 7daeec58f9a19cc54507605a19fbf87e
    md5: e625b4c713b6f8dadd38bcbed0cb4165
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/atmosphere/um.res.yaml
  hashes:
    binhash: a78cbd876ebe4dda0dee784224d92c7e
    md5: 269eaf6e71dc871839c5663934a173c6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/coupler/a2i.nc
  hashes:
    binhash: 275857396fbcd53d687460f7c4308adb
    md5: 52e7553d19f93cdeb181fa3d3b1cbb80
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/coupler/i2a.nc
  hashes:
    binhash: 127957be8c11fdfc7ec67f47779b3f52
    md5: ffbda2816caaf3bd413cd0dc41304e7b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/coupler/o2i.nc
  hashes:
    binhash: 26ac66634acf2883e9e184317a1d0cae
    md5: f7d87fe3483020500f319a44f035e050
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ice/cice_in.nml
  hashes:
    binhash: e1c505ed0b9da253bdb1bde3b2d98e71
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ice/ice.restart_file
  hashes:
    binhash: 1f719d55068f788729c81fcc8d721d43
    md5: d4b3e3e058ac351dc8d3604c694cce56
work/ice/RESTART/iced.2931-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ice/iced.2931-01-01-00000.nc
  hashes:
    binhash: 1adb040aee33dd24f50da53fb0b06051
    md5: 38526d7b7cfcc4afef9179b11ef6caac
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ice/mice.nc
  hashes:
    binhash: 165056ecac3de7608a3d52182263662d
    md5: 5fdc37a5a6c33e97895764991e6ae7c1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_age.res.nc
  hashes:
    binhash: b57a3d3f78247acb6835ec4a165caa77
    md5: 812430cd3e20f9aa679ef12433dfbf30
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5ffbb695397e426db1e557363813b36c
    md5: 2083a3889230b72abb18d7aa098af962
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2df5215be4d060d4a003473fcbcdcb5e
    md5: aaad347266465def7c0829b350bb5f1e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_density.res.nc
  hashes:
    binhash: b290a47001041823f84ea1f3d5500dc5
    md5: 2c109dd2319dde2251cc8c512a20731b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2ab6e4dd2b4d4f8554326929ec6aa279
    md5: 0d45ef0c615426583949dc272b53c34a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2a3df77fba582e23ea87688b3633d4a5
    md5: 0de841929de2993975028e02f63edddb
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9d96b3ecc7361cbaacd6f39d13c66ec9
    md5: 3a277b5f36ef9d60431d68181417af4f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d6b515b4406bee622d14b7d5dfeb57e2
    md5: 6c3687eb666c0ebad1b8610faddf6707
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f4f58627903494c4298dd6f0a691c899
    md5: c756bece069685ccc339261278b67644
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b483cd035d674406a81c55362be79972
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_solo.res
  hashes:
    binhash: de0d6630493b29ae77ec6800a9f46a37
    md5: 69ebc1d5d93c883f3f70172f587f7cdf
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d6bb7a5a128324c6ba0861eb05421ecc
    md5: c9d9a1e1a6c751b95b8685b8f274d7a2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cf99861f239395c454d665d63bc26d18
    md5: 886b27ade27d162dfc499ba43dedec60
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_tracer.res
  hashes:
    binhash: a32c60c19fad04bd3b71beb088e9dddf
    md5: add1fd7d1cd18c4cb6b19a22dd598587
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4ad8b1adb8d6553d1886d4ec710b0569
    md5: 712981671f909011d666447ea4dce249
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4e0e916e4acdfa1205b5261755857976
    md5: a14ca348b0d07f79c0f09b527f2fec7e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7468d294cee2a217b9a0fa554fdb1de2
    md5: f0dbe78df04f88071611603ec44c8988
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart254/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 700bc782353621b9e20c397f5a6a20ea
    md5: 5de0136e028e0a998241434a62355d96
