format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/atmosphere/restart_dump.astart
  hashes:
    binhash: cae061bb6ccf6c23a2f42c7c5e82d5b8
    md5: 99a90f566d5f1635fd8e7ebbfb200d28
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/atmosphere/um.res.yaml
  hashes:
    binhash: 415af00e083b374f3be362820d302940
    md5: d0b3cc09ff04c8896554e72bb7651f20
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/coupler/a2i.nc
  hashes:
    binhash: 94a24d131bf00677c5be1fe83f5e7294
    md5: 0c6c3987029174b76ae52ea83f2d08a1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/coupler/i2a.nc
  hashes:
    binhash: 764e6191d2fe7a82754842ca60e2eb93
    md5: 6359caec8758957d776c5d45c41f5b1a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/coupler/o2i.nc
  hashes:
    binhash: f2247e5f96aed2d816b2871b71cd97a4
    md5: 2a7cf46255e92c64e62bf8ad68942b1c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ice/cice_in.nml
  hashes:
    binhash: dba49a9cfb0e72f7b785451a92043153
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ice/ice.restart_file
  hashes:
    binhash: 29b445d2205c1e9f880919f6ada7db3d
    md5: 71367811e5c96e7e702d96df5ff6ca00
work/ice/RESTART/iced.2804-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ice/iced.2804-01-01-00000.nc
  hashes:
    binhash: a3eb05a0e696c82b7f2df09a92e1694b
    md5: c7c7129c3804991d6fd597e644a3e974
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ice/mice.nc
  hashes:
    binhash: 7f6e39e83d4f52c66503de36158ef8a4
    md5: 81b5b3c74da11eb21356ba7fbb6aff20
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_age.res.nc
  hashes:
    binhash: 00af57d21a08e67373871321425466ee
    md5: 13f4e26614df968694f46041fcb91e36
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2682d9a0afeea4398e5a86b69cd452e2
    md5: 0c978dfca9673dd360968d34f4298064
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 88a92b48556ea3103543a8d5026a6447
    md5: 5e47b857eb4080ba90a137caf8253977
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_density.res.nc
  hashes:
    binhash: 1861c5bf19c3134f0965f26bccb110f4
    md5: 823f05c1ba10fe932ff28f13e02b7628
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 79bdc76cd2c93ad9d2ca1db914c220e3
    md5: 1b4aabafab19b87201e1b1f5f899de54
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 40e2423a806ed53df82efa6d824cfd0f
    md5: ed6b2e3b92bda59b46c2556db92074bd
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5151ee3e7b697e7b74b2bcde874399bc
    md5: 62bad3828f7aae70c298f5afd4c86f9e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6c2cb7aea74754882a9f312b3f70f8d0
    md5: d262e80e843890051c39cf7377696b92
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 65b8cc0eaec8b5dab56ab5681c0ebe41
    md5: 455347c65fa3628365ec1fb66781a46f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 82c2a26f169214063e7d142bc9f5c50e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_solo.res
  hashes:
    binhash: 7ec290301ea5c9448641ecccb2ba3fe7
    md5: 80f5450fbad6b4eaec1b2a543c363ec2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e0291f23768fe31195b876b8a1103fe0
    md5: 7de7b674d6506daac64c282db14d6b9f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 853fe3ba2cc21c2ddcefa6a935f3006b
    md5: c0f3bc841b51a0658afd894bd643b8c4
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_tracer.res
  hashes:
    binhash: 3f622a685ed00e0d64bb514bc2551444
    md5: cb30b9d2d7d7d50fa21c0c1b2c254425
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 881a40cf3555b997502bbfbc6a164ed1
    md5: 60693c8cfc62f07fcfb9adfdf18bb90d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 12a20517922afeca71920481b0a872ba
    md5: 898254b72570278cdb3d5172b58e0577
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7a0186056132f3becc6a9c13ae8f7f43
    md5: a57c119b5c08ef732f0be12df43559c2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart127/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2972e910e8a5b7937cc5772f540d2e91
    md5: 6472b8062e183532ab79b9545f298449
