format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/atmosphere/restart_dump.astart
  hashes:
    binhash: b31fad700c6be1416ba4d6dd0fba1cc9
    md5: 95cbb9540d8683875b0ebf724337e994
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/atmosphere/um.res.yaml
  hashes:
    binhash: c12a238d8b89b461f85ea5fc4fc3ccda
    md5: 5e72c166bb1dff02845e7dfd29dc17f2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/coupler/a2i.nc
  hashes:
    binhash: e504b804dd0c6352bcba672443b92218
    md5: 09836a24587a75bfc4e9396172d7cbed
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/coupler/i2a.nc
  hashes:
    binhash: 5c9851cf49129419f2170bf3d0175858
    md5: 77934bd9259b9f2e0ab7a7607773b044
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/coupler/o2i.nc
  hashes:
    binhash: 07cdf0da8afcc4be91e22b183993e767
    md5: ed3ea0978fb8e7ee5a59fa0d4f47ec41
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ice/cice_in.nml
  hashes:
    binhash: b54fed5a6eab060d87a55f174f5fa952
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ice/ice.restart_file
  hashes:
    binhash: 09a0f63bdea85ccf07ce15e04532fe22
    md5: dcd2f3da80231006037f6be42de86f28
work/ice/RESTART/iced.2766-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ice/iced.2766-01-01-00000.nc
  hashes:
    binhash: 7b5010cf5582143e9c92dbeaf5a6b4d2
    md5: 66cf44169f0356633e82810779b35165
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ice/mice.nc
  hashes:
    binhash: 5ec1445d6eb40a2e93d49d87835c667b
    md5: 36f5f54b007780e1428bed4221062987
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_age.res.nc
  hashes:
    binhash: d7ddfa598a7f1079cf221ecc7073510c
    md5: ba3cd2299bce14d8f19147c1dc00e5ac
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a926aa8dee1a4a46fd7b7a3d68cd564a
    md5: 7f4541f9f71830c8778708a47d817050
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ac2914d42def9d831b9e710de5dcc48c
    md5: 7b5253b4570b2b9f7df535412da32cb7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_density.res.nc
  hashes:
    binhash: e46ed89caa1bad53e117a9a316ff67f3
    md5: a4fac134c540ccdc64d3770cdf7722e2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_frazil.res.nc
  hashes:
    binhash: dde953096c924c608bad795d4906a5b5
    md5: c68e728ae742100eb684d9824ef00919
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 47b404dc9713dc0a78f5c4a27ee0923a
    md5: 96161f0601b33f725b08fb2ea4efd253
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7a9ed5de8f6d983e181b080c26b6c774
    md5: 351bfffef52e2d15ae9601c5caebfe4c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f7bb90ab862477e9abcadbceb6486998
    md5: 551c2e69a72316ca84a4cca20ab39f78
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_sbc.res.nc
  hashes:
    binhash: cce6541b221cfea2359a588230adfd6a
    md5: ff3fd11b4f32e69fb97acadd0b39a462
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 06efab8406b18e7ee0b0c823e2c5ca1d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_solo.res
  hashes:
    binhash: 44a7ea67f62ac5ea6e7defd26b0738d6
    md5: 571e6cec787e9e2a0cafdbf890ae9136
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 36f3b2118ef81bd9584194996b4566e7
    md5: 03f3fcca54bc54e207fd4f0d9b1c1d10
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 46cb948b3d85e5871ae1cb98631d71f4
    md5: bdd19d4d7fe2cef151d34e19288e5020
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_tracer.res
  hashes:
    binhash: 4d2b76d348b88ca2cdedeb5cb0f5393b
    md5: 5bb9362f60761a04fce8df79038d05f9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_velocity.res.nc
  hashes:
    binhash: baea4fbb4f7aa53ce88e97f75329d3b1
    md5: 0bd9caaaffe41cbb683de2d815f3250c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 78ea966524292f31a1a1633b6bad72cd
    md5: e616b2f82c6a84f3df5d0808e34f2794
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8b733e54ce9827266b74d64082eb2ba4
    md5: e27d7c85a7c0ddbe21c3fc7a41e2c983
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart089/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e5c48fa6b43f8d56dd3b3c7697e47b7b
    md5: fc062e2d5549b0b780d52de096f6b42d
