format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/atmosphere/restart_dump.astart
  hashes:
    binhash: 56bfdac6372de36232bdeb34e3a56d57
    md5: f1af682d41cc04ea2aeb484bd4d6f9d5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/atmosphere/um.res.yaml
  hashes:
    binhash: 6cce0a8e6827b5517d291dc8e2368bbb
    md5: 17a755a239aae39a5a411d15ce08c522
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/coupler/a2i.nc
  hashes:
    binhash: 471f8e295ad907c10231788d794c59c3
    md5: 80a74aa2f2f75ae0457cf5f3f5947e0d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/coupler/i2a.nc
  hashes:
    binhash: 1f9c6e82fd49bfcafc216b6c8cd37776
    md5: 33cbe4d3e8cbbacf2a445489f7e24c95
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/coupler/o2i.nc
  hashes:
    binhash: 1c46bb17301db0e245f40b7676389cf5
    md5: 74b6db2ef78d4dab19cd1096aee583ce
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ice/cice_in.nml
  hashes:
    binhash: ca4a7261fb29b3ba0e582d696751c5e9
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ice/ice.restart_file
  hashes:
    binhash: 07abcf519174b3e3532bc4e92aa82e42
    md5: f0886ccd29d2aad7d9af87006bb586e3
work/ice/RESTART/iced.2747-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ice/iced.2747-01-01-00000.nc
  hashes:
    binhash: ce20ed2aa00cebcab0dc1b4746d6d5c4
    md5: ef822063cbc825b0aafeb7487e114daa
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ice/mice.nc
  hashes:
    binhash: e6029c3d4b5b2f5422799079e8ec6ddf
    md5: 28284fe8a6b6d58570c8fd9f3c18cdc1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_age.res.nc
  hashes:
    binhash: 01d5aba55ba1b27308418de405a63fdf
    md5: f69e1d11fa8fa6751d3f9d2a5e970cea
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 924035d2ea8e8eca083fd008178ede34
    md5: 35eec5d4892e6d550c3834aaa6ef0e91
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8881dccecf91716b795cb10124b7032f
    md5: 48b66fbc25eff3baf12789068a4821eb
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_density.res.nc
  hashes:
    binhash: b99d8444f0bb82277c078f1757dd2a74
    md5: d8f6623e1c958cb03dcc1f3846cc0499
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d647f1875ca9a2b1cae7ab85e3d20efd
    md5: 426bc3017a93b31742419dd0b7eb5f3b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 349bfe3e862f24b1d5b530e9eb6dc188
    md5: 88f9dde2edf07932e79e84d1d13c2861
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6fa11f5647b0b5ae0e6fa09a42457eaa
    md5: 80098a1f5cdb13562265ef147ef5df54
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 505f60ecf1ba2d221ac02a3397f7781d
    md5: b8ec7c53083fb508b4768fab7c6d8556
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 373e8a31451c87236c7264111e18db7c
    md5: 8a473795c7eb42e9d5e560743d6f207b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 13ed63d8afdcef16e781956d65405c76
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_solo.res
  hashes:
    binhash: 776afa4c3b6d69d2ed1ed2c1036f3e94
    md5: aa50646c7d6d663bf6c528321195f94b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 597bbc073ba167f2df1bde10eb130633
    md5: 6ce5f642a26af50cc91ceef14b383caf
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_thickness.res.nc
  hashes:
    binhash: bbe8ef8a34057fa0548b8bdd88a89a8c
    md5: ed4deb0a06991bcd0d9b3fcc88574a2d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_tracer.res
  hashes:
    binhash: cfe7f692cd568a709c023af499ef9261
    md5: a4e1c467ade833f0784ff1d5e45470cc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a59d6efec7fbb1f9a7f173aa99648269
    md5: 4fe5299a2ed8b56ff2916d4127a4b42c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a00037ae7e03ef3a620e68d72a0bfaef
    md5: e5bd20cdf60f72a4822e095dcf42533e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: be25816942503d03f9dd7f33b8ff6b23
    md5: bc8996911e49ad7ebfe1bcec4260b076
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart070/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8fa2e8fe492ef3bfea2ad147a68334f5
    md5: 43af74b78683ed266188842b1372ffca
