format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/atmosphere/restart_dump.astart
  hashes:
    binhash: 288c6d46f6c2b2c56919d0af72937a6e
    md5: 43ec9765c45fa3eb16d71d2bd70aaf64
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/atmosphere/um.res.yaml
  hashes:
    binhash: e110b0bb8118f905060c1cc279188794
    md5: 9c730d4891e7877ee22ef886a0a7c458
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/coupler/a2i.nc
  hashes:
    binhash: fc0471da437d58fb34983f5975dd285b
    md5: a5f81aa396552330afff8d96b5ca6f17
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/coupler/i2a.nc
  hashes:
    binhash: 7e10a5f9436f022b2da231b367665bd2
    md5: c774fe857d94e2a094050b0122d315ba
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/coupler/o2i.nc
  hashes:
    binhash: 471fde29893076a361c50dfebd55bdde
    md5: 02055d32c0975c6dc5a89b1c1863a768
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ice/cice_in.nml
  hashes:
    binhash: 413fb35222cbcfeed757214268443b14
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ice/ice.restart_file
  hashes:
    binhash: 8528304ddd3e5951f924036b493c647a
    md5: b5e2ce3a8ff07f09be7860f424c97021
work/ice/RESTART/iced.2781-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ice/iced.2781-01-01-00000.nc
  hashes:
    binhash: 71fb98b5943fc2a8c5794bd244bc3cb8
    md5: 515f12b40f76e99c543066ee07fe03d6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ice/mice.nc
  hashes:
    binhash: 9cf287e572bce5041c162b41f2f813db
    md5: cbf7950e81013f66420aed20669c3ade
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_age.res.nc
  hashes:
    binhash: b4fe39247cf8db87cbbb9b55cf3ae807
    md5: eab0affad495fe0326fd28e8d9fe733a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 83d7825199b3097397590311542fa59b
    md5: 2dddf6480eca1474bcc18338049fe23f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 425cd426a878f853249521c10ce33624
    md5: 61f572fc13608fb6ea1cadd8c7860d64
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_density.res.nc
  hashes:
    binhash: 01efe410af1a174beba0ebb0f6b61395
    md5: b9b1b8b25c4a5ddd3a917d9fd74daa8e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fa8ef8dcc848eda9193d0a8c6dd69913
    md5: d166c94056a478bd74564aba0100440e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a9fb0a46d7741d9914ba11630c62d0f0
    md5: 2965e8d6b9182b973549efe29263c643
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 83491d3296afed7740ad401431b63370
    md5: 9dcfb38c18ce05b80c392f88241ac0f1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d7d86f9842c3d782bfb12fcc83ed5a69
    md5: b9ac94f594e2ef8ea4d885b6260a3059
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6f5a2cabd140423dd4a49b9914fdfb76
    md5: 351f817e5f50e5d48b20425e61ace0d5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1d61438b084fa97ab06d149b2f5a154f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_solo.res
  hashes:
    binhash: ff344799b7962b3b27a7204368504c4c
    md5: aa6e8c8eaeff6a32552a63125cc4d216
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 16b91fb6ba7fc30d92011aee482e68ca
    md5: a7119be0c90eadd94c76f2f184e6e0ff
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4c11b3012282e1fd75d21a6f2fa06bf6
    md5: f9123882344407fff91a37b437f49b00
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_tracer.res
  hashes:
    binhash: ed4a3bedbcc4338d6bfb823671511c5d
    md5: 217639a662c9c4ac1ed50ad9a9e2142d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 45a7aa802c72f8f2e8ab99fcda0b30ef
    md5: 76337644b991240cd7df29cb6f92a10f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 856c1d3eabbb45fef5ecc5063270a8df
    md5: c57b83310f456c86309a69e95493374c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 72e889e1ab87d406bd0559cfad183e15
    md5: 5f1d66e8de5b85209ffd95c96f080494
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart104/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c89cdb7a4c660bcfeb862567d83614b4
    md5: 06b4b79880dc35db7e91da12dea6426c
