format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/atmosphere/restart_dump.astart
  hashes:
    binhash: 70eff62bc9b134a979c6591b5db76896
    md5: 3b85475b00e7e3e704738e456530ebe3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/atmosphere/um.res.yaml
  hashes:
    binhash: 5fcc37c9932a892b3b2b0cc711cebe15
    md5: 38afab689b37cc54ae344fe60e85ab29
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/coupler/a2i.nc
  hashes:
    binhash: 4a4d1b359188a3efd7e697c1ad3c5502
    md5: b609fc48160d83c742d1430727c9032d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/coupler/i2a.nc
  hashes:
    binhash: 07bdc2da04379d9f2175ddb9fb2dd0cb
    md5: ab5d7076b05f4cdc56f2f35648991b50
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/coupler/o2i.nc
  hashes:
    binhash: 4b40c0ed534d1967d91d8c148688dca0
    md5: 0a468e7318730fb986ef96f0fb5ce4ca
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ice/cice_in.nml
  hashes:
    binhash: abc232bb4e44cb511b207f6f1f69dca2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ice/ice.restart_file
  hashes:
    binhash: ab6a96c7d256c1299f7b78cc3f7f29d9
    md5: c7007f27c2c7d3d82fd2b4082c205c89
work/ice/RESTART/iced.2959-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ice/iced.2959-01-01-00000.nc
  hashes:
    binhash: 1baf107ae6e95bdd82992cb256b47efb
    md5: eb29860068e00598377dfd932bb99ba6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ice/mice.nc
  hashes:
    binhash: 6c25ae316b9d2d7f86bc6938564a501f
    md5: c0c5d49fc7799b0001d4118bf979d22a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_age.res.nc
  hashes:
    binhash: 89fe22d70917b0fc1879849c97407b76
    md5: 53c050ecbf098ca4a8c8a37217b98a5d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d4c74e0a7481871f23178e8bbc5209f3
    md5: 8610a9abd72fd81957069b6de3fda1de
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c32b1c1ed9463cec8354ce57eaf9657d
    md5: 8d380ee9a1a7b520ee7b7798a7f82298
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_density.res.nc
  hashes:
    binhash: f43e0a228a89a9fd0009fe16f96e3d34
    md5: 005cfa862b32dfdb1c209d2b323422dd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b9e6f41513c6124e192d3335017acb2f
    md5: 163f49f7513c929f36b03b4a622cefca
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d74170a88f1a90ecac79c1cc7dbe6fea
    md5: 01940dd7b3081e9865b982a2bb10d4c2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7a397ad14036f93067980a3f846c6772
    md5: 51f9e0848e218a675ba37019caf1932e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7c9f0cb7e50e628061a3160b40312ea8
    md5: dd10ef22faaf3eb23838aba8d26f3238
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4c96ce11b2c8cec8c0fb5881834c0a9a
    md5: b90344c4901615624bda947a9d96274f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f0adae999be3925a3acdeda9414643e0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_solo.res
  hashes:
    binhash: 5b2022bb74c387c784598fc4da6f1b03
    md5: d96cf596b670e8942bb6558a92a3f66b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cb1e4fe1f37215155c9b3155b89e4a44
    md5: 58c7c621c9aa31e0c3cb751934d78cd3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3d7764f2240cac21cf73ca88945b554d
    md5: d1cb80e613ea576e568137526ad7251b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_tracer.res
  hashes:
    binhash: c37dc185ae34f3abc214fb511a743e5c
    md5: 70ec598a8edb9a64a90c9802ec380245
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6ce17a3c75cdb68b929affc1a054ec0b
    md5: da5164e7ba8cc6c3f6870a751ceb4e72
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c2d2451a7e3af6715d4d2cf7bdf5b9b3
    md5: a4c07537c3699ec7aa7c91a8b9c0958a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 67ad55bbf2640926cc8dc81e4b2b0ae7
    md5: 4446b34c31f7dd8fc2a3e3d0d8ae9f1d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart282/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f60a0fd6b93c8712c94a36e5b2b50228
    md5: 9e84f8d2e29977a7caccf5b147337bdd
