format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/atmosphere/restart_dump.astart
  hashes:
    binhash: 8cd527093304df17b590c75fdaa94d6f
    md5: fccaef0a581edc3dba5aa5ee2a7940fc
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/atmosphere/um.res.yaml
  hashes:
    binhash: 4904d91019ecb4d6ec158994ac0b5d08
    md5: fc1007d0612c20b1ce71becf748be7c5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/coupler/a2i.nc
  hashes:
    binhash: 994deadb3df166fbfdfc55cca119cf10
    md5: 4518ea2d1156121a07bb24859b49e4b2
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/coupler/i2a.nc
  hashes:
    binhash: da7bd87a3fd46306842cdfbdd012ee40
    md5: e90e6a58487aa6e44b5b637634a9ea84
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/coupler/o2i.nc
  hashes:
    binhash: 381a8749fe9bdd17ff20c45e3f8a1877
    md5: cb2ee40021f1cb7e9c7af5bfb4af8587
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ice/cice_in.nml
  hashes:
    binhash: d39e4d60f656ca5ddf7599678968efbe
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ice/ice.restart_file
  hashes:
    binhash: 4565131b48278c5b1ff50f228466e30d
    md5: 6b6853e13075e5f70cf523b5e7262cab
work/ice/RESTART/iced.2799-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ice/iced.2799-01-01-00000.nc
  hashes:
    binhash: ac9187a2aff1d3d01e2b3cd09415a9ab
    md5: 5ba7b92545cd7f64956cbff7ae3df819
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ice/mice.nc
  hashes:
    binhash: d1daca6c334f14759a59cd5b216f182d
    md5: 0fdcb9d31061cc8cec5f252631ca0d6b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_age.res.nc
  hashes:
    binhash: f8b87a46dd499e8925d7574b390d9399
    md5: 4f29594949bef80c2424d910bdca1f37
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7bf4ea96737874f6e21d4b57c211866f
    md5: 2dd82608935257cf19d179f52e95acf3
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ebe10d701a68c86767edfad0f4a86d4b
    md5: a44e92be9511e8d70585e3cb88df931b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_density.res.nc
  hashes:
    binhash: ace03981eb7276c525f47d845e5a6497
    md5: d246cbc9524d1ab2e7d5102b8dc0975b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cfabe1894870df1aad9473771e96501f
    md5: 047aae3d8c0ba113b0e3018996329c15
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1212b55996e0259e41d4587cbacf8de3
    md5: 1e6b5f555c83b584494cdffa04d552ee
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 835360bd1663f8789fff7ca55ed7cde2
    md5: ea4d9384afed8801a8a1d0dd31be0806
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9740da7e0669f5acae4e7bc983329bdb
    md5: ac1deebad796a9802c5a46a5e87d5dce
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 00d83ca9425801ca9b1e340468b4aeed
    md5: a8e783b82d63dd91d0caaa9934b60c7a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 20352f74e467f9b9ae293071add08169
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_solo.res
  hashes:
    binhash: e8665c86eeb08f89f41328ba03e3e390
    md5: 604d5a0bd8320fb26608694379c15085
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 899944ca565966887163d20eada774e6
    md5: ba56ad4e108fae5d79a89563ccd1065e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c4118a8297da9ae78d28cfcccc5aad9c
    md5: e4b3803cc27df4729c06b385c411247e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_tracer.res
  hashes:
    binhash: 76aefd296190c0642d3787c7164059fd
    md5: 87595731f59f840e8920ff78bf820e6e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 976d1cb60d70b25f63348cd3fdf65f20
    md5: d59a592f1bcdeca10c7692b966a88e78
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 75e8320f2a0842a74fab0ec905090665
    md5: dd02b85f18aca39d39a49f0652d1fbff
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f39033ce4ba7a4d4686fc2c4020acadb
    md5: 9f3edc5170cd472e45b392b6d2b34d48
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart122/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ee130651f7a1cf0f765e9b1920e2b034
    md5: a0ea77a4abc86dd8fce6377beca34523
