format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/atmosphere/restart_dump.astart
  hashes:
    binhash: c1750322b4aed1d3eeb9be6a34389de1
    md5: d9599c114dc91227e4ce8ef755601b78
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/atmosphere/um.res.yaml
  hashes:
    binhash: a7b6ec2e4055980f6506529fc80f7e4f
    md5: d40b382737464bf735d91d7403aeaa3a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/coupler/a2i.nc
  hashes:
    binhash: a5412b5a1d40ad66050edaf137ca04c1
    md5: 54f0726c561e7231b5acda7f1e9ca2bd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/coupler/i2a.nc
  hashes:
    binhash: 635226556abd0b6b1dbd0ec5640b62fd
    md5: bba5dcc29bf17ebbb07efad1f1e68c69
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/coupler/o2i.nc
  hashes:
    binhash: 0ae7c645e0dcebf6a7828a9792a9893e
    md5: 90af2f1d311dadc3eacdda76da098a74
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ice/cice_in.nml
  hashes:
    binhash: 66aac78448923a230c9fdaa2631783ff
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ice/ice.restart_file
  hashes:
    binhash: f9b9d300482727dcb24e6ca1646528b3
    md5: d7dd3df8ca5aa12a0370fd938a4f6b37
work/ice/RESTART/iced.2738-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ice/iced.2738-01-01-00000.nc
  hashes:
    binhash: bf58413787f838a5b80a8fd7cef472ff
    md5: d3abb0ff8cca277aa374679547d86277
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ice/mice.nc
  hashes:
    binhash: 7c06d1eb22c8137e223eefa1dffb310f
    md5: a8a5c75527720de053cec1d49f82a882
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_age.res.nc
  hashes:
    binhash: 106604abe731ba8f708677525c3be55d
    md5: 8cd6f20eb70a212906d2bc977cae6608
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: aba8a1186e7f194a7f8e40d068ca989f
    md5: 0655a6923b24c9addb2c57571b9787cf
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b91f180a27deebd1f442f9cab1ac8292
    md5: dcfab69240bdcaa8241d3c11ff6ff183
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_density.res.nc
  hashes:
    binhash: 1478f3652e094ad67cf31194a3492315
    md5: 36521a15e54d7b9de1b60866af195872
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 71f97333219d35810b7093841199a2dd
    md5: 59daaf496f07ffa355d52635568f3d1d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a81b4198c4314c012b6ee4f4de576486
    md5: de79ac313a44738736c6d35d8cd937f6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ff4c376d077431ccd05589ce70de5c01
    md5: 6134ccf564d6bae0f8deecd67f32e169
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 145042d873701a89623005076d695f98
    md5: c4f2ec9106e3c16bf757c9209dca7345
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 04f755c81e13239f045d13fb2a9a01b0
    md5: 95b3e2a3eb40fdea4606634bf83969df
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: aec0e3f2642877fcba3822e0eeae0688
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_solo.res
  hashes:
    binhash: de945922d323881de8628262a602a5a4
    md5: 2407c26f63f4d3984f754501d76c9f56
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 27a4b9625b53bbf24f8a6ae7d6a8cf83
    md5: da071d0b0428fe665c01b5b5eff904c3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 78b58ff68d1b4214cd8019ada2d2e57d
    md5: ea19de0bd2da3552d9928b9957861077
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_tracer.res
  hashes:
    binhash: 4985f8e506e9edc0535d5cf199ffe09e
    md5: 84ddf03a0a20f8993d0e252c007f083a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_velocity.res.nc
  hashes:
    binhash: aa1e7e246d4d5103252818c733151f52
    md5: ccda165dcea53898d6735dab81de8c8d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 83d90393cefa3a2ce15a308b3cd49372
    md5: f45af719f3c2cf14cd82bc934dd4f7a8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 72b7036ab3c7e4895639153c22dae776
    md5: 06887d6e8a042000fc2058f65a26cb71
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart061/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 87e9137d5ba73455ef2e0e601c98d0a6
    md5: f8080426d9a214463d7667506074aca4
