format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/atmosphere/restart_dump.astart
  hashes:
    binhash: dc2391c8a6f89eec027fe55f6fd8a5d8
    md5: 214f94e10766bdf62d72255fdb39a7f5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/atmosphere/um.res.yaml
  hashes:
    binhash: 89a927babd59a7edba08be2c8ff3f861
    md5: ca4a9a836e8e8dfb976205cae2cf3080
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/coupler/a2i.nc
  hashes:
    binhash: 6ea8ce4795c60d6eca2296b95463c193
    md5: 90807eaf41bc89f81c76d9282a04a138
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/coupler/i2a.nc
  hashes:
    binhash: 717699ebba8da580ca74fed0c8e356e8
    md5: 62662c1cf0cacdd0fdf43b958a76ebb5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/coupler/o2i.nc
  hashes:
    binhash: e02b2e078b4a4a32a8858ab77592189d
    md5: df05923cde3e6a1274c0d9e3cc4793bd
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ice/cice_in.nml
  hashes:
    binhash: fc75e8f8ffae43c9f4148e7da3df8bf8
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ice/ice.restart_file
  hashes:
    binhash: de8196235811adb5e6c4ab2228adbb01
    md5: 39a201440ae5426c61a80dc856ae7b21
work/ice/RESTART/iced.2794-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ice/iced.2794-01-01-00000.nc
  hashes:
    binhash: 30dcaf56a983cb650ad73dbb4f65e788
    md5: 9b2b419abddfe8ca467c57b84b3e44ab
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ice/mice.nc
  hashes:
    binhash: 3e85927eef3a30df935dff39760cba52
    md5: 31d01ad9dda55a932960cf95ebebf8d9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_age.res.nc
  hashes:
    binhash: 38c95eb57a0f0582773337b16db64707
    md5: 8fa4fd303910a4a9470b6a39db4e4968
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c29bde2a141fb0332757ab1c1ea7f5a7
    md5: bc4436d0ca5f265e0f4eafae385532f2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 79683f749fae2838e2d6d70af4e19588
    md5: 474dbfbdd51783faa3b0c28a2a00fb95
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_density.res.nc
  hashes:
    binhash: f844450c545544e22630b54d00884bfb
    md5: 76803128ad0b959b361d5f9bcbf67c8a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b69ffa153084488f3fbad53b1d7dfbd8
    md5: 4e429768eb7d8f4a46695f1522d0e7ec
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e2f056ad187d1a0cad6fba6ea8274c89
    md5: 06cbce631514c5ca4276a396d76e2f7a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0aff46df105e199981e5d7082615e0d5
    md5: b0100148db627719bc7ca6811a71a476
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7af1aec665c8525898a5f38d58e9cfc1
    md5: ed984caf0639613402ea689c7b44186f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b979545a79ec8a57cb886679e2d94fbe
    md5: f053f4374fefc023017a6ddfe588163b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ebe621c582ef575e832112e41a102163
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_solo.res
  hashes:
    binhash: abdd82343145c5e4d0fa40564daa7664
    md5: d771ed7f6f221d2ca64707da78007085
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 625f1682a929a2b82c767926ecc8f6d6
    md5: 52a52a68789467a828abded1f8180135
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a0a56f20d5c04137df7d60f348c65329
    md5: cba2fb46979264c0f054f6555fd6b041
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_tracer.res
  hashes:
    binhash: e8f38d8fc45388dca2f2163cd4c1fbef
    md5: 5e4b3b470409444f9585f503fb50f297
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 776979960ecb89afea43470fe616e289
    md5: c7e17d69fa2e2e5acb3e11aacb4bdc16
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: df1dfd20d50e0fb651acd679c82f6723
    md5: eb74e6973c891f9898d79c2e1ff81b12
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7fdd6776b20f56f3683f9d5f74d0742f
    md5: e75437199fddd64da2876b52b5f92b28
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart117/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c5c8ed47ca2cc54efecc35cec8388710
    md5: 01de5266543fcb597126b9b2a5c13817
