format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/atmosphere/restart_dump.astart
  hashes:
    binhash: b5ebb99d7b4a99ce7f7cc5e50385070a
    md5: ddc76b4793b53521d08c08d86829fc2b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/atmosphere/um.res.yaml
  hashes:
    binhash: 8f4840f47d2e84068e481a2dfa8390c4
    md5: 755999f83542d2189bc3f443348333fa
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/coupler/a2i.nc
  hashes:
    binhash: e8fb4e5f1c7551709ab50ca96b707fe4
    md5: 34bf8f0fe5a389312100916a7d6234b1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/coupler/i2a.nc
  hashes:
    binhash: fe16829314d0b0192484bd9b5505cc8d
    md5: 18e132f3f566e9b69e21b57c0ca4e25c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/coupler/o2i.nc
  hashes:
    binhash: da353a993f5cce2ad7aae1acf7d410bc
    md5: bb6bb790169bbc9b20bb1423df56fc53
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ice/cice_in.nml
  hashes:
    binhash: 47efd350367fcd7cca3442b13f38c667
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ice/ice.restart_file
  hashes:
    binhash: 4dab78937c67253b5d1e7c2df9ea4449
    md5: ec4291c49e1e61012e04c92073fe4124
work/ice/RESTART/iced.2937-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ice/iced.2937-01-01-00000.nc
  hashes:
    binhash: 0ad28dea263d9f3bfccb428c34d2a186
    md5: 84a300e0117b49106a2bada1b1293a6b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ice/mice.nc
  hashes:
    binhash: 33cd356043ccde0b06db7637bfd1a2da
    md5: d820b7f3a2cb872cd157f5a43cc433ad
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_age.res.nc
  hashes:
    binhash: e28dde68969d90c6a8372d3555d5747f
    md5: 6e8001e9c8f9ca666c0d1151ff867831
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8f4ccc51da23b0186fbfafc581ad5dcf
    md5: 482e8d1d671e7d519e73cda249580bfa
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 916f4ae3982d12f2e8191709e0887fb8
    md5: 0464d03116e147a8bb96f1e390ff10fd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_density.res.nc
  hashes:
    binhash: bb10b5bb1928b5de159ad8d86afac5af
    md5: 3f21333cd21fd2d76d4dd90cbf68c644
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3d24d10b589241b296cf968b4c142d3c
    md5: 5bcbc76cb8cb50e76fd7d060e90f01b0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1d61e07cd735dacedb296b37488881da
    md5: 55e9c2a03cd48cb6e9cc4053c391f7b5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8bbbf443da0d046163315899cee2f390
    md5: cd2cba88f86cddd5aaf1f62660d3cf1d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0f98bbcf30d8b6122643b12ead63ad8e
    md5: 503ad8f4bf29c2e7c18212c08e1df74e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9df4b88ef39a2f7d2286dc7e40a4eb76
    md5: b24880034e977b59d6e714fed8d76c24
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3f686bea6d9787ef7e2cbf574d2cd691
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_solo.res
  hashes:
    binhash: 7554c8eccd04deb602bce97419ca23ce
    md5: 4855b51a8a1ccdb0f998986d60bdc417
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 28ef7b4975c4e74fa270d45bdf551b0a
    md5: 58fc5867b1b25f250e993d79a9145ed8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_thickness.res.nc
  hashes:
    binhash: efcf9457a8f90b495d2352dea90c1876
    md5: c024003bade775cc8f22758e0332d796
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_tracer.res
  hashes:
    binhash: c417f9f5200e9912eccaf5a2311de72e
    md5: 64dfb1b4e6a74b3b608f17f5cad07286
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d1c8beb85356b266aad1bbd074cfdaca
    md5: af14c8ca06511509aef9c7d7afab42cd
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 39acde6b92f3c77a1bc5d59cb8dfb7a8
    md5: f25ef1881f1053407db8f180ca747803
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 692439ab573dbb7e41eea6b418f4c0a6
    md5: 1ec1b4d5fcc6bb17cae073911edc27d4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart260/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 785e8944cf43a0c90962d975dcebf02d
    md5: 7092c45e2fcdb7cc5c463c4dca3727a4
