format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/atmosphere/restart_dump.astart
  hashes:
    binhash: 2f6c28abc83d82cd3f48090d1d71bc60
    md5: ac4d83a857d8e28d31d1d5c349b3c83a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/atmosphere/um.res.yaml
  hashes:
    binhash: d9f45560bbc961c2ccd6a09c6e8e8a5d
    md5: 327651b4383a4258c7d29bd917e5e8ae
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/coupler/a2i.nc
  hashes:
    binhash: 6e387e6fbc034a5f75d521620c2376e9
    md5: 61005d7a902df2542de15703d1f1118d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/coupler/i2a.nc
  hashes:
    binhash: f21b373b9115d03d3ba2828979139ba4
    md5: 7afcd9b855a02fe5984ffec43d1e7d74
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/coupler/o2i.nc
  hashes:
    binhash: 07da41fb5860f67673e24df59d3d867f
    md5: 0f0ad3dae862506d82935f78af47f4c6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ice/cice_in.nml
  hashes:
    binhash: ec7fc47bc9e782ec8071c28b62391887
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ice/ice.restart_file
  hashes:
    binhash: d079464044aeada6ea6e8de3233c6c6b
    md5: fcb6221168b743120a5b4295493c3406
work/ice/RESTART/iced.2716-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ice/iced.2716-01-01-00000.nc
  hashes:
    binhash: 3bec8368af81eb5cd9f3f05841c22a17
    md5: 56020241132c0ba6a5897915a8ef85b3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ice/mice.nc
  hashes:
    binhash: 54c2ae7019affabd5badc5537ee6a8dd
    md5: 3e1fbb28911aa056e6e78a6e0315c2e7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_age.res.nc
  hashes:
    binhash: c735cbe6afdac9dfacb4bfeff0980e99
    md5: 7b0459096ae6d3fe142dbc5aa41d8a04
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b11a1f1d483ab11af0c80e1a56f63283
    md5: 0240557fc1bd6e643efb52fcda6e46cb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0c2a9e6eac83ec9f49ff5690b62dd15c
    md5: 7fe48367deb28f78e9281bf7ec05a2ab
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_density.res.nc
  hashes:
    binhash: 9f8dbfeefec4e4d08b42a45b21ae4fdb
    md5: 59092fcfce8c71d134f0eaa9238b5a61
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_frazil.res.nc
  hashes:
    binhash: dde90acc5da4bda051611c56f8a36555
    md5: 888ab23fd6af016ef1b0a4781db9e635
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0c9baa4915f73397844890ef8dc51003
    md5: 268a7e8d5d5e229b16c0562b290929e0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 71ea40f50592327739b9e2935b379cd6
    md5: b4a2076972054ee3d1c8986d5a4be99c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9422f2ee7e84a0ac7483b8676b09b06a
    md5: a365b415f6027972b4493bb3721badde
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 23e69db20c58e540bd16317b61738736
    md5: 369bed2bd315f456e6a7455f594471e3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 02ea2b0c78502e8a2521f35093966986
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_solo.res
  hashes:
    binhash: 0fc42092080708f358bd20fda6907e5d
    md5: 4decad11ca45e6090b6ac2bfd5637cbc
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f118530be80bc6176710975218b9d0e9
    md5: cbdb5efcd362daf915af2ff689961264
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0451e7826e7e9a7589c1a45e6b0860dc
    md5: 444bbcd1f9e0bb31cebbb17e75bba03b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_tracer.res
  hashes:
    binhash: daa9a896a33fb1da1d4305669e71feee
    md5: eda7d1553e9846a10f30b5d33fc31062
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 040fbd0db86696fb1df93fee9f7452f7
    md5: 3a79f233572561a69d19314d4abc1c03
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5a452cd7897df2bc1bee1ca351f2509f
    md5: e2549c9ec4050d45c54687743c584fe3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: dc1488f95fa694a783d4b8d306dab157
    md5: 8ab293b3dd89553681cd60f7bb0c6619
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart039/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0aee49f38a9047bc3b26b1cbe37500ce
    md5: 8eefe140741fa4df2bfe3e87d2f0228e
