format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/atmosphere/restart_dump.astart
  hashes:
    binhash: ca39fd74a5037fa610bae83f930f140c
    md5: 42997f865e85e95ace83f88fc91b549c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/atmosphere/um.res.yaml
  hashes:
    binhash: 0eba78b95dce7a3dec337d1b060f8106
    md5: 0ce525bb6cc09bc765a4e030683f7bc7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/coupler/a2i.nc
  hashes:
    binhash: 45430fd39788195c8a4d173b429ac1d1
    md5: 12d178ac438cab1610c8de0921c401a7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/coupler/i2a.nc
  hashes:
    binhash: b4de068e614cfb40abb7f25f0d8fddae
    md5: 0becb5a5387fef84df5d3ddc1bea96e8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/coupler/o2i.nc
  hashes:
    binhash: e250e4eefd3ac0dda581907a1998e01d
    md5: 5fd3efcbcd481b60d7ef513aff54f905
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ice/cice_in.nml
  hashes:
    binhash: 2677ea29c2418239cfb6ef269ab6e52f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ice/ice.restart_file
  hashes:
    binhash: 36a69ab2195a0e268710e4ef52c50632
    md5: ae8944b7bfcb7b30f3e60449548eaf28
work/ice/RESTART/iced.2834-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ice/iced.2834-01-01-00000.nc
  hashes:
    binhash: 074c4a8c0b52e4d0216ff20a59cac3f6
    md5: 43db36cfdbab0986003d1b7ceeb37931
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ice/mice.nc
  hashes:
    binhash: 563ee4b768f8a788aafb963cc85375c3
    md5: c0f87d98770767af213f5cc80dc515fb
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_age.res.nc
  hashes:
    binhash: c968529dd139f25a727b7f3ccbb4a18a
    md5: 3e8030c50375336a18c8b74f8568335e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 20e421ae1ca7be901968108e6f6a1c73
    md5: d61355d676f73ba589f8b72f99badf8f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1f68d7d2935866dbd2195b410a11fe74
    md5: af042e2629ffc38028369e77ccd9c07d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_density.res.nc
  hashes:
    binhash: c338558fa2fa7b06645a5c984e0aa9b7
    md5: 673b543fe90074ca2c72dbc2d1bcfdee
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 63fd6543a7cd3e75d2df4bb2a206f232
    md5: 7303116fccaca7821652b4e28d2de75e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b4c828dcc3d5a0c4207d927ed3060218
    md5: 85655adb11d7af611cc0e1f1885ca0cf
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b4382c67b804484fb1ab264ea6940aec
    md5: 0bd4113d7a4c49abd6cb0a095e0e5cc5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5d6c4b32cb41b2972b159ff1b4120b27
    md5: 08ba2f8479900fa06e0413ac949799c2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 05627e5f317e8ed3be398a2ed92dc540
    md5: a003998022f67f8f1bcbcae08d2ca182
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0be16f16007e4f43629d6fcbe63c8288
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_solo.res
  hashes:
    binhash: 2961e2f2e0971bce7dbd495c66e7674c
    md5: 3068311d8cf2cb6994585320d3c6e2cf
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8e786ee0d474f412e0f0bccf60885fe9
    md5: 2e488a31be4ca2abcd8e98bc3bcb7347
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8e63459b08d7a987274f1fdcd27da7d6
    md5: cfb071625e1d370d34b10a1719f672ee
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_tracer.res
  hashes:
    binhash: 0c0a66fea2ec539e10a6bb227f6a28d3
    md5: 30ba7b6a44e90b8b0fa45ad1b5703103
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 80d5803bb6824564e7b3f04f52880813
    md5: 270ba7d32449236755b41128a9a40d40
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 672df483120b64b099504e5194bc3887
    md5: 7d42604aa8336ea30ca82bf762595abe
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8adc11a7bff446196d71c1ac2e27f3e4
    md5: 271a4305ec20722ff7e091e5814b31ac
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart157/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c19c289a30a2d44b414f88e4f86f7206
    md5: 136fbdcc03a41eb130bf96243c209e80
