format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/atmosphere/restart_dump.astart
  hashes:
    binhash: dc84b68ab4ba7080bc36905003748d36
    md5: 1da318dce2f81be362b0d6f970b9e437
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/atmosphere/um.res.yaml
  hashes:
    binhash: 2d794b2064c3a5b61c3a57a0a9273440
    md5: 3036632effd1e5c99f06a44edb597c8d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/coupler/a2i.nc
  hashes:
    binhash: 34e3f0d2a6d7b3c2e506fd4ddb3171d1
    md5: 5b169359ef7d3bf66fe781d4f630272d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/coupler/i2a.nc
  hashes:
    binhash: 850b9e6c2013d69d6564b836b02a2dcf
    md5: 20e151f6299d5562ddffab6f392e455a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/coupler/o2i.nc
  hashes:
    binhash: 6061225e5d051bab7c24ad9110f6e6d4
    md5: 4c76cbadf82bbd15e1d10743d1aea6c2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ice/cice_in.nml
  hashes:
    binhash: 02f62243c01cfec4b221cedfa9c933a2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ice/ice.restart_file
  hashes:
    binhash: f91c21ceba542ab2eb4e32d4423fc6d1
    md5: 78935f5b6e643cdda697fe09b0a94a51
work/ice/RESTART/iced.2836-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ice/iced.2836-01-01-00000.nc
  hashes:
    binhash: 2e9f367562b6eb6f0cc6986babca8cd0
    md5: 639b65717121a431e2860c6f929c99b1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ice/mice.nc
  hashes:
    binhash: fd0c52573aac128f832972416780aac1
    md5: 2880fad3b7507d10d4bf9d94f2e6b299
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_age.res.nc
  hashes:
    binhash: 275a1913cea1530f7f9336ae89b882a6
    md5: d228cb0aaa77dc0ba42c31ff4f5b709c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c46bb7a97d3bbda3af45de2c272a77cc
    md5: 578f69a986d437e08e7b238bca2df6ad
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2d64111c709a999ca790376cd2410889
    md5: 943e111437eca126a7f41ab449d31b83
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_density.res.nc
  hashes:
    binhash: 0f9936abbf0c5f0e7cfe3b9e1979f04b
    md5: 03887dffd199fae5165e515885b2cee1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 36c32c759834ce3f07c0bfda2c684509
    md5: 253cbdb3e4bd1e664478e3c8c2778fbb
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9c1171ad68b35adc9b938cc241fc6eed
    md5: 312c5117ada20e42d365ef3f091f26c1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ec3f8ac0257fab92baf0e1ed88cf6770
    md5: cf62072e715856c087d365416c682af2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e066dbdae7816e90714a04b05e1e674a
    md5: 28d35fc61438deec9b80ee3f59e6e38a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 40dc44b88e897a1a52caf9632666cb2e
    md5: 025711d90f31e5157b99cc2b8ca4b237
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a057218f097c22d3afaf838a97eb82eb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_solo.res
  hashes:
    binhash: 3929c717660b5cf0ea1faa31bf5ed856
    md5: d54891db05515dee3a507ab8d9f1ee0f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cb7d212e92bf43ce83716870d3c9f29b
    md5: 800c029a0efaec1f9d277541a4b85e07
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6cd493f74e51d73e18f6f850e89acf58
    md5: 0d96fd9054ddad2ce42b330f3e27be41
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_tracer.res
  hashes:
    binhash: a20f620e077f929d636692189f1d88f6
    md5: f43195ca629d31bdcdf226918a67d92c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1209aaf4e5409c4ab75290231e20a698
    md5: 7a016a8d22436556080348c8da172570
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 80b34dc284b5fa4374961bd4cda4828e
    md5: 63d190afad70c9a0b83563e1a71111ff
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4a5f3f05ae9a5c5be86008020b98aa20
    md5: 0911c139c1ee78553fb948383929e4e8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart159/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2a9641d94953e8a57e161b65c6f34f61
    md5: 1ad85caed58e6ce5afb2029c0837cb8f
