format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/atmosphere/restart_dump.astart
  hashes:
    binhash: 6be827b3ba08209651a615b9da530a58
    md5: 5f29e194c355afcc4b6402ab488d42f4
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/atmosphere/um.res.yaml
  hashes:
    binhash: 5cde051edd381e0fd2f4ce7d62ceb5a5
    md5: 722d4b679e2f703c61825790df8544f2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/coupler/a2i.nc
  hashes:
    binhash: b9a9da28fbdce6e5d576bd4fd8f5bf23
    md5: 7d0f2a7ad16647e86c514da1eb52b3e8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/coupler/i2a.nc
  hashes:
    binhash: c0404d773bbb447391a16906d715b102
    md5: 2f80337e0c07ada18a06486b5814800f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/coupler/o2i.nc
  hashes:
    binhash: 11ef1e3cc524660e35797c6821f377f7
    md5: 863b31f88198fc2c8ed1bb26891349ad
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ice/cice_in.nml
  hashes:
    binhash: 14dfaff84521bc57dd8cb26e7e797ac5
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ice/ice.restart_file
  hashes:
    binhash: 0d9009ae5fb43639bd582ce0e6dc7175
    md5: 430a0d0dbb428af73dbd5671d7ae89bf
work/ice/RESTART/iced.2779-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ice/iced.2779-01-01-00000.nc
  hashes:
    binhash: c9df8f4a058becc47c1f87daa0325a76
    md5: 0b4576d9d03733f66f76b9f2e911ebae
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ice/mice.nc
  hashes:
    binhash: 078d2fa07886fa7de8297ac22edb1ff9
    md5: b913bc7e5a4ed12aa2feb7b830d14e8b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_age.res.nc
  hashes:
    binhash: 64aefd007edaf4143a7e6b1aafb5b59c
    md5: e6b9f185008aa40eb5ee0f8ce191560e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 49d0c3eadf1d3a45550243aa542514c7
    md5: a159a49a213cdc1d235860e29a5ec2fe
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2338e6d7fa76d428990a996b35a1cf9e
    md5: b330b83cd8f3898d05e864fcf9b88152
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_density.res.nc
  hashes:
    binhash: 6d0416fbbb0c3fd5293ad4e3a4280c3d
    md5: bfca700014f72951476765b92e50e5ea
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 53f7901ad1310e3fc50181cd5165d648
    md5: abdf560be87f153f40224588b673599a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f63bfda0404826ebb6f00aef049617f9
    md5: d657a8596a74ab2ca0f5d373e4e748e5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0d95ce910eac4a130978b36cf3b0a6f4
    md5: 389c11fdfba98f581747471de50b4faa
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 131d2f67c84c5bb9ce7eb10ab8ef7462
    md5: 7e36d993ada573e5fb5239e4c7d40f2f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f8c146f59a7cb823aaa18bfc62b303be
    md5: 92aec1696bf95f488d2714ded90587d6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 11b5799693d077f215b591d5fcfefc82
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_solo.res
  hashes:
    binhash: 2927a2b82c77e117892450db7c04bb47
    md5: e05a8cce6e0373d5d936f34efca8463b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 033ae826638785dba0e5df1c02696d03
    md5: 14cbf1e5015d8af4a0d367285ff306b0
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_thickness.res.nc
  hashes:
    binhash: fd98da7cb3458a0885da4c1dc4995a21
    md5: 018a826f98e8b512eb1af7579f853a4b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_tracer.res
  hashes:
    binhash: ccfede3d294f2bba81afa633ea78398d
    md5: 230b3787643b75c2d015b7557dee14f8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 939b65f990f8206d65c64a0ac9890edf
    md5: 4b7117668d1d725bbb7ba478ff03b88a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ccbc995aba5e46ea40e99763ab58b959
    md5: 273af4684f2fa6733b0726ee72b15301
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 461ea29dea7e811f0044096a37fe9e28
    md5: 46379a68e60bbc2e968a6aa06c1b1a6f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart102/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6e9e7fb7516f30b0c3df68c0d4c28463
    md5: 724b10792cbb440481a6abde6ef908d0
