format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/atmosphere/restart_dump.astart
  hashes:
    binhash: 416f1b6dc3f5e52ba9fc50fb47d991a2
    md5: 51d912f2410ee15bf9e57b9c52b7dbc3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/atmosphere/um.res.yaml
  hashes:
    binhash: 1f2e34aa222aac1ec1b7e2976bffdce3
    md5: eef5c3b5bd92f1e397e9c948e69f65f2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/coupler/a2i.nc
  hashes:
    binhash: d0ecdd6eda44a93c56a3dfc9192eaa85
    md5: bca424ae7301eadfb0b4d848bcac7256
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/coupler/i2a.nc
  hashes:
    binhash: 1a4158ae4ec2fe09bbbf560d137603c6
    md5: e4d0f10688078993617d17102adb0812
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/coupler/o2i.nc
  hashes:
    binhash: c7bdb86cb5f6130a92fefafb7b00b6b4
    md5: bcc856de051a8cfb2f379eea1929b641
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ice/cice_in.nml
  hashes:
    binhash: d23ca8d14fcd75159df7f944cdad9cf4
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ice/ice.restart_file
  hashes:
    binhash: 1130eefcb8a0d7577511f316bdb7c2f7
    md5: e0401a5d6929e9cbdbeed4e46ebb69da
work/ice/RESTART/iced.2751-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ice/iced.2751-01-01-00000.nc
  hashes:
    binhash: 2f79bbf02c6d5507437613ea3fc68eeb
    md5: ec04695e7414c98d01f0effaf5711eb5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ice/mice.nc
  hashes:
    binhash: 83e1f28307fff768fe996628a5d8da10
    md5: f715a592a3112ad2dc2d3fb3e3e22734
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_age.res.nc
  hashes:
    binhash: 680d04b46b73ae9ecf8b8aa37101e929
    md5: 175967f038dfebe7d6506bb9b3c93808
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e5322fe71742cc837aca440667a65c86
    md5: 8de24234c546565010964146f256abf9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a3998235d342e49c7ea63ede3379a2a3
    md5: c7478d0cfeae799cf2c37431e7c240d3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_density.res.nc
  hashes:
    binhash: caa03d700a58e70bdbe58e690bfeee05
    md5: 15fa58eb41a6949f55c50140f0a4c4c8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6f3dfa9f970ca8f16a99f0c67947b146
    md5: 82bc2565eccefa0dbb51f1767abdb07f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e4dbd452fa024a344d2fb7ff85736b6a
    md5: 3a250fc490ab9ffbce0bc160e1447390
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d41051f46f5c7fc24b2b283f57e4ee3b
    md5: 5b8555c5cb72e5c0a923a5461940b5f4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 43d29fafa71a8887d9b9efbbee64819f
    md5: 846af1f85c243e9d5c05dfa848c0bda9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f4f01e439bee0d9c417d5bab98857999
    md5: 5a1c8641c0ebac7c29c6caf0bcfd1767
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fffd7255b7d2a5be2bacf9b9a95aca80
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_solo.res
  hashes:
    binhash: d8673b6adf763e656b3bf76131f587a8
    md5: e5a2512d2e84ec1cdbb6c9ed2eba79d7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 04adf6da24daee2db3c399a4c02c03ba
    md5: e606e420807a6bdad47621aaca3b8056
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0e05f53cef4912f8382f8d69de3adf95
    md5: a2657b7bcd27ab04e0f44d183e3a1286
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_tracer.res
  hashes:
    binhash: 11fd4e3a668f5413aa786290bc571cd8
    md5: 37faf75876b8a32132c9faf094018674
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_velocity.res.nc
  hashes:
    binhash: fcf2b2aaa1463ae78b446f55220e24d9
    md5: 326deadd06d1a57e2655b90e5e62b937
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f9eebe1f9bb8c01938f6769a370145ea
    md5: dda28d04d32cba6ef68a94de07fe0961
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7e3f269215357a189b1d6a30d60158b8
    md5: 117480fd34c2a9cb4bf7ef72fa3e4c25
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart074/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e2a80a86b38f3dfab7038605926b7535
    md5: c25b30c15aaf7c0f4e85891a46110c56
