format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/atmosphere/restart_dump.astart
  hashes:
    binhash: 26254fffbd73ea9d46e414276e3e0e13
    md5: 21fda337a965e25c91f4e439082cad40
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/atmosphere/um.res.yaml
  hashes:
    binhash: 83946cdd13edd619f121dd5d6499a5a2
    md5: ad9122ef271764852f807535f47e7a7a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/coupler/a2i.nc
  hashes:
    binhash: 28883765698d4e88deb6c6826a4658fd
    md5: 2bf589438163c1a6c9b870629a507a58
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/coupler/i2a.nc
  hashes:
    binhash: 135fb572ddf698998e575606ceabdd3c
    md5: d5aa789f09a163386d4add3879f62b02
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/coupler/o2i.nc
  hashes:
    binhash: 339ea2ab6414fa55ad8f3ab711264d9b
    md5: 5905c03a7787e2d814ad8431f7130e12
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ice/cice_in.nml
  hashes:
    binhash: 09541b5c6199e7f2b9a4966c8a4f80fb
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ice/ice.restart_file
  hashes:
    binhash: ded51951543f78c03fc0dd2b3844e60a
    md5: 70df334dc7ec938bf5231c765b2f6a50
work/ice/RESTART/iced.2688-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ice/iced.2688-01-01-00000.nc
  hashes:
    binhash: 0f3a1cda275a04384c16ed54e79a842f
    md5: b13d04b2b7c86d77fd01ad599917e328
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ice/mice.nc
  hashes:
    binhash: 294fc138c9ad8e17fd97b459a680d34f
    md5: ebcf2e26b14488bb9b7d8ce27beb14d7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_age.res.nc
  hashes:
    binhash: ebb5a0c525deb7733358f08409e1e448
    md5: f75a5477cbc1ba2e664603cee626c58c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5ab256b5a9f0e09b82658ea04efa2f8e
    md5: 73d45fcfb5d53158009165b4014f7963
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bfd03c4be3ae86fd023aff4488bf88b4
    md5: e8181d93bb0d364b76f4017cc24f9670
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_density.res.nc
  hashes:
    binhash: a5dd48de8fd2cde681469f49c802116e
    md5: 3fe0bbbc8f2ee6c19533730479f5c5a8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5427e04cf52707b492fcc862c08b4af5
    md5: 7006994df4b3550aeaf0a522d8d8ca1c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a9724ab536aaf61d09d13b7faa89e09d
    md5: 1328e2c9ef354dbc8d6ff29a75da3c33
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d0fcccf002defb981d93e5c191f6fa91
    md5: 4f7ffa2629e1a3f6aa01178648f8ee6d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 554f771498b0941fef3d6d6fa9f377b0
    md5: 92186212e96e64762a9f3a9820ad9c45
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 49f512260776a6fff1bc4c93c2abaab1
    md5: 3f9ca7aed4424004052628629faea96c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7a5e48c68084707dbac3f64d0bbbf5a1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_solo.res
  hashes:
    binhash: 438d4222fd63b620085bf0d03d48e145
    md5: a1d9fc40431f62bea179cee8c855a100
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4e98a940a3e7e930d9bc39ae537dd57f
    md5: 116fd70ce83468561e9612a51bd2e7ab
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 571949b199a9f16066bd7203b3beccdd
    md5: 95f93b53eae1c9c374df81fcb6c6bf9e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_tracer.res
  hashes:
    binhash: af40f5151dfeef11dcbe687bf0d537b5
    md5: 4bca4abff16100a88488c167165500c2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ba90bb9560e13b0acd21eec8d37edf0a
    md5: d56958d0ad4bdbea1cffe0872bb4724d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a62f5873883bc83bb087fcf1ad620c8e
    md5: 818d6325468f649eabf71782c8564a84
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1b0d364e114676dcd48a82834cdc8501
    md5: e7e1b49d3133d50be880b6518f29e17c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart011/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3a4f5da2547f9279598ce697029ab3ea
    md5: 678190a1a2ebf17966dd37d605ff118f
