format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/atmosphere/restart_dump.astart
  hashes:
    binhash: ca427ffa04c75efa1ad9d5e2f197ecbc
    md5: bab739ff12836b61e1b96f3086cb1747
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/atmosphere/um.res.yaml
  hashes:
    binhash: 02961ea88d21297f52ac21652684ba9a
    md5: 5e6068423d8e52686af6184f95804589
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/coupler/a2i.nc
  hashes:
    binhash: 1b7055fbef48515664567fa1b945fdc4
    md5: c16ffe92bc6c492b1800c32baf3f0487
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/coupler/i2a.nc
  hashes:
    binhash: fa838dbe963af32f0dcdee703c0c5510
    md5: 1f5eb9b63c1c17484462daf2bbd5f138
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/coupler/o2i.nc
  hashes:
    binhash: a7ca81dd7d389c94a9983326977b00f5
    md5: 654579a2ccaa26ca19f9f1dc8d908c57
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ice/cice_in.nml
  hashes:
    binhash: c53170dbeedaede826f40585721d1c81
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ice/ice.restart_file
  hashes:
    binhash: b8fd8e41ec624098af540eb332c9ab53
    md5: dc2f7f8b5926a0dd5394c83ebda78a3d
work/ice/RESTART/iced.2856-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ice/iced.2856-01-01-00000.nc
  hashes:
    binhash: ee62393f595a3e342cba39c3a1352d87
    md5: 3ad00699d9acc7142dbb23b4fb07a0bc
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ice/mice.nc
  hashes:
    binhash: c8ba4ce14736a2ef510c9f57fa0a3b39
    md5: a644c8bd347b9bbfdca171160a6b689d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_age.res.nc
  hashes:
    binhash: acca222be0d6d58226228b00b4fab04b
    md5: 75cc78feab16af3daf1ded0d3d9d49d5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a099371ab82de2136ce0555c8be17736
    md5: 19c14a94a8fdd60e0556eaf7d117e46a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 460274d44e3ead450822277c8435175e
    md5: ccab90bfb84829a89035ed73c6278fc5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_density.res.nc
  hashes:
    binhash: e8be5fb7ff6660097a5378d3aa0ea13a
    md5: 10a56fb1c363a770b3ba8d17a9f0515f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 68add656537f1f6f469512f477329448
    md5: 1a00022b83ec5808e8f84f876e60b33c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 98c6e68036358c35c6d15678d810df59
    md5: 8e7b2a3394d2c7fe049354d6400ad2a9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 031a3c1c3159421ce1dbda26364e56ab
    md5: c52e682759be35b485589d1f80e84a23
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b354baca6b3c92c4b9a726385336e20a
    md5: f0c1f6e1dca2fb3316a4bcc1f8815b87
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0cc526859555cad653075cc2e1f4c497
    md5: 23cae1a8f44111e5c604bb66603ea432
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9181b6a62a5f563b37ddd977144854ad
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_solo.res
  hashes:
    binhash: a8bc0d78b6b39bdfba9c8655fe9ee1d1
    md5: 3ff6436f4ae7fe48959fa12541f2e3df
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3ce17587f26868ec58d80dfa7b498ad0
    md5: e15f1ab4c1134adc07db033b77c9461c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 07113f8b9148241513b26d1d6d3fc2f4
    md5: 1fdd2d8091a7bf1d65837468339f7722
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_tracer.res
  hashes:
    binhash: 5f0426d2b871ee8ca483f106992e0ba4
    md5: f089da7709be5d4e6fbcd89ddeacd1c2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5a603c5e8e7308b7325a2f3abf09d72b
    md5: a58cbacefcd69708abe1a39e833d9a8c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2a5e56986420668b57e2f00a95b769b4
    md5: 23589882196b22ee0db65be05eb6130a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b211daa802bd293177c2253c2c80d786
    md5: 9e67f66cdfc48548c25e2a90df4696f8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart179/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: dd4651e521e6f6e1e13027b694809199
    md5: 70ee0d5da12251b4ed4ec9b453a3ee4f
