format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/atmosphere/restart_dump.astart
  hashes:
    binhash: 74ceba3ec5107f5c3abb40c3287e1c27
    md5: b85058cb1ec57566d3f816744ea1bf78
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/atmosphere/um.res.yaml
  hashes:
    binhash: 563aaf30c5680bde49448dca4f71f448
    md5: 9646fed8df3394e5ec9a11f965de0164
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/coupler/a2i.nc
  hashes:
    binhash: 7d084a795ef6e649c68b59a52936babe
    md5: 626cbeabcada4041d311f90f7a8532a4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/coupler/i2a.nc
  hashes:
    binhash: f9c8ab958b5049d293a9d23a2c345d30
    md5: 6951ff98508dfd46b1d358a7ab5cac05
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/coupler/o2i.nc
  hashes:
    binhash: acbb95fcb8f51d240040a5113f5ca6a2
    md5: 49cb5702ae2ee1b50845db332d2da46b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ice/cice_in.nml
  hashes:
    binhash: b23eb5d762286fc08e4c43b176fe14b1
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ice/ice.restart_file
  hashes:
    binhash: 25745c6a6c1fc796a094a4e2d53adceb
    md5: df8ccb1dacbc484f821586018f41333c
work/ice/RESTART/iced.2901-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ice/iced.2901-01-01-00000.nc
  hashes:
    binhash: 2f3f9d122d0144e4a94f43ddc2a5c7c3
    md5: 0b44ea570da716d9030a4680bc23ea5f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ice/mice.nc
  hashes:
    binhash: de84fd036bd85082b4ed77ab33968913
    md5: 2066262cff145dcd7dfaffc55a177162
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_age.res.nc
  hashes:
    binhash: f60d8a4d31f43f85fe806bdb48711d7f
    md5: 19f0868c91cdeadbab27746a0980a86c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 833c459767848453dc1698b8c4c7dfbf
    md5: 20e8514983fc265bac322d9e66e8fd60
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7079c2490f6ad3b88395f266269099e1
    md5: b2c29e3da0b84655ae15e82ab212ea8d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_density.res.nc
  hashes:
    binhash: 1f9c4f785364c2a681102350d33df406
    md5: c49d39c64d17cf48b6ee883f72f4d988
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0e11b2911b6def238c7c1c74e506dc4d
    md5: e9f71e07b3b0b6533e53efd17c3417fa
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d850e23f017c66245a4bea10009009b7
    md5: 10228610338987c1daed9b5f98902fc2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8914b7b87cb70298a06b7c47be1f5b85
    md5: 63f3b5bf8e211d7632f535864e88b611
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5bfc8911c5899c839de1ffc6f5793ab8
    md5: 2cd5dd05164ecae1afbea1a4a29f8152
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f21fd89e0660279afffc38b62b62c3b2
    md5: d715bf380ad31c3011982bbee4b88d66
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9e3642bfe8d81f77057304aaf39ef439
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_solo.res
  hashes:
    binhash: 472317ff51302cbdea80039553278b55
    md5: 2453d95c5254818aee9c4d0db51116e7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ecd978115201d28cce641398e7e77fc6
    md5: de8219c8a0b0e12aafafce5a468b206e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e705572a65231cd504c7df8b3e07e6ff
    md5: 4842e16a9d3ce9a35ce2e26bdd157576
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_tracer.res
  hashes:
    binhash: 07ea280c7ab8d744e5763bf6b7fd91f5
    md5: c9edd2bc2a34acf7fc1da2275ad6e743
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8cf094a166f460d964ba344ff6d2ffdb
    md5: ac57cba3565ec3a171321bbb8bc62f3d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 012e8f4939657b117c69da751b1a4e2e
    md5: fddb66d3fb969e23e11342c489a84d26
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 86d40f6473519f1a09f9237a36726463
    md5: 4695670abb40070cfaff89cda1d5b758
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart224/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 65f8ea37ffe272d851f8c531378c0991
    md5: 619cb4c2dff5571829804823ccca0bc6
