format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/atmosphere/restart_dump.astart
  hashes:
    binhash: 291ccfaa6ad15b14f8f72b0c4be6e59a
    md5: 20cef5a5f4ba304db717b04a2da6de30
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/atmosphere/um.res.yaml
  hashes:
    binhash: e1257a3fd66c50deadb68ae565b32cbf
    md5: 8237a0a7226fb7d677464f341e00cf46
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/coupler/a2i.nc
  hashes:
    binhash: dbcdb980899cde9f1703a04456b235a2
    md5: 6a84b17cdabcb95d11ac5e96d3f1dd55
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/coupler/i2a.nc
  hashes:
    binhash: f7f651b5902c4ca77f2d26edf7adeef4
    md5: e2e9f9d1218ae482b0fb16b4b39e8d0d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/coupler/o2i.nc
  hashes:
    binhash: d7b5234f1123eadac998f138e876914f
    md5: 09720a5f233c2b9a59f5303930ba57d5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ice/cice_in.nml
  hashes:
    binhash: 3b7b860b6e16ccdb7dd2674141ef874e
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ice/ice.restart_file
  hashes:
    binhash: 5121c6526e752846487f83651fb6793d
    md5: ff334faf4fc78430ca0bad3149388831
work/ice/RESTART/iced.2792-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ice/iced.2792-01-01-00000.nc
  hashes:
    binhash: ddb52001cdd79e5d99a7556ef37ae9e7
    md5: 8f875a3d694f6c3f1e52613ff58ece67
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ice/mice.nc
  hashes:
    binhash: a65ac4938026257b1ebfe3992e52c424
    md5: 74dd61abb771776e4221dde106bffd66
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_age.res.nc
  hashes:
    binhash: 34a2b134b9ffda4bf3730274beb1391e
    md5: b62713b5437f50c31aace6df96b69da3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2764e23e0f085790ad3a07aa5a1400e6
    md5: 0fea031162a31347a5a9c580b067215a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1b30429ebce661b17a65cbe7b7f60d5b
    md5: ffb5f25217e96b77df469050427bd9bd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_density.res.nc
  hashes:
    binhash: 187af63ff4b2f8c71d037f656183bce5
    md5: f85e1edce3daac5c501528a13b6833a5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e771f895f99e934eb12e0920ce514989
    md5: 0d9be858bca390ede56ef94cecb55aa0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3a3890f466ae95cc68b9a517f87182cc
    md5: af9300e3d41316a42912454eba6fdbfe
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_neutral.res.nc
  hashes:
    binhash: cd390da220edda68894c9e51c9ba4056
    md5: f81db392f70544a5e7228d65292f3ba6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: dcd6a16854457ff221a08bb17e2bf987
    md5: 79111ec6a678a4e3bf3d8f540caacf84
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f61893c725e03ec509244a94b28d6ff2
    md5: cf864a291d7f107c30ff7cb31607fb81
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c5483a65ad365dbf9b15bf0a51109910
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_solo.res
  hashes:
    binhash: fda301210b7c3de502b4d62b9d39dcaf
    md5: 4f73d0d30e19aba151fb4440a17f8d29
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9ffadf5c92e18a0387c731de91480f12
    md5: a3d446b392e83ae651313f9084f2ae9d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d60e5b0fa69e254318edb74d0accc281
    md5: 739b0845a7acda5630e9e52a119d9bd6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_tracer.res
  hashes:
    binhash: 9a8798e83a4268c0cfe535e961ae490c
    md5: 8fb159b6f73f0da7396eb4ae1fab1725
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e21f26c62ec43374fe36888d192d69c7
    md5: aecc7c7e99302516fd8f4472c0ba0fe4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e233b7c37b74393d151f9d4040298588
    md5: fb7113b9631c96660f85d4ce82ac3c39
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: dfec93bf262b43ebb40cba30a507e116
    md5: b750900c688257763673f39c19238db1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart115/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d66c90aceffa130bed59958bb9dbf994
    md5: c87f6d95aca936b4914ab07fcf2d17bf
