format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/atmosphere/restart_dump.astart
  hashes:
    binhash: 63d3c110888af49411c0a897f5ba4aa3
    md5: ed69877d630da6d582faf461ab456284
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/atmosphere/um.res.yaml
  hashes:
    binhash: 08bef2d4e7930a5472f79bebf2bc645e
    md5: edd5a3fbf71621ceb25c16ef4607c42c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/coupler/a2i.nc
  hashes:
    binhash: d7a25ef5a804f448ebb88c405819deaa
    md5: 0790d443f6df274d5aa0031161f41db4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/coupler/i2a.nc
  hashes:
    binhash: f0e8be7598d5189a3471b51423964032
    md5: e81cf8d6083b5fa6605e5e0b081f7df8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/coupler/o2i.nc
  hashes:
    binhash: 391682c4675e117f75825a364079aa0f
    md5: c44dddd9a35dd86ddca76cc3808afef1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ice/cice_in.nml
  hashes:
    binhash: 91a7168e5163b663280c39199ce2d103
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ice/ice.restart_file
  hashes:
    binhash: 30a9b1d14022db2d41436ac351fa8daf
    md5: 02f40ddb93e8d79a62cb8c94fa769c98
work/ice/RESTART/iced.2821-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ice/iced.2821-01-01-00000.nc
  hashes:
    binhash: 0f79e6ee36f49b67e1685987cae17c2e
    md5: 595f833c995ad4ad1e1599082c9b68bf
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ice/mice.nc
  hashes:
    binhash: aac03ffddd6241552ea719587c6096bf
    md5: 80b56916b43493397bd7f6d523634b1c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_age.res.nc
  hashes:
    binhash: 7b70a70d25c3243bda6e753b75e4c9d5
    md5: fc9d6cd1366c0223a234e3b8587b2ea5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 16b9f8f8d4ca383bf3e2c0e4f7c9bcd2
    md5: f0b04d528cdcc665a679a1f073649ceb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c872401e79647d6da84a274fff3c9d08
    md5: ccd2d10daba6ce4d5a501e891f1e115e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_density.res.nc
  hashes:
    binhash: 4d34aba201947537d4637fdf645d64a2
    md5: eebc68b8516b67fab022ebb6796f4ee1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a1134c568140ea997b642dd4b397b8ab
    md5: 335db2c48282a0227c352e8300bfc422
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 010172a6a59f1006c0b3e8547a9b12c8
    md5: 1ffd2ca0e1e1107b71cfb032e05c4453
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 47678afd28c5d48594f249d941559155
    md5: 714237380d1e0643e45576cd371181c2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f1c2584d5eebe446f17a4e5a6ca530e7
    md5: f61819cd7c84faf4cfbf27da6f6812cb
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5c173fed0200ae9786143f5f2963d283
    md5: 269465e89b94b2c59d099e50113a6012
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 66b2106fbcd8df357f6e54e50643ff98
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_solo.res
  hashes:
    binhash: 4ae87ef68fb4191a86b29795d2fe2736
    md5: 1691a3a7f28319e868c593dab94b76e5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 94a5ab3cf181f65804cff06ec6128237
    md5: c407642410ac0cff5ef5eb059595907f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2d92976ac6a21cb213f804bee4868c12
    md5: 636a9eb6f565effe96959e5cf84f8cdf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_tracer.res
  hashes:
    binhash: ef8f33671ae3209a3f57a57aa33efb28
    md5: fe260064161cdc19fa8a5b4050541a2c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_velocity.res.nc
  hashes:
    binhash: defdae952d1aa7ece55c6ec51cc3e435
    md5: 84f37d32e72a8611898fbfa972801c32
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 56be4d96fae0218e59c999bab630f99f
    md5: 8f60cfda07302d4d8071045c3cedafd0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5e4bda9d7f05f0c534b9eca6ae870dfa
    md5: 7211e8a7e6b563739b9ce594135987e1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart144/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8dc960ec520afb728f0bff7c2d29e471
    md5: f25c9ee174e1ef4aa5ffcaf51a10bad2
