format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/atmosphere/restart_dump.astart
  hashes:
    binhash: fa6f39aad99f81f58d00f18811bd1b3e
    md5: a7d2eda9b83e9cb7a805a0eda85e72ff
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/atmosphere/um.res.yaml
  hashes:
    binhash: 80f9355501db486f64a1af4cf6b7303b
    md5: 78f26c60a2e2e0336c7acec9bfecd7bf
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/coupler/a2i.nc
  hashes:
    binhash: 1087ae6c493de3182d107263a435c9ef
    md5: 08e133878244bdf5f71b437f77f60d38
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/coupler/i2a.nc
  hashes:
    binhash: af2bd3d385a3d51b5d3a15cc6217d4a0
    md5: 5f63edc02bb00e912c443ad6be7ebfd2
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/coupler/o2i.nc
  hashes:
    binhash: a0e36cd688fe998326ae9e4cec9dd0ca
    md5: 82544a7a29dac14d3a13b7211492119e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ice/cice_in.nml
  hashes:
    binhash: 32bc106522cdf72bb4589b4d9c49dfa1
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ice/ice.restart_file
  hashes:
    binhash: 956b4e884900d4c98cf74d2fcf182304
    md5: 1fd1fb44b62fe4574a933df0ffd64831
work/ice/RESTART/iced.1850-01-01-00000.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ice/iced.1850-01-01-00000.nc
  hashes:
    binhash: 98a3d8164d4a9b405e1bddb49ae78456
    md5: f169a3ccd178c066619a8c8d8a183b28
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ice/mice.nc
  hashes:
    binhash: 4fdf502bab99c92eb9eda0c303693d5b
    md5: 27b3f3c108bab0ed90e44dc0450fd168
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_age.res.nc
  hashes:
    binhash: 5aec4e6aaaf2d2c04113845994658956
    md5: 15640751876c8e8496a85dbaf9eaedff
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fb9b39c03afe96e6211adc0cfe753ca6
    md5: 4837704a0c9a43f3c2439557b707d618
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ce6225b1fdbc8fa4fd554cd2288cef30
    md5: c1f53c2694225705bb01e6fa86ff6d7f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_density.res.nc
  hashes:
    binhash: fefc88055c656f29c4c60b03c397a772
    md5: f7ec964e9af6b7a670b8973c520a9e5e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 99f4377001bd64502061034e659499c1
    md5: 42e0aef016dd30ebd6e9427783c31941
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 63919d2331bd60957c4b96bef354e74a
    md5: 836f59d03fdd633151e69f46cc2fa00d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_neutral.res.nc
  hashes:
    binhash: dd521c780539efa1fbe4dfc1c83b30a1
    md5: 9095c8b233723bc6c21afc548406d16e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c8299a67c6abf4270f4e3a85da02d81c
    md5: f8e05e92eb9870eae246db810bdbe389
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 46bdb5a253eb643efcfa6d274e8d97f7
    md5: 84fd785beab58b7633a82fa036e367f1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9b2ccceb639ffa6e4e627220e2a1f258
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_solo.res
  hashes:
    binhash: fb5779383a2772cae257206b44afbf99
    md5: 934c67949b5bad56b7bb7caaed15ab67
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ed0d979f77ccc3e7bf2ae3df1c1b63e5
    md5: 301f673e40432c52d1a34bffbdbc8a66
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 88eaba1fc4f717dd736da72186db0065
    md5: 66b770f252ba046891dc8c8d5355486c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_tracer.res
  hashes:
    binhash: f51f04799166e0ce0d3abbfd54edbec6
    md5: ab4a6886313c3db41a8aa918e4c75d6f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_velocity.res.nc
  hashes:
    binhash: fff0d23cdd26ef4599a0d74e63031eca
    md5: 5e28f47828e51400f90c32a0ae9c6a67
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 68dbaefe6984b454b2df72bcf62a2ee7
    md5: 961ddeecbd07a700d1431cfa31493b38
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 00828d136835c87df1955f5fe17bb39f
    md5: 9ae10cd92772ce4258a47a0d61100ffb
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2026.02.23/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 001557b79a6f3d35ca692e9e385469e0
    md5: 287a6e2530327631afb6a34eaedbe520
