format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/atmosphere/restart_dump.astart
  hashes:
    binhash: a376b56b793a2191e287625cd195ccf4
    md5: d5c4c601967b4bf107f4cadbab3a2d24
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/atmosphere/um.res.yaml
  hashes:
    binhash: 0fc5a1c188f066ec486f1c66710a48b9
    md5: 794d2e2dd863a49126392d482e1806ef
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/coupler/a2i.nc
  hashes:
    binhash: 1ee70a9780fd2c3ff6701123e65b2387
    md5: ed46977e09002db30715e737d46614b9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/coupler/i2a.nc
  hashes:
    binhash: 8e64e2e8f280f257d051d627e3cdf4fb
    md5: dd127fe03e5dc00db7ed19951b330953
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/coupler/o2i.nc
  hashes:
    binhash: 8aca75723d8b075aa6f803dcf4865938
    md5: c77801f5f5ddf8aeb407f401a92f2d6c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ice/cice_in.nml
  hashes:
    binhash: b241a10d0c0a3055c9852261a6d3706d
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ice/ice.restart_file
  hashes:
    binhash: bb934948193810e6b561fee82fa0e7f2
    md5: c9dd04ddd4df8128b54bc19575b155a9
work/ice/RESTART/iced.2686-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ice/iced.2686-01-01-00000.nc
  hashes:
    binhash: 6376aeef053dd7228db18285d00dd7c5
    md5: dc26e44384e1c4aebb975a93f8e59fc2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ice/mice.nc
  hashes:
    binhash: 777b901c5b79d2ce4a9a2c5f4ba4f1fa
    md5: 80aa4bbde1492aeca74076791adf30c8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_age.res.nc
  hashes:
    binhash: de41cf8ddc513e81999513ab153d77c9
    md5: 16a9d787eec4de91783f9c4b7f95e4a3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8bb1b4eaf1b825621af36c914e163abd
    md5: ee480d18ec27fd64a538345cdb58bb33
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 904f3d699425dee88fa26b9aab4a4d79
    md5: da38b5ff2f1928f06e09ad2aa06d5c02
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_density.res.nc
  hashes:
    binhash: 19a0d6069ee94902d8378306791838c6
    md5: 23d86204f47f6d736db54d0c3876e549
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 57165d47877857bc49984b4bc79ba36f
    md5: eda698a69e722ac4922ce5c0b26a49de
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3385425b8f21598a8432fd156ec95a68
    md5: 34bc2d09a3fab8a8889a43d8a8becf5f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7776ad2799d3639da908335348637eb1
    md5: 190c446560bd30407ce94dcd5f916489
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 254e402d344dcf7c48c0078e4b9c70ce
    md5: e32be6bb0040a69bd29b58cda356dafd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_sbc.res.nc
  hashes:
    binhash: aca57bad9dd21851d51988aa3e003e87
    md5: 78c948b079b0ebf09a4e325ef04088bc
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 473737a9f8adb567ec0d984586af6b02
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_solo.res
  hashes:
    binhash: 1497a15db499c42108c0c60143182067
    md5: 077338efa15a4b63e962f34aa8a48a0d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8eac3a5c375d805e157b96e07ba123f1
    md5: f8a2c76cd94fa38399545613e4081c85
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8c644d070c85edad71e4233312ce0f1d
    md5: 91851013be2dd462399f09c6e36344a9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_tracer.res
  hashes:
    binhash: 0b2de167b8403b7af8111827011f07a2
    md5: c21b8c981635824e0d1aa9a8a2613b56
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 584210043f9d0ad9b7210e9a8433e390
    md5: e1a7d607c36652715abccede994d8b44
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6de96f687474a944135a551c57fea374
    md5: dd98704a40a0d0b993afa4d06e812155
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2e126bed6448709c3f24af452f8d4649
    md5: 7deb8089068da2151d62d2c7c84a6e62
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart009/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9f6dde1cfa03ddc0a378b0c09a030006
    md5: fbd5fc5871b6765313016a656846503c
