format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/atmosphere/restart_dump.astart
  hashes:
    binhash: b95fc2b75610fd38ab504835a64b4f1d
    md5: 4060fa1541012bf92b071bd386329ede
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/atmosphere/um.res.yaml
  hashes:
    binhash: c345ea81ee737cd1c6e7561f4c2c57fc
    md5: c0fa46d52bedff8fc78ae04cae46aa91
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/coupler/a2i.nc
  hashes:
    binhash: 59228bfba129b96af362c5435997a2fa
    md5: 44225207693f6258f150a9e38cb106d3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/coupler/i2a.nc
  hashes:
    binhash: acfe668820d06c18c23d4bd6c365b377
    md5: 1f8616c9b267d2ef115b2490e671c905
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/coupler/o2i.nc
  hashes:
    binhash: 1bd4aa6c899919badfe38c531baafd5c
    md5: 0dc7a615b5a3adbf79132b93f1096dcc
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ice/cice_in.nml
  hashes:
    binhash: 5a27c3002a28fafb34886e97307ab31a
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ice/ice.restart_file
  hashes:
    binhash: f3ff54149a04e83d0075375dc77514f2
    md5: afeed2b83dfa3ae994ca0becd3c80f2e
work/ice/RESTART/iced.2765-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ice/iced.2765-01-01-00000.nc
  hashes:
    binhash: 01bd3fc212fed970ecb32e13058fdb92
    md5: 421398fc61adaff7922d16c73ef600e0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ice/mice.nc
  hashes:
    binhash: 725893d664d9179bd2d6c099be845ad5
    md5: 598fdd4ca8cbb1997906253ccf328584
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_age.res.nc
  hashes:
    binhash: d36735c4a06089599e9d6e86b25b97d1
    md5: ad5ff36cdecafcf1b990f65f64086541
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a76b84aedfe14e0df330aab7289c4688
    md5: 6ba0a8c50fa12c9c4793cda39565dbbf
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fada0e5dd5489f4c166bf6523ccfbbcd
    md5: 60c92f92e34fd65cdd5f9a70bb5d5c0d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_density.res.nc
  hashes:
    binhash: 34922625d24e7c05b4e1333c3a20bce4
    md5: 46831c51c2149878aa3af8d57c3cde08
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9546ae6a4a4c26d2f3cdaec69996effe
    md5: 444702a1236cc1ad68bc6d21b3dc78ab
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b9e9699f8234afb3285a1c614c1132d0
    md5: 4318e2becf6d360b6d22d4fe1283cdf3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 07a2571bb26b7552e745271d22d3f6fe
    md5: 38d79fc36396509e8744af511d66558f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 06030d3bda056b8578f01fa6608f8173
    md5: 8710af0875ece7aee1c8469d14cd995e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a2dfa16c060e40c3f1883bbb1244ab05
    md5: 5a7e709a6b9d6e1a3320ea976ebfebf0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4f5d9c82f46ed3aac9c16d1221368ba2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_solo.res
  hashes:
    binhash: 6150159b08b472af855d0c3baa9b8dd8
    md5: 7f9f4d9b97c44481c19a9d1dd7267989
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: be94f92f137b06dc78e1b532c1eed8e9
    md5: 268de9f5ecb3df918ae2e662213af846
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 28abf2ffa951a3abfcbaf1bd1c815d41
    md5: 493269971be3ac62ce5c7d8202370e10
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_tracer.res
  hashes:
    binhash: edd3f28c60f6f2cc3415ebffaf6913ad
    md5: 8c4ad9614d06fa6c849d2e941b7cf94b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a597a5ce965fdf1be59ca5c21869b05d
    md5: f21bc63ec060488e4b6d6d43ae8f10c8
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 915dae3e2120687eaa704c40c7476ad8
    md5: a4a9458ea23ef4aaa44064b333dc5bf2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5dede7954df05482e848d8f649cfa3c1
    md5: 6452f3d5da09d4b38aa9bcf7d494e4e3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart088/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 31b7bd7700f87f234513484175b132f3
    md5: fae50ffb31ad157edd263b35fc778dca
