format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/atmosphere/restart_dump.astart
  hashes:
    binhash: 33f43ff0989a0d2de4273c4cc1c9958a
    md5: fab170fd3f523e4ae74d4ea851eb836c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/atmosphere/um.res.yaml
  hashes:
    binhash: f2543afae07bd7726f37969abcab581b
    md5: 245276dde26ab9607d1d6e288c8eb17a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/coupler/a2i.nc
  hashes:
    binhash: 9324d28b2305dff1d6bf78dcda2f3274
    md5: e4cab7ac89841cf5f119fdf8291a7779
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/coupler/i2a.nc
  hashes:
    binhash: 1cd2cd3078150d42784d86543a16d176
    md5: ff964e4ab7c88bd3439958e215211485
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/coupler/o2i.nc
  hashes:
    binhash: a74d917a2adfde891bda8b76396e5d4a
    md5: bc2dbc909ffe25dc20d5aefc7ddc57bb
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ice/cice_in.nml
  hashes:
    binhash: e2f9663856080c1c9b3c46dac31dd0a7
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ice/ice.restart_file
  hashes:
    binhash: 676d1294875b1ba5e17366a65b5faebc
    md5: edcbc056828e63ae980fd53e0eaef36c
work/ice/RESTART/iced.2705-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ice/iced.2705-01-01-00000.nc
  hashes:
    binhash: 42c5a9295b7d2e6b100a88de734d8a10
    md5: 695ea28a4d795e039f7a0db56167f4bb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ice/mice.nc
  hashes:
    binhash: 2d78f56a4b1ce5c99ee84b57c8b03adb
    md5: e54fd08c18542acf55692049e12135a2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_age.res.nc
  hashes:
    binhash: 0ebd6061a39f676595d3155a50ef50fd
    md5: f8eaaeb9cff74dea9cc322ae8b2439b8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 99f7dfd3c46bea288e00d08dd9452685
    md5: 74529f0ec3366c7f72e75c0e69e04c5b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b544ff4d502e7132d721355f52ab3a5f
    md5: 1ffa0a4a4f89f4ae10bee5afffc28130
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_density.res.nc
  hashes:
    binhash: cd664d9b3f8e3c4dfdc95dacb439c910
    md5: c9885210b6d22bd5c80f55cacc1d2436
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e69a5915d5f511f6fe665708675df89a
    md5: 36d4c91fcad67c486cb877473ce1386c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 661c1b3a54fb2bb1324d4f32ab5c03b0
    md5: 810e946e403c5449d64478eb96885eec
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 13c1051f9144cf62abf0491c30b0577d
    md5: 1966a8884c6044d91ddfec7f00a8f69d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b96d21f3a230aadf526ab7c13c410e69
    md5: d9451dad57c3c6371116efabb050a644
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f80b32befe91d9ae82b76cd09af055bd
    md5: 64acd94735e52247514c62f28b23ebc7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a3ce4476fb924399533bc26c8bd99a51
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_solo.res
  hashes:
    binhash: 36ed84b0e14afb4ce7c348ea1618b111
    md5: 65b51b3fd0e3976e21028ad0c95500f3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0f4cf8e182ea16a7353ebbef8b6d6ae8
    md5: 9e8dec3eca5c2c36338b7115f0351db5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a8f641d36d6293b0cec9e2e7fd4e485b
    md5: f89792894fea4411c62cf4e79c3b76c4
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_tracer.res
  hashes:
    binhash: f7bac00b1c395b585a1f22fccfdd3741
    md5: 6ca272098b09d76c5883cc0fbfc397e7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b3aa48ed267ca2c355309977a3a43b26
    md5: 9b8a0efd79442c5e0826245e2d449bf5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5aabd2f4f86230fd3baddda5a6a5c610
    md5: a3d2b32d1399597479718aee8fa56a85
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9210119fd748dcd604492d0c62f6cae6
    md5: 17e0315344ebf3013cf0a3d49b45a744
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart028/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8e81a941cc3c72d76f79217ab4bad5d2
    md5: b685530a41d142be46c63c8ff8f92c97
