format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/atmosphere/restart_dump.astart
  hashes:
    binhash: e86c99882c6806be0cd89d83caa8fa63
    md5: fe7bd645bb7e6e636d1dbf19fe1aa402
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/atmosphere/um.res.yaml
  hashes:
    binhash: fc957d54feb7551e0dd43fbd831f8480
    md5: 32c2b474ec5d3cc655523599f95a1ec5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/coupler/a2i.nc
  hashes:
    binhash: c826c2e8f1bcd9c44585349c31c3731b
    md5: b66f684fa7f87e9c91126c13854c2015
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/coupler/i2a.nc
  hashes:
    binhash: 90c21114268ef94aa7dddb9625bfcd41
    md5: 35fdbb43a2bf03ab3b607e146abacb0b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/coupler/o2i.nc
  hashes:
    binhash: 3223ed9b2dd04d95e27a9bf62e2954e6
    md5: 9319d73b1f9982fca5777fd668002b02
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ice/cice_in.nml
  hashes:
    binhash: 9c4e88566f894666377dab943eb97607
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ice/ice.restart_file
  hashes:
    binhash: 57a33949af92e2e133d84264444ca55c
    md5: 6788818001a82c7460a5b87885c91d56
work/ice/RESTART/iced.2855-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ice/iced.2855-01-01-00000.nc
  hashes:
    binhash: 8980ec38e6af718dead07fd99fa31904
    md5: 6e648dcb10443ee7c183c2c3dc31155f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ice/mice.nc
  hashes:
    binhash: 60881632af27c3b71955db24c9f64add
    md5: 9ebfef1f4a273a3fc6c59560001547b0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_age.res.nc
  hashes:
    binhash: a6deac8b1f5f3b689bec55a9a627f2d8
    md5: 2b395bc3de0f2a2f6a80e660e4c189e7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bf2d024e9164bdb8cdfbabe3828dd7c0
    md5: 86641502a9a3c249360ba0c814ca155b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 70acad663b672ed66a6fe9f8eb43f350
    md5: 20670d8d3d52f48c62343f341d09c745
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_density.res.nc
  hashes:
    binhash: 4f1ec20b9750715c942f292fdfd7d8c0
    md5: 9db5af4f2d63079fb1ccf3a03634f404
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b393b0b7182d69a22f58666520becc06
    md5: 05b11ca42de850ae7ba4effddd752c79
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: dceffeea86aa2809aa4da475df077cf9
    md5: 64960c9b614bc45bd53851de30bd18f0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fc97e722836eaf3a536ec2912e14dee8
    md5: ff38cce16881d32fd3969e779387aa50
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 988bee95028078e7da626422be0138ea
    md5: 4d2b463c2085046bc46fa88f14f5d282
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_sbc.res.nc
  hashes:
    binhash: cb86ef30df6258893f7733af442ac148
    md5: ae2c6c8a24115902209af7a4a9bb9ac2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a7e5ff38bd114802c2ee532b7f106646
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_solo.res
  hashes:
    binhash: 7e9fa507e372899eff0ccf051a533d1d
    md5: 84be8056c0d9d14996d26deae35f86ad
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 828af466ae06c733a5b3ce7bf1d21f1c
    md5: 61c6b2123ea17f2e4d0df9e2c7b5ff96
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 90a7794d6841929c9a7484fd5fb54302
    md5: 6be37fb0b279743f2be1db15f20d0904
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_tracer.res
  hashes:
    binhash: faffb206a9002edc2d81ffd1eab76557
    md5: 05a259c62bc312eaa4696f6b983e8509
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a7c0cd88bf310bd033d49eda2af72af6
    md5: eec08c525a3c1287cee086df2280c1bb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6e0f06beaa2f19576bca3919bcfb3f30
    md5: 8d007aedc28243e99b6aace71a289a47
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c0d1292c47d8679021ad211e9601d182
    md5: 5d6f4bf078b48ceb2af3a57dcbbc82c0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart178/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1d7931e03b38474197aee9ce8a45aed3
    md5: 231ca7e45aa493008ef1e72edbcc5871
