format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/atmosphere/restart_dump.astart
  hashes:
    binhash: 5070cf591483fc47e24c974223783767
    md5: 4cad549f3c8e448d16bb582de2af3b84
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/atmosphere/um.res.yaml
  hashes:
    binhash: f63768d8bd991ee8084fcdd0045561d6
    md5: 8ab03642903ceeeee182a0f4933ddc0a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/coupler/a2i.nc
  hashes:
    binhash: 42287145d852333b9c676b960f56b779
    md5: 601458f43784eeaaddea6de6bd77a244
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/coupler/i2a.nc
  hashes:
    binhash: cf6d88113bd3b3124275a821ef334f77
    md5: 526d6f835a5e7ea60d8746d99e273aa2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/coupler/o2i.nc
  hashes:
    binhash: 340a38747861f91a85a55442aa633afe
    md5: ccf738326b53318f438bfdaa778acf76
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ice/cice_in.nml
  hashes:
    binhash: d8786c209a08026de5d6e50f9b88283a
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ice/ice.restart_file
  hashes:
    binhash: 0767cdde5a7dec436aad3728522694c9
    md5: 66608100313a5cf8209589b4f4ca7f20
work/ice/RESTART/iced.2867-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ice/iced.2867-01-01-00000.nc
  hashes:
    binhash: 2c1ba8e494886fc3ade5c3565aa47a88
    md5: 94e6b111c414b5d895c44877bb781e54
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ice/mice.nc
  hashes:
    binhash: 62e74642e2ee339b2a3e19b8748b490f
    md5: 15df94336fe0d096ba4adb059800901f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_age.res.nc
  hashes:
    binhash: b2f9ef1539e308c09b19386c09e366fc
    md5: ea4219f974bdb6078e403ed31a4d746f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e505b3eafac9684c975e7d79c8e89ea1
    md5: 46ef82e8cc904632eeeb04b2cad47538
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b375befed4231c8ad33a9a7d82f9fce8
    md5: 50fab04f7a1274d0cb804e372d02e2be
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_density.res.nc
  hashes:
    binhash: f29291dac24adb81153d9e37f0fe2dab
    md5: f0fcd451c140b5ccc0f69f13fe7a66c7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1fb2659a40d2cd41ec8e8e6b6726dbc1
    md5: 02ab02c5268311f0b2644a82510d596a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 49fb1bdc5111e5182fe388b1483a030d
    md5: 68b87164781329a69dd7ca9b3e19114b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 58f45b4380837881de892b2bc04cfc36
    md5: b53f180b13c30df4c9ba08d377b9abf0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d1164d2e5d3ae5dd1d1b2885a397657e
    md5: 861acfe66227054a533778ed36c518ed
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ef78a1d6cf4075d4c895cc22eb1d1fcd
    md5: 53fc4264c9c564f2bf56c529fd544827
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4d97a0c65746017d8ed658daecbeae0d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_solo.res
  hashes:
    binhash: d6fb2fd584718fdfe1e26c9c190e036f
    md5: 43a12d980d03fba423d0b0438c9fee59
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e162f233f1d60415a159db42463ce11b
    md5: e715b07843b0a1384d7803b6535bbe5e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 06aaa354ff8f87d5e1ecba1ca08bbabd
    md5: 59bf97cfd73b49db39230ff95a284564
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_tracer.res
  hashes:
    binhash: 9651eac7009efbce0fbde54e12ab2336
    md5: 6eae62f4e2b4d10fd3d9efaf8f16f029
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f0f1be3aeb1e0ac379a31b073c986fe4
    md5: dbd8713e86c150405787040200b2a9b3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7184e31696c578c7f8ec831ba8d1a76e
    md5: f241de61d36feff723e03765165d17e4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 920a4feccfe413e5eddf14c12e12df41
    md5: a60e3752150f11900df4ad11eae9ac56
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart190/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 30ddde139efa3144276b071828c39d3d
    md5: ab906420733888ceb34bf7576b003074
