format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/atmosphere/restart_dump.astart
  hashes:
    binhash: 5fd43ec9cc1d3ca82c0a97c5ec30b0e0
    md5: e13de5d85a020cd8640de47bcd9cab19
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/atmosphere/um.res.yaml
  hashes:
    binhash: b7b630634a4a810dc4f0dff8ad35f147
    md5: a2cc5c17c165dd536e46bf058665f95e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/coupler/a2i.nc
  hashes:
    binhash: d44b6f421c3a849c03deaad009906f17
    md5: 953bfef3834468a4d042668fe398bce3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/coupler/i2a.nc
  hashes:
    binhash: 8bbe6e8a3926ac0b691a3f503eefb7ce
    md5: 41f0e599cffc8e39a3f6d2207a78f1bc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/coupler/o2i.nc
  hashes:
    binhash: 25a6e00429df5a93853cfd4ba8c94488
    md5: c33bd5f4d8a2e1e4cf2b1eece75c63a1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ice/cice_in.nml
  hashes:
    binhash: ed6924e473a22b9dddb8c92596670bb8
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ice/ice.restart_file
  hashes:
    binhash: b1453d8222ba00f889e9dfa525b1e4d4
    md5: 609f700d7a0509bdccd920fec62978e4
work/ice/RESTART/iced.2754-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ice/iced.2754-01-01-00000.nc
  hashes:
    binhash: 9a787523b6f5af7600b72e8623ba7ba8
    md5: a102d952d0c623ec01087fcf6682c9b5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ice/mice.nc
  hashes:
    binhash: 8c7e5d96865e19abab5ea211fc52bded
    md5: 09dce04e86a67e50b2dcb2e503b65b2a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_age.res.nc
  hashes:
    binhash: af4671a3216d3933172e56dcded773c2
    md5: caaba7e3f2a336118c0576d4a953b454
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9b1e86211b4212281af2a69e2594a3ec
    md5: 0d7fd50c45ece0bb001cc1d8fd9b460f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8eb7eceba280183467c267c9b7db7263
    md5: d98cd7410544f6dc991d5f16d17d99d4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_density.res.nc
  hashes:
    binhash: e161803f7d27fff968a9269c11ea0dbd
    md5: b5c24906a98c926779ef53d2c3e29b17
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f2b4cbf3f557bcc76a745c49470701f3
    md5: c4c1b12afdee42c418b88b11674f0e5d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c4a832fae6f631a214dbf6ce798d930f
    md5: c38f5c5854a81f633a4fa0c0452f5952
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 18f9a5913c0af090fe9778f36ce0079b
    md5: d35c307640a5c3475ab2003b914f90c1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: be6bc83b96a5c029f635bbd537fb1c3b
    md5: 6a04b1cf798899daa0077cc690d118b7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4f802a46e06c5a72fbb3e8549c0b7d4a
    md5: 1b5879c8410c06141f844bc083391df7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f7e11048690f47c34d847a2650dece5b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_solo.res
  hashes:
    binhash: ddd33820405620666195d4000063b93d
    md5: 444521781e3c1d5d3fb406d1e48edbaf
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: df9d38c215810fabc03051658768d06c
    md5: 3be5a1d040a464caeaaaec1f00805d9b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_thickness.res.nc
  hashes:
    binhash: dddf0faf9424c8a94fdc41a9630ad0ad
    md5: 69a7eeead00fa78503c7710d56c136ba
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_tracer.res
  hashes:
    binhash: 3f5b68c270e04b066734751e94b59b4a
    md5: 4ce0f6643eca3c561d070a8cf397a953
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c50889bc999b9a864f0c0860cded56e6
    md5: 3e9ad3b4282ba5ee88c928bf9e5c80b7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0dab883013e7be068f7f3004106e8bb4
    md5: 7f3207caebb4e79b8d0e09577273db3d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cee49ca53fb23b9dcdefd353c43adffa
    md5: bee605f6b2cca3f2a5ebdbb132ee0493
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart077/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ba1aa1d673e9a5583f4ece051d0743cc
    md5: c078721a2f9cef0d8818ea2257cbdf64
