format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/atmosphere/restart_dump.astart
  hashes:
    binhash: 5e6592c3e412b75b5b9d2fd82e41b7d9
    md5: bdce90e1565ce6dd5799f16f85d0d383
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/atmosphere/um.res.yaml
  hashes:
    binhash: f2198fab58e879f9606f8caa610ccf3e
    md5: 84a9a9f78b2743f1d0caca80ee336ef3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/coupler/a2i.nc
  hashes:
    binhash: 9972584725b4852a11cd6374d8ada8af
    md5: d505105927078091f2d3d3c3a280ab23
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/coupler/i2a.nc
  hashes:
    binhash: 9f10e3ba7ff0c628e00e3a32a2db7300
    md5: 58526d70b8654dcdebd8fd9425740a00
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/coupler/o2i.nc
  hashes:
    binhash: 39cb1e765d3b748afba1f524d0c3f7c8
    md5: d91c8f53425264d3cce200648fd123a3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ice/cice_in.nml
  hashes:
    binhash: 4ec9d1b784a423fdf61ec2788c55239f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ice/ice.restart_file
  hashes:
    binhash: 598c11ac1c59a9db64e502d005d4b88e
    md5: 8f62460c4df0f3c7b3cf3bd75e4f6866
work/ice/RESTART/iced.2822-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ice/iced.2822-01-01-00000.nc
  hashes:
    binhash: 76059a50a9380430f5ea3a5ef59f9769
    md5: e0b136c77a2fce128a7b633f5e9c4f72
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ice/mice.nc
  hashes:
    binhash: 044c64ea0d1c8e3c98b1987bc801768a
    md5: 490d7fce261795f2f7eca5abbc8ebdc2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_age.res.nc
  hashes:
    binhash: 65832287f57ea2448612d9bc964b1c73
    md5: e449bddab57bcff86c544162b9fe397d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ee978e1dac25a49cca864aa641b0ddda
    md5: ed74c662004cba15070175841086e460
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: da48a038daf77aa9253667102c3004c9
    md5: cbabf4cb95db5fb1053b9cab1e917221
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_density.res.nc
  hashes:
    binhash: 4a7ecde464c5a969b1b5861606b199b7
    md5: 4e4b3e2f8b4aa0b829c14c484cd6f7ed
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1ebc6d5babb4a5599c98dd043b6cec29
    md5: a89be0fb2c3b651795c7d9b8fe7feb5a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 128a77f6bee8b56d1392aef5c6ec5d99
    md5: d58dd6ff69c75f1699b3747fc2bcaf69
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d1731b6948c03a9bafb4e6cbf312c6b8
    md5: 1fd01cf5bf0383475112a445dcd9b078
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a27a96e0d053f6cdbe93df1ac757b031
    md5: 5d71d1576a88b0ecfb53dedc97a36832
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 15b983865b514c87031bc53b6e511bb3
    md5: 4ab68cd15938c31af60bd74101449d47
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: db1fa06e2caaa9fc4e15d1a6f96504f8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_solo.res
  hashes:
    binhash: a4ef8275585d8da676bf5b8f7389fdb9
    md5: c9e73f801e1d2d7dbda5fd31c0a93140
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 47d857da7a57df8fd3540ebf99dbe551
    md5: a04b3c277a8195b437444f1e2d455a7d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 79d2104613443dc443afb3225336b558
    md5: 8caf22a880b83fd4f325c55b5ed3ecd0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_tracer.res
  hashes:
    binhash: 731282da29aef27c1e4740b63a061ce9
    md5: d0e7a89c3d6ac1e2c13c32f2c78d687b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_velocity.res.nc
  hashes:
    binhash: eccd6b59d65fa34f838630a4787c6993
    md5: 39baa317755318e6981899a8a88f1b0c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3497e390fc1629c4c6e1ee62a6c83543
    md5: b17deb2449d72ef936dc4daac1aa0ea3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8260028f6eb12266c6c90c87709ce0d4
    md5: 82365d45fe2e7bfb25db842ec9933050
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart145/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7935341e2b30e07bb49af9486cbcedc6
    md5: f395fcfa82e227ab4fd6d5fd8c5d0c0b
