format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/atmosphere/restart_dump.astart
  hashes:
    binhash: 5df7188351e12f026f18cb9840cb5866
    md5: d7cc3202d8327930981cdc1b55ddf4f8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/atmosphere/um.res.yaml
  hashes:
    binhash: fe6e4446413db54684eeee352dfa3d56
    md5: 86bad4fccbfa235ea56a3d0eeb6e70eb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/coupler/a2i.nc
  hashes:
    binhash: 5373598d7ec7232f3c7545f717319543
    md5: cfe8f39ad9cdff77e00c556901fc65da
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/coupler/i2a.nc
  hashes:
    binhash: d33fe5a88dee340707d4078e5ebe6768
    md5: 17e215830c9732f1fa49887100776d6f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/coupler/o2i.nc
  hashes:
    binhash: 0bfb799367747e176fac279a37748f7c
    md5: 2782948f1689ef5df0aa30e64598fef6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ice/cice_in.nml
  hashes:
    binhash: 25afd81c06e8d5687c741645fe8d0970
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ice/ice.restart_file
  hashes:
    binhash: 19d97469202a824b36b02f9c827896a0
    md5: 50ecfdce53dc66ebd9ffffab236ffb1b
work/ice/RESTART/iced.2732-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ice/iced.2732-01-01-00000.nc
  hashes:
    binhash: 056cfbb515fbde4cdf6b55a0cc4c4ac9
    md5: a9bd469225410f5c4b98531e08e47138
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ice/mice.nc
  hashes:
    binhash: 030ce15305418dc6ae4c6d562ac667fa
    md5: b71c05ac862344473e46b94507e0cb2d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_age.res.nc
  hashes:
    binhash: 1da947127cb125da4a3c49e9534f1a62
    md5: ae9c38294e62b2f3bba103942d010f74
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 35034b741289f5c8d4ce6dbb8a0b8e42
    md5: 403fc385c98abeaf05d3c0003c6cc50b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5241ce04c7e0bb33fddcd9d0288cfb08
    md5: 2981cfbe8605af7594ffb2c556e34fb7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_density.res.nc
  hashes:
    binhash: ae4d046262733c92c9cc762a43263f3f
    md5: a12adaa481f40d1b48c2452fd5caca64
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a68db4f027c36993c5e96af0a16430f6
    md5: 7436f8f29d72951d7224cf66a3fa17fb
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0949491a52a67446c2d21a37c8d3c1c3
    md5: f9cec2e090a2108cdb281b2872d64af1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9da27f7e8f3522017c3aa136e2cba237
    md5: 727670c6cf80752bbbf9ca33d61ed85e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7e0421d79af4ae8eff8c799ae1057144
    md5: 191034b3885ad61e002354314a67a610
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b2287fa7a38b7652d9a9e07400705cc1
    md5: 8b2a35fa6387aa3be637a84e0a08c3c1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8ba547e4bc8e056f624c526aa09d8e26
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_solo.res
  hashes:
    binhash: 0680164ca7a72ea989eaf9991e7544a6
    md5: 401eb3a906134d4240537ad9f4d020e1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4e7853c7ccfec78664b9e9e44f247ac2
    md5: 4b711dd4ec4c7fa3ec1f4689df4d2b92
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 05d426d0a46499738adf234413a8dc8a
    md5: 5d1c6bdda3883fab0668c983d793fb16
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_tracer.res
  hashes:
    binhash: 2a73b3b5a1a8d293ffc62d91aa28eb1c
    md5: af0cb41cd7ffa7f108f242f69f849732
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 03b12f82c05a52a832560759c43aa888
    md5: 8ea945131556e56131f29798e9dd3a7d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7ca08b70346cc1480a0e6cf16ee63b67
    md5: 527b41c2858653a3829f8a3e2ebd4db0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: bb6c5e4c38306d7b4988b3b1639da5e4
    md5: 70106f8c1ea6a8b158944cb98bd33296
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart055/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 42af192e0ff004468481fff7585b32a6
    md5: 250ca913d11514631c9477184940a045
