format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/atmosphere/restart_dump.astart
  hashes:
    binhash: 0bc5488a6f61347bd1df8e4169cee2aa
    md5: 793bbff16bef60da746e586bff9db335
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/atmosphere/um.res.yaml
  hashes:
    binhash: ec99818f36210d0b8784b5a74a9389bf
    md5: 78f26c60a2e2e0336c7acec9bfecd7bf
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/coupler/a2i.nc
  hashes:
    binhash: a5fb2fa67635e56ade960d6877125b8a
    md5: b3839596b889724e0f74249bfcbb2bbb
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/coupler/i2a.nc
  hashes:
    binhash: 5ec304c08dd2febdadf4e94da48f12d9
    md5: 3ef44fab3b084a45e9b3e5d6c3ea864d
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/coupler/o2i.nc
  hashes:
    binhash: 3b265e63113b4702951a08f228c2f6fa
    md5: 9cc309c53725980fb8ceea8c3beb578f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ice/cice_in.nml
  hashes:
    binhash: 3c4842304d66c4f17c9859d666568095
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ice/ice.restart_file
  hashes:
    binhash: 1b2de71da50cd637820454dc2b89c352
    md5: 1fd1fb44b62fe4574a933df0ffd64831
work/ice/RESTART/iced.1850-01-01-00000.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ice/iced.1850-01-01-00000.nc
  hashes:
    binhash: d0a1e4c50a546b6e352a5cf07cb5bf1b
    md5: 2f4d159386e059ba477a0a206686792c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ice/mice.nc
  hashes:
    binhash: e58d77893a4105c7559a9cc9948ece2a
    md5: b0f77b9c94aadc78ad29846129c068cf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_age.res.nc
  hashes:
    binhash: c16a92312a09ea285c2ab24d58732260
    md5: 8ea6938953bde98add4f0396b3aa4d7f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 74ed51149fa03ad5a5a19469194e1371
    md5: 1bbc9c7b26a763824600d343721284ca
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a83b5149aac7ac94b0bd451dfb29bff8
    md5: d3319b42b15770e6e496bf876c56c3a9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_density.res.nc
  hashes:
    binhash: 9a6dfa66a15b238b1d79dd85a92aa235
    md5: b9721a24f0ea54e6148149b6fd8c49ca
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 05b91b71f9da57d8c76d088727a43850
    md5: 9c74f9b91e446eae36647e1532b5c1e1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8a7c305e4eef2d100050ed8d0120f7c5
    md5: dedf6f50c59997f3d1a4dfa91e09141e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e78a9db83ee69b3440b65f15ffeddcd5
    md5: 5b83d74deb91b28687ab17591ab8ec7a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f3ecad773cfd0084d833b2150204d8d2
    md5: 778294e24b94dd3de9c3c4c7ddc4ae1c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b9e59360058e1e65b7fce3ab74df8ffc
    md5: 3cee186611b12bd55fd6df5d8705bbaf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 589b5dd2448d82bdc7fd3a402101e0bd
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_solo.res
  hashes:
    binhash: ff921cd41b1dff867973e75151747c12
    md5: 934c67949b5bad56b7bb7caaed15ab67
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 27828858b0c0adf4efb640826320d071
    md5: f94e61d860b97c1110da9ab9465b86dc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_thickness.res.nc
  hashes:
    binhash: fedfea2485d64d904508749bb6ba6130
    md5: 27cc724aaaa0746715b60f8287bb7be3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_tracer.res
  hashes:
    binhash: 09dfc8ca2f5e2684bcd30d67ef7b6af1
    md5: 89366655c8e44c73707bb79d7f6bcf6b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 79efd6c3057122ffb7ee4297b5a56eb7
    md5: 84daa2d28d4f4d0bb23323e873e20d48
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0dace2a6405e345584729fec36152cfe
    md5: 701abc0960bb26c8d7df8d9ca6bb73d8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6a47356dde015f653e2924be2febfdea
    md5: 292c7d2fe3f7dbd632d4b88c13094c1c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/historical/restart/2025.11.25/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 520cc58f074fea0cb86a7f0bcd36eb56
    md5: 2ef19c2a89987d615a629b6ade6179e2
