format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/atmosphere/restart_dump.astart
  hashes:
    binhash: 813fc821f1d60e673b2303c17061e730
    md5: 9648bea43a4cf9364b81febd8759b7fa
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/atmosphere/um.res.yaml
  hashes:
    binhash: 3ab77f908ed90ebe3654d5f5a30709fd
    md5: be3127c018984e2bdb2916ad49798ad4
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/coupler/a2i.nc
  hashes:
    binhash: 858490e4dc8f870a79d1d54cef227c02
    md5: 9029478b8c404233167c7c01024a45f3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/coupler/i2a.nc
  hashes:
    binhash: f0c3f3e5c03344053216d051c23b8551
    md5: 726bb6a8d906dced361cfb4b1961356e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/coupler/o2i.nc
  hashes:
    binhash: 4f1f06ddf7e1c0bc5e8e397c1b4bdc09
    md5: e6e4d6cbd799426efdc9c8abb6ee3098
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ice/cice_in.nml
  hashes:
    binhash: 1e21dd46495603472fd2162edf94342b
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ice/ice.restart_file
  hashes:
    binhash: 62323996a15ddc21f05c76c2b312cab7
    md5: e5dbf821f6b95efce2cf94aebf522afb
work/ice/RESTART/iced.2865-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ice/iced.2865-01-01-00000.nc
  hashes:
    binhash: adee023c7ea4af1bcc69ba40d50ee946
    md5: 5df1ab4179d0e9b2d3684db679c2fe0e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ice/mice.nc
  hashes:
    binhash: 8ddcd6ea64b1da6b8058aac60703636a
    md5: 2e67da512b8feb9cf138a4dc2e6cf93b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_age.res.nc
  hashes:
    binhash: 1c3659f462f62e79f008230368797aa9
    md5: f2d6bd984170560469135cf564219354
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a0cc80717bbc51e32cf439ec74b828a3
    md5: 34e8806514153deb64422ee9115544db
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e95305003b7b635407499cd61ad40594
    md5: b728d0eddbc195e991df37ea6b3d68c5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_density.res.nc
  hashes:
    binhash: 3449492a2129cc71efadf151d3a27f15
    md5: 3596de2f24c7f2ded2a17368424886c3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4a6ac7924d22730e0163c5c3a8f030e8
    md5: 15b3f2bf5250284968e5290769fda167
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 90a1ab127afe8111f4b2b9bd528bb256
    md5: 663d5537ec06764dca8106976452ae4e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e191c04b9646ea57765bb7a10e572cb1
    md5: 9d4f9188fa4dd942da58dfa1c021cf3e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d2d033105c4ae553357ebfe173ec9cc1
    md5: f29f1b8f27f685da100a1d096e09f165
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d97d1defdac5fa12aa2852ee6a6ba2ca
    md5: 1915e8355d67dfc31f21c4486fc07dc8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ca1fa9ba88d9c9632ad9c74967b5e97c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_solo.res
  hashes:
    binhash: d61e29a898e5234ace4928373aa43d5e
    md5: dd62c8997262d2623c8a2ebcc747fd4e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b9b495959df6e48c51109bd68aca61cb
    md5: de3d5aa169cac0b7b2bcd2fb901c5be3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 894e0f65485f6e8b8761c95c21e68f7e
    md5: a3d68733714822d6a04293ff1922b80f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_tracer.res
  hashes:
    binhash: 00bb7463c33055c32850cb0532a3ce8c
    md5: 7d5e613755b8c0e62be20d9c2890dbb5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 86bef84eaf42c6e7a821d0d0672362f5
    md5: 48d33018d89bdb7431bf755a067ea177
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 474653fb74779c65a3c24bf1af420f3f
    md5: 01b6dc948673fbec52b1cb684397f2ee
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f1cfcb07aed031dfbe77e181ad4f57af
    md5: 3d7c71ee317d858b90a4742491fe98b3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart188/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 56797ff768c9cb494890d245e2cf0870
    md5: f1dfd9ec289836f58d6729db2d120180
