format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/atmosphere/restart_dump.astart
  hashes:
    binhash: 41ee35586f3d42cc8d82a53c586a291f
    md5: 87da034c89082d82994d9a2d5661238e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/atmosphere/um.res.yaml
  hashes:
    binhash: 8a64b2703ee1c3b5f23cb988b0569ec2
    md5: 0f18239f757dc5d15fe373fc53e7b2bf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/coupler/a2i.nc
  hashes:
    binhash: 7c185b2c7b279ca9cbcf43ae1494db0f
    md5: 148dbc958e34e7b882c2f16c8e321912
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/coupler/i2a.nc
  hashes:
    binhash: 2a7d07f8db809eba82686b4381c7ae18
    md5: bbdea63aed0f2edea849e134b4518a1a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/coupler/o2i.nc
  hashes:
    binhash: db84453978502a8bbffb86428bb6f277
    md5: fbac01843960b77b2271ba742436d850
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ice/cice_in.nml
  hashes:
    binhash: ae0d5874e6a734f268676a8cdddc8dd1
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ice/ice.restart_file
  hashes:
    binhash: 9cc6c66cdb3fa90e5ac09a912ae4bb36
    md5: 61d29b0f8b3a13b51227faba3ec64048
work/ice/RESTART/iced.2782-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ice/iced.2782-01-01-00000.nc
  hashes:
    binhash: ee7a4b2e87495c750ff5a22c19ea888d
    md5: 492796f9c7f3acdeff54a75b424f2678
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ice/mice.nc
  hashes:
    binhash: e6c3f5dc051879673f81e0416a4f4901
    md5: 2817643fff1ead021c1d2caad4811913
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_age.res.nc
  hashes:
    binhash: 0163968fc4823dda11243d69a31326ed
    md5: 82665c534800e8ae40a9b534252b8c1e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e7294fd9c29ebc43bbdae65561e6226c
    md5: eef9c33d5f7fe3fda82a9d73912e9d33
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bb172ea9e27178459dd0e46d63cb8127
    md5: 267910c0d30d0e128051bf9ed796c7b6
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_density.res.nc
  hashes:
    binhash: c178945356886cf58681a0a3dfb2a52d
    md5: 95af743861a47e27b995d26753c12580
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cb3fba1d7acc8530aed34e9350eaad2f
    md5: d79b3063139859b500d8c2e017851126
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2d6f98c629ef9f0ee742278589d64dd7
    md5: c2a4f16559ef6257e4c9ac3704d9f021
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 81b0d5e68e8287c1b96718c7ede2b069
    md5: fed2e42d47bec6384a92fc1c028e2e69
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 37a3cda3180ed09683c63468fff3d0e2
    md5: d78d9c5791948caa59530f58d20d2bea
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_sbc.res.nc
  hashes:
    binhash: dd8ee75a3fcf6a87ebf3ed131d0f7df7
    md5: b603c19c85aeeceac8f0a38f78eecb13
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e3230603424a5fe30e833d76611e8dc3
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_solo.res
  hashes:
    binhash: 4b88e2d15043cc2653f8d8c5912b99b4
    md5: 3d38c573a70fdad816a72e9160b5b9b9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c117c9c3d64f65c217befd7c0ccabec4
    md5: fadcd82a5e81f576f489243508cea148
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0aad45ac1bd7dadae5b8961c2d3421a4
    md5: 703a007d0547889a44254f9b56829f34
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_tracer.res
  hashes:
    binhash: be7596fcac7b384e6add894de42fab64
    md5: d35390b56a39abfe96e411635b8485b3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 335347c895a3e121d1ab1e116e85436d
    md5: cf1c355d9e3dd6bc303bd76b69495bb1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5a510c97ba4ec4ada9400dbb7216429b
    md5: c6e33409913332c77bd223467a0fe5c6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: dad33125318ac52b14550b67b4dff0b8
    md5: 03fc6aee92c53ddd05a940bdd34025a9
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart105/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8c725e75c764e9bcd0158b4c2ec9c137
    md5: 900194215bea3f1621c51dafe658a772
