format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/atmosphere/restart_dump.astart
  hashes:
    binhash: 3cc6cd7f79db1a77086eb8bd024eb10e
    md5: aa1e03aba80944fcb39416ef0e967e69
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/atmosphere/um.res.yaml
  hashes:
    binhash: 52af820418d2e802185b525c4c7f5d6f
    md5: a3179b1dea16778a47024d9260e34d86
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/coupler/a2i.nc
  hashes:
    binhash: b1896cd9be07282e4a5ab52e6ab0743d
    md5: 9ddcbcd0e64d76e314ad478f0ef7c6f9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/coupler/i2a.nc
  hashes:
    binhash: a4ccf4b6ec4191a406ca44de8a3cb0a0
    md5: 4163edb5721bbc7a618e3cc8bbaa706b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/coupler/o2i.nc
  hashes:
    binhash: 168dcf86c33c4ac330c16828f958df4f
    md5: 2298030529e8e5c11aae1c54fab49664
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ice/cice_in.nml
  hashes:
    binhash: 431451d2359d10a60808c6062ec5e727
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ice/ice.restart_file
  hashes:
    binhash: 33b03a48f9e16f94c1ba1adb85872744
    md5: 64b59e77a00292359d36d22716d04c2d
work/ice/RESTART/iced.2851-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ice/iced.2851-01-01-00000.nc
  hashes:
    binhash: 1de5366083c6d42e9544bd29471c617c
    md5: 201db3347e268faa2ccbd4f221c3c72c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ice/mice.nc
  hashes:
    binhash: b6a0f36844d95c2bef019341e55b80fc
    md5: 516799f96732d4683273e1c0209fda6c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_age.res.nc
  hashes:
    binhash: 20c30dd8ac720a95742cef9a2b37f27b
    md5: 485ad4f8a46d89d9f4884774e1503f26
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 90045d2adf66621a62b97d4ee8061511
    md5: a8c3b37aae7ffafdca858ce1770e67b2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 01490b0188a7a78b16cb6727aa53537e
    md5: b753c4819012c62d5cbeeeade1ec60ae
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_density.res.nc
  hashes:
    binhash: da0bdccdd8e0e7dd6706f4a5fe0783b3
    md5: 4cc330be833b25dde3ae98e8fc76121c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 11aa7db1af6a12505e79eeca14ca2255
    md5: f8d7ce6cc7d0071cfae9a42850023824
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f02dcde3e3e13af5cd17163e6f9a9d7b
    md5: 4e85844e723b7d7cd7074e7ebb2dd134
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ef57efd2887b1ec0bb8d55c52c445960
    md5: cf78a0d097e3c568cf1b7e1cd18ae68c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d8733f70949905762c13faa9d45f3607
    md5: 695a8954bbe11331e384eb1d9c11a5f4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c2118398f56021a83bd75139d9b7b21f
    md5: 3ad5dda131efca2835cdabc1e8bd57e8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e681e7b1bfd6479ad24273e79c01a29d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_solo.res
  hashes:
    binhash: 0d4f8cb8533e29c4581bca385b0d46d4
    md5: 54cd66b85a3482416f7247189b38ca30
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fcdea16e1b7324baf5b60c7a4c4bfd16
    md5: 431b05d9631cc77d6a08361419bcbba7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a6bff1f2ddf50812dbb34f552ff9230d
    md5: dd9c47a8769d6fb630f3696e58587edc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_tracer.res
  hashes:
    binhash: 2a715f33e0cb766637aacf9fd9e771f4
    md5: 9f621015464e36697b5336873feedc09
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 95644be288b02bf3295d863953efed01
    md5: 3184831c538a42165850c3e24f043bd6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 90c7de094bf7eb588eec0c0df709995c
    md5: c5e9c3c4aed761c19c071782ecebefa9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 30de52be6a7b2c983145659fdc4fb513
    md5: 88169f54c5da3b19ad05020104100bb9
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart174/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2c882c363e3cfc62d53ba36ce3c422ea
    md5: 339568c360f105e5a9b0fc987eb434f4
