format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/atmosphere/restart_dump.astart
  hashes:
    binhash: e899330801c6119afdc52ca314c29c60
    md5: b433a9eaea1aed8ec93c32b5ec2ff747
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/atmosphere/um.res.yaml
  hashes:
    binhash: 182aa2bf9a11d12356810718a30e82c4
    md5: c828e07b637d63bed54b44723ea017cb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/coupler/a2i.nc
  hashes:
    binhash: 15a06c5898f7723052c1dabd91e4665e
    md5: c3ff3d862efa94a9801cf8d2f8c5fc8c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/coupler/i2a.nc
  hashes:
    binhash: df9a05b8970c825b17b78d2d0e1e6c15
    md5: 936c1ed89dab59e1eaa297a13da3fd03
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/coupler/o2i.nc
  hashes:
    binhash: b68e7c650442dc052a9fbacd0b0fa3fb
    md5: b51715b852580062cf6899371156a63a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ice/cice_in.nml
  hashes:
    binhash: 7336d81d3aa2d9a24eda833fde7691d8
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ice/ice.restart_file
  hashes:
    binhash: 83440ef1f7e86c9c5116f1284345abef
    md5: ebe0fc664d50e5d41403f6db94e3a53f
work/ice/RESTART/iced.2831-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ice/iced.2831-01-01-00000.nc
  hashes:
    binhash: 253bc918b3612fefa6df64099fa4d72d
    md5: d7291d548b9355cc1d1103a361ee38ba
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ice/mice.nc
  hashes:
    binhash: 924ec75c02211b603a08cc265ca74e9c
    md5: 3b37e52eed5aac13207da791a33f2c9d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_age.res.nc
  hashes:
    binhash: 6f35fa7c6bef26b70362cd393a2c70a1
    md5: 8a060035a37e5ea9b04f7cb117f55e30
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0488fceed6103fb9cf7ab00cb6a1daef
    md5: 4d36b52c1276b3241d5d1123509b71cc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 38a295ded40070f2789c1bdb8a37716d
    md5: 10d6d583a1ef7db62f5d21e02321051e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_density.res.nc
  hashes:
    binhash: bb3660ae4f20bfee3fefbdafd0d0da68
    md5: acbe8c50e7ca9f957fbb4e338dcb7682
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2d66efc2ed4d7cf0794fbfdc1e0b6212
    md5: cc5a922f95f5b3ac48ac481cf718deeb
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: fa4d9c1950265db57a2b05e01590defb
    md5: 643d55ff5d18f6102b026bf89f5949ec
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8c0777e7760b9dc1a99a1de5349582ac
    md5: dd7f43bca0f7fff7d4ebf6088e68d525
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 61afb3b19adc30a32b538c765e55ec45
    md5: a4faa3a2c8e340796d8bcceaa680ed12
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ef26cc4c293493ad9e8204d1fa8528dc
    md5: 855d774bc23c3ebca4aa9daaac0ef3a5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: de1c8e942e47b19581fd31d849bef713
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_solo.res
  hashes:
    binhash: 8507d5b01f7637c5b7442fbe5e1b659e
    md5: 5c0054143943dbb629a69d8b92154ca9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a616361fa563d08683265559b3d235dd
    md5: 5558882f60702e937e6fe50cb14d8a77
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8e14926978f03316f40b6a67419bd6bb
    md5: f5c71ca12fff7f62bd83a687ee2de3a8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_tracer.res
  hashes:
    binhash: 66df335d02a2eb10f496c7e11553b41d
    md5: f87bf1df3c98782a71c1f75a9429cd6f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 888b19d3d87734ae150db5167fa78c2f
    md5: e16a259a2d233fd102807ffe82cfeda6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ccdb37695920f9ce7c7c50f2e5a2e177
    md5: 54ad5b4d7c6d8759e7177828b326aee6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 742d88ae39faf94bc2269a59d6247123
    md5: f4e4c19888d17b42a17bded0c78c06bb
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart154/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a0ca9b01a415d0ea1a4524332c1d0e8f
    md5: ca3d51ced752623e3834aaa9161afc94
