format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/atmosphere/restart_dump.astart
  hashes:
    binhash: 7c4d9df332cb6484d08f5d1928fa0765
    md5: 959be5264949738fc65cf43a2c776a5a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/atmosphere/um.res.yaml
  hashes:
    binhash: 18af92846e1196c891f9253a6b5bae15
    md5: 5a93a83773bcb87492f3fae5dd88447c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/coupler/a2i.nc
  hashes:
    binhash: ffcbb7e3556ac507dce43caf11d426a1
    md5: 06c0de8f6251c0a5fa1ef938fd013554
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/coupler/i2a.nc
  hashes:
    binhash: caf06688ba0922a8b7473dd9d2be5450
    md5: 0fabdcd6d1276e453d474b6d367d01be
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/coupler/o2i.nc
  hashes:
    binhash: a8fa854e8a732ab379ee1c7fa24f2458
    md5: d223ed3a9f1741e6e9fc709baac6ba90
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ice/cice_in.nml
  hashes:
    binhash: 979efd49b93f1262702b071c64b09cc2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ice/ice.restart_file
  hashes:
    binhash: b5757023c79873336adbd4f351e2056e
    md5: a19bcec90e1688f3950975574d4eaa60
work/ice/RESTART/iced.2806-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ice/iced.2806-01-01-00000.nc
  hashes:
    binhash: 569ca18260bba0468ffb155785a9b26a
    md5: 35efd55b722a1de99be9cc67ee6fd357
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ice/mice.nc
  hashes:
    binhash: 8ad067bbacc327435a0c9e4560312eb7
    md5: cb6793ad7498b70f89fcdbfd8b1d9cab
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_age.res.nc
  hashes:
    binhash: 014359de19d1fc76c83dbf4951eef17f
    md5: 75741169a2e8e345aeca51bb8f9d3736
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4f70049556ffebf6560128e3423b7fcd
    md5: f7e02a4f0e3e93eed9c1e18db5222a19
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 690d70f172f186799d3ff12c13f8b2da
    md5: 23871d48e8fb30f40bf478ed1302bee7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_density.res.nc
  hashes:
    binhash: 096ce162cf7bc14c24af82564734e354
    md5: b2fc05f239ee7d6f2c37ae1487a40e74
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2af67840bdc480b96f72aa4b516122fc
    md5: 8cd1957de071a83006a6433bbdee6ba6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f74692f969fc009d6aeb12d4081c5c7b
    md5: c241d10a7b490ffa06bbcbac35bd1189
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8165e06ffedca65a0a0e9876b238daad
    md5: 44301a88b7d05b7e612b14c1cb1b28b6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 596d6245d87be91286df59accf107b6e
    md5: c90e007ff58688d97e461521cec7c44a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1b8a0a7e0281cd0404396135e927053d
    md5: 16ccf98e704f61273b4bdf28deb869fc
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8671b7dab2bd675d9461ba5da06b3fc2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_solo.res
  hashes:
    binhash: efd1f81b50705d3dd01993e12ade8a42
    md5: 84a908c7ba9da95722e13842bef073d0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bd0636cd22cf9222c596a1ba56692f10
    md5: 78410fd18163a87800fb613c2c9f9ca1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 00a8f3c6880cc58ac84c459bdad0dca5
    md5: 3bccb83e26639789331610880fa4c1c6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_tracer.res
  hashes:
    binhash: 31fb322415d3599333a7c72c2adca4b9
    md5: 2ad1a9f2d4e9830826d00d44242623de
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e0a645e4080fc32a1d18c2c3f414a0f1
    md5: 0e3f14d1ebd0d114d6a26d0155b1e274
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bfdd5b972601fd8d036ffe5fd7361eea
    md5: 0cba92cc9e753e8842b1f9354daf7951
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2f46a268574312d169260ae0f29c0ec5
    md5: 3b6dbe48fca826429f788ec772dc4687
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart129/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3d56bd3201e957cfda37b786f0c97cd3
    md5: 58b4b72419c75827ca759b8fce0392a9
