format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/atmosphere/restart_dump.astart
  hashes:
    binhash: c9192054216f10e1ef2b8ee7680edf6a
    md5: 655b11975618cdd903e605c01f303788
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/atmosphere/um.res.yaml
  hashes:
    binhash: aa8efa87b02054a1bf006b3aecdefb2a
    md5: 3c7a0f1725a4009f55cb0f6fb0eb2bb5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/coupler/a2i.nc
  hashes:
    binhash: 47e4f206e0bbda93f5e03d5d8e8a419a
    md5: 74eabde4a37d5064b9a23ccef1989e10
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/coupler/i2a.nc
  hashes:
    binhash: f1e8e7d1a0bac4e85fa76a83a266ac27
    md5: 1f2e0df024fab84bebd54d8d8e196cc6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/coupler/o2i.nc
  hashes:
    binhash: 62b6dc3f9b891e5437ea54add10cce4c
    md5: 2df15d1ed5e8b4b913a0f1f4dfe47245
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ice/cice_in.nml
  hashes:
    binhash: f0b1b5a5d351e81def5dfa49311b5b57
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ice/ice.restart_file
  hashes:
    binhash: a85b98867caca1c38080608c8158a780
    md5: 87428bd39febdcc32bba6be2971839f1
work/ice/RESTART/iced.2762-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ice/iced.2762-01-01-00000.nc
  hashes:
    binhash: 0e9678184e8ba61cfb95ca5501e4dd39
    md5: ace03a254b44447a8f177cd9faecb606
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ice/mice.nc
  hashes:
    binhash: 8a2a6876721163729d0961370fdffd3e
    md5: 78b350969763987e181ddcc33ca2d15b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_age.res.nc
  hashes:
    binhash: 14c174a08bbfd2372ca367e76676c012
    md5: b0fd12b86d83dbde09c91f347f1785d7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 21bec0c517412c06897c501a3c562e3a
    md5: eb08dab014ae0c175db63686d7c2ea3b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2971d6b3deea64b88c602d5c0d369cc6
    md5: b5e4090789cc69da09a296cb767a3963
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_density.res.nc
  hashes:
    binhash: 1b9f8b6a7568051f4d9efd8cb9581d8d
    md5: bb65d5b64d0ed56ec96e278aa28d7d40
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4ba2ed893a5cff410eef5af3dc958037
    md5: c2a6bbdb1563e09709e5b7461cc2c43f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 03b0c3ecb963f7aefca8ad849349a741
    md5: 4ca98b82b15fef161bf7397525e0eba3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 94745bb3cfe52326256d252567d88f78
    md5: 0c0485e7ff0a1055baed04cf25f20c57
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 50a4e934a231b0c7dfe4e15b48c6dd51
    md5: 4912824482cb68fd3d606080ca66da75
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9a682518234333342afa0142cb256ee8
    md5: 861eeb26f7bbe92382835ac14a92dc13
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b6ba35b71547d77236de993fe83cdbc9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_solo.res
  hashes:
    binhash: 5f1540298edb56633bd6e28fdc210f22
    md5: c961ff6b815c8233129523150f5a7683
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 500b706fc8206885f350d641af582766
    md5: 9727ded938a183be891273bc6214d1e6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4c99dc0704a3e3fea73838d08d297303
    md5: e27dbf3a383cb73516b653962c63f73d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_tracer.res
  hashes:
    binhash: 5cdba8bee03ee8ba8ea1c85e2771fd49
    md5: 8a8b0c56740973da6e3c55a198ae8117
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e63685cc1f20f203329fddf87107baec
    md5: c7fc5cf99441abac801404592fb821ff
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ec3cbf1f1c55c7ed429d0629dc412a72
    md5: 6d4f866d8909ae66b609fdd497f91124
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ec4bb70f5b37b13e7afcd9de86208153
    md5: efeb3aa2f1f85f256160e7984b68f71c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart085/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 934cc5366e2a8752b6b0bde4e8c1ba81
    md5: 55d196990c74fdedc2d919babefdc434
