format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/atmosphere/restart_dump.astart
  hashes:
    binhash: 9edcbd6de2a14fa5576eaa1409957a7b
    md5: 56a8d3e01507220dbdb4f4267e6a6c31
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/atmosphere/um.res.yaml
  hashes:
    binhash: bb63ab8cc21651ae9f4d6123923bc610
    md5: b1e35729e8ce118f4b15b6b207839724
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/coupler/a2i.nc
  hashes:
    binhash: 16f9f4d6e61efabd46d7b48fc43419b2
    md5: f5c9771986e631cb5e4b904c0490c317
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/coupler/i2a.nc
  hashes:
    binhash: b5d016bf393030d60abf58f2cc492b41
    md5: d0c277526ccbd30fcfad109aab5ee806
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/coupler/o2i.nc
  hashes:
    binhash: 92f01ea9f45b174544c3171f3f097311
    md5: 365f8eee27b3660407eb24520c69802a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ice/cice_in.nml
  hashes:
    binhash: 83bb37c20d77316a68f6e7685db06289
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ice/ice.restart_file
  hashes:
    binhash: 9a4cc6018a70f491d29478744ba5a4e5
    md5: 0cc2afc887d7a43a794559be19f36590
work/ice/RESTART/iced.2801-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ice/iced.2801-01-01-00000.nc
  hashes:
    binhash: 721556ddac55ea995743a54630170d94
    md5: ad73eeebd74ec09390ee0b30b9344f37
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ice/mice.nc
  hashes:
    binhash: 2b656afabff3c66a0035f7a24403f443
    md5: 63addf3448bffdd70298359b8904b229
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_age.res.nc
  hashes:
    binhash: 69443dc37fa8c9db6f70a8098521cca9
    md5: 98d6d3462f491f0e5985381c42bf3d38
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f46cc088943fc59301c83b14f3cd1e4c
    md5: 18657a970da5dc58caf418926d9cbfbc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5ab7c29a90b02d0492b052938a496fcf
    md5: a98281f2632e2145696520731dea1b0f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_density.res.nc
  hashes:
    binhash: 2b6fdf6385946f8fc39134abcd7eff50
    md5: 3dc66461257c302952ffd9cca22a8066
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d81d7bd4e9025066a425ce60932c720e
    md5: 8b26644a1087a8fe1bf599cfc35fb545
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 91b1550131f463d9bb02af73f44c6d3d
    md5: 8d807c35cc74fa455a99f39468fac8eb
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bc1e1f71d7591d1347799bb9010fd9a1
    md5: f4ac8eeb61ac4e6903e6c6e0f46c2329
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bdb49e31e4a5debd4ed43064a533374f
    md5: dc95f70fd592d7dce14e78832143066d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6104beb6c251547e4555fa88daac06f3
    md5: 045b584b7454ebaf02ae63e006e40b74
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 94e4b13c59c6260be4e5efbf1ab1510f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_solo.res
  hashes:
    binhash: 5d9703ac57d08b3ea4f887409ecede52
    md5: 1caf836757b1e2ca822a7a9f659ef428
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ca279671aedbd6e0fa2a968ee1fdd8d2
    md5: 079e33a31cced02ef86f7752f0811e39
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 572e767850316ae4aea474541141315f
    md5: f761197846dfa3ed63a309e5067bf7f2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_tracer.res
  hashes:
    binhash: 142ee9e395b396b95041215db2640460
    md5: 615bbbac900085684d29ed543fcc0e25
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a70aa494e2c69e009a830d22741dd4dc
    md5: dd535663415c2f8b2eb8f3ec85a84007
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f58272ce4c586f1b152870f52532fd86
    md5: bcdcafaa69e6fe5d6e7c32be52c99775
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3f141273f6747acd59eba7ef5eb5f670
    md5: 55ca01426edef6c4691343563047817d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart124/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 20579ea11c425a622a1d199fb8eac787
    md5: e0626d7a240b2db0f143fe9b4b6663b6
