format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/atmosphere/restart_dump.astart
  hashes:
    binhash: df2802618c89277655501b9e82e3812d
    md5: a14441b34e0d97504abad27158ba5099
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/atmosphere/um.res.yaml
  hashes:
    binhash: aaefdcb89b6423fd9dcb4ff1b1c83bac
    md5: 163074b757aa5705691ba759067c10e2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/coupler/a2i.nc
  hashes:
    binhash: fc438875dbfa9bb644dedbee3283a077
    md5: b76f76b0487aedd4e2028f837eb0c66b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/coupler/i2a.nc
  hashes:
    binhash: 604045ddc7467aa3625d31aadef52dd8
    md5: 78d0b75cb0fd7635949e3cc79159fcb7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/coupler/o2i.nc
  hashes:
    binhash: 30593ed8dba27b804b08dd32f9c2b16e
    md5: 41632febbe2879c1e977a695cc0500eb
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ice/cice_in.nml
  hashes:
    binhash: 9cccebb1fe23bd123a938cdb8aefe055
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ice/ice.restart_file
  hashes:
    binhash: ba606a5a4c52e05019c549774bcca203
    md5: d4d0b1463885ef1b74ea8e683ed11f3a
work/ice/RESTART/iced.2854-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ice/iced.2854-01-01-00000.nc
  hashes:
    binhash: 25ddf513361f3109b3a28318292e1faa
    md5: c8d1916adb48ce4b49b11b824b9d7ac7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ice/mice.nc
  hashes:
    binhash: edb4fcd88efccb76642c55c949f98256
    md5: ceb8295a0d2aef2fd85c3e6bbad4aeec
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_age.res.nc
  hashes:
    binhash: cdf367984cf67a71e897a8d91104ffc4
    md5: e98a2502471755c61300ffc707ee7120
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3b514af08e6118fff57b488a191a28c0
    md5: 302910e0d6659361861507d5bf0afcfc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e30b18d450be3d35995e6cef2eb4eb4e
    md5: db0614a13e520be970e54e725596fcff
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_density.res.nc
  hashes:
    binhash: 2aaad752a4662289bec19b6a0f503cc9
    md5: cff5fec2f115e95ec80baa580b64e0cc
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f2f49db0daa8bad300cf4265f08d34f4
    md5: 8a195b820142280fa594b5b72a965840
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 86b9933683c1f0a2969cf54c032409ba
    md5: 3997701ebc759e2c0f1afdc838eba735
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 86b3395470d57b8810719bb515c05b27
    md5: cb0c8fefcbc05099bf15eece304643a8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 48b3b04c77db71e736f68907c961e9e4
    md5: cd3e9fdf81cc5538b2276e44f54c609d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0ff667cb91c3ced528b08615ba9e0ead
    md5: 14d9abb88215744c79d300acb191cb69
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 94068ade28926cab72b3951c3b054141
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_solo.res
  hashes:
    binhash: 9d9e45ce6d79585d4dd2625e499b8f76
    md5: 93d34274f13916cfb0ab79ce794ed9bb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b4b5ad9e1af092e7636d7d6cca740a93
    md5: 074bdca8a929e593561735e4f6a4203b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 200110980774669c418baf71307b990f
    md5: 07ab6bb58e04201ca95345c394d6cd75
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_tracer.res
  hashes:
    binhash: d0f053ca6752c29c7c7825158d1f2c54
    md5: 63fd88bdd88e1d9d6c82317d50d3cc49
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 02577635bfb399cb4e8a4fcba50c94ac
    md5: 768b599e23cfd5c59f6ccddb3c23199f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 64a63e9dc26ac01e7c944c7e1108f3ac
    md5: 26be1d38f5f5cdab4842c5394fc8f7ae
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 463a7dcbcb34308c8da371abb1a8ffbb
    md5: 17dc53d7ecaee1433c23bc4eb69def9c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart177/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fb053aba4eba54036552388a074f53dd
    md5: 64bff11d772785a1f7d4c78daf16dcc2
