format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/atmosphere/restart_dump.astart
  hashes:
    binhash: 4dab542a05d1fd8a980fe49f86c578df
    md5: 5ab7b9b1cc71477f7af8aa07cf581a7f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/atmosphere/um.res.yaml
  hashes:
    binhash: 2d02376d9e95b1a6d426695bb7fd5ebf
    md5: 69d3bb198c6726df026386fd35b3251b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/coupler/a2i.nc
  hashes:
    binhash: 039ec4a808360daaa89859ffb72f04be
    md5: 887a606715fb023596f092dd622b9e56
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/coupler/i2a.nc
  hashes:
    binhash: 02c91ef0a7ea871e594b344933321e1c
    md5: c2b3145d36f92292cfb2b5a14f04b36e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/coupler/o2i.nc
  hashes:
    binhash: 44cfef4271078412e3a469436778164e
    md5: 397568a2347625d6ecdbf69bdcd732aa
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ice/cice_in.nml
  hashes:
    binhash: 5fd5f5531167750daa93c604cd034e79
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ice/ice.restart_file
  hashes:
    binhash: 890a958430673e17cb4376e605cfa534
    md5: eaede3dc46c99f9b623e384ef1981f34
work/ice/RESTART/iced.2894-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ice/iced.2894-01-01-00000.nc
  hashes:
    binhash: cfb415acd3497a2528e766caba3cc1e8
    md5: 0b50bc67c9d3f309a35a304ace57fbd5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ice/mice.nc
  hashes:
    binhash: 7e4918d4f61badd34b1d18efa109df50
    md5: 40f546ed95009447916cb925db843b67
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_age.res.nc
  hashes:
    binhash: e5ef693ad8b09eb7f0a7bf57defa857f
    md5: 3008e64e1696fae6e73b4a4dd6db1627
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 32f3e4cfbbe77d130d13a3447def2980
    md5: a8cda44de69c3ec16d322d80468b225a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fa69ed5c14d753fcb46bb53b31f27d55
    md5: 648ecf5689f24b45586d3d6f0e063eae
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_density.res.nc
  hashes:
    binhash: f7cc6c1f9398bb39b994b6c2b3811752
    md5: ed407adf6c2a622563778d1b16eedf9b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6124e48710c3a248c262c8efa4705e5f
    md5: 80ee67db14745d9a46dd7e23589139d9
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 077ba6e31f84696db0ccb41125aec577
    md5: a08d7ca851335df27a3bfe7b15729f1c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 15a9e4c61e2354f2fc4bc8af65a62afe
    md5: 1f228b38fc5c6dbbdfd0c014a27298b4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b8400844694dc83274eb9c76293cb5b2
    md5: 53e0fbfb71e6ccfad1f979193fbea7f4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c8a190733bf0c8d38b54e41293dda573
    md5: 04ba153d8fb3638ccd4cf593c50aa0cd
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2bc143c092607ec959786aedfdf9da79
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_solo.res
  hashes:
    binhash: b3c2fdcfe10f03e5504856829c57492f
    md5: 229d099e2198c1f397889de4c1521972
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fbfd5c4193cce32bd851aea3d4630194
    md5: db83f6bffd11ffc0e9cb4e4df8f088e9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 464ee5eea2928b8b274aab7c95a0dc1d
    md5: e3541994db830dc738a2796bd466d608
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_tracer.res
  hashes:
    binhash: fd88a72b71a3ed7359b41fc6c0718fca
    md5: d54654ac99aa5cc71d17650ff7b83c33
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_velocity.res.nc
  hashes:
    binhash: cd270f1dbca6462573561fe82e1a28d3
    md5: 2798155016e14e6dec12f159b22186e5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 65ef3c61a2b1bb1bb3951e4bf797cb1d
    md5: 0bbfccffa701bb7d55788a32b628d45c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1305389a672f91432c082f056f49757e
    md5: 21fb136f4a339d8d3d0ebb2d30b39cbc
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart217/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8453932aac201daa46bf0581767adec8
    md5: 79efc17005ab31c6263bd4f0a71a9e58
