format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/atmosphere/restart_dump.astart
  hashes:
    binhash: 7784cf663f8dd273ca5e087bb4e9ea23
    md5: fda68889665417b65f0ece6b639bb486
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/atmosphere/um.res.yaml
  hashes:
    binhash: c27b592bb1103b63f80771e857bd24a2
    md5: aaf5d3f3a2fb2b2636e99b096f61ac34
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/coupler/a2i.nc
  hashes:
    binhash: 7630ddfb2f76576ce0ab58b3787b2565
    md5: c5b848786caee0489934be92a9058576
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/coupler/i2a.nc
  hashes:
    binhash: a722d701565356e1b5e77b2c438fb3bb
    md5: ba3a4e47b08f48258b3f0bd38c5c38a8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/coupler/o2i.nc
  hashes:
    binhash: 8fe4fd037dc32b1cec4d7788d2979536
    md5: 12c85f9cca658cfc0d876836ab275fde
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ice/cice_in.nml
  hashes:
    binhash: a1f79fa7d3aa9eba1447188baf2408e9
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ice/ice.restart_file
  hashes:
    binhash: afc2b9acf14e1fed0d1eb82d5e8814bc
    md5: ac9e6712c0780c5eebf945d8142f5250
work/ice/RESTART/iced.2678-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ice/iced.2678-01-01-00000.nc
  hashes:
    binhash: a5e4a94cde2036feaaf28c42f9356319
    md5: ac7f3196314c36c65be8793f8fb754ec
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ice/mice.nc
  hashes:
    binhash: 34e7a2ca3859539c534224de98196f4a
    md5: 89a729764be45aa3a0c8f2749765496d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_age.res.nc
  hashes:
    binhash: be811ffc67d0aea0057618a8f265e34c
    md5: cd5b4c9f3afbb307317114dc79fe6aeb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5c03fffc7b4eefc1f726281eab7fe798
    md5: 6f6eae2bf36fa55d161f1d420c8c17d2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e64c82743fd0c8f6b1393f1801361315
    md5: 3f22efeb6d211c23525c7709f9f30f29
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_density.res.nc
  hashes:
    binhash: b70d6b289cd8cbf287fbab155c8bfdf4
    md5: 4d03655b14559760c99ed040c98715e9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c3c76e25f4c64bfc31c11c2719d68d36
    md5: 8f0b402d1219158388bea87028f24cfb
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: afd50dc946752f9d14edf1723f68d3a8
    md5: 8767a8e8098a5ddd4cdebc94e814bf40
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fd7f01cd13ff6790bd0bbae2a5a6ba34
    md5: cd4be3cdc75d5bbda3330f9270267d0d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1e5481bff7ec635e5081f01dcf31eb2e
    md5: 2365deeae55396987e6dc6cd56d7f629
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c3123e5717bf4ddb1e3454b6400507a7
    md5: 99df8af9a29a438f02d800d78c38320f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 417fd13c8848bb14b7a1e3ae9d85d5fe
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_solo.res
  hashes:
    binhash: 1c29fac685954b4d0ff4c29a507a36cb
    md5: 3c3c57daa724242957dd51ab579d6e0a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7bf61622806fd59c7126492d6321435f
    md5: 8e06b264113a1cc9c0346b5fa09b9ba8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 28cae78cba055ca515fd4a5df51dbcf4
    md5: 4d4edde5b0a6efb154ba2d3f068afdc8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_tracer.res
  hashes:
    binhash: fc3d389f8dd1f58f4584dc14c85d8ce2
    md5: 0e1bcc4d02102740b39711c488bdc42e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 585d41e2b690fcaef45972da048f080d
    md5: dc33a8732c2f7c8c2571c7bea85af8b0
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: de6048da4735532d88c5cc54b6bdea28
    md5: 5b15f6e866342e46bec9591043d1114e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b486e75182c55c77c3b9b9e21c20d3b7
    md5: b4cf1cf10ccf480e61bdee545b33f87b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart001/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 47f0bde65d9813e77a5c8e02fa7c7e04
    md5: 9360faa5d63e7d7b06c66bbe4900aa15
