format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/atmosphere/restart_dump.astart
  hashes:
    binhash: 4384d6009ef69279c62c0263b100a132
    md5: b7903fdc404684efa69be8d3124ad68d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/atmosphere/um.res.yaml
  hashes:
    binhash: 13de5bbcb8986912aa96f6ab353729e0
    md5: 41562b87da8e0917d182ca126f53209c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/coupler/a2i.nc
  hashes:
    binhash: 2a2aab73770620c4083345dcffc01d65
    md5: d96470aff4b9c0cf3f7e8dd2f097b572
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/coupler/i2a.nc
  hashes:
    binhash: 24e303e72604574788f1c7e4f99ca086
    md5: d5cb0c4a7bb18b8e52b0b14f5cb6555b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/coupler/o2i.nc
  hashes:
    binhash: 689924b89247a3fbdd944066375c51b5
    md5: 8028eb07441ba54d3f7f970fa24fe458
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ice/cice_in.nml
  hashes:
    binhash: ba0a8739407d36db17f9e5669fdb54fe
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ice/ice.restart_file
  hashes:
    binhash: 935b0011c09ed054ca71d63f5e205c34
    md5: c69a3c4cd2a589d591d3bdf174d5d74d
work/ice/RESTART/iced.2767-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ice/iced.2767-01-01-00000.nc
  hashes:
    binhash: 7880fcd3855cc2ca192f2256f60d773e
    md5: 679a435f736b1fa10701ced772e5c7fa
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ice/mice.nc
  hashes:
    binhash: 72ed9fb01b83165be9bf752e3777580e
    md5: 1a1d71e8859b165e068028ea373ed8b7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_age.res.nc
  hashes:
    binhash: b2452b9db90c602c6cb8e33b6e2c7efe
    md5: e4e4dd46fca06c5b02474202dfdebfb6
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: dd6b4cfb586df45d56586f4db884b2ab
    md5: 97de4dab08da3bbafa696edc973b069a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ea1348cff4960a09cbd5aed1125915fd
    md5: b721cc8f1fac4bf4acd1d86741d05b4c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_density.res.nc
  hashes:
    binhash: c32297c378564f08c13e019b65592eb9
    md5: 3191263127604347da7c503f3265bf34
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1ab802cc25305023cc7e94536c4dc74f
    md5: 0edfe1b07fbb4380fa597671c285b5e6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 005f78c9ddc6106da6e0d9bfbb45cad4
    md5: 9af37c3c8bd43a1dc6aa46fdb072de69
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3d668169fc4a5996529edca473abb14e
    md5: b715260d7647e8b9333df6962b38e4e7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c9d14ee3f380f052b506cf3777a57ab3
    md5: 91691e455d334791a6796bc177f1bfe7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b438d049f3738f2afd12520918e1be8a
    md5: dac611ba6ec31a4a01200cf44c7b99d3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5985540c18983d041873b22fdd601a52
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_solo.res
  hashes:
    binhash: c005a5df994d840448bb3e46acd102bd
    md5: 203542b6f8a74fa022ddbd06a0416d71
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8f3bacb9979a0727a02b12eac00933b9
    md5: 857eb3fe7cc847a2f526f2f4199697b9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0c6dbd962482e8ae21b0d436d4b16851
    md5: 5e07f5def46118732a079816cef8a7ff
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_tracer.res
  hashes:
    binhash: aa643e206314c6b15dd820b6b68eaadb
    md5: 68b2433a6fd2a0759fc9a20159dad381
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c1e31a866aec5370c631f36042edf462
    md5: edc3a8c9a91ddb87b2db67d8902c6984
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e537aa0ab29375b25a596c300008dec0
    md5: 01b471ba8b88c4d89effd6c7f3bf24cd
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a7549379465100d6863d3764a971b033
    md5: d250d759e6980666d240c50f24fac7ef
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart090/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5a274e83806f710ace0b51b6acc0dfb4
    md5: 88a5f65a4d8e2eb9a3c220d4f65406f3
