format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/atmosphere/restart_dump.astart
  hashes:
    binhash: cda1133d31051be56c59caa7ac829ee0
    md5: 26b8582ce4e951eb490397e5834a7d67
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/atmosphere/um.res.yaml
  hashes:
    binhash: 7264be0e0621783d0fde5667c0d19aa8
    md5: 89a77224785dddfc34f6214db305c7ce
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/coupler/a2i.nc
  hashes:
    binhash: c3c600d5d33b0398ee96355cdab4a339
    md5: 3b19ec9ce0a9a873752771e7d1dbe709
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/coupler/i2a.nc
  hashes:
    binhash: 322950dc6cd0e3f0cc1ff73d3d7f8cdd
    md5: 2936dfaa9f2b617a9538aac58bcb7632
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/coupler/o2i.nc
  hashes:
    binhash: 72ea5837dac0daf8e9ed45f77e73d420
    md5: aa1599b36a4dcfd5d115a75449aad0d9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ice/cice_in.nml
  hashes:
    binhash: 9d5bc0613a99705791e7d1f66c09087c
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ice/ice.restart_file
  hashes:
    binhash: b23d37cb3e07253f7a5cb2561aaf2f00
    md5: b749d3f944d82c42c795961fe9fd75b7
work/ice/RESTART/iced.2824-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ice/iced.2824-01-01-00000.nc
  hashes:
    binhash: d1e10c7ce6bcefd96853ccb18b14fff7
    md5: 3da8002bf31f6a6ceade94b00e0f004c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ice/mice.nc
  hashes:
    binhash: 6613dc3630e8f12cf986500349d74f01
    md5: ba680b87b9a7aec3f8e5e04fb60f1426
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_age.res.nc
  hashes:
    binhash: 1af684edefc39b93d08670a5715ef82a
    md5: 4c03b8788bd5d6f64f995e894e7d112e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 237e762f726f813aadbd9d26649b8566
    md5: 9c529971256d56128f9ceacb165be597
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 77cb6b5ea6648a12fa93ba08c2a505e2
    md5: 52a51b09f9ce37d2c34246261422cefa
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_density.res.nc
  hashes:
    binhash: 578e8f77c0c78072df1246522f41e4eb
    md5: ab6d5f3487d91becbbc35f70da851d02
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 36b0f3f6e9699f79d4667058a9af37b0
    md5: 3a88bfa475a7cc447cbb29a9568fb8fa
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a250870a7a0fdcb8a204425aa2292053
    md5: 6974bff2fc15178947fc45c33374a437
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7c8703b504ddc1adcb84c501c0189279
    md5: 7d7a17d281a0b6213a827a329386c217
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7fcf6f5c5ad4cca137ece79ecd2bf6c4
    md5: fa67f504c574072976f407558e5455f0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5365665b47d90c961ffe68481bd17c85
    md5: 27f1be60ffad9b327b2a0935d8a272f0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4c087d14930f7be24bf0f82b73674e58
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_solo.res
  hashes:
    binhash: 12cb41fe72b6279d6696826666d8a24f
    md5: 2582fbb22a1b435425fe662b195710ba
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6c4530184bce918b1d76ef73b7a7dfb3
    md5: bd81113c93e81214aabc058155e37ce2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 690c07855eba5d96b0c799fd8c959224
    md5: 5b1484fdc3955a570583618f6ddda8a5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_tracer.res
  hashes:
    binhash: 46ca55baee81b7cafdcf41a434898a06
    md5: 7c8c9e3e6f02e12a0e542c2842f391eb
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8e1d0d5f1c164160efd97ba3dd31a36f
    md5: 35e497f1cca959c4c546a272d2d9387d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 74d61855291f89b44cddc92da9d87dca
    md5: 68da172cfb8d1f1efbf1c3be3c81abb3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: de3c5088711100d64634e134776d6624
    md5: 72b918f7ef1f0ad8f73677c5a73b56c6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart147/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5bf2f00131516acd080b8a6071aa9679
    md5: 6d69bcdb7f6820a493f7de5632924e93
