format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/atmosphere/restart_dump.astart
  hashes:
    binhash: 63274b93320efa03a75faf8b1d3ff312
    md5: 612b5833ee9209cdf9d4b487df80dbfe
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/atmosphere/um.res.yaml
  hashes:
    binhash: e68929d71a5612c97845dd0874a61ffb
    md5: 6837b6b9ab94a1b77d90c984745b46ec
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/coupler/a2i.nc
  hashes:
    binhash: 781697b19af1008b02f6caedc9a2cbb0
    md5: a9bc91dba427d994a17e0a76fc17145f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/coupler/i2a.nc
  hashes:
    binhash: 2adf2cfed41c381b72ac64fb941b5502
    md5: 144650b4aceff29a8d5578167b1cf26e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/coupler/o2i.nc
  hashes:
    binhash: 31587dc2aa2733abe1b8109971f8f4f2
    md5: 806742c268bd825454eadbc004b605e8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ice/cice_in.nml
  hashes:
    binhash: 66c2d9e1f8f35a94906292a3366fe07a
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ice/ice.restart_file
  hashes:
    binhash: 51f89e4e27ad693b95000c92573341d4
    md5: 007f49a9b32be136ff03903ab0628719
work/ice/RESTART/iced.2749-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ice/iced.2749-01-01-00000.nc
  hashes:
    binhash: dae7db6c495ee3f45fc3620882eca7e5
    md5: d60af39b0fcca8750570274dfc3331f6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ice/mice.nc
  hashes:
    binhash: 80db6285ef6b6356558c9df14a98baff
    md5: 4cb49c54ecde17fa9a8efec7874dcf5f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_age.res.nc
  hashes:
    binhash: fd91e55e24d5e1544602070321e2f6e5
    md5: dde50d42018c324ca98e861d18d70e9b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: edb155d14c8e17a59d542c748295c077
    md5: dfe1b6cc213ba1e8707fccd1527d23a2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: eb46dc8b2afb95561eea2bc031485071
    md5: 8bc204fefe123950851b62219e3edc3a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_density.res.nc
  hashes:
    binhash: ffde2ed0bd46dbe21361fff3007a3343
    md5: e732d7cb1445bb7e5c31848c0babf136
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b08a01109b059cd7a17ed00aff24390d
    md5: 641ffa47dbaca7b7c7d7c25aeb73f71f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 51400701d8f2df87eaac3cafc336e7b8
    md5: c1cd1cbdcbcc621db5d4fec245c745b9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_neutral.res.nc
  hashes:
    binhash: eff9c43498b2d8ff5042ceb71800f968
    md5: 0c5cd5541d115bd5edccab7a71bbbc2c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2efbafbd31eda8458cd3b6027b8c8807
    md5: 9207da35033f43d28b00a43f87859d73
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 93ca237b332060f88d701aaad6da78df
    md5: 2a8a815077320c44b77b86918fe389fb
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e604bd8eb05b17ec4472546587e1b300
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_solo.res
  hashes:
    binhash: cd6420012ab4b265a33691ab077be45f
    md5: 939a0f6cd8c0662e095164dbd213aa1f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3c9c614d795ccf08a453d58587bf83aa
    md5: 6606e81a09a6f20a905c4815783eaead
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 57f9484b34722a263717fab68c08feb3
    md5: 00cd4b5b1cf196703323b2357848ed42
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_tracer.res
  hashes:
    binhash: 639c1658ff6dfb8320f7b2b9bb095e0e
    md5: e9d7cfd6bec4586041bf5f2ef9013991
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a475875bdaf9b8fcc3090e7c274c5698
    md5: cba1e95df0cbb2692e5252524f1911cb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 19cc3d480b740936cf5cd1e6db1dd21b
    md5: 1f42fb19b612d8ae434daa2bf69de1ba
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2692b83a8eeb08792b5d7fa20b633423
    md5: ac95c276f9b343be0b7962b0d2764d62
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart072/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 182e1b7c8f2ca553723c723c67b48c12
    md5: e9fda1763e1eb43e0f12ec9937497e7e
