format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/atmosphere/restart_dump.astart
  hashes:
    binhash: 3c3673e11426de6b07911251058bf99d
    md5: a1ca20695aa18d821de087411888b71a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/atmosphere/um.res.yaml
  hashes:
    binhash: 50d50ca6ca879cc5c0b491c34e7fc8ef
    md5: 61bb961c8290b72cfb081138ea8f0afc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/coupler/a2i.nc
  hashes:
    binhash: c7638b81b6bfb17b1257dbc46cb6fb88
    md5: db896b588f5654280d4f0aee98ccb82c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/coupler/i2a.nc
  hashes:
    binhash: f17afdaae49cd8715390d91ff389dce9
    md5: e8e2855135fc0ea5a7b08550305c17d4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/coupler/o2i.nc
  hashes:
    binhash: 724c916bfeb37a5ddc6ccf0bf23a51d3
    md5: f9ec618cb09a5841582dd4a7d600f5d1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ice/cice_in.nml
  hashes:
    binhash: 83dee60ea3189b4e7886b21dc519a19c
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ice/ice.restart_file
  hashes:
    binhash: fcbbbe4c92e7af4cd82885a28a03972b
    md5: af01aad0606b93bb0ba183af5dd7d287
work/ice/RESTART/iced.2881-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ice/iced.2881-01-01-00000.nc
  hashes:
    binhash: edce77d6368f5289ad9d3000c6524b9d
    md5: 42c14535db0b2ad37a9c1327c39e86cc
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ice/mice.nc
  hashes:
    binhash: 1c3a7ee09c064a71cc63a6dd03cd16e5
    md5: bc1478965f668707f7e5d6664db30277
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_age.res.nc
  hashes:
    binhash: af2fe9d155788e6dda9ba79d9b59b15b
    md5: 2124b2349ff748741a2e076da4a464d5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1fa1b3b8e885ade5e6e5cfecb0693b29
    md5: 67b498ee9811b23d25310030f69c6137
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e7ef2732c227c8d3f1cd4682cba4ea11
    md5: 779bc257cea0dbaea2ffeb2b5b85fbe2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_density.res.nc
  hashes:
    binhash: 7c582e263c260d383eb9f0fb6bcaf83e
    md5: 8217492e7fca3463aa442ba30db79b89
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7768ce93dedcf2ef665200b03f33b822
    md5: 0e2d117339292ea50048175330619906
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: cb98f6cec7c2cff8732c0765b1fa3dbf
    md5: e7c905a8e1d693dcb1292ac184b9ee7c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ce0d122354c52a1dc2d4345aed7d4d5d
    md5: 40aeb3b2ea8da76a6bff72e9b85fa2b3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7ee6212bb0d0cac5169abe25d4274385
    md5: b05c617fc6fe889759ca028d4b09e2da
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 81f4b18f971e3d4b8b6b38ab8e1510a3
    md5: e8d4a7c46e433de39db0577f40771b4e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2b1075959b77eb6d6225eb01ba834b0c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_solo.res
  hashes:
    binhash: 60048d8b45b8fcfadb00c0ad5d82a970
    md5: 1763c79cde3b660ef9088d3d6cc87f5a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4e763e08974a9b32023405c07e15846f
    md5: 1f985a50ccec7308e57bba6ed08f677e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d2c10ff4f250966ddaf64a5e7ffc1bda
    md5: 613095dd142e48a91fa9a4d8e3c06f99
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_tracer.res
  hashes:
    binhash: a2e88ae49807945e6825ba8941bf9e65
    md5: 314c6b242d29ccdca1c92dfddae35364
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d9d6fc03090d5cf1e03a58f15d4a96cc
    md5: 2cb1f3325b1d0099c39b9654b19ac522
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9355e52bee4b7de54e65f4108c88ac15
    md5: c7c6b90f74d41d80b1bbbe62b025ec7d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 858e548bb4cd82fa9e9d230d2bf20dd5
    md5: 60c7dc450e7a2edaedefd3955363f95d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart204/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 148c7e5bb304a9e0b2a1852d8353a8db
    md5: f750bc69806a6012d244bdab45fb12b9
