format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/atmosphere/restart_dump.astart
  hashes:
    binhash: 719d529d90d466dbc97c9291c4543a79
    md5: 9e4457df2a605f3caa0f4318e1eabff1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/atmosphere/um.res.yaml
  hashes:
    binhash: ed8ac1980e308da068545acfeac5359c
    md5: ad38f8ac3130dc9f55d49ceb07d77606
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/coupler/a2i.nc
  hashes:
    binhash: 735fb5bb5cc585519c92be5c3543a7d8
    md5: 0fc592c82a7ac8e0beae73847831b51b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/coupler/i2a.nc
  hashes:
    binhash: 08fca44a483265b39ad1809114ee7520
    md5: 0a257346fe08783610844c1cc87aecd6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/coupler/o2i.nc
  hashes:
    binhash: e20ab00fe386dd6644fafc3f5b7a30d8
    md5: fa63396883751e9aacca33edf4ccab5d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ice/cice_in.nml
  hashes:
    binhash: 6e4e2a2783596da814a6c775b5b5305f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ice/ice.restart_file
  hashes:
    binhash: 5a364e5caf1fda05d66b9d150f270faa
    md5: 03d41073591c3c54248ecba0588776f9
work/ice/RESTART/iced.2805-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ice/iced.2805-01-01-00000.nc
  hashes:
    binhash: 82a2014d321675b7e39c02357c12584a
    md5: fc00d110718659547b5ccd0d4f1f4b5c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ice/mice.nc
  hashes:
    binhash: a3168323b3860ce177a28301af7de0d1
    md5: ed702c1419d1080a3cdbfe9556e95cac
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_age.res.nc
  hashes:
    binhash: ca3f2eb0ad7070851167d84249772036
    md5: 037e889e713dc40b127a3d55d8ed8b10
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 00b79b489a6c58233865e28e47eff505
    md5: 7ff1d61b837f4f98ab400b892567f872
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: d79614591aa29705884c8a8b253abeec
    md5: 77a8d9305afe7c7b7f2f0a84b681a99f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_density.res.nc
  hashes:
    binhash: ff4e4170efe71a0d92d5a0e0c91dc581
    md5: d70618ea6958dba6472b95e2fb775fcd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5440867df55236a9664edb0bacce1d9a
    md5: 88e3a5ea8ecbb91894095a1ac40fa149
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 773cbd64ae3bd2defd977673d8857611
    md5: 7fd95303ca4c4b3e1fb3b38c9f80d2b4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6ad4b039c8eee3289d1261843e380b75
    md5: 424902b23663080741642723281dc76b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8f875a4d609de11c4009115e05366bf8
    md5: 3e8ba2ac62e3d9d6a988cc7dc8ed8d64
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 75abe6f635164ca883952a923bb89354
    md5: 9de7a54406d6d93196443f65762b55f9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7db5af35b3bdfd0b33efda1fd6e2f8a9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_solo.res
  hashes:
    binhash: 1ac9c9256a0378f3042759706eba2577
    md5: 446e82cb45f4e959ea5b44b673a9ed36
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2e4f2a0d948dd9de06c45a9ab2a58513
    md5: 7b18f20c6e8f3afccf8cb77e58a6e200
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8d46ffe8e84b90ff47dfc5d9edceec55
    md5: b34ebea8a8b4b2079701d689af8702bf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_tracer.res
  hashes:
    binhash: dd581a22f7e2eab1ada2adfb8d328b0f
    md5: 5f971d4ce0386b0042a3e482c16f0f40
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b599f579d9b7b9766f0c75a480410d0d
    md5: 2187c64478c0025f4e9b74761d50bbea
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: eea28d0e539240cc4fd86bb5a5b8faf3
    md5: 8edf632a83b9b66d06ac3344f2756a93
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e4f211c2cc018ad8cc82e16422f2b6ba
    md5: e6740df815d9fad62091122b5a6a2342
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart128/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 02ca2c2908baad05b710a52f3f8f22ae
    md5: b438fb45662a61e77381c5d7c5aebc70
