format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/atmosphere/restart_dump.astart
  hashes:
    binhash: 181970d10e32f6a8017644b3ff55a443
    md5: 8fe406e2ac56877e8bdeb92249fe251c
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/atmosphere/um.res.yaml
  hashes:
    binhash: 810d5a52e32d52f4c7b826c4237fce26
    md5: 8befeeca187905b32c0f172ebd997460
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/coupler/a2i.nc
  hashes:
    binhash: b30dc7e21b995064308e1c406b9d34a3
    md5: 08e133878244bdf5f71b437f77f60d38
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/coupler/i2a.nc
  hashes:
    binhash: ff33c8e88aba9390c0137647f6f5fd67
    md5: 5f63edc02bb00e912c443ad6be7ebfd2
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/coupler/o2i.nc
  hashes:
    binhash: 35fb3c0469d720111433c3a856d66a0c
    md5: 82544a7a29dac14d3a13b7211492119e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ice/cice_in.nml
  hashes:
    binhash: 83d93f68258fe8abf0f55bad7b2fb447
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ice/ice.restart_file
  hashes:
    binhash: d88580990e9370dad8abd20abcfbc3f5
    md5: 2f3cbf6e4e7fc37072f8b3f4246004d8
work/ice/RESTART/iced.0001-01-01-00000.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ice/iced.0001-01-01-00000.nc
  hashes:
    binhash: 04303f6211d58ef0f9fdb708d2865768
    md5: 6cea935d9a4a22d139871eed20016512
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ice/mice.nc
  hashes:
    binhash: 34d641af6b6f0c67b249ddabb3517ebf
    md5: 27b3f3c108bab0ed90e44dc0450fd168
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_age.res.nc
  hashes:
    binhash: fe5d53d21283866c700b2f0381e134ed
    md5: 15640751876c8e8496a85dbaf9eaedff
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2345c4c44fd277995e63dcfed70c38dd
    md5: 4837704a0c9a43f3c2439557b707d618
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 091eb0aa9cf160836297ef8921440180
    md5: c1f53c2694225705bb01e6fa86ff6d7f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_density.res.nc
  hashes:
    binhash: d41beb85c5e3615125d1bf26b43d5195
    md5: f7ec964e9af6b7a670b8973c520a9e5e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3eae15b307f8b35a4f6d13a856f17a39
    md5: 42e0aef016dd30ebd6e9427783c31941
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c0da81a89189ea970965a51970d59ea0
    md5: 836f59d03fdd633151e69f46cc2fa00d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_neutral.res.nc
  hashes:
    binhash: df2882259d3840adcb0d039295df10d4
    md5: 9095c8b233723bc6c21afc548406d16e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c6eaa7b4979f2226a79d8487b9df8c75
    md5: f8e05e92eb9870eae246db810bdbe389
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b6e5709e8ae9c6f019a42fbfe442f967
    md5: 84fd785beab58b7633a82fa036e367f1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 00d2ad3f926f66ebad95f810609b85d7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_solo.res
  hashes:
    binhash: bafe207d567340b2c819b6b97d8347bf
    md5: 4f2e945cebd878e006a2e961bef57ff1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4aa6cdc20649bd62480ac810e583819b
    md5: 301f673e40432c52d1a34bffbdbc8a66
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7a71acb741410d80924fb43f16ab0711
    md5: 66b770f252ba046891dc8c8d5355486c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_tracer.res
  hashes:
    binhash: 78f18b186f94bdf8e0f567283bad8b66
    md5: ab4a6886313c3db41a8aa918e4c75d6f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1aacdd52c9a5f23793ecc9a633891f67
    md5: 5e28f47828e51400f90c32a0ae9c6a67
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 83b667ec5e5fc6ea0ae2834d1c2da7ca
    md5: 961ddeecbd07a700d1431cfa31493b38
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d461a9b361c7509c8f6e2f1c3577c0a0
    md5: 9ae10cd92772ce4258a47a0d61100ffb
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.02.20/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9ef9ea40261429c76b7bd4d797a73dd6
    md5: 287a6e2530327631afb6a34eaedbe520
