format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/atmosphere/restart_dump.astart
  hashes:
    binhash: bea0df0cfe1220b5aaf2ca888a150aa1
    md5: 3879e542b7ba1cf1f3eac0d25ad9db86
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/atmosphere/um.res.yaml
  hashes:
    binhash: 2f884927931c64efe341e60dfda0d8b0
    md5: 21fbaac6582f3c13891037174439e42a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/coupler/a2i.nc
  hashes:
    binhash: f8c981cbfaa987c29956f63ead29022a
    md5: bb91e6a78c5e03437706d3b53f4286dd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/coupler/i2a.nc
  hashes:
    binhash: 52ac869db77f092ca08c1268d51ac2ec
    md5: dddf578315906667fb8130ac6552a906
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/coupler/o2i.nc
  hashes:
    binhash: 0489a4f5377ddfe085fe22cf8cece5fe
    md5: 48edee25aa530d2a35a13fd107cca036
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ice/cice_in.nml
  hashes:
    binhash: a0e34446d0c13f34df3377d972bc092a
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ice/ice.restart_file
  hashes:
    binhash: d336e9e49eb836e5ce4f0c15d974e0f3
    md5: eab3b0bf638c2fb315e596fc2c6d5b5d
work/ice/RESTART/iced.2925-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ice/iced.2925-01-01-00000.nc
  hashes:
    binhash: 10ceebfc90ad5f53c053647d8065b1f9
    md5: c560ce39ca3abf1383ac4b4cb0175abd
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ice/mice.nc
  hashes:
    binhash: 679851a63a1f2f84ebeede31264c4f89
    md5: a500bea5ecab5bbfb5534870749146e4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_age.res.nc
  hashes:
    binhash: 9342e3ec35a9adb4c06e1b43158d1e32
    md5: d3dd741d5553e560c6f401c07da3a86e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0978ce618358c9476ae58488b7469122
    md5: b25ea3c59be72787cb7ef6bdd8813217
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3ca94990c0e1db6f6311fc5afde710fd
    md5: 49af5744a1b6a83696fecfe8bf363bd1
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_density.res.nc
  hashes:
    binhash: 4e9fbd22ee280539ffb3953be8b63179
    md5: 46ec5c505d13af6f86de6260ac9b9f72
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c0d3667caecd19df1896994ba2513f57
    md5: 372185382ce642ed4f679e76540289a6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3683ef45582ed25c6e3daf514c08b242
    md5: 6f573628e0ac01ff304739644a01128c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c5ad84b21336515798b4b956b5df90f7
    md5: ce9656b4934ae50e55fc2e40f91b2218
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fbeebf6de8b64cd6f85907528c4ca86c
    md5: 50de7c2145b08c2c9de69fb5adc65094
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c28b36e47b08bd764194f8c3d472ed93
    md5: 88abb30136ccebab163e1f5210025355
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7c5950da80f783ed865d2fcc6a1d90b8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_solo.res
  hashes:
    binhash: 0d46b8819da71c77427d55908b3e16ba
    md5: c4121e2d424403e400321844441f9105
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e9cf9fae023c5c0e2499899b43b86665
    md5: 5d2662e2d2172cea2929c44b6dde917d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 34a4bff6cc7488b02707a3d1b220c145
    md5: 007fbe0378762a566e8da4e12dd3ae70
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_tracer.res
  hashes:
    binhash: 438ef208af2c84f7acbdb52b9f87e38d
    md5: d9de5d18692130641b0c09fb1ef15ea7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bd1a06c0335343cf0e09489d5eaf7fad
    md5: 1dd0fdce592282babd4fb96aa166400d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 57b15f53a54fed12d85cce0559e6765e
    md5: f0f7cee2670b2509e8dc1826f01dcbb6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cd9dc571df77a0eef125c5184d278a11
    md5: 3ccccbff57d426938a1e45685e21a858
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart248/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f194fafa1af28f6a24decea4c8f9b1c9
    md5: 912604d2ed1866ac9436d985b64bf4bd
