format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/atmosphere/restart_dump.astart
  hashes:
    binhash: b75b40d0e08a1a40e4c845f391ee6649
    md5: e79ed87a5e939656ebd0d8fdb9e7f754
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/atmosphere/um.res.yaml
  hashes:
    binhash: 0d327e0c95b479eb2d9f0676fd4fd2b1
    md5: 7152c8d4085c9816522accafafda0bc4
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/coupler/a2i.nc
  hashes:
    binhash: 1e982589f3e2d1423eec6f1e6f8ab5c3
    md5: d305357a884fc0b6ef7770be7a9c92cd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/coupler/i2a.nc
  hashes:
    binhash: 33b6240558960ab7bc4442b7db2f3fe4
    md5: 121d7d8dbe6feb911313559658c5608d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/coupler/o2i.nc
  hashes:
    binhash: 6629961739af87d15a389f4cd6e20a86
    md5: 3b1a0138b458259340932f7145ca6054
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ice/cice_in.nml
  hashes:
    binhash: b83a2d988615df04933c21825cd97fd9
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ice/ice.restart_file
  hashes:
    binhash: d48c5d431ef368da56a1430c7df7df33
    md5: e232a28ed4a1e943a0bec4f4616e6fe8
work/ice/RESTART/iced.2820-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ice/iced.2820-01-01-00000.nc
  hashes:
    binhash: 7b8916077119f89f96abb1e9a8b5f8cc
    md5: 1f93e6b274ce8d76c80fbbe49abb9b96
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ice/mice.nc
  hashes:
    binhash: dc76f12b5126ec0f6433a338f0245eac
    md5: 9615e479666504aeddbf522d33c0adbb
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_age.res.nc
  hashes:
    binhash: 72d311011e473a07cb02c5f055ac7cc4
    md5: bc7ad9892f4d12af93aabdc624ce5c31
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b05e609f182753cb5e473e8ed3eb9ee0
    md5: f4b2387281bec567cfdfc84719b90411
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7285a5e6e13a59e92893a8919e7e8f9f
    md5: 3b18f6d6c6b07c75fa92af4241ad5aee
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_density.res.nc
  hashes:
    binhash: 947439fec1b2101ef5e36be793032729
    md5: 9b511aa1ca46b1b5bacbaff5877da149
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fbd8629107781baf2c40704f12a33ca2
    md5: b3dc65df4ca2e345e3e9969e73777edc
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bcc944cdc4bae87b97b3de3260dc8534
    md5: c25ba4f8e41093d94e083f74f8bbd09e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_neutral.res.nc
  hashes:
    binhash: feb9df4d5968699af6647b9f19c1f627
    md5: 704645b7b32cf92c5a2f26eed6e04fbf
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 914d918bf2c6b42a589cc79ab415bbe7
    md5: 2b102394ec7c941500fa3e74de048ac3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 84dda420dd243ee6dc4481b223bdda22
    md5: f8fa70a661108a0b66661172f9a3652b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e9c99b06f54390704bc7188e27020297
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_solo.res
  hashes:
    binhash: 2af5fa0d01ffc8e14392f247c7ea3651
    md5: 15f54771cefb2fc3ce95f7d91497f751
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5c048ffc27f83732f267d5f8fdcdacaf
    md5: d9b02304a368a75b3c9d1de13cca9364
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ee026da03615a44eb17789630077378e
    md5: 3e01427a1055b32579883cdbdaeb1b7b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_tracer.res
  hashes:
    binhash: 010ac05f6bb0b5f76daf08b508325256
    md5: 9962d1cb8c08ccbe6436ead578e9f75b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 500579f0310b8188074930cdbadaffcf
    md5: 55adae5427d3e75fc287014e6562aa81
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 624cf5612a5536f2dc2b00ca4d57ec5e
    md5: e24d682f080c2a910c9f5d2c59269c06
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2dad90c75105b9475114bea0ad51e42b
    md5: 52baaa55be77690a545a6839c0311e63
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart143/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 25900451a532ac6aaeecc2f3b2e32fd5
    md5: 0fad62ca63376ed2c2778a1918734475
