format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/atmosphere/restart_dump.astart
  hashes:
    binhash: 21a931d2c4dd9485aa15a21d73eb519f
    md5: 6e21ce49b57c60e82476e5e4c655720f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/atmosphere/um.res.yaml
  hashes:
    binhash: 4d40adca755bc40772285d45bfc37bc2
    md5: ca91d891abb323edae32aece0d95f977
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/coupler/a2i.nc
  hashes:
    binhash: 0ff5530664bd090adbf4ff6357b4b05a
    md5: 98e5ba47af6f777d56807559b514083c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/coupler/i2a.nc
  hashes:
    binhash: d76009f7556a9edb4037b077f052e6c2
    md5: ab2ca12915ea46de520550968ddf672b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/coupler/o2i.nc
  hashes:
    binhash: 3955c45f18082949ffe1153652c5aafc
    md5: 9ec56399bf488e1364b047612392b929
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ice/cice_in.nml
  hashes:
    binhash: fed19775875c151d1d247b4b979a4ce1
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ice/ice.restart_file
  hashes:
    binhash: a5ccdaee787774a10adab1c47cdf3c0c
    md5: 9687b2c513c1c00a2a4b0da8a1f3f833
work/ice/RESTART/iced.2884-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ice/iced.2884-01-01-00000.nc
  hashes:
    binhash: 069cc56b9a9415a5824c2a567ab89c13
    md5: beff57c26ce16bd6a1c0764b4020a9a8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ice/mice.nc
  hashes:
    binhash: 02b25322eb59bebd6604e6e54e432ba6
    md5: ce5b9fff59744546a5a267230d83a0c2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_age.res.nc
  hashes:
    binhash: 1a66756aa15e905ccd7350c25213bdb0
    md5: f8d1d46aab8ff3698921e3943af711a4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 04ec81eaaf2c4762db822529b16f26fb
    md5: d2ba3ab5f4077936b5b108dc2369861b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c72264f6967789a7bb252607b154ed6f
    md5: 9067c015d154d0e7c4ae73a081bd7e51
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_density.res.nc
  hashes:
    binhash: 640a7b6cfa18efaecf20e9e45090c6f5
    md5: 16dd8dbe11553c8fc561dab77abab85d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b66e86b78799bc59c719b1e5c66dd5ec
    md5: ccc2c64a737830b4f2600a45e2a34f9f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a5d231d4b521bd34665e39bc5c6f1e48
    md5: fc46077202edde34fa80ce458d552397
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7257bae8f469c2e30ae8946339e66e44
    md5: a2a99997ba2ae891838ddcae2695cb42
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 398a90d7b9a208a6c6cd0ac673e76c36
    md5: 6c1d043e162ced646a27cc3b8c9bfec6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4994ec9ddbe2bb666fe74d424dea0ed5
    md5: 113232ab6aa35e97c2b997ab4538bd98
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 044b9d884c3b90a6a579352f77e07923
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_solo.res
  hashes:
    binhash: c7fd191e9765a7c9a28377c32e3fb735
    md5: e4d193665574b20494f6ec13013230c1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cad385a0ea1ba1b1d61df869e65d7f09
    md5: d764bd05798dd08e769d84ff4e7c5d15
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a91a2da60c1efc9a7a46b015ecad1dcf
    md5: ca32d87963bce04e5ab379d563b0887a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_tracer.res
  hashes:
    binhash: d50b91a2101642e82bb9963b82c3712d
    md5: 0a0f41129bf2cd236384d9d516aeb40c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 90ee3751471f525d533e59ce152e4171
    md5: d8fc5ca1b4055bdd1cf25ae7f345e396
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4ad92771bb840ad9ea160a85bbe9844c
    md5: 97d69e2f5baec274d67067f55c674aca
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6ecedf0d599637d8ca345fcb9399bd83
    md5: 900be456b1083b55fe5889b753a9586f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart207/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4747b6d5711c1d3d49d2bcaf2d2f1cff
    md5: 708f4f876683303e0515728579daa8e5
