format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/atmosphere/restart_dump.astart
  hashes:
    binhash: 2ed92514adb09970bcbdb390d43802e8
    md5: e1ac3cceb22869bc319cfd65669e14d1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/atmosphere/um.res.yaml
  hashes:
    binhash: 71f2668fc4daead7f3b3445faa823844
    md5: 4065b79be54201963b50de391a9377ca
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/coupler/a2i.nc
  hashes:
    binhash: e683ae2eb42bebb46b7722b9ac4cd26c
    md5: ecb71f113381ad7939e0180118c97e84
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/coupler/i2a.nc
  hashes:
    binhash: e646ccf71ac0a4d3e711f78f6c94ccd3
    md5: ee5f2817d170d7430bd4fabd4ea08039
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/coupler/o2i.nc
  hashes:
    binhash: 47981fbe7805e6c965ccaf859fc89c82
    md5: d050581a77a62732a36b5d51fcd2a561
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ice/cice_in.nml
  hashes:
    binhash: 235e6e4e979bef1c9c9757e5e7d93fb5
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ice/ice.restart_file
  hashes:
    binhash: 63aaa6523bd87bed468654e0baa44b31
    md5: eaba677f7c5a5971248882ec673550aa
work/ice/RESTART/iced.2862-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ice/iced.2862-01-01-00000.nc
  hashes:
    binhash: b40fe80f4e8bb84812e48ae3ffa84194
    md5: 415c9eec5c0f9b6a9b89299e6f226b84
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ice/mice.nc
  hashes:
    binhash: 39baf051dcb87014ca4948e5e93b84da
    md5: 1aa6962a3809e1d6bf4ccbc2cb741b4b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_age.res.nc
  hashes:
    binhash: 0cb348047c6b7dba8949c035e8431fba
    md5: 4bd78e41278234c8e09db49c81491f41
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 71252ea560eafd872c6d3e821b7d0227
    md5: c9082f3fbd5f5533afa27bd699d50890
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 42e6182d6f0fafceb3d609bfe0ca574e
    md5: 47fa9aff4f8350de1183519508967b1b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_density.res.nc
  hashes:
    binhash: 0aeaee094fc68dfbe70f15d0a0f4b4e3
    md5: d4deb68573945848f21f63bb0f8c14b6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d4b42a52ba8c759f9a6be9389de82559
    md5: 8fccebfb56427da015bb3a1a7c43820c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c60c28c0889e2e9e219b099c8c9f7101
    md5: a8c9cd923cca17cd3448b7c6de557f0e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 36239e733b3b2e6930e6b3d99ffbb948
    md5: d9aef190a2bbb79a753fd14db15018cf
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3f42090fcdc66720146c20f84414454b
    md5: 8ee81575adfd5e28860e3cf72bb93903
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 40af86ec6536b8d06935c4094f49c41e
    md5: 4c7f20e75dea99ea14998fd624159c2f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: aee3311e8328600f84a873a40a1ce855
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_solo.res
  hashes:
    binhash: 4727be2a4c5cb3dacbca6709801381a8
    md5: a66d28318098c18f7d34c67663e2d22d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a8b4f31eca361a8c9f0320e3a92ce061
    md5: e59ebdf1fd5dcc454ab1e1700554d482
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5582b6b46e2323de26926e28d2b28813
    md5: 329cd451e5eb2094e4fc96c8b5530146
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_tracer.res
  hashes:
    binhash: b8bf0b6cf921c0a384732a3364654448
    md5: efd5bf380fad852a9596d8eeaa41bc47
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5b033847c73ed444813aa018afcaf837
    md5: c21ca85a92ccd552fbad81f883db1eb9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 631f354607900986fe7299df72cccc74
    md5: 1fee816ebebca558ea7ab443c78ffa67
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a2fdcca2cf1e929a4b88a80afa0f3a95
    md5: 710dba490bd9dcfe6f335025f9f48f01
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart185/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a26139693e4fbe12cfb60716d12d5702
    md5: 1dc3d6683c72493676e13fe949285cac
