format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/atmosphere/restart_dump.astart
  hashes:
    binhash: e71e012a80f2dd4851f7f9d489066f50
    md5: 6c91330efec91a845ab135bd94511b91
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/atmosphere/um.res.yaml
  hashes:
    binhash: c3d0e5e3866c4ef68bd25f916d864ca1
    md5: 8dfafd097aa768382ba48558bc43ab0b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/coupler/a2i.nc
  hashes:
    binhash: e773f2108765f21d7ad1d5d87a0f8b24
    md5: e04989a6028fcf9e9ac1b3b020740de6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/coupler/i2a.nc
  hashes:
    binhash: 4e2feba984f04c97b5d07d230bd6184d
    md5: 9bbc72adc4a3da8a60a5c5c7e1085e3c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/coupler/o2i.nc
  hashes:
    binhash: 62c8bb586a32ec8a7cff4d270cc1463c
    md5: f65048688a4ce13f77d9c02ca980e870
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ice/cice_in.nml
  hashes:
    binhash: ca7146846a1f70500e6a0c869acca7e2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ice/ice.restart_file
  hashes:
    binhash: 410c581865021a0c0ec6dc7e0e0eddcf
    md5: 67c7c01e8ce4674f0a9e6399d6405010
work/ice/RESTART/iced.2768-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ice/iced.2768-01-01-00000.nc
  hashes:
    binhash: 74a7855ec2084d4a172792a24df52206
    md5: c86047feab9ac050c18edadc5f2ad70f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ice/mice.nc
  hashes:
    binhash: fb6032a8eda59b5ef6f4b499a8b431bd
    md5: cf1d4bf2e5e60badabc9fc2726868744
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_age.res.nc
  hashes:
    binhash: aae0c3d37545a4d5782cceca685b4e58
    md5: d0243fe717a03c5dfab9717aa2705d29
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8991ef65bead438d3b948e10f9634411
    md5: 5339ade33003f14155e54d184c9d7060
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5f37297ce21718d939bc0c91e95ac8cf
    md5: 6da509a993aa284656569d561d741475
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_density.res.nc
  hashes:
    binhash: 96057bda131f18886b7ac28643a518b5
    md5: cd3b1c0162b3cddc29eb485d30644da1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_frazil.res.nc
  hashes:
    binhash: bdcfd48fb48bbd4fb911776789a16328
    md5: e5d1c9a5c998882c181822afa5b3fa8c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 658e0981df36c89faf77c0cbb2ee49c1
    md5: 6f1921fac064879351286e3e454f4abf
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 83e5a6190088d187df6b076bc8eb225a
    md5: b0f99fb48a489eb96b70b0633b226af7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: db7c30fbd14ababe057fde3440eb1ed5
    md5: 4ca9f641029b5242a0e38d5f871b5531
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3b87e5b4a5af74c290fc984db917cb46
    md5: 7ef00343d715acf6f6c6e0e1f0589c57
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a7139a8aaf7c0f17e61a3983ae68503b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_solo.res
  hashes:
    binhash: 32aaab170d9816f1c1eb5c20b85252f0
    md5: 3d7bb906b6c744059c1a092f94d8740c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6d941f8f2ac722ebf44968f79f0807e9
    md5: 5cea179ac74b8c0e8813ca269ed73525
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b2a79bc6863e7e701b39ba649903293f
    md5: 95e2d494f9711aee7343957c9285a87d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_tracer.res
  hashes:
    binhash: 32b3e29026b8975235f91242f6166622
    md5: 3d91a17d05479f0adcf96c6a3d176bd8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 09da4943c7835de6bbf2b7ec4d197bdd
    md5: 1c0b7f00a4f39c61ed42adf57c32cf3b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cb3c3edc2b1a5b68aced485e2ee21906
    md5: a40ff7ab50894b1987fb658b3d41b0ca
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 690c99faa41f65ea294c08119bbee382
    md5: 659c11774512b8159508925ebbf76de2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart091/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: df21481aa5dd87cfb77b616030c64bff
    md5: 764747698f16e95e258b67899fb279e3
