format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/atmosphere/restart_dump.astart
  hashes:
    binhash: a83397c68f277ee9eb3ddb26f4a2914b
    md5: d8cbb235d60a833e77983302871085cb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/atmosphere/um.res.yaml
  hashes:
    binhash: 81307f7acc05b735cdbcaeef7ec0e038
    md5: c09e5aae908e5fc02b657a9d5cc2911a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/coupler/a2i.nc
  hashes:
    binhash: 2313cde2c9ee2b4377e8e8e0a008a78d
    md5: a04417b5b42882efddd6a0ba940f7409
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/coupler/i2a.nc
  hashes:
    binhash: 21d091dead3a8fb4669bcb1b0dd2a90f
    md5: 89c0638c6d8b5e0bfbfa1996a04699ac
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/coupler/o2i.nc
  hashes:
    binhash: bb2bef5c69ddaddecf9e17c452339ff5
    md5: f8ea1585b8be9dfa8b674f8e031d2b23
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ice/cice_in.nml
  hashes:
    binhash: b1d7533b92d95a4edec73a1683af8d9c
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ice/ice.restart_file
  hashes:
    binhash: 711484687c77756f32e18b4bf273894a
    md5: 41bee80238e2133a59bdb83766bb7d12
work/ice/RESTART/iced.2926-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ice/iced.2926-01-01-00000.nc
  hashes:
    binhash: 5dd1c083f15292aa480d72bbd7c32f7d
    md5: 5190efb51738e823c423d1739cbdfbf0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ice/mice.nc
  hashes:
    binhash: bc0f8951adf3143454bf53072bb858b0
    md5: 07482e9fac336db6161c9c2982c20703
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_age.res.nc
  hashes:
    binhash: f1fd1bbcc9ae456afb25a3d3f6acbe23
    md5: 0b533761af53c98065bba7e6361ff2fa
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 28ebe4495deb9885352310b68c84f8ef
    md5: 0329407b865b97cd1f906caa9f397fc4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 05a9336398baf80c36430c09dde8abad
    md5: 8b85c0af40b13c688c7f1a4b7c6183ac
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_density.res.nc
  hashes:
    binhash: f9c3e69d97dc05c91a3d06279d56b5ab
    md5: 1a6ff100716aa8642a63c520dd024e74
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0709faaea29a2aeea5013caf7e8f0b48
    md5: 35c61faaaa382ecca7ae4c438e6223d1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d48fa4316fb9ff2cd16b7ebc09bd95f2
    md5: 19c3ca5c3a156556cbe2f8072721f9c6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7d21092c4bd2ea27a491f945eac7764c
    md5: ebf552e3fc45c500f129339c941a9a86
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 00265cdad2c09b6094c23e4784937f16
    md5: 1d43ee8980cb4728dd7b9afb57b03e5d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5e0e2ec22406c4240d8fcbcb75dddf4a
    md5: b553ff4ad6dbbaaa05671154f2207db3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 416a60f9f836eaa4dfbd8bdc2c9ac992
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_solo.res
  hashes:
    binhash: 4a67a578a10347d7ba35ad0a9e94b00b
    md5: d67a898e9a31684ff614fd7194911d7c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a3433bb8e7755c3b0b263d2f57126a74
    md5: 81c21defd0ca13f02ab3bf35bc2bcc86
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 86453c99de5e00dcf2abd78394389e0e
    md5: 4a8a768aacd3dcf038a1f8ef097c16b1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_tracer.res
  hashes:
    binhash: 0660fc85ca45c035a2c5f0360a4f21f4
    md5: e35ff46a830bbd606b9b324e81e7b461
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e44d331916f778fa2648b28879b55bd9
    md5: f5513b103bea3ec0821f9a6eddf6ca2e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ee485ab49696ffe46266372e3db49ab1
    md5: 54f4b99d8c9e715399bb04821d47cdab
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 783e6c593ad06b69f8315dc302f34dea
    md5: 142c471b6e82e3f263e9cd82781252c0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart249/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5f1973e8092fb1da223d44443d8f29e5
    md5: 8096e595937ff225964e018dee905d02
