format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/atmosphere/restart_dump.astart
  hashes:
    binhash: a193fb92407cd0bdba191581e2f1897c
    md5: 4e4f9a4273d88d4d8cbc697e9e879ddc
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/atmosphere/um.res.yaml
  hashes:
    binhash: 817379a674a5493441bbbc4af7c0c1c3
    md5: 0a2a46bf130f7f5b9fa8403a78852db5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/coupler/a2i.nc
  hashes:
    binhash: b412b74e8a93be55c0ea950b3d179e70
    md5: 5cee594ccff277d104bc4ebd1efcf007
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/coupler/i2a.nc
  hashes:
    binhash: 46b0a9cfa3195faa1c6597ee30a7446a
    md5: aa40058f78dfd06fd993aa66d5df363b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/coupler/o2i.nc
  hashes:
    binhash: 9814cde1cc006a276e8b059c2f8aa65a
    md5: 8a358e27e033496cb20e7456d4599aa2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ice/cice_in.nml
  hashes:
    binhash: d34cdd354e28dce67173691e8eeaaaaf
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ice/ice.restart_file
  hashes:
    binhash: 4c57b582b6087da4d829d28eacaa0e0c
    md5: af3530b637b893a405b501cec5eb2dff
work/ice/RESTART/iced.2683-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ice/iced.2683-01-01-00000.nc
  hashes:
    binhash: f6be61c3b6fcb8be2a597407629a4e9c
    md5: 6621a45f0ee7c5d1a53214b0979bbb0b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ice/mice.nc
  hashes:
    binhash: 6dd499599ab09cce582f8c63448e10a5
    md5: fae19e713001e1f6883bf8e2e074e2a3
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_age.res.nc
  hashes:
    binhash: 5c51c2dab839d52f2f1ada0f290f3ddf
    md5: a2e1647108bfb91131face912b0d3a51
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3d07bf3a3a849847d423a6fa7e1d7e68
    md5: e1f2a5f773074d652fbd8c6ad4c1434f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 590cf017853848148f93b67c4cb5916b
    md5: 1993d457bfd1f2094b77d02936d105d3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_density.res.nc
  hashes:
    binhash: 0d002720b4c8250218c3eabf0e15d742
    md5: 9e044c747d16dd8dd9af11b5a2bc604a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6a253120de76725e8cee8badb8a447b1
    md5: 883475198637b1a9c09785afa73b1e77
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bc996786bcb85a1761800a18ff484443
    md5: aea471f745d41039afe524eeecbddf23
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c75872082983ed1897533eca371de645
    md5: ec6de8d542a3d397feb9308810e8e928
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 118174f738995526249cf1c4ef71eabd
    md5: 03abea26490a3b3801d5661fe5be1f8d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0dbef79406dc71fb9f62a644c69c63ef
    md5: ffcdfe967ef66c1dd712f73c8962fd59
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2f33f6778deb4742859a550e148ab3b8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_solo.res
  hashes:
    binhash: 86b04aac7f98c4e2abe5ea04ec1adac0
    md5: a287a9f5b9cb01d54acf381c3b2caa66
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5b11482381320ca29fa9711ed6d85000
    md5: 74d21057b8c6fcd1859e5356ec041617
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 19a5e190b0dee0aaefa6295977bbfec1
    md5: 6bac37a0b9998e9f33c747ded982ec49
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_tracer.res
  hashes:
    binhash: a3d618142977c33cdec79dbb16cdf44d
    md5: 4bd9f76a63dc40f1623cdca5acd3a2f2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f9d66414091e6f1460fff2174959310d
    md5: bd1562aa22aea2c7f1721ee6e9b3df95
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e84d149638f7a1de18e1ed4b5031e9e3
    md5: eb713632fe6076dcc5ab6bbbedf6ae51
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6b98bd5ccfd648bafd8d53013e850282
    md5: a8014db3896845c1ce2ddf7a81546e18
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart006/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0dc0562b3e684f83907101fa7aaf589e
    md5: d4cc3eff9a4ecbd6cecc3eb431a7b80d
