format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/atmosphere/restart_dump.astart
  hashes:
    binhash: 6e6fc528e87bc26ad240d05c96a17ed7
    md5: 048ba8fe5554b3c9d8a184bc3cd81e1f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/atmosphere/um.res.yaml
  hashes:
    binhash: 7cbb25964b6edf4eade71c89497b0d13
    md5: 78a15e0cc2ac844b576ad15b252b681b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/coupler/a2i.nc
  hashes:
    binhash: d8173912edd456374fb80a3d717e9d6d
    md5: bd3192f1c70252ab96f0187da2f5b0c6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/coupler/i2a.nc
  hashes:
    binhash: 5963ca556507f89ea5beb371a27ea838
    md5: 9769779869623d2704d9549891e84f7a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/coupler/o2i.nc
  hashes:
    binhash: 5b03001da0dbaf3934266a8ee40c80d8
    md5: c48800a9a83ffd36cc3538d8bb4b2f63
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ice/cice_in.nml
  hashes:
    binhash: 0cc102e8fcfb9ed400027dfcf385822f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ice/ice.restart_file
  hashes:
    binhash: 5b5ddcf5c055d3cc2582196dd1f7c799
    md5: a04cc5ae2f45ffa4f49317158603ae5f
work/ice/RESTART/iced.2941-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ice/iced.2941-01-01-00000.nc
  hashes:
    binhash: 64c0f3e3712f62899b81cedd75015b82
    md5: 7318f1f5d386234531593787a9dd5f27
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ice/mice.nc
  hashes:
    binhash: 742aadb2a7ebb1505c0f85bd26969e4f
    md5: 906debfbd2280d265a63ec9c5e22148e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_age.res.nc
  hashes:
    binhash: a38b047589be3cd5a8b6de00b65413dd
    md5: cfc7d47338b0ceb0f9962e964bb2d287
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cfb15f7a9624d44090a5d2cf984968aa
    md5: 2daa41adbcf38427ec7084ba7c2e7510
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 65219696fb52901503c6e79b7217332b
    md5: 57f31649cd4b5f63920bed80e36bb136
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_density.res.nc
  hashes:
    binhash: 6f421f198acf6d9b660981dd48665d14
    md5: d148c02ba1bae3467b548639d74eb01c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9db21645988665a5183c41b9b6ea618e
    md5: 789cc6684e946908020a869f0377ef40
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 463e12f946236a437440f14bdd86ccd7
    md5: cfa69ec89039b6e3a7c71ba9d7cfa572
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 77d664a8d61aa13cfde656c53fb4e99f
    md5: ba6a0cb550d18bdb2f50d0f14467abda
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5ce835eb9d88d40e183eee2c680abce5
    md5: 85f06b9e11d808f50d9aa43ee303d7c9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 202810296b499f3b94fb8ac78f47c779
    md5: 6e3d3cd717af8460280649e65c31f156
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: bca75f89aa94d06b28a15090007f058f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_solo.res
  hashes:
    binhash: 7004f86a3ec484a16cb7e9d4b01a0a32
    md5: 08696f6e2e51b777a0c20a17533200bb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: daebcc2bd6cebd25dc4b7b2b0a5527dc
    md5: 16adf027bace2c436d64517d5002f5ad
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2dc5270e2a26356acdb4f4a7d93d984a
    md5: 9d820774d147ebb447811389e80bd311
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_tracer.res
  hashes:
    binhash: c7ece649900a3db5b759600eb0030733
    md5: 2a0d983e6a35cae6d42284479da95369
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2757395ad81f1fc1b55347ca732054bb
    md5: d6ec34c2f6cb4e04e2c8e49858479253
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fc3bb91694b9567cafae47c0978f2857
    md5: 46b023afce5e4c65f3e97146552b1c6e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a154b9912ed0f72d3914c64dbbfeebd5
    md5: e71a40d98a9a411f4dbad5fbc7643d69
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart264/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ba8775874e373a4a890783608558d428
    md5: 22ffc8537c28a955112870decd975a1a
