format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/atmosphere/restart_dump.astart
  hashes:
    binhash: e5dea2b8f82329d3f9e74ebe5f2d5936
    md5: 06aa61c13f391a5255c1645576617fb4
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/atmosphere/um.res.yaml
  hashes:
    binhash: 85afabfa92c5ebc4e59409c99626359e
    md5: b56f91fe64e79d38bf89ff9723b059c3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/coupler/a2i.nc
  hashes:
    binhash: ac4f8c05b5a00d3c346f5e326a4b0328
    md5: 76764241d18532cb7a64ced9803f0153
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/coupler/i2a.nc
  hashes:
    binhash: ea66697bf09ca3ec76facac1b61df035
    md5: e2830d407e1897161935891a4b6194a6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/coupler/o2i.nc
  hashes:
    binhash: cfa61356c9fe71ff9412e24c352bb5c3
    md5: 3c91a1cbf54dc86d056aac99c6c075ce
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ice/cice_in.nml
  hashes:
    binhash: 90f275eeb7560fc66265b9c1f5baa8f5
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ice/ice.restart_file
  hashes:
    binhash: 80d4c117509439cb88764d8bfb8f2468
    md5: 87fcc7415310e61d5912cbfa5813c491
work/ice/RESTART/iced.2772-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ice/iced.2772-01-01-00000.nc
  hashes:
    binhash: 0b50bd3c5f19d1ce59dfd0bd13bdde63
    md5: d5a76fee659d5fb7ff5f56d82db46b4a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ice/mice.nc
  hashes:
    binhash: bca160778e81ca66d8372dc7d3a86921
    md5: b4dec3d6b7de4b7e57dc7a550f21b01f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_age.res.nc
  hashes:
    binhash: 48f6f0ee0620372a656a1286e598349f
    md5: 1525114bf93f9ea5d63f3155d1f0cb59
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b056de337ed271ec048e8f69855ad217
    md5: c8aeaa3cc4a3a3f54d47d9ae4dd3a61d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3b0b9c154f30f3817c2b30d1c75d3363
    md5: 5963361ddfc9b7773f0c5b47283b9c6f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_density.res.nc
  hashes:
    binhash: ecd214a2a43f82a73c71c6d20dd79595
    md5: 165a6e1fe9b641f46116521e02f94a0f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6da405753a90e6d49fc847eae6a8e632
    md5: b0660b041dd50d6505bdf9474a4c7b64
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 444e4bd34cd15db1ad066c0dd25b9905
    md5: dc5cbb9b8f44656be72750eb954f621b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1b2568d871d18d235303959fd95d8917
    md5: 4c599913f05c4c12e21fab4fdd37cd3f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 00bc270938164ad1a9d814cbef95a6fb
    md5: 3ea2c804170845eea3922171daf16c20
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_sbc.res.nc
  hashes:
    binhash: daa9a74def519d682ceac84d7faa3aef
    md5: f603004506a10be6ac06691dfbe42bbc
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d6abae32c6710b9e8d064f76bb8fb981
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_solo.res
  hashes:
    binhash: 09c309cd1f86d0b6969a999272ba5e5d
    md5: e15f625749c35e43e7bcc4eaa1629ca8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: da648212b3d0ac11ce2db0021cb717e7
    md5: 9fb0911b3457bf7ed05c6f5ac37ea372
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4f31c98ddc530d0bf2985b0f3f56389b
    md5: 52e53b3ed7ae2d2e10ce4a2f2eab0a92
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_tracer.res
  hashes:
    binhash: 365a4ac25739847f3375be9ab7a7ef58
    md5: 3c2a13887c1f13011ec933da352261c4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bc66a341c232a1d6df0a0b3ff3e0f232
    md5: 2e97733c7e8c1af334f092899fe902ec
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c9fc5cab5f508fa09385b4f065ea5beb
    md5: 3b29d0d2339adc9d998e25dd028dac80
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cf89f575035c6ec59ca130bf068416d8
    md5: 60a4487d5a5804ccda48a87c6a0e1e46
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart095/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ec9e44f2780b0893f9908d2304f72060
    md5: 59812808b661f10189c6e7dafd90c3bc
