format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/atmosphere/restart_dump.astart
  hashes:
    binhash: 41b3bb780eaa78f24032ba46fd26344e
    md5: b2c984c7a47e39f59f93920bced7fdf9
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/atmosphere/um.res.yaml
  hashes:
    binhash: 1f72193111f59c431bde63fa0347f48d
    md5: 05dd7d718334e8e42d92295fb08c5ffc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/coupler/a2i.nc
  hashes:
    binhash: 5796dea349ad269249a9e08df41c5b3c
    md5: 4cb2c94c2b95b45e91cb1ff5a31f3ade
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/coupler/i2a.nc
  hashes:
    binhash: cdf03901995f66f957dbe4a13053c292
    md5: d75af6366e4c6891c4f8ef8aa63006a2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/coupler/o2i.nc
  hashes:
    binhash: 0b0bb9a5bad7a9935946cd9e7a7b2ddb
    md5: 1c6c37f72a6b959351cd863a2076177b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ice/cice_in.nml
  hashes:
    binhash: e8dde8c7d9f7cac63497065938426d19
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ice/ice.restart_file
  hashes:
    binhash: a2d46255195dff0d3117cce32655a234
    md5: 40acf98d3d7e98ea8a60e1dfd5640374
work/ice/RESTART/iced.2871-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ice/iced.2871-01-01-00000.nc
  hashes:
    binhash: f3936326d29994a37f5df80494616360
    md5: 49c355418254b7f2618f4bf07a5cb2eb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ice/mice.nc
  hashes:
    binhash: 96657cfdd16cf904358ae4773885d7c3
    md5: 559be3835b521fd7f9d715634c00eb4f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_age.res.nc
  hashes:
    binhash: a62a186f98aadfa2570a0c4672ec01f3
    md5: 6c4a347b2f00e41f149aff847cd83160
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7e4294a51fdfed6e313a29e843443341
    md5: 05651512c762c0b649f1bb3b3696258c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6a7c4417fd980cad3fb68398eeb68e8b
    md5: 133cb9a66c0d4479d15c03005173fe7f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_density.res.nc
  hashes:
    binhash: 2556977687b9aaa4da8b08f69dead96a
    md5: 2ee38b49336af06f0ed136afd8aaaa3c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 840d58245d209972704143900d28be05
    md5: 647ee062fe7131b066e081118deb92d8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 47ad9e677da0d018f97fef891571c16a
    md5: 916f1d9b3bb504db8099b94c4104724a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4143c919fb138cda229d72b865302a0e
    md5: a83dd9ac1e0f1269a5a545108bfd2440
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 240033966a228fa99610ad9157a1c509
    md5: 5880733d12719e81277f0423107d61f2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 99e9f621fe15d528d510696f0038a5ce
    md5: 2e001db47faeae96c6684e9df3c9b2e5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d436f02331ea02d89c0cbd6c4377ed99
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_solo.res
  hashes:
    binhash: ac07170bddb870e099005c0ca9b05748
    md5: e27c0264e2280c4ccf22ebf06aa9c385
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d2c02af2c73e2d08396cc659fbc8eff0
    md5: 22b0aa28ddee982a7d4269d9473906b2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1c54f4805ea6bc5b4f295d738e1b4836
    md5: 8e38805648f4cc9042a9d253c7caaaa8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_tracer.res
  hashes:
    binhash: a5e3db828abc14595e35b102ee6c3b58
    md5: 56f499e361e618d4e3ad074bc357b8f3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a5869c0737960ee8572b7f822c1d32e7
    md5: 9bbed2c4f39a94d076bf7b150a003226
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c28e02f90209d5acd78f65db481a3b70
    md5: 822cf26de58ce1483bf880f8d417b5d9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e722c889ef08daa0641a6b7916e0430e
    md5: 60ad583b2078492d2f10110342fbaa90
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart194/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c97c80ccf59ed943679eeffd973c6409
    md5: 9fb2bfc9cee719e4f9f706acc5b87ede
