format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/atmosphere/restart_dump.astart
  hashes:
    binhash: db8ef8b2ad8420ccc401b0463ebe69d3
    md5: a491bc30a57ab175b703a4a8d6ad9e10
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/atmosphere/um.res.yaml
  hashes:
    binhash: 6969251d9f01d5ac7d384ca39a713196
    md5: 5c860dcb889428821fecffdcaa5d06a1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/coupler/a2i.nc
  hashes:
    binhash: d197b7d423e105d16738537c0d8faa26
    md5: afac7a22d0266fb818be4a96e67c7b3c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/coupler/i2a.nc
  hashes:
    binhash: df0645df3ee358576891e6b353f2ba7e
    md5: e1c270897c1c90a095b96402d1f0112c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/coupler/o2i.nc
  hashes:
    binhash: 9366a55d34498d3008c118284cea0e41
    md5: c1575e5fdb38303660e8410fa60d4d78
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ice/cice_in.nml
  hashes:
    binhash: ac280a9407f1722fbd2902965421c984
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ice/ice.restart_file
  hashes:
    binhash: 0baf07e37cd02d8a2fda887c25e34ab6
    md5: 7970c24ae0b337416bfa545377e303a2
work/ice/RESTART/iced.2886-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ice/iced.2886-01-01-00000.nc
  hashes:
    binhash: 63f26c34274b9c9d117a8ca0c2c9eb09
    md5: 06804b3998c070330dde30fd0019cb16
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ice/mice.nc
  hashes:
    binhash: b4ba7686803a8bc48f7e192ffb97460a
    md5: 07602a83d185b038715de0dfbc49b3be
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_age.res.nc
  hashes:
    binhash: 9aa321314f7a2ecc53cb0f966fad4f1f
    md5: f4939460629612df04c4357cf54651da
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 139e02a96a45b6919cd13cb0b2dbe660
    md5: 27e31e0aa46aff1078b344e7ee4390aa
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: dc783de136ea398c1092e01c03729c23
    md5: dc72be9c3cdd83e7352810526573ada7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_density.res.nc
  hashes:
    binhash: 606fa065c0f25fbbcfaf60a394766a48
    md5: fb49ecb7b40d39d6ec5b44cdfedbad5a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 373a8d3c26069990774509ea5dca08e7
    md5: fe955470965bbed09051f81fdd04efb6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bbb4fcf2a5ca83c874b0dcde4408eebe
    md5: 2f97c5dba41bb85b52f052a29a7d1217
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 13ef383c2362f31afc017cae0642c6f5
    md5: f1808555b78553acbf9c87193b21fe64
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1379c2949b3ae53c5273b3cc78373862
    md5: 1abd7b7a1096bad59577bb04099fa449
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_sbc.res.nc
  hashes:
    binhash: fc1aa31b7b0d3da625834702adbe90ad
    md5: 40ca17dd25c9722bd60085aa6078c36a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0241d4e5aa140bdf4d560e1984e574a8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_solo.res
  hashes:
    binhash: eb3d358d75453d1f268410398854a387
    md5: 04b9a8d556049b7ee2800874e36e3f26
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4252a82645b69de78a3bf6c4cf093575
    md5: 150a82daae7f5b21617f1c14511ef20b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_thickness.res.nc
  hashes:
    binhash: fb84ee09d741f406d3b9cde506334ac7
    md5: 1af9a322c081185141c4c8f04ed8fee0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_tracer.res
  hashes:
    binhash: 0d373898f4480adda0d1cb506d47993a
    md5: bcd0302786d7b051cacb48c749167093
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 88a36f4c09cbc17acecf894cccd05715
    md5: a22f829546a2aa5262075824cc53c420
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e11f6aa69a186206f656ba3d70559cc5
    md5: 1b1cd0de6ea75155a641fc70a8dfdff9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f5364168ad514364c066824e0f372d7f
    md5: 1c42fbff0245a44d71fb2ec97514d417
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart209/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4fa31b1c81825bf7008e9f21685cbdd3
    md5: 2fae36756a9a1e900af7d2d10724011d
