format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/atmosphere/restart_dump.astart
  hashes:
    binhash: 6759ceec7b33ec76022611cefb7298f6
    md5: 25c1bd10fc3a8ea553d32e658bfef1ff
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/atmosphere/um.res.yaml
  hashes:
    binhash: 33487ba39d87ae684557642d0baa5c27
    md5: d1448fe5e2cd49935cf446132cca1ba3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/coupler/a2i.nc
  hashes:
    binhash: 3bfdd4ca4fab5685ae90d6a066cff073
    md5: 0fc9ef96a92bf8af9bebd1d61d092214
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/coupler/i2a.nc
  hashes:
    binhash: cc73837268f00404599ec62711f16491
    md5: 2534c2b0a72ccecf0a17b30750c951ba
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/coupler/o2i.nc
  hashes:
    binhash: 66a83f5ee7db363e9d77fc9a27f14ce9
    md5: f24b2db4077eb330edd09d7bdde2daea
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ice/cice_in.nml
  hashes:
    binhash: ba43f37eb003bd4e82ae96fde30c791e
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ice/ice.restart_file
  hashes:
    binhash: e065a5b1cf07d6f0f31a9192393cba25
    md5: daeaaa39a63b7905cc232759b03a0eb0
work/ice/RESTART/iced.2930-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ice/iced.2930-01-01-00000.nc
  hashes:
    binhash: 796bca1c6e4b033d3a6adbc3ff4282df
    md5: 09c90bfbc5608e927e3a7c9398c951cc
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ice/mice.nc
  hashes:
    binhash: 83fc7b932049e58957900350beba43c5
    md5: 8b44b184d9a171f37ae87acb839d3382
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_age.res.nc
  hashes:
    binhash: 6305a84346d7edde07701a4de6bc8f42
    md5: 89a968f68eaddca973915c2553714a03
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e6354733ddc19b6aacdabdeb5ad3f3ad
    md5: 4c66b9e61128a4fe5d177981f2b974d1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 992bae99241711eac81554add7a7edc6
    md5: 88d540047abddd0a68a490067fe5ebf3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_density.res.nc
  hashes:
    binhash: acec640bce0619628c2e7904000b95d7
    md5: e11b90a3a26e79f6edde99492d82b3af
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6b8405bc842f6c65c7d848e20136ed80
    md5: 85342e393dbb6475ff5cca227c572e6c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3573df2584e76b88d9a5764058b5aa4f
    md5: 0a72ec8779ff4052c63cbcb8a8dcc211
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 57dc9472bc48af33f1716f766b96e463
    md5: 9d943943e66542db4fbff78a504e2fe7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 49bfdaf4cc52b9aa80a66750710b70eb
    md5: 8ac98f8514136ffe5e550d1eb9e64af2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 78d7c74c8428645d13e595832011bca7
    md5: 415c5cc711b53397a266794fde56c053
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3f3819b970b6c60ce45868cf4dc2b651
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_solo.res
  hashes:
    binhash: 9f1d0133f3dcefd7fb2f80257477c2a3
    md5: 85d8d5598578905f508e24e06d684e2b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8f41fcdbedcc333059f0ab4e7864571b
    md5: 3c40e7161aaa8b259296f95ab3d93197
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c5c943d05998881ee2c787862d0988d9
    md5: 0f1fa94edba24380f31f0c50752d2023
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_tracer.res
  hashes:
    binhash: a99a5384a6a767781afe056676e0efee
    md5: ab05089c2eb0c5aa17b07bc7a250f2f6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 64c1da38a381c2aa714caf22031828fa
    md5: df43e6f4016d7f856534fd7f2cda118e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: eeda3992757da41e191e579181b55856
    md5: dec0cde43beddf365e2abc4a6cc51766
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5bd6b3c0e728afdd870d3a5e621b455b
    md5: 8387988ab6fa8fca58c65d19bb269283
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart253/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: de3fb6f4c7c5efbdb2aea8ab917b749a
    md5: 4ac5a5b52bc2f1d8ddf82e266aa21d29
