format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/atmosphere/restart_dump.astart
  hashes:
    binhash: b8319835fee9fabb216dc2cf0f2f967a
    md5: 36d525bd7a910bb5c2e2fc63df7012ac
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/atmosphere/um.res.yaml
  hashes:
    binhash: 8ba6c2bfdddad98900acb4883a3b5e1d
    md5: 7744de1b463ecd7f2e1906ba4aba30a2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/coupler/a2i.nc
  hashes:
    binhash: 8038b2f91d350e85a28d3cfa703c8db5
    md5: 01996cbef3044e8571fbaa590a888d35
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/coupler/i2a.nc
  hashes:
    binhash: c81a3b6ab09b89c792bd7d77d5916e23
    md5: 2a5da62128192c77f81fd7484713f0d9
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/coupler/o2i.nc
  hashes:
    binhash: aed29e6be8c53cee8983fe456e46cadc
    md5: 594b2db0ee9dcc25cb62173bda117bd5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ice/cice_in.nml
  hashes:
    binhash: c742e71ff5e515c72dc06e1e712fe4eb
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ice/ice.restart_file
  hashes:
    binhash: 1ab0f3e87dcb00d5d0ce593fe79aa310
    md5: a357f8dedd8771f5d1cf57bcd968a1c8
work/ice/RESTART/iced.2736-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ice/iced.2736-01-01-00000.nc
  hashes:
    binhash: da78c298d7132e0aa66f7ff0a1aa3769
    md5: ab2b809575a365bbcf57942a83802aba
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ice/mice.nc
  hashes:
    binhash: 3c9c8be70874fe78864acbb089900796
    md5: 037b3cd06d9c9c4f17d4fd2486d9bcad
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_age.res.nc
  hashes:
    binhash: eb3f09643f2223034c71319c5d789f13
    md5: 8b801885c1b2e0257fe528e893f71280
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4dbbbfdc41e6520d33a50ebd4d6e781c
    md5: f947362769d50db2628b695904ec9a25
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 20bf4c5b5bd555b60f652692f1ecf191
    md5: 02dc9f24c3de07533a6e63a328e0b224
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_density.res.nc
  hashes:
    binhash: d9c562feb7c52c8b8147fc00c36de7d0
    md5: 9c6f5b7a26f4cdae94b3d87b138317a2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 07ece79d45578d8769ceeb2cce6f4351
    md5: 18b321f03210480e113e0e881707b2d4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1a65454ffc9dae5fdf1c9de5c8e0416f
    md5: 8c625e64cf5a924090200f28fd4bd6c4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0f1b8b274fee0b224b9801569b255d68
    md5: f0f5996dd1e620adafd17fec63ffe772
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e3b456d970197a3490444a6ce575cce2
    md5: d6b68161b1d53b00a9c1bede073a7a29
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 56de132074567297dc4df6922700dd6c
    md5: c182db3f23d2a02be8aa8fd26ac11798
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a06c055d6b3137823f6121e28aad1539
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_solo.res
  hashes:
    binhash: e6b3f4775f0b47ac807ec0b1fe55e189
    md5: 76d9690897242f6c84d951131f17304a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 55e67419634d531f59694a5daac82bee
    md5: f492e8cc6968a45c06fc65b1b16f570a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0b373f30fd840e8c520e274659635ab4
    md5: b0413d4f506946590a4068761356a43f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_tracer.res
  hashes:
    binhash: 15f5aab506dd99aa84cdf58cacbd1321
    md5: 0368fc507e6af4b99adec2fac8431c2f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8432f74cf729131d99d933a53f1f2965
    md5: 4a66c7697854caca1d976798b498cdff
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 712115dd406c98061aa2fae1f7e62673
    md5: ad335979dcc8c5536207e6e4b0ad178e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c6608e3a06f76da11147acfb368f7075
    md5: 193277a721177a4d153110a8789d14dc
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart059/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8cacc3437badb2077d212dc71adfd737
    md5: ab40875d12f7221d945ef31be1cc75e1
