format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/atmosphere/restart_dump.astart
  hashes:
    binhash: 205ccdcfa54c8820300dd5b48f60c172
    md5: 5cf4bb1a46794b1c95942820d6c5593b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/atmosphere/um.res.yaml
  hashes:
    binhash: cdedf238d9fa1d302174011fb2c0a0b6
    md5: d974706f2ae6d2f440329e9bc8a5d9ba
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/coupler/a2i.nc
  hashes:
    binhash: 68b6384a9b0fd7850798dd1c8d3e7832
    md5: 68e1c5bdc4058b1606fef316e068850f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/coupler/i2a.nc
  hashes:
    binhash: 70d08b3dcf6450c0bba5a44b9307fad8
    md5: d7c7e34bcabe48061d2941664d020ed5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/coupler/o2i.nc
  hashes:
    binhash: 2c879fadee0cb5a35cc4717ba18b17f5
    md5: c1d22ce7fecd51c555598da7f007f3de
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ice/cice_in.nml
  hashes:
    binhash: 9a49b4912d4b1dbf4cd2cfc66206ab5f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ice/ice.restart_file
  hashes:
    binhash: 5b2fd735e573ed9df50db289490aa0a9
    md5: c841a9ec4f8927dfefeb93cf49469412
work/ice/RESTART/iced.2878-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ice/iced.2878-01-01-00000.nc
  hashes:
    binhash: c195b7d4df783f657e553a20c8ee0609
    md5: 8c8f36728fa54c57e690537b713267a5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ice/mice.nc
  hashes:
    binhash: 64a90aac3a6212f53915170fe31e2b10
    md5: 6ef6d0035863ad819c15736cc888e914
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_age.res.nc
  hashes:
    binhash: ac7266adb724850b99253941641be262
    md5: c122848dd94ec97b8d15d43078aeb76b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 89a337dc88a60ebdc22776469b018ea1
    md5: cd9a78b8560abc3088877883d7149066
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a2c54d8c59e589e2ded0aff7de0297ae
    md5: 6a9cdbaf48743328970bc1f935b2e063
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_density.res.nc
  hashes:
    binhash: 8a1c07fa544b2eb6c3c9c7d585be361d
    md5: a62eb7a94763eaaa94c32ada8a760d8b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 90b2935fe8b3f37b85fe99c63479ebb0
    md5: 454c4a5fde2df7d2eb5d93d5aeb2dd5e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1347fea097fb9f7e84f64b2407fa8580
    md5: 1deee1452ccd670abcc31a7e3355d9ce
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0960426e2d84d4b4aeb6e8df6fbc695f
    md5: 2cc258dae55e465e163d9f2bccbcb068
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a985b69a53a8304506c7976e319a72ca
    md5: c2ff311cd2590ca9ae18d91dd87d1383
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bc07cafc466b502c8aca58c513c7e975
    md5: 808ef494095499fd3499aadff5fdb627
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e839ce584f9a94f10443eeade531d755
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_solo.res
  hashes:
    binhash: 3d80230b4dcdfc7d5cb65f7aac888a46
    md5: 0883187673d2df7732cfedbc87e45d07
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3b87317a5e9c2545f86ce992359072bc
    md5: 5659c32538ac8ef57ac33e3ef7fb6a07
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d11299ff230a63ba1f11262308f3a94a
    md5: 4841abcaefe1b3e6bc8dd4ac678b98c2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_tracer.res
  hashes:
    binhash: 87a0738ddf5c9f5362c59cbecce7bd24
    md5: 4b5fd2ca99c3bde9a544abc9098679a4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8b0d52a0f04ab3546384981928bfb27a
    md5: a6ca7a98115b755fd598d0ed2214ca47
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0d75fe6f5cc48304e1efcdd455cda201
    md5: dd6e692ec20797c8e26ddda45636b3d3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0a0dd4e4ebdc1f5506a78327ec0f144e
    md5: cca5d8d39e5fa4c9508a93d2b1f8fa17
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart201/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6e20e37686f3041fdf36ab6a404a768f
    md5: 55a4760991e35fcabb82545bb9b13c5e
