format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/atmosphere/restart_dump.astart
  hashes:
    binhash: 265dfdb6085fb91661b60ef03d9f16f6
    md5: e55f89ac446629855c41468d27484b27
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/atmosphere/um.res.yaml
  hashes:
    binhash: 7ff1f1889acabfb19a919f5278337f92
    md5: ff3a71686509ee3a5c3dc872a42ba9b6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/coupler/a2i.nc
  hashes:
    binhash: a03fe109657f7dd99a67a698e10d0a21
    md5: 5c22222287a5603cf2ae1af736786a0b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/coupler/i2a.nc
  hashes:
    binhash: 9f1c7c0f6ab35736be68d60b54807161
    md5: 872f4eac48c6a9c79868f612a199c8a6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/coupler/o2i.nc
  hashes:
    binhash: c5475c1895812ffb847c41f3ff2d3199
    md5: 66f5dcd3b233170b07d65def64915b36
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ice/cice_in.nml
  hashes:
    binhash: d9f6f6478bf6175f37619446346cb740
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ice/ice.restart_file
  hashes:
    binhash: 86e1207861936e62a68f9994264bced9
    md5: c6cd9735006601d8dc2013f98ac80f36
work/ice/RESTART/iced.2946-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ice/iced.2946-01-01-00000.nc
  hashes:
    binhash: 23a43212488f00176e1165f737b83e11
    md5: 5f7f4c5236ecb913b85fdb54d1971781
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ice/mice.nc
  hashes:
    binhash: 57d2e9fee8c27d155820375ef148e98e
    md5: 196d3b41494fb0e829eb7a82809b537b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_age.res.nc
  hashes:
    binhash: d94446d50df4d1ac6d0a0e468a1e9df5
    md5: e7b557bd22827458e7285bf0246f7ed3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: df7c59474a473977b9ce2b271e3ad889
    md5: 88ec4f0cc82bb66c60eba85565a1e429
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1b909648c8e299db7ae6034e2d45409b
    md5: 67c7f69d2d1ec3f7b35063b3328167e4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_density.res.nc
  hashes:
    binhash: a53aa90ab6a96c9359637048df94ee46
    md5: 6b3d8ae175668a0f30023bddd26b9f25
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 888bed085b3a1b1a18577081c98fd61f
    md5: c2c139114e25557564bf9168a35bff1f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: de5d40220ef22e8585a26d101f31b184
    md5: 1b3be04040b62c56242021c6933663e4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 212ff901d3f4aab7012f98ae37fb80dc
    md5: f02fa7ccb95f4f032df482dfe73e8322
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 04675b54b2aafbe38a18773d1553a291
    md5: 7860ecb963d816f9f4cbf958592818dc
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_sbc.res.nc
  hashes:
    binhash: fec9330bf8b5ec3bb5967ebfcfdea30f
    md5: 7f56ed78cb18756eead3133fd45514df
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5d8fd987f49d5538547260c077fa4dc5
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_solo.res
  hashes:
    binhash: 34d1f28aa5ca489ea6a2f1066cbebb57
    md5: 176de72998398ea124b574580000d2fb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 82fee6fdcb38c114e63d133b97e8b00e
    md5: be35bbc86c1c927d5011bc8e65533e9c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a9d730aa315b2b66b10466794d462bb4
    md5: 36fe25cd782e6bab96857a31aa757b18
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_tracer.res
  hashes:
    binhash: 6f85ace62833af0a5f0942b3510f4944
    md5: ceda085c33e008cec4e78bfd9140d72e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 24400bd688b3bf4a97bdc32ddcc0dc75
    md5: 6c516cc2f492fcba83eb55af16d08c59
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 51f62ee908b7be83303c18634da7b79c
    md5: 7484b52d97405fe6ad10fbb485917ecc
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: eddafef459ba3d8c5501e67634999fe9
    md5: 240a27283bab89092ffc4386e6b710d0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart269/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f3e43658cbadc061b99dfbf6884fc5fa
    md5: 30c59ba0bebbf478123e6f1e9f2e4a22
