format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/atmosphere/restart_dump.astart
  hashes:
    binhash: 5ceb5754ac589b8e46dac4f9ecfececb
    md5: f789e410acaad20cf1742158b1b38b2f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/atmosphere/um.res.yaml
  hashes:
    binhash: 7b9e71c11a5f4149c4b621e931a17eb1
    md5: edd7672db30d3c27d154fc4ee9c5b6eb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/coupler/a2i.nc
  hashes:
    binhash: 39d8f54025853ef2d84d1a0c71bca0f2
    md5: b908b4a6d08788b661784ddffe4ff684
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/coupler/i2a.nc
  hashes:
    binhash: b9b796c21bf8989ede55ebe3bcb751dc
    md5: d9d003efb41022bffbe118c9e0fc4f32
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/coupler/o2i.nc
  hashes:
    binhash: e72e2a2595d39b354ef9736e42ef0dc7
    md5: bd5200fc7eadd8709663526273f29bca
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ice/cice_in.nml
  hashes:
    binhash: a34103d42c793699a6ecd7c99d1e71b8
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ice/ice.restart_file
  hashes:
    binhash: 55d835d52d1463e72fc1f9c29bbc948e
    md5: a314b9373342bf8710e0494203ca5a83
work/ice/RESTART/iced.2817-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ice/iced.2817-01-01-00000.nc
  hashes:
    binhash: 2748f479ba90a885c5d365b6d1b64a9d
    md5: 3d9fe77306f25a705ad1459e285e0b3a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ice/mice.nc
  hashes:
    binhash: f5fe35c13f3338f15cfd4ffc4a8f058a
    md5: 1ec48b06845508df33ed36ad0d1d20fd
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_age.res.nc
  hashes:
    binhash: a2ddd9825f67e6c35d832d61590bac4d
    md5: 0bf1c99211b6b33787bc210b9ef8e1bb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e23a3aa9a1c6e1e772b0d9f67196833b
    md5: bc7f6e7d79793cab7194a1d1e6eb8506
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 98fd3a99ff91de09398a7d5aeb0db1e5
    md5: e762f8d7be52edf67e862293c5f0608c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_density.res.nc
  hashes:
    binhash: 7a6285b596c45dc35f30496d2343bf48
    md5: 5bf59a0fa45741ba2d47b5898254b78c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_frazil.res.nc
  hashes:
    binhash: be2d7bb89327c6b0346840d5ced0b42f
    md5: cb95168d30b3fa295381265d666edbe8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0334853f4a2acc37034cd4244ae846cb
    md5: d5cf16ad11ef5dc65e0a33b9d0de91dc
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1e56165b4069b622574ba928b1e6705a
    md5: 1c0f27d2d40c30a2ed9e4a6fa9eac371
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0448e352ccc40a35f99bec63c06e15f5
    md5: afcd24cc542d57b01a9428bf42b6de14
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f47fe000aa2dfd016927354439c6a80e
    md5: 4fc7cbd9d9badbec896b28a9790b52c7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3e925760b4fc77d266aa7be5500a35df
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_solo.res
  hashes:
    binhash: e3f4da06f76a4785aa11df2cbd678bc9
    md5: a6a1f567286d04f1c4cc30540e381de7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8453ca42fbe7b9e784ecf1ea6af63f20
    md5: ca64b8fdebf7880068e6ada5a8e8d960
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 980744ea294600d659fe8b42b4e59dc5
    md5: 2c26ae166fb64de310c53a5e61eb34f8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_tracer.res
  hashes:
    binhash: ba7f1572666556d4fc91f56858c9c3c9
    md5: fde165d623aee9e28da5fe2cb70fa58c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e516965fbbbe2b111151d3ecacd498ee
    md5: 38ee00763330280a41321fd0e0150024
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1b24017dff8e61b9871f4215103c1065
    md5: 018ebaa1d05d973c4d2f8d9bfb396d3f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4dec1a311c06e45e67ea6bc5f0d1ab41
    md5: c769cb77b0b2b567001cf0cd04a020df
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart140/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3eb2e64579903337340ca3e4ddc09723
    md5: 4886b9f2e82f5752088ebe5c5595c13a
