format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/atmosphere/restart_dump.astart
  hashes:
    binhash: 3036f281a8244bf1b9b91240c38bac95
    md5: ad6b388750fda16ba28e285770235bfd
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/atmosphere/um.res.yaml
  hashes:
    binhash: f59da0d8106c1e660e99dc5efc0fc8ae
    md5: fc98306d85473164535ed9c5367fd388
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/coupler/a2i.nc
  hashes:
    binhash: 958766d2b80d1e401cce95282cc90ed2
    md5: caa272431adbdb55892a732ef060af33
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/coupler/i2a.nc
  hashes:
    binhash: de2752b76ce4c755d787e990f9a8f745
    md5: 156206f947289f1cc8c991fcf07b520e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/coupler/o2i.nc
  hashes:
    binhash: bad2b11ed11d137690bcb3ce75d9401e
    md5: 294458c131cc19e35fc360a1a8e44286
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ice/cice_in.nml
  hashes:
    binhash: 61c86a5c2321bc8c9fdbebfe90e2caa5
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ice/ice.restart_file
  hashes:
    binhash: ea0717cfc25b36f0ebb2fa41dad7786d
    md5: 1037f99d183cce95d862f89ca2d153e1
work/ice/RESTART/iced.2949-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ice/iced.2949-01-01-00000.nc
  hashes:
    binhash: b637e4c2236226a6140c52934142785a
    md5: 4abec5fe32324b3209fa63bd73470f6a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ice/mice.nc
  hashes:
    binhash: 9fcf944a0bc09a475f9c656d9c17d3b8
    md5: be926591b073e689e605fed00855960d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_age.res.nc
  hashes:
    binhash: 17285e3f535c95cf438fcd581fbb4501
    md5: 0f50be77a9cbcf892115611dcdf40e71
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5819b87dba2a6fd5f849130d3f89f2e8
    md5: 8b1a085235f1daf3d01d133854adb2dc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0b56575be063083a9ecc03c58381e07b
    md5: a294f3a8de04be2acc8d9a23dee86801
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_density.res.nc
  hashes:
    binhash: e5d41def7e01e970776632c9ac5aeefa
    md5: e11a32b8d20f9b679157824a0d339729
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9aa6905f67844b54b308d8ece32e7319
    md5: 122d6c058590f8cf24022cbd149f8640
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d32c75aecc3742a5bd546fbe99fc44f7
    md5: 9215697202d8ff05a0e68d8fc09e1839
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 558d5da4fe762a3bded383afdd243e1f
    md5: 1e4e8205cdefa9d896143511bf619643
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cdb816bd232f772c5038fcbf17e093eb
    md5: 4585818ff2c77bdb4626bd9ab8d7c53e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a0433ddcd8dcf30d270e0d8a0fa31ecb
    md5: 62ef4b745dd170eecc803cd00075f3e7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 69ffa2ca73d4b599059a1d1208e191a6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_solo.res
  hashes:
    binhash: f8b9b2ce45364cd04015f5ae1ce29efc
    md5: 2d52432fab56a7d5caca3cc1df4aa12c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a70a04f4ca56d0649e345c7efebc41f9
    md5: 9677818e9cdac6c3dd5d8e38b9eb7365
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0236bf1e61620be1e8017d324bf58fea
    md5: 143b1cf0aebe212856780f30cf03f9ad
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_tracer.res
  hashes:
    binhash: 21341559812556f2655f0c84430498c7
    md5: 54b0d26c03e550a4aba0a85d7801ee43
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 79dd5f89fcf7af3527a0642667032183
    md5: 402f2044a6d49039d881318616ff90af
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d46b119f4c2e8087c54bd7b030b7c42a
    md5: b4607363a1451b7d17e78bda145306f8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ac24c4eb03b5ec8f9c18eecbad61111b
    md5: 26cfcef800a425bdaaffa6a15a3e6469
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart272/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 35c08c735b5fbc566aceef603f907c16
    md5: e8c32ead667fa2346f4851ff2eb972e9
