format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/atmosphere/restart_dump.astart
  hashes:
    binhash: 86ac7022bc5e2a5c956cdb7e5c4e5c2d
    md5: 913c67a54c1fd7279f6edbaf02a86702
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/atmosphere/um.res.yaml
  hashes:
    binhash: 247cccc96d8d3caeb897821f63d4cf31
    md5: 18343f1371e57826e41d6548f869f3f3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/coupler/a2i.nc
  hashes:
    binhash: 7b9a8f877b8da91504bb21bb82aafb5e
    md5: 4163b997fc7c1c91dcce178c4fa5733e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/coupler/i2a.nc
  hashes:
    binhash: f292f1231ecd21b64944b697cef0786a
    md5: c2d079f18ddc26738832683ce52c7db8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/coupler/o2i.nc
  hashes:
    binhash: 7c7e0b7d370144ce726fabfed8397713
    md5: 25e3a15ca726f01c106c30f500204ec8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ice/cice_in.nml
  hashes:
    binhash: a92c7de0e966bcceece6af929c4948c1
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ice/ice.restart_file
  hashes:
    binhash: 132395221db86e13ce4b5953dbf03af0
    md5: 2bb5e28b1798dcf2983a0f566fb97499
work/ice/RESTART/iced.2719-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ice/iced.2719-01-01-00000.nc
  hashes:
    binhash: 27bff632e261b4d854d6fd121a33ca4e
    md5: 79a06dbc75d6a075683da210986b9624
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ice/mice.nc
  hashes:
    binhash: a3f42652a8e35f511cb650259ca5e21b
    md5: 4df188faa5faed18b327f1317eab7bf7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_age.res.nc
  hashes:
    binhash: 4aa897b24a38a02f32513c41a86b8807
    md5: 3ffd3ce8add024a0d1572fa301dcad59
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8498c6ee42ed56d3e4b0a7bcc147de4e
    md5: fb62449e80a4d4b098605450adb15cfd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 616fa5e4e60d2ed49832e61529e696c5
    md5: 2409b5645fe004bf57c58dc4af8e742f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_density.res.nc
  hashes:
    binhash: e7019a0fcee4925311fd055bf0cd95fc
    md5: 677b8107def8efac95c2e4eb644695ed
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_frazil.res.nc
  hashes:
    binhash: eb96b35b07ea20bd80c89a1d6209d083
    md5: 9217077360a3f42903998c58740dd097
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: de4ff09c4e06e13d01a504cc54d25851
    md5: 3ce5875e4d5e68ddcf6a72e383320eef
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 98d87c0df1f72f295d771320d890f541
    md5: 40574d83c12c83dc0997241203bd2c69
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4378cf0724da45a70da01ba1e8f53fb9
    md5: 3bfe47f72f7c5310bfdaaf3fe1bdb35f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_sbc.res.nc
  hashes:
    binhash: daa3b3a4ae4a9ac0c12eb828ab7cfd97
    md5: df90eed473f5a441dd7f0577be13ed40
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 55435cb1b77e742fcb133499b6a8abdb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_solo.res
  hashes:
    binhash: 74590aaf9a57c8460ba4a140ceb433f3
    md5: e76a7ad9f531fc6dfe1bf04cf734339f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ef4bf167b1a95b7232306940c3622c82
    md5: 13f2a0c074eef56337520e7965800fc4
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 567a63d220b125eb26da73340fa7553f
    md5: 14bd2b799b6afd3dde730cb1029c3060
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_tracer.res
  hashes:
    binhash: 28dabfe849887095bf54041681978879
    md5: 384444f900c27292a5ac3babf31ea871
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c9de9578fc9a53246dc18f0f3c878465
    md5: 28893587a0e5d95c74ba1ebb0b8fa803
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 01e89dd64557678c9db21cad468d00fa
    md5: e1e38aa9b27d4569607cc59adb3cf559
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 64a93eb9335f108acb4237497aaa01cd
    md5: d1f8b5de84261043f6663b1021768059
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart042/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8757e40e18f44612f12018de429da478
    md5: 82991f50b7a6e41acce844a61563621a
