format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/atmosphere/restart_dump.astart
  hashes:
    binhash: e312f7c3fd921c967445545e8165da24
    md5: a9ef7c2aa9d2efbdef4b2a8024801f26
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/atmosphere/um.res.yaml
  hashes:
    binhash: 95e41a40ec6aea0b424cfb230078a294
    md5: 7a874457977e467bd3fb71984cf8d5a0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/coupler/a2i.nc
  hashes:
    binhash: 1b4b68c1c3d6b0b8ab4b3d0b1134f44e
    md5: 8d24a9accc7648f715b9082e67d22795
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/coupler/i2a.nc
  hashes:
    binhash: 502f539ff49fc5663d7e18e65373b673
    md5: bae423f6f7c7a16f839e97aafc766a89
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/coupler/o2i.nc
  hashes:
    binhash: b9bdc31de0c429093fc87f114644112d
    md5: 1b00f1eea26ba2d1a835f85856d7f8c4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ice/cice_in.nml
  hashes:
    binhash: 4af1457cb885592008f2d7cc45c7c2f8
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ice/ice.restart_file
  hashes:
    binhash: f4a4510c4f879369b74edee9dabe1b55
    md5: 0cc7150583e4ffb64c6c0ee23b77f125
work/ice/RESTART/iced.2689-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ice/iced.2689-01-01-00000.nc
  hashes:
    binhash: d3ab9bcea72ffd108dcfa23fdd026b66
    md5: 8aa42699547eb45dd8d2ffe63fd3eb8d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ice/mice.nc
  hashes:
    binhash: 86969794ab0c3bfe0fe00de5793248e6
    md5: 30f3c81dd47881f519110fa15e829843
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_age.res.nc
  hashes:
    binhash: 17da090a9a69d7655d44b20383fadff1
    md5: 8ea099ae644306f41a148e3285773b84
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f27c36da732b17c495b35e2b2c83b9f9
    md5: 8c0e24686b45119b8fb32d67d62bab0c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a7484149c2772ac6906baca6f6993bd2
    md5: d787c5892262a205de0bf343a9e0b209
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_density.res.nc
  hashes:
    binhash: 39d9586fb22834dc4507ab1760c0469b
    md5: 49699e39bad11a2ec7c8a34359a66af1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 296d010586064d989aef9cfd0fcc54ab
    md5: a2fd8f99bbacf09d7a69b85a68a078a2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a67b06f7929aca525a21af9464c4f271
    md5: 6abfb86ff63f86aa4d873f5f2fd0275f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 708c38edc16d181f249ba52cb56f2e9e
    md5: 08d985e6fca0f5d6e0bccf0bb936bd64
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 12affa32b6b62383f907c8d5b559b7a7
    md5: 06101433d416e1bcc02714751baab38f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bc8553c2ed04f518fa12728e786fbb68
    md5: ce834008bfb79f07d32dd57e584be187
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1b57264712291fa15d9925ead683a9ad
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_solo.res
  hashes:
    binhash: 0f7a6eea62f5df417257ce33aeae5f23
    md5: 04fdb0dd53966af01b94dae92776801b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: db83400dc686ecd4de5b5567279da42d
    md5: ba3dcefd51a5f5e02ae52e1a89fdfff6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 93e391b781595d8d264c3242cfb8044c
    md5: 2c8478d61dc3e52ba7a17f7ef5c80ab4
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_tracer.res
  hashes:
    binhash: fa696543cc56c83e039b7e4cb1c9c531
    md5: 0938403b6f73f0476d70e13979427246
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a82f248f2ee2ffa9101ad9ffe7070424
    md5: 569854aa00e1d1333e1d54da00318a45
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f22bcaded57c2b4b7dae5375372b6e8e
    md5: f84039b5a40b81841c5e963fa49f4ac8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5e94d6189eee10913d48534e3281b213
    md5: bb185ad1912ba01c40114e3d52b20ef5
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart012/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: aa299ca800602ca9dc6272f1663e3ef5
    md5: 40b636ebd7f493e48de055a2d2c94f78
