format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/atmosphere/restart_dump.astart
  hashes:
    binhash: afd02555894d0290860f5500fecba675
    md5: 22e92eaa4d807c82d49c138a8e899c3d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/atmosphere/um.res.yaml
  hashes:
    binhash: 9d9728548547f20b64bbd32e8f6a8472
    md5: 376a429214cc6660413f4276fc4a6980
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/coupler/a2i.nc
  hashes:
    binhash: 8e0f1064b7c931f96e48e72101f3f429
    md5: f27af2ab05d4833bbbb5d6b5a53ece1a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/coupler/i2a.nc
  hashes:
    binhash: 58f6bcb26272046a653d650f2cc0378d
    md5: 37faa4567ebe293dfa9d725820ac7e52
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/coupler/o2i.nc
  hashes:
    binhash: 45d9aa609ac403df63fbca3e3e47ec67
    md5: ccafd471fbd8d116a309c3bc3dae4e8f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ice/cice_in.nml
  hashes:
    binhash: 4539ade89425e98ce97ecc76c7e43113
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ice/ice.restart_file
  hashes:
    binhash: 588344466c48709e599521fab81a0b8e
    md5: a7071910539fc9012220e7acc08e8217
work/ice/RESTART/iced.2707-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ice/iced.2707-01-01-00000.nc
  hashes:
    binhash: 405888119797771289e1a5130d97ab43
    md5: 45bf6f96292ebd300f89799fc993a932
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ice/mice.nc
  hashes:
    binhash: 3a76125259009d27539e11f5269ca23c
    md5: d6c2a04b22bb7ae71167ef3178d3f932
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_age.res.nc
  hashes:
    binhash: 2fc9d52e197a930153307044e6ccace0
    md5: da74818041696e3a6e8c67ace4f7fb56
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 71840f070285d1c4a14059c6b28f3e8d
    md5: 46afbbb1517d31a1f2efb3f5e8080ac3
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 809ac8c5f0cd09ce50f82aaf39b60f50
    md5: 5fa6a6f4f42530858fef08ce71e66b63
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_density.res.nc
  hashes:
    binhash: dc9eb606fcfaf0e3617200e28886e793
    md5: 5636f782f7555c497608550cdc1b71e6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7cb0cd44ce9818a00384eb5d5d16a914
    md5: 2258a0faf9829eb5e51314e3df3b340a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2483ff614a8de879771a14c86931fae1
    md5: ec432a39acf7260a6fcbc4c808ad6e91
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 27c08f1057e1444de6afa1cda13d1a3e
    md5: 1b163311470a336c60d1f6c46382b712
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 913054f91456dbaee7689b223f3244e3
    md5: 03696bf80b0de9d6546b79121952b4d2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 90fec88d7b30765fee90c850f1acd186
    md5: 3ccfd35e292dd29708b4bd688273f405
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8b0efa5836203a6af87c50df20d68eee
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_solo.res
  hashes:
    binhash: d36822adcb7949d62306d67db166b76e
    md5: 3e97afb3aee42b62ce5730a3a6bed087
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fba7d98bf60838180043bfe004452d51
    md5: f667421cb1b403687de8b1d7780df7f6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e7c7ce6a71ecc9db4e9bea8ae649ba3d
    md5: 02f1d9fde52d32b4d4ee411cddf4e3f5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_tracer.res
  hashes:
    binhash: fa02d2c7a8be4371f9adbecbf549d8ff
    md5: 7d8bd7a15058f52c98743b0067f314be
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2455c37a55687f51950db72331823b01
    md5: e5c008e3743bfeacbee3e999a4b8bcd0
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4c2ff6c6d02fd7e5cab6b74e95feb5c6
    md5: 144cfef16da9ce5d3eda9fc85a6c634e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8bde1e3d71408e06dd85d8372a77bc8d
    md5: eff3c84bd75045537867ab11b111b9ee
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart030/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2b63aebf03af237c94ea8ce54b953a23
    md5: 4b26a64ef8bd2d64a39f815cfe37bac0
