format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/atmosphere/restart_dump.astart
  hashes:
    binhash: 8678a86017b236a1d2377ce4d5ca45a4
    md5: 25465fcfc24132ef2d669ae37f18eb0b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/atmosphere/um.res.yaml
  hashes:
    binhash: 458eba10fc8255adbfd872389387a979
    md5: e109d621009d8bd7eae2c6598c316369
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/coupler/a2i.nc
  hashes:
    binhash: b5a0cb5cc88564e195fb966e99d3e8d7
    md5: 98b69a8e72bdb75e33fc7d2ceb93e74f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/coupler/i2a.nc
  hashes:
    binhash: a344b95c38f2c1ab2f0d74b26726742c
    md5: aa96283c90d5bbe8ab2e2e3d0252dee3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/coupler/o2i.nc
  hashes:
    binhash: 25b279b42a1e118795ebe033dba023af
    md5: 61556a6b6b10f0491adc69a2a6890fff
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ice/cice_in.nml
  hashes:
    binhash: e56742a39dd6a7ebba60d49fedac5aa8
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ice/ice.restart_file
  hashes:
    binhash: f77ba72ba6a1d389e78b3c7b1a622e06
    md5: 616e34454b38a14ab1ffe907c6b9f60e
work/ice/RESTART/iced.2952-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ice/iced.2952-01-01-00000.nc
  hashes:
    binhash: a6ee8a6bcfda87e0d4288bd553d85c9e
    md5: 34da82eacbaa424ba6773fe2763461bf
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ice/mice.nc
  hashes:
    binhash: 95888b2c29d8ec0408d8ec92f11fec1a
    md5: bf42e10c4de86ffbef17ff1fbf4c68b4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_age.res.nc
  hashes:
    binhash: 266ccde79b588e9f873c15cb4cf5ff09
    md5: e52829d58cc56568bc09f8a561ff17db
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e397657e4d33f04db6d55e5ee398f165
    md5: eac89e8b75d90a8ffd9687d8693ec4f1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a77751e4e5adcf26a9614e9906b1ff0b
    md5: 36c028b5d07bae360ed2cbeea662143e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_density.res.nc
  hashes:
    binhash: cfb63ffba288b4854e34a72275532f57
    md5: bf79d4809c1c42ee5352fba446920058
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6e714eeec6a303a503f1dd2c1e9aff60
    md5: 6cff616ec1d5441da7a29a0e4439ffce
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 59e9fd838e6fe23b7760bbb629a35069
    md5: 852d41c25e9d5a54b8ef457071bf0b24
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ce26cf784ef2083d1fa724d88851115e
    md5: 89d63a720a4320b58a1d6555fd81565d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: dc0460f8c603eb1510cbbf0967050992
    md5: e8a442c903fd5876ecebe4792acf2b61
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 63f68bd9aea49e02f0bf8480e0d7748e
    md5: 4bbb47db9bf3e67c291d88bc7fcda883
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 41fd6be0a9646aa34a650f0ede747acc
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_solo.res
  hashes:
    binhash: 6e9deec8f9319d874fdcf103733ecbbd
    md5: 8f8d640b890577a9ff558fb19f5df9c9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 48b0cd5c24c8fa77591ee98a85703704
    md5: cabe2276abf7b30d439dda8abd669985
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3bbd3eaf486c849dbda9f7404b20daba
    md5: d4ecf45261dac331a3eececacee4958a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_tracer.res
  hashes:
    binhash: 57d6f9a5a9c2fc51531e27258bbbe08f
    md5: b9d26782025deebf17c4eb1b8bcc6ca8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 758d4b00f603e6efa14da24f07d872c8
    md5: 8333d92950f7cfe0d9c3f7af9278299e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a90d03dae6f921ebf2cf1105203a8f33
    md5: a1363f98334992c4c33d572247c05c89
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8c3a0793dd5523b895e72246a9446bf9
    md5: 62c26001f16b7abf62f80b927fc4355f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart275/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a250330fa2d2f648cf88e36cfeffe75e
    md5: 4275d0944eeceb5726683a62ee709798
