format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/atmosphere/restart_dump.astart
  hashes:
    binhash: fccb23e9abef83cdb87255ee2f5f9204
    md5: b5c6c53a2b4104c252333f8fbc4b8796
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/atmosphere/um.res.yaml
  hashes:
    binhash: 5ae89662b9cd60e5d0fc59643c206829
    md5: 0d174aeaa0477cf6897421aabeb2b123
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/coupler/a2i.nc
  hashes:
    binhash: 09b185d381ce80f6a1a3c80f77674f18
    md5: 6ccc2469b8cdf0ed40d23eae7dcf3569
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/coupler/i2a.nc
  hashes:
    binhash: e2c378090354a3e500446a6db0e8d231
    md5: 7d71d3ae780e705a86dc564af49f3ca4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/coupler/o2i.nc
  hashes:
    binhash: b4e3967e2c539b490a1fa415939b461a
    md5: 0288b0909d9361204d49a3994bd3fdcf
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ice/cice_in.nml
  hashes:
    binhash: 57abe87b17b81ba59f96e578ff389e62
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ice/ice.restart_file
  hashes:
    binhash: 283c04047381213cbc7d4833569439c7
    md5: 547a39102d2aadb72fdbdb0b0455afef
work/ice/RESTART/iced.2961-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ice/iced.2961-01-01-00000.nc
  hashes:
    binhash: e15711072ace5970a7daf58320ec6541
    md5: 26eda47ce80590b809172f2af0dccf43
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ice/mice.nc
  hashes:
    binhash: c649f57e2ab9d1a35b21bb20fbdaf04d
    md5: a5b9f84060a6c91a7134da7c6697f538
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_age.res.nc
  hashes:
    binhash: 23a86187dc4eb02b5938f093439b42df
    md5: 45dfdb95fcf5a64dbc4165ee63e14313
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: efa2e471a72a7f5cb07656412dedf713
    md5: 5a69ac4eb279ff36d944d0207ec8a998
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a204c2084bcaf6f7151849fb09d123c5
    md5: 976828f355b6cfcefd8fa73fb73c075b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_density.res.nc
  hashes:
    binhash: 3c9407b4133b4ce050178707f503c80e
    md5: 6a5513e98f9879979fc90a709dd1ef72
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c536644d523592738d514c2890c231a5
    md5: 7bf935d9137bf6b4262b709e408d69a2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f8ebd810fa713d649bae98a9d461642a
    md5: d57b1f9d503fee38c501691cb559f974
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 805116645ebb47a41417f7a1955fb383
    md5: 795d83687f301e08545720246edae0a3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cc4742a7e4c4c54f15ecf9b38aa4d4ac
    md5: 142d3e084f47b38db3e37446c500af3e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1cb7ab3b0af81b11d8754f5736615f59
    md5: 3ad8a96cc8f350ad3b043cc6eba3e398
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ce8c238b990ba3d84bc68a5fb6ad2fc4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_solo.res
  hashes:
    binhash: b9c70839b3a2d913462e19f8595e26e0
    md5: 2cf8ed84ba538fc19a3f0ce1578ed793
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c183c65a0e2716670b3bb1713d565c8f
    md5: f9ec79c2ab2a0afa616cbc3e4397527f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3a78541a26d9d883517f37d2c8be8993
    md5: 83c0fb4ed76e2f89b4201fa9a403e7c8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_tracer.res
  hashes:
    binhash: 44f26a5dd20dcd30666280be7105a7f4
    md5: cc1abac1a21a14ed71208111fabb602b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2bc62dd8274d75ac45a7cda235acc3e3
    md5: b44744339c97399fa6c94577321b086c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6d1d608be062f395ffa75e7cf5d54018
    md5: 262eb7adf2ca79b6d1dcd60d7b529846
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: fc9433b83bfc7e115257074901dd7778
    md5: 8b657d5ff3176a63f07828de665c35a7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart284/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ade1dc970e96f459bfb55408427e4a0a
    md5: ace9d67b6e5be1b0a4507a855b1ff637
