format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/atmosphere/restart_dump.astart
  hashes:
    binhash: 163aede2afd2f866a60d59b50d295933
    md5: 2c8b0f7cb11581a3a21475a4e1b89709
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/atmosphere/um.res.yaml
  hashes:
    binhash: 698e7a6b37725e06411e9be8d2762140
    md5: ee069ca2b61e43d75eb7687aec86bfff
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/coupler/a2i.nc
  hashes:
    binhash: 49f680cea19788bbba5de9774a1e41e8
    md5: 9cf2b2f42f0d6cebe90f1105624a7878
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/coupler/i2a.nc
  hashes:
    binhash: a7e96325e2cadd329be773bba71bf847
    md5: 67ea74165fcee21f61c95e8f6811ab5c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/coupler/o2i.nc
  hashes:
    binhash: a8ddccd7a9542d60ca0ba76e03da5e4e
    md5: 76735c4a4d01e3f0a1c2d0104719b2db
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ice/cice_in.nml
  hashes:
    binhash: 643740218e93587aa9592050d962d9a3
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ice/ice.restart_file
  hashes:
    binhash: 384e8b0dc29cb6e5f486086bce1f8375
    md5: 278dae6b60e5b4c47e9862ed77b7e759
work/ice/RESTART/iced.2712-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ice/iced.2712-01-01-00000.nc
  hashes:
    binhash: 0667df98c07a7321ed5f296cd8e439e8
    md5: b5f57eee17393904c888fc9d4d28827e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ice/mice.nc
  hashes:
    binhash: 4693271437ab7ba0c70e3acd3ba50633
    md5: 28da2ae7fb4dd0064f015094867dfeff
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_age.res.nc
  hashes:
    binhash: b3ffd8725bf4c78ddb0c467f359fc4b8
    md5: d938ad897c3ddbf9dcef7ec311f18b5b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a49d85a042aa9a795cbb3b2f6b58822b
    md5: 7ce242250be2e6dcaaabfd2e0eb1e0f4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bbc727ab9e38f59b31f650b2381cc847
    md5: 4747a24138101c94425fb8de7e262123
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_density.res.nc
  hashes:
    binhash: 5af3accd974bcabd303dc9b55edf7036
    md5: b348701ea9dea766063d0d956fc77691
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 91aa965f6fee59f4f851b22eb864496c
    md5: c202ff9698ec78e4ce19bbcb7b37819c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 24cc12840ed42c22eeb3675070623a75
    md5: d39b1a89d39df717cb80d2097d7b8841
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3d003fa9ada52fb0fd98aba062e1d67c
    md5: b943f0636129e5f0a978334f7b0704cd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0d2f5cda2553cd1db2325d82dc910de9
    md5: d998c6421b5fcb8a57da356087b8ff93
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 28d7912459a7d97c61eeb2ac7c57207b
    md5: a97d057a73a4ecb96d2c4601650847cf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 92c380cab3f31644d97a73df0af5dea4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_solo.res
  hashes:
    binhash: 1e0eebc628f692e43fc4bd4accce0a8a
    md5: 938e8f736586c4986a218cd496173b9c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c12428152aaa2966ae3b5da03bc8902e
    md5: f28e46dca22d4ba2702be235bb379801
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 34df15771b8be27865e0d7fa6313f451
    md5: e6c53dc54cb3ab888fb64834eb6fd415
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_tracer.res
  hashes:
    binhash: 7f99e1d5b246fb9c9947bafec31bc54c
    md5: 7338e35fef881efc992336542deca55b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b2702ea294022141c8b71b7292147867
    md5: 06d8a802fc787d728d3333c757b007f7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8644d70e1f5e3be8c28b3ac96abfbd83
    md5: f14a82063526d8d25a6c3356eb6036d5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0d3aa78abf38cbaa5f36e28c332f6ddc
    md5: 0a73b7c854fb9c9d4f0d7ffb633f03f0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart035/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ac1b2b32ee63acef15270678ddf679e3
    md5: a1f69333d310880167896f51ca5d057c
