format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/atmosphere/restart_dump.astart
  hashes:
    binhash: 4e0357727faedecdf161d2727e23c72b
    md5: b52bb829a0d81c76434e92b22c0271e2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/atmosphere/um.res.yaml
  hashes:
    binhash: c98c16e29f12ec502c56a3c167d157be
    md5: cbf25167005d4f0436440c4fb1686102
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/coupler/a2i.nc
  hashes:
    binhash: 99f6ad25926f18971c0795cd7ba2bf73
    md5: 17e290e7bd6109d9842616f753e1544b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/coupler/i2a.nc
  hashes:
    binhash: 517e26d85662bffb3bcd9a46f808e8e4
    md5: 324b66c76c8795924a1005cdf3673872
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/coupler/o2i.nc
  hashes:
    binhash: f77c546cf23603a3dd08e40056e445f6
    md5: a8165315d5a0e01c4e2f73228771ecea
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ice/cice_in.nml
  hashes:
    binhash: ff187be623f3b40966fcd30b3fc631fd
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ice/ice.restart_file
  hashes:
    binhash: 7b772a421702089db49c48b0d1a61187
    md5: bffadcdb6c07ddaecb4e3e33b3224d0e
work/ice/RESTART/iced.2776-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ice/iced.2776-01-01-00000.nc
  hashes:
    binhash: f42b6d9cdd3da80a0fd599e379697ad7
    md5: 03139ef7d364c932804151aa45a4d26b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ice/mice.nc
  hashes:
    binhash: 6eeaa426bf07840ef487a26e6dd4c48f
    md5: 7ed88854eecf6d59cfc1fbc46af0c364
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_age.res.nc
  hashes:
    binhash: 32476bdf7f2bd9dc6dc228d07c70e7e6
    md5: fc527f3705397282e29a51de953c26a9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 868d595dddfd59d549f5721cc0216061
    md5: f5bf659ea44de57552a9a49e3ca4d25a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8dd5274ae8929eea9965e0e08dd33e4f
    md5: f2c6e361ad63dc06324f99ee38e77800
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_density.res.nc
  hashes:
    binhash: ac35ce41ce1e39cebcefb12d51645deb
    md5: 604e6ba57f11af829e12c6cc98e00d7e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 09d21818a5d009bb3f8798eb1e2df713
    md5: 4bf665c52e9a419f19995a8ea39cdd25
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b222e5b49f894fced9a73ff543e8390d
    md5: 8e883a8aa87755976d42eb960a5b3597
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0ca24d5a7596262f39cc56a390a582fe
    md5: 948283bef155408df426072a1af4cb94
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 383055c6e2bb648ac60fad7b4ff861f5
    md5: c75c28a857d0088c079c57c18808eadf
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3c6df8cc1894ef765e18ee628bf15c2a
    md5: e5fca14805217f306507d65de8d5b8ed
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f92815db52300b5ac0e3db5a7db53680
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_solo.res
  hashes:
    binhash: 907f92d74d134eb63a16cf26091ce4ae
    md5: a7a376d7dd832c98e6c9cee34cc7fba8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 54aed8553f096f1d88a95ca804f80df7
    md5: cacd404e72ac2896656eefcf8c16091a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b2000efa54d15bdcfd024307de11ec3c
    md5: 67adabea2c4a42484ebb716eee573dad
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_tracer.res
  hashes:
    binhash: c1c1ad76255fcfc92f28fbe14a9725fd
    md5: 36bf0fe8b830d21ec68cb5465b5679ac
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 06771634536edf9d208a208c7959710a
    md5: 018d91a07a13521c462d0e8cb6678d9e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 16855ed9b9b0e53cee877a4b82baed70
    md5: 597a940917d58144bfcb30835e6e4915
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 67aa1fd872aed5fb83e4fc0ba786c449
    md5: 230edfd06f44255caaad0b9b17449e6a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart099/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4214caace61e8efa8ab13a7230ca68dc
    md5: d3e03cf7b52291442947cae8736ab8f7
