format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/atmosphere/restart_dump.astart
  hashes:
    binhash: 65eb6008d83bdcca77b0e007586d6b74
    md5: 6397a46c3776fa76abd561c8d2cb454b
work/atmosphere/um.res.yaml:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/atmosphere/um.res.yaml
  hashes:
    binhash: bed39f6829a53f36a3ab259425345ac4
    md5: 619ce2eaf337e3e2d76d81ddc4cfb14a
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/coupler/a2i.nc
  hashes:
    binhash: e33d6d077c7f26a4498e7c1465b6656b
    md5: c58552d65983ab9338f2cf7fc4bdbfcd
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/coupler/i2a.nc
  hashes:
    binhash: 33f1ec9a8134f93f6243190f0b157a2d
    md5: f0e70e9d3a60a566d1d18b1e9f4c8edf
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/coupler/o2i.nc
  hashes:
    binhash: 3e318a6ea126e927692bd21bee1d3fd0
    md5: 428940c9c9566d1dc58be1a30dfb0e07
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ice/cice_in.nml
  hashes:
    binhash: d6bbe2b00e88f8c5803e211984ab8cc9
    md5: 27e137b8bbbdcf664f2dae09eb94be58
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ice/ice.restart_file
  hashes:
    binhash: aa746d94f55083a0e1a12df3fd7ef3c5
    md5: 8ff14618db24231d6f0644492931c468
work/ice/RESTART/iced.0786-01-01-00000.nc:
  copy: true
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ice/iced.0786-01-01-00000.nc
  hashes:
    binhash: 18c2c6591545f24e914b3ed19554c5dc
    md5: f29bdda38e829c643b8970365a5791d6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ice/mice.nc
  hashes:
    binhash: 6972ee7a673b2bbdcd4014a2702c190a
    md5: a4a74c30b58995b04e483416e345c8fc
work/ice/RESTART/mice.nc-01001231:
  copy: true
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ice/mice.nc-01001231
  hashes:
    binhash: bc8beb5084c930bc0e7a157d26e9adcc
    md5: 380a7008500f58eb5e8006b1eac18527
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_age.res.nc
  hashes:
    binhash: bf868a5ad455461c57faaadf0d4fa849
    md5: 5e94789a93fac0132f31a09b88a4f445
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 80ec09575870c80a81d53fa9abedb9a7
    md5: 46742643d39ed423a4402e885ee0f835
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b1d8c1e643ea14d8caab183971037b84
    md5: 598a42b5a2b9063037d57a9de8992663
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_density.res.nc
  hashes:
    binhash: 123775669675a362061498392e3585db
    md5: e3fc4d9258ac94c6cd14d18cdc0016f7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2db15331dbe3510f69a0620d54e21c33
    md5: 11417509d1f2d1875f7615f9ff6b44d0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 686462908a96e459ee64cafb7586e47f
    md5: b27546788b48c2fb087b238f854bdc1d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 784a5df4ed00ee7890a2e40305d33fca
    md5: f3665cf960ff7342746031e675c6970f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 27c523fd09157d79c6bdfb65a06ae1d5
    md5: 0c417f0eaed8d285d226b6a618702c3f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 530cb25773384ca3995e1674951d930b
    md5: 510f5ca6fb9e64cd02799dc919baae40
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: eebdba22961f10f781022c8ab695ef81
    md5: e79fdeb47e6d0f7d20847a1ded2b5296
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_solo.res
  hashes:
    binhash: 555b4cd22a9ad53385cee81f301ef93a
    md5: c2a0e6f64d3cbc016ca1c9dc8546f672
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8eac1909e9a2a7a6fa3adb3d23d5b21c
    md5: a1b2b75e3953ee2a287c1f2e863e2d13
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 29366256bfe280fd0790f11864351cc6
    md5: 6a0142332f9574aa00f4ed24305cf39e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_tracer.res
  hashes:
    binhash: 85887e20d49d9d9972603d34181f93fb
    md5: c52f00a0612dac2c2271f4f2c7e828d8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c6b21447a4e51456bb2d52529f7f8d28
    md5: bb2bf4ec7eceec6a8461d60b18d79609
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d671a10a79f881132405346d85f920c1
    md5: c6e2118ffcaf6ac5a5190c926399b765
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 64b57fe6233fd09f5df6e1d43f3aa81d
    md5: e3b5526e20f0227495b7375f753ebbee
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/tm70/as2285/payu/esm1.6/esm1.6-preind-202504-cice5/restart100/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 599285d5550397e244d22432bd2365c3
    md5: ad8657f697e17fbcbdc4ee77ab86cb2e
