format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/atmosphere/restart_dump.astart
  hashes:
    binhash: 36efc66cecf3a59a30c330d8cbb51e05
    md5: 78b381500fa39f0a920a66f940d9b0bf
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/atmosphere/um.res.yaml
  hashes:
    binhash: cdfc9403befd70a16669f7886d82b53e
    md5: 07e8d416cc9ddf266f4770451bbaf450
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/coupler/a2i.nc
  hashes:
    binhash: 3331f846b5ebcb995bfc86d51edad049
    md5: 3e32e0fcc2f067c34314d46597a6c667
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/coupler/i2a.nc
  hashes:
    binhash: bfb797b225e43571e0ee58c9bb3d22b3
    md5: fb182af969f2b8e6b201c4dd75f24c5f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/coupler/o2i.nc
  hashes:
    binhash: d2cbfc58cf5481dcb00c65d8e5e1bea3
    md5: fee1193a36fd628c638c355de4a821bd
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ice/cice_in.nml
  hashes:
    binhash: c4b45ec6890b6052e47eefcb59047dad
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ice/ice.restart_file
  hashes:
    binhash: fa06f5a988073274fe1219ece0499642
    md5: e665695241f8f0c56942f36c7b7038b0
work/ice/RESTART/iced.2832-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ice/iced.2832-01-01-00000.nc
  hashes:
    binhash: deff0ef8c68987a4c7a9cfe255dab538
    md5: 96f07dec9bc8da1c09175a459f56abb5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ice/mice.nc
  hashes:
    binhash: 606edfbdf8b4050c3461446c6cb228a4
    md5: e9b26bdce2e8ce8a8f2208e9f0b77289
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_age.res.nc
  hashes:
    binhash: f426e6534c9d6495c8afa3880c5787ae
    md5: 069e1de43f6352ce8619e4016cac37d2
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d8b92fdcf1281db40acb0e3c77aa7060
    md5: 8b8d93da1f377f5feefb2ce269b28b69
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 772cdd391c8718c2120d95ac6adf1af7
    md5: ee582e32cf49bca86708adef6f0510e0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_density.res.nc
  hashes:
    binhash: 29bd99e9840f01e1c8736a0792878dcf
    md5: a933dc25b9bcca06a503fa40901cf231
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 79028b02079d72a16c7d14f0c38e9c75
    md5: 619b67b5e304b4077c1e8ccf9c0a14a1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 37dfe3fa2768a4c7dd49a6bd1f30f4df
    md5: 014e79652a9cf013175a8c59826e073e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 460b3d0cf047e5c11f3a3c06c670f366
    md5: fbc117cc8901cf21fcbff5377dab0fef
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: dc75804198db3d7c63695c0048610635
    md5: e9bf1a5234e5e80071add0596d8517e3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_sbc.res.nc
  hashes:
    binhash: df578746de5261817ef3ca2531c023f3
    md5: 6e2968d928fc2be4d90d62c045425a62
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cee73f06fa1666a7b358bc41af32f84c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_solo.res
  hashes:
    binhash: 7c8ce86a1ab8251ef8ac2a55be8e4113
    md5: 9bc4394c8953602913d853cf1043f91c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: af236cfc101647d91a28b408b3f91414
    md5: 77bff05587b781c1d4d7431f4b3a2931
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1fa866188e6f8f8cf2fe13a19448b687
    md5: 38b15a21cf26650fa869963b9e9f160b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_tracer.res
  hashes:
    binhash: c6fee6a1084f9cbbf4f521e94118aa46
    md5: 06e739fbe44b0607ea7f7e9ad63ee5a9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ff48943f8e1e36497eb56f6b377ab1f2
    md5: e6588dc13a64f1583d6929ec9492b6b5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9c032a699e901a69ba594db721f0f73e
    md5: 203c4d62a2d1566d79effbcb44e99320
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b48dfa42cdd4e4804b90b5b07d569de3
    md5: baa1a68f5d301eb30342a5024c011b71
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart155/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 43dcf6b10410779f2313e520fe459457
    md5: eaf64d571e5d8ad3b14a3d250d12849c
