format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/atmosphere/restart_dump.astart
  hashes:
    binhash: cec1b713792f98949b9a5db77e27e69b
    md5: 781b8a9b398eb3e16a7a4c8068e5acfa
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/atmosphere/um.res.yaml
  hashes:
    binhash: ea62703e14ef4ab231df781f2a667dcf
    md5: fec5331d08d8f4bc809b0961bb556d27
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/coupler/a2i.nc
  hashes:
    binhash: 84aae2a6adedac27c158e40b7c3cfa1e
    md5: c532b4773aaaff7e860ae44533e7cbef
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/coupler/i2a.nc
  hashes:
    binhash: 380392291e03d4747344ef5c6cf6ba82
    md5: 9e41427f471616688a9968ad624ec05a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/coupler/o2i.nc
  hashes:
    binhash: cd0527d1c8ff4bca181324227d2c0306
    md5: ee18718bb080a6def07b611474bad8c2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ice/cice_in.nml
  hashes:
    binhash: 827dfcab2086a9d08f5c78da13354d82
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ice/ice.restart_file
  hashes:
    binhash: a8737e62795fd1cc27426307f6080cb2
    md5: a626789014c83870cbb42fc11171799b
work/ice/RESTART/iced.2800-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ice/iced.2800-01-01-00000.nc
  hashes:
    binhash: dd77da2502a84da0912a4d08bd49d828
    md5: e771dc43e2c775dfbd23ebd22903b27e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ice/mice.nc
  hashes:
    binhash: cb206f3fc83289ba6fbc60c3ef1fc59f
    md5: e3eff60c732dd8c53364cd1883700d3c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_age.res.nc
  hashes:
    binhash: b482213223cdd6dd027ac0302d1a290a
    md5: 894e81579e8a7b8ed3fba916e4388e5f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fa5d65aefa476820e3b778982450abe8
    md5: da9c21a79cb99b90915512f520f9f9e4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: d5f0007d33a3bd058b2dbb7cbd663054
    md5: 31bd497d7753a4c15f75b7ef88db9b49
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_density.res.nc
  hashes:
    binhash: 1759934482f8e1e4cde22586fd09b60a
    md5: a8410e42f93afc2e2d2b2f4ae3fe1084
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 52ef6cfe3149fc2909e804f9e277860d
    md5: 4c65b383693d8f63fdad32aaf127ddcb
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0d76acb546116cd60a5a53e49416c879
    md5: 7568d2f2e1a54e805863196f49e40f3c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0b8b3a3e647d194dc4579306a5f05045
    md5: 27e4186d59174a6a9c8b34b6720d470e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 60786d0a04a066c50f14499e7015eb83
    md5: 3ac764842cbcdfb5a2bca86b6d2f8a74
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4160e2ae6ac9890a2d55159eb278cfc4
    md5: cb8c3e68541976dc16505812bda19c20
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e9deefea03ff53cae14ef38766175185
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_solo.res
  hashes:
    binhash: 9a6cb50656d17b5b991ca5609b3f6f35
    md5: 8c4f5e685f73eafe2da51b3cb27984b7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5ca807c79a78a90e6e2db8696d4185c4
    md5: c3e94ba6ac5586f9685822067077c1de
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e03db9fa53135f258e82b28936dc314e
    md5: 068666e4cac66e14e227a9b66ee6fe36
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_tracer.res
  hashes:
    binhash: 588b32277452f949c200ef5ac9d97812
    md5: 9e3eb1d9a66d6aa3b0a6136a6f36ee91
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4f3cb11bf99bcbfd002538ecc67d38e6
    md5: bd3a0fdbffbc3ae348ded79219792296
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: de3c6c948015847e54feebb08d331bcd
    md5: b45f5f2889d916ce45ae31dcfd51feef
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1cbaf55201665fe9472e66656925603b
    md5: 7858abd4b62bb6ca897aa846f39ddf9f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart123/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 01af2a6bdd6e2f47dad66974a62e9a4f
    md5: f2f320c3a5df6e57cbe5c1451fb4f8dd
