format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/atmosphere/restart_dump.astart
  hashes:
    binhash: c243f245bfe44e55c2c39669cf962480
    md5: fb917f0b9585a95d53909555822fe49b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/atmosphere/um.res.yaml
  hashes:
    binhash: 5817e10b4cf4b29fb7e01f327ebc7f75
    md5: 86761410a871ab55375e474f925921ac
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/coupler/a2i.nc
  hashes:
    binhash: 569685b8b8eeae70f9ee05708b8be0ab
    md5: 816051302b0a4c7d55c97e74fb5eb2fb
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/coupler/i2a.nc
  hashes:
    binhash: 9735bff707d701333e6ce14756eb2dce
    md5: 27389ab1ad1f92ec47985359716a56d9
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/coupler/o2i.nc
  hashes:
    binhash: 9cba35a3e635ad271d201d1797c553ae
    md5: 8a7dbbd1b3cae27a6805dc2b45c90cae
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ice/cice_in.nml
  hashes:
    binhash: ac71df20a5584e2f9bd0a5356d5b4e50
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ice/ice.restart_file
  hashes:
    binhash: 1380585c9aaaddfa9921ed3629de9c99
    md5: 165b649c999297170b9dd27cddc49b42
work/ice/RESTART/iced.2887-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ice/iced.2887-01-01-00000.nc
  hashes:
    binhash: 421aa9d19e9995f0d38dd1b151276dbd
    md5: 741fb20579ad01382b76208e798eb254
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ice/mice.nc
  hashes:
    binhash: d8d59933e3669ec870106f536720a0ad
    md5: 11c2e2decdaf8b6bd30251e599b2d0ce
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_age.res.nc
  hashes:
    binhash: 4a38f4ac2a97b66ba49e6b01b4c449da
    md5: 6f19631bfe41c9db120ccdb8ed2dfd52
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d865dbd98b38448d617ed063a35b78c9
    md5: 909307847ecb589087ccce7a3f382664
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 50abd754c5faa461dfe1b6a7f29bce74
    md5: f32b4cebe65cb0722712cd6eb4f2b508
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_density.res.nc
  hashes:
    binhash: f7fbf8ac5e7d0ae6eb11a2158adb701a
    md5: 42f123c04f52ae422357a7ce3ee59d5a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e06fce180a4224a62b3358724f5deb4d
    md5: 610da1d6b29850a686ea4ecc83966fb4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8b10b03daab048067cc166a91a9edcd3
    md5: 6482a7f232b99c0754693483c79181e6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 67757966b9771d7ec9b4970def57bb48
    md5: b0dbe2ca41cc4739fd4c410f73ebf0ac
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b5a45c5f70f7287b225d64b1c59dbc84
    md5: 055eb5264b4527a8baa040ccdac06cda
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_sbc.res.nc
  hashes:
    binhash: fadb22b1e85313152bd356de7b78f308
    md5: 7e76e0d208cdbaddada15bce077eb7f9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a210e42e080c41dcacd9bd2b141d145f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_solo.res
  hashes:
    binhash: 3f0271240fc4d149630ceefcbf95b125
    md5: 1475201d9948369f055496d5e1f980eb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: dc60e7b036c50defe119abfc8cc8a4b3
    md5: 41f7eb623e78ad50d610854f65a744cb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3a8703551d4e8a68561a7f6b2c0f64ff
    md5: dd7c56981fc201ab2322d66672815320
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_tracer.res
  hashes:
    binhash: daa959885d9b79959278167899f8ea0e
    md5: b603088bc4775b621b5b27bd3e03e5a4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_velocity.res.nc
  hashes:
    binhash: adb87fb5fd6b801da6fb961ede19900c
    md5: 9f55114fa49e6d284b489c543de78955
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3b3395ad5bafa1f2fdf21ba54552fe60
    md5: 728ceb53c75653a624b426a122193a17
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b2d595777721e46fd1fa2829bb4a057f
    md5: bb893a295302d8021efbb59830d58120
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart210/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 084470a68f7bb035d0bb3cd7fad3954b
    md5: 23b770fcc1612ee9d16393631e091259
