format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/atmosphere/restart_dump.astart
  hashes:
    binhash: eb57269bb522bbcc94b071db4de39cfb
    md5: ea702f562d6716f1a2636201ee0b4b87
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/atmosphere/um.res.yaml
  hashes:
    binhash: 54a09ac2b4165fdd0e4948527ed0c665
    md5: e75f42f2060aa62acc1545a7029dd848
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/coupler/a2i.nc
  hashes:
    binhash: b3a0b6068af12ee1a97a48adde91e9dc
    md5: ce74ba8c84944cb702785a29de49c8f7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/coupler/i2a.nc
  hashes:
    binhash: bf895f9c42bff4b53d2eddd44f60cbcc
    md5: d9c461f276e66cb2699af686a04e9fdb
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/coupler/o2i.nc
  hashes:
    binhash: 45e40ef84835296f3966b7df0769db8d
    md5: f8eb651079ee21e7cfbccb69b38aff01
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ice/cice_in.nml
  hashes:
    binhash: 0d6adad961e8b8482525045b70158066
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ice/ice.restart_file
  hashes:
    binhash: 519c5163d2dce08757a87fa5e91bfdc9
    md5: a50f8ff7e07f351bf70561df50d14c91
work/ice/RESTART/iced.2727-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ice/iced.2727-01-01-00000.nc
  hashes:
    binhash: 21dbaf4f180959ff190eb915c7193f8a
    md5: f3c14401333b5956cd665a624e46d45f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ice/mice.nc
  hashes:
    binhash: c87e7e805fdb159cb658b85f95cc06e8
    md5: deed4cdc6f4c7f8a3e1e049910a31239
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_age.res.nc
  hashes:
    binhash: fabaa0117f96af18d90deb0d8581aa04
    md5: 6187ddc5e861d1f558228feb5e78415f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 74f45c223cf3936be2b9784384f8211e
    md5: df02cdf7b20f7019db6889fb756a3151
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: db7d98326d45cdd5f12564dbda0d6d7a
    md5: 7bed247368006298ed0e5aaf0012e787
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_density.res.nc
  hashes:
    binhash: 87d873a106bfbaa6ea44094207837836
    md5: 2ee5a7e73cf7ca67b34f10b4a87336f8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 82c5999e766c4cfd9e2ea6d2bc139765
    md5: e9b308ed6e218bad92d4c2d9faf32bf1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6e0a4ac988d4820d3312ffa70924ac16
    md5: e31de1570d86830d0228134a980dffc8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 79ee7d03c1243aecdc796b31997cbaf4
    md5: 0a33b3eb02aaeab8fa816af7b60de7ae
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 96c749de85403c3bbeebfca875d4e609
    md5: 15318b80e4bc6b6fb95b1c87a8264116
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 182221fed6e202d2c175bc42e4f33fd1
    md5: 9f53400c8e25fef3ed1827528954cd26
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c131188db47192e7ee078dba7c0a67b1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_solo.res
  hashes:
    binhash: 7587b564dd852e9c5777094fc3a2514e
    md5: dd7290dc91d3b99e6a7996dfe5916de6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c6947e4308e911cfa18df222a406c07a
    md5: caa83e2668f9305095da9428f354ace0
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 99de335c05993df2e31295feb17fd062
    md5: f41c472ff824cca59604195d314a91a7
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_tracer.res
  hashes:
    binhash: 803316c3d257c811775d44b3cf20e157
    md5: 32d4c78080d410f8f6537df69ddfb110
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e3a301b966cb5c0b2347ace92c57bc42
    md5: f679457b40be9f6b20f77e1328e9affb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 668bc4db0674206ea70a4cebd066f1a7
    md5: 1808d77e9d0aa5d0fe64cba091532878
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1d5d00d00189f464359552d8e74e81c6
    md5: f34fdda771a65517d48cb8b014dd989c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart050/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: cbe3ddbd0208204de65c5cbf5eec45ac
    md5: c1aa7bf1fe334a2dbfe7fee713b5480d
