format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/atmosphere/restart_dump.astart
  hashes:
    binhash: fcee241e2db47b20643d140f883bede6
    md5: 3652a16db65cce9a72be2c30b767a84c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/atmosphere/um.res.yaml
  hashes:
    binhash: 73e6911d80f5a7ee7dc72b5d1de91bf1
    md5: bac38f330ecb9d912a37426c4bc79e8e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/coupler/a2i.nc
  hashes:
    binhash: 47823899b7533e4a4737b19f53102ee6
    md5: 49114739da98e68c29997610ed7906d9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/coupler/i2a.nc
  hashes:
    binhash: 066adc7568470cabcb0ca9ad0117c3a6
    md5: 0b230a260c481db5c9036a69e7c5ee60
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/coupler/o2i.nc
  hashes:
    binhash: 54e03a1b12f10c623f64c599035979c8
    md5: 74ac8d400d7d633864b0b30fc85be29b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ice/cice_in.nml
  hashes:
    binhash: 890dcaab936fc76b2413ed2bbb7094a2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ice/ice.restart_file
  hashes:
    binhash: f943b39789709e374fe405b90d7fb2d2
    md5: 2627606cd7911b8778bb5711f173c983
work/ice/RESTART/iced.2863-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ice/iced.2863-01-01-00000.nc
  hashes:
    binhash: 9298eb69501870f93f6acf8c2bb6fd73
    md5: 70bd91e9106e19414da49a5222d5d4dd
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ice/mice.nc
  hashes:
    binhash: dad232d1ba6861951cd3f6d3ef06f5f6
    md5: d44d9c4ca728e2a7716b11b7410cf102
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_age.res.nc
  hashes:
    binhash: 6e0f6dcdc6fc69ad7c0d5e379c77c0e8
    md5: 53f75bbbeb301b5053fcb7cb2cf39fa1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d0b8cd453c5a9bf9183578343830bbd7
    md5: d47ef36f1a82091811d2e20eeed9b9c0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1cbdff24c3ec33228bd49142baebe4d6
    md5: ec1fd3fab409cd52e4c509e8add44865
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_density.res.nc
  hashes:
    binhash: 5dbc7a3cd1924a2ce241ca906cb79c0f
    md5: 41b26fc6ccaa43e9d3a6ed5707753746
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4bc080dc98d8c656a53d5c2b82c001c5
    md5: b709d384ffd01b0f041b0da2965a11b4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 190d374860b3bb6c4732d87b0902df9d
    md5: 1efb6e214926c219c7156cb2481b48d4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3fc0dffe56f3d1e6facda20c3b407463
    md5: 73cc2da71707d13822215e27513deb8a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c48d0345e615dc8a5489e0931d2f3f13
    md5: 767dc72de213fc61c498cb614a9220a5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8ecae58b87c5d41191115bd75cdb2c67
    md5: dcbda691e988abc95f7822d1de1a7add
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1fd4925d032c7cfb5c2099905a18c55f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_solo.res
  hashes:
    binhash: 636bc2393548e68bfd370404c7460963
    md5: 4e5de04f40e4bf7b0f183ae044422639
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e4d44ab9d92070f7f20c2d3008ddd520
    md5: 9959bc6f1ae7d84eee3f1bb7cfc8d6b5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1da5222bf5f04b39f2e059345d7faa43
    md5: a90a80d10b4f11eb8a0115a0313ef7cd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_tracer.res
  hashes:
    binhash: cfd8a464cbbefea598b1a0391fc94d67
    md5: ca8d8d9133fb439c31d5043f9eb2a4bc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4dc2795625e5e80fb1ff522bce481b72
    md5: 383aac2d73f200c10c503bc0046378ea
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f4dc57c3d0b19e6b53de56b3357d6475
    md5: 361df1b335763ec9fa93cb64cd23f00b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 510cd97956641d379d206250417ee56c
    md5: c44d1297d7688918accc188b38c1a40d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart186/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 95ad0669472d09d821461ead63a5a9fd
    md5: 569d31f0212524cf44423487bfe729f4
