format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/atmosphere/restart_dump.astart
  hashes:
    binhash: d0cc060eed95ce81d47beec6a8a1b548
    md5: 4b17af4cb20df1caced8e273a95a3be6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/atmosphere/um.res.yaml
  hashes:
    binhash: cae0c2ca681bd192e17c3bd77f1e71f0
    md5: 7fe79b4b606c9ee178096a30e5a88dc2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/coupler/a2i.nc
  hashes:
    binhash: 2045bff5abcac8ba6ac481b70ac22d83
    md5: 7d37997539ffcbf17149d1742922681e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/coupler/i2a.nc
  hashes:
    binhash: a4bb3899497b1ef8323ead491cc6bc87
    md5: 9753c7d5d25c5781f06d9359e880985f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/coupler/o2i.nc
  hashes:
    binhash: 72fc219453a910f23c3b8901584ec815
    md5: 0fc10476da8876842fd70ac391262421
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ice/cice_in.nml
  hashes:
    binhash: 867bab3eaac4e973ce16bedb27904b12
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ice/ice.restart_file
  hashes:
    binhash: 4a3c279902496c7f464476faac8fd79c
    md5: 6747d12a1ff4cea7d363b1ec01dcec1b
work/ice/RESTART/iced.2731-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ice/iced.2731-01-01-00000.nc
  hashes:
    binhash: ea11bcecc9b0124f48de2f508900d381
    md5: a8e5f250e9d5de22f8acc3998cef91a4
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ice/mice.nc
  hashes:
    binhash: c444a5b0360d9d6589bc34a0db752d9e
    md5: 872273d0c957fb7b68fa8abae6df5adc
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_age.res.nc
  hashes:
    binhash: a7204ef361af52408883ef4d55142470
    md5: c3d29f20d5d3bbfe7c7d1f7d757e85c2
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b071fb05c80204212a798f43ed22287b
    md5: 21e8c3766b08cb4d7ba80198de3d83e7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 731e68fc459343d77fb036dd1afdaafc
    md5: b44794235bea3bccaca4613cc4178124
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_density.res.nc
  hashes:
    binhash: 138d01831db53ccf019999fb687b717f
    md5: 457208875adc510646e04e23bbe6451d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 33140c36d21c8e8a4edf57971a21f7fa
    md5: 1c230e0d8fa551efcd4459daffd97d43
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3881ad444ff4dc0e031bc57900f4b9dd
    md5: 968fab6c2b3dd472cc80d479a2e4cdaf
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d86ee8d04f695983b8ff44636a3f86ce
    md5: 7e505a1aade6ad9d5dd92589f0a30fae
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c19ce0103e6efa2adca3a152c576533c
    md5: 9b33f7a0c2113b0191574c1ccf5b412f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c63409f4c5fc3d97de9e2dcafb36400e
    md5: 75b14784601ebbccd97375f7622c0b77
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c9ac92f2aa59509618a93c87a9cfb4be
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_solo.res
  hashes:
    binhash: 09a9dd5ee7a93dca7f63a71eb9723bb7
    md5: 196495b8e9ebf412d288adfd69afec2c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0b9df8f67770930d447cec3953074a74
    md5: 597ffa5f1474db8df2f2275c43a93a60
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1fbb9b1dc52ee8ed2a097b15fd1cadc6
    md5: b018808c61bf567317c0b452e8bfac28
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_tracer.res
  hashes:
    binhash: 9bd5869a7b2748cf46ab765d8036d40d
    md5: 664fa53d1012238b9338e81bdbcb2c64
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 25a8cb7447b51a7e8fd2cf34696c8631
    md5: d6e9e070e01d7499037026a5f25faf3c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f9041b66089a3a0ef8159238378b8b93
    md5: 4233faa155df28c359b2b0833b3b7a22
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1dd0c9d84303eb9697b2019b2d77b671
    md5: 70a867405362d9e9645686a6676cfeaf
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart054/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2cb57ad6b76ece616108a4f44dd7d656
    md5: ad1d87f735b0a92b080a5d9bb639afe3
