format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/atmosphere/restart_dump.astart
  hashes:
    binhash: a3eb395aae1a2853d8d586f0ede728a0
    md5: 36be095ec4f834f992ac48bd50df4075
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/atmosphere/um.res.yaml
  hashes:
    binhash: 595e31e69a9fdee53dfbdc8955ae18ad
    md5: 7203ca095f7657fbaa99f5805282ccb4
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/coupler/a2i.nc
  hashes:
    binhash: b64ae94cf78e6b998caea6d0aface315
    md5: b7d946cb939a8a93fd2ac451c8a7722f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/coupler/i2a.nc
  hashes:
    binhash: 4903b4d797a993271a22b1a2432296b6
    md5: 18705b320e6177fb791b1c435b4a40ad
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/coupler/o2i.nc
  hashes:
    binhash: 55ed2ae5d4fefb312939f2a0060c9b11
    md5: 7c864641e450e1cc03d52b8dbe2b1cc3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ice/cice_in.nml
  hashes:
    binhash: e8bd7f252791cca62e429ad9c222388b
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ice/ice.restart_file
  hashes:
    binhash: 11c593ff20851a671109f9a93193908e
    md5: 342351f1cae85260e2b715566bbae119
work/ice/RESTART/iced.2920-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ice/iced.2920-01-01-00000.nc
  hashes:
    binhash: 78146ea5b44245a914c2982529ffc7ae
    md5: 1009fa79168c14411ef54fe588d43b8d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ice/mice.nc
  hashes:
    binhash: 539f58017868fb2d6bd214c82253bb5b
    md5: cd4ee2fbe3c6e95c20838aff7b3942ed
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_age.res.nc
  hashes:
    binhash: 5438ab358d804084c820d36fc4bacf17
    md5: 208a9f0388e534d1c8f2982c1c723425
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 985a6847f41447a84d2175978ea961cd
    md5: 0f958a6b57b9f67aafb63973c5716ac1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8658a8f65504502fa716c72cc758c088
    md5: 91b1b08c23b142f4abcee1abbf14c240
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_density.res.nc
  hashes:
    binhash: a7eac03c10c58a23730310299cd2d038
    md5: 19f7f1b073a43024a0847bd35626faa4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9c3bd8c2e524cb86e19c8f14bcd33a3a
    md5: c01cdd07dd016ed436239fc2641f30b0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5fb504f1f48dab761109869301f1ba12
    md5: 71eb068b6fb8164d48fe054cfe9a584d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a10a1a4ddd8a2495d1998bc3ff5715fb
    md5: 67f898fd3f5bdc63ad8376709b694e52
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 35a4e91cab45cbe896549836469f3d1e
    md5: 283c2612f1523633e0a8d21a94d13db7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 46eae557cd2e05a2e6ae31e8fcf0f9e9
    md5: eaf331495e9c0b520b21e402312fdd9d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b89c162b0125a8be9dccd6b4ed71b688
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_solo.res
  hashes:
    binhash: a91ae8c7a2d7df77146200a73002dcb3
    md5: afe811e41927e8aaf01abe7da5a26e51
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0cf3b0edc0784ffc4ae64e51ceccf8b9
    md5: 74f474265a2378208f8b83965e52cb30
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 79b7e8286c35aaf25b98a5a166795ead
    md5: 7b0379e890c1a2b7b3cab2b3a7603ebe
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_tracer.res
  hashes:
    binhash: c93331de48e87b9b989a4c8f084593b2
    md5: 8f739026cd6907fad93bfa956e36c5f1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c684ad7edccfe800c6a6ab1d7df3eff7
    md5: feb6c7fc5c5afea8492261aeebe443ef
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4943936a384297cfe334cd4dab5d31e1
    md5: 7b0348621c02392d1b634adb59266069
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ac15c320f3c4a5533105d8d9ab5a5cb5
    md5: b210a074862b5440c4cfa9f6428610ea
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart243/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b45cabb4f5f6fd7846573c9ac63e552a
    md5: 280eeb8c108674fe5ee019c5d74b1358
