format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/amip/restart/2025.11.24/atmosphere/restart_dump.astart
  hashes:
    binhash: a208dd12212375b20f84006580c908f6
    md5: ec6e99863b74edcaf7593ed8de16eb7b
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/amip/restart/2025.11.24/atmosphere/um.res.yaml
  hashes:
    binhash: 2040e85136929bf2b14b9f8f7f79ca13
    md5: 2040b7490b72ee39c2693667166461e3
