format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/atmosphere/restart_dump.astart
  hashes:
    binhash: d0f34f54958adc300c9d73742f00e8e5
    md5: 1b84819dbd8700c522c6dec2ac4c1152
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/atmosphere/um.res.yaml
  hashes:
    binhash: a181b97628aa20088f0d50554003da71
    md5: 098438dfb778c678d821ce6c1334f374
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/coupler/a2i.nc
  hashes:
    binhash: 4c07f8cfa739f4e56f2de691e2ca6bea
    md5: c7640c9305b96dcc49312343b8a67c73
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/coupler/i2a.nc
  hashes:
    binhash: 39ed243c1470dc0dba6bf724ade820ac
    md5: 6892a11cdde4d1c2eb5871acbb251a3d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/coupler/o2i.nc
  hashes:
    binhash: 3872669476c40fd3454739a4fc043d34
    md5: a8a2a137d3b8a17d468e1c1ed2de4737
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ice/cice_in.nml
  hashes:
    binhash: 5fd5bc23cfaba6543f4b9d5983b269ce
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ice/ice.restart_file
  hashes:
    binhash: 3768587e724a88af7c28ceda32ddf5c3
    md5: b7770f5cf06ccae32aab7021fb789898
work/ice/RESTART/iced.2743-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ice/iced.2743-01-01-00000.nc
  hashes:
    binhash: 409d9078f46275f7aa985ba23a9ed21c
    md5: 7650c49d448738fff8f46f50b3d8050d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ice/mice.nc
  hashes:
    binhash: 08803553e51e6be89d1b4aef8f72f71a
    md5: b46ad4a50d9701944919f213f1e1d866
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_age.res.nc
  hashes:
    binhash: e231ff7c4d09f6ff22e21019a17bfda4
    md5: 4f91ead47b07c796ba8e603eaf1e6d05
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6ad50954ad8d3c68eefcd67cfcebbbd6
    md5: e859f80f42ec8d49fa467d7d70464f3b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1dfac237307797be4cafeb9cbec6fac6
    md5: f1163eff99351db6cbe66b6e8a5886ef
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_density.res.nc
  hashes:
    binhash: 034ace3b70d0bb2333cab8de4ff7ce30
    md5: 7bcd0eb4ce099014f15370ed4a6d9643
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4ce35ac1dc9d05f4fd64b378e60d380a
    md5: d455490025b7bc6988b7dee6bf2843b7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1f73d6674be5c1af1327f428c07627c2
    md5: e8467de086997cceb93072b03621e4f0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 93c43aa1cba3b88945670f5845f92d19
    md5: 7373e1d36a24a6960d246f42b97adfdc
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 49876f80fd2bb14830d246ca7e3c7afe
    md5: d3d10bfd0403893c3c735fac41d76d9f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 99f7294b05eced5d03cf29259c099ed3
    md5: bfc2d57f73e58b93d2f349750a593b90
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 86c4a8ddf6263ef358b48d1f65ace873
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_solo.res
  hashes:
    binhash: 63624fd3ca7358706727a7ecf48130ea
    md5: 0d82665db473d9b56d6a8f95b0749eda
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9beeff36a79fff78fa79cf594b688c7c
    md5: cecd1cf6b62a1c84c2e2421e84e34921
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e732af3dd2b5b8a95272649f3c7cc9a5
    md5: c907ac1a788f168cb7c2f951339d3dd3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_tracer.res
  hashes:
    binhash: d69e457b1b855a57b4a6a69df542fab1
    md5: 25e9e8caa806904a5b98b3bd865f850b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 560cc9e1c963b2de39775eba2a357a48
    md5: 1eabc1ea9c6613038b1f48db2ea1497a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 546dca3db06df1a66dd2b9bb71f9aefd
    md5: 4fb61ab9ff39a32d0a82b517c6b7654f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: afa1173194b02b02e2b2b1305b6ea929
    md5: 66bb46d804e9b3b907cc92b492484f33
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart066/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 033a62c86f23b3438e8e8dc3c04197b5
    md5: 35f0ae955f42d151e595a213c5daf026
