format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/atmosphere/restart_dump.astart
  hashes:
    binhash: 16679343bb0c99cb30632c9b0e2025b1
    md5: ab897bc03500c5302402ae9330c495b5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/atmosphere/um.res.yaml
  hashes:
    binhash: a26f9baf08074a4658e6468b49da8b23
    md5: a32e3a38d8dad307a4f303ed71cbf549
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/coupler/a2i.nc
  hashes:
    binhash: 4d804ed84212ad32fc5520f4eade89dc
    md5: 5a61a282cee6db24d8aa617a6a159f13
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/coupler/i2a.nc
  hashes:
    binhash: d5796c8d7558147ea8c4d87801fe551d
    md5: 48812a1e3c0ebeebf36a8c47c271d6ac
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/coupler/o2i.nc
  hashes:
    binhash: aa982a2fdea6697fc609c6f79a7e0913
    md5: ea404a9451c67061aaf4270a2cc96c32
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ice/cice_in.nml
  hashes:
    binhash: 90a888204b2381fbbf5cfc264a7d6293
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ice/ice.restart_file
  hashes:
    binhash: fc9b9fd1f9f2cfcf304fccb5a846f34a
    md5: 2d95042b27604c9dfb91de4e12a03a18
work/ice/RESTART/iced.2885-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ice/iced.2885-01-01-00000.nc
  hashes:
    binhash: c94db13cc7aea5b6e30bf6fa10ed2df0
    md5: 588781cc97a315003ab17fc7076fb427
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ice/mice.nc
  hashes:
    binhash: c544575ef5a42d21796bc0b2bbdab802
    md5: 49bb03b9bf9d30d93e6872f6f4631a2b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_age.res.nc
  hashes:
    binhash: 49e48c4fa86649e2480db86c7ac23de5
    md5: 787c17e43037f722e02b3a6440a6d86d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9308d6957728aa26e4d81ad07feae6dc
    md5: 789933e8fee2a5d8440feff7003f7f42
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e10a826d372e24618bc89669c8d7ef71
    md5: 4532f78fe7604ba2da8197220506127a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_density.res.nc
  hashes:
    binhash: 5c70b58171ed2f2e0c2cf96e3c220676
    md5: 539ab787fbb533064ad16519dbea2765
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0915d86b2df90733cacfd8b6fd34576c
    md5: a26c4dfcfbdc4948cf67b47d1602959a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b0f333b2546b3419384fe4de0de4c2bf
    md5: 6784d58016e2b338bde50a82de28a4ea
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1642b8a64eb549fd466840cd74a684f3
    md5: 651fca6c88d1905a5f50584fe9d91a16
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: aab05566e9451b0c176d6f4e816f346c
    md5: b7bea11b0241618210c3bb7a569cd9cd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9f6c1e3b2b0da186ff906a1284cd6246
    md5: 5c5a35ce21c891f998acb75e662d7a79
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e8d1c74ffe02a436e47904df21ffd155
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_solo.res
  hashes:
    binhash: 495ca115ba885c90e7ed1cc507dae6b0
    md5: d84a23244da5fba5803debd114bf270b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a9da927d803bd15ad41ce53974b02d54
    md5: 53046e49ea9e0ec6c451bd74535c0d9e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c4c234cb7e75aa5a3fed2c798efa4bbd
    md5: c3d904a2b76d47613467e8b6979f40ae
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_tracer.res
  hashes:
    binhash: 00a65cff48607a6ae5179fd4a25015cc
    md5: 2490b9682cdc5ca4220eaaf4b1fddfe4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6a3fff511338287cbf44e4ac4adfc91b
    md5: 2f67459c182f9f5eadb0d1f684d6f6e9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 36bd0a6f5de10f7221e5bf84577d0d60
    md5: 499f2a01dd49f38c5e894682bf66962b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9fcb3aadf0dc0537b7bc901ba224fb42
    md5: ddf6e59ed4e45f7bb6e590a552f34c37
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart208/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 099ee13599d04b8fefa4a41769026f80
    md5: 9fc9f274b53bde8e8b7e2d2beff72288
