format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/atmosphere/restart_dump.astart
  hashes:
    binhash: 58b95166cf52761d5b263aba875319bc
    md5: bf537f5c1cccd9e8b7c3870e766c80cf
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/atmosphere/um.res.yaml
  hashes:
    binhash: 04318e12d01956afd4403512007ed424
    md5: 878b1be1f5e3b4d03794e15666ee3ec0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/coupler/a2i.nc
  hashes:
    binhash: 4c742a7f2954c4337c33d91c1f643513
    md5: 761c61a17730b5e7918d10ece9b47c99
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/coupler/i2a.nc
  hashes:
    binhash: 5e073e793c9cb9753b207f2b43d01c7a
    md5: 830bdbbdb56cf53dc97e51bc05eaf058
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/coupler/o2i.nc
  hashes:
    binhash: f5c58307552ca669011cca8760cd7882
    md5: 5159797d5ebc1d5d28a6daae7435bd73
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ice/cice_in.nml
  hashes:
    binhash: 33f0f4b452ae4eeb24ff414d0ced0e2d
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ice/ice.restart_file
  hashes:
    binhash: 33cd36232618db349d271cf06f89d6ad
    md5: 731b93a789ba7f685bd79518febb90e9
work/ice/RESTART/iced.2849-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ice/iced.2849-01-01-00000.nc
  hashes:
    binhash: 8be4400550356f82d87f0c3d0c31bb8d
    md5: a373504d2a8e5a2e31e2f333f69bd8fc
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ice/mice.nc
  hashes:
    binhash: 99368450edbde350a64ba4064b4c6d72
    md5: e0fc91ea543996241ed0aa108f327b9b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_age.res.nc
  hashes:
    binhash: b303c8cd8c71d3d0c33f5a6f37a9fb86
    md5: 2bf413b889ea3438c6ddc7fe92be8d04
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f83a826346b070346d617ff316cd6dce
    md5: e0f8e2f370a66c910ce7bb68f718a994
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 177f97ca9d0b39372881a5003c4e0405
    md5: f62758df88f2b5e859acd63b4ddaca16
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_density.res.nc
  hashes:
    binhash: b096a544046b03ee3a41878a482392eb
    md5: 7cc5548662a0d0f653ad8f7c9cf51b57
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f0d38ed81401536ed286e6dd39ab13b4
    md5: 5fc645869d8fdab5baf1d4414c4a7c81
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3835e1a529f93ac099bec0cee71fdd49
    md5: 22d53e16ae91547c010762baca09fc87
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7e774fde9865b23480b1fea21b9a9ce7
    md5: 47caaebb38094a1a184e005fc07165f8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d3af36d4d4936fdc20bfa66761f2585b
    md5: ae9386f3b36203f3983c1eba360c8173
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 01502e03741d0240544b83ab97adc07c
    md5: bfd146ed64fae8f9bc65d6b07ec5dcef
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 81bdb07db69d751655929842aedd8be9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_solo.res
  hashes:
    binhash: 61eb880c2a57eb87f865e9ab69dc59e6
    md5: bea22d89d30cacff58322715198e4d9b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 418ada2f14f9aea54d29ba498a3765a1
    md5: 0d7a2eafc9f9cf0eb3042d29aa9276f8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1112ecf679923377956136f3bb58f00d
    md5: 9756b9b67899cdfbf69c0388d5d29c85
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_tracer.res
  hashes:
    binhash: 5b2adb2310996ffc6988116327ea5314
    md5: 643eed5553c4917635da947eec9a4203
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0ebed67530b83e54ba187c155307b20e
    md5: 752af622e5d2d6367fe49c5ca17ca70c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 86df829e8fa5827d1dd6a4caf3412233
    md5: 25b385a2fb59b8c41bc5641c4b147ba4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 98935b81501350bb1b81ab91b473bf9c
    md5: 0ff26edf23eff978a4a6341cd6c4a90f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart172/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a88c2df10957116161af4406fae0102d
    md5: 7159ef8f48cc90088784f85f36815260
