format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/atmosphere/restart_dump.astart
  hashes:
    binhash: 3b791df69261df002ad29dec71e8e97f
    md5: f3ab0d9d27c54de34bf7eb20ec3298c7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/atmosphere/um.res.yaml
  hashes:
    binhash: 1f7d63ffb19137f176dfe8a6be4e013e
    md5: 473f64b5e71a680ab8eb248df6c2bd5b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/coupler/a2i.nc
  hashes:
    binhash: 2cbf4ef09b91d5715f39e6e7ed15fc40
    md5: 9461256fd4bcaee157e7bd288766f1b7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/coupler/i2a.nc
  hashes:
    binhash: 0bd93d5f5b4bf5af1eb2558aeb6c6c1c
    md5: 8bc634bbda6011508ab1d0f8e38c04cd
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/coupler/o2i.nc
  hashes:
    binhash: fbb051aa27fcb2b869cd3ef0ed9bdbda
    md5: 796681d0b61f93512bc795824fb85b5b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ice/cice_in.nml
  hashes:
    binhash: ea58cc4afe92620ef46b3c0de63fb05f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ice/ice.restart_file
  hashes:
    binhash: 753b010081df7d5af09c2bda4504d491
    md5: c1abfd57707064a9578809d0190a6063
work/ice/RESTART/iced.2681-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ice/iced.2681-01-01-00000.nc
  hashes:
    binhash: a79e748464d0c6d12065a116288d9a15
    md5: 4eb407675c919ca728cc932f23281840
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ice/mice.nc
  hashes:
    binhash: d2764674ce242f04c79bf74501811e94
    md5: 9c9932f44e53bffc5199693fff4fbd18
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_age.res.nc
  hashes:
    binhash: c8cf4fd32c0f1b842b892a0089b8ebf4
    md5: e12a1a76e17f6ec4177556b56797d121
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 90f29eca15de061887e79bc5848ec377
    md5: 34811c8e630775054948cfba1b39a498
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8486b99b4e56eace5df504f70d0660bd
    md5: f97d0221944f393596959089d9896f83
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_density.res.nc
  hashes:
    binhash: 0ba8ae6bd29b0ef1519a9e17d90d2ef4
    md5: a049af1cf6c6c27c79d7b16f9cc5c43f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7c817271d5f8f3c343955db0fb2dc2ce
    md5: 9a6d6db0942ae54fc9c70e601f18222c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: fe1a14bb6d978d5a18ce8796305205d9
    md5: fcd5ee2ee9212e8d13e91b9ec5b6ab87
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_neutral.res.nc
  hashes:
    binhash: da3f9dd1862810a95b97d8e096db7baf
    md5: ceb028dcb3325789c29913603df88703
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c5780d1266ce108f4e45d3b8b36293df
    md5: 00d781f10d41320e929e083aa11b66cf
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a7d0e5a62fffc4a93a9085c9a09be713
    md5: 46d24c27dde82f6ad8cdedca10cc8c1e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 83ff23963438872a508677a24f602225
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_solo.res
  hashes:
    binhash: f6a87080e1b58d081ad817d59893e4eb
    md5: acda07ee748063419088f0c9932bb780
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0a04da9c82dc7fead068ce3180d4f8b5
    md5: c254180cffda37589167f41cf2612a63
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1722bc9a76f8cdebe386ff27dfe134ad
    md5: 794b9047d4298f84bbe9237aad870a25
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_tracer.res
  hashes:
    binhash: 8f9eb6714caae10c14e2fa3d5695e33d
    md5: 0b8f7ebdfbf669faa28703dcb62e6864
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ab4205daa88c7152ec903edccd913b2c
    md5: 4a3056d779d9af403a5d5aa1a0c99a17
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 28a8b5cc809bbdfeeef29ef8850c126f
    md5: 61dba9abd181d9f1eca186ef82460dd9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1d24ba704b285b888eb6ce22f469d3a5
    md5: ab197f32c1ef982b906e2f9fac61bbcf
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart004/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 32678dec42de159ce6d032ea81059a38
    md5: e673455d0ddafd6cef9b966c0a19b5f7
