format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/atmosphere/restart_dump.astart
  hashes:
    binhash: f570d8aa32c359eaa86a4d672a762b05
    md5: 00f3f3be1afc31a6d599d203ec46d6ea
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/atmosphere/um.res.yaml
  hashes:
    binhash: da632fe411612a63d28c685572fc8f73
    md5: 32b98c12ce0659584679657b77199d28
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/coupler/a2i.nc
  hashes:
    binhash: caff30943128173cd87c6b2e55d97c2e
    md5: 5d788e46b7f9fbdb86e45548c58cac2a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/coupler/i2a.nc
  hashes:
    binhash: 4cc9a2e310e44ee8f4e12b920ef86fd6
    md5: 365b0c1050a397012cc8774496a3c334
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/coupler/o2i.nc
  hashes:
    binhash: c9c1c0a3034f79d9bc84a4725e8d9d5c
    md5: 7a49fc5758f5647089ce5c73040d14a0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ice/cice_in.nml
  hashes:
    binhash: c20e2b61c720b62b6fcb8dd94c851608
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ice/ice.restart_file
  hashes:
    binhash: 4348711f8b456bf23e6e5363f75d589b
    md5: 93dd88b50ad535fbeb391ad94a778b9c
work/ice/RESTART/iced.2714-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ice/iced.2714-01-01-00000.nc
  hashes:
    binhash: cd423f27de1c8bc018259aaec34e47a1
    md5: dc0f829314c6888d104281b0dd5ca05a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ice/mice.nc
  hashes:
    binhash: 36cd16c1e5733bce0ecfef9991bb4928
    md5: 1f441b314f57c8a40d239626cdc2b69e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_age.res.nc
  hashes:
    binhash: d56eddae019b97138095acee897152d7
    md5: 4207051be079ce8d8f19b3aa9a010e45
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f9f549b74db24aa12c05ca6462e4ae07
    md5: b27be30b376de4df0c961abc3bd81f2a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 108e4428f0d3bf112b339df1b1ba5011
    md5: 2c15d9f82912861b56356c89a629087b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_density.res.nc
  hashes:
    binhash: 0429e872f90fcdd6e84e720cd9323f07
    md5: 4d74c373a2670fc317c78ce935821010
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 22327947361b9dd011f798ab2119a1ea
    md5: b2070b2971f2493a3446a4a00b9397ad
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1d612b3f2656e727c6cf455e2e9f3bcf
    md5: 7251c993b6508dd5c23ec6771f15e10c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6a50c208e20d2e590c55f8ac0993345a
    md5: 36b32bc05b39267b43cb206bb4df52e5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2dc006cfe7d25836adbe9327529062d3
    md5: 2cf53aa74b259cce9bd8532cbd97dad6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c5cfcc6b4adb456ae3b48b8aa5990061
    md5: f9820e2987e9dcb2b549b1eb34d3f2c9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4f5738d3261d924f977d41cc03e9b83b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_solo.res
  hashes:
    binhash: 6d864c8fc2f2a101a9bddec557be8930
    md5: ee7cd8bdf3e4f781a870c8efed2cf1b3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 837bc6359c8e4c7e9cc4d95fa4fd9cf6
    md5: bfdbff595ca41d5e848e6a370c10c708
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 821c7a18fb528548c23bfe51dffb6435
    md5: 6588131bb44d91498e14f1afaf6e09d7
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_tracer.res
  hashes:
    binhash: 4c733f594a1a410f99300e01534ea7d9
    md5: 54eef7f812e6449c563a7172d4b418e4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_velocity.res.nc
  hashes:
    binhash: eae736adcff39e02bfb415b61df958dc
    md5: ba90079f1fbc95c6b682cdb0b2a7047b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 249eb2da1ecc581e19339567974e5829
    md5: 6d9f4dbfd81e8b69bf07c10ce21c255e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: adbbffaf74cf19dc0224a2c126aab128
    md5: 7c18ffd4220672b2e1db4d1b082d71f1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart037/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e89ed5c0f98437f6aa73fcfe74f155d2
    md5: 2ac1401d76ba7bb2b803cfc526205fc0
