format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/atmosphere/restart_dump.astart
  hashes:
    binhash: 1f371f4e80ccd921e67aa2c2f2d01a0c
    md5: f8d18337c174fd81590320fba2edccab
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/atmosphere/um.res.yaml
  hashes:
    binhash: 8301ba2b33362150ea6cf1624ae2242d
    md5: 5bb7be4437a9d370b0cb6ee9f2dc6425
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/coupler/a2i.nc
  hashes:
    binhash: fdc0cc00848ff5dfa049cd6f2eeff641
    md5: e972ab079e25ce84613ca2472095131f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/coupler/i2a.nc
  hashes:
    binhash: 12deddb1ddde68bbdca95d545bf16bdc
    md5: ac3ba7072f0109266cadb11412dcc5e8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/coupler/o2i.nc
  hashes:
    binhash: 6caeb324a6e5435e403e4f5f42e8ec07
    md5: e64cf66909031262c665a1a2570c9d32
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ice/cice_in.nml
  hashes:
    binhash: ec3950056e009c4a6522215155bf9922
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ice/ice.restart_file
  hashes:
    binhash: 626cef115ce924c0c9acb37ea385dc1c
    md5: 004d2265c24e6e0024020d91ee153fdd
work/ice/RESTART/iced.2915-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ice/iced.2915-01-01-00000.nc
  hashes:
    binhash: 8a560811f2de83992a681b92aa7c9623
    md5: 45649c2471833f5e12ef33a7c125dbcb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ice/mice.nc
  hashes:
    binhash: c53c68ee03efeff8ba247ade1d0ea208
    md5: 9534cf1ca09a9f0f5f910867ea201270
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_age.res.nc
  hashes:
    binhash: a9e1974b074917632a42e2fff79208a9
    md5: 144adef70f74ece6db1e37891b2bf7ce
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6a84b3a28015f130511ed57732ba051a
    md5: 9f0f60e0698bc430a4329ff2ef47218a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: be22dbae14d838935acf120625ccb8b9
    md5: 61f7d567445f5b73c707e0f96cc6f631
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_density.res.nc
  hashes:
    binhash: 139ab891a1ee2bc114eba8599c93ad18
    md5: 5b25b31a6f64a3f70bb7b53037875cd0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a8c01893209cb65adf6be2426f5081df
    md5: 6e810bd03a6dafd09550ef5a03537149
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d71a1afcc0b72303bd196957d90113fb
    md5: 6dccf4e779f182203e0b01c2ece3e33d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 85efcb715456d6948ad70e99e2b5977e
    md5: 30644adc36198b134b845b7fafcefbc5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4efcb54bac208f477ddc42a805e11332
    md5: 909e1d3e4b36a6a91607fb3fe7bc5bc0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 72b7b81a73fe7ca55b831eb406579ad7
    md5: 87dd7728c069426da0b028e97a338035
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c71db955dc9865418c33d09ad12eba0e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_solo.res
  hashes:
    binhash: 06d305600304e313cd5e5aabaa6b2c57
    md5: fe0c66348e7a9a419b212e3a1fc01d8c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5dcff0629145b138de1aa14524b4ce37
    md5: f05ad1185c1fd7df18c93d6b21604c3b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e03ffa4c6deacb861b267a11b40c7828
    md5: 5596ecab33fb0ec4e284fffc4c33f4df
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_tracer.res
  hashes:
    binhash: 32866b3262de532daea517d882890c30
    md5: 40b5cd81a6891c216fae84ba88ed8423
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1a8ebdbcb31c0a659b0da4368e97cf2b
    md5: 3bffb537d1c02b112e0a8936de094fe7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4434bc3f91c63ddd6389c8726729b478
    md5: 3c7e2141bc4b8e44495e96fbfe6e5908
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 93fc9dbf7d56f3c02ae441dde25eccd9
    md5: 98f8b35a3a6e42a0145dc9a878f95368
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart238/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0a85697b1de67f342d543fef4d5cd8ef
    md5: 1399103c3c018a3ebca038c213ba8ed2
