format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/atmosphere/restart_dump.astart
  hashes:
    binhash: bbaa0af21a4cc712e3c8999a4f3deff4
    md5: 0619a097e1fee62ce8fb0debd509105c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/atmosphere/um.res.yaml
  hashes:
    binhash: d0561cfc693d0311889b11584b268633
    md5: 544b48deeac6890be08c68877d7a4190
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/coupler/a2i.nc
  hashes:
    binhash: 208b3b4db5287ea91918026b0482ab54
    md5: ab162749722566f3011c2cb421be53ac
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/coupler/i2a.nc
  hashes:
    binhash: 08ebd00c74c5f3e193c96da1552e3519
    md5: 38cdcd10719b7394610967f3b0951fbb
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/coupler/o2i.nc
  hashes:
    binhash: ac9a4d6eaf2ff2058a5404357961ad78
    md5: 88e8e37ceb1b1cee5d3c300f58cdee54
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ice/cice_in.nml
  hashes:
    binhash: fe0d028ea63717a4064f6a2241bbf72f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ice/ice.restart_file
  hashes:
    binhash: 776d7a7a8cb412ee6735dcc0f16658ae
    md5: 01c580b3ceb381e8927687157426c260
work/ice/RESTART/iced.2845-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ice/iced.2845-01-01-00000.nc
  hashes:
    binhash: d3c7222d692596ecca324faa14a3932f
    md5: 75e445bd0ddec9110584ecefc605fe35
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ice/mice.nc
  hashes:
    binhash: 9c89a44b98fbf19f2bfb1e21b9299c1b
    md5: a07c35e91808358f376a84d83ca12aab
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_age.res.nc
  hashes:
    binhash: 7cec0e98d99c2d2210d4297395736aa4
    md5: d12bdc6982a69de327deba90a1bc9446
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 769f2352f228ad8c3662a33d7b7fc96a
    md5: 473f7feac65f0287f088b7c6961d4afb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9631b4aafdf9f82400461ed0dc85ebfd
    md5: d2f7ffe16a2e0a9fcf62cb2195b9a5b3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_density.res.nc
  hashes:
    binhash: b1b98fb84cac5f393ada9fd2f1baa008
    md5: 4aa0f810a359cd286b5279c40f05fb75
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f5c9c9a13f53212a069776b18e2c5178
    md5: afdb71915aa0b53515319016704f2332
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6304042d99f4b87708786543f7f17c26
    md5: 003416452324c57e4d6e14b88dd19e01
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d356287c781f985bafbbce4bdb66093d
    md5: 1bdb7b88293630c9ede11a01d5bd8014
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c9804fe5744998365b68802cb2e0a921
    md5: 0b441daaed68eceb07378ba8524810ce
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3904ba5a9c730825df9d2185b9026f73
    md5: 37f6bbf149193854b4717461329b256e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f1e6b89923bb0803aaa5f287ad340374
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_solo.res
  hashes:
    binhash: 8e86ffd25d543b0eccb9f7febf4272ad
    md5: 041ed05c94d61b12ceeba4f7608338b0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 04e1628d862c1358b814cdc549c65807
    md5: fb77697c91bfeef4c242c23b1b6a890e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 33d6e3eb7ada0ba7feec6dbcbe36ca2b
    md5: 8c732f19aa67a67d87c1bb2f33d941fa
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_tracer.res
  hashes:
    binhash: 353d822cbcc19bb3e14e19a56683823e
    md5: 2af03e5b1a37cd2cf16ffdae1f7d7eb5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d3db5d4c6cc077140f07a5c7d1f8a5fa
    md5: 93224fcfa741ab11ef887e70c28279ba
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2ebb03e74b645c6ce06c4b8c4a3b7432
    md5: 4562959835f9c2987cca508d14d930ed
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: af32ca7685b30872f5dadcacf1305ba3
    md5: 7497a8c3376defe9b0ea58f27c484a16
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart168/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7f4f511e9caf45a103f61268434a3a3d
    md5: 0f4ff7787e10814578a1b1498ceff59d
