format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/atmosphere/restart_dump.astart
  hashes:
    binhash: e97374fcbbb526c1f1a055b29d9ec5e0
    md5: 459f644e7a9484374905c6065faaa52f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/atmosphere/um.res.yaml
  hashes:
    binhash: 6007cf7352ea76c7d6ac2ab1e528b6a0
    md5: ec1296ceb71b6df132e8f5c0e2e90838
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/coupler/a2i.nc
  hashes:
    binhash: 4379d58fd92ea40b1d9a28fc9e57f5e7
    md5: 51d681c1cc878ed2d369b763d31f6b2d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/coupler/i2a.nc
  hashes:
    binhash: 3ab3d556d92e08a1b814739b8a5c1af2
    md5: 4a843d1e2415fda957f9e072d0a07980
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/coupler/o2i.nc
  hashes:
    binhash: 90d4b150dc7a9ca1f8912fcdb1c6cd27
    md5: bc1efca08ce2e3efef902711fb91c4cd
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ice/cice_in.nml
  hashes:
    binhash: eea3d6ba28dd8244ac69e11ba2e391b9
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ice/ice.restart_file
  hashes:
    binhash: c799be94bc45a213c95109d27b7946d3
    md5: 7f43c211849eb795b43360446cf7cd56
work/ice/RESTART/iced.2687-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ice/iced.2687-01-01-00000.nc
  hashes:
    binhash: e1d75332f5c8ba7a02d9ce13ede2c6d2
    md5: 982bead54e2690a872ed8b3bd979e579
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ice/mice.nc
  hashes:
    binhash: 4350cc05ebe337e7f01a27d355264353
    md5: 1cde83d9d6f26bb6a25c510e7ea3b27f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_age.res.nc
  hashes:
    binhash: d11de820af7c607650eed04429c43c6c
    md5: 6122b79d33c93b03c0532ff7231f568f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9f7bdef133ed1711a23db60b1ea09643
    md5: 3947b99a3146ef569fd13e9070ccf198
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 580f3a16e2c3fc130147de95edf5ed25
    md5: ea72f8f3ad44512bb21df7c4a67a0e8c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_density.res.nc
  hashes:
    binhash: c8d92cd480814ccf99b1a6ac74f56b5f
    md5: 37f0f3e256d42cd15eede091f9c8251f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6176f60d639342108584b05bb0b17d25
    md5: 86945604e49d0e03d9ee05586c9ce811
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 112714961bfa1d9e334804288b03f1f3
    md5: 0abca5aa300de9c993417b5ab49e5f6a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2ee474b0c7797446becf31277767e5cf
    md5: 6ec1a34e5dc14e0774cc5c0282b9af14
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e61fe8052f5ef6cc4a24c4df78b8ad99
    md5: d3481802a2e2bc1326bb2b1b23a3a633
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f581218221e6b27d9a099c84cb2a194d
    md5: be942401739d53b26953e6a67a33cb00
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9df9c45caed0919becc50f5cbeb43c28
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_solo.res
  hashes:
    binhash: d31cc962b27a3bc3302c3d0b687f5c86
    md5: 21a5184c9aa0814fe902941b03cf88a4
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c4116eaa86c0095c333079a1d51b6aa0
    md5: c8bb8a4af868cfe5a3756bbea51e9cc2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_thickness.res.nc
  hashes:
    binhash: efeb3e8a5a2e2d08cfc753b9e4387a7c
    md5: cca48cae3dfead38d5e2c1ff6c4360da
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_tracer.res
  hashes:
    binhash: 891d300df2d5e72b1226bf839489c45a
    md5: 846367438a78d07180cc6d6e5a798832
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 00a45c0304b3a468abc3ed2c660aadf6
    md5: dc004bae344bbe8079346b1861561de8
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 162d23f1b8ac7153306b9f7929581635
    md5: 43ddfc6de6f0ed66b6826c703a83ec66
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ba8f101ca9bc10e5296efe205ac9a1d0
    md5: 8115b5774969c6781dfc7a64552df45f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart010/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 51a0a00755bb641f1e297728d78ca9ef
    md5: c4ff5ac33483c53db8bcd01cb8f4a5b3
