format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/atmosphere/restart_dump.astart
  hashes:
    binhash: 3e4ee3b0afd1060efbb253516c2901d8
    md5: fb1f73004a7e8e423f087f2ec56564fd
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/atmosphere/um.res.yaml
  hashes:
    binhash: 7a00fa92c038ed803e12db6ef2b4f99f
    md5: ffdd696c90ad709e2cee3378ddbe2073
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/coupler/a2i.nc
  hashes:
    binhash: ba7a8b1e2154940f4bc21e328e19bc43
    md5: 82e88f61cde75e154499d62ed5dc70cc
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/coupler/i2a.nc
  hashes:
    binhash: f160fa1da8fc5abe9da131d263b28c7b
    md5: 7811fe240d7c8ea01e93a8670cd8614b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/coupler/o2i.nc
  hashes:
    binhash: b597cac5f15179528fa4e342c53bcacc
    md5: d919d47a30702427048db29f8f5b0c62
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ice/cice_in.nml
  hashes:
    binhash: 787757cebbd0fe0edc6f3592e44e162a
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ice/ice.restart_file
  hashes:
    binhash: 0c8102bc82bc36b8f6a8be518fc452cf
    md5: 6528d3f2a453e288f7dcc914c9792198
work/ice/RESTART/iced.2938-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ice/iced.2938-01-01-00000.nc
  hashes:
    binhash: 895ac763a57c7ba592f0aa98cb964505
    md5: 88c0d6badc6d32c97032c273873581d6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ice/mice.nc
  hashes:
    binhash: a5e9563d225f9403a5ccbd05ab9b78b6
    md5: 4628a76fb10fd9a22aafaeccc8daf54a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_age.res.nc
  hashes:
    binhash: 1bfe64ce9f815498f5c241281722e3e6
    md5: 306dbb078ecb20d179648aa5b6131f9f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 59e260c8e511b0c4e9c04df7813511fe
    md5: 56fedafb5cbdb906c613730309e36bcd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ad23434e578df2578f3511ad75ee5e5a
    md5: 7f9eac53303c353c20caff4e9787096d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_density.res.nc
  hashes:
    binhash: 5d8b69890d39ac5c4f4daf069b91952a
    md5: 1d2e6585695c8e6ad1c1cba15c0350c5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2f8f6cc581e5adceb9ab8519fbe55385
    md5: 680d785bc501692f9af8d311dbae3c5a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 879f42a3de9bcce2b71ccaf73f23c4b0
    md5: 9ac576a075313e0f72e024bfa7b0729c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_neutral.res.nc
  hashes:
    binhash: aae8e6610920252d32d95813101c84d5
    md5: e7a0a77a8cf2501ce1430604a916c371
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 37a25859731987f455b87c2d5e298b5f
    md5: 79c992e986ccd535df4dff7b1b3ac317
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9d8984803be613713211e737cf44a7c1
    md5: fa2d1d7bef431fff04b8997afb9da64c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0f925688c97cf5908f1e04a8929f0ecf
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_solo.res
  hashes:
    binhash: 5b708c42bfff240b5b0548b045262b94
    md5: c114cb0f0594191fb409ccc1a7611956
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e03d361001d590ca8c874edec9bf5567
    md5: 96839012d7538284f7b6a69622952f55
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1e1e406ea993bcf4a0308f0f55e20e26
    md5: aa38cdbc2b05d0d1c3442870f2b0bcc0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_tracer.res
  hashes:
    binhash: 37e9243b56ebf15599e0fe148d8b8efd
    md5: 858b5a6843e20e6c4a8cbb9ff5471fb2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 961f99859ea72abbe1a80804abdccc43
    md5: 783275a16684b05ff0c8186eedc13883
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 763570217dc7bae636897cea120162fe
    md5: f8fd67f372a7119f45cbf5fa54f0032d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6b9c99a890f4750fb9ee4a241d069382
    md5: 0bdd442cdf326750d8299faca6c4ff0b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart261/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 537791f2405fe3c2f669f52bb5b76448
    md5: 0d4cc8c31b3943618f3b22f4e6f3a502
