format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/amip/restart/2025.12.22/atmosphere/restart_dump.astart
  hashes:
    binhash: 90b9a69df924420b63e671bfadadfdeb
    md5: 672da52576a606595f9bbb8772f48b43
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/amip/restart/2025.12.22/atmosphere/um.res.yaml
  hashes:
    binhash: a3ab417968f36882d2a6911c0355e843
    md5: 2040b7490b72ee39c2693667166461e3
