format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/atmosphere/restart_dump.astart
  hashes:
    binhash: ce9608d8db43a3b03b01b9541ed2fd07
    md5: b140e4ddc7864aa94d583c08b01224f0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/atmosphere/um.res.yaml
  hashes:
    binhash: 86632bd29acb906063acef1b67a9fe45
    md5: d0d9b925036209b07ca7fb9cc31aebdd
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/coupler/a2i.nc
  hashes:
    binhash: 4594f56f06090b192bcadcc1afc1821e
    md5: 24298cdf15e7cab05feec14b24afb072
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/coupler/i2a.nc
  hashes:
    binhash: 765de05d57c6a9c70a736e931caebf8f
    md5: 8424b430321f588e7569d5235a665386
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/coupler/o2i.nc
  hashes:
    binhash: dce30fea7d7cd186594a830d83741eac
    md5: 3dfe886c175f97772c32efd2bd28aa4c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ice/cice_in.nml
  hashes:
    binhash: 5023689b0020708ce1bae618e700644f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ice/ice.restart_file
  hashes:
    binhash: 46885d3a6cd076e12e26fdeff338782e
    md5: 35643dd3f54c11e8538979f6f2d587db
work/ice/RESTART/iced.2802-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ice/iced.2802-01-01-00000.nc
  hashes:
    binhash: 1e974c1048ba05ef5f6fa56de3887ba0
    md5: 1542ff16bac493bdec5dec113f0eb8df
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ice/mice.nc
  hashes:
    binhash: e1e9df911741b95c9d1422abf46882be
    md5: 30150bdbe77b755d88f85bfa3e1d2c86
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_age.res.nc
  hashes:
    binhash: 2c529ffe9e392a05b682f77c7767c223
    md5: 6c3dd3f087f8e7913a0e63a5099d1ce2
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6f51ad6d5471f4d429d3ae557c87f8af
    md5: 8ddd882d2730702049599134e5531392
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6fe4a0e914056669d3d3811d802c1289
    md5: 55fd4d4b3c77c94c85d4d04cc26f58c8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_density.res.nc
  hashes:
    binhash: 06df01cd6d07787460fc0ffcd758d811
    md5: bf1f68785c8a2c758663d6ef5f2b28cc
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 808369e67ca3f449ba985e03c9d47035
    md5: 1a1a934e391f5909dfa2ace93526ae73
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a62df9955854fcd6a7c2e2fe1a619345
    md5: f3453fb827e94d96c750ca85c8ee589f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 688e005592a312f148327620b0788277
    md5: 5e489a790ebd73700e9720849794d1bd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 07ef3fb906adb1c4d85d2764643dfbca
    md5: d883e12a918e0349e0501ca1a679f658
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ea38682a3db50db8fbbf1b38abbe47bc
    md5: b13d80c3fc94f4efab8ca34bb0be31be
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 05dce73301b924df979f49656e23bb12
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_solo.res
  hashes:
    binhash: cef6b4cf925e2ec1239b46ac87b1e362
    md5: 70168959624d41ed7a1ffe91efa190b2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7a889c8086d5d517daf69f9f9a43c2bc
    md5: aa64beea79c6511950f2c40344606502
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 747ed93bd75f1e6735164e92c57af53d
    md5: f9ff9bc969332b571e2ac0683a167cd9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_tracer.res
  hashes:
    binhash: a6d64d2e026dda1c75e6db5a8ed36053
    md5: 0195774da2a55dce1028da895f06ffa9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 177d45547adec7b984c9a913e328acb0
    md5: 54b5909fe0624cff60afa9f0884829d7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 13249c5a3f905cda73638dbca6f18b46
    md5: 62e723fafcbe4dac3be664572711b353
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1d03cf53714efe27e7c758aaa64548b3
    md5: 4bf9f04c4859de6f4024a5a50d021ade
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart125/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0efe6a858ec5c95c04d7f3d4971f9e2f
    md5: 6358b804dee7254b6f757817b3381295
