format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/atmosphere/restart_dump.astart
  hashes:
    binhash: d8c5ec8e4d38b5ed19a516f4307b5b72
    md5: 5ab4f554958e45684acd8fe913aa235d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/atmosphere/um.res.yaml
  hashes:
    binhash: 759aa127c127e4b6b892ef970de5d481
    md5: 4be264dca19b009e2cfd3c0b1bf9ad05
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/coupler/a2i.nc
  hashes:
    binhash: 7d133877910cc3c602656325a84d8b3a
    md5: 35eef0c25c293389cf89d6f9135b8718
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/coupler/i2a.nc
  hashes:
    binhash: 46a6a9c87ddebab383f47f680426f636
    md5: a53f10f9cef4eea6a25139cc905efb4b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/coupler/o2i.nc
  hashes:
    binhash: 6f6931bc590acc0bfc6961c3ee9570e8
    md5: d5521ac4cb52bd5002641829c30c7326
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ice/cice_in.nml
  hashes:
    binhash: 5056c7a73624a7f087b7312782c2b9e5
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ice/ice.restart_file
  hashes:
    binhash: a4f7ba20100be722d30b7bd0ed78d019
    md5: 535903f1078a1ce95ce976825b4232f9
work/ice/RESTART/iced.2816-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ice/iced.2816-01-01-00000.nc
  hashes:
    binhash: 594c6245c77c1461b96613229e1c714e
    md5: 176fe04805db2c1dbc0f9dceb1c07141
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ice/mice.nc
  hashes:
    binhash: ff019298dab69af74fc0716efa35b3ea
    md5: 49a1ace4cca8e4004668a30d1e113d08
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_age.res.nc
  hashes:
    binhash: 0726e797bc1430f30fdf0a745dcd045d
    md5: da7d24da16191e718abdf152e1032313
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fbe719d89bf60912a4d1e25fc21eca53
    md5: 40dbc7c891183bc12898c0f5b4622163
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7e4162e0ac035f8a2ffe51dc336463fd
    md5: 434baaa9dd4c78a57051981e5bfd6524
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_density.res.nc
  hashes:
    binhash: 4390b383ee2d58ef76a9c3d6ec8dd222
    md5: 1728f54f48e18027870451ec4562a151
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 53da774b7360c64d9f1814b833f1fae0
    md5: 48494af831cabc8ba2342d91c3b7faf1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e9c26ee0e10291142e263ebe362242c4
    md5: 121ad39cb7cc913a5eb97cf6efebee2f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5a10bb304cd72ace416b9120a02eff36
    md5: 01656b47f132a1b691fd7c70fbe259d0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 447eae8d9d1ef71a0d357c01748d44a7
    md5: 52fe771666dc9b398e471afb9e40eb11
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c41bd6762e4ebe5e9daf49bb878cf7dc
    md5: 628f75f13a30454911cf206f7c7dec51
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cb5ad2ce721a0bff4f455146cfbd0751
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_solo.res
  hashes:
    binhash: b044502d52e0b493b6bbbdd80ebaa1b2
    md5: 1c8c149955d9ac5238b8c0a566b5403d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6f956093736a9974ccadd0dd2dd1c6a3
    md5: 519c55c1346a6bc56a43c456601fd286
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3c3d5e4492578affa28484188aa79179
    md5: bc8a366ad84c4c695af9f1deea81401a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_tracer.res
  hashes:
    binhash: e3d866b7cf86c485d8e86af5a44dc9f4
    md5: da3cbcb43fb96309823f92eba9142c36
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4c6870ed53e25bc0543df005424ff2b1
    md5: 8bd08aa5b3a32ff59e49ddac0bdf137e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: da62885a0d045f7988f1b3d6bd683db0
    md5: c4a6843ef65ff0be67cb4226cb22cb1f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e0c769e977f5b7845ae34892b3e9fc35
    md5: 2467da412165684fc97a4937e80b74d8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart139/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3ecf51bd0688fe10e5ef107b6cf8d8f5
    md5: c51f4937c81510c35b42c1c84f0af58f
