format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/atmosphere/restart_dump.astart
  hashes:
    binhash: 9300d90e3f9abb01b359ace8e8f44f74
    md5: 5fecfa474a0bf0871e26e98fa84495cd
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/atmosphere/um.res.yaml
  hashes:
    binhash: 0a3a8ef4dc30c926354e7181af1ece9a
    md5: ad6eb68114bc83431329b38d712bf5fd
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/coupler/a2i.nc
  hashes:
    binhash: d269ca0a29ca7c0206d016f034b96ab2
    md5: 847d10e63787408e3b0e93db52fbf7d6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/coupler/i2a.nc
  hashes:
    binhash: cb7cf7f4ae85d2626310595444637dc9
    md5: 1313dfa986b90bdb8c6c848be88c705f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/coupler/o2i.nc
  hashes:
    binhash: 4c5ba5e16a2578762b26b04708672bb0
    md5: 739b90947e9c23995c57033e085f3205
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ice/cice_in.nml
  hashes:
    binhash: c6346884ba7cf86a68c9ab3244d91000
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ice/ice.restart_file
  hashes:
    binhash: 4e42c24f3fcbb64203441b63a4065e26
    md5: cb639db17e42155e090eb0eef74c5248
work/ice/RESTART/iced.2893-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ice/iced.2893-01-01-00000.nc
  hashes:
    binhash: 03c9572cd7d45f95d04bb4facbf5e10f
    md5: e28079780e3f0c9ae173e65762481bc7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ice/mice.nc
  hashes:
    binhash: 49ba65a5b060f484fcda125d6785ec2e
    md5: 079dfe25b7cd7de3ed171936c4d617c0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_age.res.nc
  hashes:
    binhash: c242bd93551dc1199a809949b65061f8
    md5: ea29bed5f95c5fb48e1ab3364411ea90
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a7aca4eaea9ce9aa4767f021aa8c6779
    md5: d0db598468373a2d6c6820adc8ad0d46
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9639eff80eefc27ff9b39b7c5f63f856
    md5: 6d1cd937bdef3b4964fccd2dc70cd9ab
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_density.res.nc
  hashes:
    binhash: f65b5a3e0c7be7bab95ed138dbf5b80a
    md5: 369ff3eb864cfc2e38b56bb7863074e1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 670f8516f123d125d9b72d3eb90e2e54
    md5: d2610626a7ac0b4d9faecc9342ea6fee
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3147f693e4431f21905704408a3824fb
    md5: 64145d37a5b2086dfb1d8afcb5692980
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 19cf6e16e9cc52834ca9e2836405b573
    md5: 101b589b0717240b54e78b6f17b13bda
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c2c977c37814e41bf233f4d7700ca598
    md5: dcbc403b2e900d9d4f2372f272a2821c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d695c0fa88face5c23feb196ad2325be
    md5: c1e2983a63ae9b7b3e4f0d67df938c5b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 072033257fc020373d8b884e687b9945
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_solo.res
  hashes:
    binhash: 7bd3e40cced603b5bc2efcf6409801fc
    md5: ab538fef2a7dcc5f0344f221cbe4fa01
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bdf6710dae00cb220acf5747b6db542e
    md5: 1c818a8f8c37ba53da5203aaf3ccc9c8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_thickness.res.nc
  hashes:
    binhash: fda87d9b3151e75ceb64c234c866c33e
    md5: d88c4853cc3126140aad935c930120f2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_tracer.res
  hashes:
    binhash: abafe2f2304b8ec030097517e68c8088
    md5: 5b35891b6d685b2f4fff367c6f9b3acd
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bfaaae5dbf95bbe114c8f00e66b3312a
    md5: d17ee020bf01c5a7e3f8719e62d1a8d6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c0944bbff08386bdcfd3057b380c1000
    md5: 120c56424ed58140860e45ccb60931f7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 225654563ba1b278bd08a7c2dac3c882
    md5: 80096354d6891660ddecfcdaa33002c5
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart216/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9b4d0eb71606c6301b271dad4961bd78
    md5: f0a8f59097e99f74e69b6e3cd1e41075
