format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/atmosphere/restart_dump.astart
  hashes:
    binhash: b9a608368ba14e71fcd2100cf39d6279
    md5: efe53e4c7d3dc289fc066f3c7ad5790b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/atmosphere/um.res.yaml
  hashes:
    binhash: e7452f527d05b08778d099a6299eded4
    md5: fe92ba5ea60fd4d97066766f8e5c369c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/coupler/a2i.nc
  hashes:
    binhash: 0a09b65e74f2ba21df179b83e63c9af3
    md5: be15f73c3643c1c85e57c50bcf8ac2ea
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/coupler/i2a.nc
  hashes:
    binhash: 19c5e2d1621fb1a2bdf691fd26640127
    md5: 728a19d4f224cfa42d1b047f476b704d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/coupler/o2i.nc
  hashes:
    binhash: 434eca4ab0c972d6b78f82c38b4b06a4
    md5: e1ceeef843670b02866113d8d8d32c7b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ice/cice_in.nml
  hashes:
    binhash: 38a4ccc1316c42bbc3b944c69a85f715
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ice/ice.restart_file
  hashes:
    binhash: 03c979e88538020eec57b21d1c5c7b0e
    md5: 66f01737a3a9b758dd73c92b10aca5a9
work/ice/RESTART/iced.2694-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ice/iced.2694-01-01-00000.nc
  hashes:
    binhash: 3cf9a7c52a803e0ffe150b4a058d5ae3
    md5: 003babcdca224b80807271cbc002078b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ice/mice.nc
  hashes:
    binhash: 8ffe0c9232ec4b4d5b9e6a2407a04d52
    md5: 1d3e154a4183c55d724549177adf6840
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_age.res.nc
  hashes:
    binhash: 8ca5ba9d5dd12a095a3aad19078519f9
    md5: 91818f123cece5ff7230e758fd69a151
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cfa72c3892e4e403f27de0d67c7c4c52
    md5: 96c63ab9a6bdd7faf0e0a5ea027405a7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fddfaee9d06b208a9c1c1941a76e72bc
    md5: b027800d12ae3a6a65b8351a5d2ac72f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_density.res.nc
  hashes:
    binhash: d6613127be94bfc0dd717420e5ced53d
    md5: bae31747a9e00dad0a486c9e23d631ea
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_frazil.res.nc
  hashes:
    binhash: eaa622ffb6268ae74a5bada5f6251884
    md5: ca48496f7a94606e2877a0f8ed60e0ec
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: eb5dc24f8e06a49c9c4fb69bb1d80b9d
    md5: fe89eec54a91670f25429497bc56ad6f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2990c915bf563bba86defd699e673435
    md5: fd79f8bed0220c5633e00a24557f2b9b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0bac26f9372c4005f559caa92a817daa
    md5: 00809300d824c871991c88d83a05af01
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bbe733cec3c8cb609a6f70071ec63cfb
    md5: cfb474dd948539753011edf17d7fbd01
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ee3739947f255d21782ade0e8a2783ad
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_solo.res
  hashes:
    binhash: f67f80a6b6b57c2f1abb8e5d1092cd05
    md5: 7963cf7644468bab2d694cdac287c879
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fcf9a3ecff62e17f4eac51f4142986bd
    md5: dda4e85dc6d576d4a3e5a99ac24a85cc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f93194ae885f8a6dc4be80090b96f86c
    md5: 09dc4889d24db0c41e066ee9906a730a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_tracer.res
  hashes:
    binhash: 2d76b6cb429d9a6714d263837e042c28
    md5: 87d173e9057634e56f0f6c80d6c2e834
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d44d349776a5e63a07dc5835e2c2cbd7
    md5: 75dc691f5dab121ddcfa1de331cec2ba
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ff5b6b0db32b5194227b1b8bdcfd4cbe
    md5: 019ca56838638d72d2f5b5f44f749c1c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: aaf37e3734a2825cbd8b37fcfa603d0b
    md5: 71bb6b11689fc107f475afb48f36c6fd
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart017/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9684124f42545f7ea03c88da364e203b
    md5: 0df98376383190f9b4d359017a93b222
