format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/atmosphere/restart_dump.astart
  hashes:
    binhash: 73e1a6692d4caf75d67984f73ce23e21
    md5: a52ea31a5f4ee0de281cae03ca220782
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/atmosphere/um.res.yaml
  hashes:
    binhash: 462223814efbe7a5fad720b7f729f67a
    md5: af4c6d9801e958de5293895d8136dcad
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/coupler/a2i.nc
  hashes:
    binhash: 9bcd0017db5ee5794803975c457a97e4
    md5: 630a235b4e9dc2abe2e5068895960ae6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/coupler/i2a.nc
  hashes:
    binhash: 1397640f0e2ef6756cce8953b16392ce
    md5: eea420b1342433df8e2cbe1c496e4dc4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/coupler/o2i.nc
  hashes:
    binhash: cf9b7b7b2549a9200294f99852d1588b
    md5: 494333a234b8759c8b383e92656b2c3b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ice/cice_in.nml
  hashes:
    binhash: c8a99eb721e57a33eb66e377a115c39b
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ice/ice.restart_file
  hashes:
    binhash: f0b55233cd0497a2e090197337b49d10
    md5: 98a162bb08efbbe01d57a520fa377af0
work/ice/RESTART/iced.2864-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ice/iced.2864-01-01-00000.nc
  hashes:
    binhash: a72d3ccf2871ba76c0ad769b924349ad
    md5: 4a126b25685177c2b8973f8040cf8d89
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ice/mice.nc
  hashes:
    binhash: bd2f0374e155197c900d9488925bab4d
    md5: b11f109df0253fd12d7629b939587f4d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_age.res.nc
  hashes:
    binhash: d67852b88d26aaf91585718720bc1d5d
    md5: 5080a720aec605b34e5db4af95b0beb7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 72340b4ced95a6f0efc3d7ad540010fe
    md5: 02a2d02f1b13dffe1b1c9d1fc7f7ffc6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 889fb48ab9d88871481dbb6d13301a76
    md5: d30e970175acd26f6c39ec252c02fe8b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_density.res.nc
  hashes:
    binhash: 0f740c332c75c0c3930f289ec8ae81e1
    md5: 07f377b9c32d37ebd15fd5fb753eb7c9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6858ba94c2ca275a32991d94fcad7de4
    md5: 144079fa753598a7f29ee4632972fb88
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: eadcd2ae426d3c9b76f54af417c2a428
    md5: b5f866295342b276b0e8450c150dfb68
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d799eed7661cba8daafbacad63c6d968
    md5: 9135009fb6536e5280f4e731b054ee73
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 11770917550020875f44b40b52bcc32e
    md5: 9912d95482786ef71d1744e134f17f0d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a39a7073929ebfafd0a9cae8aa237c9d
    md5: 2cd220418d8ec00d6c80d1e98ce46110
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7eb26e014d21bc47c447c9b0fb3f0a3e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_solo.res
  hashes:
    binhash: 7a039ad57216ac4d26c0600042127853
    md5: 0c7bf37a2363eddca52ade76f6dcb58e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 75bbe29de1084d9075f3d1f4eb7ef2d0
    md5: d38626680b307d975f9b28d64282b1bd
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 09eb57e849e3fd571869d994d44734dc
    md5: 626dab802049eab9704095fe91a146aa
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_tracer.res
  hashes:
    binhash: 15d037693317287516cc0a2988e77d2f
    md5: 978ec5330a0b3ef599310eebbee33917
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9b2ce70f6c99815194e9a3b6bebd6657
    md5: a4b14de346da44785cc352b1ec0c9491
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4aa594f9b5ea5ee2f2b48ce2b9638861
    md5: 4f675565e26d80b85c4b829a2350f16e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d8d3509ec905c9441ed2ef4f1a913a18
    md5: 8453af6d8ad6e3a0a184342ca3e4a452
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart187/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2b554a90f2a9825ebc713d5c4b6152cf
    md5: 1b6207b62cdf71f7637b598387872f6f
