format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/atmosphere/restart_dump.astart
  hashes:
    binhash: 2e75bc6f2716b5173b9460209c703c8f
    md5: 2d684960c7d5109628ade798546a1148
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/atmosphere/um.res.yaml
  hashes:
    binhash: 629b87f0eaa18bc716ec2e8bc300b4f0
    md5: af3e6adc690df6a965282bcbc64149ab
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/coupler/a2i.nc
  hashes:
    binhash: c79038387f1c902ea7ed7c7d7bfcae41
    md5: 38b8a640f0640ee43529604e150d0b72
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/coupler/i2a.nc
  hashes:
    binhash: 59d611c615d1e8f20f43006b23c552e6
    md5: 5e000d1f562b95d9d879585cd0919f1e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/coupler/o2i.nc
  hashes:
    binhash: 733a80f8116558ea3709e7025cdf03f1
    md5: 7a36977b0142612a8ff20e35e67374a7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ice/cice_in.nml
  hashes:
    binhash: e2a3c6becaa140147019d9c673eed394
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ice/ice.restart_file
  hashes:
    binhash: 20d316f8197139f7080e50141599224f
    md5: fc0641b9d99696b3fb80475411742274
work/ice/RESTART/iced.2684-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ice/iced.2684-01-01-00000.nc
  hashes:
    binhash: e5ad9c5fa945e48d3862c81d8d921ccc
    md5: 84c30da3397fcfa8b0ed488c6a427953
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ice/mice.nc
  hashes:
    binhash: b325b452ab504e222b4f6df2c855c7bd
    md5: bd93c86514f74c43b943b953ebe40cda
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_age.res.nc
  hashes:
    binhash: 347812c40e467b350f39510e23e9df69
    md5: 081b449df3669e624d3d16418513097f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 29c19e254b49b7837e3ba3be2ee1ba1e
    md5: ee98747697dedf989822db7d57a49b8b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5b2a6a9cb0263ba784bf746f3bebd0e0
    md5: 1ffc18180716eccd19ec72bd5772aa24
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_density.res.nc
  hashes:
    binhash: c3769b0b8d15eb98c23b5731e95ffc4d
    md5: 14fb271d0058940255dac27dd774d811
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_frazil.res.nc
  hashes:
    binhash: bede70f79d19dde983e133acac220ab6
    md5: e88700c58790fce7d8bf475deb4a0342
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 991644f73089e61027cc8b60eca9a30a
    md5: ae614de6d5da60a95ce0cf130a135058
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 754e21214b7bde8193ccb2dfaeba9190
    md5: c707528b2130f8f5211158102740357d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8158261ad1040f45178ebccb6af17516
    md5: 9a2c6cbe3a6f3259a032a09c41552ecf
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 02f454401bc85447e55de4363fb505d8
    md5: de387eaa9c5f061aea3817e8217d68ea
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fa29ce9ef4cbef7e3038852eeddafc3c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_solo.res
  hashes:
    binhash: 494a04109fdc1ea154ce1773e15a9ada
    md5: 22a1a016f47bec958d321613d4e3321d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a7a7ffce780a239aaf3d248ea7f80bbc
    md5: 868bfa411f54b66d23a4011c17b87215
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ef3b440a5699534c249ea47f1715e536
    md5: a846375db86b80aac9642a8d43ca4be2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_tracer.res
  hashes:
    binhash: e517860131492d53c71fbee4cc200679
    md5: 383f0868d02b0a5482650301fed7dd2a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 405964e8985e932285ef2df79d548e82
    md5: 83956d2e98ecb1fb1f5397f81daac628
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 82b2325f64715ba094edd3dce1e7fba4
    md5: 4851758af6db22ac404ca37320b6b720
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f6b5cb17a72884b1504ff54be6d83038
    md5: bedc66cfc821b01a4444d850ad9aaa9c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart007/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7438d870bc4ec89f1093b5e1c20433b3
    md5: a149c568083755df2699936e0685cd30
