format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/atmosphere/restart_dump.astart
  hashes:
    binhash: bdf2f2d6326f4e835af9288bd4a1d238
    md5: 543ace7982b503d2999832b492c0a68b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/atmosphere/um.res.yaml
  hashes:
    binhash: af50dd2c5d04b8ca1a8e4cf0dec6bb37
    md5: a059d460c2b8c6450b816d86187a263a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/coupler/a2i.nc
  hashes:
    binhash: 0aeee7d038cc6308ea05930e6109b712
    md5: 2ea4a69c0408008caf5e4b96f80a1741
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/coupler/i2a.nc
  hashes:
    binhash: 10ce02d2f435dc77a2be44aa84efb72c
    md5: d3e7929eb8dcc508a2b9182fee9166f2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/coupler/o2i.nc
  hashes:
    binhash: 004cbac6062a0cb310160899c7ecea9f
    md5: 15046b384452bd5dfd55e49f31e6f26f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ice/cice_in.nml
  hashes:
    binhash: c1f4a0271f04d3e03adc2bd08cdfbd69
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ice/ice.restart_file
  hashes:
    binhash: ca89d1ef31002f9cc335b951f570f5e7
    md5: 8a01bfa3c6858cbe34257cb7d0032810
work/ice/RESTART/iced.2953-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ice/iced.2953-01-01-00000.nc
  hashes:
    binhash: ba7f994790e1c273747c5e8a0f9a6118
    md5: 57299003c7a9e55d0876f980ea074623
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ice/mice.nc
  hashes:
    binhash: 4d80a4883fa52015562459269b7621ce
    md5: 860c5ce53e7096985a384afa98d413c8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_age.res.nc
  hashes:
    binhash: a7ec7e57341b4c0bde35a551483867a4
    md5: 94d73cb199a980d57b1a4f31ffbb3eca
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5814b21122c9093b82a699b7c0cb2301
    md5: d3b01c07e3a043d2105799da0178f9f1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ae254b0fbc457d7d85eb2ad5599dd90a
    md5: 44b91d912092d84e183d502d528934f7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_density.res.nc
  hashes:
    binhash: 099291517373a70aede9e270c68b04d5
    md5: 0b2ba657c59b784be5147a21c0c777d8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d6d46fad5d2c554b7f11be31c46f1aeb
    md5: aacf61900805398a5a61a145e3acb90f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1a0babad0d0248ae03f336ad84fc625e
    md5: 9539e7ee2a6bb3e8f230aa018fdaf1e4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ebdf2cafd60f3d8f6bc689aecdd6a983
    md5: a46887890f6d535028552e08e696a4f7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d333a52560b24b122c7c1595e503858d
    md5: 5f8bb6341da32bd4138f339a4b441def
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ed2c8f2dc639ca15146c3ecdae82ea9f
    md5: 87d95655b964d1d0c6af4d6f3b320259
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 30ca27133386f612201eb5726da56670
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_solo.res
  hashes:
    binhash: bb76f2999f5f159b29df30d41ebd9bfe
    md5: 00cdf2360369fdca607c0797f026af09
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 69fd7f9d3b097487b364e28c55dcf92a
    md5: 3a3e56fe3f7b785684133541d5b8efa4
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 28c1795c4c4ee84c28d8bf538f596caa
    md5: bd3bae758298a2ea354864e573b99f16
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_tracer.res
  hashes:
    binhash: 12ba842c4b17f98a623690f7bff19fd1
    md5: e6279eafef4b1e52be773f0af40d87a9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2cba4a16afecccee29ab36cab23e8a3e
    md5: fd15bc90f97d7cdb9b89c42e837f0047
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 39d1b58335f2698e29af78572b5d9374
    md5: b4cc64d34948fea311b099ccb9cdb118
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a88b116b8ee4f8034a3fc35a8ede4ff6
    md5: d8b41d8c754223181126c178ef060cf8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart276/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8b78f7ff0ae0ab2813c91c8c07396d7b
    md5: 745d4fbed916f220218e78b723898680
