format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/atmosphere/restart_dump.astart
  hashes:
    binhash: 9019d2ec2dc2460a5c45e274316c9a10
    md5: add6329a977b7eee6894a7546d0795aa
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/atmosphere/um.res.yaml
  hashes:
    binhash: e889b6689d6eea091ec056bb1bce8278
    md5: 96cbebcd107de2084b3b6bde55f554b4
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/coupler/a2i.nc
  hashes:
    binhash: f1cb8d94593b2556acf50af907a42737
    md5: d4def9f01c4e61757e5172c309d58371
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/coupler/i2a.nc
  hashes:
    binhash: 8664c30235566e6022791c2fed9016b1
    md5: ac43372288e545d35a5b5b4d01ac1f2c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/coupler/o2i.nc
  hashes:
    binhash: 87f688ff141a4dff1337eb084cad2f5a
    md5: d4991c7d454937ad71c1c2696e19c6b4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ice/cice_in.nml
  hashes:
    binhash: 3f193751039ec0e07efdcfb5885be695
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ice/ice.restart_file
  hashes:
    binhash: 901b09ae7badd461f36982095c813d7c
    md5: 878d94f0c029f209944f23a0a9667306
work/ice/RESTART/iced.2757-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ice/iced.2757-01-01-00000.nc
  hashes:
    binhash: 3198dae4bd3704e4a2d143b9da41f2e4
    md5: 7bfea69ebce9f7496cab3b46b87c358e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ice/mice.nc
  hashes:
    binhash: 051eae2ad07e42968bef33a4dfc67a9d
    md5: 8f500acb4427d5f329bf5df92571da29
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_age.res.nc
  hashes:
    binhash: cee96b020eb6cf4a311e2148573d23ce
    md5: 9ebd2f2327fa9d770f2372b897289105
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 68bacfa5993187cb59554b624a01b2a5
    md5: 73c0739869735de007f51c2fce4e09c4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bed5a7cef832104d8fc04dbbda973099
    md5: 58304c7e968578bb9384649875768126
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_density.res.nc
  hashes:
    binhash: 991a3e8d8d9b1a934494a311d5fe8035
    md5: 888d3415efc2558281734d29c2c27100
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5a8da3636d11f44964d9c9e67fc0662f
    md5: 4f03d490931a06ffee97e39dec953a0d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 98fd9f3e6291e6f9639f8c68c22f40f7
    md5: 67eb33b1cef45025cabbf3efa50775d2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_neutral.res.nc
  hashes:
    binhash: dee9681a8f56c94ca043457d5c65cd9d
    md5: 5490d0d0a845ba02bcd5472c9f8622f6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 46239d6840ebee27fc6b336e417e82cc
    md5: bdb47b93cb5292fe048f21e87e85b91d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4f7bb81e419ff77bc2500804dd690401
    md5: 832c4ca4cabf02496e6655d326df6038
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ee6759d441e32f89ea670075c2de32c3
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_solo.res
  hashes:
    binhash: a36938a7cae3e10769984568a85f92ac
    md5: 3ae68ad63b776cb0dcbaf35131cd0e90
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1641a03d8f6e2a23471d0eeece06f9d7
    md5: 62aea656d3d800aad2cedef160cbe815
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3f1167d1d2789f539e388070feed5700
    md5: 13e492a6926edbdda67ea4bfcfe71a1c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_tracer.res
  hashes:
    binhash: dc020c867fd5648334671756a85749d4
    md5: 4d3fb57092c68e9ee8502e63cf208eee
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5d573caff6aaf57a7fb8acdc682aa7da
    md5: 1fe4a1b89e9c77ac90472d1de9ac6ed3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 178334ac773b1a54b97b5a853ddacf89
    md5: 1c955256b1b9990e32cea73d9bdf4fc6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 65b028f46f487835689c0c17b6462ae6
    md5: ea6329c3e0129c5961b5b59871daf0d5
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart080/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 643ad1de6d49decca8739e41ffd7adc7
    md5: a74d060b341a47c6c209b031f80686a3
