format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/atmosphere/restart_dump.astart
  hashes:
    binhash: a8a9f838e89e8a72988a3a2ea966673b
    md5: ed1bd069d6c13302f0eb35410b890a8e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/atmosphere/um.res.yaml
  hashes:
    binhash: 9df2cdfc8836b3c27d6b87d343b7e6a6
    md5: dd4eeb67737b0dcf84ae319263bf719a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/coupler/a2i.nc
  hashes:
    binhash: fe370428c71ea9106d6305744fbd376e
    md5: 214564760f5915965ab629df88785630
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/coupler/i2a.nc
  hashes:
    binhash: 8bcbb78c30838ddab8ec194d23907dde
    md5: 538f7d1188c7a6226702979483f93e43
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/coupler/o2i.nc
  hashes:
    binhash: aab0b184de0a0069dc378d34dec0d5fd
    md5: 0013a116dd2655c6ff724eef3987ffc7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ice/cice_in.nml
  hashes:
    binhash: d57c5a245a3d1893de28887165dc4fca
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ice/ice.restart_file
  hashes:
    binhash: b3f03aa405f8cee1eb6b951272d4a802
    md5: 72de48bfe5f6f8cb8dc4c60302a0d980
work/ice/RESTART/iced.2702-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ice/iced.2702-01-01-00000.nc
  hashes:
    binhash: cf6d284f500efbd391ad49c7f9512546
    md5: 0d9eca20f74563ae9e23b351c2b16fdb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ice/mice.nc
  hashes:
    binhash: beda5e0e60e2a7b31031148be8352d8d
    md5: f18a29e5609c89f9aec3fd7cfb59e95c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_age.res.nc
  hashes:
    binhash: 1c60625c37af5cb576dbe3ea4e9c8ec9
    md5: f25b164e7a0c0d7fa804f1cddf3dc89b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 29ab46e42baa7ff5c776dd8692204fb0
    md5: 679ab4d72f8890a3acf061397b2ea4c4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 595936810ae08171e509805f11b37c2f
    md5: 15b5264c3bf2ea0cb3982e1c908be199
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_density.res.nc
  hashes:
    binhash: 2ecc1b76ae38c74b16a67c8f1611e7d4
    md5: 81a63248ed590782395e2fd9fd7fc6f6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1eb8cdef5ee8efd87433c7c3fa1d1f0c
    md5: 9607d013b5392a68b07ed8479f727024
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 32d51f81b058dfef792b37956e3d27fe
    md5: cb794512e94c1cdeb17f7f4505b5bc8f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 09384af7cab9084a819b0dfa1e66974f
    md5: a5b83944e7c17d411c03e3708d22760b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c428b72446423890e11573eb56fff9a8
    md5: bfdb8e9d9658812f4af36b9b2aab8ec9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2632e43476b26ef2940e8e1e75bbb19a
    md5: d403fac52478f45625391a6780e16608
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 51e221f6dac1ceeb593cd8b48bb40935
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_solo.res
  hashes:
    binhash: 9427464ed3ad5faf04a3473eee55853b
    md5: 6f7d3df1a386192417400044ac183c90
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5a44fc10d791a2cbac9a89131b32d9b3
    md5: f605729926612677d1d78535118b2f14
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_thickness.res.nc
  hashes:
    binhash: fa4204dc342bb0acb1fcb788da8a32a5
    md5: a6c293d3ac2a72daac989bf12809d92e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_tracer.res
  hashes:
    binhash: a4d4497e0d0c0656862e4ac5ba493d19
    md5: c89b2ad6ea0805062ef66bef3f17bdbc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4096d846c92e6af1f87deb22aa31fd44
    md5: 1ced7f66aad7b9e0bf934decd5f3d554
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5f224144c62389c22e9936cc6034fba9
    md5: adfd4839a1c52436127f304ff18e470d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 91eded19c741b5f91a6aa02c8aae7ba3
    md5: eee269a3d53265389a8bb9e17b314a3b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart025/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ce429dc951e6a482e0f2737c89f77841
    md5: 57fc72453257c4415918d99362546bf6
