format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/atmosphere/restart_dump.astart
  hashes:
    binhash: 5617fd8c3305c27ff0f08021f27add6b
    md5: dca4904225cef9e44b588f00bfeca67a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/atmosphere/um.res.yaml
  hashes:
    binhash: caf6b70c21633e56a133b191897ff02d
    md5: aa4a7805a86aa969d3e0efeca405fa36
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/coupler/a2i.nc
  hashes:
    binhash: e0a44969fae4873635dab8c6fe74ca84
    md5: 0d7c34c7dc6e184f6d920bacddf5f974
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/coupler/i2a.nc
  hashes:
    binhash: f5361b4574eed63e9fcc0580bd9f6556
    md5: d0fe7c8d89075bfb8bf24b1307d1ea91
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/coupler/o2i.nc
  hashes:
    binhash: eda93477f169c1f288aede0c00bef705
    md5: 0423916cd24e555724a573735718f5c0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ice/cice_in.nml
  hashes:
    binhash: cb8b76aa0a5155274ccc98ed299b1dc6
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ice/ice.restart_file
  hashes:
    binhash: c4d98ac8b202185cbfe39a079d707920
    md5: 1cf707a0f739eafa7450a8672f5df0da
work/ice/RESTART/iced.2956-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ice/iced.2956-01-01-00000.nc
  hashes:
    binhash: 5353794e25ba2d8c40aabb7f006868b0
    md5: 95d9d01ec12ddc6bd515ae9dfe2b5c6c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ice/mice.nc
  hashes:
    binhash: dd2b1168e57e677f8258b6a5447b313e
    md5: 404db506bfc8f1ff32d5757113ae4938
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_age.res.nc
  hashes:
    binhash: 7a72c0aba721cb6dca941c3e9cef51e8
    md5: 247e7f10b848cb81dac019d8bbc3ea44
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 619786259063e524a4a348edc3960a94
    md5: db646b2dc96f27486895156e9622743c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4cf34435fb97f4abdeeb91de9e25863d
    md5: 2115ea7ffd4d7f4c783775d3990aae49
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_density.res.nc
  hashes:
    binhash: 55bc47428e18fef152e5d79ca3958139
    md5: e8bc524da8ad70489553c420f2b61d24
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8354bf77a26c87a9fab7b3872c5c120d
    md5: 76f413bfe0597a64b6914659a6d30e02
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c9dadfd51f317b7198bbfbc242ca663b
    md5: a997220dfcdc69c75ac7644701190c34
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0767172045f9465d2305338efea94014
    md5: 9daaa6dbc81751180cef90ed6011c2cc
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 601a0310238ca66d479799c3186ff1ab
    md5: 77cd5852c40c361b723061e4de0b6a93
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e6b108bec2d54db6697fb076a41b4664
    md5: 727ec11687a164f2e85681f751c7f8f2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a0883fffd04a2665d789db18620c7d85
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_solo.res
  hashes:
    binhash: 6db2f076ed3e3d2c44ab0fa40bfaea62
    md5: c0e709b506a326b314e86522a23f465b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: de5358d2d7cf5113b3215539847d802a
    md5: 612841cb8a0373258554dcad642f613c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2dd00c47f8b8378e2a1ef0452e3e3cf5
    md5: ba7910fe4573d3406d61d931f110cfd7
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_tracer.res
  hashes:
    binhash: a80061a44e0ec67bfca905dc16c5d2e5
    md5: 99c78cdf20fe1f9b168cbb01bac68d17
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a9aa56ec4dfdb7dad4ec14711670f0ae
    md5: 744e9f6cd657b21f9c00a4444e2bb985
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 22e8cb6054e05cbfbb22e4d63d234296
    md5: c0bfe52b9a41c7e1678b52f73a6c9dd4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 84d515ad0e55e0b345c50e9fbb2be259
    md5: a25ef84b2ab24c37db47e4e0e3f2bd1b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart279/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b8efae8295a910a69eb992c2bc25ecf7
    md5: 679e59072366726cbe2c8ade5be3a92c
