format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/atmosphere/restart_dump.astart
  hashes:
    binhash: f43a44f6b4ba0bedd9ea336dd8d3a306
    md5: 18c70703811ba5f32da6d052ac89cf56
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/atmosphere/um.res.yaml
  hashes:
    binhash: ceba3cd894dfcd627e970cf81630b480
    md5: df8cca09e17d3d5ee82183dd8ff6d07c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/coupler/a2i.nc
  hashes:
    binhash: 46db38ce1e8a1e79a30339ceca7eb415
    md5: 9eec6d45f196ed633747c62e81e3df19
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/coupler/i2a.nc
  hashes:
    binhash: 9af0d80b81ace4c361798b2eebf8e7d6
    md5: 83f4690e548d835a9b84f529a66b53a9
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/coupler/o2i.nc
  hashes:
    binhash: 065219332a20e4357912d8984315a565
    md5: 23d716044984ecf7962fdd1054026894
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ice/cice_in.nml
  hashes:
    binhash: c77eedc8839076d619077053b7a62af2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ice/ice.restart_file
  hashes:
    binhash: 1e0d92a88367bbbdd03d944cdd167b8d
    md5: 780d9a1415ca73544d595c276968ee1e
work/ice/RESTART/iced.2905-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ice/iced.2905-01-01-00000.nc
  hashes:
    binhash: 6209e4d91c921ecdd2f7195114681203
    md5: daecee217fafae0b1f0274d48f24d022
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ice/mice.nc
  hashes:
    binhash: 510c1afb48de2e05768398ef6024f5e7
    md5: b931156f3484b6e3e2f52b3a5025ec41
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_age.res.nc
  hashes:
    binhash: 7b3f926359e24753351f372e0b318797
    md5: 444da4a404c3387a168bcd0741a9f7de
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ec94d28d7f03634fff040ff2519117ba
    md5: 9935ada9f79b8bf9d644e28c25216adc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4e0b0328a59b65c4db04af26a16706d2
    md5: e1a55a4e07930331ed2edc2d637d9957
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_density.res.nc
  hashes:
    binhash: a115d88d46802ce55d40564b467a5b74
    md5: d094ac089a8a0c920401f43aa8797e45
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 61fc1a796c0da07a07829921fab7200a
    md5: f186c94fcad3896fc721645daa3f7a60
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 698b7656de31457a1d27f0fee30d3897
    md5: 2ff0f99f0174546a23d5dbcc1f5d5bb4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 35d6ed4ab7778ba17b9329d774650074
    md5: ec5a2831cdb93b89647178a8073fb74e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7a86a416925c23c7cf56c1d5b4985cab
    md5: 38377f0416f02b2ac1e22ad1a5ab5cff
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 31fcce4e9db77aaa7961a28d55aac7be
    md5: 6bd8b50fc8fc66fcbe4861d15da77fe1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 94c3c2bab3eb9f7715bb5f7fa34de980
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_solo.res
  hashes:
    binhash: ce0178132af377d5fea3c88f2b33943b
    md5: 5f7ae5ab8565ecd20477f8a1df10fc97
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 98f30338460ad7c403d3ffa37484ff85
    md5: b880192d90c67e953fdca586708f2322
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ada836d6ed3c45636fd4743c35f2f8ea
    md5: 15f0c0a9f120ec7391a04127b40b6e5f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_tracer.res
  hashes:
    binhash: b5637bf93363f271fa38669bcf05c5be
    md5: 16d39692aef7020680eb4d452a8e8e30
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9e5f016bfd1c62baba53334f35c3488a
    md5: f7eab7b90ebaf96660e5f59c5ad32aef
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 04ad439c4f45c494a944867cb1882dfa
    md5: c6c8adc9c4a019b65957b5b4543d8840
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4bc198328576077bdb5550b46dcac50c
    md5: cd4e80cd2eecde2506ca799fe6b1514f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart228/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e8a8c7141b3808f68ce28401a1632900
    md5: 7e9c635ab7678cbcf6b5b145ed497622
