format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/atmosphere/restart_dump.astart
  hashes:
    binhash: f7729442d3eb51e9acb8a881b013dd67
    md5: 6ddc2625272ac3bb37913d805785c63e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/atmosphere/um.res.yaml
  hashes:
    binhash: cb346565f31c3464106496a289b421eb
    md5: 6fa4d8389236d770f32775c2a05cc2a0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/coupler/a2i.nc
  hashes:
    binhash: 535cd5bfe39ade21f50d2029cba02bb8
    md5: 316598b5cf0fd7acc544f17e278ca830
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/coupler/i2a.nc
  hashes:
    binhash: 30750629a6f26cc0b179325f6921b91f
    md5: 497e9ba539cc5fb1423a2f89bc217108
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/coupler/o2i.nc
  hashes:
    binhash: e2db77753cac9e081213e1a00b100362
    md5: 52537431b3ed40c804614f9cc2e47dc1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ice/cice_in.nml
  hashes:
    binhash: f61ec6aa0d3556c73373b82b4548794c
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ice/ice.restart_file
  hashes:
    binhash: 619cf09c554098a30a54b78b98d3b3a9
    md5: f24e372f3a7350e6cfc6e3868f4ceb6e
work/ice/RESTART/iced.2699-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ice/iced.2699-01-01-00000.nc
  hashes:
    binhash: 94e485bfb37e92053002ec798e84ed0b
    md5: d6a7d52df32346c5460905489b631fda
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ice/mice.nc
  hashes:
    binhash: 37902de87eac6f21ad9e9b4c7a1005a0
    md5: ea22038b679a9f4492bf45136df51bd5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_age.res.nc
  hashes:
    binhash: 1b9418e77745bef7bed1119d332e03fd
    md5: 8d37b1b09af4e741b3e8778c428916c8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a3b2434c5c18d37450a0a11d78d1b737
    md5: 4803346c27ec8115b91ff65b7cef3a5e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: aa852216a00c8a197ee5134b07cebd8c
    md5: 3fe06412bcb07b8409db5e7dba790870
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_density.res.nc
  hashes:
    binhash: e9dddeebb915925cad5900d07db05fb1
    md5: 9ce5397b5dbd5583750afdea12bc41c7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e69901cd8500feb957dba8a3e32dcc86
    md5: 218e94b2f457964559cbbc0a8e7ba32c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b97c249e722d528c227fb4ea8250c842
    md5: d13a0b451ace0b40b9b10f02a7325349
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2596a524268f1cb670c06b91b1b4f08f
    md5: 2ee572b462c004a289a433530254e668
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8425d5c201f2c4c0016b95466fa9f110
    md5: f8b35976a263709622b0f577db44bd12
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 17620b2405d3d4054953274a594f24fd
    md5: f350666038839337f2d93be586e9bbf1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 07bb00abbbb70d77733ef359005829c9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_solo.res
  hashes:
    binhash: 4c638b4fe22c529f9bc55749f8406c2e
    md5: acc313460bca8f0dd67aba79283a8dc8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e0d7fdb7d7001015e6bdafe29195ff8c
    md5: dfbefc8555e830b4dead799c072ec365
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8756ac5de03351360ae9ff458f7cac8b
    md5: 09e097ffbfd39dce58e702497abd9ed0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_tracer.res
  hashes:
    binhash: f62dd78955ebe22a9fccc31199c5b590
    md5: bc6e59c4bea3ba8bdf440bc7821e6977
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7dde5970bac78ca21e2e55516de7a1e8
    md5: c54127e400206544f1ea543ffe6df9f2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 23010697f6e5b43133c1dd2b924b1e63
    md5: 907f8cf70ea45b3d95c8b068f0446470
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9691b43d60bf6711628848b639000a0b
    md5: 4580b12b12c85251e553d76b34ec0072
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart022/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fd494c124d489aa61d883d98d95d1f69
    md5: a76a93870c43720f9662c580c2daa262
