format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/atmosphere/restart_dump.astart
  hashes:
    binhash: 2aa4ac954cdc3f0a15166ffecb4fb967
    md5: 8f003ad78bc3b77c4ff7d77b1ffa0b7c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/atmosphere/um.res.yaml
  hashes:
    binhash: c8667bf762dd93aedeb1484a6b49f178
    md5: 042b20a3cd57e3714fadfcea0b36dc9c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/coupler/a2i.nc
  hashes:
    binhash: 156d2d51888d2b7f53071ad7f0506d1a
    md5: 41f2d6a5e7eb51fe6a8599976bece56e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/coupler/i2a.nc
  hashes:
    binhash: f9bddf21a74efc92710926286361fa43
    md5: f062d72dbf061832ecadb974c32d068c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/coupler/o2i.nc
  hashes:
    binhash: 9ee13f384202f7a853d3c4093f40e571
    md5: e613c78dfc3fcdd786e3cdd7be6a6869
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ice/cice_in.nml
  hashes:
    binhash: ebd4d69c84bb7f59b672ad179eb3b4d9
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ice/ice.restart_file
  hashes:
    binhash: 3459432e865ad8f0d9cf17a07be99ae9
    md5: e7432210d4f9a7eccc0c5e5e0323c4e5
work/ice/RESTART/iced.2746-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ice/iced.2746-01-01-00000.nc
  hashes:
    binhash: 94ccd7e8879967d4c3b0df8d403d5ddb
    md5: d8ad36592cea35236cdb2d4d26f3dc2c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ice/mice.nc
  hashes:
    binhash: a1b397d1b4eea43220e58e52cf3d8f2b
    md5: efcbe447d12730a108e56a3708306fe1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_age.res.nc
  hashes:
    binhash: a6d9c1239a1937c945b6ba093c2ba2d6
    md5: 96daf481a33df8c6d52c7a5cf01d6e79
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5ead38358ad887e2433ae9552b49fe28
    md5: 5d53068d73279523ecd036cd1b5bc7e8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ef22615254ea970245af6043bfbd05de
    md5: 56db253c17c6589cc7d8d5e17787394b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_density.res.nc
  hashes:
    binhash: 4d1b87a17c9f2decb477b55e77fd7b68
    md5: 708553edd359e2ace98f9940244bd501
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 65be471b43fac5600f49df3c95280fad
    md5: e92138e6d04854910a1b0a60148a8741
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: cf31e98b3cd4b82dc348642a1d35b279
    md5: b02bf3a38baec4de55885b6c65a88b69
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5bbdbeccdd5499a2eb445d9bdcb6c5e3
    md5: 7a0eeeef736da5cc295f9df737e04122
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f0481ad2bc39476b84a9867518536e54
    md5: 40b94a1f761f5be363f68e5d0fc68f3c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 30d359b85ec3ae25cc2ef283b44f1d63
    md5: 040dff085871244adc0390e06521334b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 71d3cfc36f5b1a1d173257c08e0a9ccb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_solo.res
  hashes:
    binhash: a4654f5bf9925606748f09cc98073591
    md5: 3fc5fa3ea9297644bd014caf16b7c615
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 631a4c11d4f37a20bb1b6b73c728728d
    md5: fd49216699ee18292b025a63552a964c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0f3acb6c74aa2e8dc9495d0c452adfdc
    md5: 2f661ea8501387f0c63cd65623b80f8d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_tracer.res
  hashes:
    binhash: 097aef5c30f06d8dbbb4a49cacc1d653
    md5: dccb405cac5d03ad1ba95c98db2c70da
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0f2f5a354a729c964fffadc8c179fc39
    md5: c4e76c4f01b4e6172f6efec00fda09db
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1af17c71219ad7fbcdf86e6bfc9ac644
    md5: 8be4d9101c4fb86c5778e5fbd15820e7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5821da89f2c7dfcd04ffbcc9e229c578
    md5: 7a5584fc4e49cc9d71c3f7bb557f855b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart069/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5771be4d01f52e732860f26d1ad7f27c
    md5: a6d36e0de85c18e699088ae2313a41f3
