format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/atmosphere/restart_dump.astart
  hashes:
    binhash: 38d6a4cf3019d7ce4edc349c70faa688
    md5: 4c3dc89e653a24cc0f1a87dae6c6c7d0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/atmosphere/um.res.yaml
  hashes:
    binhash: b503829a04ea1f29c6d0b4f10b48b63c
    md5: f48655649ec7754d9f49082d3838be22
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/coupler/a2i.nc
  hashes:
    binhash: 77860f9a90117e4aad20e02335660e76
    md5: 425183a3369c26ede5274a6c7a74f925
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/coupler/i2a.nc
  hashes:
    binhash: 31d2c63fc18097f44d6693e35152cb1c
    md5: c20e6c6403001fedaf73e77e36dafed9
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/coupler/o2i.nc
  hashes:
    binhash: 98b818fe6786c5449e1db8406653d34e
    md5: cd9eb7e008d2345a1afb65f446e8806b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ice/cice_in.nml
  hashes:
    binhash: 93f24e4b3968a3656dc047ac2a14a216
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ice/ice.restart_file
  hashes:
    binhash: 6679b13fe90bfb5b62d7138ec2fe8f20
    md5: 73a9a2a5f30abcd6d4f44ad8a628c615
work/ice/RESTART/iced.2777-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ice/iced.2777-01-01-00000.nc
  hashes:
    binhash: a48a66bef8b137bc767d6f8321806b32
    md5: ddbaa52463e2d5cbfd7df8f10c8ab975
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ice/mice.nc
  hashes:
    binhash: b979201c0a4e20733b96f02ed4551a52
    md5: d1f99380b612035a75080b37daf3d0f9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_age.res.nc
  hashes:
    binhash: 119c1e7df6ec2697434049a2f75402ed
    md5: 9358540feba5cdec52d3ed3bb02c4c65
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3cde1c4e884eadf49d87ad7d4fd38fe3
    md5: 8bd5134688e181285468cbc4e8820504
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e6eb9c9fc19275d27034a477478cce3d
    md5: 5c4e6cec5ec125230910b7a686631e4c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_density.res.nc
  hashes:
    binhash: 6f05ae896b5064ceec273527532f6f71
    md5: c9016050e1c98eff4d54bd66da112fd2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 027005c8cbaa7ae8d025becaa321bdf1
    md5: 760247aa2020082c6f26d6ad1759d2fa
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7f8c2099b7c8c644959d89fbe5a89dd7
    md5: 0b4cc3f07749eea3f5243d5b2adb71c2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f040c30bb28a5dade41ca2a5d9e0edfc
    md5: 5f18827865342e85ae96198a8fb684d2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2c1be054e4641d9144bb8916738cc3eb
    md5: 292a53ebdcb2bc47c323bee9bb60d5cc
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 29b81fef89520cb67b731e7a3383c208
    md5: f2f2d26506628359cec35adcab52a0f9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 88e9647553c5c7ef1a726a2c56e8f34f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_solo.res
  hashes:
    binhash: e2e94b3601c871277430678e990da327
    md5: 52e8729de3ccd06465ee16780be499c0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cc50879a75977f54dfcc621256f4f72d
    md5: b31b0b83e7bc6b495cc8b6a6fcf6eaf2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_thickness.res.nc
  hashes:
    binhash: dda64a3b37313ec63d9e83b5e88cbe47
    md5: 9aec1cc32cda29964ae4622a892281d0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_tracer.res
  hashes:
    binhash: 5cee978d57d9d09cfcb2c9335bc208e8
    md5: 6969ef45b34c83866e49ea04c155d4ec
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e29fbdaa6295ac743b3b497ed6fb12e6
    md5: bdd340f3790e9094bab842f2c42962f9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c39f8d16ba805b644eebd0e76d12521e
    md5: 621f17064552d0f792fa6a1f07ae1423
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4f87b6586a599ef36980683492594848
    md5: 626c79524c0cc18f653072a619ee86de
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart100/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 662f18d81f2cacb31e01e5e31842b994
    md5: ded6014d4d2c3226c4a056c076c79b9f
