format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/atmosphere/restart_dump.astart
  hashes:
    binhash: d5b2537f102e939d0dcc032243cf5bbf
    md5: ae11937cb542984fdec33b500fc04c37
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/atmosphere/um.res.yaml
  hashes:
    binhash: 8a45bda5bd28c648d07cd4b119988e5a
    md5: 867727d2eb1fb2ec65060fc315d3a13c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/coupler/a2i.nc
  hashes:
    binhash: 10d79be86db707b65f8d5745cd4195a6
    md5: 3d15198e1aeeeacba4fedac534d5dc0f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/coupler/i2a.nc
  hashes:
    binhash: 152b8fb63f65c35ee6b2714b56667aca
    md5: aff985f710517b310669fc7c87350f6a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/coupler/o2i.nc
  hashes:
    binhash: 84dc62b01cf9e39a2a71a70deb0428ba
    md5: af40633a1f5c548d1f87dcdea76395c1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ice/cice_in.nml
  hashes:
    binhash: 71e54d7282349cb8ca5556ff1a5d3d63
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ice/ice.restart_file
  hashes:
    binhash: 3b8d0932f1d787c846d84eab4b6b5b85
    md5: ea53fef9d18a040dda55f163dea80f3c
work/ice/RESTART/iced.2786-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ice/iced.2786-01-01-00000.nc
  hashes:
    binhash: 934e130b1037300052fbe2f096bd8d55
    md5: 20b425633f4c3f30ea15c89725f133ba
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ice/mice.nc
  hashes:
    binhash: 959df6bac3a824bd6e1b810724267485
    md5: 6af787001cf41a74ed8a513f58dcc43a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_age.res.nc
  hashes:
    binhash: ca0c1394e73b9c1a9d7b5e92eb51f990
    md5: 33ec5951febc532058f74eb1835bc6ce
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 526cb456faba6d70f59d72657ee9c41f
    md5: 48c41052d3d8898d72ece0c372dff32f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 127b3556b59963815345d5962b9b9751
    md5: b999416aab0a81b269411c749996551e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_density.res.nc
  hashes:
    binhash: 1414c034a742f5df5160833680a4b9ec
    md5: 85cdf40c4de9c7b64660ee8caab06fcc
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4dd7ba6564d575756075d8f803dda5a9
    md5: 4cdd866686a48a13fee72044729e23f0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a8fb3e773f8b453daba10b49bedd3858
    md5: 6ca9c3645fc16aea966b14302524a0e0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 43900a31701d91ed63cd802e7a59fe04
    md5: 8ac200f3200680831582fb01b2dbe395
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e6438649b8f844246ed9d9a9fdebe5ee
    md5: 65fe8c84936033b2a406961cbaeef21a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2bf157aff3c24db41e2cc4f096e9b6da
    md5: 3263ff0c72063d6112ebee299edf1744
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0950e92d3812acd75510abc4031be58d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_solo.res
  hashes:
    binhash: b0d7e9c57eeac74ad4024b8c38e0b3c2
    md5: 0cb38e0368c39b529b109052a196caa7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f73be554186df488bd826fe165e954ba
    md5: 28cbb5b4c51a60079bcae5bd5388c8ee
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 67cb8833b555c1bed106d14dfe7c48b2
    md5: 4698ac4de83edb7cef92afeafdc7121f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_tracer.res
  hashes:
    binhash: e829d4a18fa12dc99ef2177f312da94c
    md5: 9b5e87f6a98213be5af8f3007b58db23
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 19332044700c0ec4cf4e2e167b5f97ec
    md5: 726c4d5f23ac4bd3f5b1e35d0f0a902c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 32170d674a66f319bc27c18280fa6274
    md5: 3ff619eace2e6722c8c3b4b5d22ee826
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c87894e37efbf491182c673bbc79c536
    md5: 5aa8586595e58696ac5d3f6d11302e4b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart109/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 76e38d172eb2cbf982e35129098c7a90
    md5: 1bdbc212670dcb21084c0e4eac116c59
