format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/atmosphere/restart_dump.astart
  hashes:
    binhash: d533ef5a5753827d87d0af3c9a7985aa
    md5: 665d9e7cd397aff99d18ab5b96215da3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/atmosphere/um.res.yaml
  hashes:
    binhash: b52fb2b7ef955ffc97ba62c63f5f5001
    md5: 45ce97b792efb8081ffeb757cf79b6f1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/coupler/a2i.nc
  hashes:
    binhash: b069c091995faea138f4e99b26afa164
    md5: 563d015d463d7ac0d3d801312b2b12f4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/coupler/i2a.nc
  hashes:
    binhash: a5bcf71663d91ccdf7570a0ff4e86df2
    md5: 7315e33ce461b274867d31b3d24728ba
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/coupler/o2i.nc
  hashes:
    binhash: 08e3b12b8afcf37e2cd54bb910d0633c
    md5: 2de79aca4b4a31ae40b3bb855edc3681
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ice/cice_in.nml
  hashes:
    binhash: ff810f9576025138a4426c67ba66bac1
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ice/ice.restart_file
  hashes:
    binhash: 362e0badadfc77f7ba6a1171492e3c26
    md5: 3eb344ec88acb525bb91eab6c9ac7c1f
work/ice/RESTART/iced.2850-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ice/iced.2850-01-01-00000.nc
  hashes:
    binhash: e97884a169ee020fca5126f709d0aa27
    md5: 2a8da8bb083e0fb1306bbc1a49637cd0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ice/mice.nc
  hashes:
    binhash: c3354218981c036b6277e4243f35e8ae
    md5: 132f0b9aef3604f332c3079fd9403d65
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_age.res.nc
  hashes:
    binhash: 34d8ee3b933016f979f88dcfffc470eb
    md5: 5d8d0c3cd78aa8b8ad7f88b827450cd4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2ffa8061225dd7d985759dadee8fa0f7
    md5: 2e358f7c7c0f37af3ea0f0c274ca3fd0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: d4e33393687985a5a72fc2997e601563
    md5: ae389039215305c97021cc97ccb3fdb7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_density.res.nc
  hashes:
    binhash: 4a9cda62197eeb978609a8df71f28fab
    md5: 41bc5e0acc32f3568395be7033cca66f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fb916bfceafdd030f40468510507c237
    md5: ea6c81a4029ad4a90d6b3def924d2334
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bf613ab62ee8675291343998a3889324
    md5: 5f746378c87962fd406a30606941d9ea
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 34de2a84c7d6bea66fbfacb581ed2f3a
    md5: 552731ca3e6142aa536fdf8fbdc16a86
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d70ff4d5542bf8c9c14f03928ec96f23
    md5: f89b66e2a25f398468dcbfa282476122
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f840a37496adf1c542d7338deb2a606f
    md5: 25e134c6da51a2a5182b817df60ebf2d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 20754848686cadf8b2edcff94199f579
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_solo.res
  hashes:
    binhash: 055a2af63489943cf284c1274028aaf0
    md5: d8dedd39388e54340e8c2a3562af572b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 48d3aedb2f0a5d26c317f09515b82533
    md5: 79b4b16735db9194e4c49525c2cafc89
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a57dfd1c166ae758083b03bddd68056f
    md5: a068f23aa929962139c8f99915eabf0e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_tracer.res
  hashes:
    binhash: d5c6c28a410ecf7aab10b70b3d413028
    md5: f7da9a61baa3752d8f106af792177bb6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 81c57680ce727597834f481ac4ee2a4d
    md5: 26ec8c30da505f7b22ec05f61e59f839
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9102a0e684174bf522e83b23dce44f99
    md5: 9cb175a298d32bda771ec6a4d77b7ef6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1759137071e53d589668975050b04f72
    md5: 90c94eec364de20791416325a963862f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart173/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 489d333531beb81a8666f6992ca848d9
    md5: b5b8e7ab795b9e7513aaf4dd1d84b4af
