format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/atmosphere/restart_dump.astart
  hashes:
    binhash: 135dd6fd80fdf6abed7770a6346a26cb
    md5: 1f36e5c30a19efd3f5a39f763b7deb31
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/atmosphere/um.res.yaml
  hashes:
    binhash: 53f8171bee96f1a2a03d1c3eb62ad966
    md5: 4c7924c96cea1323480a6ce7ebbf5a31
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/coupler/a2i.nc
  hashes:
    binhash: 80f679e20ded77270afebc8aa5cb34a8
    md5: 127cf72570150f2174832e465269f0ea
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/coupler/i2a.nc
  hashes:
    binhash: 770b93dda762289ce1df84e362176caf
    md5: d04043c835ea6fb2f1bf83516518a3d4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/coupler/o2i.nc
  hashes:
    binhash: 3a7e3c25d93cfaae18c8a8df074319b3
    md5: 659eaea982ff4481d0c8345c64ea24d1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ice/cice_in.nml
  hashes:
    binhash: f9ed1017511835e2312eb06cd3c56a0f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ice/ice.restart_file
  hashes:
    binhash: fb04245679aa3360952f743b2863c20a
    md5: f4bef97aa68beed9b80e8aea186a6295
work/ice/RESTART/iced.2774-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ice/iced.2774-01-01-00000.nc
  hashes:
    binhash: 69f38e6498093f7582e3978a03e45933
    md5: 7fd41a534d4de4ec51510d033e2ee334
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ice/mice.nc
  hashes:
    binhash: eae78fe7bfdf3210703c9d42b47b7a7f
    md5: 22acf534f1f1fa771b34dad2ccbc04cb
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_age.res.nc
  hashes:
    binhash: 7962b3c045179194f88a370a1be0503b
    md5: 29fb1a8352df7736b9d28b05728f6223
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 126b7cb1524668cf3253ad5a4b7404f7
    md5: dd96328a49fa30e0eebe4b822d544610
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 75e154991d794043777e6535570f3c55
    md5: ec77036faf02955d191f8ba74740642f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_density.res.nc
  hashes:
    binhash: f363d84f6cde5944ef7120e955111d54
    md5: b6189798e1afd00289934fd040bd132e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 83160798182926d09b8e84dfed56da1e
    md5: 09876d66d4e2b46f5e534f1a5db3180b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a3710561118d935786b865121af48d12
    md5: d45877a9834e4ccb2b99cba45f4f53bd
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c2dde0730a3c07d1b9dee4ecb6cded87
    md5: efa21783db5839c2ce9075e89f9b62a4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b3ebb87bd409cea532f99788aec423ff
    md5: e7806343b3f8691039e9f1b18083e06e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 966f5a8c5a455e95721b18a7aba66c1d
    md5: eab44a4e86acda8d7acdcbdd40e55353
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4ec0cae3611395e14857d4a3b57ec3e4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_solo.res
  hashes:
    binhash: 84aaea4b7d59b0b0cceb46352b4ba2b5
    md5: ff58ad0186dc192b5959e0819feda886
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8d138e0c2bc2649a755d025d499f68d7
    md5: ce777bbe8bb9d4c07804393b3873543e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2279c4b5f2c518a5df871ac55444acac
    md5: bb20d4560b9e14d8fec100c7ba8aca8c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_tracer.res
  hashes:
    binhash: d9066429c7f535276e450e9e24da7d7d
    md5: 44d1568233fe1bec547ee761dc320770
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ac57f217e0e7d3831f6169d9da449c2f
    md5: 5c5299837b69a975bb96ac9ef93b2144
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d786c3cc8d736aeffd5841197f1dd656
    md5: e88d1c6583ca123d4cfe188b7296bd79
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 654b24d26ae0bee743d7eb7f0b1be9ea
    md5: 88afc3af1aa23f166015aa651585be75
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart097/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2da5e939d7b3ea339f8e80f5f2b00f16
    md5: ba6034df733162e44d6393dbf00b3c63
