format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/amip/restart/2026.02.23/atmosphere/restart_dump.astart
  hashes:
    binhash: c87d2fc33638439cb4685ac820f32530
    md5: 6de0c085f8ddc19f44e8aa59fc32e67f
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/amip/restart/2026.02.23/atmosphere/um.res.yaml
  hashes:
    binhash: cfa0dec033068e705c7f862aaa676322
    md5: 2040b7490b72ee39c2693667166461e3
