format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/atmosphere/restart_dump.astart
  hashes:
    binhash: 6d5858d5e921747bb4492d0c71379580
    md5: d65bf9eb552ef3705a0589dc6f6faceb
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/atmosphere/um.res.yaml
  hashes:
    binhash: 7da4e9c38a26391c1b68b1862b241bd5
    md5: f5307351dfeb7863d90209bb30500be7
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/coupler/a2i.nc
  hashes:
    binhash: 3574b18513c9596d4beb050fef52cb58
    md5: a0705dfbc3435320d5b0c65119430e80
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/coupler/i2a.nc
  hashes:
    binhash: 9c5375f456e0d9c21cdfab90095312b0
    md5: f2a8449927119b6d7676590f5ef3cec4
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/coupler/o2i.nc
  hashes:
    binhash: 898a3addd6b8853ae46c3d38312717a8
    md5: 424e12481d4827ebdcf12738ea68d8fe
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ice/cice_in.nml
  hashes:
    binhash: 01632412802699effc152a3acfe99507
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ice/ice.restart_file
  hashes:
    binhash: 7b8530257880aab18906de5360828daa
    md5: 6ffb313c0a715bd962769f972fe8aebf
work/ice/RESTART/iced.2676-01-01-00000.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ice/iced.2676-01-01-00000.nc
  hashes:
    binhash: b4ed0a94897ca3e404262f472ed94fbf
    md5: 53ce8cebad1d2fba41d58a07d055d2f6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ice/mice.nc
  hashes:
    binhash: 861980e5b55714e9ff1ecf1e5dac5621
    md5: c71f480eb83945a5138db052b91aef6a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_age.res.nc
  hashes:
    binhash: b6266c97b6448106b812ec9592171eb3
    md5: 7eceeaadc40f68654ac01c13929acff3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 003717c81238d3e9d1c6af3da2228cfa
    md5: fb21f6c407252ebb063daa14eabf7c42
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a63ae46e32addedca21379b578bb4087
    md5: 17eb6887873fab1a7893a9af97791dd2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_density.res.nc
  hashes:
    binhash: b485cd6a67153d1fef70bbec4c1d14a1
    md5: c76c29f0c2f9ed805d687e6f69d18e4b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8c4a8a52e025fde85776fb31770910ca
    md5: 8bfc7a175a5cd83253ad25eb163551be
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2b626e5c56b4a525f5b8773824cd8b72
    md5: 7fa1f8541b4fb08e267ec7a1b53a817a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 191038708670bb0233439f06b74d05fd
    md5: 609965c633d18eb742fa810d9cbe4395
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7c86510d4aeee5f06d2bc1d87cb86752
    md5: 4fbd75b94fead7103fdadb4f1665e751
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 75e0c57fdf235d2452138d2447aa0f9c
    md5: 95e1bd4e65a8fba7883757f4ae9d20a6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ac177aa9fa05ac0bd361c095d084fbbe
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_solo.res
  hashes:
    binhash: 19e8d5641913114abdcd08b80cfa30a1
    md5: 241cc3f69d951a2e25860d212a23ff79
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 166beb9648b96a13ad1f9da3af9ac196
    md5: 5fa6b9508886f9f8574265672f1e8310
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3d9e53c3bfd5c3a465af75c3cb74ada3
    md5: f7e5deb8d6ce99a24e1d94072d6ddf09
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_tracer.res
  hashes:
    binhash: b23232c5335e443c729b29fb67d61194
    md5: 573b342d4729db00dcf8ab58166cb707
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 39bbe38ad0090a6d78a47c131f25b88b
    md5: d78bdff14e081dfc6064e92f75c56c59
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c8630f30cf98b1027c9ce60e2530224f
    md5: 7d5936788f925b717f8f48008e07c345
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2ca9fdeff6aaf93dba4e5e51c082ce97
    md5: cc1b35030bf63b2f47c264055546cd88
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2025.12.22/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b79b04403c0ac035ae0e7f8197b9ce5a
    md5: ab126b4a4b67ed259bc9ad42d3b598f2
