format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/atmosphere/restart_dump.astart
  hashes:
    binhash: f982ea8d8b719bb48a6571100a74d748
    md5: 0d6e76e2bf0bbd28d8fc23af73bde757
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/atmosphere/um.res.yaml
  hashes:
    binhash: 736a2878746128c8ebd12af4acf6c057
    md5: 6c2fdb1bb3fb96e5749ba6d13629022b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/coupler/a2i.nc
  hashes:
    binhash: 3e2b4de90e95575414fcabaffcaed653
    md5: 2be1f13c933d5e18f79c1ddb5e820375
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/coupler/i2a.nc
  hashes:
    binhash: 57a1f9eb0e64755a2f6bf11d03cbc70d
    md5: 960c7c1ddf4bdef403f7121647290c57
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/coupler/o2i.nc
  hashes:
    binhash: a597571222b625efa46f8770cc3cc82f
    md5: bd7fc306694b5f926a200bbd1778e497
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ice/cice_in.nml
  hashes:
    binhash: f258f00beaaed219cc23ac7a9991de41
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ice/ice.restart_file
  hashes:
    binhash: 80e8b880372d9f5cd7fe0a81a0ce0a67
    md5: 54ca0d273b58b21be1a80007c174215f
work/ice/RESTART/iced.2790-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ice/iced.2790-01-01-00000.nc
  hashes:
    binhash: 9184059dc523dc4501cb1551813066c2
    md5: 02bd5e9ba8d8f34a2e65763431d9a780
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ice/mice.nc
  hashes:
    binhash: 5d78c82d77f1979b9e0652d5199dce33
    md5: f6e5677af4fe24a0891938744e693372
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_age.res.nc
  hashes:
    binhash: 73031a90903b378a38f5fe095adcda13
    md5: 316d05f90c321585b9358b517da44086
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2741df62f9e7cd9d63a379b816e9ff35
    md5: 47dcaa319f156a3741788773339554b7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: dfd89bddfa5b76e61a45b845b0cfa9f0
    md5: d222cd5c933f574af488a87a59bccadd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_density.res.nc
  hashes:
    binhash: e40cb4435b1d88ed9843d857cbe0e8c6
    md5: 234a1c4f91df411a04ce705e05a6488a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fb7c60b279eb0f8fd979b73e63e76f56
    md5: f2662e1e4586edc40826b43ce82198e1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8627790bc58aee09ae3b638d0a3464b5
    md5: 648f016d31176e373153e806a8f3387e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 00f156b358da033c050877068e32b6fb
    md5: b1b4f6c55f196af71075eb110c7bfe11
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7c8eb2f70806542ddd560b0ed21c2f73
    md5: ae9ce0e1556d72746d5e0168538602b0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1b0a7d3ecb7f083ffbe7fa9b4d6d47fe
    md5: 5ce3990dbfcb0e5e42237c552125e9fd
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5e399e7a73c7a38aed0f3dc2f948d3ec
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_solo.res
  hashes:
    binhash: 6d0e1cc44402bcb9659a0c391713c7d5
    md5: 2609365197b03e76e0082bceec323491
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7d71958cd43cfd4fa0451c545bbdff2e
    md5: 76e2af6ea401be4be11637a7f1c44223
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6dd9bf6d5011d2a7e9faf497efe33a54
    md5: 1348945fad5fc289f02c7e1932c17a46
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_tracer.res
  hashes:
    binhash: a0c658a078f0027e080bd676106814b5
    md5: fa11a439cd271e2cfdc06368dca4c8d8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d3ec48949f56a0023144d428a76b644e
    md5: d87b26725657deea4efb91cf12f9ed0d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: eeba378bf88b42f14e3d69bd0b949f6f
    md5: 7a88fe4bd5dbf0f3a5daf32c357a64c2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8cd325d481b0ac8cdec61fc750fb45dd
    md5: a798605d4be0582cca1d7cbbedac13c7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart113/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 69ef173f18d0c71b18164be0a8827c86
    md5: 80558c1ff4533df2538c92d38d2cb59d
