format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/atmosphere/restart_dump.astart
  hashes:
    binhash: 4ddbf4e163fdd47e692a60cafc75e960
    md5: 405293402d7da41a6eede01375c7a814
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/atmosphere/um.res.yaml
  hashes:
    binhash: d2e38fdab83b76bff623860328337e09
    md5: 8f6ba31e1e1dbbd0cef86332ba46aff6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/coupler/a2i.nc
  hashes:
    binhash: c7a5958f55ff67bd2b972ff5a7a23c57
    md5: ed3a01f32c210510ee3b2cc6015ccef5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/coupler/i2a.nc
  hashes:
    binhash: a3126780412d0bf7f575ea4c3b189bff
    md5: e9293dcd60cf1c4bfd1865214d4e6ece
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/coupler/o2i.nc
  hashes:
    binhash: cfd625ec1f4798e92cc6ddb9d22de232
    md5: 5301e8f70f96fe9a9f0287eb65e396d6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ice/cice_in.nml
  hashes:
    binhash: d45327c3f5bb66044589d4472a971f10
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ice/ice.restart_file
  hashes:
    binhash: 797f21960e37bf85ea65865be1eb6c18
    md5: 9da73d6c3d0dbef2aff2b933a7e08845
work/ice/RESTART/iced.2833-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ice/iced.2833-01-01-00000.nc
  hashes:
    binhash: 01aa112e1ca32e1bf952fdc838c97eda
    md5: d7062169985442fffa855b1c43f043f4
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ice/mice.nc
  hashes:
    binhash: 222823c2f1624eda0c6f123e7ebb7773
    md5: acfddeffdb842a13bdebd10f7f195dac
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_age.res.nc
  hashes:
    binhash: fe7e2a30fcf9afd9ed9dd1dc59970375
    md5: cf1c8630ae0d4f541d11e55929639122
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2e5e944694388e45f10018c66340d74a
    md5: 02c8826cf89e71fc306d0f7f16eb8a70
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c753aacc03fda7574b280e3985df0cca
    md5: 2943306771b9035f41ebf18e892c9139
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_density.res.nc
  hashes:
    binhash: ec873b78eb3fb54d6aac21bbefd83f02
    md5: bfd2ecd2050647502e806ed4f8c81133
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f0398feed9ca6595fb643b6cd075717a
    md5: ce135239115c72b8095d8fea38b1f361
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4c4c6504fa0c2279d38e39ce2a707194
    md5: 049831a2b70b1127abf52210f70dd2e9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c112caf014ad7d4312794585f8f71623
    md5: 6b4c33f4987b6d8a6a44ad534519863b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 28c3c8526b73d0ab2d5e0c5f82b9e7a4
    md5: 5ae037790f39b16bc80464295522869d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_sbc.res.nc
  hashes:
    binhash: be9533a71ea177b31d6ab5dee4340f79
    md5: 20f7dc5146250819500e9787076a530b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6693171d7ed7fe29975ba12f78ba60aa
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_solo.res
  hashes:
    binhash: c2f4e6b81ea406cd9cfb86eeb0c94949
    md5: 71dcc0cef6eff30cbe8fbdf658302e00
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5dbd081687f5333c3cc5724348a9a788
    md5: 74a390a6d283c55aff6e9811c85b3f20
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3a393a90e7b35ae8c2afd3dbeeff3389
    md5: 941c6c2b7055ce10ddcdcb61d2d054b1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_tracer.res
  hashes:
    binhash: 2f4ee9441496b67cc4b2606d37b4fdf3
    md5: 1855b35287382f779fb29f64be9d6352
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 277aab76887c3dc0bfa1b64a0767817d
    md5: 6db80859592bfc4c0f728706cd68b173
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2f8e8de44fa728c8065d7a85a7ceab51
    md5: c0b0a0cb64e2640940da285ea6ed0922
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e7066e4e5b044ab9d338b2f99d246620
    md5: bd119849f536f2d2b904fbbc7610e6be
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart156/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2e352dcf7d4a7269e46fe5d596c6d436
    md5: ab2ddb56e9b5b2b0dea030bb6dd82d8a
