format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/atmosphere/restart_dump.astart
  hashes:
    binhash: b0aac1e25e43086202c172a94d2f13ec
    md5: 7b66a3e5f4283cd5d318654063d6b67b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/atmosphere/um.res.yaml
  hashes:
    binhash: fa956b01bd74795bff035845ed047010
    md5: a898a988751ced8ebc196f87b6638308
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/coupler/a2i.nc
  hashes:
    binhash: fc5469f9617e78ef5c5062a02386808b
    md5: f0fe2dcda6206bffd9d04af10142a7f1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/coupler/i2a.nc
  hashes:
    binhash: 82d48e6c0684affaf826013e29246150
    md5: 43ec7d16eb4fc9bb9ff93690fe1624fa
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/coupler/o2i.nc
  hashes:
    binhash: f4e4aee9707d85bba232ab840e21ae8a
    md5: 3597fe904d1077880b3dc0158bf44b2a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ice/cice_in.nml
  hashes:
    binhash: 6a102ba75fde32661e58381ec43e1ac2
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ice/ice.restart_file
  hashes:
    binhash: 33aa44ff9d501515e0f983e4ed92d4b7
    md5: 74b6d3336fa9429b5114f95643332b59
work/ice/RESTART/iced.2857-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ice/iced.2857-01-01-00000.nc
  hashes:
    binhash: b1a87190df5ee5cbdd7f2051d6115336
    md5: 5da6be260d415bac79052df5c7d00c96
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ice/mice.nc
  hashes:
    binhash: d21f65b09906ac3318fe261bcb9a8ca9
    md5: 4d0d9a966cfa8a000dc0921053936ad0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_age.res.nc
  hashes:
    binhash: bde092321d264ad71fbde2dc19f8388a
    md5: 729ffd7495b66556ef0061f246088024
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6d15c8e88a2cbf59d43f200e47f8744f
    md5: 55e49c043d8a306632aace7cbd60c113
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e1557c310fc4cdb6bec1f2461525479c
    md5: 92454222e4d4165321691dcb6bc3fdb2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_density.res.nc
  hashes:
    binhash: 6c360d4d80d215dfb8212cb5e6c8cbc8
    md5: f066b117fab223a3f1b3353c98228630
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 83c9621a6a8b623cf00ba89ac5b30811
    md5: e832bc81ab0845c0fe5885ed82f7b439
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5ec42098e6515f7ab3185a2e4ae4bffc
    md5: 9938b8edc0ebbb7f5df3c03d3b343309
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4cdd201725a9f36ad120410931224053
    md5: 192c48c17e51262f9dab2caddd2a5329
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ae817710a3e4c0df8e861fbf503451f9
    md5: 56d3daecdb3928bd8defc53e4dec28f3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bbb88b7947232783b800a34df2a8ee9c
    md5: ed87ab69538cfff6413266155d45cc7e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 134283a359a964bd72a67b653fb3506e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_solo.res
  hashes:
    binhash: ce61cf64b02c93ea6cb51c17953343b4
    md5: 51948d60b4fd3da789f3ca5c4683ba87
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9e61a5580cfec8d9047cd3fcee82004f
    md5: 7f7873001078ddc29a1a20c47ec5a3c9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 708cc19739bbd7de2597880162131033
    md5: 63b23825d582993cf0c4c541b9120652
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_tracer.res
  hashes:
    binhash: 0e3c6f10401eb886ae7910f601568d9e
    md5: c099e4e8db94e56a4a1c93383583539d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0db3d9b858345ae255b075e21f4b667a
    md5: 41fb1b41b1c8005f2632580279ea8c28
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a6353c1dc761dfef341cd40414969936
    md5: 322b1432b5f293d3098405349cb48893
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: df3ae75d037045ef7ee58d36a29baf3a
    md5: 2e03028a4bd59ddbcf34c6fdfcef046d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart180/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2ba6d9982db440720861538785b6aab1
    md5: 117349385fc453c64dd83ee1f755d879
