format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/atmosphere/restart_dump.astart
  hashes:
    binhash: f95d07b1a4447668d320a9214d728e17
    md5: 6d16e98f35ee9a0595d4df5bea4bcb75
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/atmosphere/um.res.yaml
  hashes:
    binhash: 2de7f945d983d4e01c93e2d46480c056
    md5: 4c73c6684709a0026bddc9a04f5f5c8b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/coupler/a2i.nc
  hashes:
    binhash: abc253cc569df28e2507dc4490cc13b1
    md5: 2de01a6bea0870499d488ba6331ce58e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/coupler/i2a.nc
  hashes:
    binhash: 541c9daab5d8bc1050c5d4aada59f884
    md5: 36a6a99eb78b620c0a058124b9dc06a8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/coupler/o2i.nc
  hashes:
    binhash: c3946e6d7133914d394ce13342769be4
    md5: 3fcd7ed1851b30c6a87483b6d1c57a82
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ice/cice_in.nml
  hashes:
    binhash: e08a305c6c53ffffb2cab0994c3f1efd
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ice/ice.restart_file
  hashes:
    binhash: a62608a0c4692a4280dddbf1a09e4526
    md5: 628759e8fb7dd51796115796e52ab2b4
work/ice/RESTART/iced.2807-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ice/iced.2807-01-01-00000.nc
  hashes:
    binhash: 0fb4063e955af2643419fdc1645eaeba
    md5: 1fd85cb86d481567afab0d55ae57c6d8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ice/mice.nc
  hashes:
    binhash: 1bdbd8660e7c4c530a4e31a0529d25e1
    md5: 1695293c0e7ebda8cbd2ee36cea5226b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_age.res.nc
  hashes:
    binhash: 62b7b03a8dc88e33dce0e900b1b73ea6
    md5: 909ffcdeb47e90e48f0a5eda972181cd
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f0cf38f9a32d68433dc030996b5e61cc
    md5: ebd17b238cf8b02784c1a33642bc770e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 23a48c726215dfbc37833563c0ba255d
    md5: 358e5bdea4c245f32c02237c0a552e00
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_density.res.nc
  hashes:
    binhash: 3f95cacd229bce072ab8d3f7e6f0b18f
    md5: 9d5d419466fe041c7f8d6a77d506f7cb
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1d89952d69400b10d7c6d33ce8574078
    md5: 183aa88de343e0dbe8a81b968a44a243
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f94ffbfeaeb227e2e370de33855abacf
    md5: a26708520aa99bcfecea40b8f3988420
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1f60786c1720471e0120e6e5ff0870ff
    md5: f1c6b81a13ee7c56f4abe377ed66283b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 728c31b19c5ba40876f84c0784fb1c82
    md5: a83b354f80e0323cff83354cd5801358
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_sbc.res.nc
  hashes:
    binhash: adabbf3a1bcad82a31e828602d545a64
    md5: b6c84bdf0092e7b32960b8da0147d4b3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4ca28a1e8de6d72d8ceb1d472fb03ed9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_solo.res
  hashes:
    binhash: b625238d8fc2d5069d96cb97ab851720
    md5: 66b925fd33671cb1529ff49408ee46e1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e62721f5d151661c6fd1aed8b9ebe7f4
    md5: 4057a531d02c2bb7ca0ccf55c615a834
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8e0706fe5eb07f289021c984c7f79a73
    md5: 896c8fe05b2a63cfe4b780fa38fb57e9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_tracer.res
  hashes:
    binhash: f4aaccb7f72a025a9bbfc60c8f51f9f2
    md5: ff2d4cf5e56df7683e2ce6ba1dcb6cfc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 613c6ad844017216686f0f5330f29df3
    md5: 35ec669374840f8dd798ce5b9b8deb56
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 337a8251ac0ec148f947d2bdf314b000
    md5: 952b270b9b19a6b3a842f5aad58fca48
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0dd52719ac1fab5752c82f89268fc1de
    md5: f70cf518e6dca32a2ff72fb5bf44824d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart130/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c82359e73cbc39a2d9d325466dd3eb71
    md5: 4788bc4d40955941d39b00d605793eec
