format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/atmosphere/restart_dump.astart
  hashes:
    binhash: 40a181979d3f89021ba3bc88116ec6df
    md5: 0ab9cb3b981f54935e1d29b1a1922f7c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/atmosphere/um.res.yaml
  hashes:
    binhash: 53e2619d01d33e4382dadf5f8ba76be6
    md5: b408983af06733657b927a95bde4ab50
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/coupler/a2i.nc
  hashes:
    binhash: 6563cd2c9bd73db1f65b62b9b42e2cf9
    md5: 2670b49f12ffb351de6a7db585b22518
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/coupler/i2a.nc
  hashes:
    binhash: b8850640a1cdfa4a94a75eb4e0e7e2cc
    md5: f866885d3a32d25d0d429d04b11e8711
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/coupler/o2i.nc
  hashes:
    binhash: f57624535d5ab0011b091a79e22f2e30
    md5: e72249f7b44e4c7c07f8e4d07b612a6d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ice/cice_in.nml
  hashes:
    binhash: 49970dbcdde3bd0d2bc4b8679d51df91
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ice/ice.restart_file
  hashes:
    binhash: f5956d0fb276142d45406ac0b8079f28
    md5: ed417652dc92825c53447ad5a0952f8c
work/ice/RESTART/iced.2811-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ice/iced.2811-01-01-00000.nc
  hashes:
    binhash: 4d96e9eb95dd9b458a706aba72dbe434
    md5: d45f3de7da1c237c25a6eacd7b0aa5d1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ice/mice.nc
  hashes:
    binhash: 3665b00137b7deec2b8e0228baf934db
    md5: 8f9660aa2a9559a2aa3f2dc1131a7a36
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_age.res.nc
  hashes:
    binhash: 203495d351aa1db5fc9ca86ba51b07e8
    md5: 7001f4b1d9a3a744fb4264be36b1533e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4363ca5f47d9869f4d4226a009bb99ef
    md5: c1e68e32b798ca8be2cc62c81e55a105
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ee04de61752d634bea24f0d97f6e572e
    md5: 59408db0b880c63dbebf4848966554b5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_density.res.nc
  hashes:
    binhash: 3cb9f3a9cf8835000649bc726d52ad9e
    md5: 0a6c4612b683432d5875c7d7a82fe642
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2d9222dc63b1312ec02aae96f72f0c9e
    md5: c14f5a6c2169bfb5f185f3b71d2b7fa9
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1ae153145e0c15bc44eb45e2694c1d8b
    md5: b22f556489045f0ef1e10a26ff9491b1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6090262fb4e11655e4dbeeb3b95e3a95
    md5: 847efafffabff3dc12c6d4e2b56638e4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 51f34006a11eaa71de528ae4dd0c843b
    md5: 44e7033fbd8488d571eb7576d3d8f2e6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bdda27ad66df9f36f2c3ba77790ecffe
    md5: dfa178e23baeb9c51d51e8be7c1c1f1e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a65ab96aeaad3b7c9484c179dce39d2a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_solo.res
  hashes:
    binhash: 475ce40739163a7eddc5651d0d9d2ddb
    md5: 28cf99d3212b4bc807fd1bf37f660e6c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9ccd560d5f6ad05548baeb6cbf0e4fee
    md5: edcfc9c69f82c075a0afb07b9a4c96a1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 31217d7888b4ea985fa83a52b7625ce3
    md5: 584e607921577f9b382da1c40e94b99d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_tracer.res
  hashes:
    binhash: 60d566f03763e98cacf98044d975b535
    md5: e9829cb660474488d338bee824beb0a2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 45bba079fd0b1dc39fcc8256290f84da
    md5: 4d9d9aa545bee3032b637623b187f901
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a7d62ab1270c769398f926ef028739b3
    md5: c7342ab314ce1684728781cca484687e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 61c138a3f6df6e67dbb531334e6c3107
    md5: 587e9287652cadbe8449670c11c9ee61
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart134/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 77825b92105b902e3146c376b4d4a5ed
    md5: 871fd31dafacf5ffa07ab877915deb82
