format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/atmosphere/restart_dump.astart
  hashes:
    binhash: 9dc7c009f37bb77e88d1c4f35434845f
    md5: 8b360848581374705169e501ebac1474
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/atmosphere/um.res.yaml
  hashes:
    binhash: 9b0de0442d43115737df0bb7989cd26f
    md5: b087e3f16a7283c38fd2224fd6612873
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/coupler/a2i.nc
  hashes:
    binhash: 4086556a48067038b06aa35004028475
    md5: 2e7563c6e1b5f03e4a8dcc5639f2dff5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/coupler/i2a.nc
  hashes:
    binhash: dfd7ccce77ed301172d94d92b2113c86
    md5: 30334783eede73f505e816820dfa1c1d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/coupler/o2i.nc
  hashes:
    binhash: 40c2879e28d86747683e751e6102964e
    md5: bb9d08724d6e50a74e5bf386966c7d4e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ice/cice_in.nml
  hashes:
    binhash: d60d2e2dd6895e9c37a688241ef93864
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ice/ice.restart_file
  hashes:
    binhash: f095b45d654918c507b1128eb3b10446
    md5: e0b0ca469a4143ba7805e742a7ae0f9f
work/ice/RESTART/iced.2932-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ice/iced.2932-01-01-00000.nc
  hashes:
    binhash: 5d9e8bf8c2c80cb297cd2e41678c548b
    md5: ceb83302ec3b85a7e328aad8454ee822
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ice/mice.nc
  hashes:
    binhash: fada609985d78c5cd02808784ac5e84f
    md5: b580d2f9e0827d7fd060a16da51c705d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_age.res.nc
  hashes:
    binhash: 7cb835f29ce704437ce1406f4bb8e412
    md5: b57c5914b18c8fa4be84e145f934865b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: de8c77e8f1a414139d2dd28005749bbd
    md5: ccc0079b9f363ad621541ce1fd40755e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fe17f3cb84052cd0c23b7f14a1e9a460
    md5: 94981762ad93aab11a609f6d0989a8cd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_density.res.nc
  hashes:
    binhash: b400ece32dee5ffed2f3d329e4747449
    md5: 272432062cf10b1dba7e8b22ecdf2df8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4950be6de0f5bf842a82ca9f256ac5bb
    md5: 43f27c2a165e4b7186b96f082b0d0e3b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 602cd4d29094d96ed53db8760e26b90c
    md5: 1a1f1510e284a9ea460f3f3193b39dd0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d5d86c293f9c11a863f14cf6a6388c41
    md5: bfc3bbf0b10d6dc797ae7e72c3c21ff0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d91d8d0d3fc4621f8251a58ddda380dd
    md5: 73e39f40b96ac09da5241e3b1665ec81
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1c506bffa53d17332c6e4c30d326e761
    md5: 412eb3b6957f8acb7b8fde46adf2a488
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1fab84de789575b50800de52aaad4b8d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_solo.res
  hashes:
    binhash: af691bf52252e40431149745bfed3227
    md5: ba19a5c6ecc8ea44981132fcb47a8878
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4cf4139e2ae7019b9884123aa93c1d06
    md5: be52835a980f0370873ca3649ffa5f88
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e48cbea9dcecfae82a347897522eae7a
    md5: df8064109f53c7efa4fd51effe6313f7
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_tracer.res
  hashes:
    binhash: 1cf7b99ba90c7183dd239ec810911a19
    md5: 08e3dc64be5ef8b4508837d6d5fad26a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a82594773638679c4c44f291fbc623b5
    md5: a5d9490c0e35aa7bb9eeb66c7b44813d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 97b84e44a24a9aee1345cbf1f6fe79a1
    md5: ef0689cd145c1254e4605683b889d022
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4afda1b783086392620b0b4b1499b55d
    md5: 00ee3888a3ad6f750d18477297f373b7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart255/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2a7be27d9f468a78296bfd0699b9471f
    md5: e9a38988a7204757d5fe2c31904677a2
