format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/atmosphere/restart_dump.astart
  hashes:
    binhash: 1615bfabd15f43659b91de1a25dbc982
    md5: 6976fb91ae2c2a319ef2cd2c4c80d0cb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/atmosphere/um.res.yaml
  hashes:
    binhash: 1fcc2cdfa4937246a275dd694b96ef99
    md5: e0bd4275484bc02ad3d929c942f4a920
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/coupler/a2i.nc
  hashes:
    binhash: 9a32f5b8ef048eef55521f2c80d4532b
    md5: 83fbc804cda010484f6195734eb617ab
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/coupler/i2a.nc
  hashes:
    binhash: a8e0d6fe2a65954da28a8a9e6ac90528
    md5: e3515b23b56f36c744a7ec98428c0136
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/coupler/o2i.nc
  hashes:
    binhash: e79802e9d1cff30c3d153b1c3d9d3041
    md5: b254125ce109f06a35ba8a3585b8b500
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ice/cice_in.nml
  hashes:
    binhash: 208d9778dac010bbcbf0bafb5c2eab8f
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ice/ice.restart_file
  hashes:
    binhash: 6dc33703ac0afcef3f35914884f2acdd
    md5: 4225b1cfb63dde068da23f347849d792
work/ice/RESTART/iced.2909-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ice/iced.2909-01-01-00000.nc
  hashes:
    binhash: f1caea500bcff208eb5986e5a26c7488
    md5: a831e1d794479b608eed2d17e09ce562
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ice/mice.nc
  hashes:
    binhash: 6a57c2884593be46dca480c2bd22cd1f
    md5: 9a0372718f37c9f0947859d895aac915
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_age.res.nc
  hashes:
    binhash: 23e9be5b8dcec5b3fc3a21456750c4e1
    md5: 891794eddecb69241368071813b686c4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7f6a8bc4ec5c8c894bec414d436cfb69
    md5: 66ec8b00329cf95b8b28627e901a7a71
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 80a3e915857e87733f6a176cdadc62d3
    md5: 7a2167799ed427a5824a3eda7b7bb072
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_density.res.nc
  hashes:
    binhash: 8747ce653d8ac26435c47304cd42c2f6
    md5: 5bc025d0dc038b2c0212b5613b1fc21b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 645ce2d518d6db85d5906414fdf5b940
    md5: fd086181537960dfb3f37ec12c505d2f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e965766b93b3506cccec552c18fbd87d
    md5: a26335045eca6a8860c82f551ddccbdf
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 24ce19028c4e69d4f053b85311d8c08e
    md5: f3bd5da3ac3e31be01d937fd768b665e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9881e9217715ee2a839822dfc5b68ccd
    md5: cfdebd11cb54b7a1fbd5b80fa8046b72
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 97be7f782cd69f033f36b608c335246b
    md5: c7b071469e26aca01ec707bedffaced7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 74577934bda9e487677ac36935f1cd6b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_solo.res
  hashes:
    binhash: 98fcfcaad0208e30d54e9a353df60a4c
    md5: 607db951306f3e2341c6b97fd4edc259
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9949a8fce1da4fd62478507fc197ca64
    md5: ed46888176e0c6ff1aba88f1624dd73d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a934601fe06e50a6f07c9f7ed052d6d2
    md5: ee4cc6e995ff5bdd2fd1f6daf3240518
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_tracer.res
  hashes:
    binhash: a2d65adf1fa934aeda108236c0068581
    md5: c540dc49d9cc2dffab31e115dea1c8f2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 70b5aab97249720229d433f13d2845c0
    md5: 13f5a3547df01ef6082df551308b1984
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 88e35a5f270d151f3a35df23152377be
    md5: d87402ef3e4fa40c72687ccebcbf7bc4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 740e6828c7e22793164d83ccc33c9945
    md5: f980651e41044c63fb90f5ff57b27d0d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart232/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1dc1e3416f569da46031ebeb753aa400
    md5: 9a986af2ea29eaae34011aa7a762e95f
