format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/atmosphere/restart_dump.astart
  hashes:
    binhash: af798d52a16647d77e161fc87caaa230
    md5: 0f1dde7374b3d7c9e4ab79ca4b49d272
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/atmosphere/um.res.yaml
  hashes:
    binhash: c50525a2d48e82626f10133de2fee4d7
    md5: 978ec2220ebb6bf5f8ab5a5b3e7984ae
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/coupler/a2i.nc
  hashes:
    binhash: 5d3258152873ba4a72e101bbd33ea070
    md5: edf33055c031df643bbbf3a5a91fe817
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/coupler/i2a.nc
  hashes:
    binhash: 399a14be74bd966f30ae90f778c5f3c9
    md5: 7986abbbb1e2a65c79f7fee650522d85
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/coupler/o2i.nc
  hashes:
    binhash: bfa58c82ff280fca143f4a9712c4e425
    md5: e11e88d8ba61486dd14066075084c2a7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ice/cice_in.nml
  hashes:
    binhash: 541d2e66e98131eff093591ccd949d2c
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ice/ice.restart_file
  hashes:
    binhash: a247b744f752efc768fd51989d93321e
    md5: 15983c491adf31d75bd9643d931e784a
work/ice/RESTART/iced.2842-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ice/iced.2842-01-01-00000.nc
  hashes:
    binhash: 5d2110668d495e76654204209bae234b
    md5: caaa687835e05fb31ac74763322edd22
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ice/mice.nc
  hashes:
    binhash: a2d741d4d7a019d86cde15eec8c56194
    md5: b9c3d15a52e31224890f7965a5f8d3f8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_age.res.nc
  hashes:
    binhash: 38d7a3915f7660ec15ba9eab9bd9db77
    md5: ca5a54de6a1d50bfdeb7649a51790075
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f1c19ea82383773bd3437f9f2ff665f2
    md5: b1a488358afa60eabd322578889b45b9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 740c4187bd32cb7457c631c319558702
    md5: 7cdddc80e518026ff5f83dff7896165c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_density.res.nc
  hashes:
    binhash: 9d3b58b7d14cbf190c2f4ba054633764
    md5: f7e801585672fda04ec9502916b349ef
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d3459d0eb9538d201706d8c37759770d
    md5: 8a04faf2d10b88311d071025cb054d78
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 835b2b0cec150ead7be84ad44169e423
    md5: 5f8a63161ce73e1c417738d99de7ed04
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2859461192acee3ecd3af1cf27691bc9
    md5: 1a00b0507725501f8754a219fa6b149f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 88b330c504c24bc6a1de992db19907d1
    md5: 2a874a96954615318f4563ed8d76ef7d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 49f8556cba814c3d8d3331ef88afd448
    md5: a521418957a5cea1de41f87495eb2d40
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 79bcf77fd40b41b253d86be0456a8459
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_solo.res
  hashes:
    binhash: 8d32e056e3355da905d72eff3de9cca3
    md5: a421355f73ccfb2077dbe0d71e93fc6c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: db4518c0b2feec12069e00f26c04e629
    md5: 96f26322d5f059466807b04dd7f4e404
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a7d9c8caf9e4df64c9c90b2c2ddc4576
    md5: 05ae00a34e8acc176cce221fe31bc586
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_tracer.res
  hashes:
    binhash: 3dfcc36bafc6c637debb4361e4136716
    md5: 8d9e1b4c9bd0d659c38440d2fd86b1a9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e1d4403205beb95e4e5897f03dd15165
    md5: 43db969e4bac0fd8ac6be4b74046001c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4d32a1d4e42bff0ec924aebb1529c575
    md5: 45997f2def8301f6adcfab4bcfbb8a87
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 94a92e2551132c93d7502f82092ac4e9
    md5: c50b483f717d94fe7798f3b31032b1cb
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart165/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 213e5c76b251fb054cc70c715dfea9f3
    md5: 2a2e4dce30bb0ccde122d8d20b0e703a
