format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/atmosphere/restart_dump.astart
  hashes:
    binhash: 6fb08684fca87bf40e0864e29ce00cfa
    md5: 99eace8be2abbe070954ece0e9484ea5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/atmosphere/um.res.yaml
  hashes:
    binhash: 7c5e8ee2cb43fccc6c7a2a9b82a67130
    md5: 6462049856aa976354c06e6bc7b3d076
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/coupler/a2i.nc
  hashes:
    binhash: 3811a67625216da7a86b1b7dae8e66e9
    md5: 0190f9c6249b67bc62004d65473d013d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/coupler/i2a.nc
  hashes:
    binhash: 20ddbe632ee21dd09fe4e829abea93f7
    md5: 31988258e2669f85bf7734b7b47e60fe
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/coupler/o2i.nc
  hashes:
    binhash: 05d1b585a237e3c90cbd24219298fcdb
    md5: 6dc877e59d634bccd2b9af3f89bb6198
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ice/cice_in.nml
  hashes:
    binhash: df57d6385b8413748226be606d73a6ea
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ice/ice.restart_file
  hashes:
    binhash: 54f5402f1699dbd191b555b312195566
    md5: 52470a6d89581dcf6d71b6729d7bb293
work/ice/RESTART/iced.2750-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ice/iced.2750-01-01-00000.nc
  hashes:
    binhash: de633b1bbfc4bff52af64ef2582d73cf
    md5: 752acae90f52b5d69e1bbf93e9c74c18
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ice/mice.nc
  hashes:
    binhash: fcbdda75b4e7029e16870ffc5694bdb4
    md5: 2b19f7769fd911bb2e0847e7f6908ba1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_age.res.nc
  hashes:
    binhash: 5bfd7e69232dcafd71655b67bf9de3b0
    md5: 5c5fd14aca506e223d293acbe79259c4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5d4d99f2f448eab7c024dbd569cf82e4
    md5: 6f189d7abf6b77dd3813c115da42f3c8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c9f9764a1b81bf5b3f6c515de88bfa3a
    md5: b7db764a718e3b1b01eba4a5a5e35a45
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_density.res.nc
  hashes:
    binhash: 6fc43dade60384f608e785cc9c16e356
    md5: 75dba35bb1bd0f632c70fdf308f1f813
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9b30401311e31054a6f14edc398c5677
    md5: b5f8746b74aef05819f575c4ac8bce41
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e1f6a68e967a9a88bb5315e043578269
    md5: ce5bd4525e9a7914531ae9b6460ea194
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 69b8a9155ac85eff827ccd1f197a78f5
    md5: 7260a54fac3e8aa45293054997844dfe
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ce1ca77a2577f627cb0d8f89bb68e4e4
    md5: 96e72b1ceb31f070239377c791de242f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8351065dc538ee7210f4eeaab8719d93
    md5: 1d9592c625933c0f2936be35228bbae6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 40b9bd6cdaf2176229372ea3f8f3836a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_solo.res
  hashes:
    binhash: 13839ef73aba3380aac06ad7d969a267
    md5: 565eed3b65cfc7c400201a26d0fb549d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fbdf83070cefa9fa926e2f258a3ee69b
    md5: 0b3e77caf5c932abd06cf31d82ce6542
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 181a64d53a9e3424f734c24900451f96
    md5: bfec16940359a6577b1b9fa90052cfb8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_tracer.res
  hashes:
    binhash: 9850906171f064ec1704e5c51c673a23
    md5: 65473c96bb3f9481c9501f80b65a5666
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ba43c47ce8e707cd7e2b3e775d5b2b6b
    md5: fd65b5425ea246879ac9673c8dba4bc5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6fd5f91eabafef04773b19c0d6c6989c
    md5: ec47a636a6429425eda200c1459ba9d5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ed4f9c477841a981dab84a0d5e0fec1f
    md5: 93533e691ca47da2bf2152e606351379
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart073/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4bed670efd9efb0d60a78424f3f3f231
    md5: 097fcb10a57b327ba1653a8a8f14518a
