format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/atmosphere/restart_dump.astart
  hashes:
    binhash: daa731a1b5d68da80e4242861eb02c60
    md5: 73d519ea9c3ad486772c08f2c1760d85
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/atmosphere/um.res.yaml
  hashes:
    binhash: 944e29ceb2938fa8a8403210520278a6
    md5: cd80a9b7f6cd6fd957b1d64a25c32f8b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/coupler/a2i.nc
  hashes:
    binhash: 2173acb2d662ba8f490cfb301ff435b5
    md5: 55944b3abb24a41b206d426e948de97c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/coupler/i2a.nc
  hashes:
    binhash: 149e3fe89a49a6fae4a65667d5f5d5c1
    md5: 7d3e7ac48b26980e96f032c59387c640
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/coupler/o2i.nc
  hashes:
    binhash: 4554a070c32f31166cfb9ac52bf2a4d7
    md5: 0c27855c84cfe9fe3b2f485dcd4ab2a0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ice/cice_in.nml
  hashes:
    binhash: 1b983bf32570cd0781a7290199186707
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ice/ice.restart_file
  hashes:
    binhash: 74e1b4a85a735041fdffd62f605f2eb5
    md5: 48eb712db296fbd05ba44646af15210c
work/ice/RESTART/iced.2809-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ice/iced.2809-01-01-00000.nc
  hashes:
    binhash: be0fa131ed3ed3cf8467d754e88ccdd1
    md5: 0ede59d1646e8986d8239ffcccba999e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ice/mice.nc
  hashes:
    binhash: e6168f3a85561c3b0de8b2bdc10ced36
    md5: 3625fb305d3e701982c5c6aea4a64bed
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_age.res.nc
  hashes:
    binhash: 721477bb73d2740cf94ff76506c5726f
    md5: 09403a43d2040135b92591735cc5e7d8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6f2881518feb3e9f82b78cb6bbb9cdf2
    md5: 4decd0b36de456a858d2e9752ae41c2d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 020531779bb2bf366154c1448ccf5705
    md5: 2699f52e4d636a53b7f1ecfbc42d00fe
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_density.res.nc
  hashes:
    binhash: d2de07ca9acd07f88b506905408edf56
    md5: d9d2496ee11f62ce70bf34b4d4ecb3dc
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 138ba073eb1f305e278aa2ff9414b20d
    md5: ee51305f8a0f5f611bccd94e9be531f5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b4f02d030d70c63cf787e1f26cf69094
    md5: ec000f4d0cd5b6bff6ddc259996a81f8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 84b951a35d07f586998d4412fc2b16c8
    md5: 2583e42eb3857ad539dc4394565678b7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 92e33fbcc1f792b65c1b83681ca605d2
    md5: 409d5e461e665b08fac060d60f3aa39a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 73683c53b6272d6d163009c75fec1e0b
    md5: cd646a36de72a87e90027b35f981f7ab
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: eae45013d02254f8cf59550677968fb3
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_solo.res
  hashes:
    binhash: 03d6186e1d16eecbd68b428e7617105f
    md5: abbd44c63050f15e65249bde39a3fa88
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 49879e950849e502da020fd495bccc9d
    md5: 6e4fe51374896485cc42689148309401
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0e3ebbf11fcb8ead9e04f36552ae4bea
    md5: 82b3301f9f8e9145bfcd69612e549e48
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_tracer.res
  hashes:
    binhash: 50b13cba64d417049be26bf12573b296
    md5: 39166a3db09a3f6510a34ebd6024ed43
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ca0351ff65406a04324f6835e9a9e7a1
    md5: 20b4dfd6c4b085542f9835533c28bab9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 70db074633df834ae1034b921ba8a1b8
    md5: d6b681d533a9e7b428dc2f98e08a9760
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 929060badc12027957fad1b9803e814c
    md5: d765cc269afe3c911ec1752b01ffd59c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart132/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0ec8bf1c26940075d1c3ceb00eb0e468
    md5: bb602663e656488ef2835cfc1016c5e4
