format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/atmosphere/restart_dump.astart
  hashes:
    binhash: 4cc039f570c59d74f0c0f38f91c0011e
    md5: 77e1cafda551478f8580cdaa799e6a91
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/atmosphere/um.res.yaml
  hashes:
    binhash: eae0ba0a5b61d97c4d8d8f88aab44b85
    md5: 24da2059ef060307d0af49982aabc7e6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/coupler/a2i.nc
  hashes:
    binhash: 57f17c1efaf1d618da32a1f749b876ab
    md5: e1ddcdcddd5f91a3fa60cff4a9924fe5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/coupler/i2a.nc
  hashes:
    binhash: b0954260271de4343a3b271010184ac8
    md5: ac54be28e6256a4ff0ef530c89a90b06
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/coupler/o2i.nc
  hashes:
    binhash: 5d093c0f7242ea177cd22e1c1b7d147d
    md5: ece8d099165ed695929c4d7ab95ac6e3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ice/cice_in.nml
  hashes:
    binhash: afe39907b446b20abdb2ac83a2cebad5
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ice/ice.restart_file
  hashes:
    binhash: bd04a227f2e118594126e775b297779b
    md5: f9c3c7975a8db370f2903cbe95792b45
work/ice/RESTART/iced.2960-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ice/iced.2960-01-01-00000.nc
  hashes:
    binhash: 2d4fc67ace34fd4f46813b0940e247ca
    md5: d28d242c88cb5efca352d4a547ebcef8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ice/mice.nc
  hashes:
    binhash: e892b707dfe742ad5bdb9258f0475b02
    md5: b1c86d89bda7d9d8a3a4b9f0d5bca97c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_age.res.nc
  hashes:
    binhash: 0f7aaa38921934d4828d5a03a7e3548c
    md5: 63bb47f6f6338533ce7d6c871a3b21e9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: daa25bd56ee7b6651ec1d19bb8ac4d4a
    md5: 98a483218c73c1cb3a20816b5afaf491
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 10f6a4c4d415b88c6d8916ce698507b1
    md5: 57b4295380b1ff54d0c5cc0009f28083
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_density.res.nc
  hashes:
    binhash: 82df967ff7d8fed2f0592f0f808c07eb
    md5: 4f19efeb42e900192ddc97dc5d41d28d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1365d12963b236cfa7b7d0df3bca357b
    md5: 40710ac204d94f7d6cbc8e9a8e068ce3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 22c8e2f5091e1803a81455e809c1569e
    md5: b13c034f03d2cf234ccb44172a302e3e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e93d8308e664810cb4865851384d8390
    md5: a62339945bfb3d3c75eef4661a19dae6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0f1ef3d51bd7dc93ad36ff504d654207
    md5: 7332b0f0e8fa97feb745d5275a1692a8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 76b8822455d0109f0b5c132ba466b01c
    md5: cb560474607e70899f5a5b66f29b1c91
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e7b14534707bd2c466640ca36dc9b712
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_solo.res
  hashes:
    binhash: 7ec889b5d1348497e0d181a960f65ddf
    md5: 50d8d2108e4a3ef84618e43c8c45ffff
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 178966f91ba9f3a452c071318996ae61
    md5: a0d023a03bc4f929639d84f85c534435
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_thickness.res.nc
  hashes:
    binhash: aed623fa04d3cc7df0061f1bd1b75ce3
    md5: 03d09a6226700ee3bb201a39bd45ce35
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_tracer.res
  hashes:
    binhash: a7ed0bb1c7175c6cd7637e6f4301a854
    md5: 076eb46f8dc653b391d1c2c48c3e1a61
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 448583c40084823a1349b958c0d0943d
    md5: 55847bf8d49ce2a24f6530de1816ec33
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b529859bc8fe170607b340017e40d3ec
    md5: 21802d2b990446ab5d25e6cd018f52c1
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f171bf041c185df13a9e04519eb34c08
    md5: 4831c8d03abdb622e0ca7f56b4d49803
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart283/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ceab797555b74cd4eabc577b6b5cb125
    md5: 5df1e50efdd5f0194e65294a8f1259c8
