format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/atmosphere/restart_dump.astart
  hashes:
    binhash: 7de654c06fd9907eb55be6b8b31f596b
    md5: 80a602fb46c51bbfdef5488ee294f9a8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/atmosphere/um.res.yaml
  hashes:
    binhash: 43bc94af6658fa31bf9f0a265d4cb1a0
    md5: 0e2fef70631d3e93e2c785e886d29e1b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/coupler/a2i.nc
  hashes:
    binhash: df6d4a78cf4cd7e87d2b162266e98c41
    md5: 28ea62c14e6a064754284876f64ac90e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/coupler/i2a.nc
  hashes:
    binhash: 7cbfe7c99c9e642572e3d8888f246882
    md5: 2e4d930c04103cba88b77cbbf1197e29
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/coupler/o2i.nc
  hashes:
    binhash: 3eaacf6d0ae180bacba4429c3f99ffd7
    md5: ff5108921626a79df54693430a0710d4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ice/cice_in.nml
  hashes:
    binhash: 5ef19588ec5aefbdbeaade1bb74d91e5
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ice/ice.restart_file
  hashes:
    binhash: 9f43c0df653f5e941dd675056f5e40f7
    md5: 117a320f53aa8df0b46b625cf0ba771a
work/ice/RESTART/iced.2730-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ice/iced.2730-01-01-00000.nc
  hashes:
    binhash: 7c21ab8cd058131b8f82bcab88245615
    md5: fcb49c6b675bf48e0606b4cc0a619059
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ice/mice.nc
  hashes:
    binhash: 67a72eca574b4da823c4a7202bf7847d
    md5: 8176c3162f489ae22dd4e8da3481af49
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_age.res.nc
  hashes:
    binhash: 7389d97b54f4953c9b336592375c3453
    md5: 4040d2ed9241ccd8c5d4bfd2b9b94381
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 469852526f136ec8d8ea4fea8c26c3d3
    md5: d008e48966f0201fd31404db41681b56
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 94aa5d607d74fe7126728e8c178f9cc7
    md5: d60a0decb1852bd3061bd466ef5b0bbc
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_density.res.nc
  hashes:
    binhash: 564980814d6e64c48037d4fa5df23d16
    md5: 8705ca7cd77edb8f4e3e223ef823d0ab
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ecda78289c8b1e9343953457f9f661cd
    md5: dd3c67d2c5926b0454936a99d38cfdac
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 539a9ca3f789b728cde8812df9db51b3
    md5: d6f7e20203193243fc6a1afd2f249bcc
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5fa84b2cd1becc057a21ad161d46428e
    md5: c5e0086c54962b1a212468b0af2a16c4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8d3824486be6430baec1d238e039eb2a
    md5: 8259705aa68a2b66023966013e9eb462
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 024d425e00c5519d3e4ffbc0812bbf77
    md5: ce1c1fb67f93737800ec963368d4fe55
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c18f44085fd457b0d2964012137deb9e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_solo.res
  hashes:
    binhash: b8a3a0de7fe47f448f55a7516d410e97
    md5: 62285e01363242236657e5edc97a2074
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 296128b5a93778b063721766ecdc3c54
    md5: 324cf17945768acc0a586dd7f5491d27
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 53e9ace3391f365c396b2535bbdb5a26
    md5: 1d7874305940ec1cbaee9d40d3925f17
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_tracer.res
  hashes:
    binhash: 6fa43f2cd0f38b688b8ee4b7988ae70d
    md5: 7eb4f40bb7b601c35ef575679b64bf83
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c904c02b7436d7c3053d35831a831a08
    md5: 6583e701de579c9610411b52b9062c28
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6d04f02af4170e6c1c80f955deaf04a9
    md5: 1287200df20473cdfef0f3e0e146af05
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ff0f5d7185cba3c93d58bbba105b8acc
    md5: 40ecf4ffab2c613f1f8f099086707d14
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart053/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fce35e7c72c9e1d00ebfcd29602f9588
    md5: 0a8864e02bea4deb14feec19e19194ac
