format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/atmosphere/restart_dump.astart
  hashes:
    binhash: 8427d44309d6858b5c8bbae7a8fa2928
    md5: f65a5a631c516907330e7f2d4479d5e2
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/atmosphere/um.res.yaml
  hashes:
    binhash: a8fffd5a3d65abf3cbc529a0abd06a60
    md5: 3799476c44ad810f06ee248dd8d58889
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/coupler/a2i.nc
  hashes:
    binhash: 6d44d81930a9db77c37d081eac8e63a1
    md5: b3839596b889724e0f74249bfcbb2bbb
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/coupler/i2a.nc
  hashes:
    binhash: a865e2b2d20bf0e909e63b72dfb9c9cc
    md5: 3ef44fab3b084a45e9b3e5d6c3ea864d
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/coupler/o2i.nc
  hashes:
    binhash: a3d02c38ec9652dbc697c8a27ce01369
    md5: 9cc309c53725980fb8ceea8c3beb578f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ice/cice_in.nml
  hashes:
    binhash: 749d92297fffd3824ee0fd217b455389
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ice/ice.restart_file
  hashes:
    binhash: 47f0cd4f003bd4ebaba8e60de31667a7
    md5: 422d27f3e0e57a911d0460ca51a34307
work/ice/RESTART/iced.2145-01-01-00000.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ice/iced.2145-01-01-00000.nc
  hashes:
    binhash: b140c0f370cbd11cba55581268e644c1
    md5: 9b38a443da662dfef1ce950042dd98ed
work/ice/RESTART/iced.2145-01-01-00000.nc.back:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ice/iced.2145-01-01-00000.nc.back
  hashes:
    binhash: 12424ed20a20bff5ef67fbfc2e03fa76
    md5: b9b59b71f031ac1538ab5a763c5c7589
work/ice/RESTART/iced.2145-01-01-00000.nc.back2:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ice/iced.2145-01-01-00000.nc.back2
  hashes:
    binhash: 577817aed7ab28464634feabbb690c63
    md5: 30aa4c9195a2354304eff8409933902a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ice/mice.nc
  hashes:
    binhash: 94c42b000bdd207d00f042286421e7f0
    md5: b0f77b9c94aadc78ad29846129c068cf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_age.res.nc
  hashes:
    binhash: 69b059ad6994343447c07a7b940f0d4e
    md5: 8ea6938953bde98add4f0396b3aa4d7f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4de33213ab330deab51635342bd6004c
    md5: 1bbc9c7b26a763824600d343721284ca
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ffa8d63e013d3c5b71883389fe2cd63d
    md5: d3319b42b15770e6e496bf876c56c3a9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_density.res.nc
  hashes:
    binhash: d395d0dfe06314fdbb95733f4e4840fd
    md5: b9721a24f0ea54e6148149b6fd8c49ca
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0c825831b35e7cdf339af9653a1cfb71
    md5: 9c74f9b91e446eae36647e1532b5c1e1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: dba9d431752484a64dd1a42d8ca89af4
    md5: dedf6f50c59997f3d1a4dfa91e09141e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d82bde77851856b7389291e54d0cad20
    md5: 5b83d74deb91b28687ab17591ab8ec7a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: dcc80929626962d447310607f598cece
    md5: 778294e24b94dd3de9c3c4c7ddc4ae1c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 160bcc91f2e60a4a21f1356410ee1d58
    md5: 3cee186611b12bd55fd6df5d8705bbaf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6ef72ab4b63aeed291e951278dfb07ce
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_solo.res
  hashes:
    binhash: e37741c5faef2964ae53674a3c62883e
    md5: fc8621b51090a6b219066eae79806042
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c77b12baf8c0a53355b2e5361c0df629
    md5: f94e61d860b97c1110da9ab9465b86dc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 40fc25f99828641543aeb519abf8591d
    md5: 27cc724aaaa0746715b60f8287bb7be3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_tracer.res
  hashes:
    binhash: 574217acc25b1ab0f741e1e54bb141d7
    md5: 89366655c8e44c73707bb79d7f6bcf6b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e610d64e030890989a60d2be0dc7d874
    md5: 84daa2d28d4f4d0bb23323e873e20d48
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2385d2fca04181f4225453e2826916d1
    md5: 701abc0960bb26c8d7df8d9ca6bb73d8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 67f70be1712eddcf562271bbb9098e7c
    md5: 292c7d2fe3f7dbd632d4b88c13094c1c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2025.11.20/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f301ab3dbbc0c806f8345b676415146a
    md5: 2ef19c2a89987d615a629b6ade6179e2
