format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/atmosphere/restart_dump.astart
  hashes:
    binhash: f6518483a2c95b51a39de1e76db66521
    md5: 8eae712e8d09ef0dfbe2a0004d19e5e2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/atmosphere/um.res.yaml
  hashes:
    binhash: ad251ad65ffd70f56cd063f77c3f6e57
    md5: 3280893fc4be5b98cea12a9baff51be2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/coupler/a2i.nc
  hashes:
    binhash: 4508f4755ac81d12a530e8a4dca81ec3
    md5: eabf515cecb0e05c5d4eee0d06bda544
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/coupler/i2a.nc
  hashes:
    binhash: 9b51edb0d4622b62dfec10cb4154fef0
    md5: 0fe208eecbc855f2a5b6c6121125da71
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/coupler/o2i.nc
  hashes:
    binhash: 29d157067da9e9bdad31303aad0be84d
    md5: 1448f6ed62fa3287064fe563025c9d05
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ice/cice_in.nml
  hashes:
    binhash: f89f6d79c704e596ad288ee1dc34eb77
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ice/ice.restart_file
  hashes:
    binhash: 74c525af4aec04b3583ff934cdcd3229
    md5: 913f430f243b83c773d29ee8dccc82b9
work/ice/RESTART/iced.2922-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ice/iced.2922-01-01-00000.nc
  hashes:
    binhash: 6c4d483c19a2f6d50ad379ac01356950
    md5: 0a6b1f453d792653b7a4da1ce6cd5bc4
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ice/mice.nc
  hashes:
    binhash: e7603531b02023807892a9741f85a099
    md5: 8ef82c291ed798d8b39899076b65c637
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_age.res.nc
  hashes:
    binhash: 6ba5c6d73f73b16a7d9055edf883b0dc
    md5: 688b9ccd1317f710202b7c91f5ce91b3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b387755862990339ff70a904805895dc
    md5: f7c26366e2bd234487c0b83948d2d5cc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 80d66741a4df81e3e0b106cc4488a030
    md5: 7bfde68df82fedf554d071996df669ea
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_density.res.nc
  hashes:
    binhash: 3a8bcb8efc42d7cf2ac8011f57af17a2
    md5: f4efa820f639eb3758aebfc122f6e0d4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ab2f115bc1c9462c777d4418c535f28a
    md5: e75f5fed7bb7b88c10b043a7b1f1d74a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 07e225ba6305265a37060a55ff19cb62
    md5: f131b6381756515a6fce87e3b0d629b8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0c34f9919d50a9f8aab02882ddbdf9c1
    md5: 6afd99b79261a5d58c52577417a52003
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1f1d6de81cd0cc6d8efe57ba6ab532b9
    md5: 663bd3c7f3fb20456d1b0202b1e809e4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f9d8bf213ad60e7fa73ce1abce58a50e
    md5: 76ffcb4787e590a954408a38aee282a0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 71d7c3cd1739808e9521ab892e39d9f8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_solo.res
  hashes:
    binhash: 645238ea86c721a0f25b8868d56f6ba5
    md5: e3a905331cd5096590a47ac8a058bc0c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9dcd69ae8b8b6db78e0cc05ccb6d4c0f
    md5: 4d36987e801a14665161c221229bd8f8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ce360f9b800d228304943a5aab26cfe2
    md5: 44cdc231eb88b306d739d4beda781db2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_tracer.res
  hashes:
    binhash: d716586e04b3448b360b5b43fb4e4288
    md5: a933a8afd67fd602661a2d097f42b786
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 55fa7ded1c4f3399931c55c26f7d2ab9
    md5: 1ac6061b159f13a3dc01b55dfa418545
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d9ca84f2981c6074b823fc0cd3cccec9
    md5: 1ae3f8f7421d19af78b8f2e5ee078deb
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c1ed544b4ebf7e91f51d209cd109a29f
    md5: 6f978e625dc312842a2a580764330d8f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart245/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 031c1346f68a15dc8de82858eeea6094
    md5: 1803ab10f1d530c547f1489c8110ce3a
