format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/atmosphere/restart_dump.astart
  hashes:
    binhash: f7816193d797337d6d078d1dbbe060e3
    md5: 2ff23264b77e5e7a9237590b92f766c9
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/atmosphere/um.res.yaml
  hashes:
    binhash: f48a5c5aebe6f1d81b984328165d845e
    md5: bf50b351a9774d7f7c60b6d1aba38033
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/coupler/a2i.nc
  hashes:
    binhash: c7c78c2029e8e6a130fb2688bc7a2e34
    md5: 9f538b0be458c5c682640d946cd8d563
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/coupler/i2a.nc
  hashes:
    binhash: 2a10759e8216333411efc6b43064842c
    md5: a67fac2ea8c9fc3415abc63b6337d396
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/coupler/o2i.nc
  hashes:
    binhash: 475642d8f8b2442e439bf2e46a17209b
    md5: ec1f792139b7f1d260f0eaa3a1bb7a2e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ice/cice_in.nml
  hashes:
    binhash: 1269b35927c2f64a61deb9882d02734e
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ice/ice.restart_file
  hashes:
    binhash: 330a403b7ee3ca4c79308517afd26602
    md5: fa90b2634ac8cf478b1d7945d4cb27ed
work/ice/RESTART/iced.2875-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ice/iced.2875-01-01-00000.nc
  hashes:
    binhash: a4d8e89277f30d4682552695a1d70596
    md5: c99749e8b05f6d62295df156ef779eff
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ice/mice.nc
  hashes:
    binhash: 4a8605b4d5b18cdd10c246de42dbcf5f
    md5: 377940f71140bdff0878e052752451e5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_age.res.nc
  hashes:
    binhash: 61ff538232a594b251db2ef022d48912
    md5: 46aaaa916612c7fe8ab4176019e8638b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d3827be960424233b01b0ff0dca231f3
    md5: 500d67b189ce3935f45f0888b449cc3d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 393573efa01bbc096c17cb24eab53b13
    md5: 0ada6fb25f544e44a2ab7f17f1286307
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_density.res.nc
  hashes:
    binhash: f757794b5101f868e2f331d93d5949c6
    md5: c6ce3410fadc938f690e08b1bd3b605e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a4981b2eb52217646162d77e933bb26f
    md5: f03aa4a506879abd47a002f25f134f40
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: aed8641ff0e530ed5ff6f640e470ce90
    md5: 305f8c04cfc1fadb689be237de277f2f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5e65a5647aab58d8679241ecc2eb4b94
    md5: de3eec5ce6d91f78909977d0888db82a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4e69e1968bf1b4030af0cf1305ebafc5
    md5: 2b7ad8ee129bfd425b8020b8f67d0ab4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0eccdbbe86e21e4dbc11e8d5f7365806
    md5: d6be6d8b9c555191baf7a739db5bd1e9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 04aeffefb2aa52f14ddfd49d4e1d9fcb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_solo.res
  hashes:
    binhash: a7b693c5ed0d1c914c16eb6fc341134f
    md5: 987dd9e276d0d42fb742fea65829c43d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 34fb144faa7ab25addae09e58c54357a
    md5: 5f9ce746dff45e0b6f1dd3bd28e771bc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 13ffc371f6e6a66f6b54e0333d859b11
    md5: 9b4bf9c3059cb4986c441af5247cb244
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_tracer.res
  hashes:
    binhash: 5dff3f006e23e03070374d6b429388d9
    md5: 976705f5beaaddaeb50c8cf297f465b2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 543688eb8e3a3e9bbcdaec95ff66402c
    md5: ef512dc8ed5a6aa566a35e39d84f3058
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 826a87153f141b8d7ffa6dcfda3358b8
    md5: e4a00201c3596e5fc2f23cd1e8390f82
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2b1d11210610483472f430451add6dd3
    md5: 751eb85266160043299da9d8e66aaf63
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart198/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 85e57674d1b3b9edf3621688334b391d
    md5: f81f5cbaf35ca41949ad4fc806fb98aa
