format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/atmosphere/restart_dump.astart
  hashes:
    binhash: 13f261a4babf79d6dcade89adb48d677
    md5: 28c7608eb1ec9384d4fda6bf8f252d4e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/atmosphere/um.res.yaml
  hashes:
    binhash: f9579033d9e9ef7c4f72678b625b9c0b
    md5: 20d3f98209a60e2895b5f0c7a7f83a49
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/coupler/a2i.nc
  hashes:
    binhash: 3f9e3d2640a7cc5af2f45ad1d88b36ff
    md5: a777ab8d1dbdb068d13936a5e96f56c6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/coupler/i2a.nc
  hashes:
    binhash: 48fa59b060742690fd18a01187baf82b
    md5: 5b6dd4d1fa5392a63a23bbeb82c73060
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/coupler/o2i.nc
  hashes:
    binhash: 23e506e321f2cde4b0f928c63854d10c
    md5: 9af48f8934bec7a683c9f5d0df14275c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ice/cice_in.nml
  hashes:
    binhash: fe86927dbd47d01a2e701d4a644b3d65
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ice/ice.restart_file
  hashes:
    binhash: c1190a3d5d2e51ceb88d96c4076e7e40
    md5: 67b3acecbe30d0a0465b822e08d00da3
work/ice/RESTART/iced.2793-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ice/iced.2793-01-01-00000.nc
  hashes:
    binhash: 442e9fc4e172fd0df03c93256eb6070c
    md5: c3eed97948bb0e726217e3bea7077ed4
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ice/mice.nc
  hashes:
    binhash: 1968161abba6384e6f201a898e041e75
    md5: efbeac60f624d21e1184b633a53a1ad2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_age.res.nc
  hashes:
    binhash: ab8d3a3215405c5f46b6bba5f4cd8fcb
    md5: 8ade76c6353bfb4bcaefa959ff3fc6f3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5d8a0a445770a773978a2877ed4ee7cd
    md5: 5d7142cb62d82e05cc00e28ddbbd44f6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6673ff91a5aef89bc7c64eb54b780a2f
    md5: 388086789e03b741692f2d316e4494d3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_density.res.nc
  hashes:
    binhash: ab419b1ec24248a725643dfe302a3046
    md5: 1dab28d0e091f04dda286effcbca6971
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d0e9c3105643bd70139a6a83cd9a6a2c
    md5: f37161d0454d820fa381987b12aee3e1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: cf5cea072a9fff488247a20b557befc2
    md5: 1390b9127fa70ee34b047711eabc84d1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 767ae0a6ac052bb387dca552595e40bb
    md5: 976ad7d15b93fd2a36ad399b7ffa083a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 49fd5a3cfc98273d66d422a3861a2d62
    md5: 7166a8d48c8d3a601597fc68121c8d97
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7c14d124b20b7828a770a9d978a90276
    md5: 2d523715897e6171ec45f23e6bec8653
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: bcd753fcfd555ae3db2587ad6dcdd8f8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_solo.res
  hashes:
    binhash: 1b791789f20e11195c17154643eb24ce
    md5: fc2f8a893f0573a8fd7ea070787baf62
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 51b00b652172160756bf198848f23227
    md5: 8114b65f64733a989f694519fda3c0ba
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7bc4813450b06ee9fe44fcf85eef4747
    md5: 30a61c78573ad8267a04322dcf75ad2b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_tracer.res
  hashes:
    binhash: 9a890edb02279d3d51f9dccf5bb5da0c
    md5: b99c31891e00f2a2ece0194bcb05809a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5a031096aebdc0ad0690812d606d2440
    md5: 3f907475a4388cf7c75f3ac67defd67a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 089d5cc878e48b661bd52ccb0b06665f
    md5: 568ef0cc4abf91e79a38aa29c4c580b4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 262200e941b31704c6c61fd124418ff1
    md5: 994eeff7e499016f536fe6b36a84aed1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart116/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a1a1e1eada4035f388e951f67d5f1378
    md5: dd7ca0352a4cadfd24de2da2b6dd7104
