format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/atmosphere/restart_dump.astart
  hashes:
    binhash: c9167de5b6b7235131ac5c0d186a23ef
    md5: df85310517ed2957840aee1c72c58867
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/atmosphere/um.res.yaml
  hashes:
    binhash: eb9d59987dfe7d77c4e2e43a41620319
    md5: e243960f233ff7ae45cc3abb60ade11d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/coupler/a2i.nc
  hashes:
    binhash: a1cbaf1c6d40532f822da490be4a3d09
    md5: 102c94c5fc2e058a9804d3109d9aab0e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/coupler/i2a.nc
  hashes:
    binhash: b3ed6bac0c525a57b6b54002b6090424
    md5: 6f2259dc5d7d4a2a5afbc8cebdc982bc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/coupler/o2i.nc
  hashes:
    binhash: 663505adc1c059a24b7d44e662fcbe67
    md5: 9d6b3284048747179a2e704221b4b5d5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ice/cice_in.nml
  hashes:
    binhash: 8a02793a19bf60a4de4d84ff94be7f5d
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ice/ice.restart_file
  hashes:
    binhash: 98f4ab8723e1283ced82d5215cdfdae7
    md5: a066696e042f8999f26a904983b81d1a
work/ice/RESTART/iced.2837-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ice/iced.2837-01-01-00000.nc
  hashes:
    binhash: dded7c28ed5fc3bd72115f7311fab093
    md5: 2c79839ec49138b246174f4861c4a4ff
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ice/mice.nc
  hashes:
    binhash: 6203f7f6e62a2af3356f6590ff450f0b
    md5: 751dadd01142356e06c9e80a4d2cfbc9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_age.res.nc
  hashes:
    binhash: 3fd320b836204c9b000f313256418208
    md5: eba5e6dd2864927169d0b1b228d47a2d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8983d18dee5ee82e1d8ca5d3b80bdd8e
    md5: e9999888f0033806cf53a71a0468a60a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a1a4213c53d39bbe6746aef5f226234d
    md5: 8d4a70570c6500786b2ca9b23fc00a5e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_density.res.nc
  hashes:
    binhash: 72957696305ab1af19568cc47e02bae4
    md5: 14337fd152b8396a61ec5ed3926fcbc8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d3e4d3d4dc4f35c7a1d2a833b3e58d4a
    md5: 1da9dd273480a32e92cf2eaad0ec7dd5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 10d142a7d2955b74c18f57d1ce9842fd
    md5: 1e97e984d24a34eaa81a4a9f556773b9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2016e9f31516985440698bff6e9609c3
    md5: 8aa809fa35ccebc9c1880a00b3e333ca
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 34a836f84b5c2dc641406add9bc77d83
    md5: d4f9928c9e04a68f7173f5ee7261a7c3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4ac361872bc0fbe4285cfa09b41b321e
    md5: 0a2a7601a961cff939008064daf746a2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6584b77e750480df57b5ca840a4866cb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_solo.res
  hashes:
    binhash: 148abda956a96b79e1c91e63e2213853
    md5: ce7175137aa8d7084cac760e9fe0f128
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a75d97e2c86706571ce6bfa3b58577ec
    md5: f025a78d7640c6780cc83a9c3dff067a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3af8a18e7f4e69cdec6cb5ecb1eb8371
    md5: 0f4e5b952be5a37d2c78332019b69c0f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_tracer.res
  hashes:
    binhash: c1501b08b3e1e61420b94d64d9e50ec1
    md5: b3e77092fdd48bf761211958e2476257
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0f6b796e6ff542fdbef6ee4f7c848ce6
    md5: 90707d64c1186bdd79f1aca52bc9775b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5bf1081a379b24c0bdd524c5b46b9fad
    md5: 8c941c2bbf83cde57a85c484898d35e6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 247d9674d65b77b9e81d4ce0c4d5ceb1
    md5: e15c8ac475cbe283df32225ac91f5d72
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart160/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ba203aaec3267e121a224b484525289e
    md5: a00c0e2be44d425e23a7c22cd673fd36
