format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/atmosphere/restart_dump.astart
  hashes:
    binhash: 51d2bc9cf704a5507b8e7191327c0b99
    md5: c05dc7616d6098c9274c455e57f31cdb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/atmosphere/um.res.yaml
  hashes:
    binhash: 866c366cbb4c719bf35786728aec1693
    md5: 628c6e4e244b5aaa180399c0d7c41574
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/coupler/a2i.nc
  hashes:
    binhash: 20bd03e8a9230e77e0986987bddafb3c
    md5: 104b597bc5ee8c2b3dc699745dda8291
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/coupler/i2a.nc
  hashes:
    binhash: 1d610766ff42d07b9a33811da1fa618c
    md5: 510dff22c05b5f572daab623770887c8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/coupler/o2i.nc
  hashes:
    binhash: 52c76a97dac3104f69dd9d990abe6ec6
    md5: 59c40f663d1a38ff25b057cdeddfc749
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ice/cice_in.nml
  hashes:
    binhash: a7eb971c2bc4f4ec8147c7c73cb9ced4
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ice/ice.restart_file
  hashes:
    binhash: d6095adda463776bc0fee71c3be51770
    md5: 1bc2f1283baf758e5b158aa68179671e
work/ice/RESTART/iced.2891-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ice/iced.2891-01-01-00000.nc
  hashes:
    binhash: ec379c8a01049f120aa1bbaf58fc4e60
    md5: 77affc937974ef5c85f0fad4509480c0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ice/mice.nc
  hashes:
    binhash: 831e629f19ddeb9c022317f0a092034e
    md5: f32a04375f4f6243fc1cfcd320f6909b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_age.res.nc
  hashes:
    binhash: 10223653acf69282418888f81ab02ff9
    md5: dce808bac31b76ac244b9cd30f484382
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cc63b2ae7b6834fe512c53f7a8a196ce
    md5: 6f8c7b70a7a6415a3e94952ca3b7524e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 20ab91b3b7c9d9b1b2a5512bffc4f230
    md5: 77be70b8b1a99f2bd33625e858a7d525
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_density.res.nc
  hashes:
    binhash: a220b4550d425b48f7b87127b8b78f5e
    md5: 99c46acce5d04f200111a86a48652046
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c381cb11b844542d2b64e1f1522f7e6c
    md5: 844648a6f72d3990788e4ae691cbaf2d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1f3531b3de5cae3e34911f8cdf0b28fa
    md5: 62dbc483378b36df50d56ca5c6488526
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 912de5e640ef0c78a887d99516c8fbb3
    md5: 82c40c00048edcb206e475981e3de323
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ec010a8d2d0e113149a8e55d4d47c9e5
    md5: 93c317b812ebba18bf584f94eed87446
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c9b02bdfe7fec4869c22d9e169a73fb2
    md5: 665beac514ab90c16fd425a6553466ca
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 45c9440b2651600278c58b2dc9a8be51
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_solo.res
  hashes:
    binhash: 1ee52c93d4b727526e5607b10b055f14
    md5: f19626f578b42c0267d30fe2742102b4
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e7c3e24eeae189f1f51dd211ca922981
    md5: e555a4428197a8de24150d96d5d3ea82
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_thickness.res.nc
  hashes:
    binhash: de54c367f96b8a9f711ab7319456a6e4
    md5: 17aef60f4cc55b3dec20bb2bacd36556
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_tracer.res
  hashes:
    binhash: d51beed50a71b3a022f00392771b9307
    md5: ffce05d227d0a07e072625e6b2218840
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d103d9d08709ec5231f5972f1d898b16
    md5: 7d3863f15d25d2c2105b106ba61e23e9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7bd5762bc2b25265f751814b28892bd3
    md5: 5787898ccf79bf5c609cfae02e6b83dc
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7cef5cd602c88510ae862a5f019b20da
    md5: 50efee7a7461d3e1caf0340235d3c972
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart214/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b0379d2d8b37555b40e8b24a216a6d34
    md5: 3ce24c282a4da6c58dbf564e4629ae1a
