format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/atmosphere/restart_dump.astart
  hashes:
    binhash: 0bee0e50610d4840dca5a6553a5bbaf6
    md5: 047831995a3066456f16040492b25fb3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/atmosphere/um.res.yaml
  hashes:
    binhash: 9231a804ec94154ff9d69d7fe4664e2f
    md5: 971c66ab40ac1bb076f70f67842e0427
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/coupler/a2i.nc
  hashes:
    binhash: 0d7219cfecdfe1280e4c9fe70e315f11
    md5: 82009cc89056fc5bc6c2c00079f2d869
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/coupler/i2a.nc
  hashes:
    binhash: de81b007ca0727149b8ba8577cbb2f93
    md5: f57601564f88206e601fbbf58589d4d4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/coupler/o2i.nc
  hashes:
    binhash: 0b50c9fcc6b59af48f98523bc13977d0
    md5: bd85ad3eb80638c003e0433f54260a58
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ice/cice_in.nml
  hashes:
    binhash: e230d2839f17dea6e04ad1d1f99202a5
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ice/ice.restart_file
  hashes:
    binhash: cefeedf53e4d43e2a666430fc6c9add5
    md5: ce092187f104bd3d6ecd8531e8c976d0
work/ice/RESTART/iced.2957-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ice/iced.2957-01-01-00000.nc
  hashes:
    binhash: 442c183d6c6ad658bda48c27a94bb2fc
    md5: 8643563f54c9cdfacbc0b118f13d54b0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ice/mice.nc
  hashes:
    binhash: 9a27fa7566fe5141c291cf53e260ce66
    md5: fe5b69e3f7dd8bce409eeab42131ecb6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_age.res.nc
  hashes:
    binhash: 9565703a10820284f0588fb39280b940
    md5: 253cc0f3a5d7b574674743392fdc8297
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d1c61f7352e54f2109a97dc08d172308
    md5: f0046399fffdb95f409eb9e46ccdb917
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a3bf297fafafff47646e9209978f7423
    md5: afc354db26a5e1e262c6f21d7a27d2fc
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_density.res.nc
  hashes:
    binhash: 4bf4ee5b75adc19eba1e71302a207e2f
    md5: 4f012645efbf41be5ce20230a8b4634a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_frazil.res.nc
  hashes:
    binhash: bc8fd3e44fd35484e780a781480b28af
    md5: 5382b6de0e1d7e43e24e201e0aa30aa2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a10c04dc843dbcc979449f73e0384b75
    md5: d2f9637486e3fb6b1d16150e90612798
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8f2c5d706420d2c1648f099cbde42f07
    md5: e8b2887673b0d53dfc15eb6519012006
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 066aaf3f0bab44c015c10c9e0f88e6d3
    md5: ee23634eceaa6177fea582e358a5a804
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c28fdd93d869ca13bc5c36d01659c1fb
    md5: a457757cabf809be51cae23060dc1b8f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 894f141ac8b42f6f523111d13b1155e2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_solo.res
  hashes:
    binhash: 5ad51b067ae2969a528acd1d402179a5
    md5: f5f4533908be5fe711cdf9cd8075b24c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 46c63ec78f98dd666dfeacb271d0eaf9
    md5: 60755a4d4a77e885a9d7b8d542d10c07
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4bf8c7df5a16d2a813dd8414f06e0ddd
    md5: fbeea409e67aca1c7c6d8f8097a1aecc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_tracer.res
  hashes:
    binhash: c049575c3b1c1dde6c4da32b4363872d
    md5: 45f28d440abe2e11d649b75f5ddd64bd
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e1ce426157f173288150e8a36baf6a44
    md5: ee3f1f0569b5ac5d392476a35baf6714
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bc959df16e98c51e73e23acd48a9a604
    md5: 5045c38101d7a6061d13ff81229d7fce
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: adeb552a007ff3128874000355f7474c
    md5: 1e615b2ae9268ef72a77098e4b32ce4d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart280/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b79a69aa7d24c058032776de953ce2ec
    md5: 749c3493cd29f1764d5e417cb04e1a4f
