format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/atmosphere/restart_dump.astart
  hashes:
    binhash: 147b1589688ef0e89dfec08cb1e52750
    md5: 58bff1d2c59bcea8a4bf119dd601f17f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/atmosphere/um.res.yaml
  hashes:
    binhash: d5ab06c58864dffdfb086940de66f7a7
    md5: bae99e4200d53460e06f49d18cd40cdb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/coupler/a2i.nc
  hashes:
    binhash: 8d4d86b11794a05b8a81e2af46e155cc
    md5: aa750840e7b611dd0bc4277f71c693ef
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/coupler/i2a.nc
  hashes:
    binhash: 8e815ce49bf47683102976d9d8441777
    md5: a961bfda876d9a62161999f9b64f321b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/coupler/o2i.nc
  hashes:
    binhash: f6387cf34d7c2e48cc5e4174a1386f10
    md5: f124131929ef81f6b030d0e4d265d2f0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ice/cice_in.nml
  hashes:
    binhash: c170a4a03c4e2101aa7add73c32ffa61
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ice/ice.restart_file
  hashes:
    binhash: c4bcbaf3c2232f7c63f3c2a37275e091
    md5: 6af7a72fd7115abf9cb02a0d4ff9d1cc
work/ice/RESTART/iced.2847-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ice/iced.2847-01-01-00000.nc
  hashes:
    binhash: e6eb1070b0c068976924acdfbf125ae9
    md5: 2787c42d02dd4a6b7a71116c2f9af90e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ice/mice.nc
  hashes:
    binhash: 4c3023a692de7f5a41ea389b4ea3bf15
    md5: 8ce462613456cbdc9222b1b24dfbf5a0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_age.res.nc
  hashes:
    binhash: d33b0c77b9818635f8c5d1cec2b88dd0
    md5: dd76902b487dd3f0b8bd347ca9ae2a4a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9760238f5465d643d11d553cd898eda8
    md5: 8d905be697718477f375fb45657ffb24
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 953c996ba3665f87b2bd924656659c21
    md5: 62db9c62fe8bad062ea58a8940657482
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_density.res.nc
  hashes:
    binhash: 1827d336ebab83cbf840f5a908b89911
    md5: f82f257088670677d335133c49ee39b0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b0aa2ca3e900f17e04a4e368596a43a7
    md5: 70e10c3a2bbe83bef4d9c478b167b285
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 766024d94f1c56ff86ecb331f5e1a105
    md5: 67f6f6366e22d5f3ef9c46567499e5ab
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fabc74a12f6ae8cc322b24beb1794584
    md5: 59c809f62b0c4bc9cc6109db6313032c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f77c7125e9ace17bf0df8d60a4a2cb97
    md5: 74d13e12b41ee674b3a63a63457c9f3e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d456e9688a436e0e48f0ffa9bdfb3d28
    md5: e8c5792984167a91f3176a625c689506
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6163579796d8b9f23fffb2538fc19766
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_solo.res
  hashes:
    binhash: d73fc6b3cbe7db3192b20598f1c712a1
    md5: 53bba6be66238a21c78bd5396da447a7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c35c5885a61729ac41a1f83c72b4fce9
    md5: 3e12784f159fcc4d4287b58daf8f7a97
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0224b77bbb2a713c9c786eba73a2be72
    md5: 46620c52318de4d05060333e04f54417
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_tracer.res
  hashes:
    binhash: b8710bcc21f4fe01f27a903c886f60ff
    md5: befe9e1a552a2f081baf8d17673e239b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_velocity.res.nc
  hashes:
    binhash: fda5229fff016c3c4d00a6fae2e4e5b1
    md5: 4ede4a7198f40080e20d80c537c9a4fa
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 48e1ba0aa371dd65de5434d6bd255360
    md5: ffcf1dd36bd7208195f35d97e0f815c8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 191fe3141e8319dda5328df06e88c737
    md5: a0ff2ffd44d12795e3376a0e2a1e6f49
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart170/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 64aa109149744006fe8efaaa383284e7
    md5: 2cef3d7b190f3db1be0812df1502792c
