format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/atmosphere/restart_dump.astart
  hashes:
    binhash: 8ec8b0ee14eb32fc073704088e94c6fb
    md5: 83f016e991793e548a6f07bdb1bbd83d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/atmosphere/um.res.yaml
  hashes:
    binhash: 1c65908b58ba43dc3778279b5db73c82
    md5: 23933787be46112bab8fae56336a5405
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/coupler/a2i.nc
  hashes:
    binhash: 42cf5551f5da6a56e8c88d5d5b8d7144
    md5: 4b3dc8b87a7ae668d5812eae74274131
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/coupler/i2a.nc
  hashes:
    binhash: e78cd41dc60ad1dac288d62be0639410
    md5: d4fe2a1d79f98b3a02fa82aef46b18db
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/coupler/o2i.nc
  hashes:
    binhash: f07575fbcb4d52b7685b1141bb7aba32
    md5: 51b4134ee64bea7551ec275ebd021dd9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ice/cice_in.nml
  hashes:
    binhash: 47ebe2a719fdc82cb84d5bf0d83ddc6b
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ice/ice.restart_file
  hashes:
    binhash: d1f6aeb6c98c87618256a7e6b8b182a9
    md5: 0a2f58e41aeade7322879fea56a2e6c3
work/ice/RESTART/iced.2866-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ice/iced.2866-01-01-00000.nc
  hashes:
    binhash: 9bc53b69be119558105f17b2857d524f
    md5: 1566becf787ce5d80c92dc2760d6756d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ice/mice.nc
  hashes:
    binhash: def7291d3d8f425a1b5869a2cb49cf70
    md5: 2a4e53f3dacb1d09fed90bab9c262188
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_age.res.nc
  hashes:
    binhash: 7e05253e4ff5fc86539925805dc36682
    md5: 0e444bd62e46c0bce7bc1d867abc459e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0267ae830dc15c2e204a5286e1e143ba
    md5: 174982ffea03df8996ad64de3296e8fb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8ecafa6d9002c88cf99996b958a00049
    md5: a469e65e155bedb6b029f4d1161926d6
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_density.res.nc
  hashes:
    binhash: c265bf62f5cb8f48ecfbeb27d8e99182
    md5: 44d72b5b255071e763d470ba5a155dec
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 395312d556bc116b30a5149ef05c4888
    md5: ab4ba72851561bd50b94a5652a9d4b51
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e75e1815e76f988fb4bae5c159e2048a
    md5: 2ea8d845b3b170482a67f72789bdd987
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4081bb7e940fbcb5fc04babb97324365
    md5: d27261ef926f348d222eeea4ba899b4d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 23aa8bc3cdc90fee61328ff799b826c2
    md5: 41b1cb4e333c7e8ced8da4ddaab55a66
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c1530922b741bb536fc60fb896982620
    md5: c8c0e316a866489a68ed6a5fc3a22f7a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0f190ab6093213c5d8a80822017e4ddc
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_solo.res
  hashes:
    binhash: ed574a9f82ede1f273f60dfc4903c09c
    md5: 1f4dad3d0ea9dcb38600883d85da79fe
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 86678230015518bb771a888d63993dca
    md5: 4a2c34eaf41eca81824586a3d45583bc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 96b3359bc75f17741404646013fbf374
    md5: a2267301515e90691759cabfad4045f0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_tracer.res
  hashes:
    binhash: f4a9a6a89d1e0a429d42561ffca27f44
    md5: 91bedc2884b3e3ffa1b83e09d30f1504
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0b15ab035170ae24a6864d0616ebbb10
    md5: 0cfe97999ff3da965fbc0a75884924a6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cf9d5c3b279f75f6d740263d2927d357
    md5: e26f78ccd1e50544e7c7496dee841d73
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c1b51788a1476ffd569174227a1e34e2
    md5: d0679a447bad82167297d2b295e27eb3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart189/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d186d7ccca0e2d17db757746c97706b2
    md5: 6f4b41fdf88ecefdeb6500bebd40d0c4
