format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/atmosphere/restart_dump.astart
  hashes:
    binhash: 37e505e55e6fa2222ab7754df776d63b
    md5: 180cb53b25dcb2e2b5a69ed26c2f34f1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/atmosphere/um.res.yaml
  hashes:
    binhash: a8478a5d1639f22085526c1305537c2c
    md5: b83df0cae845e6528260a40d7f3aa582
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/coupler/a2i.nc
  hashes:
    binhash: b247b2c4b0adba4d70dc7418a8e9b0b3
    md5: e77997c57fe8186951e2853924e3ccd9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/coupler/i2a.nc
  hashes:
    binhash: c05e7d8466ae371e331e1f08eaeca30a
    md5: ee0b08185b7f09c995262c65479dff36
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/coupler/o2i.nc
  hashes:
    binhash: d0c604d4b3672ea8dd2ee4c0c5a155ba
    md5: 0600d1ce266fecb317ca1d2be015f474
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ice/cice_in.nml
  hashes:
    binhash: efeb375f8897371838cd3351d229de6a
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ice/ice.restart_file
  hashes:
    binhash: fe3adf73659db338850ace028235041a
    md5: 66ef6e90a720bb0ebb25cd58c1e7ff68
work/ice/RESTART/iced.2823-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ice/iced.2823-01-01-00000.nc
  hashes:
    binhash: 643e281485be68a71c4b3769f8921d3a
    md5: 0dcef61da7f6f884e29b433b4b924352
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ice/mice.nc
  hashes:
    binhash: 845e9aef228097fe53a41acfec981d8a
    md5: 2e8b1dec91c7cc92c23b5b4afc274c2c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_age.res.nc
  hashes:
    binhash: 91f5780bd504e7aa3ded8c31615d3219
    md5: edc39acc07c20160d56c18d5bf9947b2
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 48948246dd776de91750ebcda460a702
    md5: 44a9ba157a4ac674ff6a50b6a2f4b1cb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 62988123f1bd68d4a635807e5bbae46e
    md5: 0e5bd1a12bb69c0d097a85c87da7c8fa
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_density.res.nc
  hashes:
    binhash: b997af050e2490e374b137d5820994b5
    md5: bb36f82e18141864dcb17d6f96dcc9e5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 564cdec7886a450dd04034d01b016372
    md5: ce4f74c4d8808fb4a0c1e6b53ffdb849
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8b6117f65b42e41ffb08ed3d9f23570d
    md5: 9af2977938ee61702a9125b6e451102d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d08084d213ff2a1e915c078ef88462de
    md5: be6b0ba713798120832655b8c9954afd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9b632708baae6378c7a4833ef3adeb13
    md5: 3d62fd8e8c0a7c930e316b20fa81bfeb
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_sbc.res.nc
  hashes:
    binhash: fe8fe4c241439ef05c601cb4c7553453
    md5: cab9a2faf4072cf4462f53f91dcea178
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 95a0d6bd4014d6145670fe86d8f2bdc5
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_solo.res
  hashes:
    binhash: b09c94b82f3118df5a51c24ea7e9f993
    md5: 2416a317a408da9fc740e734ccbbb4c0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4b0ebdb331a604b42a5ae2f16ead0a20
    md5: 533609320a09d94ca463adf2edbf4fbc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e9df270d7913c5a1931c48797ebe18d0
    md5: b3481374942ad0f41ebef5d1ff0c9630
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_tracer.res
  hashes:
    binhash: 9a9dacc87d0852c469d04b57708bddd5
    md5: d66fb550ff893a68af7f585d9b7f3ecf
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d2d3ebe3fe7e3481c9faf004d34360f2
    md5: 20c9c997a93bcdae317153f1e7a3d996
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6fe00e3811ff62428f3bc160b460bdb4
    md5: 7fdc4c21508b598327b8702e390490b6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6f96cefdbeaa922425e0289ada6fdc16
    md5: df8195b6f36b8af1e2377840aaac1ed8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart146/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: db85776cbf2a8294042b2b667b9e5e32
    md5: 878886eb28ba1b2fb2fda5917299ca89
