format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/atmosphere/restart_dump.astart
  hashes:
    binhash: 98054e59ab1a321f7171def2a9bf75ac
    md5: c5e7a58a41559247d541f75ff643a2a5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/atmosphere/um.res.yaml
  hashes:
    binhash: 81d27c54d4d6d25d5055883794082d5e
    md5: a23e89283d41851336eecea3e486f140
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/coupler/a2i.nc
  hashes:
    binhash: 2439430ac06b11c6b0052ea041c01cd1
    md5: 44fc6228ce96255323d18b119ee6532e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/coupler/i2a.nc
  hashes:
    binhash: 737ca4071129fc5ec70bcaeee0447c59
    md5: 8dd7ad938e99bee065dc4296d91748f7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/coupler/o2i.nc
  hashes:
    binhash: 963515282d025183baf52248a3a44c51
    md5: 260f3efd58b775568ff37ae75f4acc24
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ice/cice_in.nml
  hashes:
    binhash: 9e7420b232d338b46d3afe70b8a548dd
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ice/ice.restart_file
  hashes:
    binhash: a552e3f3476f4251821f24be624499b4
    md5: 1090ead121eb309bfac73df749c01c3f
work/ice/RESTART/iced.2828-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ice/iced.2828-01-01-00000.nc
  hashes:
    binhash: f3deb0f6357760f820188cab120bbf49
    md5: 47a6de8076f28e7d8844012968bd4e77
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ice/mice.nc
  hashes:
    binhash: b6b28f068345f7f21c7980b05e3d8bbb
    md5: a2b1c2765dde1bcaa79c3520cdd44459
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_age.res.nc
  hashes:
    binhash: d1d081d4cbb7eaf0a310b3ff85916cfb
    md5: b263bfc0edbbee0ef025d00967ad8fab
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 15f0da27ba13dfee8ed625537a07882e
    md5: 6c335ec87e108368c113fd443c196864
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5483fef0d3b90f25e7cc0520bcbc43ee
    md5: a018c9c93ac3cfe7a0401ba0e50d4fa3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_density.res.nc
  hashes:
    binhash: 3656f0a5af98623f46fa38dcd7d78a81
    md5: 3d661d78d2c8813fbdf18eb24dc8dc15
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f30746931bc5fe10391b95c43824f782
    md5: 0d9c45c3ed63102c8ad624c3d99c2575
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b9767724b2abe97a44e64a16f01ec8cd
    md5: 3ef3e060467d9eca565b1fbbea2c1018
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_neutral.res.nc
  hashes:
    binhash: db86b27c86c01d3b88893b0019582dfd
    md5: dc9e945d88177fac5ac62a5dcb2a359e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f3c5474716f6d829c0ddd06fdec64230
    md5: 773d2704c22bfdadbe0ad45d62a810d4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3c41bf8e9419de55301a2d5b88743406
    md5: e837c5f5fb7588d68f1317deb27121e8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 225ed688ab193a3605f6f232cf9ea4dc
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_solo.res
  hashes:
    binhash: 10b244b32870b7ad60a4a28aa4662a78
    md5: d52455572dd567b696caab4e6fc9e5ac
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a0d903b4a1e8818aa4ff738a36660a0f
    md5: 8fb2134d6386a3a99dcc5af6058893f5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_thickness.res.nc
  hashes:
    binhash: bb1fe5782d8bceb499715e47408fd7e8
    md5: b09deb80c9ae5526e1c06e8a9cced867
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_tracer.res
  hashes:
    binhash: f1a98c3aefea52106a8c845c78e2c74a
    md5: 58c438534a8e5701fd0c6677470520df
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e53c008e62081442e54c5459626685cd
    md5: 683d59f00dff0c3f16ea968930920caa
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b449b94da181db1055769e2294a67161
    md5: ffcc8479b13872b94a04343b2f9db5e5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5b5178650f238352b78cca6b2420389e
    md5: 2de42bd0b40aa9386341c5f6d28a77bd
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart151/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0e0a0299bb873de56bc461c83ae9fdc4
    md5: c376cdeaa4d246379eeece1f9b98ab8a
