format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/atmosphere/restart_dump.astart
  hashes:
    binhash: 281b92515afeb6de338592e0c40c136b
    md5: c3ab32f7288157a0e621291e661ef62d
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/atmosphere/um.res.yaml
  hashes:
    binhash: d347f1937294fcd2def1c29d374da9e7
    md5: 8befeeca187905b32c0f172ebd997460
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/coupler/a2i.nc
  hashes:
    binhash: 20e92c93a4e26530fa923055a11f6a9c
    md5: 5577ba3a5a5d041d337c42afbebe7aea
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/coupler/i2a.nc
  hashes:
    binhash: d57a55757c17cf6c29001ae18c022e7c
    md5: 6f6014149998f9e66f3a237d753c6241
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/coupler/o2i.nc
  hashes:
    binhash: 9b2a8843e233227a15271dca0372d915
    md5: 49fbece3066b709aff00074a9524e40a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ice/cice_in.nml
  hashes:
    binhash: ed97e9e3e1161ff7f31d796a81cc93f6
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ice/ice.restart_file
  hashes:
    binhash: 530e550cb7a66dfce392fe7c558dda04
    md5: 2f3cbf6e4e7fc37072f8b3f4246004d8
work/ice/RESTART/iced.0001-01-01-00000.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ice/iced.0001-01-01-00000.nc
  hashes:
    binhash: 56c69942bbc9148bb679dbc25d5e1689
    md5: d7158e3cd572e0f59b3300f38276e8ec
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ice/mice.nc
  hashes:
    binhash: a7b5f6f3d89d8f8a5b875665f350a369
    md5: fe95a1fb134d40cad01907343269ed16
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_age.res.nc
  hashes:
    binhash: 3ac0473ea0340be2abb36570526ae5d0
    md5: 9a0834dee30659fb06463f86927079f0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 615a154bc19816840c5e96c8eade5169
    md5: ff867a2fa7d2d6d734692b750be33e5f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 744017844bbd92f43bb193c580e438a7
    md5: d807e37be71f41ce3c773d3c36407338
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_density.res.nc
  hashes:
    binhash: a2dc7559c24ed70ddb5d0f12aeb35f73
    md5: 09bea23fccd16f8bd440e64950149625
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c2ac6a6b2336d813ceb41b6a184521f3
    md5: f115a7ae3019501ab7edf2477f50c3c8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a09386c96cfe3a8d93549d4910b8fcb1
    md5: fe3b606f4cd382ed749e6cae1d1eb398
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0919fc2a2da06fe29c6dcd22fcaef348
    md5: 3b6217c3f7f2c97f36b5c6e0696c0b53
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 694952e7f236df583210e55089049f83
    md5: 481c0569fe5876cd56e54d2d3faba154
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 686ad331c1ee6616df02123a97f94c5d
    md5: 416f9f68f267e779cad9b7f747170b41
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 309822e40d9fa9470db94b174089bddc
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_solo.res
  hashes:
    binhash: f2e7d3554f153cb7d062c5ccdae4e0b7
    md5: 4f2e945cebd878e006a2e961bef57ff1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d87dbe2c411aa2591e5e9c6c17f75fe9
    md5: 7590f18fe287f8cee22204e348a4b0c9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a113170a6fe00bd165f3152c41f7dfdd
    md5: fc12071b725b88b27360fc23d4938377
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_tracer.res
  hashes:
    binhash: a67c4646cb968e4ea2c54961caa7b8ff
    md5: f310fefb9537d27ba9fd1ab8b1e4abba
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1f9a8dd0a79210d8bb895f527af8a27c
    md5: 6970fe303122852f341b691f109955d1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1a5fd779ba387e28a430ead1e7f70a88
    md5: 137cac2076982e9ddd4a077c8c0aef7d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a99a34eba4e41f35fc2f425c339f0998
    md5: e9d8c90f24ed3a2f8cee7211d534cfcf
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/pre-industrial+CN/restart/2026.02.20/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 892fa40d3f53172f300837a61839522e
    md5: 9d189f0331a3c0d4ab624fc66e50b1b6
