format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/atmosphere/restart_dump.astart
  hashes:
    binhash: ecba64c4b42779c9edcaf4c19dd73ab6
    md5: 48492f1eb52f6f3777c80414d6609d90
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/atmosphere/um.res.yaml
  hashes:
    binhash: a795a25396400b5aa09e63673a66a917
    md5: f62cf547c229619aa42e23706013a803
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/coupler/a2i.nc
  hashes:
    binhash: 8c362c325757fd7328f99ee0f1041be2
    md5: 37464b2f7f85083547e31746b453d921
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/coupler/i2a.nc
  hashes:
    binhash: 53c4ec4d28d605556a7a4b874604b555
    md5: 2309b6e26b5d9e5e95c6a116812118d5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/coupler/o2i.nc
  hashes:
    binhash: 9cdbaca58ffe53de0a84439559c848e3
    md5: cce84ce3ab4247a611eca2bcf0fa271f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ice/cice_in.nml
  hashes:
    binhash: 4c7c0d0682fab868ef3643dc0d543ebb
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ice/ice.restart_file
  hashes:
    binhash: a080022ef0f56f7ea81aa4b65ad931a9
    md5: 5ac9a1c57ec548f56c1076565f3607c0
work/ice/RESTART/iced.2775-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ice/iced.2775-01-01-00000.nc
  hashes:
    binhash: fa1c9f5f0f5dc23f1e18dd5e0ae07680
    md5: 3e85a93436e1a6665e72e120468a9971
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ice/mice.nc
  hashes:
    binhash: 1e495e1ef2acb598ea5afa65bde53aef
    md5: 811c0c64fd2c4424de18ad8a50d7e5fe
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_age.res.nc
  hashes:
    binhash: d7962441093f56d3ebab7defaecf87ce
    md5: 99d6527ed99eedb34f6a5c91939aa7aa
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cfb23e70f52a538c6202ff4561874fc0
    md5: ffbbe4ddf7b06b1644842a6416e96f11
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a779befc71e50bffd10d97f8cd377d7b
    md5: b3c8d608fb32eb0a8faae563e07f4c8d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_density.res.nc
  hashes:
    binhash: 8dbceb7fe58e06d007389845acf6a16f
    md5: 1546a674a84aec111762397b0a2ee85c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 746025d45efc7c064f447b2aa0274400
    md5: c1f33506b1ab09a34a9a82977f56e32f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 244d1541bb759f3aacffe2170ad9af50
    md5: 011dff6e7145fbe583b68befdaeabc67
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_neutral.res.nc
  hashes:
    binhash: cbb2872b15fce6270fe07d48e5d06d87
    md5: 9719206cb68e2a556f44dfa0c32482f7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 07710f273b474eb2883fbcae85cb618f
    md5: 24d435d0cdd55291b56861903386a440
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a6a0afce5952c4c0d1fe1fdbcbba2895
    md5: 59d052d13a52e98bff971e42d57848b0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: eedccaec82b535fce7d68dcc376a8484
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_solo.res
  hashes:
    binhash: 98b483641cd0769d2f4021508268342c
    md5: 8ed67364795f3ec8142f6f2e6cd359c0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 46f8b0c51eac0e21ffefcb83aed1eae6
    md5: b187e67b3f6989beff951a25a93a8ae1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1f42d73e4fd77fc08e61655b62f16c3e
    md5: 3a411a7779fdaecaa7e3b2727690896c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_tracer.res
  hashes:
    binhash: a586603c39f45f2e0f0f5effddd22f98
    md5: cb605c5ab405e63bc3857813c60f7e3b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ba69b2bc77508863f0326cd97753d823
    md5: 52557bf27f357fa09a2ae57b65be38b5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 25a4e8536427a4037a259b16364a481a
    md5: 02cf702713e0163b434aad2f44725b08
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 45dc0666e22b5171d89bcd0d66d80fba
    md5: 3bd76ecace7b7ff0fcc33ccf932cb879
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart098/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 28a549ff923aee26ce0736474f02570e
    md5: 6f17e5e0e25c90d50b26524eb05ecc19
