format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/atmosphere/restart_dump.astart
  hashes:
    binhash: 7b25bf3186bef4468c3c059d84e556f7
    md5: 09b5eaabcf8bd354164d42a03d095836
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/atmosphere/um.res.yaml
  hashes:
    binhash: 9a9da9318109cdaf0e873eb3aee09291
    md5: a19e75587ff30a763b94c5b216903361
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/coupler/a2i.nc
  hashes:
    binhash: 3d793311f365ecda0cd66f45f06cd018
    md5: 8dcf7f7199ac1a8abb58c5ec36375a95
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/coupler/i2a.nc
  hashes:
    binhash: 7a47529dfc08bae7c683fad9f288ee63
    md5: ec0d359d7cc925a01d9b03a01127ee06
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/coupler/o2i.nc
  hashes:
    binhash: 5dbda89b434e3055214f6eb9116832f9
    md5: ec993beca96fa05237525f5599ec186f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ice/cice_in.nml
  hashes:
    binhash: e18eaad474880d48c94ff8bc2f2a3012
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ice/ice.restart_file
  hashes:
    binhash: 70ea780b0a37cf11132c010f41ca713c
    md5: b3ebd4732c8ac12d33127d64f79320cb
work/ice/RESTART/iced.2825-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ice/iced.2825-01-01-00000.nc
  hashes:
    binhash: 53923e800b42a7649dace2009c6736a5
    md5: e72bfe82c4edb376180d50996fc2312a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ice/mice.nc
  hashes:
    binhash: 62716888ca46cad1bd6f0b69c5b6bfae
    md5: bd76ea2d334a50dbd24d39a4e86a59aa
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_age.res.nc
  hashes:
    binhash: 04547c1f0b9b3201a65cf6a369297204
    md5: 54265717ae116b40f1c36203444741e8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 337a873787e08ccd5f6d022ffe9ba84a
    md5: 812fc21bb8647bc5aaf35390cd1a4438
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 162c00c37f258538551c1fa037d5cbcc
    md5: d3cc53edbdd6191e07046b0aa7fcef29
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_density.res.nc
  hashes:
    binhash: f081e668b41dd3fb911ad7f6881e22c8
    md5: 9fa162ef5fd70a9e8373db202c73646f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b54bf4172a7301a0cb9b5ca1cacb811b
    md5: ed25869a48cad73ee5449324113e0cce
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 83c2a65d50c792a9b4416404de07b4df
    md5: 26a95c2bdafae0f39ef2f5dc8eb5ca59
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0ddff1454e24609c0439eb2a1664ccbe
    md5: d9c29f046c0aea118bbe64b05efd40ae
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0e77124c7166ca2e8fd57ffcbc562522
    md5: 4b5f73865d4e226c4c5ba3b2f72de14b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a80a7687f14f6b8d2be6cd1f0dd07761
    md5: 5cb939330e0cf099cc2e894115fb4609
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 33f536cd9af262ca822c6a800472ffb6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_solo.res
  hashes:
    binhash: 221390a51917263be80be250388ba10a
    md5: c3eaee7d255b1e5cc4d81ed76209b76e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c12baa774dbad3abad90638853352a04
    md5: f0a6f11cf0d2a4f31648d1e6d6f82e2d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_thickness.res.nc
  hashes:
    binhash: dde17af3cd4373d0194a5fd1d1d1db99
    md5: 96575ae634030b35ce99041b3aa63582
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_tracer.res
  hashes:
    binhash: 0d665540f8a8447245bafd4cb0ffa51f
    md5: 9509530056b3577303c414bc014787f9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c05766c77e0b28fff5012ce9fb37c6d3
    md5: 63565b783f6fd3dea9bd0b679dda833f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7c84c761edc1f157952b11a3507673e9
    md5: 03ff322884dedeffc2a80bccbe190445
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a6ffd7c9dd101c6e373b9aa34ee91b9d
    md5: cc57de445cd0c17fa83d58f7f39dbbb2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart148/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e2b69232b29b852d8e0a9803fe431c40
    md5: 8e3d3ca96a1cb47343065143a8bd43e8
