format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/atmosphere/restart_dump.astart
  hashes:
    binhash: e0a328544bdc68f8fdc145f96f78fd55
    md5: f064778744146a9c72e17d1024922f1a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/atmosphere/um.res.yaml
  hashes:
    binhash: 65423fc42e93c7b148dcf06b3fb0dd52
    md5: e5dd857136e1d083185acf0f6310cccb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/coupler/a2i.nc
  hashes:
    binhash: 76b4d7360bb028e90eee129494cba064
    md5: 6a9d60ec1f05f04b9095548c2cf289f9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/coupler/i2a.nc
  hashes:
    binhash: 2af7408455f543eec69e151466a77979
    md5: 577d70f517c4a7973c93870e253678c8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/coupler/o2i.nc
  hashes:
    binhash: ef9e85ca5e3e48b4e413163576f4c442
    md5: 34b55d3b99b3d4f8e26177c90d6d45cc
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ice/cice_in.nml
  hashes:
    binhash: b9878b53ac7c97e5462997c329df2ef6
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ice/ice.restart_file
  hashes:
    binhash: 1413982551fca643d2e1eeb0416b51a4
    md5: 758ef0fadb2073ed1ace5f0e65849f40
work/ice/RESTART/iced.2812-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ice/iced.2812-01-01-00000.nc
  hashes:
    binhash: 5de78c624373b1c2f534f268e24b8dad
    md5: 008c59c4d48d3a2fe6c73ab7571f3b42
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ice/mice.nc
  hashes:
    binhash: 381a59495980b955cd8bcf8cf70cf134
    md5: 5348f175055dab1f34da6835f6dd0794
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_age.res.nc
  hashes:
    binhash: 4713f8d6b2ac9efca7b6971922fc30db
    md5: 8dea6b744474137da002adfe20274934
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 40a6ad3e20c8cfb9bd211fe45130bcf9
    md5: 3899a04e56a3c310fa62695ef648a162
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ada488c24f2df07c1ba3258ef7c0e40c
    md5: cc4745d0470cf21e0924a49b52bc0e9a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_density.res.nc
  hashes:
    binhash: 02c455edfd680bf3275c3fcea644c95b
    md5: 92f4ae49258efca5efce5dc3b2ec1079
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 68c4e9109c9ef18901525f6ac7db810a
    md5: ecd6541e8c6d930e1c1fa4e5bf8c4ae5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 55ae798b4e6cd30f218508e7d0b912b5
    md5: 07be2f24551a66bd9b4656c07bc419c3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f4350d29b48b5ceb4af56a0c23df202a
    md5: 6e1a86a9bfe858f29f8a7151f4cc74df
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 64972f2febf226b2baf7283ed28d385a
    md5: d75d7e21e42477fdf1dcbd39ea920aeb
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 21d643a8905741eafc587991d18b8856
    md5: f94d3ea2723102fe4e89b7d9060e7360
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9a18dfb5b6a30d00f5706183cae6b256
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_solo.res
  hashes:
    binhash: 915234cb0afac865062365847abf372f
    md5: b0cc69deaef3f6d5352ef03624f014d2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ceb0eca2ec286bd6bdbb4074728396e9
    md5: 555036712e845f8396a8dd4ac3033135
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d929d16118d0c7429da1bdd8ca62ce29
    md5: be8b5c9038345776ab0546277862a558
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_tracer.res
  hashes:
    binhash: 9ab2d13f6b1532233d27a12edc4160fa
    md5: 5411d71d46c132d1cf01775bf5c6c299
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4e6856c8c54f8d1bcc5086ba636c9459
    md5: 20fc084e0f1573619971f1c9fbab5a55
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3af4799c5f8804ed49c9fe74d204fb3b
    md5: 46a1f5fe6e8b2855dd456ed12f9a17c0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 59026b9333a44bd543957298e29125ad
    md5: b6621bec59e90c18fde453c21ba182af
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart135/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d3d1e47b1784467987913bf708200194
    md5: 2b14219880c903dbd7e5da77fa2691d6
