format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/atmosphere/restart_dump.astart
  hashes:
    binhash: 4b53ed871ef1d453db5984d62fad54b0
    md5: ec5aa73e4c7b37655bbb2f8081b7d0dd
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/atmosphere/um.res.yaml
  hashes:
    binhash: d1c2f2fc67463071ecb3b8775d455914
    md5: b1edd21a8760c370720c3bc42158da68
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/coupler/a2i.nc
  hashes:
    binhash: e61ece43745441b9b959f9b922001d73
    md5: 2948b2dc5379c2e465e725e5bc75cd18
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/coupler/i2a.nc
  hashes:
    binhash: a5e8d0a80505fb0b7aeeb93feba550b0
    md5: 5539a4a7b431d1069b0e05b2523d5ed3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/coupler/o2i.nc
  hashes:
    binhash: 2e8bda1f179ff532ab51981e1f6ccbcd
    md5: de8ad9e1d5343d61edb649c63737c706
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ice/cice_in.nml
  hashes:
    binhash: 811addea7d3e8967ad5f719040aae595
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ice/ice.restart_file
  hashes:
    binhash: eb3ea458b9d691ee6602cf1310e116ed
    md5: 311d97779ba20c9661b0434959ab15f2
work/ice/RESTART/iced.2734-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ice/iced.2734-01-01-00000.nc
  hashes:
    binhash: 74161eac65ce031342c86b66dd30efd6
    md5: 91d84bceb4e708ec71703ff2af7458d5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ice/mice.nc
  hashes:
    binhash: 69f903b593942f4e218217f9e91cc621
    md5: 170f7aa60871139a9d5985b580160f96
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_age.res.nc
  hashes:
    binhash: 2943f54994cceeea9b15e9be1b1df3e0
    md5: d1b0ea5e88c4b6238af8d5ae817f8357
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d18b0f5a5f78890e4a4b3f6d99a33348
    md5: 1cecdcc000376d6c0deb6fde8167a08f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c31c1eab6b3b878fbb8dd42d7665e895
    md5: 48fa3d6dbdb0bf0f79f8a83b9d12305b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_density.res.nc
  hashes:
    binhash: 4933381d624378d8d8dc6906297329db
    md5: e4a17146f0df99c2b23a813d2b818682
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 289022bfccf8125cb1ad5f2ed400bf71
    md5: 34edcf7e125fb4a17dfa8bc93154fc1e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6789b92354e972258491cd37e40b6564
    md5: 411d1177313230c935de8ce3cbe5a649
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 863690aaf72080f1478309285387f8a4
    md5: 5e40e04bde722dd9f2e90d2f8b6a1422
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 356719567b7b23a188574e57f8541f36
    md5: 0ef6ac25bd49c7645fb57a1eda7e3c91
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d1754979fcbcbafcb10ec7f0e7e91140
    md5: c245d56835159ba4712cb3fc3223e23d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3268b82e2c608b02a76898623d228994
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_solo.res
  hashes:
    binhash: cc8722fcfafe74b4c19a406069bfcab4
    md5: 9911c662788c9220a4b9739975b23655
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 29f1680307fddaeae9c571856c54847b
    md5: 6f06a01f8cc5e94a90e14ebc9db9b81a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 604993fee9d68ea273ec0e253d7e8147
    md5: 6e2806a1ef148409416e09c2e2242b08
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_tracer.res
  hashes:
    binhash: 1784ed3ff590ff1d848720f506219301
    md5: 229dd54e8befce1b736ea83df96e88fd
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 755b9ac101166536cfa714f1c4b9909d
    md5: dc195a936ffeb9d38a427ec7b0f9a520
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3dd81678fd772300a2970366a84b3054
    md5: bcaa60c55b423c62626e791c6b05427d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 758399612c0d6483e12e4b8bfca3e485
    md5: f7d163697ae7eee9ba71b14931afcfc6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart057/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: bcdea8c022b789c2b24628bfae5aaf39
    md5: a8bd24daf25c735d3b8b1ca21df866d4
