format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/atmosphere/restart_dump.astart
  hashes:
    binhash: d8d01b893b154272ebc6deba82d78476
    md5: f6a146d4bca9185c739a3f940b23a3f8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/atmosphere/um.res.yaml
  hashes:
    binhash: 72d96513001baf24a49e972218394831
    md5: e07a5db20d19f83efbbc272a75d34ec4
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/coupler/a2i.nc
  hashes:
    binhash: 7047ba4c2aaeed923862dce2309aa977
    md5: 4644840148865bdd8b3f052b76d63045
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/coupler/i2a.nc
  hashes:
    binhash: b38ee881e31e6888c1cb48c0c5df16b3
    md5: 315110440e998853a31d3a4034b64add
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/coupler/o2i.nc
  hashes:
    binhash: 0ad8dde25de68de4b7458a3babbb6b4c
    md5: 9800dcdf01473b0c38f108240fd2a916
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ice/cice_in.nml
  hashes:
    binhash: 4967cc96e310d826225ede162af928a6
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ice/ice.restart_file
  hashes:
    binhash: e23a9adf461e50b183cadedd46d57981
    md5: d42138141b47bf1afcaeb55989c11598
work/ice/RESTART/iced.2803-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ice/iced.2803-01-01-00000.nc
  hashes:
    binhash: f4438070bc62b3784a08ac2568267ff5
    md5: 8f5abaad0ba90fa04afa7a17bfa28dd2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ice/mice.nc
  hashes:
    binhash: 6624bb97c65a1bb1d89e21756b5f8659
    md5: fc2feac91db0aa411ce140e451e15da4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_age.res.nc
  hashes:
    binhash: af53975ab1b8c72f6223835bcec0ac92
    md5: 84ded4d8731af1cf93a64e2f629d41c4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 61cb397df161eb73e1429c5790f6c088
    md5: 151a9e70f9c043742434f65d43575712
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 43f1d6a83bbdb15f9503a7c4a0b38a76
    md5: 4a21b3a165b98f118556640510f54a6f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_density.res.nc
  hashes:
    binhash: 3c7167ea9b48cc6026701769f4b6c2bb
    md5: a8a73ade947d5847d3d47593614419de
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 63f14a6e0b1b37382760ef7ba5af72a9
    md5: 080e537ced0d781a4a8f8a91c1abb47f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3facffb71bf448ea440f717112d77d87
    md5: 7acbb19cba3275c41ae83e492b700a99
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a4d788135cbf47aeb3b5f9b4d84797ce
    md5: b99209a89b0496e1b931599129248811
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fea33a05a48d12ff34e18aa2fe248611
    md5: f01a114f6979fa51e1e90292862a7032
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 08f0c5f6141195c6e259833c336b826d
    md5: 8494c018470fd8eb26756500cb1efc75
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c7c3bd38549ae459d6b8ba8e0808db69
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_solo.res
  hashes:
    binhash: e0d8a31d1ac715bad162ffa8508a964e
    md5: 345bb77fbd7a6b16b7a4ac8dc57fbbfa
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 03e8828af0973dc23ecf3d006d24b19e
    md5: bb5218e9633fbb581e7ee2e623cce600
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 56ebf5b9e1bf35051ceffddce1edabe7
    md5: eaae6ce1d2c6ebd93333e1dc710d8905
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_tracer.res
  hashes:
    binhash: 0c78b0adb88d6b65dd305f2c46389f92
    md5: 4f66d16da1c42068506d053658b168f0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2eb5188d2835c6340000128220804880
    md5: bed75871789551aa7c9502e4c4222d31
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f0126c66034430803df9177fbaf08a3a
    md5: d6973cebe82d9b9962d353e1509d19ff
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 587db76ab40d8f8070c29297a79fc214
    md5: 5d7ce6e6eb48e6c9d0f0f1906e2ed41b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart126/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0f08c5887c589e46eda7f8c12eee4418
    md5: 594321457a5bfa5d026c2966ffc4ad0a
