format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/atmosphere/restart_dump.astart
  hashes:
    binhash: fe0b28e758b82a88ab44ab75a5d42800
    md5: 78f28ceb3ecafa1bbf21ab34fe4d542b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/atmosphere/um.res.yaml
  hashes:
    binhash: 818e55fe2b35bd9dd1b3de8fe66682f1
    md5: 931ad21b244af3cdcacf54756cfa78d7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/coupler/a2i.nc
  hashes:
    binhash: a8d9ed0d83c48a4f980c077dd57a16ab
    md5: bc8dd95db47aa8abb28587075a8c253b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/coupler/i2a.nc
  hashes:
    binhash: 22967462f42f5c2f52b0e82202dd0e71
    md5: 2359e2e48226e1aea94bb000a9249e21
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/coupler/o2i.nc
  hashes:
    binhash: e036cb56bb5795aff1906c8d5b7fe912
    md5: af80f43213fff3c5e1c8effd180ccf01
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ice/cice_in.nml
  hashes:
    binhash: 618892e1e215d73d78ce2e176f8d94d0
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ice/ice.restart_file
  hashes:
    binhash: c00d1fcbbd53933217b64f2ccfb8e969
    md5: 9050ac5757c6631861047088f244c57c
work/ice/RESTART/iced.2693-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ice/iced.2693-01-01-00000.nc
  hashes:
    binhash: 75ed2dc24a354009e468071588a63097
    md5: 784feeea1e1ff7711283471f19dea37e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ice/mice.nc
  hashes:
    binhash: 9744ee37729f7dd355f08fecc23ae75d
    md5: cbd3aa4787ec803fd6ad55f8ff2bace9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_age.res.nc
  hashes:
    binhash: f7ca2c935f89dc82e75453664e657b3e
    md5: 0a99d186216ec2e5e26d502ae6a23786
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c71780bd881b6ce71f11fa09e8c201e5
    md5: 6e41be6a9386c78e79166efdedf6f83d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 083d4da2368b80eec3d424244c330d47
    md5: 81a912aa16c7a20eb0b7d6b8f995b4c1
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_density.res.nc
  hashes:
    binhash: 028255ba6036f712c885f64a7cc22821
    md5: 31861717eafa3f98d9d37ec3acb160a0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e3a8e5b045a5dbd8cde508061869b448
    md5: 9826eebce6ba088648fb5792f82f08f3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 30e432d25ebb14178152fb3e05a84958
    md5: 3c0def71a0c4e0923b54298d2147e587
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6f5796916c33e3167c66f248b971e495
    md5: 28368ca7aa9b61a6eb9b1ea68e85d5ff
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e6ed94cfaa5ec6ba6c00075df2a680de
    md5: 73fe8040baa5f43771691ce9dcc6ca1a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c7bc3ac9bb0cc87f5fc6845fb84e62d6
    md5: 5841d8c08c7ede7733f070da73e26481
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: afc70d9f733686cf1e8542fc3e081b8a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_solo.res
  hashes:
    binhash: d660dc5b2b4572b606b434529e992e44
    md5: 4d717030ac5207ff10d421bf4a9e21ff
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 540a36cdcbaedee7d43029a4cc1a85f6
    md5: b569164ec1a5b1ea4606880ec64deb33
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b3e403cca419c1b9d4d5dbeb0ffc9e26
    md5: 94d71946d040787a967bf9fede9ce027
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_tracer.res
  hashes:
    binhash: abb5bb9d57181d215279c43b32e9e40f
    md5: befcd66ef738929abecef2ed8197542a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7870de6eea144099b4a9ba1a6aba90aa
    md5: 491f0b4768723f388ef2377cfd2332ef
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f925959dd3de6f1745b70e1ed94b6524
    md5: 8c8e3cbd7fb25f1df09cb7a9949955f9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4dc2f9f0dc66f2e569c4b04d8b41d1b5
    md5: 1893ee9a7df4703544bf88a73b57cfe7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart016/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7656c3b33b4b3b63bf7b3c089ccfb640
    md5: 6df816fd7e03eb12f692215b580ca929
