format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/atmosphere/restart_dump.astart
  hashes:
    binhash: 13bfbe7fba28a36809dfc0c77c9753bb
    md5: e5e6319380e7533a3dbcf58cab461dde
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/atmosphere/um.res.yaml
  hashes:
    binhash: d29ebd984bb4a7f6a4d5f81544cc906c
    md5: e70e7b24d430e5b60351b5fabae7783d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/coupler/a2i.nc
  hashes:
    binhash: 73e60b7f81b4712e37e728c21308bcbe
    md5: 13fc4fc617a5bdaae88fb4ac566ba0f7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/coupler/i2a.nc
  hashes:
    binhash: 9112019a8102a2a071e682a2323d899c
    md5: 9607e68774e4557340f7202a2a644ab0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/coupler/o2i.nc
  hashes:
    binhash: b94bd17e70eaaaf4d13040f174887ebc
    md5: 417d60675605d6f90ee5326614482653
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ice/cice_in.nml
  hashes:
    binhash: daf5f14c657d306580d64f5c228fdd1b
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ice/ice.restart_file
  hashes:
    binhash: 3acf826bfe3acbd8ec9a49448b763876
    md5: 373e00ff18278220e5d57145d3fddead
work/ice/RESTART/iced.2910-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ice/iced.2910-01-01-00000.nc
  hashes:
    binhash: d03edc751f5e15a379c145011dce0488
    md5: 29516564d47e4a93e846096dfefdef36
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ice/mice.nc
  hashes:
    binhash: 0e2a92683e5db7236f78952a52d99be6
    md5: d6edef3010da39c5c413b4f30069bf2f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_age.res.nc
  hashes:
    binhash: 5c011cf1d7d2e5da20848b4dcff1fb0a
    md5: 0b3097efcacd4fcc18cc381c02b8c4bc
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 351bdc8171fca0a95f68dd94f3b3fb93
    md5: ae8bc1370d79e6d736dba73f3c7105e7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0caaf9afaa58a556cf9522c4edcd81c1
    md5: 344105d0d3ccac6df913905cdd80fbdf
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_density.res.nc
  hashes:
    binhash: 50fa2e47156eae75dbb3430422f3b6ee
    md5: 5abad909c89dcf0a9d4c6972d4193666
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 27cdd4348933e31e9027b9d26cfc35ed
    md5: f25c2183e9c4b37fbf58220cc88d5904
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c708230d1c3dde74dd652c863a9023bb
    md5: e544150a12cdf836bce88f53554848ca
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a8d86799078f2ab0979743301d0cd05f
    md5: 3ae6efacc4eecb72c957b2f6a6033a1e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4f1c95de14cf3b04b96819c0712c3ce7
    md5: 62c97d2591f8e33407a82acf58e6e66a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f48b3c43ac40b6e50d397682769472fd
    md5: 23a7e4d519a7b1d8ae59a7170af1bb47
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d5184f5dd18ca344b5de300ac8971745
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_solo.res
  hashes:
    binhash: 3672d3d67aabd4231331ef8e950c6491
    md5: 380375e0816a5c1b916f4be85294383b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a36f697a05ee3a6dc4fdb62809cf0e78
    md5: 4a55963540f9f9f5bcc0525bfd702bda
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 92015f66bdabf2e9f7d1c09a0a15d2f3
    md5: ac28881ab08f72bea004acc760d990b3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_tracer.res
  hashes:
    binhash: b29ad52ddc377c3eb7d5556958f314d1
    md5: fb4e396a5f180c5137ef2d4dc610c425
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d4b13b6263816b0d7a33e2e148380c3f
    md5: d09a290c973d8b9b65c334c47886ff38
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: aaadc68d0e603a0d599a6ffa574900c7
    md5: 412197e819fba22fdf9bc2af7fcdf549
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 13694241174da64834dee9d32fcf52c7
    md5: 3ad6870429d0f1ce9a973f2d7c835685
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart233/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2c47b3beee64b12efce8e67d46b30672
    md5: 15b02373f35dcaac8110feb47ce6dda2
