format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/atmosphere/restart_dump.astart
  hashes:
    binhash: 9979d622b01b3a18d6903b24d17bf51e
    md5: a60c67e6501b882ad21eefcbb16edc2e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/atmosphere/um.res.yaml
  hashes:
    binhash: 117416b4645a0323bae584bc1e5a8ea0
    md5: 0eeceb72c191c249d8fb97f68d284c13
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/coupler/a2i.nc
  hashes:
    binhash: 5ed42f3cdc31e3181440f94da95b8653
    md5: 2a9d5c7f1fd3fbd69c87b5041bb1da17
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/coupler/i2a.nc
  hashes:
    binhash: 4f6313d971e53b44f837e874575346e0
    md5: eb7e33eee77980362ee346096923cfe0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/coupler/o2i.nc
  hashes:
    binhash: 8c58042bd4b87c85fd11ab4a85869266
    md5: d2fca7414e985bced8f7c50a9f9f9d9b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ice/cice_in.nml
  hashes:
    binhash: acc350f1e1a4cce9521b2633f5cfa232
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ice/ice.restart_file
  hashes:
    binhash: bc50531a63ad595e96a66a724627395c
    md5: bfef0b7801f83b785f1cf04ede335226
work/ice/RESTART/iced.2827-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ice/iced.2827-01-01-00000.nc
  hashes:
    binhash: fa2438bf8443ccd74296a0935276f822
    md5: c55fffca6464d2fd0f0446d03e322844
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ice/mice.nc
  hashes:
    binhash: 2f42413b25f6625fa7051e54c58594c3
    md5: a9249622716fa64f83624c98bcaf20d2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_age.res.nc
  hashes:
    binhash: de4c2486536331ece1ef93eedb8d24f6
    md5: f4a4ba94414a8ab80e50630b13d55573
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0c258de84f9d7c67ebced8170867284d
    md5: 8817ab1841ab9a82f2c654a5f443e1d9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c05fad19b6b9b19cefe655c98600e081
    md5: f097b11fca32ec10e2338a4af2a12f1c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_density.res.nc
  hashes:
    binhash: ad00d56c7300c3faa037149bb0fe7ba8
    md5: 477a28e2c2a9fd5959ac9a2de8114ad6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9facb29df40473a8c3ca875a8be0ba15
    md5: 184466208fa147e514129b0e22009444
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ae18e7b082e4e6960f59290d71d87092
    md5: fecc424362dadfafbd3de196af44820b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fd8e108bfd33d9c6acd0c571c9778d66
    md5: b8deb15ec026d9cfe6d9b46e604286b0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3867abcc179b9e6cafcf9bd096dbf719
    md5: 5edf245f96ab5745e49c6d0465c09339
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9843f8a9eb32a177ac58d33f68142b56
    md5: bc288225a6430f1868dee4a0dd4cfd3e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c7ffb558c79a0f720a8226bfa374040e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_solo.res
  hashes:
    binhash: 4b16f0a03e7d662d0c8739a78f43a3b5
    md5: 12caedf34ee56c849eba7fa6bf65932d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0f8d8de97b4cfb3ff264a39574321318
    md5: 0caafa3f7baa96c2f0f4ef1347a20821
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9e5df4bbab352671d2eeeacd81e44f0e
    md5: fe83c64f01214859aa98213514b24a80
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_tracer.res
  hashes:
    binhash: 79321be98e7a73a0d3b661d5b04eb058
    md5: f78a1b84146943a4a91dba1898955c82
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e665e61fb0129e708cadd0ba4ce5ccf6
    md5: b4b791ff05eea457b0102cf57106e54d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c192096e5a45860a93784320b92b8acb
    md5: ad9734124041e967403c48c5a558d960
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a9ff64371e4f94af93c3d51637135f6d
    md5: 907db1ffeee09c1452556a4a9b639ae7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart150/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5ef41c5392ee6bb77d0fe5a4ed057e7f
    md5: ba642df8af13ae09dc081deab72c5c05
