format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/atmosphere/restart_dump.astart
  hashes:
    binhash: cf67a10bf555c564b654d09a8af6382a
    md5: 0aa154a9613caef35d6b864163dab102
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/atmosphere/um.res.yaml
  hashes:
    binhash: 787875982bfdf8e280288ba7623436ea
    md5: 226311ffbbabcbe1c54661e2c703cc92
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/coupler/a2i.nc
  hashes:
    binhash: a48613e1aec18f9f44d4e0000eeb5d97
    md5: 8f1dc48493ae2985e48d0658a23ff30b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/coupler/i2a.nc
  hashes:
    binhash: b44460c16393a965b786f5e55c11f34b
    md5: 4897007363cd8feb2d919968382dd191
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/coupler/o2i.nc
  hashes:
    binhash: ed2a13837cb0fc04535a7d1fd1fc4a82
    md5: 301ec4b6c6ec28ea43934da7bee6d0c3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ice/cice_in.nml
  hashes:
    binhash: 371805c3b17a696431c77327feb38e76
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ice/ice.restart_file
  hashes:
    binhash: b68ddcc650262d7d4554a89c886e417e
    md5: 8eb7efcbf442c79f1b41af9e1f6c125e
work/ice/RESTART/iced.2810-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ice/iced.2810-01-01-00000.nc
  hashes:
    binhash: 38fcd91cdca00ea0de6fe54d29e0a170
    md5: 5298d9f8974e9c8e8b38ee0780667998
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ice/mice.nc
  hashes:
    binhash: 2f4e31912c14898b6b47ee2b239ebaf8
    md5: 139a0b256bfe8c63c61f98f8592d1f69
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_age.res.nc
  hashes:
    binhash: ad63b5505ea58a783dcd71bc0f435a1e
    md5: f637e5754fec27d8b26776d4a78151fe
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 137c493e53e4cf93c50e161887bed4be
    md5: 30986d98ea332ab8947d4a5ace118fa6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2e576beefcc615117d0c3b68e558d94a
    md5: 464b2b719d9a09b8288f5be077a3482f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_density.res.nc
  hashes:
    binhash: d163d187a76a72faf26c2cc784844383
    md5: 7bd594cbaa3f693dae5af62f6b366691
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 727d2665bc0637a1ff50db503db3c7d6
    md5: 4e6778d213074d7128f56d54cd9b0aa5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f8d66fbba7eae8e26632aaebc40a7236
    md5: 981f53f0fe8445eb0e19ad69e5af0b9c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fa4583f7ce1ef7802048154c4d902ef1
    md5: f7d90b956ad033378405e7a2098dfe6d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c1509697471b254be6b77271b1b8b05c
    md5: 5fd9a6cd13299ad252810ff626ab030a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 426084bc32dd08f0248899c59d91b801
    md5: 10b889e7fd0eac8115a61bbe3f8b6fab
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7bc96f4b6fa2b25442e1a83f331db088
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_solo.res
  hashes:
    binhash: dca6304c2dae9c86617e8b1bdf143725
    md5: 1f48f310143ccfb47438c30a238f99ef
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 48e61ce7b7a4c30a36fd5dafa23f4702
    md5: 7e1236ecb7ef04b0863ba2c949e92943
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 30dfcad65a26cc9ebfa4a80750104b8a
    md5: bd4af19733888da827355d82b9a0b5de
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_tracer.res
  hashes:
    binhash: 6396bbd906723ddbb5c17b3577796161
    md5: 51ed325f4339d594c34187bd569682a4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1ed1e945406ddf03b723e2fb847a859e
    md5: afad46ee9d3b4e649e2cdb832c36c761
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fecee0949b52f331f3410b3bb23c25f6
    md5: bc45a7a39eb375eeeb36e787fae19d65
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 785b455168d084be362812f6b81f8d52
    md5: bee580be530f41542366d83cce40675c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart133/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a15db60f7d82f1db0ffe36a9ca2c1452
    md5: 9035c19de5d6788172e945d46e003498
