format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/atmosphere/restart_dump.astart
  hashes:
    binhash: 2b67bbed61259f5184a07ee633239836
    md5: c170b945e67edaf647b76e5716b94b93
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/atmosphere/um.res.yaml
  hashes:
    binhash: f22b1e78cc074df356e512610d6671fe
    md5: 8dd663825cbbf57e6b9975d5550d9901
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/coupler/a2i.nc
  hashes:
    binhash: e42f1d29985b96c4505e1c86cda13c67
    md5: 50e23eb6f02e83e4efe12e9ff9315adc
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/coupler/i2a.nc
  hashes:
    binhash: 9f7afad177d6e4357152351629c66edf
    md5: 6bbbbfb90170b50a29be325f292c7859
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/coupler/o2i.nc
  hashes:
    binhash: 2e3256ef095a62e467723496c001232e
    md5: 38a5ee7a550db17790fc057f2294bb49
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ice/cice_in.nml
  hashes:
    binhash: b33733cdcba0e15e3339c72537e14f51
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ice/ice.restart_file
  hashes:
    binhash: 69e4c7e402525e8e283f776a13022864
    md5: 1b11dfa2c93b4a2bc9b76aee4222c81f
work/ice/RESTART/iced.2695-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ice/iced.2695-01-01-00000.nc
  hashes:
    binhash: 883ee1332301e47f9c9aae2f22c9d65d
    md5: 145acf828000d1c9cf582aa9938a6b62
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ice/mice.nc
  hashes:
    binhash: cf104bdad84729ad7c87c75ddacc4595
    md5: afeba3fd33348594ebaab3ea5277dc11
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_age.res.nc
  hashes:
    binhash: 9c4640f4d71cf2e59714900d25413139
    md5: 08a1794cb908a30386d7b2834eda3e04
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6e553d645f7b53c0806a2591dd4c41c8
    md5: ab208cdc00440c4a424dd622fdd6ffbb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8c0a6154b794197f0f634a0b7f474438
    md5: 240111c5e435d536233493ee8be99314
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_density.res.nc
  hashes:
    binhash: 825c2af8cd3f93cfdaa312a2549062f8
    md5: e3c70af426bf4a2874600347b751141e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fb7cbdf689ab5742af549211e44e6044
    md5: 8bbc6dd1f158efced5fe983406f1ef41
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ea51db1fd61723a347d32a1183e12202
    md5: 59183097122764a471dd6d8082250bd1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a17c9af072d969920154adf000d03206
    md5: 80bf040d04593077642862808dd4ff98
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9f249a5c28d70f21b309675b38ea0f72
    md5: e86097ea5550bd18e2e9064f1f722a20
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 308773518d7e0394d290b3fb5e78f539
    md5: 5f86402ad80928c625278bdd9dc56b8b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ad441d4c6e0d709e6a52e82cef6323b3
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_solo.res
  hashes:
    binhash: cc9b341bfe0c56051665d3346899c5a1
    md5: ccf7e1a39a3bed6dc50c3770521663b0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 415eacf430e3718da91d0b630effe5a1
    md5: b0b03baf34402e741887604232097cb5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 618a4c2285e61d0dd6ea489f38555d77
    md5: 022d83387ec0a34cf67fcae8452638a0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_tracer.res
  hashes:
    binhash: 14db7b31384f05ddcdbefc86e16f643f
    md5: 12890a05c82cf4e34df6a927b5af3086
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 055a0c42c6bd8bdaf119e41d2bfb2bf9
    md5: e0fe1b1be48ba5a77e337d8ca6515c65
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4955ee8d1601a2899fb3b5031291553f
    md5: 43a7327a962134100b311b5843dc68d6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c46886a62847d2af676b6ee98451cb17
    md5: 887764325b481b8a923e8eaccb444f5d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart018/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 81e63582119a32d87c54611c60977139
    md5: 5a27f03b2a94b395d82db825e8745025
