format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/atmosphere/restart_dump.astart
  hashes:
    binhash: 85a4efcc287230db973eba41b4a4853b
    md5: 0be3d6d5cdc57defd1a3cfc52a8522db
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/atmosphere/um.res.yaml
  hashes:
    binhash: c705fafccc1ba91e1c8f45f686093e6c
    md5: 302a270ab66b1128bed3435a9e40ffaf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/coupler/a2i.nc
  hashes:
    binhash: c5d7551281e900d417ef8f62495c03e2
    md5: dfd517d5af106802adf348154e3d7629
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/coupler/i2a.nc
  hashes:
    binhash: 90d894a3151366701b86df4537f809e6
    md5: 7478c33f15c02529a2154e52a831f5a0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/coupler/o2i.nc
  hashes:
    binhash: bf26a82f65154216ecd33910265781a6
    md5: 908bfacaccfea048ad241700eaf3827a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ice/cice_in.nml
  hashes:
    binhash: 8721ea2f32f541b8e2dbd1a77f76ea81
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ice/ice.restart_file
  hashes:
    binhash: 831f4bcb22e2be4d3c61b8854ea95622
    md5: 8d0d825ee4fd78e57eafd2e42c6cdc5b
work/ice/RESTART/iced.2708-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ice/iced.2708-01-01-00000.nc
  hashes:
    binhash: fea5c5a675583b84592e4c8cb9256801
    md5: 3a485b99bb4cc3fc42f5cc7efa4edaf6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ice/mice.nc
  hashes:
    binhash: 21208ef01e25cd850584ccee8daca1a9
    md5: 632f4585e31d869db1587df70c31bb69
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_age.res.nc
  hashes:
    binhash: 141d21fdeae29479bec6861904a45ca5
    md5: eaba9de4f1bd7ef64cc4c68d62814da7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bb17c3fa918a9b4dcf8892c2ddf7aea8
    md5: 433dcd1d8872af2896858758b450a53c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 90e3ace920f5411a8a90d0dd626799df
    md5: e9b5f704d3eaf0ee882aecd6269f9bba
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_density.res.nc
  hashes:
    binhash: bb801ed1c26c7cd5e991a9bb027d7aad
    md5: d10f53c2dbfa01afbf445f8775ea6691
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e6c78fa58809d4a58150b67168156426
    md5: 89641dd809d7c1e57de0f2fd432e86c4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7b66ef74d2897b7889d5a72cc19b1e5c
    md5: f0399dfb99488fa135e0ed8c25df30c2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 196ff4575940f60a1ddfac073f61ee42
    md5: 516e555f27b9e75ada771220c0d8c8df
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 56d1623b8e1f179566c7684f1557a39b
    md5: c609eb549419392dea131884cd100257
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4ad5bd269dfebac71c9198103075db6e
    md5: 4afc249de2e7d49c9e66c598658a2eed
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 652ff27560cebe26dba68fa0d38894fe
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_solo.res
  hashes:
    binhash: ddda61e2c5ab0f11a8adf03a37ffe6d7
    md5: ff99e025aff4e3a55bae5de7b17da85e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 00f8ab72a0358d450758358abfddeaf6
    md5: 50b6ee8d777cba04e7ff93e06e7af750
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0b4a877c661b8b54056edf557f054c93
    md5: d99e6a99170bf8825b1edc3d350eac26
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_tracer.res
  hashes:
    binhash: a463ba843b19c94b69d715a7e14518b7
    md5: 1404e74af9a7d82534424a8f1ed3e839
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a4839ab38b61d69bf4acd777c7ae4939
    md5: 02d4b71bb752d65c0fe57b5de7e7ae8d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: df8c18915311a28b753b85acc1a710e9
    md5: 0e12657438bfa9cacdafcd5700bfa062
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 04b03a6b2e51882f8016c1bce81f2196
    md5: 263fa0d1e06201e64bc1842a6757b8b4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart031/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c9a8bf678b3d258f337dc52df5e5b358
    md5: 6f83c4568538d104f72883195222afa2
