format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/amip+CN/restart/2026.02.25/atmosphere/restart_dump.astart
  hashes:
    binhash: df9b3f9d0970548ea30bd36373a3a702
    md5: ff419a6dc82e287e7f75667483c80f1b
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-esm1p6/modern/amip+CN/restart/2026.02.25/atmosphere/um.res.yaml
  hashes:
    binhash: 205c2fca83d3ea178c192060c5746817
    md5: 2040b7490b72ee39c2693667166461e3
