format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/atmosphere/restart_dump.astart
  hashes:
    binhash: 48fc8c314ec75eeccc899c1303b4de10
    md5: 544dc52d3e95f4ad80bb7a4d852de53e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/atmosphere/um.res.yaml
  hashes:
    binhash: 90a318f5da67e69216f54899a447ae68
    md5: af4bb3d07bd58ce064b521ced5659e78
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/coupler/a2i.nc
  hashes:
    binhash: e8f8b4a8deb85326b68fb6019dfb4da7
    md5: e6b7f41ecc80ce81c006df762591e4c8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/coupler/i2a.nc
  hashes:
    binhash: 497cc02452dfe0578b656a8e6eca21d0
    md5: 75c99de1068edf57af1df9e9b88953b7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/coupler/o2i.nc
  hashes:
    binhash: 0eb367579117b4bb363479419a780697
    md5: d3a3bd9cddf4dd3b9af50e38274c3598
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ice/cice_in.nml
  hashes:
    binhash: 8bd32416b73085692b9dfe310cf8dd47
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ice/ice.restart_file
  hashes:
    binhash: 64e1c2df00e0abebd378902c32e03961
    md5: 435d7967a9436b88ef248dc8a3c42b83
work/ice/RESTART/iced.2955-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ice/iced.2955-01-01-00000.nc
  hashes:
    binhash: 9a1d5b5e2b7bbc1732ecb19a0740d0b0
    md5: 8fad4e847325bb2422dcad71c618910e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ice/mice.nc
  hashes:
    binhash: 602d358679589cb91d81db5b560da86b
    md5: b82be158959c55a1b38929d99dd8d4cf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_age.res.nc
  hashes:
    binhash: c1daafd1cdba93ecb999745fe00f5bc4
    md5: e277eb5cdeb402c87c37a931d2939ca5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 07f63e841b420fca41063600ff727779
    md5: ef3bdbcf5a9e099cc8a4ef23f4e7a84a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fd7912591fb6a62e203a02813cf3c8cc
    md5: ad9f787c6cb6021a473a279719c5b068
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_density.res.nc
  hashes:
    binhash: 0ef3ff4409cab9e2f76dad7f5c732fd0
    md5: 6a5c63b4527084259b3f53e4d5437d9a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b01b90ab12609e55dbf41165d628a411
    md5: 4f7e8f03c2226973ca9c7e51c67496ee
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 66becfaa1d8f2148bdf0c57c6cc562ae
    md5: ec131c95636b3a8bb1e91a3790b8d6ba
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_neutral.res.nc
  hashes:
    binhash: df1af6ad8ee2c8f29d75378d7efe2c80
    md5: e6169594bb10f1a08e455ea3e71f6461
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: da7a5537ec9a85897fcc4be7c96516bb
    md5: b6ae412ebaf7015a4ea672056e63fb69
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1d016b8d5f16df0b9a8e0563ec0ac72e
    md5: 5a0a471e305f93179ec6330f4372ba8d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: dc324a957445865548599990ba0483cf
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_solo.res
  hashes:
    binhash: aeb63a9e21359d5e635d7d7abaa3679c
    md5: aa6937b442acb73b0bce6b063d7630dd
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a556307e484e6ec0567edfebb53e29d2
    md5: 8ceb8841c3ed6dc0dd25a1958a69fa54
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c65b57d9ca4301edab2f48d4455ecbc9
    md5: 8bd1063f174022e291fc9fcb3ec26050
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_tracer.res
  hashes:
    binhash: e22b2ed8ed24de16efd48d6fb6c8ed30
    md5: 3a0fc3b20d2347278725a0371d037fb7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_velocity.res.nc
  hashes:
    binhash: abd9ac621f4c34be463bb8e8cc751ab3
    md5: f332eaec858b54d62941bf1cc2cca64e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c5b74338ed4b784425d45329d30ec716
    md5: 07c55700d8218234d203ec6e60d6fba3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 11aee7863a20a6ef61409de97bfb96cd
    md5: 2db9c6a8df4e3ca831d59f7a8206f6f7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart278/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 039b302ae4249ac2127f2b0f28d20004
    md5: 101f42395d66e46234e845d9490507a6
