format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/atmosphere/restart_dump.astart
  hashes:
    binhash: b29b4095ce28fb51daff634d3b475eb6
    md5: d3c990fa427983ec284beb6a2613a677
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/atmosphere/um.res.yaml
  hashes:
    binhash: fe6c5a82c86634fdd90c4efd7c0fdec8
    md5: 62ff901173563fb997a8475483a26b49
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/coupler/a2i.nc
  hashes:
    binhash: 1bcdd3bf36b6144278e4d42a2cfff586
    md5: 48c39f463d4c2b8f309aa0958e2f791d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/coupler/i2a.nc
  hashes:
    binhash: 49fee67a5eba230a78bb4bc465a68cad
    md5: 768c95695d6d322877f4b4e2d55a611a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/coupler/o2i.nc
  hashes:
    binhash: 2f4773634fd314cf29429576f4c3523d
    md5: bfa43b3b34ba4c10448253204ae22d44
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ice/cice_in.nml
  hashes:
    binhash: 8096b3f102aa8e39a02733d6fe4a9a65
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ice/ice.restart_file
  hashes:
    binhash: 06bc4dd9ca61ff5a70a48f325324d82b
    md5: fee5147a1f5a04e18805bff36429b9fb
work/ice/RESTART/iced.2795-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ice/iced.2795-01-01-00000.nc
  hashes:
    binhash: c14c31b50d15b60e68da3970328ead45
    md5: d4d49901a22dd478d0300147336cadb2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ice/mice.nc
  hashes:
    binhash: f664c1e1d8a3f114766446c6c1c75bd2
    md5: 94c1e5f4c3dd5605834a91631dfa181e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_age.res.nc
  hashes:
    binhash: f14ce5a6cf6d7bd397c98e71c58d6819
    md5: caa23f6df22ddb713ad73b7d287f2412
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a4db84829fc7491b97fbe25c1c261eee
    md5: a652e7fb7eb90f4c0b45159049d3e5c7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b85a4bf22930406570894d4af76b8501
    md5: ded656d3508700c619dee6c6bd86706d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_density.res.nc
  hashes:
    binhash: 4d10fea161a451a270a77e851fd1dbbd
    md5: 71b6220bcddad948de02ff760e016dc8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9688ca40f58540df7a048bd76621aeb5
    md5: a6e4d9f28871f4a6f9b48f7dabd758b8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 12bbb1c141382b232c6e9cfb3a280bb9
    md5: b4a0597c3a8c8f63cff9ff6fb9ede7d2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0283c6bbcc52d520a809b96e937d4a94
    md5: 1c2a653ff6971098aeff47cb5c77975d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 94764dcefbbbe4a592abf148d255940f
    md5: 9b1947c9f1421c9d0aa79a6728d3cf2e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8b5235268411498742c27ad8ffaada17
    md5: 8a28656015042c61c61435a03683dea9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4d7dad679ae4106864e35868a8d93d76
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_solo.res
  hashes:
    binhash: 7914a0a01982cc8a01fba3e56b3e02b3
    md5: 75be9bdc209d5a2d995195eb8ecaa319
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a664f7e453fd551aae2a3050524fdd45
    md5: 805de8c3648c776996cbe4ef6b2045e6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f4985cef45a6f18a088bff46155c234c
    md5: b32ebcc98e85c5adaf7296892d22b2f2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_tracer.res
  hashes:
    binhash: a7f697ceb81dec001ae55b2eee0e698b
    md5: 7e076f8acb92f6a24fb25478487eb509
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_velocity.res.nc
  hashes:
    binhash: fd226c1335c97b4fd5a3f88ae18f3a0c
    md5: c137cd9658930f3f4266572f4cc5adb2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6314df1cf5633c3c8d4938b95ca5f233
    md5: 53229978fe33a0ecac41c20f85f565ec
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 37f88554647eb551ead3c6ddb4ec784e
    md5: 9f75e9afa76a28ee39d4d109ec96c76a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Dec25-spinup-Dec25-spinup-87bd039c/restart118/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e501ffea3bbf4fcd017a030eca143c02
    md5: f4a15ec392e35eae9f3be680316cbbca
